### ISSUE TITLE
IP tagging filter

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1001]
@junr03 @ccaraman can you add general description of what we are doing here in case anyone has any comments on the plan. Thanks.

**Comment by ccaraman** [comment]
# IP Tagging filter config
IP tagging data will be stored in the envoy config as a part of the HTTP Filter config. It is installed as a part of the HTTP Connection Manager filter chain. 
```
{
  "type": "decoder",
  "name": "ip_tagging",
  "config": {
    // (optional, string) The type of requests the filter should apply to. External, internal 
    // Or both.
    "request_type": "...",
    // (optional, array) Specifies the list of ip tags to set for a request.
    "ip_tags": [
      {
        // (required, string) Specifies the ip tag name.
        "ip_tag_name": "...",
         // (required, list of strings) A list of IP address and subnet masks that will be
         // tagged with the ip_tag_name.
        "ip_list": []
      },
    	...
    ]
  }

```

# HTTP IP Tagging filter
### Maintain the IP Tags
When the IP Tagging filter is loaded, a level compressed trie(LC-trie) will be used to maintain the IP addresses and the associated tags. I will use these links for reference: http://www.drdobbs.com/cpp/fast-ip-routing-with-lc-tries/184410638 and
https://raminaji.wordpress.com/lc-trie/

### Internals of the filter
When invoked, the trusted address from XFF will be used as the search key in the LC-trie. 
The tags will be stored in a requests in the header `x-envoy-ip-tags` as a comma delimited list. 

Note: All applicable tags will be appended to `x-envoy-ip-tags`.

**Comment by htuch** [comment]
@junr03 @ccaraman It would be helpful to have the trie somewhat generic/reusable in some other contexts. In particular, I'm thinking that in the v2 LDS API, we have a notion of multiple CIDR ranges in the `FilterChainMatch` table (see https://github.com/lyft/envoy-api/blob/master/api/lds.proto#L73). We'll want to do longest prefix matching against a set of IP ranges there, so hopefully the trie implementation you add here can be placed somewhere and type parameterized to support this.

**Comment by brian-pane** [comment]
I was just thinking about how to use this filter in a route matching rule.

If a route wants to match on IP tag `example`, it needs to use a regex like `(^|[ \t,])example($|[ \t,])` because the tag could appear in the start, middle, or end of a comma-delimited `x-envoy-ip-tags` value.  (I _think_ that's the right regex, based on HTTP's [grammar](https://tools.ietf.org/html/rfc7230#section-7) for comma-delimited header values.)

Also, the implementation needs to remove any `x-envoy-ip-tags` headers received from the client, to prevent a trivial bypass of IP ACLs. And it probably should prohibit the use of commas and whitespace in tag names, too.

Given how brittle the comma-delimited string representation is, my proposal is to _not_ encode the matching IP tag(s) as an HTTP header, but rather add a new field to the `RouteMatch` proto:
```
// Specifies the set of IP tags on which the route should match.
repeated string ip_tags = 8;
```
and let the implementation represent the matched tags internally as a `set<string>`.

**Comment by mattklein123** [comment]
@brian-pane that sounds reasonable to me. As a companion change, we likely want to add the IP tags to `RequestInfo` also for logging, use in matching, etc. cc @ccaraman

**Comment by brian-pane** [comment]
I created data-plane-api PR #503 based on my proposal. It also moves the basic CIDR-to-tag mapping out of the HTTP-specific part of the v2 schema into the core, in support of two potential future use cases (outside the scope of this issue) : IP tagging support for protocols other than HTTP, and a new xDS type for dynamically loading IP tagging configs from the control plane.

**Comment by brian-pane** [comment]
@alyssawilk I think this got closed as a side-effect of the merge of #2614. There's still another PR or two need to finish this feature.

**Comment by alyssawilk** [comment]
Ah, I guess partially fixed gets regexd as fixed :-)

**Comment by mattklein123** [comment]
@ccaraman @brian-pane I'm going to go ahead and close this as fixed. Nice! Let's open fresh issues with specific enhancements/follow ups.

**Comment by rgs1** [comment]
@mattklein123 @ccaraman dropping super late to the party (sorry), just to clarify: 

@brian-pane's original concern of removing `x-envoy-ip-tags` so that it isn't used to bypass ACLs wasn't addressed, right? Took a quick look at the code/docs and couldn't see it being done.

If it hasn't been addressed, I'll follow-up with a PR to fix that if it can be done cleanly.

Also, are `x-envoy-*` headers special in any way (as in, can't be set by downstreams)?

**Comment by mattklein123** [comment]
@rgs1 if it wasn't sanitized, we should add it to the sanitized list (see code and docs on sanitizing). Unfortunately there is no hard rule with x-envoy-* headers, as some can and are set by downstreams.

**Comment by ccaraman** [comment]
@rgs1 @brian-pane and I had talked about that offline. Apologies for not updating the comment here, what we were going to do at Lyft is add x-envoy-ip-tags to the list of headers that are [internal_only_headers](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto#routeconfiguration). There are cases where you'll want to keep on propagating the headers and appending to it. If that solution doesn't work well for your case, we can talk about adding a flag to sanitize the header for the IP tagging filter.

**Comment by rgs1** [comment]
@mattklein123 something like https://github.com/envoyproxy/envoy/pull/3191 perhaps?

cc: @ccaraman @alyssawilk
