### ISSUE TITLE
[API] Breaking change with RFC header constraints

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#10318]
This PR https://github.com/envoyproxy/envoy/pull/10093 introduces potentially breaking RFC header validations on header-related fields. 

Previously, Envoy code uses debug `ASSERT(valid())` on these fields to guard only against `\r\n\0` characters in headers. However, previously API valid configs may have header related fields that didn't have these characters but were not RFC compliant, These would now be broken because of this. 

This is a tracking issue for the work:
- [x] add an Envoy specific header validation to PGV mimicing `valid()`
- [x] replace the validations in the PR to that validation
- [ ] mark fields as deprecated and add a replacement field that is validated.

**Comment by alyssawilk** [comment]
@asraa thoughts on assigning this your way vs help wanted vs leaving as is?

**Comment by asraa** [comment]
Assigned to myself, thanks! I'm on my way working on it :)

**Comment by asraa** [comment]
@antoniovicente @htuch The last point on moving forward is still outstanding -- what do you think? Keep header validations as-is? Do a giant deprecation/replacement to RFC compliant HeaderStrings?

**Comment by htuch** [comment]
My $0.02 is that we do a giant deprecation. The way I think this could work is that we introduce a runtime option (default existing behavior) and we add a recursive traversal via reflection (similar to `checkForUnknownFields`) at config ingest. This would enforce the stricter requirement beyond what PGV does when it sees a weaker PGV header annotation. Then we can replace this with pure PGV after the deprecation period.

These reflection based traversals can be expensive in terms of CPU cost, but since this is only for a bounded period of time and we have so much other protobuf overhead going on, it might not be too bad from a marginal overhead perspective.

**Comment by antoniovicente** [comment]
Can we figure out a way to runtime guard operations done by PGV?  Or have a way to instantiate the validator in 2 different ways, so we can select weak or strict based on a runtime guard?

Possibly related: https://github.com/envoyproxy/envoy/pull/11058

**Comment by htuch** [comment]
How general do we need to make this? If it's just for the headers, I think we can have Envoy do some reflection based weakening/strengthening of the constraints on config ingest, and use the internal runtime guards for this. If we foresee a general need for this, then, sure, let's design this into PGV, but that's a reasonable project and we should file something at https://github.com/envoyproxy/protoc-gen-validate/issues.

**Comment by asraa** [comment]
If i understand the intent of #11058 correctly, the annotations appear only as documentation, and not as actual validation, so I don't think that we have any need beyond headers. If so, field traversal with reflection is probably the way to go. 

I can tackle after exception removal/when there's some spare cycles

**Comment by antoniovicente** [comment]
We may want #11058 to extend to validation eventually(requiring some fields be set, or using different defaults), that's why I mention it.
