### ISSUE TITLE
Redis command CLIENT SETNAME support

### ISSUE THREAD

**Issue by aviramha** [envoyproxy/envoy#10402]
*Description*:
When using envoy as Redis Proxy, it doesn't support the client setname command.
I propose two options (maybe implement both):

- Support of the command coming from the client and proxying to the server, also setting next connections with same name
- Set the client name in the envoy configuration.

I'm considering sending a PR, would like feedback before doing so.

**Comment by mattklein123** [comment]
cc @envoyproxy/redis-dev

**Comment by aviramha** [comment]
Would my PR be useless without prior feedback?

**Comment by HenryYYang** [comment]
sorry for the delayed response.  Since envoy proxy multiple downstream client connections to the upstream Redis server, this is potentially confusing if it comes from the downstream client. 
 I think options 2 and only option 2 make sense in the current context, you can follow the example of how AUTH does it.
