### ISSUE TITLE
better insights into time spent in HCM filters 

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#10530]
I am currently debugging potential slowness in the gzip filter (see also #8448) and there are no -- afaik -- stats to know how much time is spent on each filter like the `upstream_rq_time` percentiles we have for upstream clusters.

At the very least, I'll come up with a PR to do this for the gzip filter. But I am thinking that a generic mechanism to measure time spent in filters could be very useful for debugging perf issues.

Thoughts?

cc: @mattklein123 @dio @fishcakez

**Comment by mattklein123** [comment]
I'm not sure if we want stats here or perf hooks? cc @jmarantz as our perf expert to advise.

**Comment by jmarantz** [comment]
If you can tolerate rebuilding Envoy to take these measurements, you can use https://github.com/envoyproxy/envoy/blob/master/source/common/common/perf_annotation.h which would enable you to hand-instrument the code to collect very targeted, annotated information, e.g. round time taken in each method in each filter, broken out by e.g. URLs or clusters or something. Those are hand-instrumented as macros that compile to nothing when not enabled on the bazel command line.

That would likely add sufficiently little overhead -- say 10% depending on what you annotate -- that you could run it on live traffic for some amount of time, until you collected all you needed.

Or you could simply run the code under callgrind or cachegrind but that's probably only appropriate for synthetic traffic due to the overhead?

And then a third option I can think of is to add stats for each filter, and leave those in the product permanently. These would give less detail than perf_annotation.h but could run on live traffic forever, be incorporated into monitoring, alerts, etc.
