### ISSUE TITLE
Add runtime flag to make Weighted Least Request LB behave like Weighted Round Robin LB in weighted mode

### ISSUE THREAD

**Issue by gkleiman** [envoyproxy/envoy#10602]
At Lyft we use Envoy to red line test/squeeze a single host of a service. Red line tests are performed by increasing the load-balancing weight of a host via EDS  to redistribute the service traffic and send an increasing amount of the traffic to a particular host.

While this approach works great in many cases, we noticed a few problems:

1. For some services there is a limit to the amount of traffic that can be redistributed to the host under test. This happens even when the service is getting a considerable larger amount of traffic.
2. The amount of traffic that is redistributed to a particular endpoint and its load-balancing weight are not always linearly proportional.

After doing some experiments we arrived at the conclusion that these problems happen because our clusters use the [Weighted Least Request (WLR) load balancer](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#weighted-least-request). 

Currently if two or more hosts in a cluster have different load-balancing weights, the WLR load balancer shifts into a mode where it uses a weighted round robin schedule in which weights are dynamically adjusted based on the host’s request load at the time of selection (weight is divided by the current active request count).

For some services the number of active connection to a host increases as that host gets more traffic, even if the host is not overloaded. This causes both aforementioned problems.

The [Weighted Round Robin (WRR) load balancer](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#weighted-round-robin) does behave as desired for red line tests and we would like to switch a cluster to the WRR load balancer while running a red line test. However this is easier said than done — a cluster’s load balancer can only be changed via CDS and doing so makes Envoy drain and reconnect all existing connection pools [[1]](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration#cds).

Since the behavior of the WLR load balancer is non-intuitive when two or more hosts in a cluster have different load-balancing weights, I propose adding a runtime flag that would make the WLR load balancer behave like the plain WRR load balancer in this scenario.

This means that if the runtime flag is enabled and there are two or more hosts in cluster that have different load-balancing weights, the WLR load balancer would not dynamically adjust the host weights based on the host’s request load. It would instead calculate the host weights using the same calculation used by the WRR load balancer: `host weight / sum(host weights)`.

**Comment by htuch** [comment]
@gkleiman for red line testing, why isn't it acceptable to do a CDS update with drain? This seems like something that is done relatively sparingly, so the impact of the drain and delay might not be so bad.

**Comment by mattklein123** [comment]
> why isn't it acceptable to do a CDS update with drain? This seems like something that is done relatively sparingly, so the impact of the drain and delay might not be so bad.

I don't think the CDS drain is a big deal. The main issue is the required control plane complexity is actually really large to implement this (start RL test, wait for CDS swap, verify swap is done, start test, swap back, etc.). I discussed this with @gkleiman before he posted this and from my perspective I think the use case here is reasonable/common enough that a config option for this on the load balancer is reasonable, thus making the behavior opt-in. @snowp any thoughts here?

**Comment by snowp** [comment]
I think config flag + runtime flag makes this ok - the config flag seems to be necessary since we avoid creating the EDF scheduler for memory reasons when all weigths are the same. 

The CDS approach is definitely more involved - you'd probably need to hook into CSDS to poll for the cluster to no longer be warming (or perhaps there should be a more ergonomic feedback mechanism for cluster warming completing)? In general it seems like updating CDS is the more natural solution to this problem, though I can understand wanting to avoid the complexity.

**Comment by tonya11en** [comment]
The reason WRR behaves as expected in the Lyft redline tests is that the weights directly correspond to the proportion of traffic delivered to an endpoint. The weight normalization that WLR does based on outstanding requests to an endpoint causes the subset of nodes we'd like to squeeze to have a much lower effective weight as they actively juggle more requests. I think this behavior doesn't warrant a flag to disable, since you can still get the desired effect in these redline tests by increasing the weights to higher values, they just won't be directly proportional to traffic volume.

Keeping the existing behavior also has the added bonus of working for heterogeneous clusters. Adding a flag to drop the "least request" behavior in the WLR LB could result in other unintended behaviors in those environments since there is no visibility into the what the effective weights are after normalization of what was configured.

These subsets of nodes under test must be monitored for some kind of stopping criteria (via automation or manually), so I see no reason the weights have to be at specific values rather than "discovered" through gradual increasing until the stopping criteria are reached.

**Comment by mattklein123** [comment]
> I think this behavior doesn't warrant a flag to disable, since you can still get the desired effect in these redline tests by increasing the weights to higher values, they just won't be directly proportional to traffic volume.

I disagree. I think if this feature is added it should be an explicitly documented configuration flag. This can however be `RuntimeFeatureFlag` or similar to allow for full flexibility.

**Comment by htuch** [comment]
The justification for runtime flag over CDS seems reasonable, but it left me wondering about how general this is. It's pretty coarse grained; aren't you worried about the impact on unrelated clusters? I think this is another justification for config flag.

One other concern is that this seems very special casey; it's basically a runtime flag for Lyft's load tests. Is there any way this could be made more generally useful? Maybe mark clusters as eligible for runtime override of their LB type and then supply the name of this LB in a string? The problem there is it probably gets complicated as you need to do a full cluster rebuild an drain etc.

**Comment by mattklein123** [comment]
>  I think this is another justification for config flag.

If we do this I think we should absolutely use a config flag that also allows a runtime key to be specified. This is the best of both worlds.

> One other concern is that this seems very special casey; it's basically a runtime flag for Lyft's load tests. Is there any way this could be made more generally useful?

We have gone back and forth on this. I agree it's a special case, at the same time it strikes me as a reasonable one as this is a known issue with trying to do stress/RL testing with the WLR load balancer which many/most people use in production. As such I think this is a reasonable feature to add as long as it is clearly documented. Definitely willing to be swayed otherwise though.

The long term solution that we want is I think the following:
1) Finish the extension LB ticket so that we can easily add extension LBs that can be compiled out.
2) Add what I have been calling the "overlay LB" which would have its own configuration API that would allow overlaying host weights and LB policies on top of the default config (or in place of it). This would allow us to fully solve the "override a host weight" federation issue in a pretty clean way IMO.

^ is obviously a lot of work and we felt this was an OK intermediate solution as it's trivial to implement and easy to understand if well documented.

**Comment by htuch** [comment]
I'm good with this plan.

**Comment by gkleiman** [comment]
@tonya11en I've experimented with increasing the host weight, but it hasn't helped with services that don't get enough traffic.

Per your suggestion on https://github.com/envoyproxy/envoy/pull/11252 I'm working on making the LR LB use the following formula to calculate the host weights when not all weights are equal: `new_weight = (configured_weight / outstanding_requests^k)`.

I'll try that change internally and then follow up here once I have the results.

**Comment by gkleiman** [comment]
@mattklein123 / @tonya11en:
I verified that https://github.com/envoyproxy/envoy/pull/11252 has the desired effect in Lyft's infra during a squeeze/red line test.

The patch makes the Least Requests LB use the following formula to calculate the host weights when hosts have different weights:

`weight = host.weight() / host.active_requests()^<active_requests_exponent>`

When `active_requests_exponent == 0.0` the WLR LB algorithm behaves like the Weighted Round Robin algorithm and yields the desired behavior during squeeze tests.

When `active_requests_exponent == 1.0` the WLR LB algorithm keeps the current behavior.

The current patch makes it possible to change via a runtime flag the active requests exponent for all clusters.

I propose updating the patch to remove the runtime flag and to add an `active_requests_exponent` field to the [`LeastRequestLbConfig` CDS protobuf message](https://github.com/envoyproxy/envoy/blob/2b83bc999036086cbc4f69e084dd85ae50d7f620/api/envoy/config/cluster/v4alpha/cluster.proto#L313-L321) with a default value of `1.0`.

At Lyft we would change our CDS management server to set `active_requests_exponent = 0.0 ` for all clusters.

**Comment by tonya11en** [comment]
Sounds like a good approach to me. Update the draft PR with these changes and I'll take the first few passes on the PR.
