### ISSUE TITLE
http/2: implement push promise and link header following

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1070]
cc @htuch @tschroed we are going to do this for Lyft use in Q3 FYI. Let us know if you have specific requirements.

**Comment by htuch** [comment]
@alyssawilk

**Comment by tschroed** [comment]
If it would be useful we could probably arrange some VC time for your folks to chat with our folks who have relevant experience and ideas.

**Comment by mattklein123** [comment]
Sure sounds good re: meeting over vc.

**Comment by espectro** [comment]
Hi
we are making H/2 server push from golang backend and  getting 
>>> Failed to push: feature not supported

Is feature not implemented still?

**Comment by alyssawilk** [comment]
Yep...  I suspect there will be Envoy support at some point, but it may be a while, and first pass support might be accepting a header from upstream to push a given resource downstream, rather than accepting upstream-initiated streams.

For what it's worth I've seen 5-10 attempts at teams and companies using server push and each one gave up on it as not worth the latency benefit, but until/if the industry gives up on it I still think we should have support in Envoy :-)

**Comment by alyssawilk** [comment]
Client side metrics show that on the internet server push is used in less than 0.005% of requests.  Fewer than half of attempted server pushes are used (generally the information is pre-cached, there are various race conditions etc.)  Meanwhile overenthusiastic pushing often results in wasted bandwidth and server push doing more latency harm than good, and client side management of regular requests, push requests, push promises etc. often results in subtle bugs and network backup.

Because of this we think server push is more trouble than it's worth, and do not currently plan to implement in it envoy

**Comment by woluohenga** [comment]
Hi, in some occasions server push is necessary. 
If we have some clients connected to envoy by TCP, back end services need send notify to client, I don't know if this can be achieved through envoy.

**Comment by alyssawilk** [comment]
I think traditionally features like this are handled by hanging get, to be compatible with lower versions of HTTP and the fact not all clients support server push

**Comment by woluohenga** [comment]
@alyssawilk Thanks for reply. 
In some business area, such as development of online game（especially FPS/MOBA/MMO，ex COD、LOL、PUBG...), server push is necessary, because the message sent by server to client are send very frequent(almost reach 20-30/s for one client). It's impossible to work if message is only get by client.
Because some of our server deploy in istio now, we plan to discuss if envoy can as a gateway in our game, we expect envoy to play a greater role in this field. But now I don't know how to realize server push easily (we use TCP connetion, not HTTP2 yet). Perhaps I can record connetion info in custom filter, connetion id as key, then upstream push with the key, is this feasible? Or is there more currency and easy way to support this feature?

**Comment by alyssawilk** [comment]
I thought most of the gaming industry used bespoke UDP protocols?  I don't know of any game services which use HTTP, let alone server push, do you have a use case of a customer who actually does?

**Comment by woluohenga** [comment]
Yes, we use TCP and UDP protocols most time. we need server push in these protocols, but I don't find reference of how to push message by TCP\UDP,  I search 'server push' and find this issue, so ask here directly.
In backend server, is there easy way to push message to given client?

**Comment by alyssawilk** [comment]
HTTP/2 server push is orthogonal of raw pushing raw TCP and UDP from server to client.  I think you're trying to tackle a different problem :-)

**Comment by ayroblu** [comment]
Well, it's unfortunate that this feature isn't well supported.
For the record, the value of push is for non cachable assets, commonly data.

Imagine you have a weather site, you send a request for the html, but the html hasn't changed since you checked like 3 days ago, so you can send a 304 Not Modified back, BUT since the weather data must always be fresh, you can send the latest weather report data before the response goes back, and then the client makes a subsequent request to fetch the weather report data.

"Ah, but SSR!" you might be saying, but actually this is the bandaid that the industry has come up with due to lack of server push support. Crude SSR support will always delay by the slowest item. Some of the nicer SSR streaming solutions rely on multiplexing over html. But now you have wasted bytes from non cached html, you have a long lived html thread so you can't use script defer or async, all scripts need to be blocking so that you're not wasting cycles while waiting for resources, you need to compute on the backend and frontend, so duplicating the cost.

Anyways so my point is that specs and protocols are there for a reason, and it would be nice if we actually implemented them rather than looking at adoption curves.

**Comment by ayroblu** [comment]
Hey! Sorry that the tone came across as so negative, but I don't have much clarity on "That feature turned out to not work as well as originally expected". All the discussion I've seen online is from people trying to push some js and css files and how that is a waste of bytes. I'm not familiar with a technical reason at the protocol level that causes this to not work as well as expected, I'd love to get some clarity on this

**Comment by DavidSchinazi** [comment]
Thanks for clarifying. Chrome did quite a bit of analysis on server push and realized that on average it made performance worse instead of better because servers often push resources that the client already has. HTTP [early hints](https://www.rfc-editor.org/rfc/rfc8297) have been found to help more in practice. There are probably some niche use cases where push can be more helpful, but because those are rare it's not currently worth the effort to maintain that code complexity.

**Comment by ayroblu** [comment]
Yeah so this is my point, I want to push non cached resources. Its impossible to hit the case you've described cause we always fetch the data
