### ISSUE TITLE
[Question] Envoy binary size increase

### ISSUE THREAD

**Issue by appario** [envoyproxy/envoy#10801]
We had forked envoy around the v1.11 release and at that time the stripped binary size was around 27M. I recently merged the v1.14 release and noticed that the binary size had doubled to 55M for the same build config. Are there any high level new filter/features that were added in the last couple of releases that would cause such a jump?

@sumukhs

**Comment by mattklein123** [comment]
Nothing specific comes to mind, but that's a huge increase. Not sure what filters, etc. you are bringing in. I would definitely only compile the filters you are actually using. @junr03 has done size analysis for Envoy Mobile and can possibly provide some scripts if you are looking to better understand where size is being spent.

**Comment by appario** [comment]
That would be very helpful. Thanks!

**Comment by moderation** [comment]
I know from testing that the Kafka filter alone adds about 11MB. This is another reason why I advocate for custom builds where only the extensions you need are compiled into the binary (vs. the kitchen sink images / approach).

**Comment by junr03** [comment]
@appario since v1.11 the v3 APIs were introduced. That by no means account for such a big increase, but it does account for a non-trivial amount (for example, it accounts for ~10% of Envoy Mobile's size under some measures).

You could follow the instructions [here](https://envoy-mobile.github.io/docs/envoy-mobile/latest/development/performance/binary_size.html) to do some analysis on your Envoy binary. I have used a tool called [Bloaty](https://github.com/google/bloaty), per the instructions. Bloaty even allows you to compare binaries and see where the increases happened.
