### ISSUE TITLE
How to find BoringSSL version used in binary

### ISSUE THREAD

**Issue by daganibhanu** [envoyproxy/envoy#10824]
*Description*:
I have successfully built the envoy binary using (version 1.10.0 sources ) with the bazel environment that comes bundled as given in the document. (https://github.com/envoyproxy/envoy/blob/1a9f1859fc530ca40cbd66675c4971bb6ed3d575/ci/README.md)

Is there a way where I can know which BoringSSL version is being used in 1.10.0?

can someone help me on this?

**Comment by daganibhanu** [comment]
@PiotrSikora Do you have any idea on this?

**Comment by ggreenway** [comment]
From the same commit you linked in the repo, the following line shows where it is fetched from:

https://github.com/envoyproxy/envoy/blob/1a9f1859fc530ca40cbd66675c4971bb6ed3d575/bazel/repository_locations.bzl#L38

**Comment by daganibhanu** [comment]
@ggreenway I got that, but is there a way where we can get the release version of this boring ssl? please help!!

**Comment by ggreenway** [comment]
I've never looked into how BoringSSL does releases, so I don't know.

**Comment by daganibhanu** [comment]
Apparently there are no "release versions" of boring ssl, any project that uses boringssl is supposed to consume a commit of boring ssl and ship boring ssl along with that project's code. so as mentioned [https://github.com/envoyproxy/envoy/blob/v1.10.0/bazel/repository_locations.bzl] in link `fips-20180730` must be the tag/version.

**Comment by matinats** [comment]
Hi @daganibhanu!

I would like to reopen this issue with a feature request to provide the corresponding BoringSSL version in the envoy --version command.
I opened an issue in BoringSSL community but it was advised to open it here.

OS:
$ cat /etc/system-release
CentOS Linux release 8.2.2004 (Core)

Getting the version from envoy (build non-fips) returns only this:
$ envoy --version
envoy  version: 923c4111bb48405ac96ef050c4f59ebbad3d7761/1.14.4/Modified/RELEASE/BoringSSL

In envoy 1.14.1 github repo this is the BoringSSL URL: https://github.com/envoyproxy/envoy/blob/release/v1.14/bazel/repository_locations.bzl#L38

As stated there:
urls = ["https://github.com/google/boringssl/archive/1c2769383f027befac5b75b6cedd25daf3bf4dcf.tar.gz"],

I would like to see a BoringSSL Version to correlate with the tags in BoringSSL repo in github, or a commit in github because the  hash cannot be found in BoringSSL repo in github:
1c2769383f027befac5b75b6cedd25daf3bf4dcf

I cannot correlate this hash to a BoringSSL version in github.
This is considered a feature and not a bug.
Please advise.

**Comment by PiotrSikora** [comment]
> I would like to reopen this issue with a feature request to provide the corresponding BoringSSL version in the envoy --version command.
> I opened an issue in BoringSSL community but it was advised to open it here.

Envoy has a lot of core dependencies, none of which are included in the `--version` output.

Why version of BoringSSL should be included there?

> Getting the version from envoy (build non-fips) returns only this:
> $ envoy --version
> envoy version: [923c411](https://github.com/envoyproxy/envoy/commit/923c4111bb48405ac96ef050c4f59ebbad3d7761)/1.14.4/Modified/RELEASE/BoringSSL
> 
> In envoy 1.14.1 github repo this is the BoringSSL URL: https://github.com/envoyproxy/envoy/blob/release/v1.14/bazel/repository_locations.bzl#L38
> 
> As stated there:
> urls = ["https://github.com/google/boringssl/archive/1c2769383f027befac5b75b6cedd25daf3bf4dcf.tar.gz"],
> 
> I would like to see a BoringSSL Version to correlate with the tags in BoringSSL repo in github, or a commit in github because the hash cannot be found in BoringSSL repo in github:
> 1c2769383f027befac5b75b6cedd25daf3bf4dcf

It's there:
https://github.com/google/boringssl/tree/1c2769383f027befac5b75b6cedd25daf3bf4dcf

> I cannot correlate this hash to a BoringSSL version in github.
> This is considered a feature and not a bug.

BoringSSL doesn't do releases, so we're tracking versions used in Chromium stable, as explained in the file you linked above:
https://github.com/envoyproxy/envoy/blob/4e5c4b981c99437532ab09d24ff7464ce2772e6e/bazel/repository_locations.bzl#L63-L69

**Comment by matinats** [comment]
Thank you so much for your explanation!
Now I understood how to find the correlation I was looking for.
I had been using the github search box with this commit "1c2769383f027befac5b75b6cedd25daf3bf4dcf" and didn't get any results.
I am stating here the steps for future reference:

1. Find the BoringSSL reference in envoy:
https://github.com/envoyproxy/envoy/blob/release/v1.14/bazel/repository_locations.bzl#L37

        # chromium-81.0.4044.69
        urls = ["https://github.com/google/boringssl/archive/1c2769383f027befac5b75b6cedd25daf3bf4dcf.tar.gz"],

2. Go to https://chromium.googlesource.com/chromium/src/+/refs/tags/81.0.4044.69/DEPS  -> the tag is writen in the comments above
3. Get the revision commit:
'boringssl_revision': '1607f54fed72c6589d560254626909a64124f091'
4. Use github search box to find the commit
5. Show tree https://github.com/google/boringssl/tree/1607f54fed72c6589d560254626909a64124f091
https://github.com/google/boringssl/tree/master-with-bazel

Thanks!
