### ISSUE TITLE
Any difference between max_connections and max_connection_pools in circuit breaker?

### ISSUE THREAD

**Issue by maxliu007** [envoyproxy/envoy#10826]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break-cluster-maximum-connection-pools

About
{
"priority": "...",
"max_connections": "{...}",
"max_pending_requests": "{...}",
"max_requests": "{...}",
"max_retries": "{...}",
"retry_budget": "{...}",
"track_remaining": "...",
"max_connection_pools": "{...}"
}

After reading above documents, I am so confused on when to use the max_connections and max_connection_pools.

Is max_connection_pools bound by max_connection_pools?
If I set max_connection_pools=100, while max_connections=300, what will happen?
If I set max_connection_pools=300, while max_connections=100, what will happen?
Ary they complementary?
With the same terminology, if it is describing a DB connection pool, there will be a parameter to control the connection pool size, e.g. max_db_connection_pool_size. How about for envoy connections? I think that will be max_connection_pools for envoy, am I correct? Then what is the use of max_connections here?

Also, why max_connection_pools is in plural instead of max_connection_pool for a cluster?

**Comment by yanavlasov** [comment]
@snowp mightr be able to clarify

**Comment by snowp** [comment]
For most use cases max_connection_pools won't be relevant and you can leave it as is: generally a relatively fixed, small number of connection pools are used (routing priorities used (max 2) * protocols used * number of hosts). Some use cases might dynamically (mostly custom filters afaik) add in additional connection parameters, which might result in an unbound number of connection pools having to be created (since we do one conn pool per unique set of connection requirements).

So max_connection_pools doesn't have anything to do with  the size of a connection pool, but literally how many connection pools we allow.

**Comment by ankatare** [comment]
@maxliu007 As per doc https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break-cluster-maximum-connection-pools 
The value of connection pools should likely be no greater than Cluster maximum connections. If this circuit breaker overflows the upstream_cx_pool_overflow counter for the cluster will increment.
so second scenarios as you suggested seems not valid.... 
If I set max_connection_pools=300, while max_connections=100, 

please correct if my understanding is wrong....

**Comment by maxliu007** [comment]
> @maxliu007 As per doc https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break-cluster-maximum-connection-pools
> The value of connection pools should likely be no greater than Cluster maximum connections. If this circuit breaker overflows the upstream_cx_pool_overflow counter for the cluster will increment.
> so second scenarios as you suggested seems not valid....
> If I set max_connection_pools=300, while max_connections=100,
> 
> please correct if my understanding is wrong....

Sure according to the doc.

So what is the exact usage on **max_connection_pools** here? Could anyone give a more concreate example as I am really so confused with **connection_pools**? 
Suppose we have only one upstream and with this configuration : **max_connection_pool**=99 (no greater than Cluster maximum connections), **max_connections**=100, what will happen if there are 200 downstreams trying to connect to this upstream? How does **max_connection_pools** play here?

**Comment by snowp** [comment]
Say you're using HTTP/1.1 for all upstream calls: you'll be using 1 connection pool, and it will create more and more connections as it handles more concurrent requests until the max_connection limit is hit, at which point it will enqueue further requests. `max_connection_pools` will not come into play here since it only ever creates one pool.

**Comment by maxliu007** [comment]
Then what changes can bring `max_connection_pools ` into play?
What if it is configured to use gRPC instead of HTTP/1.0, how will that behave? Still only one pool?
