### ISSUE TITLE
conn pool: clean up legacy impl

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#10868]
Opening this to track the removal. I think this can be done since we have cut 1.14 but I'm not 100% sure of the policy. cc @ggreenway @alyssawilk @asraa

**Comment by alyssawilk** [comment]
+1, I think we just wanted to make sure nothing drastic happened during HEAD rollouts

**Comment by ggreenway** [comment]
The other concern was the additional circuit breaker enforcement, and whether that would break someone's config, and it was easier to disable a runtime feature than to fix the config (in the short term).

But we haven't heard any concerns/complaints in this area since the release came out, so I'm ok deleting it now.
