### ISSUE TITLE
[Feature Request] Envoy::Event::Timer::createAlarmer()

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#11059]
It would be great if there was a standard feature for creating a recurring timer, alarmer, whatever you want to call it. This is currently hackable by re-arming the timer in the TimerCb, [e.g. in DrainManager](https://github.com/envoyproxy/envoy/blob/master/source/server/drain_manager_impl.cc#L49), which is difficult to read and requires the timer to be visible to its own callback.

**Comment by alyssawilk** [comment]
Bonus points for a base class where the alarm unregisters on destruction - I'm always surprised it has to be done manually

**Comment by mattklein123** [comment]
+1 to the general feature request.

> Bonus points for a base class where the alarm unregisters on destruction - I'm always surprised it has to be done manually

Note that it actually does unregister on destruction, however many places call disable explicitly because it is easier to mock test. (The underlying issue has to do with nice mocks not being able to ignore destroy mock calls in destructors, so without this pattern it would be a giant pain in the common case.) Would appreciate any ways to make this batter and/or clarify this aspect of it.
