### ISSUE TITLE
Support multiple addresses per listener

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#11184]
Via https://github.com/envoyproxy/envoy/issues/11124. This would avoid mass listener duplication in cases where a listener config needs to be bound to multiple addresses.

**Comment by ggreenway** [comment]
This may be required for some QUIC use cases. If Envoy is terminating QUIC and sets a Server Preferred Address, packets will start arriving on a different listener, but are part of the same QUIC connection. So packets from different listeners will need to go to the same QUIC connection router.

Same story for QUIC connection migration.

This will also remove duplication if both HTTP/2 and HTTP/3 are needed for the same configuration (UDP vs TCP listeners).

**Comment by uablrek** [comment]
FYI the same for `contour` which also uses envoy https://github.com/projectcontour/contour/pull/1162

**Comment by soulxu** [comment]
I'm trying to work out a PoC for this issue

**Comment by danzh2010** [comment]
> This may be required for some QUIC use cases. If Envoy is terminating QUIC and sets a Server Preferred Address, packets will start arriving on a different listener, but are part of the same QUIC connection. So packets from different listeners will need to go to the same QUIC connection router.
> 
> Same story for QUIC connection migration.

I think supporting dual-stack ipv6 sockets and QUIC server migration are different things. The former only needs a 2nd listener with the same config but listening on a different socket. But QUIC server migration requires one connection lands on the same listener. #19367 seems to implement the former, but I don't see how it helps with the latter. QUIC server migration might be easier to implement in L4 load balancer rather than requires one listener to listen on both sockets. Google is planning to experiment server migration, but we don't have a good story to tell yet.
