### ISSUE TITLE
Feature request for router_check_tool

### ISSUE THREAD

**Issue by KenjiChao** [envoyproxy/envoy#11206]
We're migrating our company's reverse proxy to envoy. One thing we provide to our internal developers is a UI to test the routing table. They provide the URL and HTTP method, click a button, and it returns with the resolved cluster and endpoints.

In order to provide the same functionality after moving to envoy, we create a wrapper class for executing the router_check_tool. We need to intentionally fail the test by setting `cluster_name` and `path_redirect` as empty strings in ValidationItem. Then, we parse the error message, e.g. `expected: [], actual: [exemplar], test type: cluster_name`, and populate the information to front-end.

This is not a great user experience, and we can only provide limited information. It's also hard to differentiate between redirect and direct response. If it's a direct response, we don't know the response code.

Is there any plan to support our use case? I imagine we can just provide the input, and get detailed information like the matched route entry and virtual host, and all the response headers.

**Comment by mattklein123** [comment]
cc @LisaLudique who probably has some thoughts on ^.

**Comment by LisaLudique** [comment]
@KenjiChao Just so I understand correctly, there seem to be 2 asks for support:
1) a function/API that given the test inputs returns (information about) the matched route. This is different from the current unit test-based workflow that the route checker tool supports but I think it's a valid use case and shouldn't be too hard to expose since that logic is already built into the tool.
2) adding a check for HTTP response code. This doesn't exist and I agree it would make testing direct response routes more robust.

**Comment by KenjiChao** [comment]
@LisaLudique  That's correct!
