### ISSUE TITLE
Can H2 CONNECT supported connpool be viewed as tcp conn pool?

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#11205]
Thank @alyssawilk for adding H2 CONNECT in both HCM and tcp proxy.

I am exploring if H2 can be used as general tunnel, for network filters other than tcp proxy.

I realize most of the known terminated network filters are using `tcpConnPool` provided by `ThreadLocalCluster`, including `thrift proxy` and `dubbo_proxy` and `rocketmq_proxy`.

If we can provides a `ThreadLocalCluster::tcpConnPool()` backended by H2 CONNECT, where `TcpConnPool::newConnection` is actually supported by H2 connect stream, all these  proxies could transparently use H2 connect tunnel at no cost.

Alternatively, we can also provide a H2 connect powered transport socket but this one might be coupled with existing transported socket.

Does it make sense to you? @alyssawilk @mattklein123 @PiotrSikora

**Comment by alyssawilk** [comment]
Yeah, I think that's doable.
I think we can refactor the code in the tcp proxy session somewhat like you have in your WIP, where we have a tcp-or-h2 pool which takes in config for tcp-only, h2-only, or let-upstream-decide (or what have you) which uses the neutral interfaces in tcp_proxy/upstream.* and use that code for any traffic type which wants to tunnel.

The more interesting case IMO is how we handle that on the far side - muxing over TCP is only useful if you can demux.  Right now, we allow demuxing raw TCP but only sending it upstream, not dealing with it in the Envoy which terminates.  I suspect for this feature to be useful, we'd have to implement the feature we'd discussed several times, taking the demuxed payload and feeding it back to an Envoy filter chain as if it were a new incoming connection, so Envoy could process it as TCP or redis or kafka or whatevever.  Make sense?

**Comment by mattklein123** [comment]
Agreed this sounds like it would work. My only concern here is whether this is too specific to be in the core. I kind of like the idea of this being a transport socket extension, but that would not give you the connection coalescing behavior I think you are looking for on the egress side (since the "TCP" connection would actually be handled by the HTTP/2 connection pool as a stream).

@alyssawilk any thoughts on whether this should be a core feature or if we should add some type of extension point for this?

**Comment by alyssawilk** [comment]
Hm, the original TCP-over-H2 (
https://github.com/envoyproxy/envoy/issues/1630) seemed to have
pretty broad support, so I could imagine it getting decent adoption.  To
me, this is the logical extension - folks will likely want to tunnel
generic things over a prefetched multiplexex connection but treat it as if
it were not tunneled once it lands on a given machine.  That said even if
adoption gets update, there's no harm in breaking it out as a plugin and
making it optional built-wise.  I think if we're going to go this route we
should do it before CONNECT support leave alpha, since it might break
existing configuration.
If we want to go this route, if you are up for syncing on structure on
slack, I can work on moving the existing code over.

**Comment by mattklein123** [comment]
> If we want to go this route, if you are up for syncing on structure on
slack, I can work on moving the existing code over.

Yeah it might be worth a quick sync and/or a short design doc just to make sure we are all on the same page. If we believe this is a generally applicable feature this SGTM I just want to make sure we think through it carefully if we are going to add it to the core.

**Comment by lambdai** [comment]
> I kind of like the idea of this being a transport socket extension.

I wish I proposed this plan. It could address another group of use cases as well. E.g redis cluster and xds which use adopt `ClusterManager::httpAsyncClientForCluster` and `Cluster::tcpConnForCluster`.

**Comment by lambdai** [comment]
> feeding it back to an Envoy filter chain as if it were a new incoming connection

This is indeed useful. It's actually very useful to istio users and developers. People building mesh features wish to work with the mode that filter chain manager dispatched listener and h2 tunnel is the implementation detail.
