### ISSUE TITLE
Admin interface /quitquitquit handler doesn't require POST

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#11275]
Currently it allows GET, which is less secure than POST.

**Comment by alyssawilk** [comment]
Can you give a bit more detail about what you're running into?

If I tweak our QUIT tests to use GET I see

[ RUN      ] IpVersions/IntegrationTest.QuitQuitQuit/IPv6
[2020-06-02 18:56:21.161][744][error][admin] [source/server/admin/admin.cc:680] admin path "/quitquitquit" mutates state, method=GET rather than POST
test/integration/server.cc:226: Failure
Expected equality of these values:
  "200"    
    Which is: 0x669270
  response->headers().getStatusValue()
    Which is: "405"
-- Test timed out at 2020-06-02 18:56:55 UTC --

so I think it does require POST and is working as intended.

**Comment by wlhee** [comment]
Hmmm, you are right, I can't reproduce it.

Probably it's something related to the Google internal envoy admin interface helper.
