### ISSUE TITLE
Aggregate some prometheus stats

### ISSUE THREAD

**Issue by bartebor** [envoyproxy/envoy#11293]
I have a problem visualizing some of the envoy's prometheus metrics in grafana.

Currently, there are metrics like:
```
# TYPE envoy_cluster_outlier_detection_ejections_consecutive_5xx counter
# TYPE envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx counter
# TYPE envoy_cluster_outlier_detection_ejections_detected_consecutive_gateway_failure counter
# TYPE envoy_cluster_outlier_detection_ejections_detected_failure_percentage counter
# TYPE envoy_cluster_outlier_detection_ejections_enforced_consecutive_gateway_failure counter
# TYPE envoy_cluster_outlier_detection_ejections_enforced_total counter
# TYPE envoy_cluster_outlier_detection_ejections_overflow counter
# TYPE envoy_cluster_outlier_detection_ejections_total counter
```
This is cumbersome to visualize, because we need to create separate queries for each of these metrics.
A more convenient way is to use query with wildcard in metric name (via regexp on `__name__` label), but this does not work because of labelsets being the same in all of the metrics (this is the way `rate()` function works in prometheus).

A better, "prometheus way", would be to merge all of the above metrics into one with extra label, like this:
```
# TYPE envoy_cluster_outlier_detection counter
envoy_cluster_outlier_detection_ejections{type="consecutive_5xx"}
envoy_cluster_outlier_detection_ejections{type="detected_consecutive_5xx"}
...
```
This could be also addressed in a compatible way just by adding a label and leaving metrics names as they are:
```
envoy_cluster_outlier_detection_ejections_consecutive_5xx{type="consecutive_5xx"}
envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{type="detected_consecutive_5xx"}
...
```
or even adding whole metric name as a some label everywhere.

PS. There are more such cases, like `envoy_cluster_health_check_*`.

**Comment by bartebor** [comment]
As a workaround, one can use following configuration snippet:
```
stats_config:
  stats_tags:
    - regex: "^().+\\.([^\\.]+)"
      tag_name: name
```
what produces metrics like:
```
envoy_cluster_outlier_detection_ejections_consecutive_5xx{name="ejections_consecutive_5xx"}
envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{name="ejections_detected_consecutive_5xx"}
```
If this is the way it should be done, please close this issue.

**Comment by mattklein123** [comment]
cc @ggreenway @jmarantz for comment.

**Comment by ggreenway** [comment]
I agree that many prometheus metrics aren't aggregated in the best way. This happens because prometheus isn't the primary way that stats are organized; statsd is the native format. The current aggregations are based on a default set of regular expressions, which sometimes miss things like this.

But I'm worried that changing the default aggregation will introduce compatibility issues.

Long-term, I'd prefer if the internal representation of stats became more structured, instead of starting with the statsd format and trying to extract information from that name to aggregate. But that would be a big project, and I don't know if it would be worthwhile or not.

One option to fix things like this while not being incompatible would be to add a prometheus stats version somewhere to the config, and come up with a better set of regexes that we want to use going forward, but keep the existing ones for users who don't want to change. Or maybe even just have a wiki page of common regex config to add for different, common use-cases.

**Comment by jmarantz** [comment]
if we do use a new set of regexes to improve prometheus grouping, let's definitely use re2. I have a start to that here: https://github.com/envoyproxy/envoy/pull/8831

**Comment by reda-ayoub** [comment]
@bartebor I know its the not right place to ask about this but how did you manage to enable the envoy_cluster_outlier_detection_ metrcis, I cant see them on /stats/prometheus but I can see the other envoy_cluster_circuit_breakers metrics?

**Comment by bartebor** [comment]
@reda-ayoub I didn't do anything special, it just works. Have you enabled [outlier detection](https://www.envoyproxy.io/docs/envoy/v1.22.2/api-v3/config/cluster/v3/outlier_detection.proto#config-cluster-v3-outlierdetection) in your cluster configuration?

**Comment by ankitdiscovery** [comment]
@reda-ayoub @bartebor i need to enable /see these outlier detection metrices somewhere or in prometheus for visualization. i can see those values(total/active outlier detection) in `istio-pilot GET stats` but need somewhere to track / visualize them.

**Comment by reda-ayoub** [comment]
@bartebor I'm using envoy through Istio. I installed the last istio release 1.15.1 using Helm on AWS EKS. I'm still not able to see those metrics. I can say that the outlier detection is working because I can see that some pods does not receive any traffic when they trigger the circuit breaker. How did you install/setup envoy?

**Comment by bartebor** [comment]
@reda-ayoub I hava a custom envoy installation with own control plane and configuration, but it should not matter in this case. Note that circuit breaker and outlier detection are separate functions. Make sure you have outlier detection enabled in cluster config. If outlier detection stats are visible in envoy's administration interface (`/stats`, `/stats/prometheus`)  like @ankitdiscovery said above they should be also in your telemetry.  It is also possible that some of the metrics are dropped or modified with `stats_config` in envoy's bootstrap. It may be also due to lack of graphs visualizing those stats; I have no experience with istio, so I can't tell.
