### ISSUE TITLE
Splitting out custom header parsers into a utils file

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#11321]
The documentation and process around custom header processing is a little confusing, specifically in how exactly things are queried into streaminfo. I'd like to move the three [`StreamInfo -> String parse*` functions](https://github.com/envoyproxy/envoy/blob/master/source/common/router/header_formatter.cc#L133) from header_formatter.cc functions into a separate file, maybe `HeaderFormatterUtils`. This way, I can import the parsers into my filter tests and verify my filter changes `StreamInfo` correctly. Would this be ok?

**Comment by mattklein123** [comment]
cc @qiwzhang who was just looking at this during the local reply work. Please sync up with him. In general, anything we can do to improve code reuse and clarity here would be great. We have a lot of overlap with header parsers, access log parsers, etc.

**Comment by auni53** [comment]
@qiwzhang I looked through your recent PRs and they don't seem directly related to this. Are you ok with the proposed change?

**Comment by qiwzhang** [comment]
In this https://github.com/envoyproxy/envoy/pull/11007,  I was asked to move access_log_formatter code out of access_log folder since it is not only used by access_log, but also local_reply. Your request is in the same direction.  I have not started the work yet.

You can expand this issue to re-factory access_log_formatter out of access_log folder together with your requirement of making unit-test of these specific functions easier.  Do you want to take that work?

**Comment by qiwzhang** [comment]
@mattklein123 , @auni53   Sorry,  your HeaderFormatter is at `router` folder,  it is totally different with the one in `access_log` folder.  So my task of access_log_formatter refractory is irrelevant with your issue here.

**Comment by qiwzhang** [comment]
My pr to refractory access_log_formatter is https://github.com/envoyproxy/envoy/pull/11330
