### ISSUE TITLE
api: add proto transform quick mode

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#11365]
The current proto transform tooling takes quite a bit of time to run. During the dev/test cycle it would be very nice to have a "fast" mode where we only transform a specific set of proto files and copy them out to the shadow files. This would greatly speed up the dev flow when making a feature, especially until we get rid of the checked in shadow files and have them built directly by bazel on demand.

cc @htuch

**Comment by htuch** [comment]
My starting point here would be to look back in the tree to the last GitHub merged commit and list the proto files that have changed, restricting `protoxform` to just these files. This should provide a huge speedup. We already do something like this, deciding whether to do a proto format run based on whether _any_ protos have changed since the last GitHub merged commit.

This is on my TODO, but not at the top, so if someone else wants to work on it please go ahead.
