### ISSUE TITLE
examples/front-proxy tutorial is broken

### ISSUE THREAD

**Issue by ahmetb** [envoyproxy/envoy#11506]
I'm using Docker for Mac and for some reason the example proxy in examples/front-proxy cannot bind to 0.0.0.0:80 inside the container.

    front-envoy_1  | [2020-06-08 21:04:27.772][7][critical][main] [source/server/server.cc:100] error initializing configuration '/etc/front-envoy.yaml': cannot bind '0.0.0.0:80': Permission denied

`docker run --rm -p 80:80 nginx` works fine. 

So it makes me think something’s wrong with the docker-compose config. I unfortunately don't know enough to contribute.

**Comment by dio** [comment]
Hum, I think all examples that bound to 80 need to be updated since: https://github.com/envoyproxy/envoy/pull/11323

Meanwhile:

```
    environment:
      - "ENVOY_UID=0"
```

**Comment by ahmetkotan** [comment]
CMD command runs with envoy user because of [this](https://github.com/envoyproxy/envoy/blob/e8a2d1e24dc9a0da5273442204ec3cdfad1e7ca8/ci/Dockerfile-envoy#L30) configuration. I tried adding to `USER root` to Dockerfile and `user: root` to docker-compose.yaml, but it didn't work because of [this](https://github.com/envoyproxy/envoy/blob/e8a2d1e24dc9a0da5273442204ec3cdfad1e7ca8/ci/docker-entrypoint.sh) entrypoint. 

If you are add to ENVOY_UID=0 to environment, you can run as root. Also see, [https://github.com/envoyproxy/envoy/blob/e8a2d1e24dc9a0da5273442204ec3cdfad1e7ca8/ci/docker-entrypoint.sh#L25](https://github.com/envoyproxy/envoy/blob/e8a2d1e24dc9a0da5273442204ec3cdfad1e7ca8/ci/docker-entrypoint.sh#L25)

**Comment by phlax** [comment]
> CMD command runs with envoy user because of this configuration.

its the entrypoint which changes the user.

@mattklein123 would you like me to PR to update the examples that expose `80` ?

**Comment by mattklein123** [comment]
Sure any fixes to improve the examples appreciated.
