### ISSUE TITLE
tcp proxy: add access log

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1159]
We need to add some kind of access log for the TCP proxy. @dnoe do we want proto version of this also?

**Comment by dnoe** [comment]
A good bit of the work that I'm doing will be useful for TCP proxy access logs as well.  We have less of an immediate need for TCP proxying at Google, so this will be a lower priority from me at the moment. But I'll keep the future use case in mind as I move forward with HTTP access logging implementation.

**Comment by ggreenway** [comment]
I can work on this in the near future.  @dnoe have you started on this yet?

**Comment by mattklein123** [comment]
@ggreenway I don't think anyone is working on this right now. Would really love this feature. We could use it at Lyft but I haven't gotten around to it. I will assign it over to you if you have time.

**Comment by ggreenway** [comment]
Sounds good.  I have an implementation already, but it doesn't allow any configuration of the log format.  This has been good enough for me so far because there's not that much to log in the tcp proxy, so logging everything was fine.  However, I expect others will require different formats, even if the content is mostly the same, so I'll see if that's feasible without taking too long or getting too big.

**Comment by mattklein123** [comment]
@ggreenway FWIW my plan was to reuse most of the code in the existing HTTP log formatter. Not all fields apply of course, but I think with some refactoring it shouldn't be too hard to reuse.

**Comment by lizan** [comment]
@ggreenway What is the status of this, or do you have a rough ETA?

**Comment by ggreenway** [comment]
Sorry, I meant to work on this when I claimed it but haven't started yet, but it's nearing the top of my priority queue.  I hope to start on it next week or the week after.

**Comment by ggreenway** [comment]
I'm hoping to start implementation this week.
