### ISSUE TITLE
ads: SRDS initialization not pausing RDS

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#11645]
Related to #11267 
During envoy initialization, if SRDS returns multiple RouteConfigurations, envoy sends a single request for each of those instead of a single one, this means it is not pausing RDS.
This is not happening on a regular config update.

**Comment by sschepens** [comment]
@htuch any clue about this one? i'm getting a little bit lost in all the initialization logic of envoy

**Comment by htuch** [comment]
I'm not even sure if this is the right place to be doing RDS pausing in general. In general, when xDS subscription X depends on resource type Y, then X should be pausing/resuming Y during process `onConfigUpdate()` for X resources. X should also pause/resume I think during its initialization of static resources.

In the link you provide, CM seems to be pausing routes. There's no dependency relationship between clusters and routes, so this seems odd.

I think the SRDS code itself should be doing pause/resume of routes during its initialization or config update. @stevenzzzz any thoughts here?

**Comment by htuch** [comment]
As an aside, I think this is starting to show the limits of the pause/resume model, which is very imperative, as we scale up complexity of the resource DAG. We have listeners depending on SRDS depending on RDS, etc...

Ideally we have something more declarative, like teaching the config subsystem about the dependency graph, so that when X is processing, it just needs to tell the config subsystem "X is in update, hold your horses" and the config subsystem does the pause/resume. This is pretty high-level, but it's the kind of declarative approach I think would be more sound.

**Comment by sschepens** [comment]
@htuch what's strange is that SRDS is already pausing RDS in it's onConfigUpdate, that's why on normal updates it does pause and resume correctly, but something else is going on during initialization.

Maybe that line I referenced is pausing RDS before SRDS, but resuming it before SRDS is done?

**Comment by sschepens** [comment]
> In the link you provide, CM seems to be pausing routes. There's no dependency relationship between clusters and routes, so this seems odd.

According to comments, this is to batch statically defined rds resources

**Comment by stevenzzzz** [comment]
it's because of this line: https://github.com/envoyproxy/envoy/blob/master/source/common/router/scoped_rds.cc#L238
when the SRDS subscription is being initialized, there may also be other RDS that're in other listeners config which may have fired some RDS requests and RDS is in pending state already(in which case we should not pause), so if SRDS is initializing, RDS requests are "fire at will".  

we can probably pause if there are no other pending RDS subscriptions.

**Comment by htuch** [comment]
@stevenzzzz as discussed offline, I think this whole pause interface is too fragile. What we should have is a `pause()` that always succeeds and returns to you a RAII resume object (when you delete it, the subscription resumes). Within `[New]GrpcMuxImpl`, logic should figure out what the refcount situation is and pause/resume as appropriate. That way, bugs like this won't happen again in the future.

**Comment by mattklein123** [comment]
> @stevenzzzz as discussed offline, I think this whole pause interface is too fragile. What we should have is a pause() that always succeeds and returns to you a RAII resume object (when you delete it, the subscription resumes). Within [New]GrpcMuxImpl, logic should figure out what the refcount situation is and pause/resume as appropriate. That way, bugs like this won't happen again in the future.

Big +1. I find the current pause() situation extremely difficult to understand and very fragile. Can we step back and do a proposal to see if there is a better way of holistically handling this?

**Comment by stevenzzzz** [comment]
if ok let's create a separate issue to track that, I'd expect it to spider into many files. keeping the pause/unpause in pair sounds good to me. One thing I want to sort out there is if we only pause/resume in one main-thread event.

I want to address the initialization improvement mentioned in this issue with a possibly smaller change.

**Comment by stevenzzzz** [comment]
create issue #11674 to track the more general interface problem.

**Comment by htuch** [comment]
@stevenzzzz that is fine, as long as this pause/resume fix for SRDS is highly local and intuitive, we can take it. If not, I'd rather not build further tech debt and just have #11674 implemented.

**Comment by sschepens** [comment]
@stevenzzzz @htuch i see that #11739 has been merged but #11674 is still open, what about this issue?
I understand that the interface problem alone will not fix this particular issue.
How will this issue be approached? is there any way i can contribute?

**Comment by htuch** [comment]
@sschepens I think #11645 should be fixed by #11739. Can you confirm?

#11674 is more a code technical debt issue, but isn't addressing an active bug at this point. You're welcome to contribute there, probably looking into https://github.com/envoyproxy/envoy/issues/11674#issuecomment-651382085 makes sense first.

**Comment by stevenzzzz** [comment]
I think it actually resolves this bug already. Please let me if it doesnt. 
The RDS is now paused when SRDS gets a resp back from Management server, and that should have solved the problem in this issue.

**Comment by sschepens** [comment]
@stevenzzzz @htuch seems that this issue is solved by #11645 thanks!
