### ISSUE TITLE
Envoy Jaeger tracing metrics

### ISSUE THREAD

**Issue by christine-gong** [envoyproxy/envoy#11743]
Description:
When using jaeger with zipkin tracers on Envoy, envoy sends spans to Jaeger collector, do we have related client side metrics/statistics? e.g. jaeger_reporter_spans, jaeger_agent_reporter_batches_submitted_total as demonstrated in https://github.com/jaegertracing/jaeger/blob/master/monitoring/jaeger-mixin/dashboard-for-grafana.json
Thanks

**Comment by dio** [comment]
Not sure about jaeger native. However, from my limited knowledge: if you use "Zipkin" config (since one can configure jaeger using Zipkin driver), the available stats are:

https://github.com/envoyproxy/envoy/blob/0f2373b3aea79bad35140f180d214622937d9b86/source/extensions/tracers/zipkin/zipkin_tracer_impl.h#L25-L30

**Comment by christine-gong** [comment]
@dio yeah, we are using Jaeger with zipkin tracer. Do you know which port are those stats exposed at?
