### ISSUE TITLE
with_request_body in ExtAuth sent to OPA

### ISSUE THREAD

**Issue by gituserjava** [envoyproxy/envoy#11834]
If we specify `with_request_body` in ExtAuth in envoy.yaml with `max_request_bytes`, will the body be sent to OPA server? If yes, how can we log or see that body in OPA logs?

My assumption is if we do not specify `with_request_body`, the body will not be sent to OPA. Is that correct?

**Comment by yanavlasov** [comment]
According to docs the buffered body is sent to the authorization service when `with_request_body` is specified. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=with_request_body It will not be sent otherwise

Not sure about logging, though.

**Comment by dio** [comment]
@gituserjava for OPA I think you can follow this example: https://www.openpolicyagent.org/docs/latest/envoy-authorization/. Looking at that, if you activate the plugin. The request body will be: 

```
import input.attributes.request.http as http_request

http_request.body
``` 

And that will be "string" (https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-httprequest-body).

**Comment by gituserjava** [comment]
@yanavlasov , @dio , thank you for the response. 

One more question, what is the maximum size of the request body that can be sent to OPA? 

Will it be an issue if we send more than 100kilo bytes request body to OPA?

**Comment by dio** [comment]
@gituserjava not sure about that, since that will be a perfect question for OPA server implementation. If you use the "istio-plugin" it will be "just" a gRPC server https://github.com/open-policy-agent/opa-istio-plugin/blob/c9c19f8b5886d07f39d426549b2e84d6875a616a/internal/internal.go#L108, which has no such limitation.
