### ISSUE TITLE
Significance of setting AlpnProtocols in the client's UpstreamTlsContext

### ISSUE THREAD

**Issue by shashankram** [envoyproxy/envoy#11909]
When an application protocol is specified in the client's `UpstreamTlsContext.CommonTlsContext.AlpnProtocols`, how does Envoy use this for ALPN negotiation? Can a custom ALPN value be specified, in which case how would the negotiation work if the server specifies different `AlpnProtocols` as a part of the `DownstreamTlsContext` in the inbound listener? What happens if a protocol other than `h2, http/1.1` is specified as a part of the `AlpnProtocols` in the `UpstreamtlsContext`? Can servers only use this information for filter chain matching while advertising a different `AlpnProtocols` as a part of the `DownstreamTlsContext`?

**Comment by yanavlasov** [comment]
@snowp did your PR that was going to change this land?

**Comment by snowp** [comment]
My PR affected how we select what protocols to attempt ALPN negotiation, not how the negotiated ALPN is used. 

At the moment protocol selection is completely decoupled from the result of ALPN negotiation: for HTTP the protocol selection is based on what is configured on the cluster (`protocol_negotiation` field), while ALPN is blindly negotiated based on the protocols specified on the TlsContext (or via other mechanisms such as the alpn override API that can be used via custom filters). I added some default behavior around what happens if no ALPNs are specified on the TLS context, but I don't think this addresses the question.

What kind of matching semantics did you have in mind?

**Comment by shashankram** [comment]
I am wondering whether the ALPNs specified in the TLS context can be relied upon to do filter chain matching based on application protocol. I have 2 sets of clients (one using envoy, one without envoy) talking to a server behind envoy. My use case is to be able to match traffic from these clients differently based on the application protocol if possible, on the server side. I am unsure how the ALPN configured in the TLS context is used. Following questions arise:
1. What is the default behavior if no ALPN is specified in the TLS context?
2. If the client specifies ALPNs in the TLS context, does the server have to advertise this via the TLS context in the listener? Can it advertise a different set of protocols? Can the ALPN be used purely for filter chain matching on the server side?
3. Is the ALPN specified in the TLS context opaque to Envoy? Can this be used as a metadata just for the purpose of filter chain matching based on the application protocol?

**Comment by snowp** [comment]
Ok so I think there's some confusion here between the upstream/downstream context:

During upstream protocol selection and ALPN negotiation, things works as I initially described. 

When resolving filter chains, the negotiated protocol can be used to influence the filter chain selected using the `application_protocols` field: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto

So to answer your specific questions:

1. If no ALPN is specified for the *upstream TLS context*, a standard ALPN matching the selected protocol will be used (`h2` or `http/1.1`). If no ALPN is specified on the downstream TLS context, no protocol will be resolved. 
2. Since protocol selection is independent of the configured/resolved ALPN, you could use arbitrary ALPN protocols to convey information that could be used for filter chain matching (I think Istio does this). 
3. The *resolved* ALPN can be used when resolving filter chains, but there is no functionality today to use the resolved upstream

**Comment by shashankram** [comment]
Thanks for your response, few questions inline.

> Ok so I think there's some confusion here between the upstream/downstream context:
> 
> During upstream protocol selection and ALPN negotiation, things works as I initially described.
> 
> When resolving filter chains, the negotiated protocol can be used to influence the filter chain selected using the `application_protocols` field: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto
> 
> So to answer your specific questions:
> 
> 1. If no ALPN is specified for the _upstream TLS context_, a standard ALPN matching the selected protocol will be used (`h2` or `http/1.1`). If no ALPN is specified on the downstream TLS context, no protocol will be resolved.
> 2. Since protocol selection is independent of the configured/resolved ALPN, you could use arbitrary ALPN protocols to convey information that could be used for filter chain matching (I think Istio does this).
If protocol selection is independent of the resolved ALPN, what is it meant to be used for? Conveying protocol information for filter chain matching seems like a use case that helps my problem (similar to Istio), but is there anything else ALPN helps with if not used for protocol selection?

> 3. The _resolved_ ALPN can be used when resolving filter chains, but there is no functionality today to use the resolved upstream
Got it.  However the server can use the advertised ALPN from downstream connections (part of TLS Client Hello) just for the purpose of filter chain matching irrespective of what protocol is selected?

**Comment by snowp** [comment]
On the server side you could use the resolved ALPN for protocol selection if you used different protocols for the different filter chains, this all requires explicit configuration though. 

ALPN is also necessary when connecting to or receiving connections from non-Envoy clients/servers: if you're routing traffic to something that does rely on ALPN for protocol negotiation. Several HTTP clients out in the wild relies on ALPN to select its protocol (e.g. curl), and we'd like to support this eventually with Envoy but that work hasn't been done yet.

One way of thinking about this is that Envoy doesn't use ALPN to figure out which protocol to use when making upstream connections, but to signal what protocol it wants to use.

**Comment by shashankram** [comment]
Thanks @snowp, that makes sense to me. 

> If no ALPN is specified on the downstream TLS context, no protocol will be resolved.

Does this also imply that between 2 envoys (client and server), the client could advertise the protocol it wants to use via ALPN and the server could simply use this for filter chain matching irrespective of whether the server's TLS context in the listener is configured with ALPN?

**Comment by snowp** [comment]
No, only the final negotiated protocol is made available to the filter chain match, so if the server didn't advertise any protocols there would be no negotiated protocol.

**Comment by shashankram** [comment]
I am referring to the filter chain matching that happens on the inbound listener on the server. The client advertised ALPN is a part of the client's _TLS Client Hello_, why does the server's ALPN matter here?

**Comment by snowp** [comment]
Reading over the code again it seems like we match on the *requested protocols*, not the *resolved protocol* (which makes sense since filter chain matching happens before the handshake completes). So what you describe is how it works.

**Comment by shashankram** [comment]
Thanks for clarifying.

**Comment by hzxuzhonghu** [comment]
@[snowp](https://github.com/snowp) @[shashankram](https://github.com/shashankram)  

In istio, for normal http, the client cluster upstream tls context alpn protocol is "istio-peer-exchange", "istio"

but the server-side, listener downstream tls context alpn protocols is "h2", "http/1.1". And seems it is intended, can you clarify why the alpn can succeed in this case?
