### ISSUE TITLE
Windows builds with clang-cl.exe

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#11974]
In order to reduce the need to engineer workarounds when interoperating with projects such as Chromium that build with clang-cl, and to provide greater consistency with the rest of our Clang-based builds, we should use clang-cl.exe instead of cl.exe. Both are compatible with MSVC.

The main blocker here appears to be https://github.com/google/googletest/issues/2490.

**Comment by htuch** [comment]
@wrowe I've been told that the gmock issue may no longer apply (see https://chromium-review.googlesource.com/c/chromium/src/+/2310189). Unclear if this works in Clang 10 or requires Clang 11.

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy-build-tools/pull/86 for installing `clang` in the Windows build container

**Comment by sunjayBhatia** [comment]
Current issues we faced building locally:
- `curl` does not build as expected, extra arguments are passed to the llvm link tool that are not relevant for libraries, this was happening with `fastbuild`, have not yet tried with `opt`, we've seen major differences in foreign cc components with different build modes (CMake projects treatment of debug builds is often faulty) so that could be something to explore
- clang is requiring all mocks to have the override specifier, which may ultimately be correct, but clang on non-Windows does not warn/error on this
  - as a general point, we need to figure out the correct set of flags to pass to clang-cl to be consistent with non-Windows clang
- We still need to figure out the flags/options to set in the clang-cl rbe toolchain

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy-build-tools/pull/88 for additions and issues with the `clang-cl` toolchain config

**Comment by sunjayBhatia** [comment]
See also https://github.com/bazelbuild/bazel-toolchains/issues/901

**Comment by sunjayBhatia** [comment]
Still blocked on https://github.com/envoyproxy/envoy-build-tools/pull/88 getting merged, cc @lizan when you get a chance

**Comment by wrowe** [comment]
We are currently working on a fork locally to determine the major roadblocks, while using the newly created toolchain and docker image. Expecting to create a PR shortly to demonstrate remaining breakage and move this forward.

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/12946 for some progress, draft PR to add clang-cl to CI

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/13133/files for some modified clang-cl flags in the updated .bazelrc that are required

**Comment by sunjayBhatia** [comment]
See https://github.com/envoyproxy/envoy/pull/13688 as a tracking draft PR

some outstanding issues it seems with clang-cl have us blocked
