### ISSUE TITLE
extensions/stat_sinks/dog_statsd coverage

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#12008]
Hello,
The Envoy project has recently started collecting per-extension coverage. You have been tagged with this issue as you are a co-owner of an extension, extensions/stat_sinks/dog_statsd, which is below the 96.6 percent coverage mark.
Could you please take a look at coverage results (https://storage.googleapis.com/envoy-postsubmit/master/coverage/index.html) and add more tests when you get a chance? Once this is done you should be able to remove your extension from the exempt extensions in [test/per_file_coverage.sh](https://github.com/envoyproxy/envoy/blob/master/test/per_file_coverage.sh) 
Thanks!

**Comment by taiki45** [comment]
@alyssawilk Thank you for the coordinating. I checked the coverage result of the extension and it seems to show 100% coverage.

![image](https://user-images.githubusercontent.com/1460043/87869379-54bdcd80-c9da-11ea-9858-91163a2dd906.png)

Then, I checked the test/per_file_coverage.sh and the dog_statsd is not listed there.

So can we say the dog_statsd extension has fulfilled per-extension coverage? Since I don't understand the background enough yet, I might miss some points, let me know and I'll add some works to fill the coverage.

**Comment by alyssawilk** [comment]
Yeah, I'm super sorry for the trouble but I have no idea how this one got filed.  dog_statsd wasn't even in the initial coverage check-in, so it isn't even a question about it having been fixed between then and now*.  I'll look through the open bugs and make sure there aren't other weird ones like that.

*https://github.com/envoyproxy/envoy/pull/11337/files

**Comment by taiki45** [comment]
No problem, thank you for the confirmation.
