### ISSUE TITLE
Error building envoy on ppc64le

### ISSUE THREAD

**Issue by rashmi-ibm** [envoyproxy/envoy#12097]
Installed Dependencies with version:-

[root@d7f1b4d1bfca /]# gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@d7f1b4d1bfca /]# g++ --version
g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@d7f1b4d1bfca /]#
[root@d7f1b4d1bfca /]# go version
go version go1.13.5 linux/ppc64le
[root@d7f1b4d1bfca /]# bazel --version
bazel 3.4.0- (@non-git)
[root@d7f1b4d1bfca /]# ninja --version
1.8.2
[root@d7f1b4d1bfca /]# python --version
Python 3.6.8

Build command:-
bazel build -c opt //source/exe:envoy-static --verbose_failures --copt "-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1" --cxxopt=-std=gnu++0x

Build failure error:-

external/com_lightstep_tracer_cpp/src/common/utility.cpp: In function 'void lightstep::WriteEscapedString(std::ostringstream&, opentracing::v2::string_view)':
external/com_lightstep_tracer_cpp/src/common/utility.cpp:75:20: error: comparison is always true due to limited range of data type [-Werror=type-limits]
   75 |         if ('\x00' <= c && c <= '\x1f') {
      |             ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 104.218s, Critical Path: 89.10s
INFO: 179 processes: 179 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
[root@d7f1b4d1bfca envoy]#

**Comment by junr03** [comment]
cc @lizan

**Comment by dmitri-d** [comment]
FFIW, we do ppc64le builds, but on RHEL8/gcc 9.3. Envoy CI uses gcc 9 too.

**Comment by lizan** [comment]
Don't add `--cxxopt=-std=gnu++0x`, we're now on C++17, gnu++0x never work

**Comment by rashmi-ibm** [comment]
@lizan I removed the --cxxopt option but the error remains the same.

Build command:- 
bazel build -c opt //source/exe:envoy-static

ERROR: /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/com_lightstep_tracer_cpp/src/common/BUILD:173:21: C++ compilation of rule '@com_lightstep_tracer_cpp//src/common:utility_lib' failed (Exit 1) gcc failed: error executing command /opt/rh/gcc-toolset-9/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 71 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_lightstep_tracer_cpp/src/common/utility.cpp: In function 'void lightstep::WriteEscapedString(std::ostringstream&, opentracing::v2::string_view)':
external/com_lightstep_tracer_cpp/src/common/utility.cpp:75:20: error: comparison is always true due to limited range of data type [-Werror=type-limits]
   75 |         if ('\x00' <= c && c <= '\x1f') {
      |             ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 396.617s, Critical Path: 181.61s
INFO: 1582 processes: 1582 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
[root@d1b5dcc5025e envoy]#

**Comment by dmitri-d** [comment]
I just checked build options we use in maistra builds, and we use "-w" which turns off all warnings. A better approach would be to use "-Wno-error=type-limits", or better still fix the issue in upstream.

**Comment by dmitri-d** [comment]
@rashmi-ibm: I'm not exactly sure why gcc build fails for you, it could be down to differences in compiler versions used -- the CI is on gcc 9.3.x, the compiler version in your environment is 9.2.

**Comment by rashmi-ibm** [comment]
@dmitri-d  as per the below link the official version is 9.2 . Will try to see  gcc 9.3.x...
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/developing_c_and_cpp_applications_in_rhel_8/gcc-toolset-9_toolsets

**Comment by snehakpersistent** [comment]
@dmitri-d I am able to build envoy using "-Wno-error=type-limits". However I am getting below error while executing tests:
`ERROR: /root/envoy/test/mocks/upstream/BUILD:11:14: C++ compilation of rule '//test/mocks/upstream:cluster_info_mocks' failed (Exit 1) gcc failed: error executing command /opt/rh/gcc-toolset-9/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 527 argument(s) skipped)`
Most of the tests are getting skipped because of this. Sometimes one or two tests ran and passed. 

Command used for tests: `bazel test //test/... --test_env=ENVOY_IP_TEST_VERSIONS=v4only --host_javabase=@local_jdk//:jdk --copt "-Wno-error=type-limits"` (Also tried it without --test_env and --host_javabase; got same error)

gcc --version : 
gcc (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by dmitri-d** [comment]
Could you post a complete contents of the error log? The message that you posted doesn't contain enough details to explain what went wrong.

**Comment by snehakpersistent** [comment]
[envoyBuildLog.txt](https://github.com/envoyproxy/envoy/files/5039499/envoyBuildLog.txt)
[envoyTestLog.txt](https://github.com/envoyproxy/envoy/files/5039501/envoyTestLog.txt)
@dmitri-d I have attached build and test logs for reference.

**Comment by dmitri-d** [comment]
There's no error in envoyTestLog, just the message that a test failed to build. You could try adding `--sandbox_debug` to the `bazel test`, or try running just the test that's failing to building.

**Comment by snehakpersistent** [comment]
@dmitri-d I can see below error in the log that I posted:
`ERROR: /root/envoy/test/common/http/BUILD:351:19: C++ compilation of rule '//test/common/http:utility_fuzz_test_lib' failed (Exit 1) gcc failed: error executing command /opt/rh/gcc-toolset-9/root/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 593 argument(s) skipped)
`
I came across this issue https://github.com/envoyproxy/envoy/issues/9962 in which a similar failure is reported. 
I tried adding --sandbox_debug but didn't get any more info as such. Pasting the log for reference.
[envoytestlog_withSandboxDebug.txt](https://github.com/envoyproxy/envoy/files/5050824/envoytestlog_withSandboxDebug.txt)

Also everytime a different test fails to build. So trying to figure out which test is causing the issue. 
Let me know if you have any pointers on this.

**Comment by dmitri-d** [comment]
> Also everytime a different test fails to build.

You can try building/running a particular test suite by specifying the path to it in bazel test command: `bazel test //test/common/http:test_suite`. 

I'd try executing the failing command shown in the debug output, but using gcc directly (I think you can skip everything up to `/opt/rh/gcc-toolset-9/root/usr/bin/gcc`).

**Comment by lizan** [comment]
I think you're seeing same error as https://github.com/envoyproxy/envoy/pull/12299, in short, pass `--copt=-Wno-error=type-limits` or `--copt=-fsigned-char`  to bazel, or write it to `user.bazelrc`.

**Comment by snehakpersistent** [comment]
@dmitri-d  as per your suggestion, I tried executing individually tests that fail to build and they are passing. When I execute all tests together, some or the other test fails to build(not sure why). I tried passing higher timeout value but that didn't help. So I am now executing tests module wise (eg. common, exe and so on) and saving the test results in cache using --cache_test_results=yes. This approach is working fine but its bit time consuming.
@lizan I was facing that error while building envoy but was able to resolve it with `--copt=-Wno-error=type-limits` as mentioned in previous comments. The issue I'm facing now is while executing tests. I have attached logs above.

**Comment by dmitri-d** [comment]
@snehakpersistent: this sounds like it might be an issue with bazel. Have you tried asking about in https://github.com/bazelbuild/bazel?

**Comment by lizan** [comment]
@snehakpersistent it looks like the compiler OOMed, what if you limiting concurrency by pass less number to `--jobs`? it can be a hardcoded number or `--jobs="HOST_CPUS*0.5"`

**Comment by snehakpersistent** [comment]
@lizan thanks for your suggestion. I am using `--jobs` option now and it has reduced test build failures. However I'm still executing tests module wise. If I execute them all together using `//test/...` then still some or the test is failing to build. I tried it with `--jobs 8`(HOST_CPU=16) and even reduced it `--jobs 1`. Is there any way to proceed with execution of rest tests even if one fails to build?

**Comment by lizan** [comment]
pass `-k` to bazel

**Comment by kumarvikas2020** [comment]
@lizan 
I executed test cases using following command on ppc64le:
```bazel test //test/... -k --copt "-Wno-error=type-limits"```

All the test cases passed except 9.
```
Executed 695 out of 697 tests: 688 tests pass, 1 fails to build and 8 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
FAILED: Build did NOT complete successfully
```

1. //test/extensions/common/wasm:wasm_vm_test failed to build due to lack of Chromium support on POWER.
2. //test/extensions/filters/network/thrift_proxy:integration_test failed due to timeout, but succeeded after increasing the timeout.
3. Rest 7 tests are failing probably due to memory leaks and some of them are crashing due to that.
//test/common/stats:thread_local_store_test
//test/config_test:example_configs_test
//test/extensions/filters/common/lua:wrappers_test
//test/extensions/filters/http/lua:lua_filter_test
//test/extensions/filters/http/lua:wrappers_test
//test/extensions/filters/listener/proxy_protocol:proxy_protocol_test
//test/extensions/quic_listeners/quiche/integration:quic_http_integration_test

I am attaching the logs of these tests. Could you check if these failures can be fixed or can be ignored safely?
[TestFailures.txt](https://github.com/envoyproxy/envoy/files/5116115/TestFailures.txt)

**Comment by dmitri-d** [comment]
Opened a PR with a fix for the failure in //test/extensions/filters/listener/proxy_protocol:proxy_protocol_test: https://github.com/envoyproxy/envoy/pull/12800

**Comment by kumarvikas2020** [comment]
@dmitri-d Thanks. PR https://github.com/envoyproxy/envoy/pull/12800 resolved issue in the test case //test/extensions/filters/listener/proxy_protocol:proxy_protocol_test on ppc64le as well.

Similar issue exists in the test case: //test/extensions/quic_listeners/quiche/integration:quic_http_integration_test.

**Comment by kumarvikas2020** [comment]
@dmitri-d @lizan 
Following 2 issues (pure virtual method called) in the test cases appear on both x86 and ppc64le platforms:

//test/common/stats:thread_local_store_test
[thread_local_store_test.log](https://github.com/envoyproxy/envoy/files/5253570/thread_local_store_test.log)

//test/extensions/quic_listeners/quiche/integration:quic_http_integration_test
[quic_http_integration_test.log](https://github.com/envoyproxy/envoy/files/5253574/quic_http_integration_test.log)

Could you check these issues.

**Comment by kumarvikas2020** [comment]
@dmitri-d @lizan
Following additional 4 test case failures that I am facing on ppc64le appear to be due to "lua" support on POWER.
Could you confirm if these issues are not related to envoy-proxy code but are external to it.

1. //test/config_test:example_configs_test
[example_configs_test.log](https://github.com/envoyproxy/envoy/files/5253654/example_configs_test.log)

2. //test/extensions/filters/common/lua:wrappers_test
[common_lua_wrappers_test.log](https://github.com/envoyproxy/envoy/files/5253655/common_lua_wrappers_test.log)

3. //test/extensions/filters/http/lua:lua_filter_test
[http_lua_lua_filter_test.log](https://github.com/envoyproxy/envoy/files/5253657/http_lua_lua_filter_test.log)

4. //test/extensions/filters/http/lua:wrappers_test
[http_lua_wrappers_test.log](https://github.com/envoyproxy/envoy/files/5253660/http_lua_wrappers_test.log)
