### ISSUE TITLE
why Result::ExtOriginRequestFailed map to different HTTP codes between local and ext origin error

### ISSUE THREAD

**Issue by hobbytp** [envoyproxy/envoy#12453]
Description:
    Question for [outlier detection](https://www.envoyproxy.io/docs/envoy/v1.15.0/intro/arch_overview/upstream/outlier.html) behaviors.  
* When local origin error and external origin error are not split (`outlier_detection.split_external_local_origin_errors` is false), the `Result::ExtOriginRequestFailed` will mapped to `Http::Code::InternalServerError` (500)
* When local origin error and external origin error are split (`outlier_detection.split_external_local_origin_errors` is true), the `Result::ExtOriginRequestFailed` will mapped to `Http::Code::ServiceUnavailable` (503)

Why will `ExtOriginRequestFailed` result map to different HTTP code? is there any specific reason? thanks

The related codes are as below:
1) local and ext origin error not split
```c++
void DetectorHostMonitorImpl::putResultNoLocalExternalSplit(Result result,absl::optional<uint64_t> code) {
    ...
    absl::optional<Http::Code> http_code = resultToHttpCode(result);
}
absl::optional<Http::Code> DetectorHostMonitorImpl::resultToHttpCode(Result result) {
  ...
  case Result::ExtOriginRequestFailed:
    http_code = Http::Code::InternalServerError;  //==> here
    break;
}
```

2) local and ext origin error split
```c++
void DetectorHostMonitorImpl::putResultWithLocalExternalSplit(Result result, absl::optional<uint64_t>) {
  ...
  case Result::ExtOriginRequestFailed:
    // map it to http code and call http handler.
    return putHttpResponseCode(enumToInt(Http::Code::ServiceUnavailable));   //==> here
   ...
}
```

**Comment by mattklein123** [comment]
cc @cpakulski who wrote this code. I remember going back and forth on this during code review and I think it has to do with historical compatibility but I'm not sure.

**Comment by hobbytp** [comment]
@cpakulski any comments? thanks,

**Comment by cpakulski** [comment]
@hobbytp Sorry for long silence - I was away. Let me look at the code to refresh my memory.

**Comment by cpakulski** [comment]
@hobbytp I checked the code and logic around how it is used. 

First of all the error code you are referring to: `Result::ExtOriginRequestFailed` is used only by Redis filter.
The idea behind splitting external errors and locally generated errors is that you may want to eject nodes when Envoy cannot connect to upstream server, but you do not care if the server returns an error or not after it successfully connected to the server. 

Ideally when you enable local/external split your config should stay the same, just locally generated errors go to different bucket.

Here, as you pointed out, this may not be the case unfortunately. `Http::Code::ServiceUnavailable` is treated as Gateway error and if you set gateway's outlier detector params more sensitive than 5xx params, it will trigger ejection sooner than when local/external split is disabled. If you however leave settings with default values there should be no difference.

To be consistent, I think we should remap `Result::ExtOriginRequestFailed` to `InternalServerError`, because it will be handled by 5xx counters, not Gateway counters. Gateway is HTTP specific concept and reacts to error codes 502-505 and should be used only by HTTP traffic not Redis. 

What is your setup and how does this mapping affect you?

Once I understand your case I will create PR with correct mapping.
