### ISSUE TITLE
build failed on windows10

### ISSUE THREAD

**Issue by rtttech** [envoyproxy/envoy#12560]
error running 'git init C:/users/rtttech/_bazel_rtttech/u3xypprs/external/org_golang_x_tools' while working with @org_golang_x_tools:
java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("git" init C:/users/rtttech/_bazel_rtttech/u3xypprs/external/org_golang_x_tools): ???????????
 (error: 2)

It seemed that create process with relative path does not work on windows, I tried this with python:
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.Popen(["git" "init" "C:/users/rtttech/_bazel_rtttech/bmpacvqm/external/org_golang_x_tools"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by wrowe** [comment]
I believe this is covered at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#windows

The project is unable to support multiple python interpreter flavors with different OS behaviors. If you have patches to the documentation or the envoy build schema to support another python flavor in addition to the sole recommended and supported package distributed by python.org, patches will certainly be considered. If they require changes to bazel itself (quite possible) those should be first submitted directly to the https://github.com/bazelbuild/bazel project itself, so that we can pick up a newer bazel for envoy's consumption.

**Comment by wrowe** [comment]
This doesn't appear to have much to do with relative paths, the "git.exe" binary from github.org (we have also had some success with msys's) must be on the process path list.
