### ISSUE TITLE
issue when adding custom headers for  External Authorization

### ISSUE THREAD

**Issue by mailofapideveloper** [envoyproxy/envoy#12596]
I am trying to send a custom header from each route to External Authorization server , this header will be used to identify the service and do Authorization .When I try adding the header at route level , getting unable to unpack error.
Can you please help in figuring out what is missing ?

**Below is the config in Yaml**
`virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match: { prefix: "test/v1/service" }
                  route: 
                    cluster: backend                    
                  typed_per_filter_config:
                    envoy.filters.http.ext_authz:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.AuthorizationRequest                      
                      headers_to_add: 
                        -  {"key": "x-prefix","value": "servicev1"}`

**Error:**
` Unable to unpack as envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute: [type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.AuthorizationRequest] {
envoy_1      |   headers_to_add {
envoy_1      |     key: "x-prefix"
envoy_1      |     value: "servicev1"
envoy_1      |   }
envoy_1      | }`

**Comment by esmet** [comment]
The yaml you provided is using `@type: "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.AuthorizationRequest"` for the per filter config, but I think you actually want `@type: "envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute"`

Instead of sending a custom header to the external authorization server to identify the source route, I believe you need to instead use the context_extensions field on the gRPC check request message https://github.com/envoyproxy/envoy/blob/12537506f8bb42797c0bfe6fa9418e02cb34ae63/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L295 - this requires using a gRPC auth service instead of an HTTP one, though.
