### ISSUE TITLE
[xDS]: document the precedence between  resource_names_subscribe and  resource_names_unsubscribe in case they have overlap

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#12646]
in delta XDS, seems deletions take precedence over additions. https://github.com/envoyproxy/envoy/blob/master/source/common/config/delta_subscription_state.cc#L19-L35
we need to document this clearly in doc and let management server side follow the same order when returning resources back.

**Comment by stevenzzzz** [comment]
@htuch WDYT

**Comment by htuch** [comment]
My thinking is that it's the client's responsibility to maintain disjoint sets here, since we don't want to have to over-specify behaviors when we're outside the normal operational envelope. @envoyproxy/api-shepherds CC.

**Comment by stevenzzzz** [comment]
sounds good. For now, on the client side, we do remove firstly added resources when update subscription interests, they are supposed to be disjointed already unless the resource_versions_ has an overlap with resource_names_unsubscribe on a reconnection scenario.

**Comment by markdroth** [comment]
FWIW, my $0.02:

- The client should definitely be responsible for keeping these two sets disjoint; it really does not make sense to tell the server to both subscribe and unsubscribe to the same resource at the same time.
- For the server behavior, I would actually be fine with saying that the server should consider this as a no-op, as if the client subscribed and then immediately unsubscribed from the same resource in a single atomic operation.  But I would also be fine with saying that the behavior is undefined, because the client should really never do this in the first place.

**Comment by stevenzzzz** [comment]
make sense. Let me close this issue as client guarantees disjointed sets are sent to management server.
