### ISSUE TITLE
Metadata support in access logs

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1278]
In the v2 APIs, we build up a metadata object as listeners/filter chains/routes are computed. Similar to the ability to log arbitrary headers in the access log today, we would also like to be able to log metadata.

@dnoe

**Comment by dnoe** [comment]
Where is the built up metadata object located? My plan was the include all the metadata in the Struct field (rather than configuring logging of a subset) although this isn't hooked up yet. If we want the ability to filter specifically what metadata is included I'll need to add something for that purpose into the AccessLog configuration message in http_connection_manager.proto.

**Comment by htuch** [comment]
I think we're open to exploring design at this point. Simplest would be to include everything, but that would only work for the proto logging, not the string based logs with formatters that would call out specific fields.

**Comment by dnoe** [comment]
I hadn't actually considered the case of logging metadata into string based logs, and I need to think about how this would look. Given the open ended nature of the metadata Struct it seems tricky to balance this against formatting it in a concise format (JSON in the access log line? ugh?), and the open ended composition of the Struct means it's hard to figure out how a config specifier would filter it.

**Comment by htuch** [comment]
Yeah. We could support simple flat Struct access, where it's just key:value at one level, which is how metadata is probably going to be used most of the time when it's destined for logging.

**Comment by mrice32** [comment]
@mattklein123 @htuch I'm not sure what the status is on this issue or if this is the right place to discuss this, but we've reached the point where we'd like to use route, listener, cluster, and endpoint metadata in our access logs (I intentionally left out filter chain metadata because I don't think we technically need that right now).  It appears as if endpoint metadata [is already accessible](https://github.com/envoyproxy/envoy/blob/master/include/envoy/upstream/host_description.h#L59) to the access logs, route metadata [is being parsed](https://github.com/envoyproxy/envoy/blob/master/source/common/router/config_impl.cc#L403) but not accessible, and the rest are unimplemented.

I'd like to come to a consensus about how we want these to be processed and accessed.  On first glance, I'm not sure why we'd need to do any merging or runtime construction of a metadata object at all.  It seems as if there is exactly one of each of the aforementioned components selected for a particular request, so the metadata for each component can be accessed individually by setting a pointer inside RequestInfo or some similar object.  What are y'all's thoughts?

**Comment by dnoe** [comment]
I think the merging was more along the lines of the fact that the union of all of the component metadata should make it into the AccessLog proto metadata field, although we were also thinking about a different destination internally for the AccessLog proto at the time.

**Comment by mattklein123** [comment]
Yeah I don't think we need merging AFAIK, as I think we assume that metadata is effectively namespaced properly by the user. I suppose when we eventually send it out in the access log we will need to reconcile if someone does not namespace correctly, but this could probably be done in the simplest way possible with good docs (i.e., just overwrite).

@mrice32 @dnoe Lyft's main need for metadata in access logs is actually to be able to *set* metadata dynamically on a request from a filter. So my plan was going to be to allow metadata to be set into request info, and then sent as part of the gRPC access logger. I was going to have @rodaine work on this probably later this week or next week. @rodaine can you reach out to @mrice32 and @dnoe in Slack and coordinate just to make sure you aren't stomping on each other? I can help with context offline.

**Comment by htuch** [comment]
My understanding is that we would merge in a very simple way. Imagine the following:

```
Metadata from LDS:

com.google.foo: {"listener_id": "thing"}
envoy.auth: {"another": "thing"}

Metadata from RDS:

com.google.foo: {"route_id": "1234"}
```

The merge is:

```
com.google.foo: {"listener_id": "thing", "route_id": "1234"}
envoy.auth: {"another": "thing"}
```

i.e. we expect different entities to use different parts of the top-level namespace, but the next nested namespace will have a simple dictionary update (i.e. latest entry wins) merge happen.

**Comment by mrice32** [comment]
@mattklein123 @rodaine Would this mutable metadata be distinct from the other types of metadata for individual components or would we make per-request copies of each of those to allow them all to be modified?

@htuch I think that method of merging makes sense, but would this merging be something that happens within a particular access log implementation?  Or would this merged copy be created automatically over the course of processing and be the only metadata available in RequestInfo?  I don't really see much of an advantage of doing this merge automatically rather than creating a utility function for it that's available if users need a merged struct for export.

**Comment by htuch** [comment]
I don't mind either way, the API would be simpler if it was merged automatically but I agree that it's maybe not needed for many cases.

**Comment by mattklein123** [comment]
@mrice32 I think it would just be distinct and then get merged later using whatever merging algorithm we decide on (whether built-in or via utility). Our use case is basically to be able to set metadata values such as:

```
lyft.edge: {"user_id": "foo", "client_id": "bar"}
```

etc.

**Comment by htuch** [comment]
For reference, here's a Python one-liner for what I had envisaged merge to be:

```python
merge_metadata = lambda ms: reduce(lambda merged, m: {k: dict(merged.get(k, {}).items() + m.get(k, {}).items()) for k in set(merged.keys()).union(set(m.keys()))}, ms)
```

E.g.

```
>>> merge_metadata([{"com.google": {"a": 1, "b": 2}}, {"envoy.auth": {"c": 5}, "com.google": {"a": 3, "c": 4}}])
{'envoy.auth': {'c': 5}, 'com.google': {'a': 3, 'c': 4, 'b': 2}}
```

**Comment by mrice32** [comment]
Thanks everyone!  I think I'll begin by making the route, listener, and cluster metadata fields accessible via the RequestInfo object, and we can iterate from there.

**Comment by mattklein123** [comment]
I'm reassigning this to a combo of @mrice32 and @rodaine for reconciling both Google and Lyft needs here.

**Comment by glicht** [comment]
Hi All,

Would be happy to help out here. 

I want to implement the part of the dynamic metadata on a request from a filter as described by @mattklein123. 

Basically,  I was thinking of adding a DynamicMetadata map to RequestInfo with a setter method: setDynamicMetadata(namespace, struct).

**Comment by mattklein123** [comment]
@mrice32 or @rodaine are you working on this soon or should @glicht take a look?

**Comment by mrice32** [comment]
I've already completed the portions I mentioned above that we needed internally (see #2345, #2392, #2435), so we don't have any plans/need to add the dynamically built metadata object. It would be awesome for @glicht to take a look at that.

**Comment by glicht** [comment]
Hi, I've created a pull request for supporting dynamic metadata on request info and an option for the access_log to log this. See: #2895 . I still didn't add documentation about this as I wanted to get some feedback regarding the approach and naming conventions.

**Comment by mattklein123** [comment]
This is complete.
