### ISSUE TITLE
Migrate FixedHeap resource monitor to api v3

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#12841]
[FixedHeap resource monitor](https://github.com/envoyproxy/envoy/blob/master/source/extensions/resource_monitors/fixed_heap/fixed_heap_monitor.h) is still using api v2. We should provide v3 version for users who are moving away from v2.

**Comment by mattklein123** [comment]
cc @htuch I think it's OK for things to stay at v2 if they haven't changed but I'm not 100% sure.

**Comment by htuch** [comment]
That's right. That said, I think we were originally hoping (very reasonably) that mixing leaf versions would allow us to minimize the DAG that is transformed during a major version transition. That has categorically not happened in v3, we upgraded almost everything except for half-a-dozen or so leaf packages. Arguably, it's not worth the complexity/confusion to follow this strategy if we anticipate future major versions (since they will now be far apart, >> 1 year) will have a similar API-wide upgrade path.

CC @envoyproxy/api-shepherds for what others reckon, but we could just move to consistent v3 leaves, even if nothing changed.

**Comment by htuch** [comment]
Also tagging https://github.com/envoyproxy/envoy/issues/10943, since I think this is something to discuss in the PM.

**Comment by markdroth** [comment]
If we're already winding up creating v3 versions of pretty much everything anyway, it seems like it would be more consistent to just do it uniformly.  This would presumably eliminate a lot of machinery used to determine when a new version of a given proto is needed, because the answer would always be yes.  It would also eliminate surprises that can cause a whole slew of new files to be automatically created in v4alpha when deprecating a field in v3.

**Comment by mattklein123** [comment]
SGTM to migrate. At this point I'm not sure we are ever going to do v4, or at least not for years as @htuch says, so seems better to be consistent.

**Comment by ankatare** [comment]
@htuch @mattklein123  would like to take this.

**Comment by ankatare** [comment]
@htuch thanks for assigning. would you please give some pointers to start and understand the requirements more clear.

**Comment by htuch** [comment]
Find all of the v2 packages in https://github.com/envoyproxy/envoy/blob/5c7737266e671ea9801c14d2779ca30bb0032bf7/api/BUILD#L125 (there should be a handful). You can manually copy them over to v3 trees. Update the `(udpa.annotations.file_status).package_version_status` status.

**Comment by ankatare** [comment]
Ok Thanks @htuch

**Comment by ankatare** [comment]
@htuch yeah, found below packages from v2. 

"//envoy/config/filter/thrift/router/v2alpha1:pkg",
        "//envoy/config/health_checker/redis/v2:pkg",
"//envoy/config/resource_monitor/fixed_heap/v2alpha:pkg",
        "//envoy/config/resource_monitor/injected_resource/v2alpha:pkg",
        "//envoy/config/retry/omit_canary_hosts/v2:pkg",
        "//envoy/config/retry/previous_hosts/v2:pkg",

what do you mean to copy these manually into v3 trees. can you elaborate what exactly meaning of v3 trees ( any one example would be helpful)

**Comment by ankatare** [comment]
let say if i talk about //envoy/config/filter/thrift/router/v2alpha1:pkg". 
so should i need to copy //envoy/config/filter/thrift/router/v2alpha1/files to //envoy/config/filter/thrift/router/v3/ 

is my understanding correct ?

**Comment by ankatare** [comment]
and then putting status as (udpa.annotations.file_status).package_version_status = FROZEN;
 in .proto file for above example
api/envoy/config/filter/thrift/router/v2alpha1/router.proto

and similarly for other cases of v2 packages ?

**Comment by htuch** [comment]
> @htuch let say if i talk about //envoy/config/filter/thrift/router/v2alpha1:pkg".
so should i need to copy //envoy/config/filter/thrift/router/v2alpha1/files to //envoy/config/filter/thrift/router/v3/

This needs to match the new layout for filters, we've moved from envoy/config/filter to envoy/extensions/filters.

> and then putting status as ..

Yes, then run proto_format and fix whatever issues and apply the transforms come out of that.

**Comment by htuch** [comment]
(and yep, that list of packages seems right)

**Comment by ankatare** [comment]
@htuch ok. thanks for quick clarifications.

**Comment by ankatare** [comment]
one quick things is there any docs through i can check such layout changes from v2 to v3  etc ?  like as you mentioned for filters.

**Comment by htuch** [comment]
Might be worth looking at the git history of some of the v3 files.

**Comment by htuch** [comment]
@ankatare can you verify before we close this issue that whatever is done works for cases such as https://github.com/envoyproxy/envoy/pull/14634? I.e. this should be producing v4 arguably.

**Comment by ankatare** [comment]
@htuch as discussed let's open new issue on that and assign it to me. meanwhile if all ok close this issue. ( long open :) )
