### ISSUE TITLE
Envoy failed on Bazel CI with "unused variable 'factory_name'"

### ISSUE THREAD

**Issue by meteorcloudy** [envoyproxy/envoy#13079]
https://buildkite.com/bazel/envoy/builds/1295#b92e2abd-a008-49b7-a929-2a5dde5a0152
```
bazel-out/k8-fastbuild/bin/include/envoy/registry/_virtual_includes/registry/envoy/registry/registry.h:348:44: error: unused variable 'factory_name' [-Werror=unused-variable]
     for (const auto& [factory_name, factory] : factories()) {
                                            ^
cc1plus: all warnings being treated as errors
```

**Comment by ratulb** [comment]
bazel-out/k8-opt/bin/include/envoy/registry/_virtual_includes/registry/envoy/registry/registry.h:348:44: error: unused variable 'factory_name' [-Werror=unused-variable]
     for (const auto& [factory_name, factory] : factories()) {

**Comment by meteorcloudy** [comment]
@ratulb Did you encounter the same build failure?

**Comment by guoruijing** [comment]
I created fix in https://github.com/envoyproxy/envoy/pull/13125

**Comment by ratulb** [comment]
I had to put the following in my .bazelrc to get around this.

build:linux --cxxopt=-Wno-error=unused-variable
________________________________

**Comment by htuch** [comment]
@guoruijing @ratulb @meteorcloudy which compiler version is this? Has this just switched to on-by-default? 

I think we should fix this structurally in Envoy so we don't have this come up again, probably by adding to `envoy_copts` in bazel/envoy_internal.bzl`, but maybe first by understanding why this is an issue for Bazel CI and not us.

**Comment by asraa** [comment]
@meteorcloudy Can you reproduce if you use gcc version 9?

**Comment by guoruijing** [comment]
I can reproduce the issue with gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by meteorcloudy** [comment]
I believe we also use gcc 7.5 on Bazel CI. Somehow this unused variable is treated as an error on Bazel CI, but probably as a warning on circle CI?

**Comment by asraa** [comment]
I think GCC 9 is used in Envoy's CI https://github.com/envoyproxy/envoy-build-tools/blob/e7ea4e81bbd5028abb9d3a2f2c0afe063d9b62c0/build_container/build_container_ubuntu.sh#L12, is it possible that this is why?

**Comment by meteorcloudy** [comment]
Sorry, I have no idea.

**Comment by ratulb** [comment]
I pulled down latest sources - still facing the same build failure. I am using:

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

I would upgrade gcc and see how it goes later today.
________________________________

**Comment by guoruijing** [comment]
there are lots of locations using unused variables. I can change like followings or we just upgrade compiler version?

-     for (const auto& [factory_name, factory] : factories()) {
+    for (const auto& t: factories()) {
+      const auto& factory = std::get<1>(t);

**Comment by asraa** [comment]
We support and use GCC 9 in CI. But these docs https://github.com/envoyproxy/envoy/blob/4706ee01abe191eef73c64d86c1835baf566323c/bazel/README.md#supported-say compiler-versions currently has GCC 7+ as supported. There was some refactor after C++17 was enabled to use structured binding, which should be find since structured bindings appear in GCC 7.

However, I did find a GCC bug about this: https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=81767
that was fixed in https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=6fc9f7aa731e895585c47d740509b5cd1591e797
I wonder if your compiler has the fix?

I think I would suggest upgrading compiler version.
@envoyproxy/maintainers

**Comment by meteorcloudy** [comment]
I don't think we can easily upgrade the gcc version on Bazel CI, other projects may still depend on the current version. 
For fixing envoy on Bazel CI purpose, maybe you can disable this warning in the config script (.bazelci/presubmit.yml) or in the bazelrc file?
/cc @philwo

**Comment by meteorcloudy** [comment]
FYI, according to https://buildkite.com/bazel/envoy/builds?branch=master&page=7, 
this breakage was introduced between (https://github.com/envoyproxy/envoy/commit/da58cfc3292c6291c04dd3f10895b09e297bef15 and https://github.com/envoyproxy/envoy/commit/defea7ecbf6f3ebffe8b9d41afa7f62322756f05 ]

**Comment by asraa** [comment]
Yep, I'm assuming they were coming from these PRs 
https://github.com/envoyproxy/envoy/pull/12791
https://github.com/envoyproxy/envoy/pull/12359
https://github.com/envoyproxy/envoy/pull/12468

**Comment by mattklein123** [comment]
IMO we should either *downgrade* Envoy GCC to match Bazel CI, or just do this:

> For fixing envoy on Bazel CI purpose, maybe you can disable this warning in the config script (.bazelci/presubmit.yml) or in the bazelrc file?

I think ^ is probably simpler?

**Comment by ratulb** [comment]
Got latest clang installed on ubuntu 20.04 LTS - latest sources built smoothly.

root@ubuntu-box:~$ clang-11 --version
Ubuntu clang version 11.0.0-++20200916113328+8f2c29681ce-1~exp1~20200916094014.99
Target: x86_64-pc-linux-gnu
Thread model: posix


FYI.

________________________________

**Comment by lizan** [comment]
Perhaps we can simply remove GCC Bazel CI jobs, we do test RBE and Coverage (via local installed clang-10), IMO they are enough to catch issues from Bazel.

**Comment by philwo** [comment]
Bazel CI by design only installs tools and toolchains from packages supplied by a given distribution version and we do not upgrade these beyond what the distribution offers in their own repositories. This is so Bazel and other projects can verify that they are compatible with e.g. Ubuntu 18.04 LTS out of the box.

If you don't need to be compatible with Ubuntu 18.04 LTS, I would recommend to stop testing on that distro. Unfortunately Ubuntu 20.04 LTS is not yet available on Bazel CI, but I'll add it shortly: https://github.com/bazelbuild/continuous-integration/issues/1035
