### ISSUE TITLE
Add an extension point for Fatal Handlers  

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#13091]
Fatal Handlers: Add an extension point to Fatal Handlers

*Description*:
When a Fatal Error occurs, we end up calling `onFatalError` from the signal handler which dumps the current `ScopedTrackedObject` of the thread that encountered a fatal error if there’s a related scope tracked object. 

However, the current mechanism isn’t flexible enough -- for example it just dumps to `std::cerr` using output from the `ScopedTrackedObject`. 

There are many cases where you might be interested in ingesting and transforming what’s dumped and where it’s dumped before we exit -- such as dumping in a particular format to be ingested by other systems, stripping away any PII, etc.

Let me know if this makes sense. Thanks!

**Comment by mattklein123** [comment]
Makes sense to me! Since you have been adding a lot of new extension points recently I would appreciate it if you could update https://github.com/envoyproxy/envoy/blob/master/EXTENSION_POLICY.md to make sure we are listing out the various places the docs need to be updated to discuss new extension points. Thank you!

**Comment by KBaichoo** [comment]
Sure thing, I'll take a look at that as well.
