### ISSUE TITLE
Adaptive concurrency rejects should put reason into `grpc-message` header

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#13138]
https://github.com/envoyproxy/envoy/blob/a8b946e1c30618dfcab6c7e90333301c16b56a65/source/extensions/filters/http/adaptive_concurrency/adaptive_concurrency_filter.cc#L40-L42

**Comment by mattklein123** [comment]
I would have thought our gRPC local reply code would already do this, but maybe not. cc @alyssawilk who has been in here recently.

**Comment by alyssawilk** [comment]
the gRPC code sends the body text as the error message, but for adaptive concurrency that's "" so not very informative.
Given I've been playing in this space it should only be a 10 minute fix for me - happy to throw something together.

**Comment by mattklein123** [comment]
Ah OK I missed that. I thought it would potentially be the reason details string. I wonder if it should be the reason details string?

**Comment by alyssawilk** [comment]
Move gRPC to sending response code details as the body?  I don't have strong feelings either way, but it's a larger change and it strikes me as weird to send different information in the non-gRPC body than we do in the gRPC header.  Then again the two are often similar, it's just that details are more optimized for logging (terse, avoid spaces) and bodies are optimized for human readability.
cc @lizan because gRPC

**Comment by mattklein123** [comment]
My thinking was mostly that the grpc-message is probably expected to not be very long, but not a big deal.

I guess my higher level comment is that it seems strange that in the common case of the body/details being the same (I'm guessing this happens a lot) the programmer has to duplicate it. I wonder if there is a cleaner way of handling this common case.

**Comment by kb000** [comment]
Great! Thanks @alyssawilk!
