### ISSUE TITLE
how to config bandwidth limit

### ISSUE THREAD

**Issue by Chwetion** [envoyproxy/envoy#13604]
requirement: such as limit bandwidth when client upload file to server 20kb/s
i find a filter "envoy.config.filter.fault.v2" https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/fault/v2/fault.proto#config-filter-fault-v2-faultratelimit-fixedlimit.
can i use this envoy filter to solve this question?
if it can, how config?

**Comment by htuch** [comment]
Fault filter is not the right choice for this. I don't think we have any traffic shaping support like this in Envoy, @mattklein123 @tonya11en for thoughts.

**Comment by tonya11en** [comment]
I don't think there's a way for Envoy to understand your client's protocol out-of-the-box, so you'd probably have to implement a custom filter for that. It seems like local/global rate limit filters would be of much help either since they are limiting connections or keys sent to a ratelimit service.

@Chwetion can you be more specific about what it is you're hoping to accomplish? Mainly, zoom in on what you mean by **client** and whether you're trying to ratelimit specifically file uploads (or some other protocol) or all network traffic. Also, are you hoping for hard-limits or "best effort" beyond some configured threshold?

**Comment by mattklein123** [comment]
The fault filter does have bandwidth limiting. Whether it's the right thing to use for your case is a different question. It's possible that functionality could be moved into an independent filter.

**Comment by Chwetion** [comment]
client means downstream, it will call upstream(tomcat)'s upload file interface. @tonya11en 
i think i want like this issue: https://github.com/envoyproxy/envoy/issues/6551

**Comment by Chwetion** [comment]
is there any doc for this? @mattklein123 


> The fault filter does have bandwidth limiting. Whether it's the right thing to use for your case is a different question. It's possible that functionality could be moved into an independent filter.

**Comment by mattklein123** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/fault_filter

**Comment by htuch** [comment]
Seems like a traffic shaping filter the factors this functionality out would be cleanest, since the goals of production traffic shaping might not always align with fault testing.

**Comment by mattklein123** [comment]
> Seems like a traffic shaping filter the factors this functionality out would be cleanest, since the goals of production traffic shaping might not always align with fault testing.

Agreed

**Comment by Chwetion** [comment]
@htuch does the community currently have plans for bandwidth limit filter?
@mattklein123 i already use http fault filter but not my expected, it cannot limit downstream upload file to upstream speed. i see just response_rate_limit, i think upload should use request rate limit.
java upload file demo application: https://github.com/Chwetion/upload-demo

**Comment by htuch** [comment]
@Chwetion not that I know of, I suggest opening a tracking issue (or converting this issue into that).

**Comment by tonya11en** [comment]
If this is to be locally enforced, it should be fairly easy to implement since we already have the pieces in various other filters.

@Chwetion can you give an example of how you think the configuration proto should look? Would be nice to also update the description of this issue to reflect where we are in this discussion.

**Comment by nitgoy** [comment]
I'm also interested in a bandwidth limiting filter. I'm working on a design doc based off the fault filter design and other requirements. I'll upload it soon for review.

**Comment by nitgoy** [comment]
@mattklein123 @htuch @tonya11en forgot to ask before - are you guys ok with me taking a stab at this extension and that it is not already under development. Please also let me know if there's any specific design template to be followed.

**Comment by tonya11en** [comment]
I don't think anyone has started on this yet. How do you imagine the proto config should look?

**Comment by nitgoy** [comment]
Thanks @tonya11en. Here's my planned proto config:

`
message BandwidthLimit {
  // Defines the mode for the bandwidth limit filter.
  // Values represent bitmasks.
  enum EnableMode {
      // Filter is disabled.
      Disabled = 0;
      // Filter enabled only for Ingress traffic.
      Ingress = 1;
      // Filter enabled only for Egress traffic.
      Egress = 2;
      // Filter enabled for both Ingress and Egress traffic.
      IngressAndEgress = 4;
  }

  // The human readable prefix to use when emitting stats.
  string stat_prefix = 1 [(validate.rules).string = {min_len: 1}];

  // The enable mode for the bandwidth limit filter.
  // Default is Disabled.
  EnableMode enable_mode = 2 [(validate.rules).enum = {defined_only: true}];;

  // The limit supplied in KiB/s.
  //
  // .. note::
  //   It's fine for limit_kbps to be unset for the global configuration since the bandwidth limit
  //   can be applied at a the virtual host or route level. Thus, the limit_kbps must be set for the
  //   per route configuration otherwise the config will be rejected.
  //
  // .. note::
  //   When using per route configuration, the limit becomes unique to that route.
  //
  uint64 limit_kbps = 3 [(validate.rules).uint64 = {gte: 1}];

  // Optional fill_rate for the token buckets (per second). Defaults to 64.
  uint64 fill_rate = 4 [(validate.rules).uint64 = {gte: 1}];

  // If set, the bandwidth limit will be applied only when the total dataplane bandwidth usage
  // crosses this value. Defaults to 0 meaning limits are always applied.
  uint64 enable_threshold_kbps = 5 [(validate.rules).uint64 = {gte: 1}];
}
`

**Comment by nitgoy** [comment]
Let me know any feedback on it. Regarding the last param, any pointers on the best way to monitor the current total bandwidth usage?

**Comment by tonya11en** [comment]
@nitgoy this looks great! Let's have the discussion in a PR though so we can comment on lines and whatnot. I think you can just open up a draft PR with that proto and then publish it with the implementation when you're ready for folks to review.

**Comment by nitgoy** [comment]
Sure, here you go: https://github.com/envoyproxy/envoy/pull/14096

**Comment by nitgoy** [comment]
Sorry for the long wait but now I have added the filter code with UTs. I'm working on the docs changes and few more tests. Please take a look at the PR and let me know your thoughts.

**Comment by shou1dwe** [comment]
Is there a TCP flavor of this available? a filter to limit bandwidth per TCP connection

**Comment by nitgoy** [comment]
No, I only added http version. Doing it at network filter will require the high/low watermark capabilities in the network filter callbacks which I believe are not currently exposed there.
