### ISSUE TITLE
Document the behaviour of JWT Authentication if the remote JWKS fetch failed

### ISSUE THREAD

**Issue by gontard** [envoyproxy/envoy#13705]
*Title*: *Document the behaviour of JWT Authentication if the remote JWKS fetch failed*

*Description*:
It isn't explicit in the documentation (or i haven't find it) what happens if for some reasons (misconfiguration, network errors...) the JWKS fetching fails.

In this situation (no available JWKS):
- What's happen if [`allow_missing`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto.html?highlight=allow_missing_or_failed#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtrequirement-allow-missing) is set and a token is provided or not?
- Same if [`allow_missing_or_failed`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto.html?highlight=allow_missing_or_failed#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtrequirement-allow-missing-or-failed) is set?

Also:
- Is there a retry policy to fetch the JWKS?

**Comment by qiwzhang** [comment]
For remote JWKS fetching.  The fetching happens at the request processing time which the JWKS is needed.  If fetching fails, the original request will fail with 401.

There is not re-try.  The next request that needs that JWKS will trigger a fetch again. 

if `allow_missing` flag is set, the request still fail since the error is not JwtMissing. 
if `allow_missing_or_failed` is set, the request will be ok.  It allows any errors.

**Comment by gontard** [comment]
Crystal clear 👍 
thanks for your answer!

**Comment by gontard** [comment]
@qiwzhang another question, in case `allow_missing_or_failed` is set, is there a way (a header?) for the next filter or for an upstream server to know if the JWT verification failed because the client didn't send a valid one or because the server failed to fetch the JWKS?

**Comment by qiwzhang** [comment]
For the next filter, yes,  the verification status is saved in stream_info responseCodeDetail.   No, for upstream server.
