### ISSUE TITLE
External Auth v3 missing http_service support

### ISSUE THREAD

**Issue by cgthayer** [envoyproxy/envoy#13718]
*Title*: External Auth v3 missing http_service support (has grpc_service)

*Description*:
Looking at the proto:

https://github.com/envoyproxy/envoy/blob/8281dd61867bfa7cf67c54389190c29ecac8d76d/api/envoy/extensions/filters/network/ext_authz/v3/ext_authz.proto#L27

Looks like `http_service` was removed or accidentally dropped.  I would suggest leaving it in since it's usually a localhost connection it may actually be faster on http2 than grpc.

On the other hand, if it's going away, please update the `envoy/examples/ext_authz` to get rid of the `http_service.yaml` and related stuff.

Thanks

**Comment by mattklein123** [comment]
@dio ?

**Comment by dio** [comment]
@cgthayer Seems like we don't have `http_service` options for network filter since https://github.com/envoyproxy/envoy/blob/release/v1.12/api/envoy/config/filter/network/ext_authz/v2/ext_authz.proto until now (including the v3 API). Currently, we only support `http_service` for HTTP filter https://github.com/envoyproxy/envoy/blob/8281dd61867bfa7cf67c54389190c29ecac8d76d/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L41-L42 (this is the save revision as yours).

**Comment by cgthayer** [comment]
@dio Not sure I follow.  Can we clarify if ext_authz servers can no longer be implemented in http and *must* be ported gRPC?  Or is that in the works and coming soon for v3?  
If it's going away, can someone update the examples to remove the external auth servers that work over http? (I can create a separate issue if we need one for that)
I have one that I'll need to port to gRPC in c# (don't ask) and that's somewhat painful, and I suspect there may be others who have http external auth servers as well.  I normally prefer gRPC but for this case (server is always on the same node) it seems like overkill and I suspect uses more CPU (but haven't tested).
