### ISSUE TITLE
close(FlushWrite) doesn't write pending data

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#13890]
From: https://github.com/envoyproxy/envoy/pull/13858#discussion_r516958931

*Description*:

It looks that `close(FlushWrite)` doesn't flush any pending data.

*Repro steps*:

1. Checkout https://github.com/envoyproxy/envoy/pull/13858 (uses `close(NoFlush)`).
2. `$ bazel test //test/extensions/transport_sockets/tls:ssl_socket_test --test_arg="--gtest_filter=*Shutdown*"`
3. Apply patch from https://github.com/envoyproxy/envoy/pull/13858#discussion_r516958931 (uses `close(FlushWrite)`).
4. `$ bazel test //test/extensions/transport_sockets/tls:ssl_socket_test --test_arg="--gtest_filter=*Shutdown*"`

*Logs*:

With `close(NoFlush)`:
```
[C1] socket event: 3
[C1] write ready
[C1] read ready. dispatch_buffered_data=false
[C1] socket event: 3
[C1] write ready
[C1] writing 5 bytes, end_stream false
[C1] closing data_to_write=5 type=1
[C1] ssl write returns: 5
[C1] SSL shutdown: rc=0
[C1]
[C1] closing socket: 1
```

With `close(FlushWrite)`:
```
[C1] socket event: 3
[C1] write ready
[C1] read ready. dispatch_buffered_data=false
[C1] socket event: 3
[C1] write ready
[C1] writing 5 bytes, end_stream false
[C1] closing data_to_write=5 type=0
[C1] closing socket: 0
[C1] SSL shutdown: rc=0
[C1]
```
Note missing `ssl write returns: 5`.

cc @ggreenway @antoniovicente

**Comment by antoniovicente** [comment]
This seems a bit mysterious.

Could it be related to SslSocket doing the following:
bool canFlushClose() override { return info_->state() == Ssl::SocketState::HandshakeComplete; }

Pre-handshake complete FlushWrite and NoFlush should be equivalent for SSL sockets given how ConnectionImpl::close is implemented.

**Comment by PiotrSikora** [comment]
@antoniovicente this is after the handshake.

But looking at `ConnectionImpl::close()`, I'm a bit puzzled by the current implementation. Why is it data flushed only for `NoFlush`? Shouldn't it be something like this: https://github.com/envoyproxy/envoy/pull/13892?

**Comment by antoniovicente** [comment]
> @antoniovicente this is after the handshake.
> 
> But looking at `ConnectionImpl::close()`, I'm a bit puzzled by the current implementation. Why is data flushed only for `NoFlush`? Shouldn't it be something like this: #13892?

The flush paths reset the event registration mask so it includes Write, so the dispatcher should do a event wakeup on the connection if the connection was already writable or becomes writable before the close timeout elapses. It would be good to understand why some of that is not happening, or if the event that gets delivered is Close instead of Write.  I'll try to checkout your changes sometime tonight and add some some logging to understand what is happening.

**Comment by antoniovicente** [comment]
See: https://github.com/envoyproxy/envoy/pull/13858/files/ca79634eb889c3de0c51b74989d3d6704ef4265f#r517692030

**Comment by PiotrSikora** [comment]
Thanks, @antoniovicente! Nice debugging. Since this issue can happen only with mocks, I think we can close this now.

(Feel free to reopen if you disagree).

**Comment by antoniovicente** [comment]
One thing to consider is detecting this case where a call to close can lead to weird behavior.  I don't know what operations are expected/allowed from certain callback hooks. Should we have a goal to avoid doing work in arbitrarily nested stacks in order to reduce code complexity?

We also need good ways to write tests like the one you wrote. I think that a possible work around is to use dispatcher_->post(...) to schedule work once the current stack is unrolled.
