### ISSUE TITLE
Where did envoy allocate the read/write buffer?

### ISSUE THREAD

**Issue by hazelnutsgz** [envoyproxy/envoy#13961]
When checking the buffer implementation, I traced the implementation of ```OwnedSlice``` and ```Slice```, and find the initialization 
```
OwnedSlice(uint64_t size) : Slice(0, 0, size) { base_ = storage_; }
```

But by search the whole codebase, I have no clues about where ```storage_``` is assigned with the allocated memory, which confused me for quite a long time. Is there any clues for that?

Thanks, @brian-pane

**Comment by hazelnutsgz** [comment]
Is this related to the placement-new stuff? Like
``` std::unique_ptr<OwnedSlice> slice(new (slice_capacity) OwnedSlice(slice_capacity));```

**Comment by lambdai** [comment]
This is probably a c++ question.
`storage_` is an array name but not a pointer.
Actually array name is a non-modifiable lvalue. You cannot assign it value.

**Comment by hazelnutsgz** [comment]
> This is probably a c++ question.
> `storage_` is an array name but not a pointer.
> Actually array name is a non-modifiable lvalue. You cannot assign it value.

The declaration of storage_ is ```uint8_t storage_[]```, so where did envoy allocate the memory for this array? (There should be some stuff like new/malloc, or memory pool to associate with ```storage_```, but I did not find it).

**Comment by antoniovicente** [comment]
Yes, OwnedSlice uses an exotic, custom C++ new operator defined by the [InlineStorage](https://github.com/envoyproxy/envoy/blob/d62a3882e584c591cddb2d7a5d0752312bd07344/source/common/common/utility.h#L631) mixin base class which allocates a memory block for for the size of the object plus an extra variable size region.  Note the OwnedSlice::storage_ array data member that doesn't have a pre-defined size, it's address is at the start of the variable length region after the OwnedSlice's fixed size data members.

[OwnedSlice::create](https://github.com/envoyproxy/envoy/blob/d62a3882e584c591cddb2d7a5d0752312bd07344/source/common/buffer/buffer_impl.h#L266) is in charge of allocating the variable size object and feeding the size of the variable size section to the object's constructor.  To complicate things further, OwnedSlice uses [sliceSize](https://github.com/envoyproxy/envoy/blob/d62a3882e584c591cddb2d7a5d0752312bd07344/source/common/buffer/buffer_impl.h#L294) to round the requested capacity passed in to the create function so that the allocated OwnedSlice always consumes a multiple of the page size, which Envoy assumes is 4kb in size.

**Comment by antoniovicente** [comment]
I changed how slice allocation works a while ago.  It's less subtle now.

See https://github.com/envoyproxy/envoy/pull/14111 and https://github.com/envoyproxy/envoy/pull/14282
