### ISSUE TITLE
Add support for musl libc

### ISSUE THREAD

**Issue by aheadmode** [envoyproxy/envoy#13998]
WIP

**Comment by lizan** [comment]
What's the goal of supporting musl libc? I did an native build in Alpine a year-ish ago (https://github.com/tetratelabs/getenvoy-package/tree/master/alpine) but didn't find it really useful. There will be a heavy performance drawback (I didn't precisely measure it but about 30% in my benchmark), because musl malloc/free cannot be safely replaced, see https://github.com/gperftools/gperftools/issues/693 for more context.

**Comment by aheadmode** [comment]
I wasn't aware about your native Alpine port. Did you try to build it with musl + [mimalloc](https://github.com/microsoft/mimalloc)?

Let me know what you think

https://www.linkedin.com/pulse/testing-alternative-c-memory-allocators-pt-2-musl-mystery-gomes/

**Comment by lizan** [comment]
No, I don't think mimalloc exists at that time. I'm not sure how its performance characteristic will be, but you should be able to try it out by building Envoy without tcmalloc (`--define=tcmalloc=disabled`), and use `LD_PRELOAD` to load mimalloc. It would be nice to see whether it can provide comparable performance.

**Comment by aheadmode** [comment]
I'm looking into that and I'll let you know here

**Comment by pjjw** [comment]
for the record, musl now supports replacement mallocs.

**Comment by PoneyClairDeLune** [comment]
So any updates on musl support?
