### ISSUE TITLE
Questions re OAuth2 plugin behaviour

### ISSUE THREAD

**Issue by andye2004** [envoyproxy/envoy#14075]
In the docs for the OAuth2 plugin it contains the following bullet point:-

> - Upon receiving an access token, the filter sets cookies so that subseqeuent requests can skip the full flow. These cookies are calculated using the hmac_secret to assist in encoding.

I'm wondering what this means in practical terms, e.g. is the access token sent back to the client as part of the cookie content? Or, is it an 'opaque' cookie that is sent and when subsequent requests are received from the client the access token is retrieved from some internal cache and added to the upstream requests?

This actually leads to another question, and, again quoting from the docs:

> When the authn server validates the client and returns an authorization token back to the OAuth filter, no matter what format that token is, if forward_bearer_token is set to true the filter will send over a cookie named BearerToken to the upstream. Additionally, the Authorization header will be populated with the same value.

If the access token is returned as part of the cookie content, the client will not then populate the `Authorization` header value, it will simply send the cookie in all subsequent requests. In this instance what is the plugins behaviour? Does it extract the value from the BearerToken cookie and insert it as the `Authorization` header, or does this header value remain unset?

My final questions relate to cookie expiry, is it a simple session cookie that expires when the browser is closed? Also, if there is any kind of session cache in the plugin, is there a built in expiration based on inactivity, and if so what is the inactive period?

Apologies for asking these questions rather than simply testing the scenarios for myself but I'm not currently able to test things out.

Thanks in advance!

**Comment by junr03** [comment]
@williamsfu99 perhaps you can address these questions?

**Comment by williamsfu99** [comment]
@junr03 Thanks for the tag.

@andye2004 
> e.g. is the access token sent back to the client as part of the cookie content? Or, is it an 'opaque' cookie that is sent and when subsequent requests are received from the client the access token is retrieved from some internal cache and added to the upstream requests?

After the OAuth flow completely finishes, the client receives a response with SetCookie headers for an HMAC value and an Expiry epoch. The HMAC value is calculated by concatenating the domain, expiration, and token together before hashing it using the hmac-sha256(hmac_secret, data) function. Consequently, when that same user visits the domain again, the filter will first inspect these Cookie values, independently perform the same hash function, and compare these two values to validate the session; if this succeeds, the filter verifies that the current epoch is not larger than the Expiry cookie. As you may realize, the filter is stateless and the ability to auto-skip authentication is powered entirely by the exact contents of these explicit cookies. No internal cache.

> If the access token is returned as part of the cookie content, the client will not then populate the Authorization header value, it will simply send the cookie in all subsequent requests. In this instance what is the plugins behaviour? Does it extract the value from the BearerToken cookie and insert it as the Authorization header, or does this header value remain unset?

The first behavior - it will extract the value from the BearerToken cookie and insert it into the Authorization header. This is an unconventional pattern but its purpose is to help the upstream expect consistently populated Authorization headers (when the boolean `forward_bearer_token` is flipped to true).

> My final questions relate to cookie expiry, is it a simple session cookie that expires when the browser is closed? Also, if there is any kind of session cache in the plugin, is there a built in expiration based on inactivity, and if so what is the inactive period?

The cookies do not expire when the browser is necessarily closed - they are your standard HTTP Cookie headers with the `secure` and `httpOnly` flags enabled. The expiration epoch is determined from the `expires_in` field within the JSON response body received from the token_endpoint. Unless you clear these cookies in your browser, they will continue to be sent up until expiration.

Hope this helps - I do recognize that the filter needs some work before it can be widely adopted. We had to prune the filter substantially to omit proprietary interactions and the outcome is an oversimplified authentication plugin. Some improvements we need:
* The filter should perform relevant data fetches - such as username - using the extracted token and pass them upstream for you, instead of expecting the upstream to do so.
* Token signing from the token server should be supported, so that clients cannot arbitrary send invalid bearer tokens.

**Comment by juanvasquezreyes** [comment]
> @junr03 Thanks for the tag.
> 
> @andye2004
> 
> > e.g. is the access token sent back to the client as part of the cookie content? Or, is it an 'opaque' cookie that is sent and when subsequent requests are received from the client the access token is retrieved from some internal cache and added to the upstream requests?
> 
> After the OAuth flow completely finishes, the client receives a response with SetCookie headers for an HMAC value and an Expiry epoch. The HMAC value is calculated by concatenating the domain, expiration, and token together before hashing it using the hmac-sha256(hmac_secret, data) function. Consequently, when that same user visits the domain again, the filter will first inspect these Cookie values, independently perform the same hash function, and compare these two values to validate the session; if this succeeds, the filter verifies that the current epoch is not larger than the Expiry cookie. As you may realize, the filter is stateless and the ability to auto-skip authentication is powered entirely by the exact contents of these explicit cookies. No internal cache.
> 
> > If the access token is returned as part of the cookie content, the client will not then populate the Authorization header value, it will simply send the cookie in all subsequent requests. In this instance what is the plugins behaviour? Does it extract the value from the BearerToken cookie and insert it as the Authorization header, or does this header value remain unset?
> 
> The first behavior - it will extract the value from the BearerToken cookie and insert it into the Authorization header. This is an unconventional pattern but its purpose is to help the upstream expect consistently populated Authorization headers (when the boolean `forward_bearer_token` is flipped to true).
> 
> > My final questions relate to cookie expiry, is it a simple session cookie that expires when the browser is closed? Also, if there is any kind of session cache in the plugin, is there a built in expiration based on inactivity, and if so what is the inactive period?
> 
> The cookies do not expire when the browser is necessarily closed - they are your standard HTTP Cookie headers with the `secure` and `httpOnly` flags enabled. The expiration epoch is determined from the `expires_in` field within the JSON response body received from the token_endpoint. Unless you clear these cookies in your browser, they will continue to be sent up until expiration.
> 
> Hope this helps - I do recognize that the filter needs some work before it can be widely adopted. We had to prune the filter substantially to omit proprietary interactions and the outcome is an oversimplified authentication plugin. Some improvements we need:
> 
> * The filter should perform relevant data fetches - such as username - using the extracted token and pass them upstream for you, instead of expecting the upstream to do so.
> * Token signing from the token server should be supported, so that clients cannot arbitrary send invalid bearer tokens.

Another enhancement is to add authorization mechanism such as group validations or roles validation and based on that deny or approved the request

**Comment by juanvasquezreyes** [comment]
> Hope this helps - I do recognize that the filter needs some work before it can be widely adopted. We had to prune the filter substantially to omit proprietary interactions and the outcome is an oversimplified authentication plugin. Some improvements we need:
> 
> * The filter should perform relevant data fetches - such as username - using the extracted token and pass them upstream for you, instead of expecting the upstream to do so.
> * Token signing from the token server should be supported, so that clients cannot arbitrary send invalid bearer tokens.

Another enhancement is to add authorization mechanism such as group validations or roles validation and based on that deny or approved the request and forward to the cluster

**Comment by andye2004** [comment]
I meant to respond to this before now but other things got in the way and I forgot, apologies. I just wanted to thank everyone, especially @williamsfu99, for commenting and clearing up some things. I'm sure in the longer term this will prove to be a very valuable plugin, but, for the moment at least, we will look at alternatives methods of implementing oauth/oidc at the proxy level.
