### ISSUE TITLE
compression doesn't work with a streaming HTTP/2 upstream

### ISSUE THREAD

**Issue by SaveTheRbtz** [envoyproxy/envoy#14121]
*Title*: compression doesn't work with an HTTP/2 backend

*Description*:
If I understand existing code correctly then compression won't be applied to streaming responses returned by an HTTP/2-capable backend:
https://github.com/envoyproxy/envoy/blob/ca6e246336a6c454132b5c832d483b8e9aa10ca2/source/extensions/filters/http/common/compressor/compressor.cc#L396-L397

*Repro steps*:
Enable h2 to the backend, enable compressor, use streaming-capable upstream.

cc: @rojkov

**Comment by antoniovicente** [comment]
You're right, the compression filter doesn't seem to like to process responses without content-length or transfer-encoding: chunked.  It's possible that the fix is as simple as returning true if the response doesn't have a content length, but we should also consider the case of HEAD requests and 204 no content responses.
