### ISSUE TITLE
Dependency: upgrade nghttp2 to 1.42.0

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#14174]
*Title*: Dependency: upgrade nghttp2 to 1.42.0

*Description*: Latest version 1.42.0 ([release notes](https://github.com/nghttp2/nghttp2/releases/tag/v1.42.0)) does not contain the PR that would upstream the patch at https://github.com/envoyproxy/envoy/blob/master/bazel/repositories.bzl#L389-L394. Patch needs to be updated for Windows and new nghttp2 version.

Assign @wrowe, @sunjayBhatia

CC @envoyproxy/dependency-watchers

**Comment by htuch** [comment]
@wrowe would you be able to help out with updating this patch?

**Comment by wrowe** [comment]
I'm happy to help with the patch, today I evaluated the entire patch... and am looking to replace the windows bits with priming the cmake cache with the appropriate flags, and dropping the patch with a single-target define. It doesn't help that bazel is unmaintained and hasn't addressed the missing copts parameter in the year since we identified https://github.com/bazelbuild/rules_foreign_cc/issues/301 - Lizan and I each stumble over this, so help finding any triage at all might move something.

If I can inject the define ssize_t=ptrdiff_t into the build without the patch, carry this to the curl and other deps, we already cover this in platform.h, and it cmake nghttp2 treats the sizeof ssize_t as defined as ptrdiff_t as valid, the patch for windows thankfully disappears. It has an open issue upstream to be addressed upon a 2.0 release, should that ever happen.

There are a host of other corrections, but they were reinterpreted by @tatsuhiro-t as avoiding incrementing the end pointer provided there is a given length, rather than a NULL base pointer. I believe, and @lizan as the maintainer should really confirm, that what the old patch accomplished was to avoid incrementing a NULL pointer when the base pointer was NULL, avoiding an actually toxic injection. It seems like a wise thing to continue to do, but you'll need to go back to the original patch authors and Tatsuhiro-san to determine intent and risk, or whether the nghttp2 project has thoroughly obsoleted the rest of this muddled patch.

**Comment by wrowe** [comment]
The patch in question, for reference;
https://github.com/envoyproxy/envoy/blob/master/bazel/foreign_cc/nghttp2.patch

**Comment by wrowe** [comment]
@asraa could you validate that your proposed fixes, as still recorded in nghttp2.patch, can all be dropped in favor of the code adopted in 1.42.0?
https://github.com/nghttp2/nghttp2/pull/1468/files
vs.
https://github.com/nghttp2/nghttp2/commit/78a56cf66f3bbe29f70b19eeaff0dbc63908c677
https://github.com/nghttp2/nghttp2/commit/cf094bd56bd3fbe0037fc72a2ebcee3cb7724b90
https://github.com/nghttp2/nghttp2/commit/1ecc7940b858f5f1d84658e8502a1dcba1ec4578

I'll continue to work on a better workaround for the Windows ssize_t mess, there is also some slight drift here of that first patch segment vs. the later proposed https://github.com/nghttp2/nghttp2/pull/1395/files

**Comment by asraa** [comment]
@wrowe I think they should be fine. They were to fix a runtime error when building and running tests with clang-10. Instead of checking if the pointer was null, the fixes seem to check if the offset is zero.

**Comment by wrowe** [comment]
@asraa That's what concerns me. NULL+0 is no different than NULL, so it wouldn't be an interesting test, but ensuring we don't play with any math modulo NULL is actually rather important. The resulting patch looks like quite a few no-ops.

**Comment by wrowe** [comment]
Before I take this further, @htuch (or @lizan) can you point out what I'm doing wrong in attempting to use a select in this emulation of copts for foreign_cc cmake logic below?
https://github.com/wrowe/envoy/commit/edeb9457072c7375675c9f674c4f2ce58fa0d955

If we can work around that, we seem ready to drop nghttp2 exception handling.

My current results are unfortunate, select isn't evaluated;
```
    FAILED: CMakeFiles/cmTC_92a43.dir/testCCompiler.c.obj
    c:\PROGRA~1\LLVM-1~2.0\bin\clang-cl.exe  /nologo   /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE
 /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /showIncludes /MT /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="re
dacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -DCARES_STATICLIB -DNGHTTP2_STATICLIB -DCURL_STATICLIB -Wno-macro-redefin
ed -Wno-builtin-macro-redefined -Wno-inconsistent-missing-override select({;//bazel:windows_x86_64": "-Dssize_t=ptrdiff_t", "//conditions:
default": ";}) /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_92a43.dir\testCCompiler.c.obj /FdCMakeFile
s\cmTC_92a43.dir\ -c testCCompiler.c
    clang-cl: error: no such file or directory: 'select({;//bazel:windows_x86_64: -Dssize_t=ptrdiff_t, //conditions:default: ;})'
```

**Comment by htuch** [comment]
@wrowe see https://docs.bazel.build/versions/master/configurable-attributes.html#why-doesnt-select-work-in-macros re: the use of `copt_str`.

**Comment by moderation** [comment]
Not stale. We still need to work through the patch issues and bump /cc @wrowe

**Comment by wrowe** [comment]
Yes, we need to work through this. Google has been less than helpful in explaining how I can rearchitect this, @htuch, as a bazel select. But there is no reason not to simply port the patch and bump to the new release and solve that issue later to drop the patch, it can't be cured upstream without v2.

**Comment by htuch** [comment]
I think https://github.com/envoyproxy/envoy/issues/14174#issuecomment-737588366 explains the existing situation around select fairly clearly; you simply can't perform a select operation on a macro argument when the macro is consuming the value (e.g. where you do `str` and condition on it). You can do either a rule or figure out some way to select condition on the value passed directly to a rule.

The problem IMHO is we're trying to do too much custom logic in macro form in `envoy_cmake_external`, we would be better off making this a rule extending what `cmake_external` does.
