### ISSUE TITLE
What will happen when `Envoy::logger::DelegatingLogSink` is destructed?

### ISSUE THREAD

**Issue by panzhongxian** [envoyproxy/envoy#14211]
I read the code in logger.h.  There is a comment in line [logger.h#153](https://github.com/envoyproxy/envoy/blob/master/source/common/common/logger.h#L153):

> Stacks logging sinks, so you can temporarily override the logging mechanism, restoring the previous state when the DelegatingSink is destructed.

There is no class named "DelegatingSink", so I think it's maybe a typo.

I can't find the destructor of `DelegatingLogSink`. My question is what will happen when `Envoy::logger::DelegatingLogSink` is destructed. Or the `SinkDelegate* sink_` being deleted has nothing to do with DelegatingLogSink?

I can understand the SinkDelegate is using to stack the sinks and DelegatingSink will use the SinkDelegate to log actually.

But it's a little confusing. Can anyone help me to fingure out the relation between DelegatingLogSink and SinkDelegate more clearly? Thanks.

**Comment by jmarantz** [comment]
There's no explicit destructor of DelegatingLogSink, but that class includes a unique_ptr<StderrSinkDelegate>, and StderrSinkDelegate has a destructor which calls restoreDelegate().

This code is a bit confusing however. I think it might be easiest to understand it by grepping for use-cases. If you do you'll find that mostly it is used during tests to redirect logging into a string so that log content can be unit-tested. See the macros in test/test_common/logging.h for example uses. Then you can grep for uses of those macros in test/...

I don't *think* there are current uses of temp logging sinks in production code but there are some similar looking blocks of code in the Quic support code, however that's a separate log-sink mechanism.

Feel free also to write PR correcting the typo and explaining better :)

**Comment by panzhongxian** [comment]
Thanks for your quick explaination~ @jmarantz 

I had excluded the testing files which made me miss some details. I will find more use-cases in testing files for more detail. 

I am going to close the issue. Once I find more detail, I will append the explaination here.
