### ISSUE TITLE
Changes in host weight does not transition load balancer between weighted and unweighted mode

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#14360]
Some of the load balancers (random, LR, etc.) operate in different modes when all the hosts within a host source (all hosts, individual localities, etc.) are weighted or unweighted. The check to see which mode to operate in happens in 
```
void EdfLoadBalancerBase::refresh(uint32_t priority) {
  const auto add_hosts_source = [this](HostsSource source, const HostVector& hosts) {
    // Nuke existing scheduler if it exists.
    auto& scheduler = scheduler_[source] = Scheduler{};
    refreshHostSource(source);

    // Check if the original host weights are equal and skip EDF creation if they are. When all
    // original weights are equal we can rely on unweighted host pick to do optimal round robin and
    // least-loaded host selection with lower memory and CPU overhead.
    if (hostWeightsAreEqual(hosts)) {
      // Skip edf creation.
      return;
    }

    scheduler.edf_ = std::make_unique<EdfScheduler<const Host>>();
```
which is triggered by the `updateHosts` calls propagated from the main thread on a config update.

The problem arises when considering a host weight only change: as an optimization, Envoy does not trigger `updateHosts` calls for certain changes to the host set. The rationale here is that the lb structures will eventually pick up on the host weight since they periodically read the host weight (stored in an atomic). While this is true for most host weight updates, some updates will require the load balancer to create/delete the EDF scheduler, requiring a full update.

The consequence of this generally will be that certain changes to host weights won't be visible to the load balancer until another update is made that triggers a full update.

Solving this in a good way is a bit tricky: at first it seems like simply checking each priority to see if it transitioned between weighted to unweighted would be sufficient, but the presence of localities and health makes it more complicated. To correctly handle this kind of update, we'd want to trigger a full refresh if any of the possible HostSets (all, healthy, degraded, healthy localities, degraded localities) transition between weighted and unweighted.

**Comment by mattklein123** [comment]
@snowp the latest convo in #edf-jitter Slack I think has us forcing a full refresh for any weight change which I think would also fix this? I was going to add this to my queue so I can assign this to myself unless you want to do this. cc @tonya11en @antoniovicente @htuch

**Comment by snowp** [comment]
Yep always doing a full update is the simplest way to solve this since it sounds like we're okay with losing atomic weight updates.

**Comment by antoniovicente** [comment]
I think I missed that host weights could change in such ways when I implemented the unweighted round robin memory optimization, but I wonder if the issue was pre-existing since the decision to process using weighted and unweighted depended on some stat that contained the highest weight.

**Comment by antoniovicente** [comment]
Doing incremental updates on weight changes seems like a fair bit of work, but may be worth the performance and pick continuity benefit.  If doing full updates on weight changes, picking could devolve to random picking if weight updates are frequent enough.

**Comment by mattklein123** [comment]
> Doing incremental updates on weight changes seems like a fair bit of work, but may be worth the performance and pick continuity benefit. If doing full updates on weight changes, picking could devolve to random picking if weight updates are frequent enough.

Yeah I agree. My thinking though is that weight changes are not very common in practice and I feel we can optimize this later if necessary. I think that is what we roughly agreed to in the Slack chat also.

**Comment by htuch** [comment]
Yeah, IIRC we agreed that there are few localities, so a rebuild is fine at that level, and we don't _currently_ have compelling reason to be doing weighted intra-locality (from Google side).

However, should we open this up to the community to verify? I'm pretty sure I've seen issues and questions in the past involved intra-locality weighting.

**Comment by mattklein123** [comment]
Yeah I think it's worth a discussion. I think within locality weights are ok, it's just a matter of how often they change. I'm practice I doubt they change very often. Also, we may be able to optimize both cases adaptively. I synced up with @tonya11en today and he is going to write up a summary of the entire issue for discussion.

**Comment by tonya11en** [comment]
If it's ok to do full updates on weight changes, I think there's a way to avoid devolving into a uniform selection probability even on the first pick. I think this can be used for picking both localities and endpoints. Dig this:

For each unique weight among all the objects, you create a queue and add all objects with that weight to the queue. The queue now gets its own weight which is the sum of all object weights contained within. Now when scheduling/picking, you perform a weighted selection of a queue and pop an object from the top. You can now add the object back with whatever weight you'd like. 

For the case where all object weights are the same, it's vanilla round-robin. If all object weights are different, it's weighted random selection. If you have half the objects with one weight and half with another, it's essentially weighted round-robin. Your first picks always honor your weights and there's no dependence on any cycle like most WRR schedulers. 

In the notorious example of 2 objects with weights 99:1, you have 2 queues with 1 object each. The object with weight 1 is picked 1% of the time as you'd expect. 

It's O(1) insertion. For picks, you can pre-process the scheduler and get O(log n) on the number of _unique weights_. If you don't pre-process, allowing for atomic weight changes, picks are linear on the number of unique weights. The pathological case here is large numbers of objects all with unique weights. Even then, I'm not convinced there's an appreciable performance penalty in practice.

You also don't get fleet syncing if you just insert hosts into the scheduler in a random order. 

It's super easy to implement, so I'll add this to my experiment branch on my Envoy fork and compare it to EDF and IWRR in the benchmarks, first pick, and temporal bunching tests. 

I will write up the summary of all those experiments and #edf-jitter posts in an issue as I promised @htuch. In the meantime,LMKWYT.

**Comment by mattklein123** [comment]
IMO moving to explicit refresh for weight changes will give us more algorithmic options. We can always optimize it further later (for example by fanning out weight deltas somehow).

The only thing I'm not sure of about the algorithm Tony proposes is whether it would be feasible to use it with weighted least request where effective weights are changing all the time. We can take it up in the other issue but the more I think about this the more I think the implementation probably has to be adaptive and there is no single impl that is going to work for all cases.

**Comment by htuch** [comment]
SG. I guess we could runtime guard explicit refresh and leave a grace period for folks to be able to raise any concerns, if there aren't any issues filed we can delete.

**Comment by tonya11en** [comment]
> The only thing I'm not sure of about the algorithm Tony proposes is whether it would be feasible to use it with weighted least request where effective weights are changing all the time. We can take it up in the other issue but the more I think about this the more I think the implementation probably has to be adaptive and there is no single impl that is going to work for all cases.

The approach I mentioned above isn't feasible for something like WLR, but EDF seems to be working just fine for that, no? My guess is that the first-pick determinism shouldn't matter for WLR because the weights are being adjusted constantly which would quickly change the ordering of the hosts based on the outstanding requests. There's not really a reason to discard EDF for WLR.

I wrote up the results of everything that I've investigated on the matter and appended it to that [PR I linked earlier](https://github.com/tonya11en/envoy/pull/1#issuecomment-744085044). Included in those results is all of the same tests run for the scheduling approach I mentioned above, which I'll call a Weighted-Random Selection Queue (WRSQ). Here are the highlights:

With respect to the first-pick determinism issue, EDF picks the same weight category 100% of the time, IWRR devolves into uniform random selection, and WRSQ honors the selection probabilities like we want.
1x host with weight 99
1x host with weight 1
```
[ RUN      ] WRRLoadBalancerTest.1stPickEDF
url:10.0.0.0:6379, weight:99, hits:10000, observed_hit_pct:100
```
```
[ RUN      ] WRRLoadBalancerTest.1stPickIWRR
url:10.0.0.0:6379, weight:99, hits:4990, observed_hit_pct:49.9
url:10.0.0.0:6379, weight:1, hits:5010, observed_hit_pct:50.1
```
```
[ RUN      ] WRRLoadBalancerTest.1stPickWRSQ
url:10.0.0.0:6379, weight:99, hits:98982, observed_hit_pct:98.982
url:10.0.0.0:6379, weight:1, hits:1018, observed_hit_pct:1.018
```

There was also a temporal bunching test, where we can see the weight categories being chosen over time. EDF perfectly spreads out its selections, IWRR clumps up all of the selections for a weight category, and WRSQ exhibits no bunching behavior at all. This matters because of what I'd mentioned to @mattklein123 a few days ago, we want selection probabilities to be honored for arbitrary time windows. IWRR doesn't make much sense if you're unable to complete a full cycle or if you're sensitive to bursts of request rates.

![image](https://user-images.githubusercontent.com/1109246/102027842-ac7b1d80-3d5b-11eb-808c-fdd7453910c3.png)
![image](https://user-images.githubusercontent.com/1109246/102027846-b0a73b00-3d5b-11eb-81f6-b0e0424b8605.png)
![image](https://user-images.githubusercontent.com/1109246/102027851-b4d35880-3d5b-11eb-8c7e-d5d69e4eee93.png)


* For cases where weights need to change on the fly, such as WLR, the EDF scheduler is still our best option.
* If you need the selection probabilities to be honored in any arbitrary time window, WRSQ seems to be the best bet.
* IWRR may be still be of use in special cases, but in general I think its temporal bunching renders it unusable for LBs.

**Comment by mattklein123** [comment]
Thanks @tonya11en. I agree that WRSQ seems like what we want for the non dynamic weight changing cases (like least request). I agree we can continue to use EDF for those cases. I'm going to work on a change that will cause a full rebuild for EDS weight changes and we can go from there.
