### ISSUE TITLE
Add stronger hash or comparison to xDS APIs

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#1452]
Some xDS APIs (e.g. LDS, RDS and EDS) ignore updates that hash to the value of the existing config. This is to avoid churn and overhead when there is no actual update. However, we use `std::hash` today for this and no further checks, which is probably not strong enough. We should either keep the original value of the config proto around for direct comparison or use a stronger hash that will guarantee improbable collisions.

**Comment by dnoe** [comment]
The actively loaded version of each xDS API can also be exposed as a stat or at an admin URL as part of this.

**Comment by htuch** [comment]
@dnoe Yeah, this will make writing an integration tests that validate version easier as well.

**Comment by htuch** [comment]
@mattklein123 Do you want hash in addition to `version_info` or instead of?

**Comment by htuch** [comment]
Assigned to @dnoe for triage.

**Comment by mattklein123** [comment]
Version info is most important (like we already do with stat for git sha) but hash wouldn't hurt either.

**Comment by htuch** [comment]
@mattklein123 @danielhochman should we also add the `versionInfo()` for all APIs to stats/admin? @kmyerson can take a look at this.

**Comment by mattklein123** [comment]
@htuch @kmyerson This is related to https://github.com/envoyproxy/envoy/issues/1453. Optimally, we would have version info and full dump for all the xDS endpoints, as well as a gauge for each version (hash of version) in stats.

This is a little complicated because we have an existing /listeners endpoint which we use only for integration tests currently, as well as the existing /clusters endpoint which dumps host info. So we need to sort this out.

@kmyerson if you want to generally work on ^ I think that would be very valuable for lots of people.

**Comment by mattklein123** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/1805
