### ISSUE TITLE
docs: Add documentation to site for installing Envoy on Windows

### ISSUE THREAD

**Issue by sunjayBhatia** [envoyproxy/envoy#14605]
*Description*:
The Envoy site documentation should include instructions/examples for installing on Windows.

*Relevant Links*:
- See: https://www.envoyproxy.io/docs/envoy/latest/start/install#
- Child issue of: https://github.com/envoyproxy/envoy/issues/13190

**Comment by sunjayBhatia** [comment]
cc @envoyproxy/windows-dev

**Comment by rajpratyush** [comment]
@sunjayBhatia  I would like to take up this issue. Although I am beginner but with a little guidance, I believe I can rectify this issue.

**Comment by sunjayBhatia** [comment]
Basically the intent of this was to add a a section similar to https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-using-docker specific to Windows. Windows container images can only be pulled from Docker hub at the moment so you can omit the "Get Envoy" tab. I think in addition to that adjusting some of the prose at the top of the page and this table https://www.envoyproxy.io/docs/envoy/latest/start/install#pre-built-envoy-docker-images would complete this issue

**Comment by pravb** [comment]
@rmiller14 can you please work on this? I will review.

**Comment by rmiller14** [comment]
For now I've just added a section referring to the envoy-windows-dev Docker image.

It should possible to pull down the EXE from the post-submit pipeline using [this API](https://docs.microsoft.com/sv-se/rest/api/azure/devops/build/artifacts/get%20artifact?view=azure-devops-rest-5.0).  The missing piece is the build ID, which can be passed in to docs/build.sh.  What's tripping me up mentally is the scenario where the docs stage in the pipeline runs and lists a link to the windows.release artifact, but that artifact either isn't ready or failed to build.  I'm also not even sure if the API call to get the link to the windows.release artifact would succeed since the docs stage in the pipeline usually finishes before the windows.release stage...

**Comment by wrowe** [comment]
https://github.com/envoyproxy/envoy/pull/15699 has resolved this issue based on available binaries following 1.18.0 release.
