### ISSUE TITLE
Cannot set an httpOnly cookie from python GRPC server. Envoy configs not correct?

### ISSUE THREAD

**Issue by kurnal-volt** [envoyproxy/envoy#14698]
*Title*: Cannot set an httpOnly cookie from python GRPC server. Envoy configs not correct?

*Description*:
I am trying to set an httpOnly Authorization cookie from my gRPC python server through an envoy proxy and back to my ReactJS front-end client running grpc-web. Currently, I can send a JWT back in a response, set it into local storage, and append it onto subsequent calls using a client side grpc-web-interceptor; however, I do know that using local storage for a JWT is not best practice. How can I make it so that running context.set_trailing_metadata('set-cookie', 'mycookie') from my python gRPC server actually set the cookie, because currently I do not see anything in the storage tag of development tools but I also simultaneously see the response cookie when checking the API call in the response tab.

Also, would it be possible to make envoy grab the authorization cookie on every request if it is there? I have read so many posts, but none of them match what I need to achieve.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by htuch** [comment]
It sounds like the cookie is sent back to the client based on what you say, as it appears in the API call response client-side, if I'm understanding what you wrote correctly. In that case, it sounds like your client is not correctly handling returned cookies; what happens if you have the client and server speak directly, without an Envoy between them?

**Comment by kurnal** [comment]
@htuch Thank you for the response! Envoy is used so the ReactJS client can communicate with the Python gRPC server. Without it we would get CORS cross-origin errors. Do you know of things I should check client side to make sure a cookie is set since it is in fact making it to the response (i can see it in developer tools).

Is there something in envoy that could possible be blocking a cookie from being set?

**Comment by htuch** [comment]
I don't see how this can be an Envoy issue if the `set-cookie` error is propagated intact to the client. Maybe this is some browser CORS/cookie/AJAX issue.
