### ISSUE TITLE
Files on host accessible to root are not available to envoy user within the container

### ISSUE THREAD

**Issue by chintan-mishra** [envoyproxy/envoy#14877]
*Title*: *Files on host accessible to root are not available to envoy user within the container*

*Description*:
I have certain files, accessible only to the `root` user on the host system, that I mount while starting Envoy for use in the `envoy.yaml`. However, the files are not accessible to the `envoy` user within the container. This is preventing upgrading from `v1.14.6` to any newer release.

A plausible hack is to use `chmod` and change the `envoy` user's permissions within the container. Allowing `envoy` user to read the file. This is a sub-optimal solution as the files are not meant to have their user permissions changed.

*Relevant Links*:
>I suspect this is the cause for issue https://github.com/envoyproxy/envoy/issues/13221

**Comment by mattklein123** [comment]
cc @phlax

**Comment by phlax** [comment]
> A plausible hack is to use chmod and change the envoy user's permissions within the container. Allowing envoy user to read the file. This is a sub-optimal solution as the files are not meant to have their user permissions changed.

if the files are not world readable, or more specifically are not readable by the envoy user, you can set the permissions correctly
before mounting them into the container.

you can do this either by changing their permissions on the host or by creating a custom docker image with the files added to the image with the correct permissions.

restricting the envoy user inside the container is a feature rather than a bug. If you wish to run as root inside the container, and disable thiis functionality, you can run the container with the env var `ENVOY_UID=0`

**Comment by phlax** [comment]
see here for more info about container permissions https://www.envoyproxy.io/docs/envoy/latest/start/docker#permissions-for-running-docker-envoy-containers-as-a-non-root-user

**Comment by chintan-mishra** [comment]
I couldn't agree more over running the EnvoyProxy as a non-root user within the container being a security feature instead of a bug. However, after spending a significant amount of time on LetsEncrypt it is evident that we should not change the permissions of the generated TLS certificates on the host. So, this was not an option. But I could surely try adding the files in a custom container and changing the permissions. For now, I am using `ENVOY_UID=0` environment variable.

Thanks @phlax
