### ISSUE TITLE
Downstream remote disconnect response

### ISSUE THREAD

**Issue by hinawatts** [envoyproxy/envoy#14908]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *What are possible scenarios where we get downstream_remote_disconnect  response ?*

*Description*:
>We are using envoy proxy to route requests based on header value to respective upstreams. While doing performance testing, few of our requests fail with response code details -  downstream_remote_disconnect. Wanted to understand when can we experience this ?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
This is set when the stream is terminated due to a downstream FIN.   If you're encountering a situation where that detail is set and a wireshark trace shows downstream isn't sending the FIN we'd be happy to look into it, but by default we'd assume it's client-caused at which point there's not much we can do to diagnose what's going on :-)
