### ISSUE TITLE
Zipkin tracer shouldn't always create a new span with a 'cs' annotation

### ISSUE THREAD

**Issue by clguimanMSFT** [envoyproxy/envoy#1497]
I noticed that Envoy is always creating a new span (when there's no context in the headers) with a CLIENT_SEND annotation: https://github.com/lyft/envoy/blob/master/source/common/tracing/zipkin/tracer.cc#L19

I think this is not always correct. Zipkin (http://zipkin.io/pages/instrumenting.html) expects to get the cs annotation in the outgoing request span (the client sends a request), but by default Envoy will also generate this for incoming requests that don't have the X-ot-context header.

Envoy should check the operation name, if it's "ingress" then it should generate a span with sr annotation and if it's "egress" generate the cs annotated span.

What do you think? If you're OK with the request, I'll work on the implementation and submit a PR.

**Comment by mattklein123** [comment]
@adriancole @rshriram @fabolive comments?

**Comment by rshriram** [comment]
Iirc this was intentional. Use of ingress and egress is not reliable in a istio deployment because a listener is shared for both inbound and outbound calls. E.g, envoy receives all inbound traffic into the pod on port 80 (trapped using iptables and using orig_dst listener) and also handles outbound traffic from pod (e.g. App sends req to another service on port 80). 

@fabolive would be able to provide better justification.

**Comment by mattklein123** [comment]
Can we just add appropriate options to make this work correctly? https://lyft.github.io/envoy/docs/configuration/http_conn_man/tracing.html already has ingress and egress? Seems like we could drive off of that option?

**Comment by adriancole** [comment]
I think @devinsba noticed this glitch, too. If there's a way to tell you are ingress, definitely that code should be annotated as a server. a child of that span would be the egress (client)

**Comment by fabolive** [comment]
@rshriram: Your recollection of the rationale behind this behavior is correct. Furthermore, at the time of this implementation, the "ingress" and "egress" tracing options were pretty much ad hoc and could not be safely relied on. @mattklein123 Yes, we could perhaps add another valid value to `operation_name` or some other option informing the code to fallback to the current behavior, and rely on "ingress" and "egress" when they are used. @rshriram This change will probably have implications for Istio. We need to make sure the configurations are generated accordingly.
I suggest that this work be tackled after #1364, since that issue requires changes throughout the entire path that processes Zipkin-related headers. In fact, I should provide my assessment to #1364 later today.

**Comment by objectiser** [comment]
@clguimanMSFT This should have been fixed by #1565 - operation_name (Egress/Ingress) is now used to determine whether client/server span. Would you be able to test and let us know?

**Comment by mattklein123** [comment]
Going to close this out. We can reopen if not fixed.
