### ISSUE TITLE
Incorrect min_rtt calculation in Adaptive concurrency

### ISSUE THREAD

**Issue by freedomljc** [envoyproxy/envoy#14997]
*Title*: *Incorrect min_rtt calculation in Adaptive concurrency*

*Description*:

Inside Lyft, we occasionally observed the extremely large value for the stats [min_rtt](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L117), which seems to be maximum value of unsigned long type (18.45 * 10 ^ 17); Subsequently, it caused [rq_blocked](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L195) and 503s to increase. 

My hypothesis is that 18.45 * 10 ^ 17 is caused by [hist_approx_quantile](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L156) on the empty latency histogram. There exists a chance that the method [updateMinRTT](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L111) gets invoked right after the method [resetSampleWindow](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L139). As [invoking processLatencySamplesAndClear in resetSampleWindow](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L147) clears the latency histogram, nan value will get returned when [updateMinRTT invokes processLatencySamplesAndClear](https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L116), eventually cause the issue.

**Comment by tonya11en** [comment]
This can be assigned to me and I'll take a look this evening. Should be straightforward to test the hypothesis via unit tests, so @freedomljc I can do this unless you were hoping to do so.

**Comment by tonya11en** [comment]
@freedomljc a few questions...

1) How is a large min_rtt value causing blocked requests? Was the concurrency limit being clamped down? This would only happen if the sampled RTT values exceed the minRTT by some threshold, so I'm unsure how that follows.

2) resetSampleWindow() can only occur if we're not currently inside of a minRTT measurement window. The minRTT measurement should be based on a request count, not a timer, and all effects from the sampling window can't happen as long as we're inside of a minRTT window. I may be missing something here, so can you give more details on the sequence of events that would lead to this condition you're hypothesizing?

**Comment by freedomljc** [comment]
Thanks @tonya11en for the follow-ups.
>1. How is a large min_rtt value causing blocked requests? Was the concurrency limit being clamped down? This would only happen if the sampled RTT values exceed the minRTT by some threshold, so I'm unsure how that follows.

I am also fuzzy about why a large min_rtt value would cause the issue. But here are the metrics about minRTT, sample_rtt and rq_blocked.  
<img width="1645" alt="Screen Shot 2021-02-09 at 2 46 10 PM" src="https://user-images.githubusercontent.com/6963707/107438841-0a22b080-6ae6-11eb-8e3a-5114d5b88457.png">
concurrency limit stats is not provided here as I am not sure whether the concurrency limit stats is meaningful: the stats keeps unchanged over time, and it was sampled every 10 minutes inside Lyft. 


> 2. resetSampleWindow() can only occur if we're not currently inside of a minRTT measurement window. The minRTT measurement should be based on a request count, not a timer, and all effects from the sampling window can't happen as long as we're inside of a minRTT window. I may be missing something here, so can you give more details on the sequence of events that would lead to this condition you're hypothesizing?

I previously tried to figure out the scenarios how the latency histogram is cleared out, but just realized there might exist another scenario: enterMinRTTSamplingWindow() could cause to clear the latency histogram as well. 

I wrote a unit test in https://github.com/envoyproxy/envoy/pull/15001/files. It tests against the scenario when the latency histogram is cleared out by enterMinRTTSamplingWindow(), the min_rtt value become 18446744073707404133.  I am not completely sure whether the events sequence makes sense or not in my test, but they would lead to this extremely large min_rtt value.

**Comment by freedomljc** [comment]
I just put a [draft pr](https://github.com/envoyproxy/envoy/pull/15004/files) to mitigate the issue: only process latency samples when the latency histogram is not empty. WDYT?

**Comment by tonya11en** [comment]
Alright, I think I know what's going on here. This condition is possible. It's not in `resetSampleWindow()`, but calls to `updateMinRTT()`! It's possible that 2 concurrent requests can succeed at the condition necessary to update the minRTT before one of them is able to update and pull us out of the minRTT window:
https://github.com/envoyproxy/envoy/blob/eb0ada654812af824bd682050f7d56cf1d591e64/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L218

The implications of this are not just getting the percentile on an empty histogram, but scheduling multiple `sampleRTT` update timers and creating noise in the measurements as the race condition is hit regularly. That's rough. Unfortunately, this problem won't be fixed by #15004.

This is going to require a compare/exchange to ensure that only a single thread is performing the minRTT update at a time or to periodically poll the sample aggregate every ~1s or so and perform the update on that dispatcher thread (but I recall @mattklein123 wasn't fond of that approach back when the filter was being implemented).

I can cook up a patch that I think fixes this and I'll add you on it @freedomljc. You pulled some serious wizardry catching this.

**Comment by tonya11en** [comment]
@freedomljc will be jumping in to make this change after our conversation on slack, but for posterity I'm posting the planned changes here.

All of the RTT mutations need to just occur on the dispatcher to avoid races and locking on the worker threads. The dispatchers will handle:
* Sample window resets.
* Entering minRTT windows.
* Updating minRTT values.
* Updating sampleRTT values.

There will be scenarios where mutation tasks are scheduled on the dispatchers using stale minRTT data, so there will also need to be a concept of a minRTT version that's passed when the tasks are being scheduled. This way if there is a minRTT update of some kind scheduled during an old version, we will disregard it if there was an unexpected update before it was able to execute.

It will also be prudent to sprinkle ThreadSynchronizer sync points around so we can easily test these scenarios and verify there aren't races.

**Comment by freedomljc** [comment]
@tonya11en , I just [drafted the pr](https://github.com/envoyproxy/envoy/pull/15060) to move the logic into the dispatcher thread, but found it might still cause this minRTT issue. Essentially, this minRTT issue was caused by the below event sequence:

1. Invoke the code block https://github.com/envoyproxy/envoy/blob/1b118df9a9ddab835f891b7458b8012f6d454dd8/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L119-L125
2. Invoke enterMinRTTSamplingWindow()
3. Invoke the code block  again https://github.com/envoyproxy/envoy/blob/1b118df9a9ddab835f891b7458b8012f6d454dd8/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L119-L125

The approach essentially moves the step 1 and step 3 into the same thread, but the above event sequence might still happen.  I think this minRTT issue seems unavoidable as long as we periodically invoke enterMinRTTSamplingWindow(). in this case, I wonder we should just mitigate the issue by checking whether the histogram is empty in updateMinRTT(): https://github.com/envoyproxy/envoy/pull/15004

Besides, i think it might cause some performance issue: every time worker thread processes the http request, and it will invoke dispatcher.post(). But there exists [a lock in the the implementation of dispatcher.post()](https://github.com/envoyproxy/envoy/blob/a96ebf4a9b4dae50c17469c64b179930e57c802e/source/common/event/dispatcher_impl.cc#L258), which would cause all worker threads pends on the dispatcher thread. 

Please let me know if I misunderstood the approach.

**Comment by tonya11en** [comment]
@freedomljc I think there's been a misunderstanding. This change is much more substantial than https://github.com/envoyproxy/envoy/pull/15060. 

A few quick notes and then I'll do a beefier writeup when I find some time tonight. I have an in-progress version of the patch I can share as well.
* Posting to the dispatcher is non-blocking. The worker threads do not wait on the dispatcher thread to complete anything, which is why this model is used.
* You cannot bump the version number in the worker threads before posting the mutation to the dispatcher. That would just result in a unique version number for each task posted to the dispatcher. It must be bumped in the posted task *after* the minRTT updates are complete. It should be that if the version number is not current, then the task was posted with stale data and should be disregarded.
* **All** of the mutations need to occur on the dispatcher. This means not just updating the minRTT, but basically anything that would need to take the mutex.

**Comment by freedomljc** [comment]
Thanks @tonya11en for clarification, look forward to seeing how it works in your patch.
I just added the unit test into https://github.com/envoyproxy/envoy/pull/15004 anyway.
