### ISSUE TITLE
Can envoy hold HTTP response headers while processing response body? in case filter needs to modify response body/header

### ISSUE THREAD

**Issue by dandlake** [envoyproxy/envoy#15015]
Can envoy hold HTTP response headers while processing response body? 

If I have a filter that needs to modify response body, content-length will change. Return code may change too. Can I make envoy hold response headers so in response body filter I can modify content-length or the whole response?

Without holding response header, I got:
[debug][http] [source/common/http/filter_manager.cc:847] [C0][S17311476643790345888] Resetting stream due to . Prior headers have already been sent

**Comment by antoniovicente** [comment]
cc @alyssawilk 

It seems to me that you need to stop iteration in decode headers and force buffering in order to be able to do header modifications based on the contents of the body.  It may be helpful to see how the compression filters handle this case, but I expect that they end up removing content-length in order to preserve the capability to stream the modified response.

**Comment by dandlake** [comment]
Thanks, @antoniovicente. I see the code in decompressor filters to remove content-length and modify content-encoding. Without changing content-encoding, not sure if I can remove content-length without causing problem in the receiving browser.

In cases where I want to change the return code(like from 200 to 4xx or 5xx to drop the body), is there a mechanism to modify/generate the entire response headers when doing body processing?

**Comment by antoniovicente** [comment]
In order to modify response headers based on the computation on the body, I think you need to force buffering and do something to prevent headers being forwarded until the computation on the buffered body is complete.  I don't know of an example of a filter that does that, I can try to dig around a bit later.

**Comment by alyssawilk** [comment]
Yeah, in general once you pass the headers on to a follow-up filter, they may be shipped upstream/downstream so modifying doesn't make sense.
The buffer filter is a useful example both of buffering, and something you may want to put in your filter chain if you want to not process headers until the entire body has been read.

**Comment by antoniovicente** [comment]
See documentation for StopAllIterationAndBuffer return value from decodeHeaders

**Comment by dandlake** [comment]
Thank you @antoniovicente @alyssawilk! I got the ideas and will look into it.
