### ISSUE TITLE
-user (User) option/config to downgrade privileges after binding to ports

### ISSUE THREAD

**Issue by ldemailly** [envoyproxy/envoy#1514]
Most daemon support starting as root and downgrading to a specific user/group after start

e.g.
https://httpd.apache.org/docs/2.4/mod/mod_unixd.html#user

Shouldn't envoy should do the same - or at least document the workarounds
(CAP_NET_BIND_SERVICE to bind to privileged ports and wrappers like setuidgid)

**Comment by dnoe** [comment]
Note that the Envoy process doesn't actually have the "daemon nature". It runs in the foreground and doesn't do the other things daemons usually do to dissociate themselves from the context they were started in. You can use a wrapper to achieve some of this behavior.

**Comment by ldemailly** [comment]
the wrapper can't do the binding of privileged ports though; it's also additional overhead to require a wrapper

**Comment by rshriram** [comment]
👎 personally. Too much code complication.

**Comment by mattklein123** [comment]
FTR I am not a fan of building this functionality into Envoy either.

**Comment by ldemailly** [comment]
it's been solved by all/most httpd servers since the first CERN one 
https://www.w3.org/Daemon/Implementation/HTDaemon.c
but it's your call obviously.

but shouldn't we have a documented workaround on how users would bind on port 80 on say trusty and xenial ?

**Comment by mattklein123** [comment]
Closing this as won't fix as I haven't seen anyone else ask for this. We can reconsider if we get more requests for this feature.

**Comment by Magnitus-** [comment]
@mattklein123 

I'm using envoy as an edge reverse proxy for its udp capabilities (something haproxy can't do).

However, I'm mapping to port 53 and am getting the same permission problem. 

I run it in docker (seems like the simplest way to run Envoy) and could do a port mapping instead of using the host network, but in our case the dns proxy is a single point of failure (dictated by our extremely limited number of available public ips... we run on a private Openstack operated by a state agency) so we want to make it as performant as possible (hence host network is preferable).

Getting the performance benefit of running directly on the host network with the reduced privilege of a non-root user would be ideal (it is after all an internet-facing proxy, I'm sure the codebase of envoy is very good given its reputation, but every extra bit of assurance helps).

Granted, this is an uncommon problem (a projet running on AWS, Google Cloud, Azure and al. with their near-infinite elasticity, plentiful public ips and managed load balancers will not experience these kinds of limitations, but some projets with strict locality requirements can't go in that direction), but it might happen more often than you think.
