### ISSUE TITLE
feature request: better build @com_googlesource_chromium_v8:build 

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#15145]
This target is internal spawn lots of tasks within. However, this target is considered as a single-core task from the view of bazel scheduler.

Generally speaking, when you run `bazel build //source/exe:envoy` with N cores, N tasks will be scheduled and at most N clang is running. However, if the running task contains @com_googlesource_chromium_v8:build, ~2N clang is running, and the peak ram usage could be huge.

A workaround: you may want to run `bazel build @com_googlesource_chromium_v8//:build` first, exhausting the cpu and ram. 
When the above task is completed, you can run `bazel build YOUR_REAL_TARGET` using the build cache of the above v8 build.

**Comment by PiotrSikora** [comment]
The official Bazel support has been requested from the V8 team (https://bugs.chromium.org/p/v8/issues/detail?id=11234), and I don't think we can do too much until that's ready, since Envoy doesn't want to maintain custom `BUILD` files.

To address the issue at hand, perhaps we could provide an upper bound to limit the number of CPUs that `ninja` can spawn when building V8? Note that this will slow-down the whole process if V8 is scheduled to be build towards the end of the build, so the workaround you suggested might actually be the best thing to do.

**Comment by lambdai** [comment]
Thank you for the confirmation and for sharing the update at chromium! I don't think Envoy should invest too much.

**Comment by PiotrSikora** [comment]
V8 team is working on this right now, and V8 v9.3 (branch cut on 7/15) should have native Bazel support.
