### ISSUE TITLE
configurate the "adaptive concurrency filter" for a specific cluster

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#15257]
I have 3 clusters and only one need to be limited. How to configurate the adaptive concurrency filter for that cluster?

**Comment by alyssawilk** [comment]
cc @tonya11en

**Comment by tonya11en** [comment]
You should be able to add it to the filter chain config parameter as part of the cluster proto like any other filter. The docs don't recommend doing this unless the cluster is representing a server local to the host. Adaptive concurrency doesn't work if you're using it on the egress in a sidecar configuration, since it needs to have full control over the number of active requests allowed through to whatever you're protecting.

**Comment by WeavingGao** [comment]
> Adaptive concurrency doesn't work if you're using it on the egress in a sidecar configuration, since it needs to have full control over the number of active requests allowed through to whatever you're protecting.

Is it possible to make a per route config/controller for adaptive concurrency filter like what local rate limit filter does?

**Comment by tonya11en** [comment]
> Is it possible to make a per route config/controller for adaptive concurrency filter like what local rate limit filter does?

It's possible to implement, but you'd need to keep the system stationary. What I mean by that is you couldn't just have a separate concurrency limit for all the different routes, because they all use the same underlying resources and the control loop wouldn't work. The local rate limit filter is using token buckets and there's no control loop per-se, so it's able to just have different token buckets for different routes.

I'm assuming you want this to address the different resource costs of various request types? If so, the way I'd go about this is assigning weights to different route prefixes and factoring that in to the admission decisions during the filter's decode step. I'm happy to help review a patch or implementation plan if you want to give it a go.

**Comment by WeavingGao** [comment]
> > Is it possible to make a per route config/controller for adaptive concurrency filter like what local rate limit filter does?
> 
> It's possible to implement, but you'd need to keep the system stationary. What I mean by that is you couldn't just have a separate concurrency limit for all the different routes, because they all use the same underlying resources and the control loop wouldn't work. The local rate limit filter is using token buckets and there's no control loop per-se, so it's able to just have different token buckets for different routes.
> 
> I'm assuming you want this to address the different resource costs of various request types? If so, the way I'd go about this is assigning weights to different route prefixes and factoring that in to the admission decisions during the filter's decode step. I'm happy to help review a patch or implementation plan if you want to give it a go.

Thank you for your reply. It really helps.
