### ISSUE TITLE
Add support for x-ratelimit-* headers in local rate limiting

### ISSUE THREAD

**Issue by hania-elayoubi** [envoyproxy/envoy#15293]
*Title*: *Add support for x-ratelimit-\* headers in local rate limiting*

*Description*:
> I see the related issue, https://github.com/envoyproxy/envoy/issues/12356, was merged on July 31 2020 so I'm assuming that change was for **global** rate limiting, and that this is not available yet in **local** rate limiting. Is that true?
>
> If so, would it be possible to add those headers' support for local rate limiting?

**Comment by mattklein123** [comment]
Yeah I think we can add this. Marking help wanted.

**Comment by zhxie** [comment]
It is easy to construct x-ratelimit-* response headers with token bucket, but there is a problem which needs to be solved. Since local rate limit allows user to apply different rate limit rules according to different [descriptors](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit), we have to add response headers corresponding to request states. Does Envoy have any easy way to track a HTTP request, store its states and pick them up when response arrives currently?
