### ISSUE TITLE
Does Envoy have basic HTTP authentication?

### ISSUE THREAD

**Issue by monelgordillo** [envoyproxy/envoy#15365]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Does Envoy have basic HTTP authentication?  Maybe similar to NGINX's authentication: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

*Description*:
>I'm looking for a credentials prompt before a user can access a webpage.  

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by derekargueta** [comment]
There's currently no built-in Basic Auth filter, but this could be accomplished either by:
1) using [this Lua snippet](https://gist.github.com/dio/7a7aa09ea5027c660e0c1c9905be7ffd) (courtesy of @dio) from https://github.com/envoyproxy/envoy/issues/8175
2) using [External Authorization](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ext_authz_filter.html) to do a look-aside request to an auth service which implements basic auth

Otherwise I think it'd be a feature request

**Comment by zhaohuabing** [comment]
We can support BasicAuth after the [credential injector http filter ](https://github.com/envoyproxy/envoy/pull/27769) is finished.
