### ISSUE TITLE
WebSocket over HTTP/2

### ISSUE THREAD

**Issue by StefanYohansson** [envoyproxy/envoy#15464]
*Title*: WebSocket over HTTP/2

*Description*:
As far I understand, Envoy doesn't support WebSocket over HTTP/2 as stated by @alyssawilk on this thread:
https://github.com/envoyproxy/envoy/issues/8547#issuecomment-540559530
I want to know if it remains true and if there's any plan to implement it or if I can help in any way to implement it (directions needed since I am new to Envoy).

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/issues/8547

**Comment by alyssawilk** [comment]
I don't think anyone has plans to address the translation errors called out in #8547, the problem was that if the client is doing HTTP/2 websocket and the upstream is doing HTTP/1, Envoy doesn't implement the differences between the specs.  I would expect HTTP/2-HTTP/2 to work though I have not used it myself.
