### ISSUE TITLE
Expose PROXY protocol headers for HTTP Connection Manager

### ISSUE THREAD

**Issue by dghermanNS1** [envoyproxy/envoy#15463]
*Title*: *Expose PROXY protocol headers for HCM too, not just tcp_proxy*

*Description*:
>Initial conversation in the envoy-users Google Group: https://groups.google.com/g/envoy-users/c/gO1XPQknxx0/m/TDCrRqg6AgAJ

We run Envoy on the edge, with the Downstream listener using HCM. The Upstream cluster nodes use PROXY protocol, however Envoy does not propagate to the upstreams the DOWNSTREAM_REMOTE_ADDRESS of the client - it sends Envoy's own IP instead.
Would like to have Envoy send the DOWNSTREAM_REMOTE_ADDRESS in the Source Address proxy headers, since we consume that down the stack.
Thank you!

**Comment by mattklein123** [comment]
Per my comment in email, PROXY proto doesn't often make sense for L7/HTTP traffic, as you will need to force each unique downstream client to have a dedicated connection pool. Is this really what you want? Generally XFF is a better solution.

**Comment by mburtless** [comment]
Just to clarify, is this comment specific to Envoy's implementation?  Can you provide more detail why each unique downstream client requires a dedicated connection pool in order to use PROXY proto?

I thought one of the values provided by PROXY proto is that it's protocol agnostic and can work natively with L7 protocols.  There are certainly a lot of solutions out there that support this use case (but maybe theres some unadvertised perform impact).

**Comment by mattklein123** [comment]
PROXY proto is per connection, not per request/stream. Thus, for it to make any sense upstream connections need to be dedicated to downstream clients. This is possible (Envoy has ways of doing this) but it's not typically what you want: you want to use XFF to learn the IP/port info on a per stream basis.

**Comment by mburtless** [comment]
Just wanted to follow up here for future readers, we ended up using http headers for our use case.  Thanks for pointing us in the right direction @mattklein123 !
