### ISSUE TITLE
Behavior for CidrRange with unspecified prefix_len

### ISSUE THREAD

**Issue by ejona86** [envoyproxy/envoy#15579]
As part of https://github.com/grpc/proposal/pull/231 I was digging through some detailed behavior of Envoy.

CidrRange has a `google.protobuf.UInt32Value prefix_len`. Since UInt32Value was used instead of `uint32` it would imply that if prefix_len is not set some reasonable default behavior should be made. There is no documentation describing what should happen in this case.

https://github.com/envoyproxy/envoy/blob/48c4fb87e9632baa6145a21771fb4d67d4aa4231/api/envoy/config/core/v3/address.proto#L158-L159

The most obvious behavior is to use a prefix_len of 32 for IPv4 and 128 for IPv6, since `0` would've just used `uint32`. However, it appears Envoy treats this case as a prefix_len of 0.

https://github.com/envoyproxy/envoy/blob/54c74450e82a3767a677ebe5406e88f0d045fb4b/source/server/filter_chain_manager_impl.cc#L181-L184
https://github.com/envoyproxy/envoy/blob/5b875969d4571fc5bda77d6340d100142ed98797/source/common/network/cidr_range.cc#L115-L117

Am I reading this right? Is that a bug or intended? Digging through history, it appears using UInt32Value instead of uint32 was likely a [simple mistake](https://github.com/envoyproxy/data-plane-api/pull/49). Although it's not clear what the previous behavior was at that point and I didn't feel like cross-referencing that change with Envoy's code.

Even if this _was_ a bug, this is looking to be pretty old behavior so it seems likely a "feature" at this point (until v4, obviously :smile:). Just add a comment describing behavior and move on?

CC @htuch

**Comment by htuch** [comment]
I don't think there is a lot of intentionality behind the default choice, and we probably have to live with what Envoy has as default here to avoid breaking people, although technically, since it's a WKT, we could change it.

Early in Envoy history, we used WKTs everywhere even when default scalar values made sense. We then changed to using scalars, which itself is being revisited in light of secure defaults, see https://github.com/envoyproxy/envoy/issues/14973, where we are thinking of switching to `optional`.

The point is moot though on what pick stylistically going forward, the existing type needs to live a long time.

I suggest adding unit tests (if not already there) and documenting.
