### ISSUE TITLE
Envoy Tools

### ISSUE THREAD

**Issue by orbatschow** [envoyproxy/envoy#1569]
Hello,

is there any convenient way of using the [tools](https://lyft.github.io/envoy/docs/install/tools/tools.html)?

At the moment it seems, that there aren't any tools packaged together with the Docker container, which is very sad. If I'm not missing something it's extremely complicated to do some route configuration checks at the moment.

Maybe delivering all binaries of the test tools together with the current image would be a solution for this?

**Comment by mattklein123** [comment]
Yes we can compile/put the tools into the docker image.

**Comment by derekargueta** [comment]
Side note, I tried doing something similar with our internal runtime container (include tools so we can do on-the-fly checking and CI-checking), but because the tools use the `envoy_cc_test` targets, which have some degree of [dynamic linking](https://github.com/envoyproxy/envoy/blob/master/bazel/envoy_test.bzl#L63)(?) I get an error like:
`libatomic.so.1: cannot open shared object file: No such file or directory`
which appears to be because the runtime container doesn't have the compiler toolchain installed in order to keep 'em light (and not have compilation tools in a prod container).

I'm wondering if we can have the tools use something more like the regular `envoy_cc_binary` targets to completely statically link. I'm pretty beginner in this area as well so my understanding might be off.
