### ISSUE TITLE
TLS: auto-complete certificate chains

### ISSUE THREAD

**Issue by danielhochman** [envoyproxy/envoy#1571]
Add AIA capabilities to Envoy so we can resolve and verify incomplete certificate chains. It looks like BoringSSL has support already.

**Comment by mattklein123** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
@danielhochman What exactly do you mean? Do you want to display this information in `/certs`? Do you want to prevent Envoy from starting with incomplete chain? Do you want Envoy to auto-complete chain?

**Comment by danielhochman** [comment]
sorry, auto-complete chain from intermediate

**Comment by PiotrSikora** [comment]
I don't like this feature:
1) Envoy doesn't know which CAs are trusted by the peer, so it has to auto-complete as much as it can, i.e. it cannot stop building the chain at the intermediate CA, it needs to include everything all the way to the root CAs, which means at least extra 1-2KB of certificate data in each full TLS handshake.
2) It would require configuration of "CAs to be used for auto-complete", presumably for each TLS context block.
3) Auto-completing certificate chains is actually deprecated in BoringSSL, see: https://bugs.chromium.org/p/boringssl/issues/detail?id=42.

If you really want to auto-complete certificate chains, then it should be done at the LDS/CDS level and complete chains should be pushed to Envoys from there, otherwise it won't scale.

Also, could you rename this issue to "TLS: auto-complete certificate chains", so that it can be found later? Thanks.

cc @davidben for sanity check.

**Comment by mattklein123** [comment]
@PiotrSikora I already renamed it. :) (Also, I added a new "TLS" label for your implementation pleasure).

**Comment by PiotrSikora** [comment]
@mattklein123 it stills shows "TLS: add authority information access capability".

**Comment by mattklein123** [comment]
Oh sorry. Fixed.

**Comment by PiotrSikora** [comment]
@danielhochman Can this be closed as answered / won't fix?

**Comment by mattklein123** [comment]
Yeah I think we don't need this. I will close.

**Comment by davidben** [comment]
Just noticed I was CC'd on this a year ago, sorry! Yeah, we are no fans of that feature. I doubt we'll end up removing it at this point due to compatibility, but we don't think it makes sense for the reason Piotr mentioned.
