### ISSUE TITLE
wasm filters: Add entropy source

### ISSUE THREAD

**Issue by DerekStrickland** [envoyproxy/envoy#15769]
*Title*: *Add an entropy source for wasm filters*

*Description*:
>It would be great to have a source of entropy for Rust-based wasm filters.

**Comment by picatz** [comment]
I would also be interested in this feature. There doesn't seem to be an ABI function that would allow access to a "secure" source of entropy from the Envoy host. Having access to one would allow things like generating UUIDs from a WASM filter. My understanding is that in order to do this safely at the moment, I need to call an external service that has an entropy source.

**Comment by DerekStrickland** [comment]
Sweet. Thanks!  I'll take a look!

**Comment by PiotrSikora** [comment]
@DerekStrickland does that work for you? If so, could you close this issue? Thanks!

**Comment by DerekStrickland** [comment]
@PiotrSikora  Looks promising. Thanks!
