### ISSUE TITLE
Flaky test is flaky 

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#15800]
### description

there is a test to report on apparent test flakes - but that itself is throwing an error:

https://dev.azure.com/cncf/envoy/_build/results?buildId=70906&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=23349

**Comment by phlax** [comment]
the code that triggers the error is here:

https://github.com/envoyproxy/envoy/blob/1134a1602c37d6fec8d5dd9bccd2855f32b2a34a/ci/flaky_test/process_xml.py#L100-L108

im unsure as to why its  failing whether the name of the test is incorrect - or whether this script is incorrect

the test that is marked as flaky is the `access_log_manager_impl_test` here https://dev.azure.com/cncf/envoy/_build/results?buildId=70906&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=23285

@davinci26 any idea why this might be failing ?

**Comment by davinci26** [comment]
I saw that failure as well

re the test failure in `access_log_manager_impl_test`, I am not sure what is happening but I could not get a repro at 100k runs so it might be some rare flake that caused this.

 re the python script: @rmiller14 do you know on top of your head how to fix the python script otherwise I can look at it.

**Comment by phlax** [comment]
this is still flakey afaict

**Comment by davinci26** [comment]
Assigning to myself to fix
