### ISSUE TITLE
Support using each individual upstream's endpoint hostname as SNI parameter

### ISSUE THREAD

**Issue by spockz** [envoyproxy/envoy#15839]
*Title*: *Support using each individual upstream's endpoint hostname as SNI parameter*

*Description*:
In our situation we have mainly a flat network except for some K8s clusters which have independent address spaces for their workloads. We currently have a, finagle-based, mesh in which we have E2E TLS & and client-side load balancing over instances, also over instances in the K8s clusters. This is how it works: 

* Each instance in the cluster registers with an externally resolvable hostname of the form $pod-ip-with-dashes.$namespace.pod.$clustername. Inside the cluster it resolves directly to $pod-ip. Outside of the cluster this hostname resolves to the IPs (plural) of the ingress nodes.
* On these ingress nodes we run an "SNI Router", the only thing it does is accepting the socket, looking at the SNI parameter and on the inside forward the TCP connection to the pod indicated in the SNI parameter.

This allows us to achieve both E2E TLS and client side load balancing over individual pods which allows us to eliminate the hot-spotting traditionally seen when employing L3 load-balancing.

We would love to be able to use envoy proxy as our sidecar but currently we cannot find a way to set the SNI parameter to be the hostname of an endpoint. We see some options to set it to a cluster wide constant value, which Istio appears to use as well.

How can we set the SNI parameter to the individual hostname endpoint? (We are fine using a WASM filter or something, but we would rather not run our distribution as we would like to be able to stick with Istio's distribution of envoy.)

**Comment by mattklein123** [comment]
I don't think this is possible today though it's something that could be added. cc @ggreenway @lambdai

**Comment by spockz** [comment]
@mattklein123 I would be happy to contribute something. Although my c knowledge is seriously limited I would appreciate some guidance on where to fix this. E.g. I'm not sure whether setting the sni parameter by default would break existing setups so it probably needs to be toggled.

**Comment by mattklein123** [comment]
So, I think this may actually be possible today via `transport_socket_matches`, but it would be extremely verbose and wouldn't be dynamic (since the config is on the cluster vs. the endpoint), but it might theoretically work for you if you can use a static cluster and inline a match for each endpoint.

Assuming that doesn't work (likely), I would have a look at how transport socket is configured today and how the transport socket match functionality works, and we can first come up with an API proposal. At a high level I think we would have an option that would allow mapping endpoint host to SNI, and create a different transport socket config for each endpoint. I would definitely like to hear from @lambdai though who might have better ideas.

**Comment by lambdai** [comment]
@mattklein123 When you mention `transport_socket_matches` I realize cluster upstream filter doesn't work. 

The existing transport socket match is something like we prepare N transport socket candidates, and when an upstream host is selected, choose the best fit for "endpoint metadata". It might be easier to extend TransportSocketMatch by
1. extend the match critieria, add another host info beside "endpoint metadata". Of course the host info we need in this use case is "host name". It avoid us encode the host name into "endpoint metadata"
2.  Create new TransportSocketMatcher field, either as straight as "bool use_host_name_as_SNI", or/and a SubTransportSocketMatcher.
The sub_matcher is much extensible, since you can decide which  occurs last, `use_host_name_as_SNI` or the existing metadata matcher.

```
  message TransportSocketMatch {
    google.protobuf.Struct match = 2;
    core.v3.TransportSocket transport_socket = 3;
  }
```
to
```
  message TransportSocketMatch {
     one_of {
       // Terminated matcher
       {
         google.protobuf.Struct match = 2;           // This field should always work with field 3.
         core.v3.TransportSocket transport_socket = 3;   // terminate the transport 
       }
      // Nonterminated matcher
       {
          bool use_host_name_as_SNI = 4;          // Always match, plus adding SNI into existing transport socket options. 
          repeatedTransportSocketMatch sub_matcher = 5;  // or use sub matcher to create transport socket
       }
     }
    one_of {
    }
 }
```
The above is likely the matcher chain in the recursive structure...

**Comment by spockz** [comment]
@mattklein123 , regarding the matchers, I think we would be okay for a PoC if we can insert the matches based on hostname/endpoint. Potentially we can add them to a an Envoy cluster using Istio's `EnvoyFIlter`. However, I'm not sure what the match configuration would look like, particularly how to set the SNI value in the configuration.

As we are generating all the entries for the pods in the remote clusters already, it would be rather trivial to generate an appropriate accompanying EnvoyFilter to override the SNI value.

**Comment by howardjohn** [comment]
Leaking Istio discussion here a bit, but FWIW Istio doesn't allow patching Endpoints with EnvoyFilter

**Comment by mattklein123** [comment]
I'm going to need to think about this a bit so let me get back to you. cc @alyssawilk also who just pinged me about a somewhat similar issue as it relates to H2 vs. H3 transport socket configuration.

**Comment by ggreenway** [comment]
I don't think we want a different transport socket config for each host. The sent SNI value is a per-connection (not context) setting in BoringSSL. I think we should add an option "set SNI to hostname" to the TLS upstream transport socket config somewhere, and set that on the `SSL*` when it is created [here](https://github.com/envoyproxy/envoy/blob/7d426641e044491ed13b0b45afb25604c323fbc9/source/extensions/transport_sockets/tls/context_impl.cc#L611).

**Comment by mattklein123** [comment]
Thanks @ggreenway for the link. I had forgotten that we basically already support this.

@spockz see: https://github.com/envoyproxy/envoy/blob/a67d8e588532fc2e3a7d89ee6aa469931c6419be/api/envoy/config/core/v3/protocol.proto#L40-L43

And how that ultimately works here: 

https://github.com/envoyproxy/envoy/blob/7d426641e044491ed13b0b45afb25604c323fbc9/source/extensions/transport_sockets/tls/context_impl.cc#L611-L613

and here:

https://github.com/envoyproxy/envoy/blob/a67d8e588532fc2e3a7d89ee6aa469931c6419be/source/common/router/router.cc#L496-L501

This issue is not HTTP specific, however the current transport socket API just takes a transport socket options to create the transport socket, so it would probably be easiest to just make use of the existing serverNameOverride() field. (The transport socket is at a layer where it doesn't know anything about hosts, endpoints, etc.)

So per @ggreenway I would suggest we add a new config option that will trigger the behavior you are after. The trouble is I'm not sure if we can avoid implementing this functionality in each extension that makes connections given the decoupling between network connections and endpoints. I'm also not sure yet where the best location for such a configuration should be. I can poke more at this tomorrow but I wanted to write down what I thought so far before I leave for the day.

(@alyssawilk for your issue, I do think that we do ultimately want to tie into the transport socket matching functionality at the code level, so perhaps the way to do that will be to auto-populate match structures on behalf of the user? We can discuss this more offline.)

**Comment by ggreenway** [comment]
One important difference with the existing `auto_sni` (I'd forgotten about that): I believe that `auto_sni` sets something on the upstream connection so that there is a separate connection pool per SNI value. For this new use-case, we want to make sure we don't do that. This new use case does not want requests to be routed to a connection based on the SNI; the SNI is just needed to setup the connection, but once setup, it is the same as the others in the same cluster.

**Comment by mattklein123** [comment]
> For this new use-case, we want to make sure we don't do that. This new use case does not want requests to be routed to a connection based on the SNI; the SNI is just needed to setup the connection, but once setup, it is the same as the others in the same cluster.

@ggreenway I'm pretty sure we can reuse the same hashing logic and it would effectively be a no op because there would be one value per host? My initial thinking was an option that is shared across all conn pools including TCP. I can look more tomorrow.

**Comment by ggreenway** [comment]
> @ggreenway I'm pretty sure we can reuse the same hashing logic and it would effectively be a no op because there would be one value per host? My initial thinking was an option that is shared across all conn pools including TCP. I can look more tomorrow.

Oh right, that makes sense. 👍

**Comment by lambdai** [comment]
Is the feature request here to set SNI by downstream request or upstream endpoint? IMO `auto_sni` does the former which is from downstream.

**Comment by mattklein123** [comment]
I took another look at this and my concrete suggestion is:
1) Add a common field on the `Cluster` proto to account for the new functionality. I think its debatable where this is put but potentially on `UpstreamConnectionOptions`. Whoever actually works on the change can suggest the best place after looking through.
2) Ultimately hang this option off of `ClusterInfo`
3) Do something like `wrapTransportSocketOptions` (in the HTTP conn pool base) but in the shared conn pool base across all conn pools including TCP. This code can look at the cluster info hanging off of the host and decide if the transport socket options need to be wrapped to provide an override SNI, and then use this override transport socket options when creating connections.

I think if we do ^ it won't even engage the hashing code that @ggreenway was talking about which is fine IMO.

I think this should be pretty straightforward and clean.

**Comment by spockz** [comment]
I think I have managed most of this locally. However, @mattklein123, could you please elaborate on the 3rd bullet? It doesn't make much sense to many.

Also, I'm wondering what the best way would be to add an integration test for this. Spin up an http server that returns the SNI value from the handshake and check in the test whether the value is what was expected?

**Comment by mattklein123** [comment]
> However, @mattklein123, could you please elaborate on the 3rd bullet? It doesn't make much sense to many.

You need to provide an override transport socket options to change the SNI. This is how you would do it I think.

**Comment by quantumsheep** [comment]
Has a solution been found using current's Envoy configuration?
