### ISSUE TITLE
Inconsistent Search Results Behaviour

### ISSUE THREAD

**Issue by zachmandeville** [envoyproxy/envoy#15934]
*Title*: 
*On the envoy docs, search results are inconsistent across similar search terms.*

*Description*:
I noticed when searching for [ip tagging](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/http/ip_tagging/v3/ip_tagging.proto.html), that I could only find the page when i matched text in the qualified names referenced on the page.   Other pages I could find by matching any text on the page.

*Repro steps*:
.
_I reproduced the below behaviour on firefox, chrome, and safari. I did not test on all versions, but reproduced using latest, 1.17.1, 1.16.1, and 1.13.1_
- in the search field of [the docs](https://www.envoyproxy.io/docs/envoy/latest/) enter any of these terms: "ip tagging", "ip tag", "ip" and note the results.
- enter "iptag" and note the results.
- enter "kafka broker", "kafka", "kafka b", "emitting results", then note results.

The first set of terms will not bring up the ip tagging page.  "iptag" will return the page by matching on the qualified names in the page.  Any of the last terms will bring up the correct [kafka broker page](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/kafka_broker/v3/kafka_broker.proto.html) among its results.

*Admin and Stats Output*:
n/a

*Config*:
n/a

*Logs*:
n/a

*Call Stack*:
n/a

**Comment by zachmandeville** [comment]
cc: @phlax

**Comment by phlax** [comment]
@zachmandeville thanks for reporting

ive noticed that the search is not very good on a number of occasions - tbh ive never been that impressed with sphinx's search

there are a few search settings set in the `conf.py` i guess its worth playing around with these to see if any help to improve results

i think there is also a search adapter that you can add to further customize, which may be useful in resolving specific issues - https://www.sphinx-doc.org/en/master/usage/advanced/websupport/searchadapters.html

if you were to experiment with these and PR any improvements i would be very up for reviewing - otherwise i will take a look at this as i have time

**Comment by zachmandeville** [comment]
Thank you for these resources!  I'll do some experimenting as time permits.

**Comment by daixiang0** [comment]
Upstream fix as sphinx-doc/sphinx#8070 
PR as #16186

**Comment by phlax** [comment]
@daixiang0 it would be good to know whether this bug is now fixed by upgrade to sphinx 4

**Comment by daixiang0** [comment]
I update the pr and I test in latest doc website with "ip tag", it works.

**Comment by phlax** [comment]
great, thanks @daixiang0
