### ISSUE TITLE
Happy eyeballs support for Dynamic Forward Proxy (and possibly others)

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#16309]
For this, we need to have
- multiple IP addresses per host (right now we roll down to 1 DNS result)
- "async" DNS resolution (be able to return v4 and v6 results independantly)
- grid style failover logic (possibly pluggable, if we want more than "try first v6, fail over over to v6)

**Comment by DavidSchinazi** [comment]
(Notifying @RyanTheOptimist since we'll be collaborating on parts of this.)

**Comment by RyanTheOptimist** [comment]
After digging into this with @alyssawilk I think we have a plan for how to do this. PR #16913 added an `addressList()` method to `Upstream::HostDescription`. This list will be populated by the DNS resolution code and will allow connection logic to potentially use any of the IP addresses to connect. 

Figuring where to do the failover logic has been a bit tricky. Simplest would be to do the failover/racing in the Grid but that would prevent the basic connection pools from being able to use this feature. Another thought was to do this racing in the `ActiveClient` but that seems tricky given the various different `ActiveClient` implementations. Instead, what we think is the most reasonable path forward is to change `DispatcherImpl::createClientConnection()`. Instead of returning a `Network::ClientConnectionImpl` it will instead return something like `Network::HappyEyebalssClientConnectionImpl`. This will implement the Happy Eyeballs logic and will internally create a `Network::ClientConnectionImpl` on-demands for each of the addresses in the list that it tries to connect to. Hopefully this proves reasonable!

**Comment by mattklein123** [comment]
> Instead of returning a Network::ClientConnectionImpl it will instead return something like Network::HappyEyebalssClientConnectionImpl. This will implement the Happy Eyeballs logic and will internally create a Network::ClientConnectionImpl on-demands for each of the addresses in the list that it tries to connect to. Hopefully this proves reasonable!

Do we think we will want this behavior to be configurable? Do we want all callers of this low level API to get this functionality? That would be my main concern.

**Comment by alyssawilk** [comment]
I think we'll want it on by default, and we can add a knob to configure it off if they want to. If we want to flag it off, I think we'd do so in the dns resolver, since that's where we currently scope down from N hosts to 1 host.

**Comment by alyssawilk** [comment]
Ah we forgot to tag https://github.com/envoyproxy/envoy/pull/17371 there

**Comment by mattklein123** [comment]
Per offline discussion I think we are going to try to get this wired up and some testable form:
1) @junr03 will add a resolver mode that will return both v4 and v6.
2) @alyssawilk will do the wiring on the host/connection itself. @alyssawilk on this topic, wdyt in terms of runtime or config? I'm mostly concerned that there may be cases in which people don't want this and they want the old behavior and thus we need config? I could go either way. I guess we could start with runtime (maybe default off at first) and see if anyone complains?

**Comment by alyssawilk** [comment]
Hm, it's a good question.  I'm inclined to do it as reloadable (default off, as discused) and see if anyone doesn't want it.  I think it makes sense as the default behavior and we can always add a config knob after the fact and use the runtime guard to allow prior behavior while we add the option.
