### ISSUE TITLE
Pass empty message as query parameter

### ISSUE THREAD

**Issue by PranayVJain** [envoyproxy/envoy#16332]
I have a request message in our proto file with definition similar to below
```
rpc GetBookUploadUrl (GetBookUploadUrlRequest) returns (GetBookUploadUrlResponse) {
    option (google.api.http) = {
      get: "/bookstore/v1/books/upload-url"
    };
}
```
The request message looks like this:
```
message GetBookUploadUrlRequest{
...
    BookFormat format = 2;
... 
}

message BookFormat{
    oneof book_format {
        PDF pdf = 1;
        Image image = 2;
        Text text = 3;
        ...
    }   
}

message PDF{
    // empty message
}

message Text{
    int lines = 1;
} 
```
Now, while calling the http endpoint using format as text works perfectly well
```
GET /bookstore/v1/books/upload-url?format.text.lines=100
```
But this doesn't work
```
GET /bookstore/v1/books/upload-url?format.pdf=
```
I suspect it is because the PDF message is empty.
Do we need to pass the empty message in some other way?

**Comment by antoniovicente** [comment]
cc @snowp @zuercher who may know more about gRPC uses of the HTTP GET method and HTTP->gRPC transcoding.

After a quick search I'm not used to finding documentation on how to encode gRPC arguments in URL query parameters.  I'm used to gRPC using the POST method and encoding the request proto in the HTTP message body.

**Comment by zuercher** [comment]
If I understand this correctly, you've configured your gRPC server to respond to HTTP requests a la https://cloud.google.com/endpoints/docs/grpc/transcoding.

This is a plain http request and I can't think of any special gRPC processing in Envoy that this would trigger. I expect if you send your `GET /bookstore/v1/books/upload-url?format.pdf=` request directly to the upstream host (bypassing Envoy) you'll get the same error.

Assuming that's all correct, this is a question of how to form the request so that the upstream handles it. I don't know the correct encoding either, but I would try passing `GET /bookstore/v1/books/upload-url?format.pdf={}`. Failing that, I'd start looking at the code in the underlying libraries.
