### ISSUE TITLE
Admission Control: QPS threshold

### ISSUE THREAD

**Issue by WeavingGao** [envoyproxy/envoy#16392]
*Title*: *A threshold of queries per second that triggers throttling strategy*

*Description*:
>The admission control filter  rejects requests based on the success rate of previous requests. However, in a low QPS scenario, a small number of request failures will make the request success rate very low, which will trigger the rejection behavior, thereby further reducing the failure rate of subsequent requests. To make matters worse, the filter has a per-worker time window, which means that the QPS carried by each worker is lower.
In fact, in a low QPS scenario, admission control is unnecessary. We can add a QPS threshold configuration and only when the QPS exceeds this threshold, the filter will calculate the failure rate and perform subsequent actions.

cc @tonya11en @mattklein123

**Comment by tonya11en** [comment]
This makes perfect sense and is totally necessary. Other implementations of this mechanism I've seen in the wild at scale have this minimum RPS threshold.

This would be super easy to implement. We already track the number of request at 1 second granularity, so we can just have a simple conditional that checks the most recent second for some minimum number of requests before rejecting. It should be one of the values at the back of the deque. 

I'd be happy to review a PR if you (or any other reader) feel comfortable submitting one or point folks to the exact line this would be if needed. Otherwise, I can get to this when I have the cycles. There are some other items I'd want to get to beforehand.

**Comment by tonya11en** [comment]
While we're at it, some other low-hanging-fruit here would be to also add a maximum throttling percentage and default to some sane value like 80%.

**Comment by WeavingGao** [comment]
I'll submit a PR.

**Comment by tonya11en** [comment]
This is still in review.

**Comment by WeavingGao** [comment]
Merged in #16742.
