### ISSUE TITLE
Instrument host selection

### ISSUE THREAD

**Issue by hamdiallam** [envoyproxy/envoy#16435]
Host Selection Metric: It would be nice to have a metric to understand when the load balancer is picking failed hosts

This is when configuring `host_selection_max_attempt`. Reference https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/transient_failures

**Comment by snowp** [comment]
Upon the first attempt, if a connect failure is hit a retry would be attempted. This retry would make use of the previous_hosts predicate to try to exclude the attempted host: host selection is attempted up to 5 times to find a different host. Whenever it finds a different host or the attempts are exhausted, it has now selected the host to retry against. In this case if you exhaust the host selection, its likely because you only have one candidate host and the LB keeps selecting the same one. 

The selection attempts don't do anything with each attempted host, but the predicate is able to use information from previous host attempts to influence its logic.

So yeah I would think in your case you should be setting num_retries higher rather than increasing max_attempts.

**Comment by hamdiallam** [comment]
Ahh gotcha, this makes sense. Thanks for the explanation. I was able to verify this with a simple unit test checking `upstream_cx_connect_failure` equaling 2 (1 retry).

Your help was much appreciated!
