### ISSUE TITLE
Composite filter header matching issue in envoy-v1.18.2

### ISSUE THREAD

**Issue by nandu-vinodan** [envoyproxy/envoy#16431]
*Title*: *Composite filter header matching issue in envoy-v1.18.2*

*Description*:
The sample envoy [configuration](https://www.envoyproxy.io/docs/envoy/v1.18.2/configuration/http/http_filters/composite_filter#config-http-filters-composite) provided in the `compose filter`  docs does not work as expected.

__Expected behavior:__
If the header `x-fault-category` is equal to the string huge fault, a 10s latency is injected while if the header contains tiny string a 1s latency is injected. If the header is absent or contains a different value, no filter is instantiated.

__Actual behavior:__
Only first request works as expected, all consequent requests with the same header (but different values) are matched against the header value of the first request.

*Repro steps*:

* Using envoy 1.18.2 docker image in macOS 10.15.

* Running envoy with trace logs enabled:
`docker run -it -p 80:51051 -p 9901:9901 -v $(pwd)/static.yaml:/etc/static.yaml envoyproxy/envoy:v1.18.2 -c /etc/static.yaml --log-level trace`

* Request 1:
`curl -v 'localhost:80' --header 'x-fault-category: tiny fault'`

This works as expected, a response is returned after a delay of 1s.
Also, I can also see the following in trace logs: `Attempting to match data input: tiny fault`

* Next set of requests:
`curl -v 'localhost:80' --header 'x-fault-category: huge fault'`

This also returns the same response as the previous one, after a delay of 1s, while expectation is to have a delay of 10s.
Corresponding log: `Attempting to match data input: tiny fault`

* Same header with dummy value
`curl -v 'localhost:80' --header 'x-fault-category: ignorethis'`
Same behavior as the previous one with log:`Attempting to match data input: tiny fault`

* Remove the header
`curl -v 'localhost:80' --header 'new-header: new-value'`
Works correctly.
Log:`Attempting to match data input: n/a`

* Again inject same header
`curl -v 'localhost:80' --header 'x-fault-category: ignorethis'`
Issue occure again: Shows response after 1s.
Log: `Attempting to match data input: tiny fault`

If the experimented is started with `x-fault-category: huge fault`, all requests with the header gets a delay of 10s.
Am not sure if there is an issue with the sample config.

*Config*:

Taken from: https://www.envoyproxy.io/docs/envoy/v1.18.2/configuration/http/http_filters/composite_filter#config-http-filters-composite
https://gist.github.com/nandu-vinodan/1d4e3fea187dba47d0bfa900e0351410#file-static-yaml

*Logs*:
https://gist.github.com/nandu-vinodan/1d4e3fea187dba47d0bfa900e0351410#file-envoy-trace-log

**Comment by balbifm** [comment]
Hi, I am also able to reproduce this behavior by just using _type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher_ without the composite filter, just to inform.

**Comment by snowp** [comment]
Thanks for the report! This issue should be resolved whenever #16721 lands

**Comment by jijiechen** [comment]
Hi @snowp Thanks for this fix.
Will you merge this fix into v1.18 releases? I can confirm the issue exists in version v1.18.3 as well.

**Comment by snowp** [comment]
We're not planning on backporting any fixes to the composite filter, I'd suggest updating to the latest version

**Comment by jijiechen** [comment]
Thanks for the quick reply.
If I understood the issue correctly, this issue is related to the matcher instead of composite filter. I don't meant to be harsh, but this makes the unified matching api totally not usable for older versions. 
The latest version of Istio v1.10 is still using Envoy v1.18, so it'll be a long time for end users to get this fix.

That said, if you can merge this one as well as https://github.com/envoyproxy/envoy/pull/16847 into v1.18, that'll make a big difference for people who want to use the unified matcher API.

**Comment by snowp** [comment]
Unfortunately we reserve backporting to security and stability fixes, so since the matching API never worked it doesn't qualify. This policy is in place to avoid maintainers getting bogged down with work around reviewing backports: if we had more people stepping up to the backport rotation this policy might change.

As for end user usage there are already plenty of users making use of this API already (I think some even through Istio, but I know nothing about how that works), so I'm not concerned about that at this point

**Comment by jijiechen** [comment]
It's sad to know this policy. Istio distribute envoy by wrapping with extra filters and components, so Envoy is upstream of Istio. Under your policy, people have to wait for new releases of Istio to get feature fixes of Envoy. Despite that Istio tries to rollout new versions every 3 months, people tend not to upgrade Istio constantly following Istio's release cadence since it's an infrastructure software. This makes the feature fixes even longer.
