### ISSUE TITLE
Use typed protobuf messages for configs of builtin filters.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#1680]
As discussed in https://github.com/envoyproxy/envoy/pull/1495 & https://github.com/envoyproxy/envoy/pull/1657, there should be a proper support for builtin filters, and  `google.protobuf.Struct` should be used only as a necessary evil for 3rd-party filters.

**Comment by PiotrSikora** [comment]
@htuch @jrajahalme @jmillikin-stripe

**Comment by htuch** [comment]
In terms of the design space here, at a high-level we have a choice between treating the builtin filters as opaque, as we do with 3rd party, and as a `oneof` in an extensible proto. The thinking to date has been to do the former, since this simplifies implementation and extension (even with the builtins, which will grow).

There are two concerns that have come up regarding the opaque filter config based on `Struct` (which is basically just a JSON object). The first is how pretty the proto text representation is for humans to read/write, the second is how efficient it is (somewhat related). Neither of these were considered design objectives originally, since Google prefers to use YAML as the human readable representation for proto going forward (proto text is not standardized) and efficiency is not generally an issue on the Envoy control plane (unless scaling well beyond current known deployments of Envoy).

I think the efficiency argument needs to be made stronger before motivating any changes, I'd like to see some evidence that there is really a real world problem (i.e. not hypothetical performance improvements or microbenchmarks) that we're solving by making an API change. OTOH, for proto text, if folks really want this as a matter of config representation preference, we can consider how to accommodate if it can be done cheaply.

@jmillikin-stripe suggested providing the option to do either `Any` or `Struct` in the filter config protos. This could be easily accommodated in a backward compatible way via proto extension. The advantage of `Any` is that there is a proto text literal representation that is much more human friendly. The disadvantage (and why we didn't opt for this originally) is that the proto is just a binary string that doesn't have an interpretation without the proto descriptor. This does not make it well suited to JSON representation and non-gRPC use. However, allowing folks the ability to chose between the two based on their use case and deployment makes sense to me.

In terms of implementation, this will be straightforward, a small change to https://github.com/envoyproxy/data-plane-api/blob/master/api/lds.proto#L36 and https://github.com/envoyproxy/data-plane-api/blob/master/api/filter/http_connection_manager.proto#L127, followed by an unpacking step in places like https://github.com/envoyproxy/envoy/blob/master/source/server/config/network/http_connection_manager.cc#L230.

There are two practical issues I see here:
1. We need to make the call on whether it is worth maintaining both code paths for `Any` and `Struct`. I think it's reasonable but would like to hear from others.
2. This is not an implementation priority for Google, so we would need folks in the Envoy community to step up and implement this if they want it.

@louiscryan @mattklein123

**Comment by mattklein123** [comment]
I don't have a strong preference. If people are willing to do the work maintaining Any/Struct seems reasonable to me.

**Comment by lizan** [comment]
> This does not make it well suited to JSON representation and non-gRPC use.

@htuch Can you elaborate this? `Any` has JSON representation without binary, (it is just an JSON object with `@type`). A non-gRPC xDS can issue a JSON like that and Envoy can parse it.

**Comment by htuch** [comment]
Well, let's say you want to convert from a binary proto containing `Any` to the JSON representation. You can only do this with the proto descriptor for the embedded message. Same vice-versa. With `Struct`, there is no such concern. This means you can write tools that can (de)serialize Envoy configs without having to know every single opaque filter config that might ever exist, only the well-known `data-plane-api` proto descriptors. That's one example.

Here's another: let's say someone wants to write a web app to inspect Envoy configs given the serialized proto. They can't do this without having to also know the proto descriptors for every opaque filter config they might encounter.

**Comment by lizan** [comment]
Theoretically I understand the examples. But I doubt it in real use cases. Since Envoy and xDS have to understand every proto messages it might encounter, so having conversions between JSON and binary there is enough. Envoy can consume both JSON configs or binaries, . 

If a tool or web app want to inspect an envoy config (not simply converting binary to JSON, or vice-versa) then it would need to understand the underlying schemas anyway, or just skip that opaque part that it doesn't understand, no?

Do we have a real use case that requires Struct?

**Comment by htuch** [comment]
I think I just provided one? Let's say I'm building a tool to generate Envoy configs, and I want to let users view or modify a `Listener` config. It's totally feasible to let you go in and flip a boolean or a string in an auth filter without needing to have the filter's schema available. This is just dynamic vs. static typing manifesting itself in another venue; what we're saying with `Struct` is we are willing to take the advantages of dynamic typing, e.g. not requiring strict upfront typing, in exchange for being able to work schemaless (or proto descriptorless). 

I don't think it's "theoretical" that folks are going to build tools to manipulate the protos and make Envoy configuration easier.

**Comment by lizan** [comment]
The "theoretical" part is not folks are going to build tools to manipulate the protos and make Envoy configuration easier. It is theoretical that you need dynamic typing while dealing with a static typed binary serialized photos. If they don't always have proto descriptors they can always use JSON which allows dynamic typing, and Envoy has first class support of it. Having a dynamic typed `Struct` inside static typed, (even worse, without providing options to do static typing) still doesn't make sense.

I don't have strong opinion about (2). The gain is basically allowing static typing in filter configs, same gain as JSON vs protobuf, (e.g. safe renaming fields etc...). Since with `Struct` we don't have the full advantage that has. The conversion could be done without converting `Struct` to JSON string once. A large filter such as http connection manager would benefit from this but we don't have evidence until istio migrates to v2.

So given the API is frozen, I would strongly propose that we have at least `oneof` between `Struct` and `Any`, to keep it backward compatible. For new opaque config in https://github.com/envoyproxy/data-plane-api/pull/189, I would prefer `Any` only but can live with `oneof`, `Struct` only is the last option to take.

**Comment by mattklein123** [comment]
Dup of https://github.com/envoyproxy/envoy/issues/1619. @rshriram is working on this.
