### ISSUE TITLE
Ext_proc filter performance question

### ISSUE THREAD

**Issue by dragonbone81** [envoyproxy/envoy#16905]
Hi, I'm trying to understand the performance expectations of the ext_proc filter.
From our testing we have measured that adding the filter on, and sending all request parts (headers/body for req/res) and just returning the exact same content from our grpc server leads to an average overhead 3ms per request.

Is this the expected overhead, or are there things we can do to optimize our configuration?

Thanks!

**Comment by snowp** [comment]
@gbrail

**Comment by gbrail** [comment]
Thanks and I'm glad that you're testing. We don't have a lot of test results yet and I'm glad to hear that you're trying it out with a real use case. I take it from your response that you're not happy with 3ms. Do you have a target?

The main thing that you can do now to reduce latency is to reduce the number of hops between the Envoy proxy and your processor. If you are sending request and response headers and request and response body, then that's four round trips. If you don't need all of those, then you can use the "ProcessingMode" to eliminate calls that you don't have.

The filter and protocol are also designed so that your processor can decide at runtime what calls it needs. For instance, if after using the headers, your processor can conclude that it doesn't need all four of those things, it can either change the processing mode, or it can simply close the gRPC stream.

@ikepolinsky is also interested in this.

**Comment by gbrail** [comment]
Thinking about future optimizations...

in your use case, do you always want the headers and the full buffered body for every request and response? And do you always wait for both before deciding how to handle the request and response? Because if so, perhaps more aggressive pipelining (send the body before getting back the headers response) would be appropriate as an option.

**Comment by gbrail** [comment]
Also, when you said: "returning the exact same content from our grpc server" did you mean that you're just returning the same request and response body that you just got? Because if you don't want to change the body (or the headers) you can just return an empty message and that will reduce the number of bytes on the wire.

**Comment by gbrail** [comment]
Good feedback -- thanks. Since you see the biggest delay on the establishment of the stream, I wonder if there are some gRPC optimizations we can do, either in your configuration or in the code. I'm not deeply involved in that part of Envoy. Perhaps some others have an idea there.

**Comment by gbrail** [comment]
I think that there's also a gRPC stream optimization that's implemented in the ext_authz filter that's not implemented in ext_proc yet. That might be worth exploring.

**Comment by dragonbone81** [comment]
@moderation we will explore this, thanks for the suggestion.

@gbrail Do you have a link to this optimization (code or docs), just so we can take a look to see if we can get any ideas from this?
