### ISSUE TITLE
Make QUIC, H/3 support non optional

### ISSUE THREAD

**Issue by yanavlasov** [envoyproxy/envoy#16974]
Presently QUIC, H/3 support in Envoy is optional and can be excluded from the build by setting the [disable_http3_setting](https://github.com/envoyproxy/envoy/blob/398794730b8a2651e004cfe2ca82de0eaa02ba4b/bazel/BUILD#L297) bazel option. In source code the inclusion is controlled by the `ENVOY_ENABLE_QUIC` macro.

Given the tight integration of QUIC with the Envoy core components the `ENVOY_ENABLE_QUIC` appears now in significant number of source files. This approach is [error prone](https://github.com/envoyproxy/envoy/pull/16927/files) and is considered an antipattern in modern C++.

This issue proposes making QUIC, H/3 a non optional component in Envoy to avoid heavy ifdef-ing of the Envoy core components and tests.

The only known issue is supporting QUIC in FIPS builds of Envoy, which can be resolved without heavy use of preprocessor macros.

**Comment by ggreenway** [comment]
I think this change would also break https://github.com/envoyproxy/envoy-openssl

**Comment by alyssawilk** [comment]
good point - ideally could be fixed with the same shims we need for the FIPs build but it'd take some digging - I don't recall where else the APIs differ

cc @danzh2010 @RyanTheOptimist @RenjieTang @DavidSchinazi

**Comment by wrowe** [comment]
I'm strongly against this suggestion for the time being. Perhaps in a few years, but HTTP/1.1 is adequate for many applications and very few scenarios can take advantage of the parallel streaming features of H2/H3.

**Comment by RyanTheOptimist** [comment]
Summarizing an offline discussion. QUICHE is the library which Envoy uses for QUIC and HTTP/3 support. QUICHE is inherently tied to BoringSSL and does not work with OpenSSL. So without some significant support being added to OpenSSL, it will not be possible to QUIC/HTTP/3 with Envoy + OpenSSL. So this means we're likely stuck with some sort of compile-time conditional in some parts of the codebase.

 At the moment, this is done via the `ENVOY_ENABLE_QUIC` marco to conditionally disable building QUICHE and any classes which depend on QUICHE. Of course, this can extend transitively which is what we're starting to see. We could limit the expansion of this macro, potentially, by providing no-op implementations of some QUIC/HTTP/3 classes so that callers would not need compile-time changes. For example, the conditional in source/common/http/codec_client.cc could be avoided if `EnvoyQuicClientSession`, `QuicHttpClientConnectionImpl`, etc were no-op implementations. It's not entirely clear to me how much effort this would be or how much value there would be in doing it, but it is an option.

**Comment by wrowe** [comment]
Ryan is correct and it's a very important design consideration 

Google QUICHE and BoringSSL is one unit 

OpenSSL and h3 will be another solution

But none of this will ever be mix n match, there will be one TLS provider tied to one http3 implementation, so we should probably modularize things on that basis

**Comment by ggreenway** [comment]
@wrowe we've discussed this previously, and come to the conclusion that it's very unlikely we'll have a 2nd http/3 implementation in envoy, due to the amount of work involved in the first one, so I don't see us having both QUICHE+BoringSSL, and something-else+OpenSSL in the future. However, if OpenSSL could be supported with QUICHE, that would be an option.

**Comment by DavidSchinazi** [comment]
I'm aware of some folks running a fork of QUICHE that works with a fork of OpenSSL which adds functionality required by QUIC. If these QUIC-specific bits ever get merged to OpenSSL, we'll then consider supporting it in QUICHE. But I don't see this happening this year.

**Comment by moderation** [comment]
> I'm strongly against this suggestion for the time being. Perhaps in a few years, but HTTP/1.1 is adequate for many applications and very few scenarios can take advantage of the parallel streaming features of H2/H3.

@wrowe I suspect your objection is making QUIC / HTTP/3 non-optional (versus leaving it as something that can be compiled out)? If HTTP/1.1 is adequate you can configure Envoy to only process that version of the protocol upstream + downstream.

HTTP/3 is already 12% of internet traffic. HTTP/2 is 66% (specification finalized in March 2015). HTTP/1.1 is at 22% - https://radar.cloudflare.com/#anchor-http-versions-vs. With universal browser support (desktop and phone), support in almost all stacks like Envoy, NGINX, Apache, ATS, Traefik, Caddy etc. and finally broad CDN support from Cloudflare, Akamai, Fastly and others, it's likely that QUIC will overtake HTTP/1.1 quickly.

The Node.js project removed QUIC in early 2021 based on lack of progress on QUIC support in OpenSSL - https://twitter.com/jasnell/status/1354525804928004099.  Apparently adding QUIC is happening again after a pause - https://twitter.com/jasnell/status/1401158337157210113

**Comment by mattklein123** [comment]
I think we need to separate the two different threads in here:
1) H1 vs. H2/3: We are not talking about removing H1 and Envoy will always be able to be configured to proxy H1.
2) The actual issue of whether H3/QUICHE is built-in or a compile time extension. On this point, some history: QUICHE/H3 used to be an extension, and it was so hacky that we replaced it with the current compile time option. I agree what we have now is also sub-optimal. Given that there is a legitimate use for the openssl build, my advice is to keep the compile time capability for now and put as much behind stubs as possible to limit the ifdef proliferation. I agree it's not heading in a great direction.
