### ISSUE TITLE
Can't get the original_src filter to work

### ISSUE THREAD

**Issue by zthomas2** [envoyproxy/envoy#17091]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Envoy works correctly without the filter, but when I add the filter as described [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_src_filter#example-listener-configuration) it just responds with `upstream_reset_before_response_started{local reset}`

*Description*:
I am trying to configure Envoy to pass through the IP of the client making the call instead of its own, and to that end I added the original_src filter. After adding this filter it appears that Envoy doesn't even attempt to make a connection to the backend servers at all, and just waits for the 10 second timeout then returns a 503 as described above. If I remove the filter, the connection works correctly

Attached is my envoy.yaml, although I have changed server names etc. The commented block starting at line 18 is what causes the issue.
[envoy.txt](https://github.com/envoyproxy/envoy/files/6696750/envoy.txt)

**Comment by alyssawilk** [comment]
If you follow the instructions here:
https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_envoy_sending_internal_responses
it may help you narrow down what's happening.

**Comment by zthomas2** [comment]
Thanks for the quick reply! I did do that actually, that's how I got the `upstream_reset_before_response_started{local reset}` response; before adding that it was just returning a 503.

I'm not able to get trace logging turned on, mostly because this was set up to use the hot restarter thing in docker and I'm not sure how to pass command line arguments through to the envoy process when that is the entrypoint. I did add `%RESPONSE_CODE_DETAILS%` to the access logs though.

**Comment by alyssawilk** [comment]
argh.  it's not my area but I'm pretty decent with trace logs.  At a guess Envoy is resetting the connection because something's wrong with permissions but without logs I'm less sure of what. Maybe @klarose has other ideas?

**Comment by klarose** [comment]
@zthomas2 

I notice in the configuration you shared that you're setting the `mark` for the original_src filter to 0. As mentioned in the config you linked, that means that Envoy will not mark the upstream packets at all. Perhaps the note should have been more explicit, but without marking the packets, the suggested iptables configuration will not work.

It may help to understand how the routing works here. Normally when you receive a packet whose destination IP is not an IP on your host, the packet is either dropped or forwarded (based on the system's routing table). This means that when you try to establish a connection to an upstream using a source IP that *isn't* on your system (which will likely be the case here), the syn-ack response sent by the upstream as part of establishing the connection will not be properly associated with the syn generated by envoy initially. 

We work around this with the iptables configuration laid out in the configuration link by essentially creating a separate routing table which is matched by all packets marked with a specific value. Basically, the configuration will make sure that responses to packets sent by envoy using the original_src filter are properly routed to envoy, and not to somewhere else. Without that setting, I could easily see the system behaving as though there was a reset before the response started: the upstream connection never really properly establishes, because the syn-acks necessary to form the connection are either dropped or sent elsewhere.

So, without knowing more, my guess is that your problem is that you haven't set up the mark to a value other than 0, and that you haven't set up the iptables rules/routes/etc corresponding to that mark.

Can you give that a try and let me know if that helps? Barring that, it could be useful to take a packet capture to see what is actually going on: does envoy try to establish a connection? Is it using the proper source IP when it does so?

**Comment by zthomas2** [comment]
Thanks for the suggestion @klarose, I will look into it and let you know how it goes!

**Comment by zthomas2** [comment]
I have made the iptables changes as described in the documentation. As an aside, the documentation states that `If Envoy and the upstream are on the same host – e.g. in an sidecar deployment –, then iptables and routing rules can be used to ensure correct behaviour.` This implied to me that those iptables changes would not be needed and/or be irrelivant to a deployment where envoy and the backend targets are not on the same host.

That being said, the iptables changes _did_ change the return code I got. instead of `upstream_reset_before_response_started{local reset}` I'm now getting `upstream_reset_before_response_started{connection failure}` which implies to me that the iptables changes made it so that envoy can't communicate with the backend at all. I will try to do a packet capture next and see what that shows, but in the meantime, are there any other suggestions?

**Comment by klarose** [comment]
I didn't get in to this in my first reply, but the remote side also needs to route the responses back properly.  How is the network between envoy and the usptream set up? Will the upstream route responses to these source IPs back to the machine hosting envoy? Or will it send them back out to the internet?

**Comment by zthomas2** [comment]
I'm going to close this ticket, as we have decided to go a different way and the setup I was trying to do is not required anymore. I'm sorry to anyone who finds this thread in the future that there is no resolution.
