### ISSUE TITLE
[WASM] Delete API for shared data

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/envoy#17217]
With the current state of `proxy-wasm`, shared data has only `get_shared_data()` and `set_shared_data()` methods. It'll be really useful to have a delete method so that shared data can be used for things like implementing a cache, having a simple lookup table etc. Is there any specific reason for not to have a delete method for shared data ? 

https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#proxy_get_shared_data
https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#proxy_set_shared_data

**Comment by lizan** [comment]
@PiotrSikora @mathetake

**Comment by PiotrSikora** [comment]
@NomadXD it's going to be included in the next iteration of the ABI:
https://github.com/PiotrSikora/spec/tree/review/abi-versions/vNEXT#proxy_remove_shared_kvstore_key

For the time being, you can set an empty value. This isn't perfect, since it leaks key memory, but it might work for some use cases with limited number of keys.

**Comment by moonheart** [comment]
Sorry to bother you, is there any progress for this api change ?

**Comment by NomadXD** [comment]
@moonheart No. Proxy-wasm is not actively developed now I guess.
