### ISSUE TITLE
Best practices for configuring max_outbound_frames

### ISSUE THREAD

**Issue by ediezh** [envoyproxy/envoy#17287]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Best practices for configuring max_outbound_frames*

*Description*:

We run envoy through istio service mesh. Recently, one of the service sidecars fails frequently on too many outbound frames error when streaming large files. By increasing the max_outbound_frames setting on that sidecar fixes that problem.

I’m wondering what is the best practices for configuring this value in service mesh? Shout I increase the value for the entire mesh? What about edge proxies?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by mattklein123** [comment]
cc @antoniovicente @yanavlasov

**Comment by lambdai** [comment]
You can also set a max_concurrent_streams in http2 option. Running 100 streams in the same connection is pretty good vs a fixed value 1 on http1 :)

**Comment by yanavlasov** [comment]
It is possible that the service that streams files does so in very small increments (i.e. 100 bytes at a time) and if the client is slow at reading it may cause the error you indicate.
The default value for max_outbound_frameswe have been picked based on experience to make it work well with the [recommended edge setting](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge). Your case may be different, if for instance your service likes to send small data frames (or chunks, depending on the protocol), and in this case you may want to increase this number. This limit is there to prevent resource based DoS attacks. If you find that your proxies run out of memory you may need to do more tuning, such as reducing window sizes and tuning the service to send larger frames.
The service mesh case it tricky, since if you  increase this limit just on sidecars that see errors now, you may end up pushing the problem to other sidecars. You can increase it gradually throughout the mesh until the problem goes away.

**Comment by ediezh** [comment]
@yanavlasov the downstream client is an edge proxy which we have configured following the recommendations https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge. It means the edge proxy has a smaller initial_stream_window_size: 65536. I think that’s part of the cause of this issue too. 

I tested by increasing the edge proxy initial_stream_window_size to the default value 268435456, the problem went away too.

**Comment by yanavlasov** [comment]
Sorry for not responding sooner. I assume that you have changed `initial_stream_window_size` in the edge proxy cluster settings, right? It is hard to tel why it solved your problem, and not just push it to the edge proxy. Perhaps the edge proxy was the bottleneck, or you have a high latency between edge proxy and mesh and as such low stream window cause the available bandwidth the be underutilized.

**Comment by ramaraochavali** [comment]
@yanavlasov @alyssawilk Sorry for commenting on old issue.

For a streaming GRPC service, we are hitting a connection reset after 512 MB because of flow control. We set initial stream window size as 64 KiB and connection window size as 1MB. We see **outbound flood metrics** getting incremented whenever the connection is closed. The max outbound frames is set to default 10000 We can increase that limit but wondering where is this 512 MB limit coming from based current window sizes. 

And are there any side affects of increasing the max outbound frames or any other config tweak can help.

Thank you

cc: @lizan

**Comment by ramaraochavali** [comment]
@alyssawilk @yanavlasov any thoughts?

**Comment by ramaraochavali** [comment]
@alyssawilk @yanavlasov gentle ping ^^. Could you please help with this?

**Comment by alyssawilk** [comment]
Because Envoy does eager serialization in many cases, increasing max outbound frames slightly increases the possibility of adversaries to send malicious traffic flows clogging your Network::Connection with frames they will never read.  If you have legitimate tragic being affected I'd definitely increase the limit and just make sure you have overload manager configured to protect against OOMs.

**Comment by ramaraochavali** [comment]
Thank you so much @alyssawilk

**Comment by ramaraochavali** [comment]
Any insight on the 512 MB limit?

**Comment by alyssawilk** [comment]
Not offhand - I assume it's how much data it takes to hit the required number of frames but AFIK it depends on payload and isn't fixed.  If changing the frame limit doesn't help we can try to look into it.

**Comment by ramaraochavali** [comment]
> If changing the frame limit doesn't help we can try to look into it.

It certainly helped. We have increased the max_outbound_frames things are working fine. Thank you.
