### ISSUE TITLE
wasm: make vm_config.runtime default to V8 (or Wasmtime/WAVM/WAMR).

### ISSUE THREAD

**Issue by mathetake** [envoyproxy/envoy#17321]
Given that almost all Wasm plugin users would put `runtime: envoy.wasm.runtime.v8`, it would make sense to me that make `vm_config.runtime` optional and default to V8 or any runtime which Envoy is compiled with. @PiotrSikora any thoughts?

**Comment by PiotrSikora** [comment]
Yes, we should definitely make `runtime` field optional, and if there is only one Wasm runtime built-in (which is currently the only option), then it should be used without any extra configuration.

It gets a little tricky because of NullVM, but we can always try to load NullVM plugin first before falling back to loading from file/remote.

**Comment by vikaschoudhary16** [comment]
this is done and can be closed.
