### ISSUE TITLE
Context management in request-response cycle

### ISSUE THREAD

**Issue by mdettelson** [envoyproxy/envoy#17540]
*Title*: *Context management in request-response cycle*

*Description*:

> We are currently testing out Envoy's new ExternalProcessor filter type.  We are using this filter to mutate request headers and request bodies before they reach our downstream applications.  We are removing some of this data from the request and then hoping to re-access it on response.
> 
> In development, our filter containers (we have tested with 3 containers running a Go application as our cluster) seems to be maintaining a single context object across the entire request-response lifecycle, which is not what we expected to have happen.  Though this makes our lives easier in some ways (we don't need an external cache to hold onto this data if it can be held in memory of a container), we are concerned that this is not expected behavior and could change in the future.  Since Go's Context library is not doing anything fancy behind the scenes, we have a sneaking suspicion that this peculiar behavior is Envoy-related.
> 
> Is maintaining this context expected behavior for Envoy?

**Comment by mattklein123** [comment]
cc @gbrail

**Comment by gbrail** [comment]
ext_proc starts a bidirectional gRPC stream for each HTTP request/response. (It's basically a long-running gRPC with data going back in forth in two ways.) 

In go, you'd receive a single call to "Process," and in there you read and write to the stream. Envoy doesn't know anything about Go contexts, but I assume that the Go gRPC code creates a single context and you'll use it as you interact with the stream.

This is on purpose, and it is indeed supposed to make things easier for implementers of external processors, since you can maintain state with the gRPC stream. (In Go you handle the whole stream from a single function, running in a single goroutine, so it's particularly easy.) In most cases you shouldn't need a separate state table or anything like that.

**Comment by mdettelson** [comment]
Awesome!  Thank you for clarifying that this behavior is expected :)

**Comment by liu-cong** [comment]
Had the same question and found this super useful. Thanks!

BTW is this documented anywhere? It will help future developers :)
