### ISSUE TITLE
Outlier detection vs admission control filter

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#17650]
Hi folks,
We have a use case where we want to fail the outbound request immediately if the upstream server is down to precent further overwhelming the upstream. I can see 2 options in envoy:
1.  outlier detection  + panic threshold
    -  for panic threshold, there are two possible options:
        - panic mode is on + fail_traffic_on_panic is on OR  
        - panic mode is off. 
    - outlier detection will eject hosts until the panic threshold and then all requests will fail immediately  
2. admission control filter

Can you please help me understand what are the main differences between these 2 options? What's the recommended option?

Thank you!!

**Comment by ggreenway** [comment]
cc @tonya11en @mattklein123

**Comment by tonya11en** [comment]
Outlier detection with `fail_traffic_on_panic` will stop all traffic to that upstream cluster for some amount of time after the configured % of hosts have been ejected. This would have the effect of reducing load on an overwhelmed upstream cluster, but it is time-based and will not necessarily resume sending traffic the moment the upstreams are no longer overwhelmed.

Admission control will gradually increase the amount of load shedding it does as the request failure rate increases. This would have a leg-up on the outlier detection approach because it still sends traffic to the upstream to measure the request failure rates. Take a look at https://github.com/envoyproxy/envoy/pull/11910 for some graphs showing what this looks like.

The major problem with admission control is that it doesn't have support for per-cluster or per-virtualhost domains. All requests, regardless of their destination vhost/cluster are lumped together in these measurements, so to use this in your case you would need to utilize it on ingress traffic on the destination service's sidecar (if you can). However, it defeats the purpose of "client-side throttling" to do this. It's something I had meant to address but never got around to.

I'd be happy to work with you on an admission control change that adds the distinct failure rate measurements for vhosts or clusters. Otherwise, you're better off using outlier detection for your client-side throttling story until someone gets around to adding this functionality to the admission control filter so it can be considered "finished".

**Comment by hochuenw-dd** [comment]
Thank you @tonya11en! This is clear to me now :) So it's another more _adaptive_ filter like the adaptive concurrency one XD.
I'll use outlier detection for now and also look at the admission control change once I'm more familiar with the codebase.

**Comment by gongcon** [comment]
Can you reopen this issue? We use locality weighted lb instead of zone aware lb. Per [CommonLbConfig doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-commonlbconfig), only one of [zone_aware_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-zone-aware-lb-config), [locality_weighted_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-locality-weighted-lb-config) may be set. We are out of luck to use `fail_traffic_on_panic`.
