### ISSUE TITLE
Support fail_traffic_on_panic without zone aware routing

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#17659]
Hello folks,
I'm trying to implement client-side throttling using envoy. My use case is to prevent further overwhelming the upstream cluster when it's degraded/down. To do this, apart from the admission control (which is awesome but current doesn't support per cluster/vhost), I can see 2 potential solutions using outlier detection.  
- outlier detection + disabled panic mode
- outlier detection + enabled panic mode + enabled fail_traffic_on_panic

In our environment, we have to disable panic mode, because to enable fail_traffic_on_panic, it needs to enable zone aware routing. To enable zone aware routing, according to this [doc](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/zone_aware_routing), it needs users to define static local cluster in the bootstrap file, and it also needs change in the upstream service. These are hard to do in our environment.

But I think a potential concern with panic mode disabled approach is that envoy would return 503 only after every upstream host is down. Let's say 80% upstream cluster is down, if we disable panic mode, the traffic may further overwhelm the rest 20% of the traffic and bring the whole upstream service down which is the opposite of what we want to do here.  Instead, enabled panic mode + fail_traffic_on_panic don't have this issue because it can start failing all requests when x% of traffic is down. 

I don't know whether this is just a rare case in reality. I guess most likely in reality 100% service would go down, so panic mode disabled should work fine. But I feel this may happen when the upstream cluster does a partial rollout (say 80% on v2, 20% on v1)

Is my understanding correct? If so, is there a way to use fail_traffic_on_panic without zone aware routing?

Thanks!!

**Comment by tonya11en** [comment]
Can you link to the docs you're referencing? From my understanding, you don't need to have zone-aware routing enabled for this since it's a [common LB config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-healthy-panic-threshold).

That being said, I really think what you want here is admission control-- this is exactly the scenario it's mean for, but it's just missing the per-cluster state tracking. The idea is based on [client-side throttling from that Google SRE book](https://sre.google/sre-book/handling-overload/).

Are you trying to accomplish this without any code changes? If so, I think you may be limited to what you mention in the description. Otherwise, you'll have a much better experience by adding this functionality to the admission control filter.

**Comment by hochuenw-dd** [comment]
@tonya11en Thanks for the reply!
> Can you link to the docs you're referencing? From my understanding, you don't need to have zone-aware routing enabled for this since it's a common LB config.

To disable panic mode (set healthy_panic_threshold to 0), users don't need zone-aware routing. But per my understanding, to enable panic mode and fail requests immediately when it's in panic mode (set fail_traffic_on_panic to true), users need to have zone-aware routing since it's a [zone-aware lb config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster-commonlbconfig-zoneawarelbconfig). But I feel like technically zone-aware routing shouldn't be a requirement. That's why I created this issue asking if we can extend it to the common lb config.

> That being said, I really think what you want here is admission control-- this is exactly the scenario it's mean for, but it's just missing the per-cluster state tracking. The idea is based on client-side throttling from that Google SRE book.
> 
> Are you trying to accomplish this without any code changes? If so, I think you may be limited to what you mention in the description. Otherwise, you'll have a much better experience by adding this functionality to the admission control filter.

I agree it's admission control is what we want if it supports per-cluster state tracking. We are trying to achieve the goal in a very short term (by the end of August), so for now contributing to the admission control filter is not an option for me given my knowledge to envoy codebase. But I may look into this later.

**Comment by hochuenw-dd** [comment]
Hi @csssuf, I see you added the fail_traffic_on_panic feature. Is my above understanding correct (users have to turn on zone-aware routing if they want to use fail_traffic_on_panic)? Does this feature request sounds reasonable to you? Thanks

**Comment by gongcon** [comment]
Can you reopen this issue? We use locality weighted lb instead of zone aware lb. Per [CommonLbConfig doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-commonlbconfig), only one of [zone_aware_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-zone-aware-lb-config), [locality_weighted_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-locality-weighted-lb-config) may be set. We are out of luck to use `fail_traffic_on_panic`.
