### ISSUE TITLE
Setting http headers within the request body callback - proxy wasm

### ISSUE THREAD

**Issue by dragoscalinescu** [envoyproxy/envoy#17669]
A common use case is adding a checksum header to sign the body.
However, the header API is not accessible in the body callbacks.

Is there any workaround available for this?

**Comment by ggreenway** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
For adding checksum of the HTTP body, I'd recommend using HTTP trailers instead of HTTP headers, assuming that your client can support them.

As for modifying HTTP headers after processing HTTP body, this is currently not possible in Wasm. It's going to be added back in a foreseeable future for small HTTP bodies (since the whole request/response needs to be buffered to change headers), but generally speaking trailers should be a preferred solution.
