### ISSUE TITLE
FCM based on EDS

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#17726]
*Title*: FCM based on EDS

*Description*:
Currently, we want to match filter chains based on Kubernetes pod IP addresses. These may be large in number (>100) and change rapidly.

Currently, they best option we have is a listener like:
```
match:
  prefix_ranges:
   - 1.2.3.4/32
   - 1.2.3.5/32
   - 1.2.3.6/32
 ```

(IPs are not in a fixed pattern, just an example above)

The problem with this is each update requires pushing the full listener again. This is even worse if we don't have just this match in the Listener (it may be shared with 100s of such matches for different services).

It could be interesting to allow an FCM argument that pulls from EDS. A strawman API:

```
match:
  from_eds: "my-cluster-load-assignment-name"
 ```

Envoy would then send an EDS request for this. It can then use the response as a match.

One thing is the EDS response will have ports as well. For our use case we are really only caring about IP, but to be logically consistent it seems like we may want to make it match the actually ip:port pair returned by the EDS response. I suppose certain responses from EDS like UDS, etc would be invalid...

I could see this being pretty complex to implement/use, so I don't have too high hopes for this, but it could be useful.

**Comment by lambdai** [comment]
I see this requirements consist of two parts
1. The data source of a filter chain. This is a xds protocol feature. That's simplfied version of filter chain discovery service since it focus on the match part of filter chain.

2. the execution of the filter chain updates: upon filter chain match (not the chain) update, the filter chain should be less disruptive than the current implementation. This is dataplane improvement and I can take this one
