### ISSUE TITLE
DNS filter protobuf incompatibility between Envoy 1.18 and 1.19

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/envoy#17921]
*Title*: 

DNS filter protobuf incompatibility between Envoy 1.18 and 1.19

*Description*:

The `upstream_resolvers` field in the DNS filter was repurposed between Envoy 1.18 and 1.18.

I wanted to open a discussion on how control planes should handle this. If the field number was not re-used, then it would be relatively straight-forward to serve one field to Envoy 1.18 and the other to Envoy 1.19. However, since the field has been re-used, the only thing that I can think of is to carry a vendored copy of the old protobuf message (which implies a different type name) and swizzle the type URLs when we marshal the Any.

If that's the only approach, then we can close this out. I wanted to raise the issue in case anyone thinks there's a better approach, or that there should be a Envoy change.

*Repro steps*:

```
$ git diff release/v1.18...release/v1.19 --  ./api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto
diff --git api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto
index 32103540c1..8221c11efb 100644
--- api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto
+++ api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto
@@ -2,8 +2,8 @@ syntax = "proto3";
 
 package envoy.extensions.filters.udp.dns_filter.v3alpha;
 
-import "envoy/config/core/v3/address.proto";
 import "envoy/config/core/v3/base.proto";
+import "envoy/config/core/v3/resolver.proto";
 import "envoy/data/dns/v3/dns_table.proto";
 
 import "google/protobuf/duration.proto";
@@ -51,10 +51,8 @@ message DnsFilterConfig {
     // number of retries multiplied by the resolver_timeout.
     google.protobuf.Duration resolver_timeout = 1 [(validate.rules).duration = {gte {seconds: 1}}];
 
-    // A list of DNS servers to which we can forward queries. If not
-    // specified, Envoy will use the ambient DNS resolvers in the
-    // system.
-    repeated config.core.v3.Address upstream_resolvers = 2;
+    // DNS resolution configuration which includes the underlying dns resolver addresses and options.
+    config.core.v3.DnsResolutionConfig dns_resolution_config = 2;
 
     // Controls how many outstanding external lookup contexts the filter tracks.
     // The context structure allows the filter to respond to every query even if the external
```

**Comment by mattklein123** [comment]
I think we should have a wider discussion of this problem here https://github.com/envoyproxy/envoy/issues/17920 (cc @envoyproxy/api-shepherds), but for this specific issue, if there is something we can do to make this easier I'm open to it, especially since this proto is still alpha (for example reserve the previous field and move this field to a new number, etc.). This wouldn't help you with already released versions but might help you in the future.

**Comment by jpeach** [comment]
Switching the field numbers would help a lot, but if anyone uses this in envoy 1.19.0 or 1.19.1, it would put them in the same position. My GitHub searching only turned up Kuma as a user of this, so maybe it would be OK?

**Comment by mattklein123** [comment]
Not sure if it's OK or not. I'm not really sure what the best thing to do here is unfortunately.

**Comment by jpeach** [comment]
| Envoy | Field 2 | Field 3 |
| --- | --- | --- |
| 1.18.4 | upstream_resolvers | -  |
| 1.19.1 | dns_resolution_config |  -  |
| 1.19.2 | reserved | dns_resolution_config |

Thinking about this some more. If we renumber and reserve the field for the next release, anyone adopting 1.19.2 from a previous 1.19 release can make the transition (because field 2 is reserved and unused). Anyone coming from 1.18.4 can make the transition directly to 1.19.2. So I think that this would be OK.

cc @suniltheta, what do you think about this?

**Comment by suniltheta** [comment]
Yes, I lean towards making **Field 2** as `reserved` for v1.19.2.

**Field 3** is already used up for [`uint64 max_pending_lookups`](https://github.com/envoyproxy/envoy/blob/v1.19.1/api/envoy/extensions/filters/udp/dns_filter/v3alpha/dns_filter.proto#L60)

So we need to find some other field ( **Field 5** may be? ) for *dns_resolution_config*. Hopefully the change that is made in v1.19.2 is also applied on main branch (before v1.20.0 release).

Saying that, there is an incoming change https://github.com/envoyproxy/envoy/pull/17479 in v1.20.0 where dns resolvers are transformed into extensions that will introduce the **Field 4** `config.core.v3.TypedExtensionConfig typed_dns_resolver_config = 4;`.

Another thought is, since there is already a production use case for the DNS filter extension can we promote this API from alpha to fixed version?


cc @abaptiste  @yanjunxiang-google, for their thoughts.

**Comment by mattklein123** [comment]
If people are using this in production, my view is to go ahead and convert it over, and perhaps this would provide the 2 different protos that are needed to handle this?

**Comment by jpeach** [comment]
Ok, I'll post a PR today (just running hazel tests ATM).

**Comment by jpeach** [comment]
> Ok, I'll post a PR today (just running bazel tests ATM).

I posted #17943 which keeps the old field number for control planes moving from 1.19.0 to 1.19.2, but renumbers the field so that control planes can move from 1.18.4 to 1.19.2. The latter set of control planes will still need to carry a patch that reverts the type of field 2.

**Comment by jpeach** [comment]
> > Ok, I'll post a PR today (just running bazel tests ATM).
> 
> I posted #17943 which keeps the old field number for control planes moving from 1.19.0 to 1.19.2, but renumbers the field so that control planes can move from 1.18.4 to 1.19.2. The latter set of control planes will still need to carry a patch that reverts the type of field 2.

This change would be needed in 1.19.2. Is there something that I ought to do to flag it for consideration?

**Comment by yanjunxiang-google** [comment]
HI, James,
I added a comment at #17943 <https://github.com/envoyproxy/envoy/pull/17943>.
I am trying to understand why we need two *
config.core.v3.DnsResolutionConfig* fields here.

thanks,
Yanjun

**Comment by jpeach** [comment]
> HI, James,
> I added a comment at #17943 <https://github.com/envoyproxy/envoy/pull/17943>.
> I am trying to understand why we need two *
> config.core.v3.DnsResolutionConfig* fields here.

Between envoy 1.18 and 1.18, the type of field 2 was changed.The dns filter is used by Kuma service mesh, so when we upgrade envoy we will need to serve xDS to both envoy versions simultaneously. So we need a proto definition where field 2 isn't used for 2 different purposes.
