### ISSUE TITLE
protocol proxy not working with varnish / not working

### ISSUE THREAD

**Issue by unisqu** [envoyproxy/envoy#1828]
protocol proxy not working with varnish / not working? i've tried making it true

can anyone pls give some example / guidance why making it true and it doesnt return anything?

**Comment by htuch** [comment]
You're going to have a to provide a more detailed bug report @unisqu. In particular, we'll need to see what the underlying Envoy config, statistics and logs look like.

**Comment by unisqu** [comment]
https://pastebin.com/p5ZsmEVH
i used a config of google proxy i've gotten online.
it's a great piece of software. everything works until you need to use the 
"use_proxy_proto": true,

pls help give some idea why it's not working from here onwards.

**Comment by htuch** [comment]
Is your client correctly setting the PROXY protocol header on the connection? Also, it doesn't make much sense to be doing `logical_dns` for `lb_type` when you have resolved IPs, you probably want `static` there. 

If you're trying to have your Varnish hosts see the actual client IP, you probably want them to pick up on the XFF headers rather than source IP as well.

**Comment by unisqu** [comment]
I'm too new to this envoy thing. It's not easy to understand the documentation as well. Can you help with the "static" you mentioned? how should i do that? and how do i forward the XFF headers rather than the source IP too?

Please help. appreciate this. if this is done, i'll be one of the early adopter and supporter of this project.

**Comment by htuch** [comment]
Sorry, I actually meant `type`, not `lb_type`. For docs here, see https://envoyproxy.github.io/envoy/intro/arch_overview/service_discovery.html and https://envoyproxy.github.io/envoy/configuration/cluster_manager/cluster.html#config-cluster-manager-cluster.

I think it would be helpful to take a step back and understand better the problem you're trying to solve. I don't know anything about Varnish, but when you say "shows the container ip instead of the real ip of client", I was assuming that something in these upstream hosts is reporting source IP address. Can you elaborate further?

**Comment by unisqu** [comment]
i'm running this envoy, (172.17.0.12) as a docker container forwarding "shadow traffic" to two instances of varnish of 172.17.0.2 and 172.17.0.7
not working with the use_proxy_proto. works without but shows the container ip instead of the real ip of client.
the reported ip of varnish (172.17.0.2 and 172.17.0.7) is 172.17.0.12, the ip of the docker container where envoy resides. how can i make envoy forward the client ip address into X-Actual-IP or XFF?

**Comment by mattklein123** [comment]
@unisqu I'm sorry but it's very difficult to help you with the information you are providing. It almost sounds to me like you want Envoy to speak proxy proto to the backend? That is not currently supported. Can you please try to provide a lot more detail on your setup and what you are trying to accomplish?

**Comment by unisqu** [comment]
envoy is running within a docker container on the same host with ip of (172.17.0.12)
i would like to duplicate traffic on envoy to two varnish instances running on the same hosts too 172.17.0.1 and 172.17.0.2
varnish is showing the originating ip address of the http traffic to be from 172.17.0.12 instead of the client's ip address (remoteaddr)

how do i resolve this?

**Comment by mattklein123** [comment]
Closing this out for now. Please reopen if there are further questions.
