### ISSUE TITLE
Docker installation instructions don't work for "latest"

### ISSUE THREAD

**Issue by ipuustin** [envoyproxy/envoy#18355]
The installation docs for Docker images here do not work: https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-using-docker

    $ docker pull envoyproxy/envoy-dev:38e7d28
    Error response from daemon: manifest for envoyproxy/envoy-dev:38e7d28 not found: manifest unknown: manifest unknown

For non-release versions, the correct tag would probably be `latest` instead of a hash:

    $ docker pull envoyproxy/envoy-dev:latest
    latest: Pulling from envoyproxy/envoy-dev
    Digest: sha256:a15c4a077c0ce9978854822c2765adc300ea62bf465d3d78f04c4c07b0df6b5c
    Status: Image is up to date for envoyproxy/envoy-dev:latest
    docker.io/envoyproxy/envoy-dev:latest

**Comment by phlax** [comment]
hi @ipuustin ive transferred this issue here, as the website repo is just for publishing - the docs are built from the repo here

ill look at the issue further now...

**Comment by phlax** [comment]
hmm, actually i think the problem with the (short) blob sha *is* on the publishing side after all (i recently introduced this bug, apologies)

I have raised a PR here to address the blob sha issue here https://github.com/envoyproxy/envoyproxy.github.io/pull/206/files

in relation to using `latest` rather than the blob sha for referencing the docker image - im broadly in agreement about this, but i believe there was some pushback when i suggested previously. The reason being that `latest` is changing pretty frequently so the docs should reference the specific image

Can i suggest opening a separate ticket specifically to address using `latest` over `blob-sha` ?

**Comment by ipuustin** [comment]
Thanks for the fix! It may be indeed better if the tag is fixed to some sha instead of `latest`. I think that in case of someone archiving the web page, the instructions will stay in sync with the version if it's fixed.
