### ISSUE TITLE
Routing TCP traffic with original destination preserved through hops over multiple Envoys

### ISSUE THREAD

**Issue by amukherj1** [envoyproxy/envoy#18404]
*Title*: *Routing TCP traffic with original destination preserved through hops over multiple Envoys*

*Description*:
>Is there a way to route original destination traffic over multiple Envoy hops? Here is the scheme I had in mind.

    caller --> NAT rule ---> Envoy1 [original dst listener ---> Envoy2] ----> Envoy2 [original dst listener ---> original dst cluster] ---> original dst
> The idea is that Envoy2 might terminate TLS or do some authentication and then forward the traffic to the original destination. Plus Envoy2 acts like a gateway / front-proxy for a set of services? I am trying to do this specifically for TCP traffic.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by lambdai** [comment]
You must find a carrier to deliver the "original dst" at each hop. Pure Tcp doesn't work.

The first hop is carried by NAT impl and the original can be obtained by socket opt SO_ORIGINAL_DST

There are various options at the 2nd hop, including mapping from TLS extensions, ProxyProtocol ,or HTTP CONNECT. 

All the above 3 approaches can embed out of bound TCP data at handshake-ish phase so that you can some how recover the original_dst from
