### ISSUE TITLE
Leverage HDS to implement endpoint registration when running as side-car

### ISSUE THREAD

**Issue by louiscryan** [envoyproxy/envoy#1845]
In orchestrated systems like Kubernetes an endpoint is not registered as available until it passes a local health check. For folks who are using bare-metal/VMs however they have to roll this type of support themselves.

We could in theory have Envoy carry this responsibility instead. The HDS API is designed to handle health-checking remote services but there's not reason we cant use it to have Envoys health-check their local backends. That information could then be pushed into downstream registries like DNS, Consul or Google's via adapters to the HDS API as long as the contract/semantics were clear.

It might also be useful for Envoy to standardize an endpoint that orchestrators use to get the health-check result and delegate that behavior to envoy completely given that it's a network behavior really. For example Istio could rewrite K8S health-checking rules to delegate them to Envoy

@davecheney
@rshriram

**Comment by rshriram** [comment]
what do we do about script based health checks?
Secondly, this would mean that we bootstrap envoy with endpoint metadata (labels, port mappings, etc.). 

If I wanted health checks on multiple ports before registering my endpoint, then these health checks have to be hard coded in the initial boot strap configuration supplied with the endpoint. And since its typical for applications (java ones specifically) to have health check and the main app run on the same port, generating the right configuration settings for the health check filter/cluster involves knowing about the protocol of the destination, certificates if any.

These are not show stoppers, but it just duplicates some small parts of the control plane functionality into a static configuration where the user has to figure these settings out.

**Comment by htuch** [comment]
@louiscryan This seems a reasonable use of HDS. What is the ask in this issue though? Are you after any HDS API changes to support this? Should we be describing a reference architecture for this in the docs somewhere? Is there a concrete implementation change we want to see? Note that HDS is not implemented today yet.

I don't quite follow the last paragraph. The way HDS works today, Envoy reaches out to the management server (so, orchestrator), and then has its health check requests/responses flow on the stream. Are you after initiation of HDS in the other direction?

**Comment by mattklein123** [comment]
I think we can consider this a duplicate of https://github.com/envoyproxy/envoy/issues/1533? IMO HDS can be effectively used for registration if we consider Envoy HCing a backend (or even itself if an edge node).
