### ISSUE TITLE
How to use multi cpu cores in persistent TCP connection scene?

### ISSUE THREAD

**Issue by smwyzi** [envoyproxy/envoy#18537]
Saying ServiceA calls ServiceB, if ServiceA use a persistent TCP connection(such as HTTP2 or GRPC), according to Envoy's thread model, ServiceA will call Envoy with one persistent TCP connection，and only one Envoy worker thread will work, other Envoy workers won't receive request due to no connection accepted.

So how can Envoy use multi cpu cores(more worker thread) in persistent TCP connection scene?

**Comment by rojkov** [comment]
Probably you'll want to configure your Listeners with `connection_balance_config` set to `exact_balance`. So that long-lived connections are distributed evenly over workers.

If you are asking how to split handling of a single connection between multiple cores then there is no way (at the moment at least).

/cc @lambdai to correct me if I'm wrong.
