### ISSUE TITLE
how to tune parameters of envoy for high performance any advice?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18548]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
how to tune parameters of envoy for high performance any advice?
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by davinci26** [comment]
This question is quite broad because Envoy has a pretty rich feature set of extensions and usecases. I would advise you to measure on your config. See [how fast is envoy](https://www.envoyproxy.io/docs/envoy/latest/faq/performance/how_fast_is_envoy)

Configurations in [FAQ](https://www.envoyproxy.io/docs/envoy/latest/faq/overview#configuration) provide some sane defaults to get your started with.
