### ISSUE TITLE
test: add log on first enableTimer() call in SimulatedTimeSystem

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#18570]
Spent [long time] debugging https://github.com/envoyproxy/envoy/pull/18487 and neither the happy eyeballs failover alarm nor the backend timer timeout alarm file when running under simtime.    I was unable to figure out how to advance them.  It's unintuitive that time passing doesn't cause alarms to file while network events continue, and  the only prior art for having Envoy alarms fire in integration tests is the idle timeouts integration test, which uses DangerousDeprecatedTestTime and  trying to use that hard-crashed my tests.

I think we should at least log warnings in integration tests when simtime's enableTimer  is called, and best case actually debug and fix the underlying problem.

cc @jmarantz who helped me verify this wasn't just PEBKAC

**Comment by jmarantz** [comment]
I am trying to see what this system looks like from the perspective of the simulated time system. I instrumented as follows:
```
diff --git a/test/test_common/simulated_time_system.cc b/test/test_common/simulated_time_system.cc
index 3fab437be7..c75431a0af 100644
--- a/test/test_common/simulated_time_system.cc
+++ b/test/test_common/simulated_time_system.cc
@@ -314,6 +314,7 @@ void SimulatedTimeSystemHelper::SimulatedScheduler::runReadyAlarms() {
       Alarm& alarm = triggered_alarms_.next().alarm_;
       triggered_alarms_.remove(alarm);
       UnlockGuard unlocker(mutex_);
+      ENVOY_LOG_MISC(error, "runAlarm: {}", reinterpret_cast<uint64_t>(&alarm));
       alarm.runAlarm();
     }
     ASSERT(running_cbs_);
@@ -328,13 +329,13 @@ void SimulatedTimeSystemHelper::SimulatedScheduler::runReadyAlarms() {
 SimulatedTimeSystemHelper::Alarm::Alarm::~Alarm() { simulated_scheduler_.disableAlarm(*this); }
 
 void SimulatedTimeSystemHelper::Alarm::Alarm::disableTimer() {
-  ENVOY_LOG_MISC(error, "disableTimer: {}", this);
+  ENVOY_LOG_MISC(error, "disableTimer: {}", reinterpret_cast<uint64_t>(this));
   simulated_scheduler_.disableAlarm(*this);
 }
 
 void SimulatedTimeSystemHelper::Alarm::Alarm::enableHRTimer(
     const std::chrono::microseconds duration, const ScopeTrackedObject* /*scope*/) {
-  ENVOY_LOG_MISC(error, "enableHRTimer: {}", this);
+  ENVOY_LOG_MISC(error, "enableHRTimer({}): {}", duration.count(), reinterpret_cast<uint64_t>(this));
   simulated_scheduler_.enableAlarm(*this, duration);
 }
```

and then ran the test with `--gtest_filter=IpVersions/ProxyFilterIntegrationTest.UseCacheFileAndTestHappyEyeballs/IPv4`.  I get tons of results like `runAlarm: 84032094815360` . But there appears to be only one timer that looks like it might be 300ms and here is all the activity on that one:
```
[2021-10-11 21:15:39.492][2128173][error][misc] [test/test_common/simulated_time_system.cc:338] enableHRTimer(300000000): 84032094860928
[2021-10-11 21:15:39.495][2128173][error][misc] [test/test_common/simulated_time_system.cc:332] disableTimer: 84032094860928
[2021-10-11 21:15:39.495][2128173][error][misc] [test/test_common/simulated_time_system.cc:338] enableHRTimer(300000000): 84032094860928
[2021-10-11 21:15:39.499][2128173][error][misc] [test/test_common/simulated_time_system.cc:332] disableTimer: 84032094860928
[2021-10-11 21:15:39.499][2128173][error][misc] [test/test_common/simulated_time_system.cc:338] enableHRTimer(300000000): 84032094860928
[2021-10-11 21:15:39.500][2128173][error][misc] [test/test_common/simulated_time_system.cc:332] disableTimer: 84032094860928
[2021-10-11 21:15:39.500][2128173][error][misc] [test/test_common/simulated_time_system.cc:338] enableHRTimer(300000000): 84032094860928
[2021-10-11 21:15:39.500][2128173][error][misc] [test/test_common/simulated_time_system.cc:332] disableTimer: 84032094860928
```

After that, the system goes into its spin loop, with plenty of timer activations, but none of them are for 300ms. So I agree that the 300ms timer (`84032094860928`) is not being called. However I think it's because it's being disabled before it gets a chance to.

Alyssa, does this sort of perspective help? I am not ruling out that this is the fault of simtime but it seems worthwhile understanding why, when we get into that spin-loop later, we haven't got that timer enabled.

**Comment by jmarantz** [comment]
Alyssa's patch is https://patch-diff.githubusercontent.com/raw/envoyproxy/envoy/pull/18487.diff

That one uses a usleep rather than a sim-time advance. Replace that with:
```
    timeSystem().advanceTimeWait(std::chrono::milliseconds(300));
```
to repro. Context is ProxyFilterIntegrationTest.UseCacheFileAndTestHappyEyeballs in test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc.

**Comment by alyssawilk** [comment]
Ok, reprod and it looks like when I switched from usleep to advanceTimeWait it was that upstream timeout alarm that did me in.
So half PEBKAC, but the other half was me spending 2 hours trying to figure out why alarms weren't firing because it's non-obvious in a given test it's using simtime.   So I'd be satisfied with a log on enableTimer that it's using simtime and the alarm will not fire without explicit  timeSystem().advanceTimeWait

**Comment by jmarantz** [comment]
I think I'll also take this opportunity to lint-disallow usleep() calls, and fix the 2-3 references
