### ISSUE TITLE
thrift_proxy: is there necessary for createFilterChain for each new request？

### ISSUE THREAD

**Issue by xiaoma2015** [envoyproxy/envoy#18988]
https://github.com/envoyproxy/envoy/blob/a5927dc3f59e79772a6007b3b5538e86b2a597b0/source/extensions/filters/network/thrift_proxy/conn_manager.cc#L181

I found create new filter chains is a bit time-consuming op. 
create one route filter took about 31 us.
the log:
![image](https://user-images.githubusercontent.com/10593758/141456559-857c5a93-258b-4122-8ab4-adcfd15d0013.png)

the log code:
![image](https://user-images.githubusercontent.com/10593758/141456829-710b0539-cb4c-4f59-8669-d78d39e70662.png)

**Comment by wbpcode** [comment]
Yep. Because filter chain may retain the states of the request. So for every new request, we need to recreate new l7 filter chain.

In general, a filter instance has only a small amount of request-related states and reference to the filter configuration. If you think it is too slow to create a filter chain, you can use the profile to confirm the specific problem and then optimize it.

**Comment by xiaoma2015** [comment]
> Yep. Because filter chain may retain the states of the request. So for every new request, we need to recreate new l7 filter chain.
> 
> In general, a filter instance has only a small amount of request-related states and reference to the filter configuration. If you think it is too slow to create a filter chain, you can use the profile to confirm the specific problem and then optimize it.

thank you very mush for guidance
it seems a little time consuming on stats generate.

[envoy.cpuprofile.pdf](https://github.com/envoyproxy/envoy/files/7537290/envoy.cpuprofile.pdf)
