### ISSUE TITLE
proposal to shift Envoy's targeted release dates

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#19228]
Right now, according to RELEASES.md, Envoy aims to cut the quarterly releases on the last day of each quarter.

This means annually we would aim to cut a release 12/30, a time when many maintainers are out, and when most Envoy users who run from head are in winter prod-freeze, meaning recent changes have not been as thoroughly tested by early adopters.

The Envoy maintainers propose shifting the annual schedule to either
15 days into the quarter (Jan 15, April 15, etc) or
1 month into the quater (Jan 31, April 30th etc)
again with the usual plus or minus 2-3 weeks allowed by RELEASES.md

We'll solicit feedback here, from Envoy distributors, and at next week's community meeting and update here based on feedback.

**Comment by linsun** [comment]
Hi @alyssawilk we had a discussion in Istio's TOC meeting today, and we believe if Envoy is released on the 15 days into the quarter, it would be best for Istio releases as we typically release 4-6 weeks after Envoy and it is also our best interest to avoid releasing in Dec due to holidays.

Thanks so much for allowing us to provide feedback!

**Comment by alyssawilk** [comment]
Awesome - thanks for the feedback.  I've heard the 15th is better from one other source so we'll likely go with that barring other objections which arise.  It'd also mean this release we could aim for January 15th and not be out of SLO for the prior target of 12/30 +/- 3 weeks and it's nice to not have to worry about when we do the move by having both new and old overlap :-)

**Comment by PiotrSikora** [comment]
The intent behind the 2-3 weeks padding was to make sure that Envoy makes a release within the first 2-3 weeks of the quarter (which has been a case since), but I recognize that the wording put unnecessary pressure on the first day of that window, and noone wants to be always behind the schedule.

As such, I believe that "15th day of the quarter" (+/- 1 week padding, with hard deadline being "the end of the first month of the quarter") would be very much in spirit with the original intent and pretty much a no-op.

**Comment by alyssawilk** [comment]
building on the 15th puts outside of the window of "acceptable delay".  If we expect to regularly build mid month to give the binary soak time I think communicating the actual planned build time is better for downstream distributors.

**Comment by PiotrSikora** [comment]
I agree that it needs to be communicated, but for all practical reasons, it's effectively a no-op. Hence "in spirit".

**Comment by ankatare** [comment]
@alyssawilk Hi, Just for my understanding, this will be effective for current ongoing release ?

**Comment by alyssawilk** [comment]
We've had more requests for the 15th than end of month so plan A is to do this next build exactly on the 15th, which is in-SLO for both the old schedule and the new schedule.

**Comment by ankatare** [comment]
@alyssawilk Ok. Thanks
