### ISSUE TITLE
Envoy CI broken with Bazel@HEAD: "Error: key "@envoy//bazel/external:quiche.genrule_cmd" not found in dictionary"

### ISSUE THREAD

**Issue by c-parsons** [envoyproxy/envoy#19230]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2275#99855095-5591-4b13-a464-1b13d64604f7

`Error: key "@envoy//bazel/external:quiche.genrule_cmd" not found in dictionary`

It doesn't seem like a definition for `@envoy//bazel/external:quiche.genrule_cmd` exists in bazel/external/BUILD in this repository?

**Comment by phlax** [comment]
checking this, i think `@envoy//bazel/external:quiche.genrule_cmd` refers to a file rather than a rule - and afaict its not visible from outside that directory

not sure why that is exactly or whether it is/not a good idea to make it visible, but adding `exports_files` in the `BUILD` directory would expose it

**Comment by alyssawilk** [comment]
cc @danzh2010
