### ISSUE TITLE
access log for upstream requests

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#1927]
Would like the ability to log the host, outcome (response code, headers, upstream-related response flags) and timing (start time, duration) of individual requests to upstreams, particularly in the event of a retry.

I think we'd have a slight preference for a separate log file, but merging this information into the main access log is also a possibility.

**Comment by mattklein123** [comment]
Implementing a totally new log file would be a lot easier, as it could be done directly from the router and not involve the connection manager at all. This one will require a bunch of design thought around config, reusing existing code, etc. Going to mark help wanted until someone firmly signs up for this.

**Comment by zuercher** [comment]
I'm going to start looking at this.

At first blush, it looks like most of `Envoy::Http::AccessLog` can be reused. Some of the `RequestInfo` doesn't entirely make sense[1]. But given a `RequestInfo` and the headers from `Envoy::Router::Filter::UpstreamRequest` I think you can get what I intended. I'm not sure it makes sense to allow filters to be configured, but it seems like they'd work.

That leaves configuration and managing the lifecycle of the logs. Does this otherwise seem like the right track?

[1]
RequestInfo's `requestReceivedDuration()` is by definition 0 since the upstream request doesn't happen until the request is received. The `responseReceivedDuration()` and `duration()` functions are equivalent. Not sure if `healthCheck()` can be determined for an upstream request.
`getDownstreamAddress()` might not be relevant or available for a log of upstream requests.

**Comment by ggreenway** [comment]
FYI: I'm touching a bunch of the same stuff for tcp access logs (implementation in progress).  I'm making some of the fields Optional<> as I go.  We might end up with a big merge conflict if we're both doing this at once.

**Comment by mattklein123** [comment]
@zuercher IMO I would just reuse all of it, including filters, etc. I see no reason to not include them as they would be generally useful. Yes I think this makes sense. I would do a PR in data-plane-api to refactor the logging messages so that they can be included in the new router protos that we have defined. When @rshriram does the work to wire that up you could then add in the new logging support.

@zuercher @ggreenway can the two of you maybe sync up offline/slack to sort things out so that you don't stomp on each other?
