### ISSUE TITLE
For Clarification on OCSP response expiration in OCSP Stapling

### ISSUE THREAD

**Issue by jtrbs** [envoyproxy/envoy#19305]
Hi, "OCSP response expires" related behaviors are described at https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-enum-extensions-transport-sockets-tls-v3-downstreamtlscontext-ocspstaplepolicy. And in Envoy, it relies on the "nextUpdate" field within OCSP response to check whether a response "expires" https://github.com/envoyproxy/envoy/blob/main/source/extensions/transport_sockets/tls/ocsp/ocsp.cc#L128-L131. And it looks like if "nextUpdate" field is not set within OCSP response, the response will be marked as expired directly, which may cause outage when OCSP stapling policy is "STRICT_STAPLING" or "MUST_STAPLE".

1. According to the https://www.rfc-editor.org/rfc/rfc6960#section-4.2.2.1, it is possible that "nextUpdate" is not set, and it does not mean that the response is not valid. In this case, should such OCSP response be used at Envoy? (Currently looks like it should not be sent to Envoy by the control plane). 
2. If the local time is within [thisUpdate, nextUpdate] (inclusive), the OCSP response is considered as valid. What is the Enovy behavior when the local time is < thisUpdate? Will Envoy wait until thisUpdate to use the OCSP response with the cert or this OCSP response is dropped together with the cert when OCSP stapling policy is "STRICT_STAPLING" or "MUST_STAPLE"? 
3. According to https://www.rfc-editor.org/rfc/rfc6960#section-2.4, it is possible that the new OCSP response is available exactly at "nextUpdate" time (or very close to). Then there will be latency sending this OCSP response to Envoy. Is there some buffer at Envoy to be configured which can accommodate such latency (when means Envoy will still use a cert with "expired" OCSP response for TLS during the buffer time)?

**Comment by phlax** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
cc @zuercher

**Comment by zuercher** [comment]
For reference:

> The thisUpdate and nextUpdate fields define a recommended validity
>  interval.  This interval corresponds to the {thisUpdate, nextUpdate}
>  interval in CRLs.  Responses whose nextUpdate value is earlier than
>  the local system time value SHOULD be considered unreliable.
>  Responses whose thisUpdate time is later than the local system time
>  SHOULD be considered unreliable.

>  If nextUpdate is not set, the responder is indicating that newer
>  revocation information is available all the time.

1. Perhaps I'm missing something, but I think the a stapled OCSP response without next-update is not useful for OCSP stapling. If an SSL certificate is compromised and the pre-revocation OCSP responses have no next-update value then it seems to me the attacker can use the revoked certificate and staple the pre-revocation OCSP response. Client would continue to accept the certificate until its revocation reached them through other means (e.g. a certificate revocation list). Envoy does currently treat an OCSP response with no next-update as immediately expired and hence does not return it in lenient-stapling mode and triggers failures in strict-stapling and must-staple mode. I'm willing to consider changing the behavior so that responses without next-update can be treated as having an indefinite expiration. I expect this would be a runtime flag given what I outlined above. Do you have a use case that requires this behavior?
2. Currently Envoy only uses the this-update field to populate certificate details in the [admin API](https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/certs.proto.html#envoy-v3-api-msg-admin-v3-certificatedetails-ocspdetails). I think this encodes the implicit expectation that some external process queries the certificate authority for an OSCP response and hence this-update is never in the future (given reasonably-well synchronized clocks). Is there a case where a certificate authority produces OSCP responses with a validity interval starting in the future? Arguably Envoy should treat that the same way it treats responses past the next-update time.
3. Envoy expects that the authority that generates the OSCP response is capable of producing responses with overlapping validity intervals and that the overlap is sufficient to distribute the response. The lenient-stapling mode allows some flexibility here: Envoy won't staple the response if it's expired. However, that mode is meant as an operational stepping stone to strict stapling or must-staple modes.
