### ISSUE TITLE
Customize service name for Zipkin/Jaeger

### ISSUE THREAD

**Issue by anvo1115** [envoyproxy/envoy#19329]
Hi,
We want to add Zipkin/Jaeger tracing to our project. According to docs https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#arch-overview-tracing 
"originating service cluster set via --service-cluster".
The problem is that we already use this property in many cases and can't change it.
And on tracing server we need to display different "service name" , not equal to --service-cluster.

Is there another custom way to send "service name" to Tracing server?

**Comment by junr03** [comment]
Not that I know of. However, it shouldn't be too complicated to add configurability via the proto configuration.

**Comment by anvo1115** [comment]
Unfortunately for Zipkin I don't see a field for Service Name:
https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/api/envoy/config/trace/v3/zipkin.proto

**Comment by junr03** [comment]
That's right. I meant to add it to the a new field to the config to be able to set the name.

**Comment by suniltheta** [comment]
I can take a look into this if no one else is already working on this task.

**Comment by suniltheta** [comment]
We can introduce a field `service_name` in the zipkins.proto similar to what we have in DatadogConfig https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/datadog.proto?highlight=service_name

I am trying to get more clarity on the use case that we want to address, so that we know what we are solving here.
From a typical zipkins formatted jarger trace [TRACE.md](https://github.com/envoyproxy/envoy/files/7804428/TRACE.md) we have several fields and annotations in the span.

I am trying to understand which value we want to override here. Is it
- serviceName --> technically contains the value of node name set from from `--service-node`
- node_id --> Same value as serviceName
- upstream_cluster -->  contain the Cluster name set from `--service-cluster`. Not of current node but the upstream.
- Or something else.

**Comment by anvo1115** [comment]
As I see in https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/source/extensions/tracers/zipkin/tracer.h#L62
in zipkin sources it seems that
https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/source/extensions/tracers/zipkin/zipkin_tracer_impl.cc#L101
local_info_.clusterName() is set in service_name. 
I'm not sure but probably upstream_cluster is always set here.

**Comment by suniltheta** [comment]
I looked at the same. It is true that in [Tracer's](https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/source/extensions/tracers/zipkin/tracer.h#L62) `service_name` arg we [set](https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/source/extensions/tracers/zipkin/zipkin_tracer_impl.cc#L101) the `local_info_.clusterName()`. But I am not sure if this value is being used in `"serviceName"` key from span's data. If you look at the file that I attached [TRACE.md](https://github.com/envoyproxy/envoy/files/7804428/TRACE.md) you can see that `local_info_.clusterName()` is not the one present in `"serviceName"` but it is actually the `node_id`, which I guess comes from `--service-node`.

**Comment by anvo1115** [comment]
Unfortunately I don't know how to intercept Zipkin trace that goes from the service.
But in Jaeger UI see in Service field - the value that was set in --service-cluster .
