### ISSUE TITLE
Will we support connection transfer when hot restart?

### ISSUE THREAD

**Issue by cwdsuzhou** [envoyproxy/envoy#19348]
*Title*: Will we support connection transfer when host restart?

*Description*:

Mosn has supported connection  transfer when hot restart? will envoy support this?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ggreenway** [comment]
We don't have any plans to support this.

To implement, it is neccessary to transfer all of the state of connection handling from the old process to the new process. For all cases except a very simple tcp_proxy configuration, this is extremely complicated. In the case of http and TLS, it is probably not possible because the libraries we use for those protocols don't support this. 

So given that it could only be done for an extemely small subset of common envoy configurations, it has not so far seemed worthwhile.

**Comment by cwdsuzhou** [comment]
> We don't have any plans to support this.
> 
> To implement, it is neccessary to transfer all of the state of connection handling from the old process to the new process. For all cases except a very simple tcp_proxy configuration, this is extremely complicated. In the case of http and TLS, it is probably not possible because the libraries we use for those protocols don't support this.
> 
> So given that it could only be done for an extemely small subset of common envoy configurations, it has not so far seemed worthwhile.

@ggreenway thanks for your reply!
