### ISSUE TITLE
hang in http2_integration_test's CookieRoutingNoCookieNoTtl

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#1937]
It's somewhat difficult to reproduce outside of CI. Locally, hung copies of the test are stuck in `FakeUpstream::waitForHttpConnection(client_dispatcher, upstreams)`. Unlike the hang that @alyssawilk debugged last week, this test does invoke the client dispatcher.

In practice, when running the test repeatedly, macOS ends up with roughly 7,000 connections in the TIME_WAIT state. At that point, the connections to FakeUpstream (which are using http1 in this test) start taking longer to complete. The connect timeout is 5 seconds, and I believe that in some cases the connection times out and the test ends up waiting for a connection that timed out.

If I bump the timeout up to 30s, it seems I can run the test for as many iterations as I like (10,000+). With a 1s timeout it reliably fails after a few hundred iterations. I can modify this particular test to increase the timeout easily enough, but I'm not sure that's a great solution.

**Comment by zuercher** [comment]
To be clear, I don't think the problem in CI has to do with connections in TIME_WAIT. As far as I can tell, the entire test suite only creates about 1500 connections. It is the case that the large number of TIME_WAIT connections seems to slow down the connection rate and I surmise that if the CI host is sufficiently bogged down, integration test connections may timeout.

**Comment by zuercher** [comment]
In my proof-of-concept I added a setConnectTimeout function to the config helper. The call site can be `#ifdef __APPLE__`. Or we could so something similar within the helper so that it's set for all tests.

Ultimately, I think this is just an example of "your CI box will always find a way to occasionally take longer to perform a task than you can possibly imagine." I think this can actually happen in any of the integration tests that use an upstream, but since these Http2RingHashIntegrationTests create 50 connections per test, it just happens there most often.

**Comment by mattklein123** [comment]
On CI I buy it, I'm just surprised you can actually repro it locally. That seems surprising to me.

**Comment by alyssawilk** [comment]
Yeah, I definitely buy that overloaded boxes are going to run slow.

If it were time-wait based, SO_REUSEADDR on test sockets might help.  We've
had problems on our inteneral proxy test suite where we used up all the
available ports on 127.0.0.1 (which is why I tend towards using alternate
loopback) but then it wouldn't wait out time_wait, it'd fast-fail on
failing to listen.

I think it's totally worth having a general timeout scale function - we've
found in the past that setting one-size-for-all timeouts tends to bite you
on tsan and asan builds, and if we generally have a function to scale
timeouts it'd be easy enough to default-scale-up for Apple there.

Meanwhile I really wish I could repro mac issues locally.  I'll poke around
here and see what chrome's doing for cross-platform testing as it'd be nice
if we can mooch off of whatever system they use.
