### ISSUE TITLE
slow start mode formula result very big edf dealine_ cause slow start invalid

### ISSUE THREAD

**Issue by jiangshantao-dbg** [envoyproxy/envoy#19526]
in slow start window, endpoints need slow start receives no traffic and beyond the slow start window, they still receive no traffic. because endpoints which need slow start will have a very high `deadline_` in edf scheduler.
```
(gdb) ppqueue queue_
$25 = {
  deadline_ = 300000,
  order_offset_ = 1,
  entry_ = {
    __ptr_ = 0x555562060158,
    __cntrl_ = 0x55556205b260
  }
}
$26 = {
  deadline_ = 2,
  order_offset_ = 2,
  entry_ = {
    __ptr_ = 0x555561eed7d8,
    __cntrl_ = 0x555561f4c820
  }
}
Priority queue size = 2
Priority queue capacity = 2
``` 
if host_weight=1, then `weight=host_weight * applyAggressionFactor(time_factor)` will be less than 1, but `deadline_ = current_time_+1/weight` will be too big.
and the endpoints will receive no traffic because it will never in top of the queue_ utils the normal endpoints deadline_ catch up it. this cause beyond the slow start window the endpoints still receive no traffic.

3. istio default set the host weight to 1. so don't work in istio. and may cause bug when deployment rolling update, just old endpoints receive traffic may cause these pods load too high.

> @jiangshantao-dbg @du2016 thanks for reporting the issue, this is unfortunate that the bug has not been caught in tests. I've submitted [patch](https://github.com/envoyproxy/envoy/pull/19518) for fixing slow start config propagation in Round Robin Lb. Would suggest to open a dedicated issue for revisiting the slow start formula. cc @tonya11en @wbpcode

how about change slow start formula to just a static percent. just use `aggression` as `new_weight=weight*aggression`. default aggression to 0.5, which means slow start endpoint just receive 50% of traffic to the normal one.

use formula can't avoid a too small new_weight which will cause unexpected situation.

_Originally posted by @jiangshantao-dbg in https://github.com/envoyproxy/envoy/issues/19437#issuecomment-1011685017_

**Comment by wbpcode** [comment]
cc @nezdolik may be we can create a configurable min factor to compute new weight just as my previous comment?

**Comment by tonya11en** [comment]
The purpose of the aggression term is to control the curve of the ramp-up. Changing the formula to be linear would defeat the purpose. 

If my understanding of the problem is correct, this is an unfortunate side effect of the EDF scheduler. The weights can't be adjusted until the host is selected and re-added to the scheduler, but the slow-starting host is being starved out by the normal weight hosts. 

My suggestion is to set a minimum allowable weight (something like 5% of the original weight) to prevent this. Short of that or switching to a deficit RR scheduler or something along those lines, this will likely always be an issue.

**Comment by jiangshantao-dbg** [comment]
yes, add a config field to allow user setting a minimum allowable weight is ok to me.
