### ISSUE TITLE
Provide necessary license and documentation for envoy Jaeger tracing plugin to ensure open source designation

### ISSUE THREAD

**Issue by cjp421** [envoyproxy/envoy#19554]
*Title*: *Provide necessary license and documentation for envoy Jaeger tracing plugin to ensure open source designation*

*Description*:
> I would like to leverage the Jaeger Tracing plugin within my organization's envoy docker containers.  In order for this to be allowed, I need to provide evidence that the plugin uses a support license agreement.  I have submitted https://github.com/envoyproxy/misc/issues/1 requesting for a license to be specified and the README updated to provide a reference to the source code used to generate the plugin.

*Relevant Links*:
> Related conversation - https://github.com/jaegertracing/jaeger-client-cpp/issues/183#issuecomment-595790140
   Reference to plugin in envoy examples: https://github.com/envoyproxy/envoy/blob/main/examples/jaeger-native-tracing/Dockerfile-frontenvoy#L14-L17

**Comment by alyssawilk** [comment]
cc @htuch @phlax

**Comment by cjp421** [comment]
Any updates on this?

**Comment by phlax** [comment]
not sure what the license situation is exactly - i added (or maybe updated) the binary to fix an issue with abi incompatibility some time ago

the binary i added was iirc from a tetrate recipe, i think @lizan knows more about where it came from originally - the url has since been shifted to within the envoyproxy namespace, so i assume its Apache licensed - but not sure and not sure where the source/compile recipe is etc

ideally with this we add some bazel build to build this plugin in envoys ci and then we wont have to worry about this so much or the other concerns iwith hosting a binary in the repo

**Comment by lizan** [comment]
Yes it is Apache license. the Jaeger opentracing C++ library is already deprecated so I don't think we want to invest more in this.
