### ISSUE TITLE
stats: add new API to get a Stats::Store from a ServerFactoryContext

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#19617]
Currently the mechanism to add a stats sink predicate is available to applications that create their own main() rather than using source/exe/main.cc, as they will be able to call MainCommon::server().stats().setSinkPredicate.

However, extension-writers don't get any clear method of getting at a Stats::Store  -- they get a ServerFactoryContext.

A possible workaround exists: `server_factory_context.getTransportSocketFactoryContext().stats().setSinkPredicates(....)` but that is really non-obvious and might even not be the right Stats::Store.

@ravenblackx @pradeepcrao FYI

**Comment by pradeepcrao** [comment]
I had protoyped a solution for this that involves specifying the predicates in the bootstrap as part of the stats config. I can create a PR for further feedback.

**Comment by ravenblackx** [comment]
I was surprised that sink predicates weren't a config thing, so I'd be very happy for it to be that rather than code as I was thinking of doing. :)

**Comment by jmarantz** [comment]
Yeah this is a good time to open your PR to allow configuration of sink-predicates. I'm interested to see what that config will look like if soemone wants to (say) include a few hundred stats that don't have a convenient simple regex that covers them exactly.

**Comment by pradeepcrao** [comment]
Aah, my solution would not solve this. This would still require someone to define the sink predicates in an extension.

What my PR would enable is being able to instantiate such an object using the bootstrap. The PR will also define sink predicates based on the StatsMatcher, that Envoy users can instantiate, without having to write their own predicates in an extension.

**Comment by ravenblackx** [comment]
For additional context, the conceptual use of this was to allow a sink extension to prevent the StatNames it consumes from being invalidated during its own lifetime. It turned out there were a stack of other problems provoked by this (e.g. the shutdown order of events involves an ASSERT that verifies that StatNames have been destroyed, which occurs before the destruction of sink extensions, so if the StatNames were preserved then shutdown crashes).

My eventual workaround was to key a map on pointers to the Metrics combined with int64 hashes of StatNames, so if they become invalid it just leaves dangling keys in the map (which is better than the use-after-free undefined behavior you get if you use StatNames that got deleted or moved, or the assert-crash-on-shutdown that you get if you try to keep the Metrics or StatNames from being deleted when they normally would be).

Given the complications that are provoked if an extension uses the `Stats::Store` directly, I think maybe it's not actually a good idea to make using it easier. Certainly it's no longer something I would want to use. :)
