### ISSUE TITLE
stats: add universal tag support

### ISSUE THREAD

**Issue by kevintchan** [envoyproxy/envoy#1975]
I'd like to tag all metrics exported by Envoy with a tag unique to that instance. This tag would allow me to isolate metrics to debug an instance. The tag value would be based on a command line argument (e.g. --service-node) or environment variable so that each Envoy instance could share a config file.

Thanks!

**Comment by taiki45** [comment]
I'll take this one. I'm just thinking using environment variable will be more extendable way and won't change current behavior until specified the same config as before. So how about adding new field to TagSpecifier message:

```proto
message TagSpecifier {
  string tag_name = 1;
  oneof tag_value {
    string regex = 2;
    string environment_variable = 3;
  }
}
```

Then Envoy will getenv with the env var and add the returned value. If no tag_value is specified, find from TagNames and add default regex for backward compat (current behavior).

I feel `environment_variable` is a little bit log name, so want comments about it. `env_var` might be better?

**Comment by mattklein123** [comment]
@taiki45 this sounds reasonable to me, but if we are going to add additional tag filling options, I would also support direct string add in addition to pull from env variable. I think some (most?) people would just specify the fixed tag directly in the config.

@mrice32 WDYT?

**Comment by taiki45** [comment]
@mattklein123 I'm also thinking about supporting fixed string or not. I'll do that.

**Comment by mrice32** [comment]
@mattklein123 absolutely.  At Google, we will use the fixed string in the config rather than the environment variable.

**Comment by ggreenway** [comment]
If this uses an environment variable, I believe this would be the first case that envoy looks at the environment at all.  I think it would be preferable to put it in the config or on the commandline, for consistency with how everything else in envoy is configured.

**Comment by mattklein123** [comment]
Initially I had the same reaction about env vars as @ggreenway did, but then I thought about it and I'm OK with it if people want it. I think in certain cases supporting env var interpolation might be convenient for people. This case comes to mind, as does logging/dynamic headers.

I don't really feel strongly about it though if there is strong objection. I think as long as it is clearly documented it's fine either way.

**Comment by taiki45** [comment]
For consistency, I actually slightly felt the same thing when I thought about error handling of missing environment variables: since Envoy has put configuration in the config file or on the commandline, the missing environemnt variables error might be a little bit confusing.

Then I'm thinking about passing default tags as commandline args like `--stats-tag=service_cluster:local --stats-tag=my_tag:a`. With it, uses can use the same configuration for different Envoy instances (this issue requires), and it can accept arbitrary tags.

We might use env var interpolation in other cases, but in my current opinion, supporting universal tags with commandline args is better way in this case. WDYT? Please tell me if I missed the downside of this. Maybe commandline args can be long sometimes, but I don't think it can be a problem in most cases (not certainly).

**Comment by mattklein123** [comment]
Sure, CLI SGTM and per @ggreenway I think fits better with that Envoy typically does. If this works for you we can skip env var until if/when someone really needs it. If you add the CLI support, the values can just be passed to the stats store on startup.

**Comment by davinci26** [comment]
@mattklein123 @ggreenway I would like to implement the env variable or command line support for tagging as I want to use it in our production environment.

The history is a bit confusing here, because PRs have been merged and then some got reverted. AFAICT the `--stats-tag` is not available right now.

Is the preference still to set have this a command line option instead of reading from the env?

**Comment by mattklein123** [comment]
Yeah CLI please.

**Comment by mattklein123** [comment]
cc @jmarantz also to weigh in on ^.

**Comment by jmarantz** [comment]
CLI >> env-var, but having read through this bug I still don't understand what this is trying to do. Stats-tagging works now via regexes (or RE2s) in the config, or hard-coded in well_known_names.cc.

**Comment by davinci26** [comment]
@jmarantz the scenario that I am looking at we have envoy deployed into a set of machines and all the envoys are statically configured and they dont talk to an XDS server.

We want to tag Envoy stats with the machine name for filtering purposes. This machine name is an environment variable.

AFAICT the existing framework does not support this because the [config.metrics.v3.TagSpecifier](https://www.envoyproxy.io/docs/envoy/v1.19.1/api-v3/config/metrics/v3/stats.proto.html?highlight=stats%20tags#envoy-v3-api-msg-config-metrics-v3-tagspecifier) only supports a fixed value.

**Comment by ggreenway** [comment]
FWIW, I accomplish the same thing by running the bootstrap config through `envsubst` before starting Envoy. The advantage of this approach is that you can change anything in the config without requiring an envoy change for each one.

**Comment by davinci26** [comment]
I was also thinking of a similar approach as a backup but the environment I am work on does not have `envsubst` so I will have to write a script to do the replacement. 

Thinking that this might be the case for multiple users, it makes sense to me to have envoy do this for all users.

> The advantage of this approach is that you can change anything in the config without requiring an envoy change for each one.

Agree on that. For now, I only have the tagging requirement.

**Comment by davinci26** [comment]
Is there any concern if I go ahead and implement this feature?
