### ISSUE TITLE
Stateless ADS push semantics

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#1988]
**Issue Template**

*Title*: Push semantics in ADS/xDS

*Description*:
Seems that the aggressive EDS/RDS request behavior makes it hard to implement a stateless management server.

Currently, Envoy requests EDS aggressively. As soon as it receives a response, it makes another request. For a server that's trying to push an EDS update, this creates a lot of complexity. First, the server needs to leave one of the requests open (otherwise, Envoy spins forever). That means it needs to know that all resources made it through EDS. Unfortunately, Envoy only accepts resources that have been asked as `resource_name` in EDS request. In case that Envoy requests resources one by one, the server now needs to track how many resources have already been acknowledged by the remote Envoy node. That information will have to be embedded in the version or be tracked in some shared cache between management server instances. This tracking per node/resource requires some state and prevents writing a stateless push server.

cc @htuch @mattklein123

**Comment by mattklein123** [comment]
@kyessenov I'm sorry but this is a very complicated issue and you will need to be much more specific. Can you please provide the exact sequence of events (in as much detail as possible) that is problematic.

Is the issue in ADS that Envoy collapses all of the EDS requests into a single request? E.g., First {E1}, then {E1, E2}, etc.? 

Is the issue that you don't know when Envoy doesn't care about an EDS anymore? {E1, E2} -> {E1}? (Basically you don't know when a watch is gone)

@htuch wrote all this code and is in a much better position to follow up on this, but I don't think I can help until I better understand the problem. I can see many possible solutions here specific to ADS in terms of how Envoy sends and receives messages, since internally, Envoy is already doing a substantial amount of logic to do the muxing.

**Comment by mattklein123** [comment]
@kyessenov I talked to @htuch offline and I think the concerns are basically ^ and he has a good plan to fix, but for other readers probably useful if you can provide more color.

**Comment by kyessenov** [comment]
Sorry about limited context in the question. I filed it right after chatting with @htuch. The basic premise is that we are looking to implement a management server that can safely ignore `resource_names`.  If the config server is pre-populated with some responses, then we need to push them to proxies with a fresh version. That works well for LDS/CDS since the response should have all new listeners and clusters. But for EDS, there is a bunch requests coming for different subsets of fresh and new clusters. If we respond to all requests with the same desired set of endpoints, Envoy spins forever asking for more and more updates. So it means we should look at the requested resource names, and then make sure that all updated resources have been asked by a particular Envoy node.
