### ISSUE TITLE
Proxy Protocol: Not getting real IP of client

### ISSUE THREAD

**Issue by shubhammittal90** [envoyproxy/envoy#19927]
Hi,

I am using envoy proxy to get the real IP address of the client for TCP connection. I am using TCP proxy filter and proxy protocol listener filter along with Upstream protocol filter. But I am getting the below error in the logs when connecting to the proxy i.e. localhost:10000 (proxy listens on 10000 port).

Error:
[2022-02-14 05:33:17.483][1][debug][upstream] [source/common/upstream/strict_dns_cluster.cc:178] DNS refresh rate reset for 172.17.0.2, refresh rate 5000 ms
[2022-02-14 05:33:20.958][23][debug][filter] [source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:67] **_proxy_protocol: new connection accepted_**
[2022-02-14 05:33:20.959][23][debug][filter] [source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:445] **_failed to read proxy protocol (exceed max v1 header len)_**
[2022-02-14 05:33:20.959][23][trace][main] [source/common/event/dispatcher_impl.cc:227] item added to deferred deletion list (size=1)
[2022-02-14 05:33:20.959][23][trace][main] [source/common/event/dispatcher_impl.cc:112] clearing deferred deletion list (size=1)

Envoy yaml:

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/99635064/153812600-350118bf-b6e9-4d2e-b003-637a515bf7be.png">

Why I am getting an "exceed max v1 header len" error?

**Comment by soulxu** [comment]
proxy protocol filter is for the client send the proxy protocol header https://www.haproxy.com/blog/haproxy/proxy-protocol/.

if you just want to get the client's ip without proxy protocol, it needn't the proxy protocol filter, envoy will get that for you.

**Comment by shubhammittal90** [comment]
I want the real source IP. Here is my use case:

100 servers connecting (n1....n100) to 1 server (A) via envoy proxy. So If server20 is connecting to server A via Envoy proxy then I want that Server A should have Src IP as Server20's IP not Envoy proxy IP. 

How can we achieve this in envoy? I researched a lot and found that proxy protocol is the only option to get the real IP of the source. But when I am using it then I am getting the error described in the first comment. 

Am I using it correctly or Do I need to make any changes?

**Comment by KBaichoo** [comment]
cc @alyssawilk @wez470  as proxy protocol filter owners

**Comment by soulxu** [comment]
I think you should use https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/original_src/v3/original_src.proto#original-src-filter

**Comment by shubhammittal90** [comment]
Hi,
I have already tried original source filter but for using it we need to do the extra setup. That I don't want to do. I got that for using the proxy protocol we need to send the proxy protocol header in the client request. Is this true? Then only the envoy detects the proxy protocol header. Or Do I need to do some extra configuration on the envoy side?

**Comment by shubhammittal90** [comment]
Hi All,

I got the source address in proxy protocol v1. I tried with nc command and added proxy protocol header as below:

printf "PROXY TCP4 172.17.0.3 172.17.0.2 0 3000\r\nGET /login HTTP/1.1\r\nHost: 172.17.0.2\r\n\r\n" | nc 172.17.0.4 10000

Please see the tcpdump collected at envoy proxy node which shows the source IP information is collected at Proxy protocol.

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/99635064/154033290-363473a8-f7e7-4951-99d9-583095b3810e.png">

Thanks for the support!!

**Comment by cobb-tx** [comment]
@shubhammittal90  i hava same problem,How did you solve it

**Comment by MichaelSasser** [comment]
With docker there are two ways that come to my mind.

## Docker
### 1. Use host mode
You would run the container's network using the [Host network driver](https://docs.docker.com/network/drivers/host/). But this comes at a price. You can no longer refer to other containers by their container name, as envoy would no longer use Docker's built-in DNS. Network wise, it would behave like you would have installed it directly on the machine. This also means you would need to make those ports you want to use with envoy available to the host machine. You also can't add any other docker networks to the container envoy runs in.

### 2. Use iptables instead of Docker's userland-proxy
If you would rather not use host mode, You could consider disabling docker's `userland-proxy`, and telling it to use iptables instead. The issue with the `userland-proxy` is that it strips the package origin. By using iptables, you would preserve this information.

You can do that, by adding the following entries to your `/etc/docker/daemon.json`:
```json
{
  "iptables": true,
  "ip6tables": true,
  "userland-proxy": false
}
```
You might need `"experimental": true` in there too because of `ip6tables`. I'm not sure. If you only use IPv4, you might not need `ip6tables` at all, though.

## Envoy

On the envoy side, you can now pretend envoy is running on the host instead of a container. At least network wise. You only need to enable ´use_remote_address` and set `xff_num_trusted_hops` to `0` (if this instance is the edge proxy), assuming the client understands this header. They usually do.

```yaml
# Downstream filtes
- name: envoy.filters.network.http_connection_manager
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
    # [...]
    use_remote_address: true
    xff_num_trusted_hops: 0
    # [...]
```
For more information see [HTTP header manipulation - x-forward-for](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for)
