### ISSUE TITLE
Compressor filter won't apply to the response from ext authz server

### ISSUE THREAD

**Issue by xxx0624** [envoyproxy/envoy#20003]
*Compressor filter won't apply to the response from ext authz server*

*Description*:
> Hi, I just found out that the Envoy (v1.19.x) won't compress the response from the ext authz server. Is this expected? If yes, is there any way to compress it somehow?
- `1st case`: For API requests that will be forwarded to the upstream service (which means the ext authz server allows this request), I can see that the response from upstream service is compressed properly.
- `2nd case`: For API requests that failed by my ext authz server, the envoy will forward the response back to client directly. But I found that here the response is not compressed!

Then I find out that why it's not compressed: because in the above `1st case`, if the request is allowed by the ext authz, the `filter manager` will go to the next filter (at this time point, I checked the log and sure that this part of code https://github.com/envoyproxy/envoy/blob/v1.19.1/source/extensions/filters/http/compressor/compressor_filter.cc#L155-L158 was executed then the `accept_encoding_` is NOT NULL!) 
But in the above `2nd case`, this piece of code (https://github.com/envoyproxy/envoy/blob/v1.19.1/source/extensions/filters/http/compressor/compressor_filter.cc#L155-L158) is not executed, then when compressing response (https://github.com/envoyproxy/envoy/blob/v1.19.1/source/extensions/filters/http/compressor/compressor_filter.cc#L246) the `isAcceptEncodingAllowed(headers)` returns FALSE!

**Comment by KBaichoo** [comment]
cc @dio @gsagula

**Comment by goncaloacbsilva** [comment]
@KBaichoo Hi! I'm a Computer Science student from Instituto Superior Técnico (Portugal) and I plan to address this issue for one of my courses (where we have to contribute to open-source projects).
The response is not being compressed because ext_authz is stopping the filter chain iteration: instead of moving to the next filter with `continueDecoding()`, a local reply is immediately returned at `CheckStatus::Denied` case https://github.com/envoyproxy/envoy/blob/51964702956d64adcd1df6b8ea132e863fe78e74/source/extensions/filters/http/ext_authz/ext_authz.cc#L355-L400
Is there any specific reason for not calling `continueDecoding()` in this case?
From my point of view, this method should be called even if the request is denied, we could then skip some decoding methods at the compressor to avoid compromising performance (i.e. why try to decode request data if the request was refused).
I already have a patch ready to be submitted that fixes this issue and implements the "skipping" referred above, can I open a PR?

**Comment by KBaichoo** [comment]
Hi @goncaloacbsilva 

The filter chain shouldn't be advanced as we're sending a local reply e.g. stop the chain and send some error response.

The error response can go through the encoder filter chain.

The easiest way to have this compress the response from the ext_authz filter would be to have the compressor filter run before the ext authz filter so it can grab the accept-encoding and use the information to compress the local response generated in case 2.

**Comment by goncaloacbsilva** [comment]
@KBaichoo Thank you for your response!
Meanwhile, I noticed exactly that when I was doing some tests with the configuration. Guess I over-engineered this issue because I jumped straight to the code instead of looking more carefully at the configuration.
As you were saying, if we put the filters in the following order:
- compressor
- ext_authz

Then we get the desired behaviour:
For OK responses:
`client -> compressor -> ext_authz -> upstream`
`client <- compressor <- ext_authz <- upstream`

For failed responses:
`client -> compressor -> ext_authz`
`client <- compressor <- ext_authz`

In this case, I think this issue should be closed

**Comment by KBaichoo** [comment]
Thanks for validating @goncaloacbsilva ! Good luck with the project (note we do also have some beginner issues here: https://github.com/envoyproxy/envoy/labels/beginner if you're still interested -- though feel free to grab other issues you're interested in)
