### ISSUE TITLE
Configurable histogram buckets without using config

### ISSUE THREAD

**Issue by VillePihlava** [envoyproxy/envoy#20088]
**Title**: Configurable histogram buckets without using config

**Description**:
Currently histogram buckets are only configurable through the config. At least for the histogram added in https://github.com/envoyproxy/envoy/pull/19180 the default buckets don't work at all and instead only the same set of buckets: [1,2,3,4,5,6,7,8] would ever be used.

Would adding an option to configure a custom default set of buckets directly in code  (maybe overrideable through the config?) make sense? This would remove the need to change the config every time for histograms that always use the same configured buckets.

**Comment by adisuissa** [comment]
> Would adding an option to configure a custom default set of buckets directly in code (maybe overrideable through the config?) make sense? This would remove the need to change the config every time for histograms that always use the same configured buckets.

I'm not sure I understand what do you mean by "configure custom default set of buckets directly in code". Can you provide some more information here?

cc @jmarantz as this is related to the stats domain.

**Comment by VillePihlava** [comment]
I hope this explains it more clearly:

These buckets are assigned by default to histograms if buckets are not specified in the config:

https://github.com/envoyproxy/envoy/blob/83f050620cec04885a74bc19cae6dcc314d1df8f/source/common/stats/histogram_impl.cc#L111-L115

Instead of using these default buckets if nothing is found in the config, would an option to assign a set of default buckets to histograms (maybe  through constructor parameters?) make sense?

**Comment by jmarantz** [comment]
@ggreenway also has interest and insight into this.

IIUC, right now there's only one set of buckets used for all histograms, which you can accept as default or read from config, but every histogram gets the same buckets. I think @VillePihlava wants to allow per-histogram bucket configuration, which makes sense to me at a high level.

Two counterpoints:
 * the data-model exposed in JSON output implies a shared bucket configuration, and I'm not sure we could easily update that to allow per-histogram config and be compliant with existing JSON consumers.
 * I don't completely understand how the default buckets relates to the XDR histogram system.

From my perspective I understand the histogram compute implications well, but haven't really used them myself to get any useful data out at this point, partially because I find it hard to read the /stats output.

**Comment by ggreenway** [comment]
> IIUC, right now there's only one set of buckets used for all histograms

This is incorrect. You can configure histogram buckets per-histogram with rules that match on the histogram name (`histogram_bucket_settings` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#envoy-v3-api-msg-config-metrics-v3-statsconfig). For any histogram that doesn't match one of the configured rules the default buckets are used.

I think the suggestion here is that, in the absence of a bucket config for a given histogram, to be able to specify a different set of defaults in code. I think this makes a lot of sense and I'd be in favor of it.

One possible implementation would be to have a set of default `histogram_bucket_settings` to use, which can be overridden by user config if desired.

**Comment by VillePihlava** [comment]
> I think the suggestion here is that, in the absence of a bucket config for a given histogram, to be able to specify a different set of defaults in code.

Yes, this is it.
