### ISSUE TITLE
Memory leak in the envoy proxy

### ISSUE THREAD

**Issue by darshanpatel29** [envoyproxy/envoy#20187]
*Title*: *Envoy proxy OOMs *

*Description*:
>We have been running Istio sidecar envoy proxies that are consistently leaking memory over the span of a few days (as shown in the chart that uses container_memory_working_set_bytes metric)
![image](https://user-images.githubusercontent.com/46955482/156456887-f7ee97a0-cfb4-4a09-bc59-5d678b049d21.png)

Here's how the heap profile looks like -
![heap_profile](https://user-images.githubusercontent.com/46955482/156457085-7a4941f0-f374-4f9a-ba68-826d85ea02e3.gif)

*Config*:
>Here's the tracing config for the envoy proxy - 
```
"tracing": {
     "http": {
      "name": "envoy.tracers.zipkin",
      "typed_config": {
       "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
       "collector_cluster": "zipkin",
       "collector_endpoint": "/api/v2/spans",
       "shared_span_context": false,
       "collector_endpoint_version": "HTTP_JSON"
      }
     }
    }
```
We have observed this across many different services. This issue may be related to https://github.com/istio/istio/issues/33073

```
envoy  version: 1a5e21be422f0799db124e8014fd94d366e1a1b1/1.18.5-dev/Clean/RELEASE/BoringSSL
```

I can provide any other details if you need them.

**Comment by mattklein123** [comment]
I see Datadog in the above heap profile but it looks like you are using the Zipkin tracer? I'm confused?

**Comment by wbpcode** [comment]
Can you provider some more detailed reproduce configs and steps. It is best not to rely on istio so that developers can reproduce it locally.

**Comment by cgilmour** [comment]
The heap profile also has references to opencensus and lightstep, so datadog's inclusion in the profile is probably equally incidental. Still unexpected, nonetheless.

Just from the shape of graphs of `container_memory_working_set_bytes`, it seems highly likely that this is related to control-plane traffic (keepalives, healthchecks and so on that happen at regular intervals) or other internal requests rather than user traffic. It looks "too linear" for it to be related to inbound traffic that varies in rate.

An isolated envoy-based repro would be helpful, but if that's not trivially available, a `config_dump` from a sidecar's admin endpoint would answer some questions, such as what tracer _is_ configured, and what the grpc configs are.

Although this doesn't seem to be specific to datadog's or any other tracer, we still have an interest in finding the cause because of its impact on customers who directly and indirectly use envoy (via istio, appmesh, etc).

**Comment by darshanpatel29** [comment]
I haven't tried reproducing this yet. But here's the `config_dump` from the envoy dashboard - 
[config_dump.txt](https://github.com/envoyproxy/envoy/files/8184067/config_dump.txt)

I'll try to make an isolated envoy-based reproducible environment to further help with debugging but it may take some time.

**Comment by mattklein123** [comment]
I'm not convinced the symbols in the above heap dump are actually correct. It doesn't make a lot of sense to me. Can we make sure we are using the right symbols when getting the dump? Thank you.

**Comment by AlexRoman** [comment]
We are also seeing a similar memory leak. We use the same zipkin tracer configuration as in the OP. Under heavy load or after a long time the memory usage of envoy grows unbounded. With tracing disabled, envoy runs stable memory wise. I will try to get some dumps with a recent dev version.

**Comment by darshanpatel29** [comment]
@mattklein123 Sorry for the delayed response. I can get another heap dump to confirm that symbols are correct. I was following this page to get the memory profile - https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

@AlexRoman  Can you please explain to me how did you disable tracing?
