### ISSUE TITLE
Missing "x-amzn-trace-id" (and other trace ids) in response headers

### ISSUE THREAD

**Issue by mkielar** [envoyproxy/envoy#20272]
*Title*: *Missing "x-amzn-trace-id" (and other trace ids) in response headers*

*Description*:
> This was originally reported against AWS AppMesh / Envoy for X-Ray integration (https://github.com/aws/aws-app-mesh-roadmap/issues/394), but further evaluation of the issue by @suniltheta showed that it's an issue with any tracing extension, and results from how Envoy support for tracing extensions is built internally.
> Long story short: Envoy doesn't add tracing headers to response if they're missing. This way, proper serving on trace headers fully relies on whether the application container uses tracing SDK (e.g. XRAY SDK) or is otherwise configured to propagate tracing headers from Request to Response.

*Repro steps*:
> 1. Deploy an ECS Fargate Service with Envoy, X-Ray Sidecar and raw, unconfigured `nginx` container acting as the _"application container"_.
> 2. Configure Envoy to send Traces to X-Ray
> 3. Send a bunch of requests to this service using `curl -v ...`
> 4. Observe the following:
>   4.1. Traces of the requests are visible in X-Ray
>   4.2. Nginx sees the `x-amzn-trace-id` header, but is not configured to send it back (also, see "Why i think...." below)
>   4.3. The response - as seen by `curl` - doesn't show the `x-amzn-trace-id` header.
> 
> In https://github.com/aws/aws-app-mesh-roadmap/issues/394 I present in much more details the configurations that were tested using ECS and AppMesh. @suniltheta also describes how he tested this with X-Ray and Jaeger

*Why I think this is a bug?*
> In ideal scenario, where our _"application container"_ is properly configured with XRAY SDK, or performs otherwise configured request-to-response header rewrite, all is fine. But in that ideal scenario, we rarely ever need the trace id.
> Things get ugly, when the requests start failing. Consider following scenarios:
> 1. The _"application service"_ times out and envoy responds with 504. 
> 2. The _"application service"_ fails with some internal error and responds with a `5xx` response code, but does not provide trace-id in the response.
> 3. The _"application service"_ contains a misconfigured XRAY SDK, and the tracing headers are not copied to response
> 4. The _"application service"_ is a 3rd party, closed-source app, which has **no way of being configured to copy these headers**.
>
> In any of these cases the client is unable to provide us with any meaning trace-id to debug issues with the request. I believe it should be Envoy's responsibility to - once it initiated new trace on the incoming request - to ensure that the ID of that trace is returned to the client. **I believe Envoy should delegate the check for existence of the Trace ID to configured Tracing Extensions not only for request processing, but also for response processing.**

**Comment by suniltheta** [comment]
So here are my thoughts:

Currently the request headers are injected with the trace context only in the request path by calling func `injectContext` on the span object ref: [code](https://github.com/envoyproxy/envoy/blob/main/envoy/tracing/trace_driver.h#L54). In the response path we don't have to inject a new context again because we don't want to re-start the lifecycle of the span for a particular request.

But what we can instead make is while we call the `finishSpan` inside [finalizeDownstreamSpan](https://github.com/envoyproxy/envoy/blob/57a85315f4ff34a2931b2eeea275578bccf23dd3/source/common/tracing/http_tracer_impl.cc#L169) or [finalizeUpstreamSpan](https://github.com/envoyproxy/envoy/blob/57a85315f4ff34a2931b2eeea275578bccf23dd3/source/common/tracing/http_tracer_impl.cc#L225), can we also add a new functionality called `copyContextIfMissing` for span class?


2 things can happen here:
1. Response already contains the trace header context (i.e., Backend is instrumented). We don't replace/update it since the upstream might have updated the trace headers.
1. Response doesn't contain the trace header context (i.e., Backend is not instrumented). We will just copy the trace related header fields from request header to response header. This can be similar to `always_set_request_id_in_response` bool (ref: [code](https://github.com/envoyproxy/envoy/blob/57a85315f4ff34a2931b2eeea275578bccf23dd3/source/common/http/conn_manager_utility.cc#L486-L488)) config flag that we have in [HttpConnectionManager](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html). Where we include if the headers are missing. Also need to decide where we want to give the config option (say `always_set_trace_context_in_response`), whether in the HttpConnectionManager (preferably) or the Tracer Config itself.

----

In saying that I am not sure if this was a conscious design decision that was made during the initial days of implementation of tracing support in envoy to not explicitly add the trace context again in the response path. I have this question for the community to seek their opinion. If this is not an issue then I can work on implementation as well.

I tried to look through the earlier issues on this github, I am not sure if this question was brought up earlier and a decision was made there.


Tagging for attention: @dio @lizan @mattklein123

**Comment by mattklein123** [comment]
> In saying that I am not sure if this was a conscious design decision that was made during the initial days of implementation of tracing support in envoy to not explicitly add the trace context again in the response path. I have this question for the community to seek their opinion. If this is not an issue then I can work on implementation as well.

In general, it not a requirement of some (most?) tracing systems for responses to be annotated with a header. Spans are opened on the request path and then finalized at some later time. Each hop owns its owned span start/stop logic, so nothing has to be returned to the previous hop to make this happen.

I'm not sure if this can be done generically for all tracers, but it seems reasonable to me to allow a tracer to be configured to send back headers are finalizing time if it chooses. For example, if there is no response with sufficient context, local context can be added.

**Comment by suniltheta** [comment]
no stale

**Comment by suniltheta** [comment]
no stalebot

**Comment by suniltheta** [comment]
no stale bot

**Comment by suniltheta** [comment]
no stale
