### ISSUE TITLE
build: refactor repository_locations.bzl

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2041]
Per slack/issue convo. Opening here to track. The goal here is to make it less confusing to see what versions of things we are using and to update them.

See https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl

cc @jmillikin-stripe

**Comment by jmillikin-stripe** [comment]
Thanks! This'll make it easier to track.

I think it'll be practical to represent the (url, version) for all currently present repos as a dict, since there's only a few combinations. Then it can be applied within `repositories.bzl` as kwargs. Something like this?

```
EXTERNAL_DEPENDENCIES = {
  "backward": dict(
    bazel_name = "com_github_bombela_backward",
    remote = "https://github.com/bombela/backward-cpp",
    commit = "cd1c4bd9e48afe812a0e996d335298c455afcd92", # v1.3
  ),
  "fmtlib": dict(
    bazel_name = "com_github_fmtlib_fmt",
    urls = ["https://github.com/fmtlib/fmt/releases/download/4.0.0/fmt-4.0.0.zip"],
    sha256 = "10a9f184d4d66f135093a08396d3b0a0ebe8d97b79f8b3ddb8559f75fe4fcbc3",
    strip_prefix = "fmt-4.0.0",
  ),
  # ...
}
```

Then a lot of the repetitive boilerplate in `repositories.bzl` can be eliminated.

**Comment by mattklein123** [comment]
@jmillikin-stripe yes +100. My goal is to basically hide the depths of bazel from anyone that is not you or @htuch 😉
