### ISSUE TITLE
Reject thrift router config if cluster/weighted clusters/mirror cluster doesnt exist

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#20559]
Thrift router impl does not check clusters exist while the config is created
 https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/router_impl.cc#L21
Thrift uses the the rds in 
https://github.com/envoyproxy/envoy/tree/main/source/common/rds

However http router impl does check these:
 https://github.com/envoyproxy/envoy/blob/fcf2c551465bc5fae280c8fffce6859278842d9b/source/common/router/config_impl.cc#L101.

HTTP uses the rds in 
https://github.com/envoyproxy/envoy/tree/main/source/common/router

The paths between thrift and http are very subtle and all the class name and template are very similar (but the implantation is totally different), which is another topic.

We do have a check while the traffic is thru the unknown cluster, but that's too late.
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/router.h#L448

-- 

To achieve this, we need to let `RouteEntryImplBase` knows the `ClusterManager` which is from the `FactoryContext`

The fundamental change is to let the `ConfigTrait` provide the information to config
https://github.com/envoyproxy/envoy/blob/ec7ef59ef36ccb5e2a9b20493ae23673504d75b9/source/common/rds/common/config_traits_impl.h#L22

Consider the diff is only two weeks old at the moment and thrift is the only non-test client.
https://github.com/envoyproxy/envoy/commit/e727e1f50b33730a3a4fc061f95bcdd6d0c48768

My proposal is to provide context while create the config, which is what mostly all factories do.
i.e., 
```
ConfigConstSharedPtr createConfig(const Protobuf::Message& rc,  Server::Configuration::ServerFactoryContext& context) ;
```
in 
https://github.com/envoyproxy/envoy/blob/ec7ef59ef36ccb5e2a9b20493ae23673504d75b9/source/common/rds/common/config_traits_impl.h#L22

so the static provider and the config receiver (for rds) can provide the context by trait,
https://github.com/envoyproxy/envoy/blob/main/source/common/rds/static_route_config_provider_impl.cc#L14
https://github.com/envoyproxy/envoy/blob/main/source/common/rds/route_config_update_receiver_impl.cc#L18

==>
so we can let thrift RouteMatcher know the context
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/config.h#L31
who generates those RouteEntryImpl
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/thrift_proxy/router/router_impl.cc#L175

and eventually we can check if the cluster is known or not.

Does it make sense?

cc @htuch  @rgs1  @mattklein123 @tkovacs-2

**Comment by tkovacs-2** [comment]
The `common/router` is using `common/rds` (at least the routing discovery part). The classes have same name because they are for the same purpose, the ones in `Router` extend the ones in `Rds` for extra needs of the http.

To pass additional information to `ConfigTraits::createConfig` should be done through the constructor of the implementing class. https://github.com/envoyproxy/envoy/blob/b77651d0ded885f085f0ac804d3a5f339a9b1925/source/common/router/route_config_update_receiver_impl.h#L21
But I'm ok to add the context as parameters on interface level. It's simpler and to access the context maybe a common need, also no deadweight if not needed.

Also I'm ok with the validation.
Just be careful, even in http the validation in controlled by a flag in the config. I'm not sure, but if the cluster and/or routing is dynamic you may drop a routing but a moment later the cluster would be updated and make the routing correct.

Long ago I opened this issue: https://github.com/envoyproxy/envoy/issues/12836
The thrift proxy is quite fatal for routing/upstream problems and forcefully closes the downstream connection even if the fail is recoverable from downstream point of view. In case of oneway (or async) messages this can cause unreasonably lost messages.
I planned to post a PR to fix this. I don't know, maybe it can help for your case as well.

**Comment by JuniorHsu** [comment]
Thanks for the great input @tkovacs-2 especially the traits flag!
It's implicit that the validation is enabled in static provider [1] but disabled in rds [2], which I missed before.
[1] https://github.com/envoyproxy/envoy/blob/main/source/common/router/rds_impl.cc#L257
[2] https://github.com/envoyproxy/envoy/blob/main/source/common/router/route_config_update_receiver_impl.h#L46

To clarify the naming issue, I spend time to figure out common/router is for http only at the moment, which isn't intuitive to me. Actually the abstraction design in common/rds is beautiful, but common/rds and common/router are with general-purpose appearance of path name to me. Therefore, I spent some time to figure out the rds one is of general-purpose and common/router is for http. Just my 0.02 cents.

I'll go ahead to pass the context for createConfig, thanks!
