### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by aveekroy** [envoyproxy/envoy#20725]
*Title*: Meaning of some terms in the codebase 

*Description*:
Just need to understand the below code - is it a `copy constructor` of C++? - the `Listener Config` part or is it `pass by reference`

<img width="727" alt="image" src="https://user-images.githubusercontent.com/1896820/162339010-562f87be-d0c3-43d4-b97f-4f69560ce868.png">

and for the below, is this `move constructor` for `unique_ptr` along with `template` declaration?

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1896820/162339184-4fa4120e-fda6-4e82-8181-9b549e24b838.png">

**Comment by zuercher** [comment]
`Network::ListenerConfig&` is passing an object by reference. 

`std:unique_ptr<GenericUpstream>&&` is an rvalue reference, which enables using `std::move` to efficiently transfer ownership of the `std::unique_ptr<GenericUpstream>` to the called function.

In the future, please seek out a C++ forum for C++ questions, rather than opening issues with generic C++ questions here.
