### ISSUE TITLE
How to add a new event into current libevent loop?

### ISSUE THREAD

**Issue by daixiang0** [envoyproxy/envoy#20904]
*Title*: *How to add a new event into current libevent loop*

*Description*:

I want to understand how Envoy works with libevent deeper and implement a custom feature, codes are as below:

https://github.com/daixiang0/envoy/blob/485720d072ecbee4f704e337c0692931a5422c2c/source/server/active_tcp_listener.cc#L26-L34

https://github.com/daixiang0/envoy/blob/485720d072ecbee4f704e337c0692931a5422c2c/source/server/active_tcp_listener.cc#L87-L98

The logic is very simple:

1. create eventfd and add event for each worker/main
2. trigger event via `eventfd_write` when `onAccept`

After build, I can get responses via `curl`, which means `onAccept` and `eventfd_write` inside have been called, (check `eventfd_write` result, it works), but it does not call `onEvent` as expected. I enabled trace log, but no helpful info.

Is there a limit that worker/main can not add one new event into libevent loop? Or more things I need to do? Or do I misunderstand how Envoy works with libevent?

Any clues may help me, thanks!

**Comment by lambdai** [comment]
due to RAII , the libevent event(`auto file_event` in your code) is destroyed at the end of the function body. https://github.com/daixiang0/envoy/blob/485720d072ecbee4f704e337c0692931a5422c2c/source/server/active_tcp_listener.cc#L31-L34 
although your eventfd is not closed.

That says, epoll or dispatcher won't watch your eventfd fd anymore.

The immediate fix is to save it in your own TcpListener. Something like: `this->file_event_ = dispatcher().createFileEvent(...)`

**Comment by daixiang0** [comment]
Thanks for your great explanation! 

I thought `dispatcher` stores the event when the event creates before.

Now it works!
