### ISSUE TITLE
Update or deprecate Datadog tracer

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoy#21083]
*Title*: *Update or deprecate Datadog tracer*

*Description*:
The current [Datadog tracer](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/datadog.proto) is at version `1.2.1` [(link)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/datadog.proto) while the latest version is at `1.3.2` [(link)](https://github.com/DataDog/dd-opentracing-cpp/releases/tag/v1.3.2). OpenTracing is deprecated in favor of OpenTelemetry.

Do we upgrade the Envoy Proxy integration or remove the extension based on deprecation of underlying projects?

*Relevant Links*:
https://datadoghq.slack.com/archives/C3ZGCF88Z/p1651209631831539

**Comment by wbpcode** [comment]
cc @cgilmour

**Comment by phlax** [comment]
related #18476

**Comment by alyssawilk** [comment]
cc  @cgilmour @palazzem

**Comment by cgilmour** [comment]
Thanks for cc-ing me on this. Yup, the version of the datadog tracer hasn't been updated in a while, mostly because of a switch to opentracing v1.6.x, whereas envoy is using opentracing v1.5.x. We didn't want to introduce a disruptive change in envoy.

I suspect updating the version of opentracing isn't a viable approach for a few reasons:
- it's [deprecated](18476#issuecomment-937469963)
- an opentelemetry tracer is [being worked on](20281)
- it forces the continued use of outdated dependencies, including the datadog tracer's use of msgpack

It's an important integration for us in its direct use in envoy and indirect use in service meshes like istio and appmesh. And as always, we're happy to put in the work to keep this feature as an option for our users.

So, let us know what approach you'd prefer moving forward and we can start making changes to achieve that.
Thanks!

**Comment by moderation** [comment]
Thanks for the update @cgilmour . When https://github.com/envoyproxy/envoy/pull/20281 is merged, will that replace the need for the existing DD tracer allowing us to deprecate / remove it? Or do you think you'll need a DD specific Otel tracer? From the blogs and docs at https://www.datadoghq.com/search/?s=opentelemetry it looks like a vanilla Otel tracer will work

**Comment by cgilmour** [comment]
Hi @phlax @moderation sorry for the long delay on this topic.

> When https://github.com/envoyproxy/envoy/pull/20281 is merged, will that replace the need for the existing DD tracer allowing us to deprecate / remove it? Or do you think you'll need a DD specific Otel tracer

A datadog-specific tracer is still preferred because of differences in trace IDs, trace propagation headers, sampling and a few other details that don't have an equivalent in OTel.

Some users that are using opentelemetry everywhere will be satisfied with the OTel tracing, and exporting to a collector that translates all the OTel details it can into datadog's equivalent.
However for others that are still using datadog-specific tracers across their systems, it'd be a huge impact to change from that and in some use cases would degrade their experience.

If the overall goal is to remove opentracing, ideally we'd have a chance to submit an update to the existing extension that doesn't use opentracing at all.
This could be done without any wider API changes or breaks in configuration.
In many ways opentracing is an implementation detail of the datadog extension in envoy - a fairly large one for sure - but from an end-user or other code within envoy, it's not an important detail.

Does that approach sound like it'd be acceptable to envoy maintainers?
We'd want to be reasonably certain of its future acceptance before committing to the development.
And as always, we're happy to put in all the development effort for it.

Thanks!

**Comment by moderation** [comment]
Thanks @cgilmour. I think an updated Datadog tracer without the OpenTracing dependency sounds good. If MessagePack is still required it should be updated to the latest version (4.1.1).

That allows Envoy to remove a deprecated and unmaintained dependency while still maintaining the Datadog tracing experience.

/cc @envoyproxy/senior-maintainers

**Comment by gaffneyd4** [comment]
Envoy [is using](https://github.com/envoyproxy/envoy/blob/d0274a7389a86262d95ae347ce850e93a19d6ea2/bazel/repository_locations.bzl#L650-L664) the [actively maintained datadog cpp tracer](https://github.com/DataDog/dd-trace-cpp) so I believe this issue can be closed.
