### ISSUE TITLE
Initiate HTTPConnect using Envoy

### ISSUE THREAD

**Issue by panchn-n** [envoyproxy/envoy#21363]
Hi All,

Based on reading the HTTP Upgrade [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#http-upgrades) I see that Envoy can proxy the Connect requests which works perfectly. But I would like to know if there is a support for initiating the HTTP Connect from with Envoy as well. 

My use case is to initiate HTTP Connect from Istio sidecar to a destination service. 

Please let me know if this is something Envoy supports.

Thanks!

**Comment by lambdai** [comment]
No. 
As far as I know, only tcp proxy can establish a CONNECT and the payload of CONNECT is the bytes from downstream TCP connection.

Currently I set the backend of http to a loopback-ish address, and Envoy sets a listener with the tcp proxy described above

**Comment by alyssawilk** [comment]
I think https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades should cover the TCP parts of your question.
For the rest I think you want to start with sni dynamic forward proxy

**Comment by ramaraochavali** [comment]
@alyssawilk Is it possible to "initiate" CONNECT in http_connection_manager instead of in tcp_proxy? Is this valid per http connect spec? My reading of the spec just talks about creating TCP tunnel from downstream. If we have to use http connection manager, do we have to use upgrade_config with client initiating the CONNECT request?

The reason I am asking is, if we initiate CONNECT at Envoy in http connection manager - we may get benefits of tracing for example (which is what triggered this question for me)?

**Comment by alyssawilk** [comment]
Right now I think there's not a great way to take an HTTP request an encap it in CONNECT without doing 2 passes through Envoy but what Istio is doing is a L7 pass through for HTTP processing, then setting "upstream" to a loopback TCP listener and using the TCP connect path to encapsulate.    https://github.com/envoyproxy/envoy/pull/21942 will allow skipping the double pass in a very narrow set of circumstances.

**Comment by ramaraochavali** [comment]
@alyssawilk Thank you .
