### ISSUE TITLE
Stats broken out by response code and class lead to duplicated metrics in tagged stats formats

### ISSUE THREAD

**Issue by JonathanO** [envoyproxy/envoy#2141]
*Description*:
Stats such as upstream_rq which are broken out by response code (e.g. 404) and response code class (e.g. 4xx) lead to duplicated data in metrics.
For example:
```
cluster.FOO.upstream_rq_403: 2
cluster.FOO.upstream_rq_404: 1726
cluster.FOO.upstream_rq_4xx: 1728
```
Currently leads to the following in Prometheus format:
```
cluster_upstream_rq{cluster_name="FOO",envoy_response_code="403"} 2
cluster_upstream_rq{cluster_name="FOO",envoy_response_code="404"} 1726
cluster_upstream_rq{cluster_name="FOO",envoy_response_code_class="4xx"} 1728
```
Which means that aggregates over the cluster_upstream_rq metric are meaningless (e.g. sum(cluster_upstream_rq) = 3456).

The output should be metrics with both a response_code and response_code_class label:
```
cluster_upstream_rq{cluster_name="FOO",envoy_response_code="403",envoy_response_code_class="4xx"} 2
cluster_upstream_rq{cluster_name="FOO",envoy_response_code="404",envoy_response_code_class="4xx"} 1726
```
Or, alternatively, the response_code_class labels could be dropped entirely since they can be calculated by Prometheus from the response_code labels if needed.

**Comment by mrice32** [comment]
Thanks for finding this.  I think there are a few possible solutions to this issue.  I think your PR is a good fix for prometheus, specifically.  But I have a feeling that other stats systems would have similar problems.

I want to give a little background on how the stats regexes work related to this scenario for anyone who's not well-versed in how these extractions are written (and can be customized in the config).  Basically, the tags are pulled out of the canonical stat name strings in Envoy.  The value of the tag must be a part of that string.  That part of the stat name string (or an encompassing part) of the string can be removed as a part of the extraction process to create the tag_extracted_name that prometheus (and other stats systems, presumably) would use to identify stats.  It is a problem if different logically-declared stat strings (that don't just vary in the tags, but the concept that they represent) map to the same tag_extracted_name.  

In this specific case, we have the two regexes declared [here](https://github.com/envoyproxy/envoy/blob/master/source/common/config/well_known_names.cc#L32) colliding because the stat name `*rq_2xx` has the tag_extracted_name `*rq` and `*rq_200` also has the tag_extracted_name `*rq`.  

We can fix this in a few ways:
1.  A specific fix, as you have proposed, for each stat system to differentiate (or drop) these using some custom functionality for each collision.  
2.  Modifying [these particular regexes](https://github.com/envoyproxy/envoy/blob/master/source/common/config/well_known_names.cc#L32) to make the tag_extracted_names different.  Within the restrictions laid out above, this would mean that the most sensible solution would be to have `*rq_2xx` map to `*rq_xx`.  Note: it would be preferable to name it something like `*rq_class` or something, but we're limited to a subset of the original string.
3.  Small tag extraction redesign to allow the injection of new strings into the tag_extracted_name to get rid of the issue with naming noted in 2 and create differentiated names that make more conceptual sense.

Personally, I think 2 is probably the best general solution for now as long as `*rq_xx` is an acceptable name for folks.  Let me know what you think.  I'm happy to make this quick change to the regexes.

Thanks for bringing this up.  Please let me know if you have any trouble whatsoever with the tag extraction system for prometheus.  We'll be using it for our own stats system in the future, so we're interested in making sure it works well.
