### ISSUE TITLE
Configurable filter of trusted proxies to handle x-forwarded-for header

### ISSUE THREAD

**Issue by Hexta** [envoyproxy/envoy#21639]
*Title*: *Configurable list of trusted proxies to handle x-forwarded-for header*

*Description*:
It'd be helpful for improving security to handle `x-forwarded-for` header from the trusted proxies only if they are specified to filter out forged XFF header from malicious clients.
And add a configuration parameter to specify such trusted proxies. List of CIDR, for example.
In a similar way as `set_real_ip_from` option in Nginx.

**Comment by yanavlasov** [comment]
Sounds like a good feature. @mattklein123  @alyssawilk  for any other comments

**Comment by alyssawilk** [comment]
I think rather than have this simply be a filter you'd want an extension to the original_ip_detection plug-in to sanitize the header before we use it for calculating the original IP.

**Comment by kg-mpg** [comment]
hello, I'm looking for low-hanging fruits to step into envoy by contributing, is this one of them? happy to give it a go

**Comment by keremgocen** [comment]
if there's a consensus on the proposed solution I'm happy to take a look

**Comment by Hexta** [comment]
I agree from my side with @alyssawilk.

**Comment by yanavlasov** [comment]
Yes, looks like it can be an original_ip_detection extension.

**Comment by Hexta** [comment]
@keremgocen Hey, are you going to implement this?

**Comment by keremgocen** [comment]
@Hexta I'm still interested, could you point me to a place where I can understand what exactly I should do better? Should I look at the `set_real_ip_from` implementation in nginx? Or is there another similar filter I can copy the behaviour from? (disc: I'm new to the project)

**Comment by Sush-Dew** [comment]
@Hexta Could you assign this issue to me? I am a beginner and this issue seems a good first issue to resolve.

**Comment by Co9514** [comment]
@Hexta Hi, is someone running an issue?
I want to try it.

**Comment by Rohan-Dah** [comment]
Hey @Hexta .. if the issue's still on I would love to work on this teaming up with folks working on it...

**Comment by style95** [comment]
+1 to this.

**Comment by Kunal-Chandarana** [comment]
Is this work still open? I can ramp up and start looking into this.

**Comment by modatwork** [comment]
> an extension to the original_ip_detection plug-in to sanitize the header before we use it for calculating the original IP.

How can the sanitization outcome be transferred to subsequent extensions? Is there a necessity for each existing extension to modify its code in order to manage the result of sanitization?

Different extensions may have varying policies for dealing with trusted proxies. For instance, the ‘XFF original IP detection extension’ might prefer to bypass the trusted address from the XFF header, while the ‘custom header original IP detection extension’ might solely trust the customer header set by trusted proxies. So, the question arises, how can we manage these differing policies within a single extension?

How about adding a `trusted proxies` config to each existing extension?

**Comment by style95** [comment]
@modatwork 
We can trust traffic coming from trusted proxies only by setting the CIDR of proxies.

**Comment by marshallou** [comment]
hello @Hexta and @alyssawilk, I would like to give this a try as a beginner. but I am a little bit confused with what we want to implement here.

`set_real_ip_from` cidr in Nginx is used to do two things:

1. It is used to [check with source IP (remote address)](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_core_module.c#L2787) to see if the request comes from a trusted proxy, as mentioned by @style95 . If it is not, it will stop the original IP detection process.

2. It is also used to find original ip by checking IPs in `x-forwarded-for` header [code](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_core_module.c#L2791). Once it finds one that does NOT match cidr, it considers it as original IP. Because the matched ones are internal reverse proxy.

I assume we want to implement point 1 above, right? because point 2 does not seem to be compatible with envoy:

1. envoy xff extension seems using [hops](https://github.com/envoyproxy/envoy/blob/6b78796398528e6d9d5c60c24ab1f54bdc57db8e/source/extensions/http/original_ip_detection/xff/xff.cc#L21) to detect original IP address, rather than whether it matches cidr or not.
2. we can not filter out non-matched IPs in `x-forwarded-for` in a new extension. Because the real client IP will never match the cidr. If we filter out real client IP in our new extension, later, xff extension won't be able to find it again.

If we agree that we want to implement point 1, I feel we should change existing xff extension rather than adding a new extension, since it is part of xff extension logic. I am new to envoy and may have misunderstanding in this. thanks!

**Comment by modatwork** [comment]
@marshallou I think it's possible to implemente the same feature as the realip feature of Nginx by adding a new optional parameter, say `trusted_proxies`, to the existed two original address extensions, [envoy.http.original_ip_detection.custom_header](https://www.envoyproxy.io/docs/envoy/v1.28.0/api-v3/extensions/http/original_ip_detection/custom_header/v3/custom_header.proto#extension-envoy-http-original-ip-detection-custom-header) and [envoy.http.original_ip_detection.xff](https://www.envoyproxy.io/docs/envoy/v1.28.0/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto#extension-envoy-http-original-ip-detection-xff). If the new parameter is not provided to the xff extension, the `xff_num_trusted_hops` is used to keep the extension compatible.

**Comment by jamesog** [comment]
Hi folks, I'm also interested in having functionality similar to Nginx's `realip` module.

I see there's been several offers to work on this, but I don't think I can see any open PRs related to it, so I've worked on this a bit and I think I have something that should do the trick.

I'm new to C++ so I'm not convinced my code is 100% idiomatic. Should I open a PR to start the review process or would it be better if someone takes a look at my changes separately? I'm on Slack if anyone wants to talk to me about it.

**Comment by alyssawilk** [comment]
generally the best way to get traction is send out a PR with tests :-)

**Comment by jamesog** [comment]
Then good news! I created #31831 :-)

**Comment by siddharthkhonde** [comment]
hi. is this still open? I can take a look into this as a beginner.

**Comment by jamesog** [comment]
@siddharthkhonde I'm working on the PR mentioned above. Feedback is welcome on the implementation.
