### ISSUE TITLE
re2: depend on the abseil branch instead

### ISSUE THREAD

**Issue by stevenzzzz** [envoyproxy/envoy#21914]
*Title*:  re2: depend on the abseil branch instead.

*Description*:
Right now Envoy depends on the default branch of re2 which uses re2::StringPiece for absl::string_view like operation, we should consider use the "abseil" branch instead so we don't need to take care of re2::stringpiece within Envoy codebase.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by stevenzzzz** [comment]
@yanavlasov

**Comment by stevenzzzz** [comment]
@jmarantz

**Comment by daixiang0** [comment]
Share link https://github.com/google/re2/tree/abseil while no details about what it cover.

**Comment by jmarantz** [comment]
HI @daixiang0 -- not sure what you are asking. This is just a variant of the absl library that uses absl::string_view for representing char data, rather than re2::StringPiece, which is essentially the same class, but replicated inside re2. It's a more convenient to be able to interface to the re2 library view absl::string_view.

**Comment by wbpcode** [comment]
IMO, this is sounds great. But will the "abseil" branch gets the same level of support as the default one?

**Comment by moderation** [comment]
It looks like the `abseil` branch is significantly out of step with main
![image](https://user-images.githubusercontent.com/246317/176482508-cede8b4e-dbb0-493c-9d09-afe32d3cc844.png)

Is there any context on why the `abseil` branch exists, who maintains it, gotcha's etc.?
