### ISSUE TITLE
Provide pre-built binaries in GitHub Releases

### ISSUE THREAD

**Issue by Cloudmersive** [envoyproxy/envoy#22196]
Today, Envoy provides pre-built docker containers but not pre-built binaries.  In the releases page of GitHub, no binaries are available.  In the envoy website, if you click on "Download" it takes you to a page telling you how to build from source.  This is pretty broken as all other major OSS projects provide pre-built binaries so as to ease adoption and to also provide official binaries for use.  The fact that these are not available is likely unnecessarily limiting adoption and seems like it would be easy to fix.

**Comment by phlax** [comment]
hi @Cloudmersive thanks for raising this - i think this is defnitely something we want, and something that has been discussed previously

if you were able to raise a PR i would be happy to review - otherwise i can look at it as time is available - i think its unlikely we are going to get this in place for the imminent 1.23.0 release

**Comment by phlax** [comment]
in the meantime the standard advice to get the binary is to fish it out of the docker image - it is built statically so will work in many situations

**Comment by Cloudmersive** [comment]
Oh fish it out of the docker image!  That is a good idea, will try that

**Comment by jrauschenbusch** [comment]
@phlax Coming with [v1.24](https://github.com/envoyproxy/envoy/releases/tag/v1.24.0) statically linked binaries are now available, aren't they? Is the naming scheme of these binaries stable? If so, I'd like to change my [renovate](https://renovatebot.com/) dependency source from [Tetrate archive-envoy](https://github.com/tetratelabs/archive-envoy/releases) to this repository because then my Dockerfile updates (used for test pipelines) will be in sync with the update of the binary used to created a VM image.

**Comment by phlax** [comment]
> @phlax Coming with [v1.24](https://github.com/envoyproxy/envoy/releases/tag/v1.24.0) statically linked binaries are now available, aren't they?

yes - there are some improvements still to make but that was the first release to include the published binaries. We will most likely backport this to other branches as/when they release also

**Comment by phlax** [comment]
im going to close this ticket - follow ups can be tracked elsewhere
