### ISSUE TITLE
WASM extension appends X-Forwarded-For header for non-proxy HTTP requests

### ISSUE THREAD

**Issue by cgrotz** [envoyproxy/envoy#22201]
*Description*:
I also raised this problem in [proxy-wasm-go-sdk](https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/300), but I think this is actually a bug in envoy.

When making a http call from a WASM filter, the `ProxyHttpCall` method is used (sorry I was not able to locate the implementation on the envoy side). It seems that this always appends a `X-Forwarded-For` header, ignoring other configuration (Which IMHO is wrong, since the request in this case is not forwarded, but origins from the filter).

I try to call a server that doesn't accept requests if they have a `X-Forwarded-For` header, so this causes some problems for me.

*Repro steps*:
Simple example here https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/300

**Comment by StarryVae** [comment]
yeah, `httpCall` in WASM will always add `X-Forwarded-For` header here:

https://github.com/envoyproxy/envoy/blob/9b6bbf28f1db9519be1f85461f5d14030c5a3864/source/common/http/async_client_impl.cc#L144

becase `RequestOptions` will never set `Xff` to false here:

https://github.com/envoyproxy/envoy/blob/9b6bbf28f1db9519be1f85461f5d14030c5a3864/source/extensions/common/wasm/context.cc#L968

cc @PiotrSikora

**Comment by PiotrSikora** [comment]
Agreed, those HTTP/gRPC callouts are not forwarding the original request (at least, not in majority of cases), so they shouldn't be appending `X-Forwarded-For` header.

@StarryVae it would be great if you want to take care of this one as well. Thank you!

**Comment by StarryVae** [comment]
@PiotrSikora yes, i would like to take this, and should we just disable the `xff` in `RequestOptions`?

**Comment by PiotrSikora** [comment]
I think so, I cannot think of a good reason to retain it by default, and making it configurable would require changes to the ABI.

Users that want to restore the previous behavior can get the `X-Forwarded-For` header from the proxied request and add it to outgoing HTTP/gRPC callouts.

cc @mpwarres @kyessenov to see if they have any objections.

**Comment by mpwarres** [comment]
Avoiding appending `X-Forwarded-For` makes sense to me, since as @PiotrSikora said it's not appropriate for the common case of callouts, and there's no way for plugin code to disable it.

Is there any concern about breaking existing plugins that depend on the current behavior? It sounds like we're willing to just require those plugins to be updated to explicitly set it. If it turns out we need an escape hatch for compatibility, I wonder if some boolean field or special environment variable could be added to Wasm filter config to reinstate the previous behavior. But it would be nice to avoid that, and I guess if someone is able to set a value in Wasm filter config, that's not much different than just updating the Wasm code itself.

**Comment by kyessenov** [comment]
The standard mechanism to deal with deprecations is [runtime variables](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/runtime). For a version, you would need to support both old and new behaviors. I think the chances this breaks someone are not that high so there is no need to add APIs. That said, I think there's an ABI issue here with lack of HTTP call options similar to gRPC options available.

**Comment by PiotrSikora** [comment]
I don't believe deprecation via runtime variables is required for experimental filters.

**Comment by mpwarres** [comment]
This issue was fixed by #22604 , but I don't have permissions to close it.
