### ISSUE TITLE
How to report resource usage to control plane while using global load balancing?

### ISSUE THREAD

**Issue by prprdan** [envoyproxy/envoy#22344]
In our scenario, we have several envoy replicas and we want to perform a global lb instead of each envoy instance performing lb by itself. I notice that the official doc recommend to achieve this via control plane.
![image](https://user-images.githubusercontent.com/105788743/180162537-7646b57a-da02-4d0c-b3b3-f647fcc2f7c8.png)
I wonder is there an existing API or config to enable this reporting or do I have to write codes in the Upstream module?

**Comment by phlax** [comment]
@daixiang0 any ideas on this ?

**Comment by daixiang0** [comment]
I am not sure there is an API for it.

ping @envoyproxy/api-shepherds

**Comment by DanEarnETH** [comment]
Thank you very much for reply @phlax @daixiang0 . My origin request is to achieve global round robin, and I think even if there are methods to report resource usage to control plane,  it not a good way to achieve round robin by adjusting priority and weights, because that will change the config too frequently and configs may not be updated in time under heavy traffic.
Currently, I'm doing this via the Stateful Session filter. I add a plugin which can read and write session from an external HTTP server, and this session server is deployed together with my control plane, so it's aware of the hosts under every service and easy to perform round robin. When a request arrives, the plugin requests the session server and the server returns a host using round robin method. Then the filter overwrites the host to jump cluster's load balancing. 
The only problem here is that the job should be done by cluster rather than an http filter, so any further ideas or suggestions?
