### ISSUE TITLE
How to get SSL socket file descriptor from eBPF uprobes on SSL_{read,write}

### ISSUE THREAD

**Issue by yzhao1012** [envoyproxy/envoy#22372]
*Title*: *How to get SSL socket file descriptor from eBPF uprobes on SSL_{read,write}*

*Description*:

Pixie uses eBPF to capture network traffic. When tracing Envoy, Pixie uses eBPF uprobes on SSL_{read,write} functions to trace the clear-text network traffic. Envoy uses SSL_{read,write} in a way that does not set file descriptor of the socket connection in the SSL struct. Where is the file descriptor get set and how to access them?

[optional *Relevant Links*:]
px.dev is the Pixie project website.

**Comment by zuercher** [comment]
Take this with a grain of salt, since I've not puzzled all this out before, but as I understand the code:

Envoy is passing a boringssl `SSL*` to SSL_read/write and that struct is actually a `struct ssl_st*`. That `SSL*` contains `rbio` and `wbio` of type `bssl::UniquePtr<BIO>` which are used for reading and writing.

Envoy constructs the `BIO` struct (a `bio_st`) with a `ptr` initialized to an `Envoy::Newtork::IoHandle`, and `method` configured to use Envoy-provided functions for reading and writing (see `source/extensions/transport_sockets/tls/io_handle_bio.cc`).

Normally, the `IoHandle` is an `Envoy::Network::IoHandleSocketHandeImpl` (`source/common/network/io_socket_handle_impl.h`) which holds the socket's file descriptor and provides methods to operate on it.

**Comment by yzhao1012** [comment]
> Take this with a grain of salt, since I've not puzzled all this out before, but as I understand the code:
> 
> Envoy is passing a boringssl `SSL*` to SSL_read/write and that struct is actually a `struct ssl_st*`. That `SSL*` contains `rbio` and `wbio` of type `bssl::UniquePtr<BIO>` which are used for reading and writing.
> 
> Envoy constructs the `BIO` struct (a `bio_st`) with a `ptr` initialized to an `Envoy::Newtork::IoHandle`, and `method` configured to use Envoy-provided functions for reading and writing (see `source/extensions/transport_sockets/tls/io_handle_bio.cc`).
> 
> Normally, the `IoHandle` is an `Envoy::Network::IoHandleSocketHandeImpl` (`source/common/network/io_socket_handle_impl.h`) which holds the socket's file descriptor and provides methods to operate on it.

This has been what we found as well. Thanks!
