### ISSUE TITLE
Envoy crashes when IPv4-compat listeners are used

### ISSUE THREAD

**Issue by LithiumSR** [envoyproxy/envoy#22449]
Hello everyone,
I recently stumbled across an issue that is leading Envoy (tested on the 1.22.2 release) to crash when IPv4-compat listeners are employed.
I already contacted the envoy security team that confirmed that this crash is not exploitable, therefore I'm opening a public GitHub issue.

The crash itself happens quite often (although not every single time) when I initialize multiple connections targeting an IPv4-compat cluster. Specifically, I noticed that this seems to happen when I do multiple burst of traffic (each with a new set of connections) targeting the same cluster.
I made a debug build of Envoy and captured multiple core-dump, all of them seem to suggest that this is related to the changes introduced in #19716.
I have also verified that reverting the aforementioned commit is preventing the issue from showing up (although this leads to the issue that got fixed by that commit).

I attach the [backtrace](https://github.com/envoyproxy/envoy/files/9212232/backtrace.log) and the [configdump](https://github.com/envoyproxy/envoy/files/9212250/configdump_crash_ipv4compat.log). Please note that the configdump was captured after my Envoy container restarted.

If needed I can share the Envoy debug build + coredump file (although the build itself is 1.6GB).
I think I should also note that I'm using the runtime flag "envoy.reloadable_features.strict_check_on_ipv4_compat".

**Comment by zuercher** [comment]
cc @soulxu since #19176 is implicated

**Comment by soulxu** [comment]
I will check this

/assign @soulxu

**Comment by soulxu** [comment]
@LithiumSR does it happened at listener add or update? saw the backtrace is about a listener is in destructing
```
#0  0x000055f0d9b79925 in Envoy::Server::ActiveTcpListener::~ActiveTcpListener() ()
    at external/envoy/source/server/active_tcp_listener.cc:38
#1  0x000055f0d9b7a7a0 in Envoy::Server::ActiveTcpListener::~ActiveTcpListener() ()
    at external/envoy/source/server/active_tcp_listener.cc:36
#2  0x000055f0d9b7a839 in Envoy::Server::ActiveTcpListener::~ActiveTcpListener() ()
    at external/envoy/source/server/active_tcp_listener.cc:36
```

**Comment by LithiumSR** [comment]
HI @soulxu 
From my understanding this issue starts at line 122 of the connection_handler_impl.c ([see here](https://github.com/envoyproxy/envoy/blob/v1.22.2/source/server/connection_handler_impl.cc#L122)).
I suspect that inserting to the tcp_listener_map_by_address is leading to another entry being replaced, the entry that got replaced out is the one that is destructed due to going out of scope.

**Comment by soulxu** [comment]
> HI @soulxu From my understanding this issue starts at line 122 of the connection_handler_impl.c as part of the addListener() ([see here](https://github.com/envoyproxy/envoy/blob/v1.22.2/source/server/connection_handler_impl.cc#L122)). I suspect that inserting to the tcp_listener_map_by_address is leading to another entry being replaced, the entry that got replaced out is the one that is destructed due to going out of scope (which unexpectedly leads to seg fault as part of the destructor execution).

thanks! yes, it seems like failed at a replacement. But the value of tcp_listener_map_by_address is a shared pointer of `ConnectionHandlerImpl::ActiveListenerDetails`, only when the shared pointer was removed both from `tcp_listener_map_by_address_` and `listener_map_by_tag_`. But there won't be a chance for the value of `listener_map_by_tag_` to be replaced since the tag is unique. I also didn't find a chance the shared pointer was removed from `listener_map_by_tag_` but not `tcp_listener_map_by_address_`, except there is bug in ConnectionHandlerImpl::removeListener.

**Comment by LithiumSR** [comment]
Hi @soulxu 
Let me know how I can assist, if needed I could add some extra log messages and reproduce the issue.
Sadly, as of now it is not easy for me to provide repro-step as this is related to an Istio release with in-house dual-stack support that is not available upstream yet.

**Comment by soulxu** [comment]
@LithiumSR thanks! that will be great to add some log to figure out why a replace of `tcp_listener_map_by_address_` can trigger a destruction of std::shared_ptr<ActiveListenerDetails>.

Since https://github.com/envoyproxy/envoy/blob/5313fa4206217e831367932a21c3e3bc6bf6efb4/source/server/connection_handler_impl.cc#L141 should guarantee both the value of `tcp_listener_map_by_address_` and `listener_map_by_tag_` removed. There shouldn't be a chance `tcp_listener_map_by_address_` keep the last reference of the shared ptr.

Maybe add log at https://github.com/envoyproxy/envoy/blob/5313fa4206217e831367932a21c3e3bc6bf6efb4/source/server/connection_handler_impl.cc#L152 and https://github.com/envoyproxy/envoy/blob/5313fa4206217e831367932a21c3e3bc6bf6efb4/source/server/connection_handler_impl.cc#L165

Ensure the when listener was removed, both `tcp_listener_map_by_address_` and `listener_map_by_tag_` are cleanup.

**Comment by LithiumSR** [comment]
Hi @soulxu 
Perfect, I will make the build and give you the logs by Monday.
Regarding the seg fault in the destructor, I feel it is happening either when it is deferencing the ActiveTCPListener object (*this) or when it accesses config_. I will add a check for this one too 👍

**Comment by LithiumSR** [comment]
Hi @soulxu 
I think you were correct in saying that there may be an issue in the removeListeners.
From my logs it seems that only the tag is getting removed, but the tcp_listener_map_by_address seems to remain untouched.
I'm attaching the logs of the crashing istio-proxy with my custom messages. [fortio-client-crash.txt](https://github.com/envoyproxy/envoy/files/9234232/fortio-client-crash.txt)
You can find the code with the added messages [here](https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5) to get an understanding of which code-path were triggered.

Sadly, I cannot say yet for sure which operation made the ActiveTCPListener destructor raise the SegFault but I hope that the logs can already shed some light on the issue. Let me know if you want me to expand the logs further.

**Comment by LithiumSR** [comment]
Hi @soulxu 
I think you were correct in saying that there may be an issue in the removeListeners.
From my logs it seems that only the tag is getting removed, but the tcp_listener_map_by_address seems to remain untouched.
I'm attaching the logs of the crashing istio-proxy with my custom messages. [fortio-client-crash.txt](https://github.com/envoyproxy/envoy/files/9234232/fortio-client-crash.txt)
You can find the code with the added messages [here](https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5) to get an understanding of which code-path were triggered.

Sadly, I cannot say yet for sure which operation made the ActiveTCPListener destructor raise the SegFault but I hope that the logs can already shed some light on the issue. Let me know if you want me to expand the logs further.

**Comment by soulxu** [comment]
> Hi @soulxu I think you were correct in saying that there may be an issue in the removeListeners. From my logs it seems that only the tag is getting removed, but the tcp_listener_map_by_address seems to remain untouched. I'm attaching the logs of the crashing istio-proxy with my custom messages. [fortio-client-crash.txt](https://github.com/envoyproxy/envoy/files/9234232/fortio-client-crash.txt) You can find the code with the added messages [here](https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5) to get an understanding of which code-path were triggered.
> 
> Sadly, I cannot say yet for sure which operation made the ActiveTCPListener destructor raise the SegFault but I hope that the logs can already shed some light on the issue. Let me know if you want me to expand the logs further.

@LithiumSR thanks! this is so great.

It should be one of those three conditions isn't expected
https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R160-L157

My guessing is this one `!address->ip()->ipv6()->v6only()`, since this is the address reading back from OS after binding, I doubt the v6only flag isn't set as expected.

If my guessing is right, I should be able to reproduce that locally.

I will give it a try tomorrow, a little late for me now.

**Comment by soulxu** [comment]
> > Hi @soulxu I think you were correct in saying that there may be an issue in the removeListeners. From my logs it seems that only the tag is getting removed, but the tcp_listener_map_by_address seems to remain untouched. I'm attaching the logs of the crashing istio-proxy with my custom messages. [fortio-client-crash.txt](https://github.com/envoyproxy/envoy/files/9234232/fortio-client-crash.txt) You can find the code with the added messages [here](https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5) to get an understanding of which code-path were triggered.
> > Sadly, I cannot say yet for sure which operation made the ActiveTCPListener destructor raise the SegFault but I hope that the logs can already shed some light on the issue. Let me know if you want me to expand the logs further.
> 
> @LithiumSR thanks! this is so great.
> 
> It should be one of those three conditions isn't expected [Nordix@486e791#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R160-L157](https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R160-L157)
> 
> My guessing is this one `!address->ip()->ipv6()->v6only()`, since this is the address reading back from OS after binding, I doubt the v6only flag isn't set as expected.
> 
> If my guessing is right, I should be able to reproduce that locally.
> 
> I will give it a try tomorrow, a little late for me now.

quick check the v6only should be set https://github.com/envoyproxy/envoy/blob/0d510b808118afa0073e820409061f6f7ed1aa3a/source/common/network/socket_interface_impl.cc#L89

@LithiumSR would you be able to print out those three conditions
https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R160-L157

Then we can know which one is wrong

**Comment by LithiumSR** [comment]
Hi @soulxu 
There is a mistake in the code that I sent at line 157 https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R157
By mistake the error msg in the commit that I sent you was "Planning to remove listener with tag {} and address {}" like in the message at L151 but, the msg that I used was "Removed listener with address {} from tcp_listener_map_by_address".

This means that the 3 conditions you mentioned are never checked as we stopped at the following "if": https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R153-R155

I will check the conditions in line 153-155 and I will let you know their values :)

**Comment by LithiumSR** [comment]
Hi @soulxu
I added the LOG msg to the first "if" at L153-155 and the outcome is as follows.
It seems that the "isSameTag condition" is never satisfied and therefore the map_by_address is never cleaned up: [fortio-client-crash2.txt](https://github.com/envoyproxy/envoy/files/9237285/fortio-client-crash2.txt).
Do you know how that could happen?

**Comment by soulxu** [comment]
> Hi @soulxu I added the LOG msg to the first "if" at L153-155 and the outcome is as follows. It seems that the "isSameTag condition" is never satisfied and therefore the map_by_address is never cleaned up: [fortio-client-crash2.txt](https://github.com/envoyproxy/envoy/files/9237285/fortio-client-crash2.txt). Do you know how that could happen?

thanks!

That is strange. Maybe we can log out what key we used when insert this listener to map

https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R104-R105

And dump the map's key-value, when you found the tag doesn't match at

https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5L150

**Comment by LithiumSR** [comment]
Hi @soulxu 
I will add some prints where you suggested but I think I can only manage to do that tomorrow.

**Comment by soulxu** [comment]
@LithiumSR by the way, when you generate the new log, would you be able to enable debug or trace log level, which help me understand which operation happened on the listener also. thanks in advance!

**Comment by LithiumSR** [comment]
Hello @soulxu,
As you proposed I added two new logs messages.
I added a "Insert Generic listener with address {} and tag {}" at https://github.com/Nordix/envoy/commit/486e791d6d3abd36448b3ebf4252e113de62b56f#diff-fe538327af200510b78cadc759f2c3af989c822a370d3f8a005b92bc59568aa5R104-R105
I also added an extra print to check which tag was expected and the one that was found when the IF conditions fail.
You can find the file 
[crash_ipv4compat.txt](https://github.com/envoyproxy/envoy/files/9258355/crash_ipv4compat.txt)

Sadly, I did not manage to get a full print of the map.
I will now try to get the debug/trace logs.

**Comment by soulxu** [comment]
@LithiumSR I think I know why there is seg fault.

First, we got new listener `virtualInbound`
```
2022-08-04T07:47:16.909103Z	warning	envoy conn_handler	Inserting generic listener with address [::]:15006 with tag 12
2022-08-04T07:47:16.909152Z	warning	envoy conn_handler	Inserting IPv4 any_addr 0.0.0.0:15006 with tag 12
```

Then the `virtualInbound` was updated
```
2022-08-04T07:47:22.722215Z	warning	envoy conn_handler	Inserting generic listener with address [::]:15006 with tag 13
```
But there is no log for `Inserting IPv4 any_addr 0.0.0.0:15006 with tag 13`. I guess that means this update with `ipv4_compat=false`, maybe this can be ensure by you or from the trace logs.

It means only the `[::]:15006 with tag 13` replaced in the tcp_listener_map_by_address. The `0.0.0.0:15006 with tag 12` still keep in the map.

Then the listener with tag 12 was removed.

```
2022-08-04T07:48:07.534729Z	warning	envoy conn_handler	Planning to remove listener with tag 12 and address [::]:15006, listener_iter->second->listener_tag_ 12
2022-08-04T07:48:07.534774Z	warning	envoy conn_handler	1st IF, tcp_listener_map_by_address.contains(address_view): true AND isSameListenerTag: false
2022-08-04T07:48:07.534783Z	warning	envoy conn_handler	Listener for address in map did not contain the expected tag (expected: 12, got: 13)
```

Since the tcp_listener_map_by_address only have the listener with tag 13 now, then it skip the later check for `0.0.0.0:15006 with tag 12`, and that keep in the tcp_listener_map_by_address, but the listener with tag 12 will be removed from listener_map_by_tag. 

To now the tcp_listener_map_by_address has the last reference of listener with tag12

Then another update coming
```
2022-08-04T07:50:25.177581Z	warning	envoy conn_handler	Inserting generic listener with address [::]:15006 with tag 14
2022-08-04T07:50:25.177616Z	warning	envoy conn_handler	Inserting IPv4 any_addr 0.0.0.0:15006 with tag 14
```

The `Inserting IPv4 any_addr 0.0.0.0:15006 with tag 14` trigger the destruction of listener with tag 12.

At that time, the config of Listener with tag 12 should be destructed, then the ActiveTcpListener of tag 12 still reference those destructed resources.

I think I can come up a fix quickly, you can test in your env.

Thanks for logs again!

**Comment by LithiumSR** [comment]
Hello @soulxu 
I have captured the trace logs. You can find them here:
[trace_logs.txt](https://github.com/envoyproxy/envoy/files/9259472/trace_logs.txt)
They are quite "rich" in content :p

**Comment by soulxu** [comment]
@LithiumSR I bring up a fix https://github.com/envoyproxy/envoy/pull/22563, let me know if you able to test the fix in your env

**Comment by LithiumSR** [comment]
Hi @soulxu 
Thank you! I will build it right away and I will have the results by the end of today.

**Comment by LithiumSR** [comment]
I'm afraid the issue is still there.
I will run more tests soon

**Comment by soulxu** [comment]
emm...maybe you can generate the same logs as previously, then I can help for check that. By the way, you can the listener is v6only or not in the log, that will confirm that is the case trigger the bug.

**Comment by soulxu** [comment]
@LithiumSR I found ListeneSocketFactory::clone doesn't handle ipv6only flag correctly also, you can wait for me fix that before you do another test.

**Comment by LithiumSR** [comment]
Hi @soulxu
I was just building the release with the additional logs.
I will wait for your clone() fix and I will start the tests 👍

**Comment by soulxu** [comment]
@LithiumSR I updated https://github.com/envoyproxy/envoy/pull/22563, but it is still waiting for the CI

**Comment by LithiumSR** [comment]
Hi @soulxu 
From what I can tell the issue is still showing up even after the changes to clone().
I will double-check, add back the custom logs and provide you more information.

**Comment by soulxu** [comment]
@LithiumSR thanks!

**Comment by soulxu** [comment]
One thing I can't get an answer is the log showing you update a listener's v4compat flag from true to false, since the first time you add the listener
```
7:47:16.909103Z	warning	envoy conn_handler	Inserting generic listener with address [::]:15006 with tag 12
2022-08-04T07:47:16.909152Z	warning	envoy conn_handler	Inserting IPv4 any_addr 0.0.0.0:15006 with tag 12
```

It has the log for adding any_addr mapping. It only happened when the v4compat flag as true.

The update of listener, doesn't have that log, it means the v4compat flag is false.

```
7:47:22.721823Z	warning	envoy conn_handler	Inserting generic listener with address [::]:15006 with tag 13
```

So the behavior I guess there is an update of v4compat flag. And indeed, the code doesn't care about this case correctly.

But I also found when we update the listener, we will clone the socket from the previous listener. And it also has bug, it will clone the previous v4compat flag also. And this is why I added the fix here
https://github.com/envoyproxy/envoy/pull/22563/files#diff-b0d5e1a1317df8e22a556ee74d6f728379c5f85ce640a9404acc14bfe8192ad3R963

The problem is that means you never have a chance to update the v4compat flag from true to false due to the issue of socket factory clone. But your log show there is an update that happened. S

**Comment by LithiumSR** [comment]
Hello @soulxu 
Sorry for the delay, here are the new logs with the extra messages as requested.
[istio-mt-esarleo-0_fortioclient-7f885bbd55-t96gp_istio-proxy.log](https://github.com/envoyproxy/envoy/files/9283210/istio-mt-esarleo-0_fortioclient-7f885bbd55-t96gp_istio-proxy.log)
I checked the coredump and the issue is still showing up at the same insert_or_assign due to the replacement of another entry.
I will upload the code with the logs in a branch and give you a link.

**Comment by LithiumSR** [comment]
Hi @soulxu 
It seems that your new fix did the trick :)
The situation seems stable now, I will expand the scope of testing (It will take around 5 hours more)

Thank you so much for looking into this

**Comment by soulxu** [comment]
Thanks! 
Then I can begin to write the version for the main branch, then backport the fix. Let me know if you still found something wrong.

**Comment by LithiumSR** [comment]
Hi @soulxu 
I finished testing, everything came back green. No regression whatsoever from my side :)

**Comment by soulxu** [comment]
> Hi @soulxu I finished testing, everything came back green. No regression whatsoever from my side :)

@LithiumSR, thanks for all the help on the debug and validation!
