### ISSUE TITLE
Backport wasmtime updates to 1.22 branch

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#22561]
Currently the 1.22 branch is showing a couple of wasmtime CVES:

- CVE-2022-31104
- CVE-2022-31169

as there is a 1.22 release pending, and already some delays i think we should backport the recent wasmtime update to resolve

**Comment by phlax** [comment]
cc @mattklein123 @PiotrSikora

**Comment by PiotrSikora** [comment]
Techically, Wasm is still only an experimental feature in Envoy, and Wasmtime isn't even the default Wasm engine.

Note that there are quite a few reliability and security fixes for Wasm since v1.22, both in Envoy and in Proxy-Wasm C++ Host repos, so if we want to backport something, then there are better choices, IMHO.

**Comment by phlax** [comment]
ok - ill close this for now on the basis that there are bigger issues

in this case its triggering CVE alerts, and its not really clear whether these issues actually affect our use in Envoy

either way, i think it would be good if we were able to at least ensure our stable branches were passing our CVE scanner - not least as it is likely to be flagged in users' scanners

cc @moderation @kfaseela
