### ISSUE TITLE
SSL/Auth Termination for Kafka

### ISSUE THREAD

**Issue by abergmeier** [envoyproxy/envoy#22905]
*Title*: Enable separating Auth from Application logic.

*Description*:
When writing application code, it should not matter, how to connect to Kafka. Everything SASL/SSL should be shifted to be injected/terminated via Envoy.
Question is whether to do this in a separate Filter or extend the Mesh Filter.

**Comment by mattklein123** [comment]
cc @adamkotwasinski

**Comment by abergmeier** [comment]
From looking into the source, it seems like using SSL + librdkafka is not compositional/layerable. Thus I would expect the Filter then to have no way of passing API Message along to other Filters.

```mermaid
graph TD;
  filter(KafkaSSLTerminatorFilter);
  terminator(Terminator);
  sslconfig(SSLConfig);
  lib(librdkafka)
  filter --> terminator;
  sslconfig -.-> terminator;
  terminator --rd_kafka_transport_connected--> lib;
  terminator --rd_kafka_send--> lib;
  lib --rd_kafka_recv--> terminator;
```

**Comment by adamkotwasinski** [comment]
Re SSL:
I guess we already have SSL-termination out of the box due to transport socket configured with DownstreamTlsContext?
As of TLS origination, yeah, librdkafka would need to be compiled with SSL and so on, or the Envoy UpstreamTlsContext would need to be made to work with lib "somehow" (ouch) or replace librdkafka with Envoy's connectivity model (ouch as well, that's why I picked librd due to limited time).

Re SASL:
Main point would be hooking into https://kafka.apache.org/31/protocol.html#sasl_handshake
Given it's a simple request-response at the startup of connection (after metadata), we could handle that even in a `broker-filter` and then just re-sequence (minus 1) all the following traffic (as per `If authentication succeeds, subsequent packets are handled as Kafka API requests.`).

**Comment by abergmeier** [comment]
> I guess we already have TLS-termination out of the box due to transport socket configured with DownstreamTlsContext?
As of TLS-origination, yeah, librdkafka would need to be compiled with SSL and so on (we still go the non-Envoy way), or the Envoy UpstreamTlsContext would need to be made to work with lib "somehow" (ouch) or replace librdkafka with Envoy's connectivity model (ouch as well, that's why I picked librd due to limited time).

Not sure I get the point you are making.
Would it be possible to do a TLS handshake as soon as a TCP connection to a Broker gets opened? When we terminate TLS in Envoy then shouldn't the TLS handling be of no consequence for the Kafka client?

**Comment by cpakulski** [comment]
I am not familiar with Kafka protocol, but if it starts with cleartext and TLS handshake follows within the same TCP session, you need StartTLS transport socket and code in Kafka filter to control the StartTLS.
