### ISSUE TITLE
http2 server push issue

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#22933]
As far as I know, the downstream connection and upstream connection are decoupled completely. 
There are no map relationship between a downstream and upstream connection.
However, if the upstream server want to push something to downstream, how can envoy handle this case ?
In my understanding, if we need server push, we must use tcp listener instead of http, is it ? 

For my case, I want to create a  envoy cluster for our kubernetes API servers.  
kubernetes API server works in http2 and the go-client library will use the list-watch mechanism to get object information from kubernetes API server. If go-client sends list request with http2 to envoy, I think envoy can choose an upstream API server to forward the request. But for watch case that means whenever there is some change for k8s object, API server will push back the data to client proactively. How can envoy know which client should go?

**Comment by daixiang0** [comment]
As I know, Enovy works as data plane, it use xDS protocol to sync those info from control plane, like Istio.

**Comment by RogerFuns** [comment]
@zhangbo1882  Interesting problem. I think we can consider the `server push` as another server response. Normally the HTTP request and HTTP response is 1:1 mapping, but after introducing `server push`, the mapping can be 1:N. Since Envoy can work well in 1:1 request/response mapping, should be no problem when it comes to 1:N. Correct me if I'm wrong.

**Comment by qiming-007** [comment]
@zhangbo1882 Interesting problem. I think we can consider the server push as another server response. Normally the HTTP request and HTTP response is 1:1 mapping, but after introducing server push, the mapping can be 1:N. Since Envoy can work well in 1:1 request/response mapping, should be no problem when it comes to 1:N. Correct me if I'm wrong.

**Comment by zhangbo1882** [comment]
From my testing, in http2,  the downstream connection and upstream connection is 1:1 map so that the server push can work. In my original understanding, the http2 map will be N:1. In that case, envoy can not know which client it should send message to.
