### ISSUE TITLE
Lightweight/EDS attached SAN validation

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#23027]
*Title*: Lightweight/EDS attached SAN validation

*Description*:
Currently, we create a cluster for a Kubernetes Service. Each Service consists of Pods, which are given distinct SPIFFE identities. Each pod represents an endpoint within the cluster.

While identities, in our model, are attached to endpoints, in Envoy they are bound to the transport_socket on the cluster (ie, at the Service level). Because of this, we aggregate all of the service accounts and provide a list to the cluster.

This introduces a mismatch. We want to just send a small EDS update just for one ClusterLoadAssignment when a pod scales up/down. However, we can't do that; instead we need to also trigger a CDS push, which is **much** more expensive.

It would be great to be able to either dynamically update the SAN matches or put them in the endpoint level (metadata?).

I considered `auto_san_validation` and/or `override_auto_sni_header` but they don't seem to fit quite as needed since they are HTTP only and we don't want users to override by header, we would want to override internally

**Comment by kyessenov** [comment]
What's the desired behavior when SAN negotiation fails? Should a cluster try another endpoint?

**Comment by howardjohn** [comment]
I think just failing is fine as it would if it failed at the cluster level.

**Comment by kyessenov** [comment]
1. We should be careful not to allow mutation of endpoint policy since changing an endpoint does not trigger any drain I believe. So that means both the policy and the attribute on the endpoint is expected to be permanent.

2. I think we can also use a custom cert validator with its own source of data as well, like https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto.
