### ISSUE TITLE
Proxy wasm set http response body when original response does not have a body

### ISSUE THREAD

**Issue by dragoscalinescu** [envoyproxy/envoy#23181]
Seems that the `on_http_response_body` callback is not called when the original response does not include a body.
Because of this, I don't see a way of setting a different body, except for using `send_http_response` from a different callback.

Should the api trigger the callback with `body_size = 0` in this case?

**Comment by kyessenov** [comment]
cc @mpwarres

**Comment by mpwarres** [comment]
The `on_http_response_headers` callback should already give clear signal as to whether or not a body is expected, via the `end_of_stream` bool param. If `end_of_stream` == true, then the plugin shouldn't expect an `on_http_response_body` callback; IMO that would be a little surprising, since the `on_http_response_headers` callback already indicated the stream ended.

A plugin should be able to call `send_http_response` from the `on_http_response_headers` callback in cases like this. That could be warranted anyways, to allow changing of the HTTP response code for the response.
