### ISSUE TITLE
Circumvent Kafka client protocol metadata without needing to change broker advertised.listeners configuration

### ISSUE THREAD

**Issue by DiegoGamaV** [envoyproxy/envoy#23185]
*Title*: *Circumvent Kafka client protocol metadata without needing to change broker advertised.listeners configuration*

*Description*:
> Me and my coworkers found Envoy Kafka filter while searching for proxies for Kafka to terminate SPIFFE/SPIRE. We noticed it is a little intrusive, since it requires Kafka to point towards Envoy (advertised.listeners) for it to properly work. It would be very useful for Kafka filter to not need this, and maybe tamper a little bit Kafka metadata to change the advertised.listeners of brokers to itself (maybe on different ports?). This would allow for it to be easily plugable, both as front-proxy and as sidecar. 

*Relevant Links*:
>Kafka proxy is an interesting example, and has this feature (although it doesn't have the Envoy SDS to work with SPIRE): https://github.com/grepplabs/kafka-proxy.

**Comment by wbpcode** [comment]
cc @mattklein123

**Comment by mattklein123** [comment]
cc @adamkotwasinski

**Comment by adamkotwasinski** [comment]
@DiegoGamaV yeah, that's doable, you might want to start changing in https://github.com/envoyproxy/envoy/blob/v1.23.1/contrib/kafka/filters/network/source/broker/filter.cc#L49 , conditionally downcasting to Metadata response and then rewriting the data inside (you'll need to somehow figure out the listener address from Envoy codebase, or just add yet another config option if that's hard)

**Comment by caetanobca** [comment]
Hi @adamkotwasinski, searching on the web I found this [demo](https://github.com/flobuehr/spire-envoy-kafka) and that looks like they don't set the Envoy as advertised.listeners. I was hoping that someone with more experience could take a look at this repo and sees if there is something that I didn't see

**Comment by DiegoGamaV** [comment]
Hey, @adamkotwasinski, sorry for the delay.

But isn't this the metrics facade class? Is this really the place to temper with the response? This commented diagram seems to suggest the better place to change this is Request or Response Decoder. https://github.com/envoyproxy/envoy/blob/v1.23.1/contrib/kafka/filters/network/source/broker/filter.h#L111

I apologize if I'm spilling out nonsense, but I'm having having a hard time grasping the workflow of a message in this filter.

**Comment by adamkotwasinski** [comment]
@caetanobca 

So how Kafka works:

1. client sends a Metadata request to one of servers in `bootstrap.servers` about topic(s)
2. response contains all servers (with what they put into `advertised.listeners`) hosting these topics
3. client then drops the connection to the bootstrap.server one [in non-degenerate cases, it's considered to be "-1" broker]
4. .... and then connects to one of the folks from point 2.

I'm not a K8 expert unfortunately, so I think one of the two might be happening here:
a) the Kafka brokers advertise themselves without change, so the _followup_ connection goes _without_ proxy in between (actually we had a problem like this in one of Envoy examples) - only the initial connection (steps 1 & 2) goes thru proxy.
b) hostname resolution magic (given K8 is so complex I'm not ruling this out): have a Kafka broker advertise itself as e.g. "broker1". When it's resolved on broker1, then obviously it's the same machine. But with all the networking/hostname resolution wizardry it might be possible to have the _client resolution_ that points to _proxy_ instead of broker itself. Think something like hacking your `/etc/hosts`.

I didn't run it, but you can figure it out when you turn on logging for (Java) Kafka client for `org.apache.kafka.clients.NetworkClient=DEBUG`. Then you will see the Metadata traffic being sent and received:
Initial connection (notice "-1" shown as initial id):
```
2022-10-18 12:20:02,337 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Sending metadata request MetadataRequestData(...) to node localhost:19092 (id: -1 rack: null)
2022-10-18 12:20:02,343 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Sending METADATA request with header RequestHeader(...) and timeout 30000 to node -1: MetadataRequestData(...)

# THIS RESPONSE HERE CONTAINS THE REAL SERVER (broker id = 1 running at 127.0.0.1 / 19092)
2022-10-18 12:20:02,685 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Received METADATA response from node -1 for request with header RequestHeader(...): MetadataResponseData(throttleTimeMs=0, brokers=[MetadataResponseBroker(nodeId=1, host='127.0.0.1', port=19092, rack=null)], clusterId='TnDYQaBQRbKyV2KweXWeQQ', controllerId=1, topics=[...], clusterAuthorizedOperations=-2147483648)
```

And then the "real work" follows:
```
2022-10-18 12:20:02,781 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Initialize connection to node 127.0.0.1:19092 (id: 1 rack: null) for sending metadata request
2022-10-18 12:20:02,782 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Initiating connection to node 127.0.0.1:19092 (id: 1 rack: null) using address /127.0.0.1
2022-10-18 12:20:02,787 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Completed connection to node 1. Fetching API versions.2022-10-18 12:20:02,787 [DEBUG] [main] [NetworkClient] [Consumer clientId=consumer-null-1, groupId=null] Initiating API versions fetch from node 1.
```

Now instead of "127.0.0.1" have a (that came from my server's `advertised.listeners` prop) resolveable hostname and you can get it to point at the proxy, and then it should work.

I hope I haven't confused it more than needed (I found it really the easiest to learn/debug to work with a live dev installation to get a feel).

**Comment by adamkotwasinski** [comment]
@DiegoGamaV Hah sorry I confused you - I was pointing at an example implementation of request listener. Then you might get an access to the request coming and modify it.

But! Then the implementation detail is that we are not serializing the deserialized data - it's all passthru (https://github.com/envoyproxy/envoy/blob/main/contrib/kafka/filters/network/source/broker/filter.cc#L97)
So even if we get _pieces_ of request we pass them onwards even before we manage to decode a full request (as we should not be making any assumptions about what's present in received `Buffer::Instance& data`, theoretically we could be invoked multiple times with 1-byte buffers `:(`).

So for really initial version I could set up something like this: receive records, parse them, and serialize them downstream (what should be equivalent to what was received) - that would allow at least initial version of being capable of hacking into this flow.

I could make an example PR (that would then allow hooking) for this late this week / next week. WDYT? Then the work would be "what to put into `advertised.listeners`" (e.g. some config prop).

**Comment by adamkotwasinski** [comment]
@DiegoGamaV I just realized that it might not be as simple as replacing with only one value - metadata requests contain information about _all upstream Kafka brokers_ i.e. {broker 1 = host1, broker 2 = host2, etc.}. If we need it to work we'd need to either:
* keep the current model (envoy per broker) and have the config that's aware of the whole cluster topology (e.g. envoy 1 knows the address of envoy 2 when it receives metadata mentioning broker 2),
* go towards what mesh-filter is doing and maintain our own upstream connections (that's what I'm working on but it's slow).
