### ISSUE TITLE
Background on JWT authn filter skew default

### ISSUE THREAD

**Issue by pauldthomson** [envoyproxy/envoy#23215]
*Description*:
The below commit added a default clock skew to the JWT authn filter, and mentions that a skew buffer is recommended and seems to use 60s as that's what GRPC uses. I'm wondering if there's any more context to this? We have hit some issues relating to tokens traversing envoy and non envoy proxied services due to this. Before removing/changing the setting, I just wanted to check there was no rationale that I'm missing, as my naive take is why would someone care so much that a token with say 15m validity expired in 14m30s cos of clock skew? 

Thanks for any input.

[optional *Relevant Links*:]
https://github.com/envoyproxy/envoy/commit/cd684e76bda80e140ab90573815f1990ec6f2a6f

**Comment by qiwzhang** [comment]
Sorry, not clear on your intention.  Are you proposing to remove the `clock_skew_seconds` config?  

This may cause backward compatible issue.   Someone may be using it.

**Comment by pauldthomson** [comment]
No, sorry. Internally we are considering setting it to 0 (via an `Istio` `EnvoyFilter`), but just trying to understand the motivation for the 60s default before we do.

**Comment by fiadliel** [comment]
I'm just looking at this for a separate issue. The skew is supposed to allow a variance due to different clock-reported times (e.g. no NTP). e.g. your JWT token expires at 12:00, but you call a service whose clock is 1 minute fast (12:01); a skew allows for this JWT token to still be accepted.

The issue (I think) in jwt_authn is that the time check for the JWT token cache is done by jwt_verify_lib, see https://github.com/google/jwt_verify_lib/blob/26c22c0ce1bc607eec8fa5dd26b707378adc7a88/src/jwt.cc#L151

This is a valid check if you are the receiver (consumer) of the JWT token, but not so great if you are the producer (as the cache is, in a sense). It's another example of Postel's Law. The token producer needs to _subtract_ the required skew.
Otherwise, without any clock skew, the jwt_authn cache will provide tokens for a minute after they expire.

**Comment by pauldthomson** [comment]
> your JWT token expires at 12:00, but you call a service whose clock is 1 minute fast (12:01); a skew allows for this JWT token to still be accepted

OK, maybe there's an inherent assumption here that we always want the client to be the first one to notice the token is expired, i.e. we want the client to be able to proactively re-issue a token rather than get a `401` or something back and _then_ refresh its token. In which case adding the +/- 60s buffer makes sense. 

I have see situations where a client either proactively refreshes tokens with a few mins of buffer, or just reacts to the likes of a 401 from the server by refreshing a token, and in those cases whether the token expires in 10m or 10m +/- a minute seems kinda arbitrary.. So I guess the behaviour here is more for the former.
