### ISSUE TITLE
Starting slow_start_window after upstream cluster active health check okay

### ISSUE THREAD

**Issue by jhsbeat** [envoyproxy/envoy#23328]
*Title*: *Starting slow_start_window after upstream cluster active health check okay*

*Pre-Question*
- Is the [host.creationTime()](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L996) value the same with Envoy ready time (i.e., readiness probe succeed on k8s)

*Description*:
> Current slow start window start calculate time factor after host creation time. However, many application should receive small fraction of traffic after the backend cluster application ready especially for JVM applications needs warmup traffic to create usage profile. For this reason, could you please provide an option to start slow start time factor calculation after active health check succeed? Furthermore, in this case, the condition comparing host_create_duration and slow_start_window because the time factor should be always applied. In short, we hope that we can use the slow start mode working as the same way with AWS slow_start attribute of target group.

*Relevant Links*
> Envoy slow start time factor : https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L1007
> AWS slow start mode : https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#slow-start-mode

**Comment by yanavlasov** [comment]
@snowp @zuercher for comments.

**Comment by nezdolik** [comment]
This is duplicate of https://github.com/envoyproxy/envoy/issues/18351

**Comment by nezdolik** [comment]
>Is the [host.creationTime()](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/load_balancer_impl.cc#L996) value the same with Envoy ready time (i.e., readiness probe succeed on k8s)

No, it's not the same. `host.creationTime()` indicates a timestamp for when the host has joined the cluster. 
Host enters slow start upon passing 2 conditions below (when an active health checking is enabled per cluster):
* host create duration (duration since host has joined the cluster) is less than or equal to configured slow start window;
* host has passed an active health check. 
More detailed docs [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start#:~:text=Slow%20start%20mode%20is%20a,traffic%20to%20new%20upstream%20endpoints.).

This is a known issue that slow start mode is skipped if host does not reach healthy state within configured slow start window. Instead, slow start mode should start when host transitions to healthy state.

**Comment by nezdolik** [comment]
Fixed via  #18351
