### ISSUE TITLE
Add support - route to load balancer subsets based on header/url param

### ISSUE THREAD

**Issue by davidshepard989** [envoyproxy/envoy#2334]
It would be great if you could route to  [load balancer subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing#load-balancer-subsets) based on a header value or url parameter.

Similar to the way you could route based on `cluster_header` in v1 - https://www.envoyproxy.io/docs/envoy/latest/api-v1/route_config/route.html?highlight=cluster_header

**Comment by mattklein123** [comment]
Pretty sure this is already supported? @zuercher ?

**Comment by ufodone** [comment]
I'm also in need of this same capability.  I've hacked up a version of Envoy to do this that I did as part of a proof of concept integrating Envoy with my app server but am now interested in putting together a proper version.

My hacked up version just looks for a hardcoded header name and adds it as a key/value pair to a new MetaDataMatchCriteria instance.  

There are a couple of things I'd love some input on:

1. Syntactically, what would the configuration and headers look like?  The "cluster_header" feature is simpler in the sense that the header value is just a single piece of information where as with the metadata, it will be a set of key/value pairs for matching.  Should this be encoded as a single header value?  And if so, what would it look like?  Something like "stage=canary,v=1.2-pre" ?

2. How should this interact with the existing metadata specified in the routing configuration?  My first though is that it should be merged with the routing config's metadata take precedence over what's specified in the headers.  This would provide a little more security/control on the Envoy side to prevent clients using metadata keys which are meant only for internal routing use (not to be exposed to calling clients).

**Comment by ufodone** [comment]
It sounds like we have similar use cases but because the extraction process I need on the inbound http headers can't be handled by regex, I've instead used a lua filter to grab the header, parse out the info I need and then add a new header before passing the request along the filter chain. I'm guessing that could be an option for you as well if there was a desire to keep the metadata header processing simpler.

**Comment by zuercher** [comment]
My apologies for not seeing this sooner.

The non-regex version of this is [supported](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing#load-balancer-subsets).

In our XDS implementation, we're able to compute the possible combinations of the metadata values and produce static metadata values for each route. E.g., we'd match a non-regex header of `X-Do-Something: v=1.5` in a route that configures the load balancer metadata to be v=1.5.

It might be simpler to add a field to `HeaderMatcher` and `QueryParamMatcher` that provides for the transformation of a header/query param into metadata. Otherwise I think some use cases end up applying regular expressions to headers twice (and worse having them configured in two places). I think in your example the dynamic metadata matches end up as separate header matchers in separate routes.

Something like:

```
match:
  headers:
    - name: "X-DoSomething"
      value: "version=([0-9a-z-]*)"
      regex: true
      metadata_match:
        filter_metadata:
          "envoy.lb":
            "v": "$1"
```

**Comment by ufodone** [comment]
So to use the existing functionality, I'd need to define a route entry for each unique header value?  

In my particular case I'm effectively trying to replace client-side load balancing/routing for the app server by placing Envoy in the middle which means that I'd need a route entry for each node in the cluster.  I'd be concerned that I'd likely need hundreds of routing entries to accomplish this.  Use of RDS+EDS would keep the management aspects under control but could there be a potential performance concern?  I assume route matching is done via linearly processing all the routing entries so if I had hundreds of them...

**Comment by zuercher** [comment]
For the existing functionality, yes.

Route lookup is a linear search. So for a sufficient number of routes it would become expensive.

It sounds like your application is routing requests to individual nodes. Can you provide some more details so I can better understand what you're trying to accomplish?

**Comment by ufodone** [comment]
> It sounds like your application is routing requests to individual nodes.
Yes, exactly.  The short answer is that I'm trying to put a facade in front of an older service to make it look more "normal" and play nicely in a larger ecosystem (and along the way gain a bunch of the benefits Envoy brings out of the box).  

For a variety of historical reasons, I've got a stateful service which requires requests for a given session key to always be handled by the node in the cluster which owns the session.  The routing of requests are currently handled in concert with an associated client SDK.  I'm trying to move all this routing logic/complexity off the client and handle it internal to the service itself.  

New requests that come into the service that don't have a session key yet will just be load balanced to any of the nodes (I'm using the round-robin load balancer).  Once a session key is obtained, all subsequent requests will get routed back to the node which owns the session.  The extra wrinkle here is that there are some circumstances under which a session may be migrated to a different node (typically caused by a maintenance operation).  

My proof-of-concept has an Envoy sidecar which gets its EDS info from the cluster itself.  Included in the EDS info is an instance_id metadata key/value pair.  I then have a lua filter which looks for the session key in an inbound request, calculates the instance_id that the session belongs to and adds an instance_id header to the upstream request.  This is where I've currently hacked up Envoy to look for this instance_id header and use it for subset load balancing. (Which is turns out was unnecessary for a proof-of-concept based on the info you provided.)  

Ultimately I'm trying to come up with a solution that works with stock Envoy version so have been trying to figure out a way to handle this using generic building blocks in Envoy rather than, for example, my own custom load balancer module which wouldn't likely be useful to anyone but me.

**Comment by zuercher** [comment]
Ok. Adding the regex-capture-group to metadata match functionality seems reasonable to me (from the standpoint of reducing large numbers of routes that map header values to metadata matches).

Just for completeness, have you looked at the ring-hash load balancer? You should be able to get stable routing to hosts that way.

**Comment by ufodone** [comment]
Yes, I've looked at the ring-hash load balancer but it won't fit the bill because sessions can migrate between nodes (eg. during scale up/down operations) and requests absolutely need to end up (eventually) on the node that owns the session.  

Regarding your suggestion to add a field to HeaderMatcher: currently the headers specified there need to match in order for the route to be selected.  Are you thinking that would still hold true if a metadata_match field was specified?  The use case I'm thinking of is that for initial requests to my service where a session key doesn't exist yet I just want to use the default load balancing behaviour as specified in the subset config.  In that case I guess I'd just have a second route which routes to the same cluster but doesn't require the header?

**Comment by JonathanO** [comment]
> Regarding your suggestion to add a field to HeaderMatcher: currently the headers specified there need to match in order for the route to be selected.

Yeah, that's why I suggested adding a new property to route rather than adding it to the existing match->headers HeaderMatcher. My thought was that if we require these to match then the number of routes you'd need to match different combinations of optional meta values would be annoying. The alternative of making some HeaderMatchers in match->headers optional seems slightly messy to me, but would work just as well.

**Comment by ramaraochavali** [comment]
@zuercher Thanks for the detailed explanation on this. Looks like load balancer subsets is a very powerful feature to control LB behaviour for use cases like canarying etc. On the similar lines, is it possible today if we specify `node` to which the request should go via some http header like `envoy.route.host` and LB just sends that particular request to that host? This is slightly different from the above implementation where there is no `Metadata` associated/provided in the `LbEndpoint` message - only the request header has the host details. if it is not available, do you think it is a valuable use case to build?

**Comment by mattklein123** [comment]
@zuercher I just assigned this over to you for consolidating this conversation into a final feature request. From a quick skim, new functionality to set metadata based on header regex captures sounds interesting (though a little scary from a security perspective, we would have to have a big warning on this feature).

**Comment by zefyrr** [comment]
@ufodone: The route match is still linear right? Was wondering if you had some perf numbers to share.

**Comment by ufodone** [comment]
Well, yes, technically the route match is still linear but in my case, I only have a single route so not a problem!

My proof-of-concept is using the metadata matcher to drive the LB subset selection - and the metadata matcher builds all the metadata into a tree so it's effectively doing map lookups to do the node selection (I only have a single metadata key I filter on).  I did a quick-and-dirty modification to Envoy to pull my needed info from a fixed header name and stick it in the metadata.

I haven't done any perf analysis yet on my prototype so nothing to share.  My guess is that it's going to be the processing I do in the lua filter which will have the biggest impact on performance.

**Comment by zuercher** [comment]
@ramaraochavali the only way to individually address upstream hosts today is to assign metadata for each one with unique identifier and then generate a route for each unique identifier that matches on some header and specifies the correct metadata for subset load balancing. Implementing the feature under discussion here would make it possible to have a single route.

**Comment by zuercher** [comment]
Opened #2436 as a feature request for what was discussed here.

**Comment by zuercher** [comment]
Closing this question. Further discussion (if any) can happen in #2436.
