### ISSUE TITLE
A peculiar fall back requirement in envoy

### ISSUE THREAD

**Issue by dahalmanoj** [envoyproxy/envoy#23386]
Hi,

I have two services A and B. A is a **https** service and listens on port#8445 with end point /dataservice1/A.
B is a **http** service and listens on port#9446 with end point  /dataservice2/B. Both A & B exist in the same host.
Now my requirement is if A live, go to A, else go to B. If A back to live, switch back to A.

How can I configure this in envoy so that above requirement works?

Thanks,

Manoj

**Comment by pxpnetworks** [comment]
Hi,

Because of the different paths I think I would do it with [Aggregate Cluster](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster.html?highlight=aggregate%20cluster) and [Outlier Detection](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier.html?highlight=outlier%20detection) or Healthcheck on the aggregated clusters. 
But probably there is a better solution?


BR,
Stoyan
