### ISSUE TITLE
path rewrite based on endpoint metadata

### ISSUE THREAD

**Issue by masquee** [envoyproxy/envoy#23417]
*Title*: *path rewrite based on endpoint metadata*

*Description*:
> I have an upstream cluster with endpoints with different path prefixes. Does envoy support path rewrite based on endpoint metadata?

> As far as I know, rewrite can be done in route action. Is there any other configuration or extension that supports rewrite based on endpoint metadata?

**Comment by RyanTheOptimist** [comment]
cc: @zuercher

**Comment by zuercher** [comment]
I don't believe there's anything available to support this at the moment.

This would be tricky to do in an HTTP filter, because HTTP filters are applied before an upstream host is selected. Thus the filter has no mechanism by which it can access the endpoint's metadata. Further, any filter can cause Envoy to recompute the selected route (e.g. if the filter has modified headers). This could potentially cause a different route to be selected, with a different target cluster and endpoints. That seems like it would be a problem for your use case.

Off the top of my head, I expect you'd want an upstream HTTP filter that could modify the request once forwarding began. At present I believe there's only support for upstream network filters: you'd have to handle the HTTP part yourself and that's a pretty big effort.
