### ISSUE TITLE
Should we include the Envoy Node info in `RateLimitQuotaUsageReports`

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#23585]
Question from @bbassingthwaite : In our use case, the RQLS management server needs to know the Envoy node information in order to understand where the usage report is coming from. Should the first RateLimitQuotaUsageReports that Envoy sends contain the Node similar to other xDS APIs?

**Comment by tyxia** [comment]
Hi @bbassingthwaite, for this question, first let me describe our design a bit.

The relationship of different objects here is : 
- A single report could include quota usage for multiple Buckets (i.e., 1 `RateLimitQuotaUsageReports` <-> many `BucketQuotaUsage`) 
- A single `BucketQuotaUsage` includes the usage info for a group of clients (could be single client per configuration) as the rate limiting reports and assignment is at granularity of each bucket and we group clients into each bucket. This is because you may want your high priority clients (e.g., production clients) to have more of your capacity then lower priority clients (e.g., development) and let them share the same rate limiting decision.
- Also, the way requests/clients group into each bucket can be defined in various ways. e.g., client IP, request header, URL path, etc.

So, the `RateLimitQuotaUsageReports` here is not specified at the granularity of Envoy [Node](https://github.com/envoyproxy/envoy/blob/daa9840d0be7aa5e730a525c979d990bb9d03a8b/api/envoy/config/core/v3/base.proto#L142). And I want to know why the Envoy Node info is needed in your case first.

**Comment by bbassingthwaite** [comment]
Hi @tyxia thanks for the response. The RQLS management server will receive reports from many Envoy nodes across various regions, clusters and tenants. In our use case, the Envoy Node contains all of this information and allows us to distinguish the tenant/region/cluster and apply the appropriate rate limiting policies. 

We could encode this information in the bucket but it's quite redundant and would need to live on every bucket. If `RateLimitQuotaUsageReports` include the Node on the first request, we could simply store it and know that every subsequent report that came in would be for that tenant/region/cluster. It would also reduce the size of the RateLimitQuotaUsageReports since we can send that information once and not need to include it on every report.

This behaviour is quite common across the xDS APIs, such as ADS, ALS, Metrics Service, Trace Service, etc...

**Comment by tyxia** [comment]
@bbassingthwaite  Thanks for sharing the information and use case from your side!
For our(i.e., Google) cases, we currently don't need this information as I describe above because we are operating on quota bucket basis and don't really care about which Envoy Node. We could use it later (e.g., logging).

But I think your proposal is for the legit use case. I will send a PR for this later.

**Comment by bbassingthwaite** [comment]
Thanks @tyxia !
