### ISSUE TITLE
Support for Month, Year rate limit units for business subscriptions

### ISSUE THREAD

**Issue by renuka-fernando** [envoyproxy/envoy#23844]
*Title*: *Support for Month, Year rate limit units for business subscriptions*

*Description*:
It is possible to have business cases with per Month, per Year rate limits (for global rate limiting). These rate limit policies are not to protect upstream from attacks like DDoS, but to have some business advantages like a monthly subscription or yearly subscription for a customer to use the upstream.

Following are some sample subscriptions for an upstream.
- 10k requests per Month
- 1M requests per Year

The existing implementation only supports the following units. For a business subscription, it is worth having month and year as units.

- SECOND
- MINUTE
- HOUR
- DAY

[optional *Relevant Links*:]
https://github.com/envoyproxy/data-plane-api/blob/5ba669d8a54e7c4bbbba3a6445ebd1a09d9e9dc0/envoy/service/ratelimit/v3/rls.proto#L80-L95

**Comment by renuka-fernando** [comment]
@tyxia

**Comment by tyxia** [comment]
@renuka-fernando  Let's continue our offline discussion here so that anyone has opinion about this request can chime in and comment.

For us, `month` and `year` unit are too coarse-grained unit and we want to control rate liming more tightly on a more frequent basis.

With that said, I am open to add this in the API for your business need. But out of curiosity: 1) It seems that it will be huge number to report for `month` and `year` unless the traffic to your upstream is small. and 2) you will have your Envoy instance  to run for month or year with same configuration?

**Comment by renuka-fernando** [comment]
@tyxia thank you for your comment.

> 1) It seems that it will be a huge number to report for `month` and `year` unless the traffic to your upstream is small

Yes, the traffic to the upstream will be small, and planning to control it with another rate limit policy applied together with this monthly/yearly subscription.

For example:
Route: /weather/v1/location - (10K Per Month + 20 Per Min)

So downstream clients can't use the whole 10K within a short period of time. it is controlled with "20 Per Min", the second rate limit policy (as a spike arrest rate limit policy).

> 2) you will have your Envoy instance run for a month or year with the same configuration?

Yes, the Route exists for months and years. But maybe have some changes like adding new Routes. Deprecate this Route and later delete it. Update the subscription from 10K Per Month to 20K Per Month.

**Comment by renuka-fernando** [comment]
Hi @tyxia,
Thank you very much for working on this.

**Comment by tyxia** [comment]
> Hi @tyxia, Thank you very much for working on this.

No problem. You can close this issue now. If you have other problems or needs, just let me know
