### ISSUE TITLE
restore coverage limits

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#24353]
Lowered in 
https://github.com/envoyproxy/envoy/pull/24320 to fix main

**Comment by tyxia** [comment]
Hi @alyssawilk , I have sent out a PR for your review.

Looking at the CI result in this PR https://github.com/envoyproxy/envoy/pull/24351, especially the coverage report [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=122519&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=e00c5a13-c6dc-5e9a-6104-69976170e881), looks like the problem is `Code coverage for source/extensions/clusters/common is lower than limit of 96.6 (90.3)` rather than main coverage (`Overall coverage rate:
  lines......: 96.1% (121370 of 126334 lines)
  functions..: 76.1% (25767 of 33838 functions)
Code coverage 96.1 is good and higher than limit of 96.0`)

**Comment by alyssawilk** [comment]
That has a green coverage result with the lower limits so to be clear while it's a step in the right direction it doesn't resolve the bug.

**Comment by tyxia** [comment]
@alyssawilk  I think this issue can now be closed after #24355.   Could you help me to close it ?(Looks like I don't see a button for me to close it)
Thanks!

**Comment by alyssawilk** [comment]
Sorry this was incorrectly closed: we fixed the explicit breakage but the filter which caused the breakage was still added without sufficient testing and that has not yet been fixed.  @tyxia can you please make sure it's addressed?
"source/extensions/filters/http/rate_limit_quota:94" # TODO(tyxia) WIP. Improve coverage as development continues

**Comment by tyxia** [comment]
Sure. actually rate_limit_quota's current coverage is actually [94.8](https://storage.googleapis.com/envoy-pr/b46a61c/coverage/source/extensions/filters/http/rate_limit_quota/index.html) slightly higher than 94 listed there.

I thought the goal (why it was closed) was to bring the overall coverage back to 961, which is now 96.3
Is the goal to bring rate_limit_quota itself to 96.1 ?

**Comment by alyssawilk** [comment]
the goal is to remove the exception by bringing coverage up to the bar of 96.6.

**Comment by tyxia** [comment]
Got it. Thanks!

**Comment by alyssawilk** [comment]
Marking as no stalebot, and ccing @krajshiva

**Comment by krajshiva** [comment]
Thanks! will prioritize this cleanup.

**Comment by tyxia** [comment]
RLQ is now fully covered at 97.7% except for the death code. So this issue which is for restoring RLQS coverage limits has been closed.
