### ISSUE TITLE
remove swift DirectResponse APIs

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#24428]

**Comment by alyssawilk** [comment]
https://github.com/envoyproxy/envoy/pull/25582 made the test server code usable for TCP upstreams, so I think all we need to do is port the direct response tests to use real upstreams and we can close this off.

**Comment by andy-fong** [comment]
@alyssawilk I stumbled upon this workaround that mentioned this issue: https://github.com/envoyproxy/envoy/blob/cc4a75482810de4b84c301d13deb551bd3147339/mobile/library/common/http/header_utility.cc#L16

With the change in https://github.com/envoyproxy/envoy/pull/34490, this workaround would no longer work because the value would be `direct_response{}` instead of just `direct_response`, right?

I am not sure what this workaround is for and I don't need it, just happen to saw it.

**Comment by alyssawilk** [comment]
fixed by https://github.com/envoyproxy/envoy/commit/d78e8138feb499147730a1c39da8e479a796a621 :-)
