### ISSUE TITLE
refactor of data-plane-api caused breaking gRPC changes

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2466]
When we started to rollout https://github.com/envoyproxy/envoy/commit/d6b630abcb3f99d604b4f87b22d4bce3c6538e4b at Lyft, we noticed:

```
2018-01-26T20:34:01.09881 [2018-01-26 20:34:01.098][30244][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:66] gRPC update for type.googleapis.com/envoy.api.v2.cluster.Cluster failed
2018-01-26T20:34:01.09881 [2018-01-26 20:34:01.098][30244][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:193] gRPC config stream closed: 12, unknown service envoy.service.discovery.v2.RouteDiscoveryService
```

We now realize there are two breaking changes here:
1) gRPC endpoints have changed.
2) Anything within a proto `Any` will refer to an unknown message by name.

These types of breaking changes are not allowed. We will need to figure out some way of having stubs or duplication and then removing the old endpoints/messages. This also needs to be called out clearly in DEPRECATED.md.

**Comment by kyessenov** [comment]
For (2):

There's only one instance google.protobuf.Any in data-plane-api, and that is the xDS service discovery. I imagine there are ways to go around this:
1. keep the old proto definitions around; we may want to unlink them from the docs
2. provide a proto translator from one type to another type via JSON/YAML inside Envoy
3. eventually, migrate the management server to use the new service definitions. That needs to be done for the envoymanager and go-control-plane. This should be a simple change, since the protos are structured identically for now.

**Comment by kyessenov** [comment]
cc @junr03 on ideas how to move envoymanager forward.

**Comment by kyessenov** [comment]
@htuch I'm happy to move cluster.Cluster, route.Route, listener.Listener, and ClusterLoadAssignment back to where they were under `api.v2`. That is a simple way to solve (2). WDYT?

**Comment by htuch** [comment]
I think so. We can still refactor the leaves of these into the subpackages, but that might look weird. WFYT?

**Comment by kyessenov** [comment]
Yesh, we only need top-level definitions to be in `api.v2` and move everything under it into subpackages.

**Comment by wora** [comment]
Sorry for the trouble. Changing proto packages is a breaking change, since it affects both gRPC URLs and the `Any.type_url`. I don't think there is any native support for package renaming in gRPC. To support this renaming, we have to build custom layer to translate the URLs.

Given Lyft is using Envoy in production, I don't think they want to take the risk. I believe Google also has some services using the Envoy APIs.

If the Envoy APIs are only used for wire formats, not for configs, we can workaround the problem by having new servers talking to new servers, and old servers talking to old servers. If the Envoy APIs and configs are stored in source control, I think we probably should give up on the renaming.

For Google APIs, we solve the problem by not allowing break changes at all. With a stable API Design Guide, the need for breaking change would be significantly less, so we don't need to deal with the problem in the future. If we don't have a way to roll out the renaming, let's just punt it.

**Comment by htuch** [comment]
I would be open to a compromise, where we keep the service defs and enough of the core messages where they are to make backwards compat work. I'm a little concerned the organization might appear "unnatural", since this constraint is forcing us here, but let's see what hte PR looks like.

**Comment by mattklein123** [comment]
Agreed on the compromise if @kyessenov is able to mock it up. I think there is real value in moving a bunch of stuff around. The lack of namespacing in what we had before had never made me thrilled.

**Comment by wora** [comment]
We need to know what code is in production and how flexible you can deploy the breaking changes. We can come up a safer plan based on the information.

**Comment by mattklein123** [comment]
IMO we should do the following:
1) Move the service definitions back to where they were before.
2) Break the Any which is used on ADS API as I'm pretty sure no one is using that in production.

**Comment by lizan** [comment]
For `google.protobuf.Any`, since the only usage is ADS, it is possible to have a type_url mapping from old one to new one, and update the type_url before parsing into actual resource when Envoy consumes them.

**Comment by kyessenov** [comment]
OK, I'll start a PR to move EDS, CDS, RDS, LDS service definitions to `core.v2` in both data-plane-api and envoy. If that doesn't work, I'll need to shuffle more protos again.

**Comment by mattklein123** [comment]
@kyessenov what do you mean by `core.v2`? do you mean `api.v2`? It needs to go back to what it was before.

**Comment by kyessenov** [comment]
Yeah, sorry, I made a typo. It goes back to `envoy.api.v2`

**Comment by kyessenov** [comment]
Proposed fix https://github.com/envoyproxy/data-plane-api/pull/438

**Comment by mattklein123** [comment]
Fixed
