### ISSUE TITLE
Redirect: upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by bernardogeneroso** [envoyproxy/envoy#24812]
I have a microservice running NET7 working, open in "http://127.0.0.1:5010" and "http://192.168.1.99:5011".

Error "upstream connect error or disconnect/reset before headers. reset reason: connection failure)", when opening in browser this url "http://127.0.0.1:10000/applicant/WeatherForecast".
I'm running "envoy -c envoy-dev.yaml" command in ubuntu wsl in Windows.
It's work for me when using docker with some minor differences in configuration.

Configuration:
![Screenshot_3](https://user-images.githubusercontent.com/58465456/211159060-d2f4a525-0423-49e0-835e-bb0ce08df56d.png)
![Screenshot_4](https://user-images.githubusercontent.com/58465456/211159059-4f96d290-c7bf-4c83-9d8c-149825befe42.png)

**Comment by htuch** [comment]
Honestly hard to answer this kind of question as it probably relates to your local networking configuration. Some suggestions:
* Try validate that from within the same environment (container or otherwise) that Envoy is running, you can reach the upstream with curl, i.e. `0.0.0.0:5011`.
* Include trace level logs or stats (with PII etc. removed) in the issue. I'd suggest the above first.

CC @envoyproxy/windows-dev in case there is some Windows angle eventually.
