### ISSUE TITLE
Rate limit on retry (x-envoy-attempt-count or anything else)

### ISSUE THREAD

**Issue by yfouquet** [envoyproxy/envoy#24937]
### Context
There are currently three main controls around retries:
- The first one is define the retry policy at the route level (see [config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-retrypolicy)). We there set the amount of retries per request, the back-off delay, the response code to retry on, ...
- The second mechanism is to define a limit of concurrent requests in the circuit breaker, at the cluster level (see [config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers))
- The last mechanism is to use rate limit to limit the entire traffic (see [config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit))

The challenge with the 3 mechanism above is that they don't protect from retry storm when the amount of customers is large. Let's consider that one service is called by 10,000 servers. All these servers send limited around of traffic - let's say 10req/sec in average. Finally, the configuration allows for 2 retries, the timeout for each retry is 40ms and the total is 100ms.
If the upstream service suddenly becomes unavailable, a retry storm will suddenly start:
- the circuit breaker will allow at least 1 retry for each server i.e. 10,000 concurrent retries. Because of the low timeout, this means many tens of thousands of retries per second.
- the rate limiter will not help either - we would usually put the client-side rate limit to 50req/sec and allowing those retries. We can rate limit based on many things in the request, source and upstream cluster - but we cannot rate limit attempt count only or the fact that it is a retry request. Rate limiting header is good, but `x-booking-attempt-count` is adding by envoy and we cannot rate limit based on that.

### Needs
We would need to add something in [RateLimit.Action](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action) to rate limit retries only

**Comment by eightnoteight** [comment]
We came across a similar problem at zomato; the issue is retry budget is based on concurrency rather than requests; although concurrency is an ideal attribute to use as the latency changes in real-time, it also makes the retry budget pointless in most scenarios where per container, upstream concurrency is very low that even 20% might be lowered to 0 retries. As a temporary solution, we implemented it at the application level to solve this but still solving this at the envoy level would be great. At the application level, we observe throughput over a decent-sized window, i.e. 10 seconds. Based on this, we decide the retry quota for the next window based on the budget. For example, if the retry budget is 20% and in the first 10-second window, the container initiated 100 requests (10 req/sec), then for the next 10-second window, the interceptor will allow at max 20 retries. Because the implementation uses previously observed throughput, even if latency changes and concurrency is a bit different, the number of retries will still be conservative.

This implementation could be improved, though, rather than tumbling windows using a sliding window algorithm and applying jitter in how we pick the window start time so that sudden degradation won’t trigger a sudden retry storm in a small window.

Something like this can be implemented in the envoy as a separate filter.
