### ISSUE TITLE
ZK filter tries to parse metadata for every piece of data fetched from the buffer

### ISSUE THREAD

**Issue by Winbobob** [envoyproxy/envoy#25024]
*Title*: ZK filter tries to parse metadata for every piece of data fetched from the buffer

*Description*:
- When enabling the ZK filter, we noticed that sometimes the buffer did not include all data of a request or a response. The filter tried to parse the metadata (len, xid, etc) from all later parts of the data fetched from the buffer the same way as the first part. Since all later parts of data does not include the metadata, only pure raw data, the decoder error will be recorded, specifically
  - The first part of data will be parsed successfully and the filter will erase the xid record from an internal map ([here](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/filters/network/zookeeper_proxy/decoder.cc#L194)).
  - For the later parts, the parsed len and xid will be incorrect and the code cannot find the xid entry from the internal map and raise the `xid not found` exception.
- Ideally, the ZK filter could simply ignore later parts of data since it just skips them.
- This is the reverse case of the one mentioned in the code: [one buffer may contain multiple messages](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/filters/network/zookeeper_proxy/decoder.cc#L475-L477).

*Repro steps*:
> Enable the ZK filter and try to get data of a znode (~70KiB).

*Config*:
> Much like the official example [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter).

**Comment by Winbobob** [comment]
cc @rgs1

**Comment by rgs1** [comment]
Ok so buffering is probably not an option here. I think we can rework the decoder to handle the following states:

* METADATA_INIT
* METADATA_DONE
* DATA_INIT
* DATA_DONE

We have the message size and we know when we are done with the metadata, so it should be easy to keep track of these. Ping me on slack if you want to chat a bit more about this.

**Comment by rgs1** [comment]
Since we have the message length at the start of each message:

https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/filters/network/zookeeper_proxy/decoder.cc#L50

I'd say we should probably just peek at the length in `Decoder::OnData()` and then return `StopAndBuffer` to `ZooKeeperFilter::onData()` (the caller) until we have the full message. It won't be a huge perf hit and since messages in ZK are in order anyway it doesn't matter much. Otherwise, extending the decoder to deal with partial messages would make things much more complex for very little practical gains.

cc: @fishcakez

**Comment by Winbobob** [comment]
Related to issue #25482
