### ISSUE TITLE
What's the difference between filter state and dynamic metadata?

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25130]
This question might be trivial for some, but I am wondering what is practically the different between filter state and dynamic metadata? They are both seem to be accessible from the connection object and can be accessed by filters and upstream clusters implementations.

Will appreciate an explanation on this, thanks.

**Comment by kyessenov** [comment]
Both serve the same purpose - data exchange across extensions. Filter state is more advanced and preferred (it's faster, nested across streams, has read/write controls). Metadata has better UX (since it's proto) and was integrated deeper (since it was added earlier).

At some point, they were supposed to be reconciled, but it's hard (see https://github.com/envoyproxy/envoy/issues/4929).

**Comment by ohadvano** [comment]
Thanks, @kyessenov

**Comment by ohadvano** [comment]
@kyessenov is there any other issue that discuss the performance impact of each alternative?

**Comment by kyessenov** [comment]
Not really. Protos are not trivially destructible so they're costlier than simple structs. Filter state can also store a complex state (like TLS session).

**Comment by ohadvano** [comment]
Thanks again
