### ISSUE TITLE
Injecting fake content-length on a POST request without body is waiting till stream to timeout in ext_proc filter

### ISSUE THREAD

**Issue by shibin-aot** [envoyproxy/envoy#25413]
For testing a scenario i had injected content-length header with the request > 0, and there was no actual header.
The behavior is different when RequestBody processing mode is set to BUFFERED.
The actual request wait indefinitely till the stream timeout.

When the processing mode is STREAMED.
The request fetches the response, but the ext_proc filter call Recv and indefinitely wait for a response.

It gets stuck literally if we inject a content length > 0 header and send without a body

**Comment by wbpcode** [comment]
I need some time to check the source code.

**Comment by shibin-aot** [comment]
@wbpcode Ok

**Comment by wbpcode** [comment]
After a quick check, I think this behavior is as expected. If the request has a non-zero content-length but have no actual body, then the filter chain can never set the `end_stream` flag and the filter that need handle body will wait for body indefinitely.

And If the `STREAMED` mode is used, after the external response to request headers is received, the headers processing will continue. However, it's still a wrong because the ext_proc is still waiting for body.

**Comment by shibin-aot** [comment]
Yeah got it.
We are expecting such fake content-length on our request, so keeping the thread running for 5+ minutes can cause memory issues.
Do you think adding the below line could solve our scenario
    - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stream_idle_timeout: 10s

**Comment by wbpcode** [comment]
Yeah, I think it would be helpful.

**Comment by shibin-aot** [comment]
Hmm, it would be a good idea if we can set the behavior same as without filter. Same strategy without filter should work.
