### ISSUE TITLE
ExtProc/ExtAuthz: support header mutation after data processing for streaming requests

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#25410]
*Description*:
By https://github.com/envoyproxy/envoy/pull/15935, header mutation after data processing is supported for unary requests and we need the support on the streaming case. In our case, we want to **inject some header from the first gRPC streaming message**. 

**For ExtProc filter**
Currently, you can configure `BUFFERED`/`BUFFERED_PARTIAL` mode for streaming requests, just treating it like unary requests by buffering all the messages until `buffer_limit`(256M by default). Apparently it copies too much data,  introducing 1) CPU overhead 2) memory overhead 3) latency by waiting for a data of `buffer_limit` size 4) maybe not work if the first message is larger than the `buffer_limit`. 

Ideally for our case in streaming, the extProc filter can 
- `stopIteration` on `decodeHeaders` after sending `HeaderProcessingRequest`
- `stopIterationAndBuffer` on `decodeData` until seeing the first gRPC  delimiter and only send the buffered data before that to the extProc server(I am afraid that logic isn't generic enough to directly add into extProc filter)
- receive the `DataProcessingResponse`, mutate headers and `continueProcessing`

**For ExtAuthz filter**
The ExtProc filter almost support the same functionality of [forwarding the request body](https://github.com/envoyproxy/envoy/blob/d9d432c9f5d697850e0927939b448aa95d3f4afd/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L69)(but with static size) and [injecting request headers](https://github.com/envoyproxy/envoy/blob/d9d432c9f5d697850e0927939b448aa95d3f4afd/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L293)

**Comment by TAOXUY** [comment]
@gbrail @ggreenway

**Comment by wbpcode** [comment]
cc @snowp

**Comment by gbrail** [comment]
Hmmm -- this is interesting but I'm not sure how to do this generically. BUFFERED_PARTIAL today kind of does what you want -- it waits until it has enough data to fill the buffer, and holds up header processing until that first chunk is processed -- but it won't work with a gRPC stream because it'll wait until it has "enough" data.

I could see changing ext_proc to hold the headers until the first chunk of the body has been processed by the processor. The problem is that I don't know how to generically know whether the first chunk contains a complete gRPC message. Certainly in the current interface Envoy just works on a stream of bytes and those chunks could be grown or shrunk by a previous filter or something on the network.

I think you're asking for the chunking implementation in Envoy or ext_proc to take into consideration the HTTP/2 message framing. I only know enough about HTTP/2 to be dangerous, but is that something that someone could imagine doing?

**Comment by gbrail** [comment]
One idea might be for someone to write a "grpcFraming" filter that would make sure that the (en|de)codeData callbacks would only be called with a single, complete gRPC message. Then ext_proc could hold the hedesr after the first chunk.

Frameworks in other languages use this technique to build up filter chains.

**Comment by TAOXUY** [comment]
Thanks Greg!

Yes, the problem is how the filter intellectually know the gRPC message framing?Could you please clarify the codepath of this gRPCFraming filter and the extProc filter? How gRPCFraming filter notify the extProc filter when the first gRPC message is there?

**Comment by TAOXUY** [comment]
Hi @gbrail,

Not sure if I understand your idea correctly. Are you saying
- in front of the extProc filter we have a gRPCFraming filter. During `deocdeData` time, it will return `StopIterationAndNoBuffer` 
and keep buffering the data. When it sees the end of the first gRPC message, it calls `Continue` and inject the data back to the filter chain. 
-  The extProc filter's `STREAMED` mode will be changed to **support header buffering and header mutation for the first dataProcessing**. In this case, the filter buffers the headers first and then receives the first gRPC message in the first `decodeData` call. It will forward the data of the first gRPR message to the extProc server and the server will respond the header mutations. The filter finishes the header mutation, propagates headers and data.

**Comment by shuoyang2016** [comment]
Are we allowed to make ext_proc server stateful and buffer data?
