### ISSUE TITLE
subset lb fallback policy not invoked when hosts are unhealthy?

### ISSUE THREAD

**Issue by pianiststickman** [envoyproxy/envoy#25654]
Suppose that the first matching subset in a subset LB has all its hosts turn unhealthy, or the subset's LB otherwise returns nullptr from `chooseHost()`. The subset LB will return the nullptr anyway from `chooseHost()`:

```c++
    bool host_chosen;
    HostConstSharedPtr host = tryChooseHostFromContext(context, host_chosen);
    if (host_chosen) {
      // Subset lookup succeeded, return this result even if it's nullptr.
      return host;
    }
```
https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/subset_lb.cc#L254

My question is: why? I would have been inclined to classify this as a bug (it's a _fallback_ policy; why aren't we falling back given the subset can't produce a host?), except we seem to have gone through the trouble of doing it this way quite deliberately.

(I am trying to match a host by metadata and fall back to any other host if that host is unhealthy)

cc @zuercher @htuch @snowp who might have opinions if not answers :)

**Comment by wbpcode** [comment]
>     // The behavior used when no endpoint subset matches the selected route's metadata.

It's by design (but I also don't know why.) If the endpint subset is choosen, then no any fallback will be triggered even there is no healthy ep in the choosen subset.
Typically, the fallback is designed for subset selecting, not for host selecting.

**Comment by pianiststickman** [comment]
I guess an additional question would be: can we change this?

It doesn't make a ton of sense to me that a fallback doesn't, well, fall back.

**Comment by htuch** [comment]
@zuercher could you advise here? Thanks.

**Comment by zuercher** [comment]
The original design was to limit load balancing to a subset of hosts, as if they were the entirety of the cluster. When a given subset exists (has any hosts) the subset lb defers to the underlying load balancer implementation, which might result in no host being chosen once endpoint health is taken into consideration. The fallback mechanism applies when a given subset doesn't exist at all.

A more concrete example: In my experience, one reason to have a single-host subset is to allow developers to target a client at a specific test host. The use case is to test the specific code running on that upstream. As the developer I'd want to get errors if that host become unhealthy rather than have request forwarded to another upstream running different code.

I'm willing to concede there are probably other use cases where it makes sense to switch to a fallback subset when a subset's load balancer cannot select a host. It should be possible to add a configuration option to enable that.
