### ISSUE TITLE
Decompressor filter silently passes empty request body when encoding doesn't match Content-Encoding

### ISSUE THREAD

**Issue by joshuaspence** [envoyproxy/envoy#25869]
*Title*: Decompressor filter silently passes empty request body when request body encoding doesn't match the `Content-Encoding` header.

*Description*:
If you pass a request through Envoy with a request body encoding (e.g. gzipped or uncompressed) that is inconsistent with the `Content-Encoding` request header, Envoy will send an empty request to the upstream cluster. Decompression errors are logged at the `trace` level and `envoy_http_decompressor_upload_gzip_decompressor_library_zlib_data_error` metrics are emitted (for gzip at least), but there is no way for the upstream to know that the request body has been discarded.

*Repro steps*:
Within the `gzip` sandbox example, run the following commands:

```
docker compose up

dd if=/dev/zero of=empty.bin bs=1024 count=10240
curl -si -H "Content-Encoding: gzip" localhost:10000/upload --data-binary "@zero.bin"
```

*Config and Logs*:
[debug.zip](https://github.com/envoyproxy/envoy/files/10867448/debug.zip)

**Comment by joshuaspence** [comment]
My expectation is that Envoy should return with a 400 response.

**Comment by zuercher** [comment]
cc @kbaichoo

**Comment by KBaichoo** [comment]
This happens because nothing in your filter chain stops headers from propagating to the upstream.

You could quickly fix this by using something like the buffer filter for your own deployment.

Alternatively, you can add an option to the decompressor filter which will:
1) Stop Headers from Propagating
2) Only if received chunk does not match the encoding, send local reply.

You'd do #2 around https://github.com/envoyproxy/envoy/blob/eee9b7cf37545147e135a81624589de7465179e9/source/extensions/filters/http/decompressor/decompressor_filter.cc#L162-L165

**Comment by KBaichoo** [comment]
cc @bootsieh

**Comment by joshuaspence** [comment]
@KBaichoo by "you" do you mean myself as an Envoy user or is that directed at Envoy maintainers?

**Comment by KBaichoo** [comment]
@joshuaspence It means whomever wants to pick this up
