### ISSUE TITLE
Ext-Auth: Continue filter chain processing for denied requests 

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#26489]
*Title*: *Ext-Auth: Continue filter chain processing for denied requests*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

This might sound counter intuitive but in many cases when the `ext-auth` filter decides that the request is `Denied` we don't always want to send a direct response from Envoy but rather we want to route the request to a different cluster in order to show a more user friendly page rather than a direct 403 response page.

So similarly to `failure_mode_allow` we want to allow requests which are denied to for further filter chain processing. This in combination with the issue #25330 would allow for routing based on denied responses

WDYT? Is there an alternative way to achieve this?

Assuming we have consensus on the solution and its value we can potentially contribute this feature.

**Comment by ggreenway** [comment]
There is some prior art in this area related to mTLS and selecting a route based on validated/not-validated: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch-tlscontextmatchoptions

The idea makes sense. I think it's worth considering a stronger match criteria than a header added by ext_authz, similar to how it's handled for mTLS. I'd want to be very careful about how we structure the configuration so that it's hard to accidentally configure such that auth failures result in continue processing without any handling of that condition in the routes.

**Comment by davinci26** [comment]
>  I think it's worth considering a stronger match criteria than a header

I agree here the `tlscontextmatchoptions` seems way more "native" approach. I proposed this because we seemed to be moving forward in that direction https://github.com/envoyproxy/envoy/issues/25330 but this might be slightly different.

Sweet will propose an api here by taking some inspiration from `tlscontextmatchoptions`

**Comment by ggreenway** [comment]
Either dynamic metadata or FilterState would work for this. I think there will be 3 possibilites: allowed, denied, or failed (only possible when `failure_mode_allow` is enabled). Or it could be simplified down to just allowed and not-allowed, if you think that works out better (and failure under `failure_mode_allow` would be not-allowed).
