### ISSUE TITLE
Method name as a label for thrift metrics

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#26823]
*Title*: *Method name as a label for thrift metrics*

Hey thrift owners @zuercher @JuniorHsu,

We would like expose some additional o11y for thrift proxy in the form of adding 3 new metrics (these can be either entirely new or just labels on the existing metrics):
1. `{method_name}_response_success`
2. `{method_name}_response_errors`
3. `{method_name}_response_exception`

Which contain `method` name as part of the label for the requests. Does this request make sense? WDYT?

**Comment by JuniorHsu** [comment]
Hello @davinci26 

Thanks for raising this issue. It makes sense but there's a few notes:
(a) where's is the metrics emitting? we're able to emit in a new filter with bidirectional filter [1]. we could also send from connection manager view or cluster view (after routing decision) as well. actually we have a non-opensource metrics filter which basically does the jobs. The biggest thing is performance issue, tho we don't get latency degrade but it takes 50% more cpu on thrift data flow since we're using `Stats::DynamicSavedName` . Unsure if we could use table join like zone metrics [2] but iirc it's not possible in a filter (i might be wrong) 

(b) Even we use a connmgr or cluster view metrics, most o11y has cardinality issue, which suggests those metrics with methods should be optional. Probably a repeated field like repeated<string> method_name_metrics and empty means no metrics with method name. (filter is already optional by its nature)

(c) consider add exception_local/exception_remote which is the first thing we're trying to tell the bugs. we also have invalid type/decoding error in cluster view metrics iirc but not a problem usually.


[1] https://github.com/envoyproxy/envoy/pull/20816 
[2] https://github.com/envoyproxy/envoy/blob/652a89b6a76e6a59521a46d764b2bd52317421a0/source/extensions/filters/network/thrift_proxy/router/router.h#L345-L356
