### ISSUE TITLE
setting outbound (envoy as client) SNI based on host/authority 

### ISSUE THREAD

**Issue by ldemailly** [envoyproxy/envoy#2690]
it'd be ideal if https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_ssl
sni field supported an "automatic" mode where the sni sent is the authority of the captured http traffic

(this would allow to write wildcard rules for istio and still have outbound sni work)

followup from https://github.com/envoyproxy/envoy/issues/2670#issuecomment-368726197

**Comment by glicht** [comment]
Hi All, 

Checking if anyone is working on this feature. Would be happy to help out here. 

It is something I found necessary when working with original destination cluster and egress https proxying.

**Comment by mattklein123** [comment]
@glicht this one needs design though and a formal proposal. It's not immediately clear how to implement given the decoupling of HTTP processing from the backend cluster manager where TLS options are abstracted.

The way to approach this will likely be doing a new connection pool implementation that pools connections using SNI also. 

Anyway, it needs a bunch of thinking.

**Comment by mattklein123** [comment]
Yes, you could probably do this relatively "easily" for original_dst cluster/lb by doing the following:
1) Adding server name/authority to LB context.
2) Maintaining a map in original_dst by both destination IP and authority.
3) Creating a host specific to this authority w/ SNI pre-configured.

This will require some TLS work however, since you will need to create a custom TLS context and store it along with the host, versus using the one created for the entire cluster. It's all doable but will require some splunking. cc @PiotrSikora @ggreenway @jrajahalme

**Comment by lizan** [comment]
I will take this soon if no one has been worked on. Some underlying dependency (SNI override from filter, conn pool) has been filled already.

**Comment by mattklein123** [comment]
I believe this is done.
