### ISSUE TITLE
opentelemetry tracer: configurable trace context extraction/injection

### ISSUE THREAD

**Issue by seankhliao** [envoyproxy/envoy#27384]
*Title*: configurable trace context extraction/injection for the opentelemetry tracer.

*Description*:

Distributed tracing generally consists of 2 protocols: propagation (inter-service header format) and reporting (service to telemetry backend span submission).
The opentelemetry tracer currently only supports the W3C Traceparent header for propagation.
I would like it to support translation from other formats: namely GCP `X-Cloud-Trace-Context` and AWS `X-Amzn-Trace-Id`.

In our cloud deployments, we use cloud-provided L7 load balancers which inject these headers, and start their own traces.
We'd like our proxies to participate in the same trace context, rather than start a new root.
We'd also like our internal systems to consistently only use W3C Traceparent as the canonical propagation format, rather than force every system to understand multiple possible tracing backends.

```
                      ┌────────────────────┐                                          ┌───────────┐                                 ┌───────┐
GET / HTTP/1.1        │                    │    GET / HTTP/1.1                        │           │   GET / HTTP/1.1                │       │
Host: example.com ───►│ Cloud Load Balancer├─── Host: example.com ───────────────────►│   envoy   ├── Host: example.com ───────────►│  app  │
                      │                    │    X-Cloud-Trace-Context: 0001/0001;o=1  │           │   Traceparent: 0001-0001-01     │       │
                      └────────────────────┘                                          └───────────┘                                 └───────┘
```

[optional *Relevant Links*:]

- The [OpenCensus tracer](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto) has limited support for this: it has `incoming_trace_context` and `outgoing_trace_context` supporting `TRACE_CONTEXT`, `GRPC_TRACE_BIN`, and `CLOUD_TRACE_CONTEXT`
- #9958

**Comment by ggreenway** [comment]
cc @wbpcode @Shikugawa @basvanbeek

**Comment by wbpcode** [comment]
From your description, you may want the envoy tracers could read trace context from specified headers (like `X-Cloud-Trace-Context`) rather than only `W3C`? Then the inner system could keep using the `W3C` and need care the format external headers?

**Comment by seankhliao** [comment]
> From your description, you may want the envoy tracers could read trace context from specified headers (like X-Cloud-Trace-Context) rather than only W3C? Then the inner system could keep using the W3C and need care the format external headers?

yes

I did look into header mutation, but I don't think it's possible with the limited string manipulation that's possible?

X-Cloud-Trace-Context: TRACE_ID/SPAN_ID;o=TRACE_TRUE
- TRACE_ID: 32 char hex
- SPAN_ID: decimal
- TRACE_TRUE: 0 or 1

Traceparent: 00-TRACE_ID-SPAN_UD-TRACE_FLAGS
- TRACE_ID: 32 char hex
- SPAN_ID: 16 char hex
- TRACE_FLAGS: 2 char hex

X-Amzn-Trace-Id: [FIELDKV...;]
- FIELDKV: FIELD=VERSION-TIME-ID
- FIELD: Self, Root, Parent, CalledFrom
- VERSION: decimal?
- TIME: 8 char hex
- ID: 24 char hex

**Comment by wbpcode** [comment]
Hmmm, the logic is a little complex. And It's hard to express this convertion by configuration.

We need a new early header mutation extension impl for it. But not sure if this a common requirement or just useful for you.

**Comment by wbpcode** [comment]
because I hope we can solve this problem by only one punch. Then a independent extension that work for all tracers would be helpful.

But it just a coarse idea, I have no much deep thinking or insistence on it.

**Comment by kamalmarhubi** [comment]
@wbpcode could you mark this as "help wanted" or "no stalebot"? I believe it's still a problem.

**Comment by akashjain971** [comment]
This is required. Envoy should support different propagation formats irrespective of the export format.
W3C and B3 are most widely used and required for backward compatibility and legacy applications.

**Comment by so2bin** [comment]
Yes, this should be planned

**Comment by ggreenway** [comment]
If someone wants to contribute a PR to address this, feel free. We try not to leave issues open for extremely long times when nobody is planning to do the work on it.

**Comment by DuncanDoyle** [comment]
I've got a similar requirement. In my case we receive a trace-identifier in a non-standard, custom header (e..g a correlation-id for the trace-id plus x-b3-spanid for the span-id). We want Envoy's OTel tracer to start a child span for that context, so the proxy joins the existing trace instead of creating a disconnnected root. Because the header isn't a W3C traceparent (and not even full b3), no built-in propagator reads it, so the OTEL tracer always starts a new root and the trace is broken across the proxy.

We tried solving this using `early_header_mutation`, but the problem here is that this has no per-request matcher, so it runs on every request. When the source headers are absent, we end up with a malformed `traceparent`. And a malformed `traceparent` does not result in a new root span, it actually creates no span at all. So the workaround using `early_header_mutation` workaround breaks tracing for requests that have no incoming context and should get a fresh root span.

What would actually solve this is one of two things: either a header-transformation step expressive enough to build a `traceparent` from arbitrary headers that runs *before* the tracer provider, or the ability to configure the OTel tracer provider to construct trace context from operator-specified headers. Today neither exists — the only pre-tracer hook (`early_header_mutation`) can't express the conversion (as noted earlier in this thread), and the tracer reads W3C `traceparent` only.
