### ISSUE TITLE
Remove "x-envoy-expected-rq-timeout-ms" and "x-envoy-upstream-service-time" from envoy response

### ISSUE THREAD

**Issue by pramodrj07** [envoyproxy/envoy#27776]
*Title*: *Remove "x-envoy-expected-rq-timeout-ms" and "x-envoy-upstream-service-time" from envoy response *

*Description*:
>We would like to hide these headers from the envoy's response. Though there are a few hacks in the bootstrap file itself, is there anything we can do as part of the go control plane to hide these headers?

**Comment by pramodrj07** [comment]
@ravenblackx - Thanks for the pointer, really appreciate it. I see that " "x-envoy-upstream-service-time" is successfully masked but "x-envoy-expected-rq-timeout-ms" is giving me a hard time. I tried it in all the 3 resources(RouteConfiguration, Route and VirtualHost) and it doesn't seem to mask it.

**Comment by ravenblackx** [comment]
I don't think `x-envoy-expected-rq-timeout-ms` is supposed to be in the response headers at all, it's supposed to be [added to the request headers going upstream](https://go-review.googlesource.com/c/protobuf/+/301953).

If that's what you're talking about, you'd need to put it in `request_headers_to_remove` rather than `response_headers_to_remove`.

**Comment by pramodrj07** [comment]
Thanks @ravenblackx
