### ISSUE TITLE
unmatched behavior between main thread hasCluster and worker thread getThreadLocalCluster

### ISSUE THREAD

**Issue by JuniorHsu** [envoyproxy/envoy#28103]
*Title*: *unmatched behavior between main thread hasCluster and worker thread getThreadLocalCluster*

*Description*:
We have an internal filter rely on a local cluster.
We checked `hasCluster` on the main thread to ensure we have that cluster but `getThreadLocalCluster` in the worker thread still returns nullptr, which forces us to abort envoy given we don't know if it will self-cured.

Moreover, we notice oauth filter has similar behavior.
(a) check the cluster on the main thread
https://github.com/envoyproxy/envoy/blob/f00166c4cc95b5d3aea14af40a7afe0e849cc78d/source/extensions/filters/http/oauth2/filter.cc#L158
(b) have a local reply if local thread doesn't have that cluster
https://github.com/envoyproxy/envoy/blob/f00166c4cc95b5d3aea14af40a7afe0e849cc78d/source/extensions/filters/http/oauth2/oauth_client.cc#L66-L74

Any insights?

**Comment by zuercher** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
Is this a persistent issue or a transient one during reload?  I'm pretty sure that cluster update is asynchronous so around the time of an update I'd expect corner cases like this to be possible, which is why we guard against it.  We could add more cross-thread synchronization for the master thread, or you could handle transient errors the way oauth does.  If it's a persistent disconnect that's more interesting and I'd have to get more information to help dig into it.

**Comment by JuniorHsu** [comment]
It only happen to us for new hosts since the cluster's endpoint is static. Looks like it's very possible that worker thread got the cluster information later than main thread. We abort the envoy for this case and reboot works. the pain point many abortion happened while we launch a new cluster. Main thread guard mitigate this but just a gap stopper as mentioned. we'll try to have a work thread local reply and counter to see if that's a long disconnect. Thanks.
