### ISSUE TITLE
fix releases tool to not leak creds

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2812]
https://envoyproxy.slack.com/archives/C78HA81DH/p1521068391000470

Having trouble getting this working and don't have a lot of time to invest in this. I'm going to comment this out until we clarify how to not leak creds and how to set this up.

@bndw @taion809

**Comment by bndw** [comment]
Opened an issue for the underlying upload tool: https://github.com/aktau/github-release/issues/85

**Comment by bndw** [comment]
I've opened a PR on the github-release tool that should fix the credential leak. As per @mattklein123 we'll give that a week and see if there is any activity. If there is not, we'll fork it to the envoyproxy org and apply the fix.

Once we have the leak resolved we need to update the invocation's `--user` flag, or env var, to be "envoyproxy" instead of "envoy-bot". This is because github-release [uses the user variable to build the repository URL](https://github.com/aktau/github-release/search?utf8=%E2%9C%93&q=ASSET_RELEASE_LIST_URI&type=)

**Comment by taion809** [comment]
I think this might be fine to close, I think the istio approach to this might be something we could look at mimicking.

**Comment by bndw** [comment]
Just got notified that they approved [my patch](https://github.com/aktau/github-release/pull/86) to fix the credential leak. If they decide to merge, and this is still relevant, we could pick this back up.

/cc @taion809
