### ISSUE TITLE
buffer: test flake on Windows in OwnedImplTypedTest.ReadReserveAndCommit

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#28177]
Here's a test flake that has been appearing recently in test/common/buffer/owned_impl_test.cc:
```
[ RUN      ] OwnedImplTypedTest/0.ReadReserveAndCommit
test/common/buffer/owned_impl_test.cc(1389): error: Expected equality of these values:
  result.return_value_
    Which is: 0
  static_cast<uint64_t>(rc)
    Which is: 1
Stack trace:
  00007FF7BA1AF5B6: (unknown)
  00007FF7BA1C7D88: (unknown)
  00007FF7BA1C7F4D: (unknown)
  00007FF7BA1C89BD: (unknown)
... Google Test internal frames ...

[  FAILED  ] OwnedImplTypedTest/0.ReadReserveAndCommit, where TypeParam = class Envoy::Network::IoSocketHandleImpl (1 ms)
```

Recent failure timing here:
<img width="892" alt="Screenshot 2023-06-28 at 8 37 53 PM" src="https://github.com/envoyproxy/envoy/assets/1942589/91e68519-f7c5-4a49-9876-f17c8d5ff8f7">

@phlax FYI

@weisisea I am not claiming this particular regression is necessarily due to the change you made, but yours is the last change to this test: https://github.com/envoyproxy/envoy/pull/25695 and there have been no recent changes to the impl. Given that, would you be able to investigate this issue? Thank you!

**Comment by ravenblackx** [comment]
Looking at the two impacted tests, I think the test is actually undefined behavior that should be expected to be flaky, and it's merely an implementation detail of non-windows that it happens to not be.

Both of the problem test cases perform the sequence:
1. set a socket pair to nonblocking at both ends.
2. write to one socket.
3. read from the other socket.
4. expect that the read is of the same length as the write.

Since steps 2 and 3 are nonblocking, the expectation that the read completes, and the expectation that it has all the written data, should both be not guaranteed (and it turns out, on Windows, they are not!)

I'm not sure why these tests involve sockets at all, so the minimal change I would suggest to make them less undefined (while retaining the overall behavior in case it's important) would be to either perform the read operation blocking, or to put it in a loop with a small delay and only exit the loop when the expected amount of data has been read or a timeout occurs indicating test failure.
