### ISSUE TITLE
Examples for extensions.stat_sinks.wasm

### ISSUE THREAD

**Issue by andresmargalef** [envoyproxy/envoy#28248]
*Description*:
I'm looking for some example of a custom implementation for a [stat sink in wasm](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/stat_sinks/wasm/v3/wasm.proto) but have no luck to find any.
Any pointer is welcome

**Comment by kyessenov** [comment]
There is a test example https://github.com/envoyproxy/envoy/blob/main/test/extensions/stats_sinks/wasm/test_data/test_context_cpp.cc, which uses this private encoding for the stats:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/ext/envoy_proxy_wasm_api.h#L79

I haven't seen any real module built for this API, however. It might be worth asking what you're trying to do since this is a very Envoy-specific interface.
