### ISSUE TITLE
BoringSSL FIPS is out of date 

### ISSUE THREAD

**Issue by tyxia** [envoyproxy/envoy#28246]
Currently BoringSSL FIPS is using the version that was release at [2021-04-29](https://github.com/tyxia/envoy/blob/d830cea10b24c037b8397a1e2888e6c09e50ea16/bazel/repository_locations.bzl#L132) .

Therefore, some API are not available for example `SSL_was_key_usage_invalid`.

**Comment by kyessenov** [comment]
I don't think it's that old. It looks to be 2021-04-29.

**Comment by kyessenov** [comment]
This is the last certification per https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/FIPS.md. So I don't think we can update it to anything newer.

**Comment by tyxia** [comment]
Ok, this [date](https://github.com/tyxia/envoy/blob/d830cea10b24c037b8397a1e2888e6c09e50ea16/bazel/repository_locations.bzl#L132) should be updated then.

Thanks good to know

**Comment by kyessenov** [comment]
@tyxia You're looking at an old commit.

**Comment by tyxia** [comment]
oops , you are right. The latest one is [2021-04-29] (https://github.com/tyxia/envoy/blob/37f764e056505632ae12a22d215fa46305be4053/bazel/repository_locations.bzl#L133)

**Comment by davidben** [comment]
Note that that doesn't mean Envoy can't use new APIs at all. Of course, if Envoy wishes to support such-and-such old BoringSSL in some builds, those builds will be unable to use newer BoringSSL features. But Envoy builds targeting more recent BoringSSL versions can use new features perfectly fine. You just gate the code behind a preprocessor check like `#if BORINGSSL_API_VERSION >= ...`. That's BoringSSL's standard strategy for dealing with version skew.

In particular, the API you mentioned was specifically added because someone on Google's Envoy team requested it to help manage a transition to enable this security check. Our expectation was that they would use it in Envoy quickly, using this standard version skew strategy, and not wait for Envoy's oldest supported version to move past it. I'm a little surprised to hear that's the impediment. Hopefully this comment clears up the conclusion and Envoy can now switch to using BoringSSL following our standard practices. Artificially waiting years before you can use new features does no one any good. :-)

**Comment by tyxia** [comment]
@davidben Thanks for sharing the details and info!
I just want to clarify one thing in case there is any misunderstanding: This API is now being used but not in FIPS mode like below:
```
#ifndef BORINGSSL_FIPS
  // Increment the `was_key_usage_invalid_` stats to indicate the given cert would have triggered an
  // error but is allowed because the enforcement that rsa key usage and tls usage need to be
  // matched has been disabled.
  if (SSL_was_key_usage_invalid(ssl)) {
    stats_.was_key_usage_invalid_.inc();
  }
#endif
```

Regarding `#if BORINGSSL_API_VERSION >= ...` you mentioned, I think it won't be effective until version that Envoy is using is actually bumped? But it is the good generic approach to check in the code using API in the future

**Comment by davidben** [comment]
Ah okay. Yeah that works too. Using the number means it'll get picked up automatically as the BORINGSSL_FIPS build updates, and you can keep track of which ifdefs are old and can be retired.

**Comment by ggreenway** [comment]
We're already using the latest FIPS build as noted above; closing
