### ISSUE TITLE
Envoy stats sink - flush time or max_bytes_per_datagram

### ISSUE THREAD

**Issue by javedsha** [envoyproxy/envoy#28316]
*Title*: How Envoy flushes stats to stats sink?

*Description*:
I have a dogstatsdsink set up and the CPU utlization of envoy and the sink is going very high, due to which throughput to redis cluster is affected. Without the stats sink, everything works perfectly (as I expect the throughput and latency to be of redis calls)

Is there a way to set the stats flush time in envoy ?
Or what is the ideal value for max_bytes_per_datagram?

*config*:
"stats_config": {
    "use_all_default_tags": "true",
    "stats_tags": [
      {
        "tag_name": "custom_namespace",
        "fixed_value": "ch"
      }
    ]
  },
  "stats_sinks": [
    {
      "name": "envoy.stat_sinks.dog_statsd",
      "typed_config": {
        "@type": "type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink",
        "prefix": "envoy",
        "address": {
          "socket_address": {
            "protocol": "UDP",
            "address": "127.0.0.1",
            "port_value": xxxx
          }
        }
      }
    }
  ]

We are running envoy with conncurency 4 (have tried all concurrency setting, but same issue always).

The stats agent is taking 120% CPU, and is a bottleneck for redis calls. Without the stats configuration above, our redis performance increases close to double.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by alyssawilk** [comment]
cc @jmarantz

**Comment by javedsha** [comment]
@jmarantz Hello, ping :) This is a blocker for us at the moment, any help will be much appreciated. Thanks.

**Comment by jmarantz** [comment]
Have you captured a flame graph? I don't know DogStatsSink; is this for Data Dog?

**Comment by jmarantz** [comment]
To answer your specific question, you can set the stats flush interval using https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-field-config-bootstrap-v3-bootstrap-stats-flush-interval

**Comment by sschepens** [comment]
Something we realized recently is that Histograms in Statsd are submitted each time a value is recorded, because Statsd is the one aggregating and calculating the histogram.
This basically causes envoy to send several UDP packets to Statsd for each request.

**Comment by sschepens** [comment]
[here](https://github.com/envoyproxy/envoy/blob/main/source/extensions/stat_sinks/common/statsd/statsd.cc#L108) is the code where statsd ends up flushing histograms everytime a value is recorded.

So flush interval really only apples to counter and gauges.

**Comment by jmarantz** [comment]
Yes that seems to be how it works. I'm a little surprised by this, to be honest, but it doesn't appear to be an accident.

Is the problem that there's no buffering in the UDP statsd filter, and we really should batch these up?

**Comment by sschepens** [comment]
We could batch these and attempt to send multiple in the same UDP packet.

Also, Dogstatsd (DataDogs implementation of Statsd) allows batching submissions of histogram values, it basically supports sending a list of values to submit for a histogram.

**Comment by javedsha** [comment]
is the batching possible today? or disabling the histogram?

**Comment by jmarantz** [comment]
There is a new DataDog interface. @dgoffredo FYI. See https://github.com/envoyproxy/envoy/pull/23958

It might be that the statsd protocol is not the optimal one for populating Data Dog.

FYI we use this histogram hook internally to copy Envoy histogram data to our own custom histogram structures, effectively batching the updates.

**Comment by dgoffredo** [comment]
The work in https://github.com/envoyproxy/envoy/pull/23958 was for the tracing subsystem, and does not involve the submission of statistics.

**Comment by jmarantz** [comment]
Ah thanks @dgoffredo .

The decision to write histogram data to UDP as it is updated for statsd seems to go back a long way. E.g. https://github.com/envoyproxy/envoy/pull/2158 or maybe even further back than that.

I think someone with skin-in-the-game on statsd needs to make a call about whether this is the desired behavior. I can definitely believe it's expensive.

Disabling an individual histogram is reasonable easy, using the stats-matcher API. However disablng *all* histograms is a bit onerous and may add a lot of stats-matcher overhead to stats creation.

I think it would be a good beginner project to add an option to disable *all* histograms.

**Comment by jmarantz** [comment]
@dgoffredo do you have opinions from the Data Dog perspective on whether there should be buffering of histogram updates in-memory for flushing later?

**Comment by dceravigupta** [comment]
Is this issue specific to statsd/dogstatsd? Wondering whether the same problem exists in opentelemetry sink as well or not?

**Comment by dgoffredo** [comment]
@jmarantz 

> [...] do you have opinions from the Data Dog perspective on whether there should be buffering of histogram updates in-memory for flushing later?

I don't have an opinion, and it's because I don't have any experience with that part of the product.

My only use of Datadog stats so far has been to send an HTTP POST to api.datadoghq.com/api/v1/series in a cron job every few minutes. That is, to my knowledge, not the intended usage.

For C++, I don't know of any dogstatsd client supported by Datadog. There is the third-party [cpp-datadogstatsd][1], which is based on Datadog's [php-datadogstatsd][2]. I looked through the code today, but not very closely — not sure if there's any batching going on.

Apropos, though, in Datadog's Python version of the idea is this [commit][3] from late 2021. There "buffering" of data sent to dogstatsd was disabled. So, previously it had been implemented and enabled by default (in Python). Today, it is still [disabled by default][4].

I can discuss this topic more with my team and with more metrics-focused people within Datadog; but, judging by the state of client libraries, I doubt we will have a strong recommendation.

[1]: https://github.com/BoardiesITSolutions/cpp-datadogstatsd
[2]: https://github.com/DataDog/php-datadogstatsd
[3]: https://github.com/DataDog/datadogpy/commit/2cba9f6690a627a7e94465bb18a90e963c5f4d3e
[4]: https://github.com/DataDog/datadogpy/blob/5ca8b0c57b1766823318fb8b983287b55c9dfe44/datadog/dogstatsd/base.py#L98

**Comment by dgoffredo** [comment]
@javedsha 

> We are running envoy with conncurency 4 (have tried all concurrency setting, but same issue always).
>
>The stats agent is taking 120% CPU, and is a bottleneck for redis calls. Without the stats configuration above, our redis performance increases close to double.

I'd be interested to know which part of the metrics sink code is using a lot of CPU.

If it's the system-ish overhead of sending the UDP datagrams to dogstatsd, then batching might be a viable way to reduce CPU usage. However, if it's some calculation going on in Envoy code, then batching at the transport might not help much.

@jmarantz I did a closer survey of existing dogstatsd client libraries.

- The Ruby library [dogstatsd-ruby][1] batches messages and [flushes them][2] at regular intervals.
- The Go library [datadog-go][3], [aggregates metrics][4] and periodically flushes them.
- The Java library, [java-dogstatsd-client][5], I haven't yet grokked, but its README file does [say][6] "we have tried to set convenient maximum default packet sizes that should help with performance by packing multiple statsd metrics into each network packet," which makes me think that messages are batched at the transport.
- The PHP library, [php-datadogsatsd][7], has [two implementations][8]: one with batching, and one without.
- The C# library, [dogstatsd-csharp-client][9], performs "[client side aggregation][10]," which combines some metrics events instead of sending them separately.
- A non-public C library batches messages in memory and serializes them periodically.

Based on this, it looks like either batching messages, combining multiple events into one, or both, is the norm for submitting metrics to dogstatsd.

One caveat to remember is the Python issue that I mentioned in a previous comment.

[1]: https://github.com/DataDog/dogstatsd-ruby/tree/master
[2]: https://github.com/DataDog/dogstatsd-ruby/blob/02e217e4b8db4193e89d1e2b954b9da1cb99a965/lib/datadog/statsd/sender.rb#L24
[3]: https://github.com/DataDog/datadog-go
[4]: https://github.com/DataDog/datadog-go/blob/master/statsd/aggregator.go
[5]: https://github.com/DataDog/java-dogstatsd-client
[6]: https://github.com/DataDog/java-dogstatsd-client#transport-and-maximum-packet-size
[7]: https://github.com/DataDog/php-datadogstatsd/tree/master
[8]: https://github.com/DataDog/php-datadogstatsd/blob/63071c99a188e09a0f2f0ffc537a0a826aa1065e/examples/example.php#L5-L6C13
[9]: https://github.com/DataDog/dogstatsd-csharp-client/tree/master
[10]: https://github.com/DataDog/dogstatsd-csharp-client/tree/master#client-side-aggregation

**Comment by javedsha** [comment]
We tried using open telemetry instead of statsd, and this has resolve the issue for us.
