### ISSUE TITLE
Is there any way to evict shared data?

### ISSUE THREAD

**Issue by LoremipsumSharp** [envoyproxy/envoy#28339]
*Title*: *Is there any way to evict shared data?*

*Description*:
I am developing a wasm plugin, which would cache the authentication ticket (Json format) into shared data, it seems there is no API available to evict the cache, as the memory keep increasing, the instance would OOM finally? I wonder if envoy has implemented any LRU like cache store for such scenario.

**Comment by alyssawilk** [comment]
cc @mpwarres  @lizan

**Comment by mpwarres** [comment]
You're correct that the Proxy-Wasm API currently only provides ways to read and write shared data, but not to erase it. In practice, you could conserve memory somewhat by writing a zero-length string as the value for a key, and having reads treat that as another case of "entry not found". But that isn't quite the same as fully deleting the entry.

Envoy uses the default implementation of the shared data functions provided by proxy-wasm-cpp-sdk--see [here](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/25daf5e9b7fe25595cee966d09fcb750fcf7c5d7/src/context.cc#L194-L210) and [here](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/25daf5e9b7fe25595cee966d09fcb750fcf7c5d7/src/shared_data.cc#L28). Internally, there actually *is* a [`removeSharedDataKey`](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/25daf5e9b7fe25595cee966d09fcb750fcf7c5d7/src/shared_data.cc#L28) method to remove shared data entries, but it is not currently exposed via the Proxy-Wasm API. If you'd like to see it added, I'd suggest filing an issue against the Proxy-Wasm spec at https://github.com/proxy-wasm/spec/issues .

This is supposition on my part, but I wonder if part of the reason for not exposing an erase function is that it weakens the shared data atomicity story. The shared data API uses/stores "cas" (compare-and-swap) tag values to allow plugins to atomically update entries even if there are competing writes. If we add deletes into the mix, we'd still need to keep track of the cas tag even for deleted entries, at which point there isn't a huge difference between deleting an entry vs. writing an empty value to it. But that's just a guess.

Tagging @PiotrSikora in case he has any thoughts on this.

**Comment by LoremipsumSharp** [comment]
@mpwarres thanks for you reply. If the cache unable to purge from the shared data, does that mean the envoy instance is at the risk of OOM.As far as I known, some reverse proxy like openresty, which implemented its shared data in LRU style so the cache item in would evict when the memory limit is hit.

**Comment by PiotrSikora** [comment]
@mpwarres it's extremely nice of you think of us that highly, but the reason for missing removal function is simply because it was missing at the time of the initial commit, and we're stuck with the ABI that was never meant to be the final version (hence vNEXT).

We also went through the "consolidation phase" at one point, so it's likely that we planned for `set(key, NULL, cas)` to remove the `key`, but that was never implemented.

Regarding compare-and-swap value - it's a global counter, so I don't think you'd need to store it for removed items, and it could be included in the delete function to preserve atomic semantics.

Regarding [removeSharedDataKey](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/25daf5e9b7fe25595cee966d09fcb750fcf7c5d7/src/shared_data.cc#L28) - it was added later by @jamesmulcahy (see: https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/203), along with a [custom Envoy extension](https://gist.github.com/jamesmulcahy/03a656b2a4e564993e6f044672698e2b) to expose those functions via FFI.
