### ISSUE TITLE
Cannot modify body in `ext_proc` filter due to clearance of `content-length` header

### ISSUE THREAD

**Issue by EItanya** [envoyproxy/envoy#28515]
*Title*: Cannot modify body in `ext_proc` filter due to clearance of `content-length` header

*Description*:
Currently in the `ext_proc` filter I cannot modify the body of the request, (and potentially the response but I haven't tested), because a `modify_body` request will always result in the clearance of the `content-length` header. The filter should either allow the user to set it themselves, or set the header based on the final modified value.

The offending code is here: https://github.com/envoyproxy/envoy/blob/0a672f829fcc02681de38656b964ebae00c58608/source/extensions/filters/http/ext_proc/processor_state.cc#L231-L233

Because the header clear happens after the header mutations, there's no opportunity to set the content-length header properly.

*Repro steps*:
To reproduce this bug I have a repo based off of @gbrail's rust stubs. https://github.com/EItanya/envoy-ext-proc-stubs-rust
First, run `cargo build` to build the rust server. Then download envoy v1.26.3. Finally run all of the necessary pieces.
1. `python3 server.py`
2. `./target/debug/server`
3. `<envoy> -c envoy.yaml --component-log-level ext_proc:trac`
4. `curl -X POST -d '{"Hello": "server"}' http://localhost:8000/service/2

The curl request will fail because `server.py` does not receive the content-length header because it is cleared.

I am happy to create a PR to remove the offending header clears, but I want to better understand why they are there, and what the intentional behavior is. Also, there is an integ test that is supposed to test this behavior, but in the test logs I see that the content-length header is not set, so I think it's passing when it should not be.

**Comment by lizan** [comment]
@gbrail @stevenzzzz @tyxia

**Comment by tyxia** [comment]
oh sorry missed this issue earlier.

Yes, I also noticed this and having a fix locally

**Comment by EItanya** [comment]
To be honest I'm not sure what that comment means, I wasn't able to get it working without manually modifying the code and re-building. 

I'm fairly certain the integration tests are passing by chance, from my brief digging around it seemed that the server wasn't taking into account content-length, but I was never able to fully confirm the behavior as I was forced to move on.

**Comment by tyxia** [comment]
@EItanya Actually i have a theory:

Yes, integration test doesn't check `content-length`. I think for your case, curl will check the `content_length` first before reading the body. In other words, body actually has been mutated ext_proc/envoy but the mutation doesn't show uo because `content_length` check in curl fails first. 

Does this make sense to you?

**Comment by tyxia** [comment]
One thing I can see is python server fail to read the body because that server check the `content_length` first. (just not curl logic)

So I want to confirm that `python server` is your upstream server? Just to clarify my terminology and my understanding of your use case, you are on request path: 

request is sent from `downstream client` ---> Envoy/ext_proc  ---> send to side stream callout server for body mutation ----> return back envoy and ext_proc remove the content length ---- > then the original request is continue to upstream server (python server)

Is my understanding correct?

**Comment by EItanya** [comment]
Yup! That's corect

**Comment by tyxia** [comment]
Thanks for confirmation！

Could you please check what if you remove the content length check on the python server side, can you see the expected request body mutation? (Not sure if it is possible for you server logic)

**Comment by EItanya** [comment]
So per the HTTP1 spec as I understand it, there's no way for a client/server to know the size of the body without the content-length header, and therefore no way to buffer the correct amount of bytes.

**Comment by tyxia** [comment]
Yes, I understand and i agree this is the issue need to be addressed. The I hope to confirm (via the experiment i mentioned above) is if the body mutation (by ext_proc then callout server) still be able go through all the way to your python server.

Besides, I want to confirm: 1) so once you remove that clearContenLength logic, your python server is working fine? i.e., you can see the expected body mutation. 2) if so, is your [processing_mopde](https://github.com/envoyproxy/envoy/blob/8bdc349965979b08f0d8258b151de98be22d6ea2/api/envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto#L49) is set to BUFFERED

**Comment by EItanya** [comment]
Ahh I see. Yes the body mutation is properly done by envoy, but then the server fails to parse the request. 

1) yes
2) yes

**Comment by tyxia** [comment]
@gbrail I saw your replies to the other ext_proc issue. While i have you here, can i ask if you still remember why ext_proc is doing removal of [contentLength](https://github.com/envoyproxy/envoy/blob/0a672f829fcc02681de38656b964ebae00c58608/source/extensions/filters/http/ext_proc/processor_state.cc#L233) and [here](https://github.com/envoyproxy/envoy/blob/0a672f829fcc02681de38656b964ebae00c58608/source/extensions/filters/http/ext_proc/processor_state.cc#L295) and here [https://github.com/envoyproxy/envoy/blob/0a672f829fcc02681de38656b964ebae00c58608/source/extensions/filters/http/ext_proc/processor_state.cc#L105].

From our testing, it seems that proxy won't restore the context length, and such clear behavior make the application(either client or server) fail to read the full body

**Comment by tyxia** [comment]
@EItanya  Hi Eitan, Could you please help to check if chunked encoding is enabled? Based on [HTTP1 codec impl logic](https://github.com/envoyproxy/envoy/blob/93b7427eb6bfcdd9c67b6723389b2f7cb05fa407/source/common/http/http1/codec_impl.cc#L176-L230) , envoy will try to enable chunk encoding when content_length header is removed.

If it is enabled, application can read the body based on chunked transfer encoding without need of content length

**Comment by tyxia** [comment]
@EItanya  I was able to confirm the codec logic i mentioned above. Also, I took a quick look at your sever.py. More specifically, https://github.com/EItanya/envoy-ext-proc-stubs-rust/blob/0f5abbce29831075c35b86cf657f1f26ba4d88b1/server.py#L13

I think we should not rely on content length to read body as chunk encoding is preferred/enabled in the codec whenever feasible

**Comment by tyxia** [comment]
I think it is a fair point. In http 1.1, we can make chunked encoding optional in ext_proc buffer mode where content length could be set correctly. In other words, it is up to user to decide whether they want to use `content_length` or `chunked encoding` in this case.

**Comment by yanjunxiang-google** [comment]
@EItanya 

Thanks for bring up this content-length issue.

We are changing ext_proc filter design to be like below regarding the HTTP1.1 content-length encoding:

1) The content-length will be removed from the message header in the case the body is sent to the external processing server for mutation. This will ends up the message being chunk-encoded by Envoy codec before either forwarded to upstream(request) or downstream(response).

2) The external processing server get the body from gRPC, so it does not need the content-length header.
https://github.com/envoyproxy/envoy/blob/52f9f33a826e44df30054c06cadaafc2191f59b2/api/envoy/service/ext_proc/v3/external_processor.proto#L92C31-L92C31
or
https://github.com/envoyproxy/envoy/blob/52f9f33a826e44df30054c06cadaafc2191f59b2/api/envoy/service/ext_proc/v3/external_processor.proto#L96

3) The upstream server or downstream client received the body which is chunk encoded. It can do chunk decoding there.

4) There server.py above
https://github.com/EItanya/envoy-ext-proc-stubs-rust/blob/0f5abbce29831075c35b86cf657f1f26ba4d88b1/server.py#L13
 is an example server code specially written for the H1.1 with content-length encoded.  This need to be modified to support if the the body is chunk-encoded.

**Comment by yanjunxiang-google** [comment]
@htuch @yanavlasov @stevenzzzz

**Comment by tyxia** [comment]
I personally lean towards keeping content length in buffer mode as one option.

`header mode NONE + body mode BUFFERED` is simply not a valid configuration if a customer wants to set the content length header. If they want to mutate the header, their header mode will NOT be `NONE`. We can be specific in API .

In other words, buffer mode/ext_proc does have the ability to update the content length correctly via the `mutateHeaderOnBody` feature that is also available in other OSS filters. I don’t fully understand why we want to disable this feature and possibly break other users.  I think the effort to achieve this flexibility is just a few lines of code.

However, I am ok if other folks want to remove the content-length completely.

**Comment by EItanya** [comment]
I understand the motivation behind this, but honestly I don't think it takes into account the reality that many many people are running services which can use chunk encoding, regardless of whether or not it's defined in the spec.

**Comment by yanjunxiang-google** [comment]
@EItanya 
Do you mean you have some backend servers which do HTTP1.1, but does not support chunk encoding, and only can decode request which has content-length in the headers?  This kind of backend server is not compliant to the HTTP1.1 spec here:
https://datatracker.ietf.org/doc/html/rfc9112#name-chunked-transfer-coding

Here is some text:
"
The chunked transfer coding wraps content in order to transfer it as a series of chunks, each with its own size indicator, followed by an OPTIONAL trailer section containing trailer fields. Chunked enables content streams of unknown size to be transferred as a sequence of length-delimited buffers, which enables the sender to retain connection persistence and the recipient to know when it has received the entire message.

A recipient MUST be able to parse and decode the chunked transfer coding.
"
So, if a client do not know the body length beforehand, it will send data with chunk encoding, no content-length in the header. And a server MUST be able to parse such data.

**Comment by EItanya** [comment]
for HTTP1.1 correct, but afaik envoy supports HTTP1.0?

**Comment by htuch** [comment]
What is the issue with keeping content length in buffer move? It feels reasonable to support (at least as a configurable option) and  avoids us being too opinionated.

For HTTP 1.0 and 1.1 clients / servers, the last thing anyone should assume is RFC compliance. These are text protocols that plenty of real systems implement in a very ad hoc way (think that 5 line Python thing you might cook up).

**Comment by yanjunxiang-google** [comment]
@htuch , for keeping content-length in buffer mode, if the body is later on modified, but the header is already shipped to the next filter in the chain(header mode is NONE), that leaves the content-length and body size out-of-sync, by spec that will cause the message be dropped.   At same time, chunk-encoding is the standard way if the body length is not predetermined.
Do you mean Envoy should support a way for non-RFC compliant backend server (like only can do decode based on content-length) to work?  That will need some significant changes on Envoy side.

**Comment by yanjunxiang-google** [comment]
@EItanya 
Envoy support HTTP1.0 client. But does not support HTTP1.0 backend server.

So, for downstream request from HTTP1.0 client, it will be converted to H1.1 or H2  so chunk-encoding is fine there.

For upstream response back to HTTP1.0 client, content-length is not required in response path.  Envoy will simply close the connection as the indication of end-of-stream.
https://www.ietf.org/rfc/rfc1945.txt#:~:text=Otherwise%2C%20the%20body%20length%20is%20determined%20by%20the%20closing%0A%20%20%20of%20the%20connection%20by%20the%20server.

**Comment by htuch** [comment]
@yanjunxiang-google @tyxia have you considered just truncating the bodies? If an ext_proc server doesn't respect the content-length, just drop the body (or even error out the request)?

**Comment by gbrail** [comment]
Sorry I didn't answer, I'll try to recall the historical context...

When people first started using ext_proc, users had trouble with any
processor that modified the body because if they changed the length of the
body but didn't fix the content-length header, then the resulting request
would not match the HTTP spec. A best practice when writing an ext_proc
processor that modifies the body is to remove the content-length header
before modifying the body, especially if you don't know what the final
length will be, such as when writing a server that does streaming
transformation, like one of the samples does here:

https://github.com/google/envoy-processor-examples/blob/c904408579be62d1bcf43e3dae1f8ab4df91eb27/go/cmd/processor/service.go#L488

This works because if the header is removed, Envoy automatically puts the
data into streaming mode, which is all compatible with HTTP/1.1 and works
fine. (I even recall at some point that if the whole body is one big chunk,
that Envoy puts the content-length header back, but I may be hallucinating
that part.)

A lot of people were forgetting to do this, and as a result their
processors weren't working, so we must have decided to do this for them in
certain processing modes so that the process works in a least astonishing
way.

What I didn't think about was the number of clients and servers that don't
properly implement HTTP/1.1 and thus don't support chunked encoding.

Perhaps one way to have it both ways would be to move the order of the
header and body processing in that code chunk you linked to so that, if the
processor modifies the body but supplies a new content-length header, that
we won't strip it off anyway. This would only work in BUFFERED mode, which
is the only mode in which we can modify the body and headers
simultaneously, but it might be worth a try.

**Comment by jmarantz** [comment]
One benefit of having a content-length header is that clients may behave better if they know the content-length before processing the body. I can think of two ways clients may exploit this off the top of my head:
 * An API could pre-allocate the right-size continuous buffer for the content
 * A browser could display an accurate progress bar for a long download

I think Greg has a good idea -- it's probably best for the filters to remove the content-length if they plan on modifying the content, and then, if Envoy can figure out the full content before writing headers to the network it can add the content-length header. I don't know if it actually does that though. That, I think, resolves Yanjun's concern of the headers having been passed to the next filter in the chain prior to knowing how the content-length may change.

**Comment by tyxia** [comment]
I think Envoy won't restore content_length header. In HTTP1 codec. when content_length is NOT present, it will enforce chunked encoding whenever feasible. Please see the [code](https://github.com/envoyproxy/envoy/blob/c97ba34a56bd3643c9a9fffe5f4c8e34fddbebe5/source/common/http/http1/codec_impl.cc#L176) . I also have confirmed in codec test and ext_proc integration test on both request/response path.

**Comment by gbrail** [comment]
That makes sense about Envoy and HTTP/1.1.

Today, is it possible for someone writing a processor to receive the body
in BUFFERED encoding, replace the body with a body with the different
length, and update the content-length header to match? Today I know that
the protocol supports that, but looking at the code referenced above, it
seems as if Envoy would remove the header anyway.

Or, in ext_proc itself, when processing the response to a buffered body
that has been modified, ext_proc could just update the content-length
directly -- in retrospect I'm not sure why we didn't do that.

Either way, however, anyone who is writing a processor that modifies the
body in streaming mode (which is probably few if any people) must remove
the content-length when processing the headers, before processing any of
the body data, because in streaming mode, once the headers are gone it is
too late to change them.

**Comment by tyxia** [comment]
Yes that is our plan:

- Stream mode: always remove content length

- Buffer mode: For the code I referred to: if content-length is not removed beforehand(e.g., not removed by ext_proc filter) , Envoy won't remove it.  I think we are currently leaning towards having 2 options for buffer mode : 
-- Remove content length: This will enforce chunked encoding and client doesn't need to worry about setting up correct content length 
-- Keep content_length: customer need to set up the correct content length header (which means they need to have correct processing mode as well)when they mutate the body with different length. 


Such handling of buffer mode addresses the ask in this issue. It can be discussed further.

**Comment by yanjunxiang-google** [comment]
Thanks everyone for the comments!  Thanks @tyxia for your plan.  After discussing with @htuch @yanavlasov , can we tweak the design a little to bit to be as below:
    
    Have ext_proc filter preserver "content-length" header if it is possible, but strip it whenever it is impossible.

To achieve that:

-     STREAMED | BUFFERED_PARTIAL mode: always remove content length
      impossible to get a correct content-length after body mutation.

-    BUFFERED mode
     1) If header mode is SEND, then preserve the "content-length", and ext_proc server MUST send back the correct "content-length" after body mutation. ext_proc filter will put the update "content-length" in the header and send.
        This is the only configuration combination after the body mutation, the body length is known and header is still in the ext_proc filter buffer.
     2) If header mode is NONE,  remove content-length. 
In this configuration, it is impossible to update the header after body mutation since body is already gone.

**Comment by htuch** [comment]
LGTM. @eltanya @gbrail @tyxia ?

**Comment by tyxia** [comment]
Thanks for summary Yanjun! SGTM

**Comment by yanjunxiang-google** [comment]
> Thanks for summary Yanjun! SGTM
> 
> Regarding preserving the content-length, we also need to clarify the contract that ext_proc server is responsible for setting correct "content-length" in API/doc etc

Yes, that's right!

**Comment by EItanya** [comment]
Definitely agree on this, I think forcing the ext-proc server to set it makes the most sense to me as well, it should definitely proclaimed loudly in the docs haha
