### ISSUE TITLE
Allow creating headers after reading body content in Wasm

### ISSUE THREAD

**Issue by djannot** [envoyproxy/envoy#28587]
It looks like it's not possible today because the function to manipulate headers is only called before the function to access the body.

I talked to @yuval-k who thinks it's due to this:
https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/c932df12c9db59d331dcb1020174d5f911f67244/src/context.cc#L500

My use case is to generate a new header representing the hash of the body data.

**Comment by StarryVae** [comment]
In this scenario, `StopIteration` should be return in `onRequestHeaders` phase since a new header representing the hash of the body data need to be added, but proxy-wasm converts `StopIteration` to `StopAllIterationAndWatermark` which makes the filter chain stop unless `continueDecoding` called, but where should we call the `continueDecoding` in this scenario? cc @mpwarres @PiotrSikora

**Comment by PiotrSikora** [comment]
This scenario is not currently supported in Proxy-Wasm (although, it will be handled better in the next version of the ABI).

Having said that, for something like "hash of the body data", you should really use HTTP trailers and compute hash while streaming the request/response body. Otherwise, you need to buffer the whole request/response body in the proxy, which will eventually trigger out-of-memory crashes.

**Comment by djannot** [comment]
@PiotrSikora the request body tends to be small in most use cases (apart form file uploads) and there are many examples where a hash of the body can be useful at the gateway level.
For example, to apply rate limiting or authorization based on the request body, especially for REST or GraphQL APIs.

**Comment by PiotrSikora** [comment]
@djannot but "small body" is by no means a rule and in significant number of cases (file uploads and response bodies) the body is larger than the proxy buffer size and/or flow control.

As such, this is not something that could be "simply" enabled, without accounting for deadlocks, risking crashing plugins (if Wasm memory limit is enforced), risking crashing proxy (if Wasm momory limit is not enforced). Again, this is something that we want to address in the next version of the ABI, but simply returning something like `StopIteration` is not even close to being sufficient.
