### ISSUE TITLE
Envoy Stats to emit Duration as metric

### ISSUE THREAD

**Issue by djonnadula** [envoyproxy/envoy#28669]
*Title*: *Envoy Stats to emit Duration as metric*

*Description*:
>It would be really helpful having visibility into Envoys stats registry to capture Duration as metric rather than just accessible for given request to logged in logs 
%DURATION%
HTTP/THRIFT
Total duration in milliseconds of the request from the start time to the last byte out.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by ohadvano** [comment]
I think that [downstream_cx_length_ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#listener) and [upstream_cx_length_ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#general) can be used for that purpose

**Comment by wbpcode** [comment]
cc @jmarantz

**Comment by djonnadula** [comment]
@ohadvano [upstream_cx_length_ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#general)
makes sense as it really instrumentation at cluster level but [downstream_cx_length_ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#listener)
does not really work in case where envoy acts as ingress. There is no real way to track accurately for given request downstream cx_lenght_ms 
Ex: 
envoy_http_downstream_cx_length_ms_bucket{container="envoy", endpoint="8002", envoy_http_conn_manager_prefix="ingress_https", instance="1.1.1.1:8002", job="envoy", le="5000", namespace="ingress-contour", pod="envoy-12345", service="envoy"}

**Comment by ohadvano** [comment]
For a specific request there's no tracking of downstream duration, I agree. I don't think it's impossible to support this, but I think that the problem doing so is that you would need a way to distinguish between those metrics. Assuming you emit a gauge metric for each downstream connection or request, you would need to tag that gauge with some unique identifier, otherwise it will conflict with other metrics of the same name. I believe @jmarantz may add more information on this and whether it's possible and/or perf considerations.
