### ISSUE TITLE
Listener filter chain matching based on HTTP Host

### ISSUE THREAD

**Issue by pchaseh** [envoyproxy/envoy#28953]
*Title*: *Listener filter chain matching based on HTTP Host*

*Description*:
As it currently stands, we can have listeners use different chains based on TLS SNI (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_listener) or HTTP protocol version (https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/http_inspector)

We use Envoy as an edge proxy where being able to have one listener accept traffic for multiple domains, each with their own configuration (meaning a unique HTTP Connection Manager) is desirable. While choosing the listener filter chain  based on TLS SNI woul work, unfortunately it appears as if there is no equivalent for plain HTTP. If, for non-TLS listeners, we could have a listener filter (or revisions to the HTTP Inspector) that allowed us to use the `Host` HTTP header to match chains, I believe that this would meet our needs.

**Comment by yanavlasov** [comment]
If you just need different HTTP filters for different Host values, you can try composite filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter.html#composite-filter

If however a different HCM config is needed then either HTTP Inspector needs to be extended to extract Host, or a new listener filter is needed, since HTTP inspector supports both H/1 and H/2.

**Comment by pchaseh** [comment]
Hi,

This indeed appears to work, I completely looked over the composite filter. Thanks a lot!
