### ISSUE TITLE
What is BPF used for in HTTP/3?

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#29148]
The HTTP/3 doc strongly suggest to enable BPF for "production performance": https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http3#arch-overview-http3-downstream-bpf
Will appreciate any extra detail on what this impacts in practice? How does it improve the performance?
Thanks

**Comment by RyanTheOptimist** [comment]
cc: @danzh2010 @ravenblackx @RyanTheOptimist

**Comment by danzh2010** [comment]
If BPF is not supported, most QUIC packets will land on the wrong worker threads and then be tossed to the right one with the default QUIC connection ID generator implementation. This will be very CPU costly.

You can override the default QUIC connection ID generator in a way that it actually doesn't toss packets across workers, but then you won't have QUIC connection migration which is also a network performance gain for QUIC.

**Comment by ravenblackx** [comment]
> Is this because as opposed to TCP where there's a connection handled by an accept socket, for UDP the traffic is coming through the listener socket and since multiple workers are using the same port, the kernel will randomly dispatch the UDP packet to one of the worker listeners?

Pretty much yes (though it's a little more involved than "randomly", for our purposes it is effectively "arbitrarily").

For TCP a new socket is *created* by the accept socket; the new port number of that created socket acts similarly to how we use the worker id portion of the connection id, for the kernel to deliver packets to the correct 'socket'.

**Comment by danzh2010** [comment]
> Got it, thanks. On the same topic of UDP, let's say Envoy is a UDP server (regardless of QUIC) and I have some UDP client. If the client will send a lot of UDP datagrams (let's assume millions) to the same destination (Envoy's IP and port its listening on UDP), therefore the same 5-tuple, is it expected that all UDP datagrams will land on the same worker's listener? Will they land on multiple workers?

They will land on the same worker.

**Comment by ohadvano** [comment]
Thanks, I guess my original question is answered, I'm just trying to understand the difference between QUIC and normal UDP then, because I'm confused now. If normal UDP will land on the same worker why in the QUIC case packets may land on different workers?

**Comment by ohadvano** [comment]
Thanks

**Comment by ravenblackx** [comment]
I may also be confused now. :)

Is there something in the kernel that maps source ip to a particular worker or something, for regular UDP? I thought the answer to the last question would be that regular non-BPF-programmed UDP packets would land on whichever worker happens to be next in the read queue.

**Comment by ohadvano** [comment]
Well, I deleted my previous comment but for those who didn't make it to read - I asked why QUIC is behaving differently than normal UDP datagrams that requires this extra balancing that plaintext UDP doesn't.

@ravenblackx yes, from this article: https://lwn.net/Articles/542629/, it seems that the kernel will hash the 4-tuple and based on that will choose the listener among those who are reusing the socket, so that consecutive UDP datagrams with the same 4-tuple will land on the same worker.

For QUIC I assume that the balancing is not really about the UDP part rather than making multiple QUIC streams land on the same worker, so related streams of the same connection are identified by the connection ID as @danzh2010 mentioned earlier.

Hope you could confirm my understanding, thanks

**Comment by ravenblackx** [comment]
> yes, from this article: https://lwn.net/Articles/542629/

Ah, neat, I didn't realize UDP was self-optimizing like that, thanks for the link.

> For QUIC I assume that the balancing is not really about the UDP part rather than making multiple QUIC streams land on the same worker, so related streams of the same connection are identified by the connection ID

I don't think it's relevant to that part - multiple streams from the same connection would still all have the same 4-tuple so the kernel UDP handling would be adequate to support those being delivered to the same worker as well, without the BPF. The BPF handling becomes important when the client end of the QUIC connection changes IP address. With TCP, or with the basic kernel UDP routing, that change would result in the connection effectively being dropped, but part of the goal of QUIC is to support that migration without dropping the connection, hence the connection ID. Which means subsequent packets for that connection ID also need to still be delivered to the same worker in envoy.

If I'm understanding correctly now, this means the BPF doesn't really need to be there for the initial connection, because the kernel's UDP handling would already deliver related packets to the same worker consistently, but if the client *does* change address, every packet after that change would [most likely] be routed to an incorrect worker by the kernel and have to be rerouted, if it wasn't for the BPF program.

(This is speculative and I am open to correction, don't take anything I say here as authoritative!)

**Comment by danzh2010** [comment]
> If I'm understanding correctly now, this means the BPF doesn't really need to be there for the initial connection, because the kernel's UDP handling would already deliver related packets to the same worker consistently, but if the client _does_ change address, every packet after that change would [most likely] be routed to an incorrect worker by the kernel and have to be rerouted, if it wasn't for the BPF program.
> 

Correct, BPF is not needed if you infrastructure doesn't use CID for routing but instead use network 4-tuple. But if you want to support connection migration which is a network performance gain as I mention earlier, you will need CID based routing, hence BPF.

**Comment by ohadvano** [comment]
Makes perfect sense now, thanks a lot
