### ISSUE TITLE
Add Vectorscan (same ABI as Hyperscan) for Arm 64

### ISSUE THREAD

**Issue by sambercovici** [envoyproxy/envoy#29276]
*Title*: *Add Hyperscan/Vectorscan to non x86 processors like Arm 64*

*Description*:
https://github.com/envoyproxy/envoy/issues/19376 added hyperscan as a matcher and an optional regular expression engine. 
Hyperscan supports x86 processors and is included only in contib build for intel.

Vectorscan - https://github.com/VectorCamp/vectorscan is a fork of Hyperscan supporting the same ABI for Arm64 and PowerPC 64. Specificaly:
- Arm 64 - ARM NEON/ASIMD and/or  ARM SVE2
- PowerPC 64 - VSX

Either switch to Vectorscan for all supported processors (including Intel), or use Vectorscan for supported non intel processors.

>Describe the desired behavior, what scenario it enables and how it
would be used.
The Hyperscan functionality will be available for all Envoy supported CPU architectures.

[optional *Relevant Links*:]
https://github.com/VectorCamp/vectorscan 

>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
cc @zhxie @soulxu

**Comment by zhxie** [comment]
> Hyperscan supports only intel processors and is included only in contib build for intel.

It is incorrect. Hyperscan supports all x86 processors with SSSE3.

**Comment by sambercovici** [comment]
Feedback would be appreciated.
- Is this something wished for for platforms other than x64/amd64 ?
- Should the feature only use Vectorscan for targets other than x64/amd64 or for all targets?

**Comment by sambercovici** [comment]
@phlax is this of interest? Anyone else from the core team may be interested?
If this feature is needed, we will implement it.

**Comment by phlax** [comment]
codeowners cced above are the best people to ask i think

**Comment by sambercovici** [comment]
@phlax, as far as I see, @zhxie @soulxu work for intel.
Should they care about extending the support for other kinds of CPUs?

**Comment by zhxie** [comment]
Compared to modifying existing components, my suggestion is to add a new extension.

Furthermore, I have concerns about the supply chain security of this component. It appears that this project lacks CI assurance, proper unit testing, Fuzzing testing, and compliance with other Envoy OSS-related policies.

**Comment by soulxu** [comment]
> @phlax, as far as I see, @zhxie @soulxu work for intel. Should they care about extending the support for other kinds of CPUs?

As intel, we aren't interesting other CPUs. For hyperscan, we got the team support, if we move to vectorscan, we won't have any support when something wrong. So it is really hard for us to migration to vectorscan. If anyone has requirement on that and got enough people support that, I think people can just free to add an extension for it.

**Comment by sambercovici** [comment]
Hi @zhxie,
This is proposal is to enable the existing extension for additional CPUs over x64.
This means that for x64 the dependency is kept on Hyperscan.
For aarch64 and other CPUs the dependency will be on Vectorscan.
The envoy extension itself will not change.

@soulxu , I am not asking you/intel to migrate to Vectorscan. 
Please keep the great job you do on Hyperscan and as suggested the x64 builds will use Hyperscan.

**Comment by markos** [comment]
@zhxie Hi, I was requested to comment here in favour of Vectorscan. I am only going to comment on the CI and unit testing. So, as Vectorscan is a direct API/ABI Hyperscan replacement, is based on the same code, it runs the same unit tests (both unit-internal and unit-hyperscan are run). There is an internal CI, jenkins based. It is internal only because we didn't integrate it with Github, but we are currently moving to a different CI, something easier to program than Jenkins and easier to integrate to Github. Even so, our current Jenkins tests x86 (SSE, AVX2, AVX512, FAT), Aarch64 (Neon), PPC64LE (VSX). Each architecture is tested for both debug/release, on multiple gcc and clang versions. Each PR is tested against that if it doesn't pass it doesn't get merged. Unfortunately, we haven't integrated that with github so it doesn't show. So, to answer that, the plan is extend our CI to more configurations, more compilers, a few more architectures, add ASAN testing, and of course make it visible to Github. A new release 5.4.10 is out the door, and a new Debian package will uploaded immediately. The decision to support it is yours of course, I'm just mentioning the current situation.

**Comment by sambercovici** [comment]
@phlax , @soulxu , @zhxie , any additional comments?
If not, may we work on a PR to add VectorScan as the implementation for aarch64 processors?

**Comment by soulxu** [comment]
> @soulxu , I am not asking you/intel to migrate to Vectorscan. Please keep the great job you do on Hyperscan and as suggested the x64 builds will use Hyperscan.

Ok, I see your proposal now. I guess it is same answer, we prefer to hyperscan for x86 build. you are free to do anything for other platform.

**Comment by sambercovici** [comment]
who can tag as "no stalebot"?

**Comment by phlax** [comment]
done

**Comment by sambercovici** [comment]
@soulxu , @zhxie 
Following https://github.com/envoyproxy/envoy/pull/29881#issuecomment-1786455068
What are is the plan for Hyperscan 5.4 LTS since 5.5 and forward will be under "Intel Proprietary License"?
