### ISSUE TITLE
Implementing custom tracer using OTel SDK as envoy filter

### ISSUE THREAD

**Issue by vigchan** [envoyproxy/envoy#29280]
*Title*: *Implement custom OTel tracer as an envoy filter and configure the filter to HttpConnectionManager*

*Description*:
Based off my understanding of envoy's code [here](https://github.com/envoyproxy/envoy/tree/f17f1fdd644cc4b32f65579184757e3975843db6/source/extensions/tracers/opentelemetry), the OTel tracing implementation does not seem to be relying on the C++ SDK. 

I have a use-case where I was planning to write a custom OTel Tracer based off the OTel C++ SDK as an envoy filter, like the [HTTP Filter example](https://github.com/envoyproxy/envoy-filter-example/blob/main/http-filter-example/README.md)
and then configure that as one of the filters to the HttpConnectionManager, exactly the existing tracer as per the [documentation](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/opentelemetry) 

Would the above approach work? Or do I have to make the code changes by forking envoy's codebase?

**Comment by phlax** [comment]
cc @alexanderellis @htuch

**Comment by kyessenov** [comment]
You should be able to add another Otel tracer extension that uses Otel SDK. Is there a reason to use HTTP filter extension point?

**Comment by vigchan** [comment]
The tradeoff here is mainly forking away from envoy codebase v/s writing a filter extension and compiling that with envoy. And then using that with the HTTP Connection Manager. We are anyways building and maintaining a host of HTTP filter extensions on our side. Is that a best practice or an approach that works though?

**Comment by kyessenov** [comment]
The main concern is that tracing has cross-cutting concerns (sampling, span tags) that could benefit from shared Envoy infra used for all tracers rather than making new config for HTTP filters.

**Comment by kyessenov** [comment]
The extension model is the same for tracers and the filters and other components. It's very easy to add or not consume extensions from upstream. In the future, it might be possible to add it to `contrib` or `core` extension in Envoy, depending on its adoption.

**Comment by vigchan** [comment]
Awesome! Thats great to know. Thanks for clarifying and providing pointers. I will proceed that way.

**Comment by htuch** [comment]
@joaopgrassi

**Comment by joaopgrassi** [comment]
Hi @htuch #28929 is about extending the existing OpenTelemetry tracer and add the notion of resource detectors to it, which is a feature of OTel and is also present in the OTel C++ SDK. In a nutshell, we are "replicating" the behavior of the OTel C++ SDK in Envoy since we don't use the SDK in here. 

IIUC @vigchan is trying to do is add a new Tracer that is then using the OTel C++ SDK internally . I did some investigation on how feasible to the same and I hit so many road bumps that I'm not sure it's so easy.  I'm just a noob in Envoy at this point so maybe it's just that, but from my limited time working on the codebase and debugging the trace-related part I feel this comment summarizes it well:

> The main concern is that tracing has cross-cutting concerns (sampling, span tags) that could benefit from shared Envoy infra used for all tracers rather than making new config for HTTP filters.

Even if we have a "extension tracer" that is using the OTel SDK internally, other parts of the Envoy would still not use it, sampling is completely different. My sentiment is that to fully get all the benefits of having the OTel SDK in, would be to completely change how tracing is done in Envoy and _only_ have OTel spans/propagation .Then you can benefit from the multiple propagators OTel offers, Sampling, exporters, span processors and etc. 

I'm not sure I helped with anything but that's my view.

**Comment by htuch** [comment]
Yep, thanks, that makes sense, just noticed a superficial similarity on SDK integration. OK, I'm not sure why we would want to do this then, can we just get the OTel tracer that you are working on to support whatever @vigchan needs?

**Comment by joaopgrassi** [comment]
With the changes I'm working, we will be able to export via HTTP #29207. #28929 will bring support for custom resource detectors, similar as we have in the [OTel collector]([open-telemetry/opentelemetry-collector-contrib@main/processor/resourcedetectionprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor?rgh-link-date=2023-08-23T16%3A00%3A46Z))

The next thing I think I will work on is defining also custom sampler for the OTel Tracer. I think I will use the same idea of the resource detector and use the extension framework in Envoy to allow users to configure a custom sampler, that is then used by the OTel tracer in Envoy. I will create an issue for it today or tomorrow.
