### ISSUE TITLE
Restrict ext_proc service mode_override API to header response only

### ISSUE THREAD

**Issue by yanjunxiang-google** [envoyproxy/envoy#29302]
*Title*: Deprecate ext_proc service mode_override API 

*Description*:

The mode _override service API is used for the external processor to change the processing modes after receiving request from Envoy:
https://github.com/envoyproxy/envoy/blob/29c2a5c49f7ba81a738db018b21c032b578a5069/api/envoy/service/ext_proc/v3/external_processor.proto#L174

This API should be deprecated since it allows the external processing server to change a critical Envoy ext_proc filter configuration: Processing mode 
https://github.com/envoyproxy/envoy/blob/29c2a5c49f7ba81a738db018b21c032b578a5069/api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto#L118

Allowing such configuration change not only make Envoy very vulnerable for attacks, but also make the Envoy ext_proc filter state machine very complicated. For example, if ext_proc filter is configured with STREAME body mode, and mode_override is returned by the ext_proc server when responding one of the body chunks, then the entire data chunks still pending in the queue will have to be handled specifically:
https://github.com/envoyproxy/envoy/blob/29c2a5c49f7ba81a738db018b21c032b578a5069/source/extensions/filters/http/ext_proc/processor_state.h#L75

Also, it does not look to me there is an import use case for this capability.

Thus, I would propose deprecate the mode_override API to let Envoy control this config, and make things simple and clean.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by yanjunxiang-google** [comment]
We previously added a configure API to disable mode_override API. 

If we can deprecate this mode_override API, I would like to clean up the code which is to support this API, like anything related to https://github.com/envoyproxy/envoy/blob/29c2a5c49f7ba81a738db018b21c032b578a5069/source/extensions/filters/http/ext_proc/processor_state.h#L75

Including this while loop: 
https://github.com/envoyproxy/envoy/blob/29c2a5c49f7ba81a738db018b21c032b578a5069/source/extensions/filters/http/ext_proc/processor_state.cc#L254

**Comment by yanjunxiang-google** [comment]
It's a valid use case after seeing headers and response mode_override with SKIP body.

However, since mode_override can be sent in each body response, what's the behavior in the below case?

In STREAMED mode, Envoy sent 5 -> 4 -> 3-> 2 -> 1 five body chunks to the ext_proc server.

After receives 1, ext_proc server send back response and set mode_override to BODY_NONE.

And the ext_proc filter stops to  put any more chunks to the queue here:
https://github.com/envoyproxy/envoy/blob/35a0574dfb90bb22e60436853dc7cb51708764fc/source/extensions/filters/http/ext_proc/ext_proc.cc#L628

The code handles response of 1) well. However,  what's the designed behavior to handle 2, 3,4, 5 in the queue?  it looks to me the code have issues processing those chunks in this while loop:

https://github.com/envoyproxy/envoy/blob/d99027a8bf61f1ddfc498310aabb79092ef1b1b2/source/extensions/filters/http/ext_proc/processor_state.cc#L257


If we forget about the problem in current implemenation, what's the desired behavior for 2, 3, 4, 5? Should Envoy just re-inject them to filter chain?  

Also, what's the behavior for the ext_proc server after they received 2, 3, 4, 5? Should it just silently discard them?

Then Envoy will get gRPC call timeout for each of those chunks: 

https://github.com/envoyproxy/envoy/blob/d99027a8bf61f1ddfc498310aabb79092ef1b1b2/source/extensions/filters/http/ext_proc/ext_proc.cc#L752

And in failure mode allow false case, this is an error condition, and will trigger immediate response being generated and sent to client.  

So, my suggestion is that at least we should restrict this mode_override when Envoy is configured with STREAMED body mode && when there are body chunks already sent to the ext_proc server.  The mode is especially vulnerable to this mode_override since this is the only mode which may have multiple outstanding gRPC calls , where other modes only have at most one outstanding gRPC call.

**Comment by gbrail** [comment]
I’m just catching up to this now, but the ability for a processor to
override the processing mode is key to the functionality of ext_proc and to
how we originally anticipated that people would use it.

The original idea was that we could use ext_proc to implement even complex
API gateways and other similar systems which may look at the headers of a
request and decide based on those headers whether they need to reject the
request, or keep processing, and to decide if they need to intercept the
body or let it pass through. Without the ability to change the processing
mode on the fly, a sophisticated gateway like that would need to be set up
to always consume the entire request and response body even if it was going
to pass them through.

(Basically, I wanted to design this protocol so that we could replace much
of Apigee, which can proxy thousands of APIs and apply different sets of
processing to search.)

This also allows ext_proc to support use cases for service providers such
as multi tenant proxies. For example, imagine that we are building a
service that could potentially front many hundreds or thousands of upstream
services. We might want to decide based on the path or host header what
processing needs to happen.

Now, I could buy the argument that most such products would only need this
capability when processing the request headers, and that we could possibly
only do the override there — that would simplify things a lot.

With all that said, I’m no longer working on any products that might use
ext_proc in this way so perhaps others have more direct experience.

**Comment by yanjunxiang-google** [comment]
Thanks for sharing the detail background!

Based on the above comments,  it looks to me only supporting mode_override in header response seems to be a good compromise. Please confirm.

**Comment by gbrail** [comment]
That may be a great compromise.

I know early on that some of the security tools companies were looking at
ext_proc and I wonder if they would have opinions.

From my perspective, if mode_override only worked in header responses (both
request and response) it would meet the original requirements and reduce a
bunch of error cases.

**Comment by mpwarres** [comment]
+1 to only supporting mode_override in header responses--good idea!
