### ISSUE TITLE
start_child_span config creates spans with the wrong span.kind

### ISSUE THREAD

**Issue by MisterSquishy** [envoyproxy/envoy#29549]
*Title*: *start_child_span config creates spans with the wrong span.kind*

*Description*:
when the [start_child_span](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto#envoy-v3-api-field-extensions-filters-http-router-v3-router-start-child-span) config is set to true, i would expect envoy to emit `router .* egress` spans with the `span.kind` set to `client`. instead, it [copies the parent config](https://github.com/envoyproxy/envoy/blob/d3c384ae5d7f9ea4e72e711e419d218af3e26a17/source/common/router/upstream_request.cc#L99-L102), which has `span.kind` set to `server`

*Repro steps*:
set the [start_child_span](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto#envoy-v3-api-field-extensions-filters-http-router-v3-router-start-child-span) config to true and inspect the emitted spans

**Comment by adisuissa** [comment]
Seems to be a question related to tracing. This feature has been there for a while (since #1931).
cc @mattklein123 @wbpcode as tracing domain experts.

**Comment by wbpcode** [comment]
Hi, which tracer are you using? Different tracers may have different behaviors.

**Comment by MisterSquishy** [comment]
we are using the opentelemetry tracer!

**Comment by wbpcode** [comment]
got it. I think this is a similar problem with previous zipkin. #22987

The tracer could work on two mode:
- work as sidecar of app, the inound sidecar will output server spans and outbound sidecar will output client spans. Both inbount sidecar and outbound composite an independent hop.
- work as independent hop, output server spans for downstream and output client spans for upstream.

Because historical reason, value of `Tracing::OperationName` is mainly depend on the traffic direction and could use it to determine the type of span.

Seems we need a more complete solution to this solution.
