### ISSUE TITLE
how can  I  debug envoy  with vscode devcontainer 

### ISSUE THREAD

**Issue by jason9015** [envoyproxy/envoy#29627]
I use vscode devcontainer  to debug envoy,but fail,Permission denied

[1067 ms] Command in container failed: mkdir -p '/build/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-arm64/8b617bd08fd9e3fc94d14adb8d358b56e3f72314' '/build/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314'
[1067 ms] ln: failed to create symbolic link '/build/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314': Permission denied

env:  Apple M1 Pro    13.5.1
        vscode
        devcontainer

       release/v1.27

**Comment by adisuissa** [comment]
Not sure I understand the problem, but it seems that creating a directory in the docker instance is not allowed. Can you enable permissions for your user in the instance?

cc @phalx - not entirely in your domain, but maybe you know the answer.

**Comment by jason9015** [comment]
What do I need to do?

**Comment by phlax** [comment]
not a mac or vscode user so not immediately clear what the issue is

checking here https://github.com/envoyproxy/envoy/blob/782bb0c102ffbd9880615526c54c00301a6f3f82/.devcontainer/devcontainer.json#L4-L15 it appears to mount the folder `envoy-build:/build` so i would check the permissions on the `envoy-build` folder which i imagine was created by Docker

it seems like when you create the container it automatically sets the permissions (https://github.com/envoyproxy/envoy/blob/782bb0c102ffbd9880615526c54c00301a6f3f82/.devcontainer/setup.sh#L18) so may be rebuilding the container would also fix

**Comment by jason9015** [comment]
let me try it,thank you!

**Comment by jason9015** [comment]
<img width="517" alt="image" src="https://github.com/envoyproxy/envoy/assets/22276078/36a4a674-51ca-49d7-b598-c155ae8eee38">
I user release/v1.27,run .devcontainer/setup.sh,but fail

**Comment by jason9015** [comment]
I also build envoy success,but run tools/vscode/refresh_compdb.sh fail

**Comment by jason9015** [comment]
@phlax  I am an new begineer,can you help me to run debug envoy on mac with vscode

**Comment by phlax** [comment]
im not the right person to ask im afraid - im not a mac user - let me readd triage and the on-call maintainer can find the best people to ping

**Comment by jason9015** [comment]
@phlax thank you very much，can you tell me who  can i call?

**Comment by ggreenway** [comment]
@jason9015 I made a change late last week that should hopefully fix gen_compilation_database.py on mac

**Comment by jason9015** [comment]
Can I use  main branch to try?thank you
