### ISSUE TITLE
Why config is complex and not unmemorable

### ISSUE THREAD

**Issue by efeArdaYildirim** [envoyproxy/envoy#29974]
Hi I intererested envoy it is good but config is yaml and it is wanna proto path in config. It is not memorable, I can't remember never. Why envoy using that syntax? Why not like nginx? Is envoy not for basic jobs doing with config? Is it desined for diffrent using without config file?

**Comment by pxpnetworks** [comment]
Well, I guess Envoy config is not supposed to be read by humans :)

**Comment by zuercher** [comment]
Envoy configs are defined using protobuf objects. The bootstrap config is loaded from yaml format into a protobuf-generated object. 

Envoy is extremely extensible and that extensibility requires configuration. Since extension configurations are defined in protobuf as well, everything is uniform and readily machine-generated. I don't see us defining an alternate format.
