### ISSUE TITLE
Android tests are permafailing CI with diskspace issues

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#30098]
Probably we can add a hack to resolve this - but not sure what we want to remove to free diskspace

**Comment by abeyad** [comment]
hey @phlax , is there a link to the failing jobs?  Is it the kotlin_helloworld one?  I see that one failing a lot (e.g. https://github.com/envoyproxy/envoy/actions/runs/6482932266/job/17603711441#step:5:6859), though the error message seems to be a download timeout (maybe it's timing out b/c it can't download due to no disk space?)

is the diskspace issue on the worker agents?  can we run `du` or something similar to see where the majority of disk space is taken up?  if it's old archives or test logs, i think we can just delete to free up the space

**Comment by abeyad** [comment]
oh nevermind, i see it here: https://github.com/envoyproxy/envoy/actions/runs/6473012784/job/17574833005

**Comment by abeyad** [comment]
can we just `rm` the `/home/runner/runners/2.309.0/_diag/Worker_20231010-175424-utc.log` file?  i'm not sure if i have login credentials to do so myself..

**Comment by abeyad** [comment]
sorry, i meant `rm /home/runner/runners/2.309.0/_diag/`

**Comment by phlax** [comment]
yeah here is the ci log of fail https://github.com/envoyproxy/envoy/actions/workflows/mobile-android_tests.yml?query=branch%3Amain

re resolution - we have a toolshed action (`git grep actions/diskspace`) it has a parameter to tell it what to remove - it maybe the defaults remove stuff that is wanted - not sure

re _diag - not sure about that - re login it needs to be set in ci (not sure iiuc)

**Comment by phlax** [comment]
like in existing code

https://github.com/envoyproxy/envoy/blob/d5cf0c33430d858eba46eed2028e93ef5618b154/.github/workflows/codeql-push.yml#L28-L32

you may want to _not_ remove what that is removing - the defaults are here https://github.com/envoyproxy/toolshed/blob/b974b20fbf9a2436c5c8643d5dfc6fdfcbbfe024/gh-actions/diskspace/action.yml#L2-L7

im not sure what is actually used by this ci - if it uses the build container then just remove the lot (ie use default)
