### ISSUE TITLE
bind to port ranges

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#3010]
Similar to https://github.com/envoyproxy/envoy/issues/1411 we have a need to be able to specify port range valid for binding.  Something like "bind to some port between 1000-2000 for [various traffic steering reasons]

Unless anyone objects I'd suggest we do the ugly-but-working method of changing our current "best effort bind to this address" to "really best effort try a couple of ports in the specified range"

**Comment by curiouserrandy** [comment]
Does you think it make sense to include as part of this a DB of some sort tracking what addresses are already in use by the envoy instance, so that it doesn't waste time colliding with addresses it's already bound?  Or will this code be executed often enough in a context where the port namespace is shared with other processes that the extra complexity won't be worth it?

**Comment by alyssawilk** [comment]
I think the latter is likely enough that the extra complexity is probably not worth it.  Plus it can't hurt to start simple - we can always enhance later :-)
