### ISSUE TITLE
go mod vendor on golang http filter: `#cgo noescape envoyGoFilterHttpCopyHeaders`

### ISSUE THREAD

**Issue by Meshkati** [envoyproxy/envoy#30208]
*Title*: *go mod vendor on golang http filter: `#cgo noescape envoyGoFilterHttpCopyHeaders`*

*Description*:
When I try to locally develop on golang http filter example of the repo ( ./examples/golang-http/simple ), I get this error:
```
internal error: failed to find embedded files of github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http: /Users/seyed/go/pkg/mod/github.com/envoyproxy/envoy@v1.27.1-0.20231013215548-11bb91e1b192/contrib/golang/filters/http/source/go/pkg/http/cgo_go122.go: invalid #cgo line: #cgo noescape envoyGoFilterHttpCopyHeaders
```

*Repro steps*:
```
./envoy/examples/golang-http/simple
go mod tidy
go mod vendor
```

**Comment by spacewander** [comment]
It seems the `go:build` tag is ignored by  `go mod vendor`. I will try to figure out why.

**Comment by spacewander** [comment]
Commands such as go mod vendor and other commands currently parse the import statements in all Go files to determine which packages. By definition, this ignores build directives, because one wants to vendor all dependencies in all build configurations.

Here is an ongoing issue to adjust this behavior: https://github.com/golang/go/issues/42504.

Unfortunately, the `#cgo` directive need to be put above the `import "C"`, so we can't workaround it by moving the unsupported syntax under `import`.

**Comment by Meshkati** [comment]
So the current solution is to not vendor it and use the modules from `GOPATH`. Thanks.

**Comment by doujiang24** [comment]
Since we introduced the new syntax in Golang: https://github.com/golang/go/pull/60399, which is a performance optimization.
It will be released in go 1.22, so we buildtag on go 1.22 here.

Maybe we can remove this `cgo_go122.go` file temporarily, and add it back after go 1.22 is released.
WDYT @spacewander

**Comment by spacewander** [comment]
LGTM.
Only one tiny thing, unless Go provides a way to recognize the build directive (like the discussion in https://github.com/golang/go/issues/42504), we can't add the file back until we no longer support Go < 1.22, not just after Go 1.22 is released. Otherwise, running `go mod vendor` with Go < 1.22 won't work well.

**Comment by doujiang24** [comment]
yep, I think that's acceptable, we already require Go 1.20 for now.
