### ISSUE TITLE
`//test/extensions/filters/http/ext_proc:streaming_integration_test` is flakey 

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#30227]
This is probably our worst current flake - its failing ~1/10 on postsubmit. and regularly fails on pre

It would be very good if we could resolve this issue before cutting the 1.28 release

```console
[ RUN      ] StreamingProtocols/StreamingIntegrationTest.PostAndProcessStreamedRequestBody/IPv4_EnvoyGrpc_WithDeferredProcessing
test/extensions/filters/http/ext_proc/streaming_integration_test.cc:292: Failure
Value of: client_response_->headers()
Expected: http status is "200"
  Actual: 24-byte object <40-16 EA-01 00-00 00-00 38-1B EA-01 00-00 00-00 B0-1B EA-01 00-00 00-00> (of type Envoy::Http::ResponseHeaderMap), which has status code 500
Stack trace:
  0x1db2be4: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x1db2a84: testing::Test::Run()
  0x1db3bd4: testing::TestInfo::Run()
... Google Test internal frames ...

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=152542&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=67a76341-37f4-5b49-db38-acbb8a59af82&l=776

**Comment by phlax** [comment]
This appears to be the same issue as https://github.com/envoyproxy/envoy/issues/29625

not sure if it wasnt fixed or came back

**Comment by yanjunxiang-google** [comment]
I will take a look

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by yanjunxiang-google** [comment]
https://github.com/envoyproxy/envoy/pull/30253

**Comment by phlax** [comment]
removing from milestone but leaving open to track rare remaining issues

**Comment by yanjunxiang-google** [comment]
There is a problem to run concurrent test for ext_proc:streaming_integration_test:
"
bazel test --runs_per_test=1000   test/extensions/filters/http/ext_proc:streaming_integration_test 
"

The test sometimes fails (~0.1%) due to some weird/unexpected downstream request message is received by Envoy listener.   From the log dumping, such unexpected downstream request message seem to be the message Envoy is trying to forward to the ext_proc server.  How that is possibly sent to an Envoy listener?

So the root cause is that the test_processor_, i.e, the test ext_proc server, its port number is assigned by the ServerBuilder, which is completely independent of the Envoy integration test framework port assignment scheme.    So, it is possible the test_processor_.port() collides with the Envoy listener port. If that happens, then when ext_proc filter tries to send the header/data to test_processor_,  it is actually sent to the Envoy listener, and goes through the HTTP filter chain and ext_proc filter again. Such unexpected request message is causing test failure.

BTW, during the debugging, it is not that easy to reproduce the case that in one test, the test_processor_.port() collides with the Envoy listener port. However, it is not too difficult to reproduce it with:
"
bazel test --runs_per_test=1000   test/extensions/filters/http/ext_proc:streaming_integration_test 
"
The reason is that with --runs_per_test=1000, multiple concurrent threads are created and each test its own cases. And somehow there are two threads with one's test_processor_.port() collides with the other's Envoy listener port.   So we can see from the logs that one thread just started Envoy and main dispatcher loop ready. Its client is not sending any request message yet. However it receives a request message from another thread. 


Solution of this issue:

It looks to me the only thing we can do to completely fix the flakiness of this test is to move these tests to unit test and getting rid of the test_processor_.  

We can not using the integration test framework as in ext_proc_integration_test.cc for STREAMED mode since if client sends 100 chunks of body,  there is no way for Envoy to know how many chunks will be received by Envoy ext_proc filter. That chunk number is non-deterministic due to Envoy codec buffering.   

The draw back to convert these streaming integration tests into unit test is that we lost the benefit the integration test provides us----- the end-to-end test.

**Comment by phlax** [comment]
>  its port number is assigned by the ServerBuilder, which is completely independent of the Envoy integration test framework port assignment scheme. So, it is possible the test_processor_.port()

cc @ravenblackx 

@yanjunxiang-google that seems to fit with the fail being on arm

**Comment by yanjunxiang-google** [comment]
@phlax  yeah, I think we should convert these into unit test. There is a port number assignment collision problem in these tests.

**Comment by yanjunxiang-google** [comment]
@jmarantz

**Comment by phlax** [comment]
i think @ravenblackx has a couple of tricks for this

**Comment by gbrail** [comment]
This is brilliant troubleshooting -- thanks!

I remember working pretty hard to figure out a way to get random ports for
tests and also to make it work in test environments only with IPv4, only
IPv6, etc.

I also recall that getting a test environment to test all the nuances of
the protocol and get all the test coverage was tricky, hence the separate
port for these particular tests. If you can figure that out, then great,
but I'd think that trying to resolve the port conflict might be the best
way.

**Comment by yanjunxiang-google** [comment]
> @yanjunxiang-google Thanks for deep dive into this.
> 
> If root cause is port collision, I am just curious if it is possible for `test_processor_.port()` to avoid such collision (probably not as you mentioned that they are completely independent). Or even simpler, can we skip such test run(as succeed) if we can detect such collision in the test.
> 
> I am just brainstorming here from a quick look, other folks probably have some ideas.


It might be possible to detect collision if within one test thread the test_processor_.port() collide with the Envoy listener port. However, it is impossible to detect such collision when run:
bazel test --runs_per_test=1000 test/extensions/filters/http/ext_proc:streaming_integration_test

The test_processor_.port() number in one test instance is not known to the other test instance, which is running in parallel.

**Comment by ravenblackx** [comment]
I didn't have a solution for *guaranteed* avoiding port collisions, but my workaround is pretty good for *very likely* avoiding port collisions; instead of `127.0.0.1:[rand]` use `127.[rand].[rand].[rand]:[rand]`, reducing the chance of collision by a factor of 16 million.
(As used in python [here](https://sourcegraph.com/github.com/envoyproxy/envoy/-/blob/test/integration/hotrestart_handoff_test.py?L22-26).)

**Comment by yanjunxiang-google** [comment]
That's a good info. However, the test_processor_ here is implemented from grpc::ServiceBuilder.  I am not sure we can manipulate the IP:port.  We need some help here.
