### ISSUE TITLE
`//test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy:dynamic_forward_proxy_filter_integration_test` is very flakey

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#30313]
This appears to be a new issue possibly introduced in https://github.com/envoyproxy/envoy/pull/30270

its flaking pretty hard on main (and i guess presubmit)

we will want to backport any resolution to the `release/v1.28`  branch

```console
[ RUN      ] IpVersions/DynamicForwardProxyIntegrationTest.BasicFlow/IPv4
test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter_integration_test.cc:155: Failure
Value of: fake_upstreams_[0]->waitForUdpDatagram(request_datagram)
  Actual: false (Timed out waiting for UDP datagram.)
Expected: true
Stack trace:
  0xacf7d5: (unknown)
  0x7f81c818631d: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x7f81c816d09e: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x7f81c815499d: testing::Test::Run()
  0x7f81c815548e: testing::TestInfo::Run()
... Google Test internal frames ...

```

https://dev.azure.com/cncf/envoy/_build/results?buildId=152986&view=logs&j=4930ecaf-18f4-5b3c-dea3-309729c3b3ae&t=573d8780-d7b9-52e3-b4e0-a89886b0b9ff

**Comment by yanavlasov** [comment]
#30270 is not the reason for flakiness of //test/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy:dynamic_forward_proxy_filter_integration_test

the test can not possibly trigger premature reset protection since there is no HCM, the code that #30270 is not running in this test.

There is an inherent race condition in this test, as it checks for the main thread to complete DNS resolution. The main thread still has to dispatch to the worker and allow the second request to succeed. This may not always be the case on since the test oversubscribes CPU.

**Comment by yanavlasov** [comment]
Giving the test more CPU reduces the flakiness quite considerably. But the test needs to be adjusted to solve its inherent flakiness.

**Comment by phlax** [comment]
duplicate of https://github.com/envoyproxy/envoy/issues/30303
