### ISSUE TITLE
gRPC JSON Transcoder: Allow custom type URL when transcoding Any type

### ISSUE THREAD

**Issue by rickardb** [envoyproxy/envoy#30350]
gRPC JSON Transcoder: Allow custom type URL when transcoding Any type

If the upstream gRPC service returns a proto message packed in an Any type with a custom type URL the filter will fail to transcode this returning to the downstream
```
Invalid type URL, type URLs must be of the form 'type.googleapis.com/<typename>', got: xxx/yyy
```

Proposal: Allow configuration of additional type urls which can be used and included in the proto file descriptor set.

The type helper is hard-coded to `type.googleaips.com` here https://github.com/envoyproxy/envoy/blob/dc841d18fd45ff8043dcc0d3bb9e7f8e84768d55/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc#L152

**Comment by kyessenov** [comment]
CC @nareddyt 

I haven't seen non type.googleapis.com types yet, where can I learn more about the other registries?

**Comment by rickardb** [comment]
We have a set of custom error details that we use in our platform. They are derived from the [google ones](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) but are adapted to our needs. 

We pack these in the `details` field of a [Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) proto and would thus like to have them transcoded by the proxy layer in the platform. Both in the scenario where they are returned as trailers but also in the response message - we have a similar system that does admission control where we in the [CheckResponse](https://github.com/googleapis/googleapis/blob/master/google/api/servicecontrol/v2/service_controller.proto#L161) returns a `Status` message.

**Comment by jacobk** [comment]
Adding to the above. Practically, using the Java grpc libs, we use custom `typeUrlPrefix` when we `pack` our `Any`s. For example:

```kotlin
    Status.newBuilder()
        .setCode(code.number)
        .setMessage(message)
        .apply { details?.let { addDetails(Any.pack(details, "<our-platform-name>")) } }
        .build()
```

The reasons for doing so are:
* Partly aesthetics, using (the default) `type.google.com`, leads to a lot of mentions of google that has caused some confusion
* Governance, we wanted to make sure that we can control and document which types are expected to show up
* What does it mean to use the default `type.google.com/XXX` outside of a Google context?

From `any.proto`

>   // A URL/resource name that uniquely identifies the type of the serialized
>   // protocol buffer message. This string must contain at least
>   // one "/" character. The last segment of the URL's path must represent
>   // the fully qualified name of the type (as in
>   // `path/google.protobuf.Duration`). The name should be in a canonical form
>   // (e.g., leading "." is not accepted).
>   //
>   // In practice, teams usually precompile into the binary all types that they
>   // expect it to use in the context of Any. However, for URLs which use the
>   // scheme `http`, `https`, or no scheme, one can optionally set up a type
>   // server that maps type URLs to message definitions as follows:
>   //
>   // * If no scheme is provided, `https` is assumed.
>   // * An HTTP GET on the URL must yield a [google.protobuf.Type][]
>   //   value in binary format, or produce an error.
>   // * Applications are allowed to cache lookup results based on the
>   //   URL, or have them precompiled into a binary to avoid any
>   //   lookup. Therefore, binary compatibility needs to be preserved
>   //   on changes to types. (Use versioned type names to manage
>   //   breaking changes.)
>   //

From a non-google perspective the above is pretty ambiguous wrt. to the expected behavior of the `type_url`. E.g. supporting HTTP GET etc.

>   // Note: this functionality is not currently available in the official
>   // protobuf release, and it is not used for type URLs beginning with
>   // type.googleapis.com. As of May 2023, there are no widely used type server
>   // implementations and no plans to implement one.

It doesn't seem this should be treated as a URL outside of google ;)

>   //
>   // Schemes other than `http`, `https` (or the empty scheme) might be
>   // used with implementation specific semantics.

We've opted for this. Our `type_url` currently use the empty scheme.


Lastly, the Java libraries allow to register custom type registries for `JsonFormat` when creating a parser (using `usingTypeRegistry(...)`). This is the closest thing we've come to talking about registries ;)

Some of code we've found just seems to split the `type_url` by `/` ignoring the type when trying to resolve fully qualified message types against the corresponding descriptors. E.g. https://github.com/protocolbuffers/protobuf/blob/77aa913e689304329b6e3df71eea9944acfbc62f/java/core/src/main/java/com/google/protobuf/TypeRegistry.java#L60-L66

@kyessenov , when you talk about "registries", what does a registry signify for you?
