### ISSUE TITLE
Override filter configs using configs retrieved from dynamic_metadata

### ISSUE THREAD

**Issue by rakeshdatta** [envoyproxy/envoy#30539]
*Title*: *Making filter configs dynamic*

*Description*:
Hello, much like this ask I had in the past https://github.com/envoyproxy/envoy/issues/28194
I see some of the filters support fetching the filter config dynamically from the dynamic metadata.

We need this capability in many other filters, to support a multi-tenant envoy config, where one filter (filter A) determines the tenancy and passes the tenant specific config to the next filter (filter B), using dynamic metadata. And the filter B is able to pick those configs from the dynamic metadata and override the static configs it has.

I am wondering if we could enhance all the filters to use this standard data exchange pattern and overriding the static config. If yes, can there be one common change that could take care of this requirement in all the filters, rather than we going and changing the code for every filter. Else is it fine to implement this feature in one filter at time (as needed) and upstream the changes?

[optional *Relevant Links*:]
(https://github.com/envoyproxy/envoy/issues/28194)

**Comment by alyssawilk** [comment]
cc @kyessenov

**Comment by rakeshdatta** [comment]
Hello @kyessenov Could you please look into my above query. Thanks

cc @alyssawilk , @mattklein123

**Comment by kyessenov** [comment]
I think the generic way might be too powerful, since you are essentially asking for xDS configured on-demand by the clients. There might be some limited form of this that works (e.g. there's a library of templates that the main xDS offers that is then instantiated on-demand), but that work certainly needs a proper design doc.

Today, most of the config is explicit and centrally controlled which simplifies the operations. You can achieve what you want on a case-by-case basis with per-filter dynamic overrides via metadata or filter state. The settings for these overrides are documented [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/advanced).

**Comment by rakeshdatta** [comment]
Thank @kyessenov 

Not sure if I understand the 1st paragraph completely. 

My custom filter (filter_A in the filter chain) is taking help of a bootstrap extension, which in-turn using a xDS like protocol, to retrieve connection/downstream_client specific filter_B(next one in the filter chain) ) properties from the control plane. On receiving a connection, based on the connection properties, I am able to get the dynamic overrides for filter_B, from the bootstrap extension database. That's not an issue. 

The issue is how to make the filter_B (which is all the built-in filters) consume those dynamic overrides.

Thanks for confirming in the 2nd paragraph, that using dynamic_metadata/filter-state is an accepted approach. I could implement the changes on a case-to-case basis and try to upstream it. Meanwhile, if you have any other suggestions in mind, plz do share. Thanks.
