### ISSUE TITLE
External Processing support with VCL Socket Interface

### ISSUE THREAD

**Issue by BenAgai** [envoyproxy/envoy#30590]
Hi,
I encountered Envoy's integration with VPP using VCL Socket Interface.
I wanted to ask if Envoy's External Processing mechanism is supported when using VCL Socket Interface?

-) VCL Socket Interface
https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/vcl

-) External Processing
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_proc_filter

Thanks,
Ben Agai

**Comment by lizan** [comment]
@florincoras @KfreeZ

**Comment by florincoras** [comment]
Hi @BenAgai. I've never tried it but, assuming ext_proc_filter does not rely on socket apis not supported by vcl and that vpp is configured with the right routes, it should work fine. That is, the socket interface implementation should be transparent to an http filter.

**Comment by BenAgai** [comment]
Hi @florincoras,
Thanks for the response.

Where can I verify if ext_proc_filter relies on socket APIs not supported by VCL?
In addition, do you have any documentation of the tests done on Envoy's integration with VCL?

Thanks

**Comment by florincoras** [comment]
Hard to say if any of the apis are not properly supported. The vcl socket interface implements them all, so the best option would be to test the integration with real traffic. 
You can find a rather old presentation of the work done to support the integration [here](https://wiki.fd.io/images/0/08/Using_vpp_as_envoys_network_stack.pdf). There's no CI testing for the extension because it would involve running vpp however vcl sockets in combination with http router/filters is constantly tested. In open source, we might add a simple test in vpp's CI sometime soon.

**Comment by BenAgai** [comment]
I see.
Good to know that some cases are constantly tested.
I will continue with the relevant tests.
Thanks @florincoras
