### ISSUE TITLE
Support ASKING command on server side redis_proxy filter

### ISSUE THREAD

**Issue by deveshkandpal1224** [envoyproxy/envoy#31024]
*Title*: Support ASKING command on server side redis_proxy filter

In our setup we use `redis_proxy` filter on server side so that we can use `key_formatter` [feature](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/redis_proxy/v3/redis_proxy.proto#:~:text=%3A%20%5B%5D%2C%0A%20%20%22-,key_formatter,-%22%3A%20...) to format incoming redis keys before sending it to backend node. 

On client side we are not using `redis_proxy` filter, but the application has built in redis-client. 

Redis is running in cluster mode, so in an event when hash slot migration is happening from node A to node B , client is still issuing request to nodeA as expected. However, incase if the key has been migrated already to nodeB from the slot undergoing migration, the client receives an `ASK` redirection from the redis backend. As a result, the client then issues an `ASKING` command, however `redis_proxy` on server side returns `invalid request` today because of [this](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/redis_proxy/command_splitter_impl.cc#L662-L666) block of code.

Would it make sense to explicitly handle `ASKING` command in this case to respond with an `OK` response ?

**Comment by deveshkandpal1224** [comment]
@mattklein123 - this is regarding this particular [PR](https://github.com/envoyproxy/envoy/pull/30871). Appreciate your time!

**Comment by ramaraochavali** [comment]
@mattklein123 @HenryYYang and others whoever is familiar - When redis cluster is used in Envoy, Is server side (redis cluster) using Envoy in your deployments? I assume NOT, otherwise you would have run in to this issue. Curious, how you solved it? Is redis cluster only being used from client side (connecting to some cloud provider cache like Elastic Cache)? One option I can think of is moving the server side to TCP - so we do not run in to this issue, but we loose the key formatter behaviour - Curious how people are handling this deployment model

**Comment by mattklein123** [comment]
All the use cases that I know of use it on the client side. It would have never occurred to me to use it server side but if there is a use case that is fine. However, I think this is broken client side. Maybe this needs to be config driven? I'm not sure. At the very least it needs more documentation to discuss the server side use case?

**Comment by ramaraochavali** [comment]
> However, I think this is broken client side. Maybe this needs to be config driven?

Yes. I think the client side should be fixed irrespective of this if it is broken. Regarding the server side, we can enable it either via config - may be we should have generic config that says it is `server` proxy so that we can add similar features in future. I agree on updating doc to describe more about server side use cases
