### ISSUE TITLE
Regarding shared library of envoy api and envoy api dependencies

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [envoyproxy/envoy#31216]
I am using envoy 1.26.4 version. 
Is there any bazel command through which we can make *.so kind of c++ shared library using bazel/Cmake command that can be loaded inside c++ project and we can call envoy api?

**Comment by soulxu** [comment]
@Gaurav0411GitHub the Envoy API means to xDS API? or you just want to add extension to Envoy?

**Comment by Gaurav0411GitHub** [comment]
We are using c++ based control plane api so how can we make shared library of control plane api's? 
how can we use c++ based xDS Api in envoy 1.26.4

**Comment by Gaurav0411GitHub** [comment]
I am looking for the steps to integrate with envoy 1.26.4  xDS APIs for my c++ project. So how can I integrate my c++ project with xds api's

**Comment by soulxu** [comment]
cc @adisuissa @htuch

**Comment by adisuissa** [comment]
Not sure I fully understand the question, but I'll try to give an answer.
Envoy has all its xDS APIs defined using protos. These protos can be linked to a project, and protobuf can create a C++ class which allows accessing the messages/fields using classes/methods.
If all you need is the protos, the [data-plane-api](https://github.com/envoyproxy/data-plane-api) repo may be useful.

Envoy mainly uses Bazel to build its files. Specifically to link a proto library to a c++ file, the dependency must be inclueded ([example](https://github.com/envoyproxy/envoy/blob/b18ea4488a540aaab4979aea7ebeb252b77d4fe7/source/extensions/filters/http/compressor/BUILD#L24)). Then, the c++ code can access messages/fields that are defined in the proto ([example of c++ code](https://github.com/envoyproxy/envoy/blob/b18ea4488a540aaab4979aea7ebeb252b77d4fe7/source/extensions/filters/http/compressor/compressor_filter.cc#L81) accessing a [proto field](https://github.com/envoyproxy/envoy/blob/b18ea4488a540aaab4979aea7ebeb252b77d4fe7/api/envoy/extensions/filters/http/compressor/v3/compressor.proto#L39)).

**Comment by Gaurav0411GitHub** [comment]
Thanks for your reply
I want to make a c++ shared library of control plane api (envoy api, envoy api dependencies) let's call it as libcontrolplaneapi.so so that I can fill these api from my c++ code like you are filling in the below file
https://github.com/envoyproxy/envoy/blob/ac5792e1da4c966656f4afc7a184fb39644f24fb/test/config/utility.cc#L1020
So I need the below help from your side
1. If We can create libcontrolplaneapi.so using bazel, how and where I can get libcontrolplaneapi.so? so that I can load libcontrolplaneapi.so into my c++ code.
2. If We can't create libcontrolplaneapi.so using bazel, Please let me know the steps to create libcontrolplaneapi.so on linux platform

**Comment by Gaurav0411GitHub** [comment]
Kindly help in the above matter

**Comment by Gaurav0411GitHub** [comment]
Kindly help in the above matter so that we can make shared library of envoy api

**Comment by adisuissa** [comment]
Sorry, I don't understand what you are trying to achieve.
The APIs are protobuf files, and you should be able to use the protoc compiler to generate the corresponding C++ code to access the API messages and fields. See more info [here](https://protobuf.dev/).
You should be able to execute the protoc compiler on any `.proto` file that exist in the [API](https://github.com/envoyproxy/envoy/tree/main/api/envoy), and then add these files to your project.
I don't think that Envoy needs to publish a shared-library to access the API.

**Comment by Gaurav0411GitHub** [comment]
Yes you understood correctly that I want to make shared-library to access the envoy API.
I have used protoc compiler to generate the c++ source files and header files but when I am creating shared library by including those source files and header files that is giving error which are mentioned in the below ticket
https://github.com/envoyproxy/envoy/issues/30637
So as we want to use envoy api from c++ project. Other repositories have redirected to envoy that envoy should provide a document/steps to create shared library from envoy repository.
So here it is kind request to provide help in creating such kind of shared library

**Comment by adisuissa** [comment]
I guess that if your project used bazel it could "build" the relevant protos.
Unfortunately I don't think we have the bandwidth to create a shared library for the API files.
Maybe @phlax has a different idea.

**Comment by Gaurav0411GitHub** [comment]
I am not expecting you to build shared library for the API files.
If you can share the steps of bazel to build all envoy api, envoy dependencies(gRPC, google api's, protobuf) so that i should not get error like which I have reported in ticket 30637

**Comment by phlax** [comment]
@Gaurav0411GitHub the best way to figure out how to do you what you want is to learn how to use bazel and more specifically familiarize yourself with how Envoy uses it.

there are a few different targets within the codebase that build or expose compiled/collected/colated resources for the api

these targets can be seen by either looking at the api targets in `ci/do_ci.sh` and tracking through the bazel, or following the binary build to see what that is doing

also worth looking at some of the related api projects to see what they build - some are better maintained than others

learning how to use bazel's `query/cquery` is pretty important as that will let you track relationships between different parts of the codebase without having to track through build files

bazel automatically handles dependencies - familiarizing yourself with the tools should allow you to either build what you want with bazel or translate to whatever build system you intend to use

as suggested here https://github.com/envoyproxy/envoy/issues/30637#issuecomment-1787811419 you need to ensure you are building with both compatible deps _and_ any required compiler flags/setup

doing this with envoy's build environment (docker/bazel) is the easiest path to building anything, and the supported way

if you are not building with that tooling, then they are at least the reference for how to do so otherwise

**Comment by Gaurav0411GitHub** [comment]
I have created my own container on rocky linux and I have downloaded envoy 1.26.4 code base and trying to build shared library of envoy api's, envoy api's dependencies

**Comment by Gaurav0411GitHub** [comment]
Please let me know just the target name of envoy api and envoy api dependency I will try to build using bazel
