### ISSUE TITLE
Subset load balancer: Add a fallback policy that uses priority/locality weighting

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#3123]
*Title*: *Subset load balancer: Add a fallback that uses priority/locality weighting*

*Description*:
Currently subset load balancing and priority/locality load balancing are mutually exclusive for a cluster. However, I have a use case where I would like to allow client either to select subsets via HTTP headers, or to elide the headers and follow priority and locality load balancing rules.

Currently the closest I can get to that is to use the ANY_ENDPOINT fallback policy, but my understanding of the docs is that it will give all hosts in the cluster an equal weighting, which isn't what I want.

I can get around this requirement by doubling the number of clusters I have and having one for subset load balancing and one for priority/locality load balancing, however I'd rather avoid that if possible.

**Comment by mattklein123** [comment]
IIRC lack of support in the subset LB for priority/locality is a "known issue." @zuercher can probably SWAG out the effort to implement. cc @htuch

**Comment by htuch** [comment]
I think there is a design level issue here. See https://github.com/envoyproxy/envoy/pull/2892#issuecomment-377061603.

**Comment by mpuncel** [comment]
That comment totally makes sense, it's unclear how to combine metadata selection and locality weights in a sane way per request. In fact, in my use case I WANT specifying metadata to override locality weights (it means the client knows where they want the request to go).

I'm not sure if this is any easier to implement, but what i'm interested in is either being able to fall back to locality weighted balancing when there is no metadata match (e.g. when no metadata is passed at all) or be able to explicitly disable the subset load balancer via a route. Basically I want my clients to be able to set an HTTP header to express "send the request to X locality" but also omit it to get weighted balancing.

That would halve the number of clusters in CDS (right now i have like `foo-cluster` and `foo-cluster-subset` for every upstream service)

**Comment by snowp** [comment]
@htuch What do you think about adding a config option that enables the naive solution to blindly apply locality lb weights regardless of subset size? A smarter weight assignment strategy could be added later on, configured separately. 

To prevent people from running into the potential pitfalls you mentioned in your comment we could add a warning to the docs explaining it. 

We have a use case where all our subsets are one or more complete localities, so we'd never run into the issue of a subset match causing unbalanced localities. We're currently modeling these subset as different clusters with the same hosts using the locality lb (since we need locality weights), so being model this as a single cluster using subset lb would be super helpful for us.

**Comment by mattklein123** [comment]
@zuercher do you mind weighing in here?

**Comment by htuch** [comment]
@mpuncel I think having fallback to locality would be relatively clean, if it's not hard to implement it seems this could be one reasonable thing to do.

@snowp I'd be inclined to support this, but we really need some very explicit user documentation explaining the different corner cases and how load can behave strangely.

@zuercher ping again :)

**Comment by zuercher** [comment]
I think good documentation is sufficient for now.

It might be possible to extend LRS to report separate stats for the subsets (along with their identifying metadata, I suppose). That might make it possible to for the management server to make more useful decisions about locality weights in the presence of subsets.
