### ISSUE TITLE
Custom TCP proxy filter to split database read write traffic

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31272]
We want to distribute the traffic among backend endpoints based on some properties of the packets. Is there any existing support in envoy to achieve this?
The decision to select a backend/endpoints may be taken from some L7 filters like- Postgres filter.

**Comment by lambdai** [comment]
It's not a low hanging fruit.

For one thing, tcp proxy selects the cluster right after connection establishment and before any bytes are read.
Your traffic attributes seems from the stream payload so these attributed cannot participate the cluster selection.

The cluster/endpoint selection is limited
1. ClusterSpecifierPlugin is not introduced in TCP proxy yet
2. TCP_proxy [metadata_matcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#envoy-v3-api-field-extensions-filters-network-tcp-proxy-v3-tcpproxy-metadata-match) support only static metadata. The metadata need to be known by config update which is before request serving

**Comment by wbpcode** [comment]
It's supported by HTTP proxy. You can extract some attributes from traffic and store them into dynamic matadata with namespace `envoy.lb`. And then you can configure the backend cluster with a subset lb which could select a subset of endpoints by the attributes under `envoy.lb` of dynamic metadata.

**Comment by wbpcode** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets

**Comment by cpakulski** [comment]
For postgres/mysql protocols, which rely on long-lived TCP sessions this would be very difficult. As I explained on slack, and @lambdai pointed it out as well, upstream TCP connection is established immediately after accepting TCP from downstream client. Those two TCP sessions stay up until the client logs out. 

In order to do what you want, you would have to keep the TCP connection from downstream client open and initiate upstream TCP connection whenever a new request from downstream arrives and close that upstream connection after receiving response from the server. You could initiate that connection to different endpoint based on packet characteristics. But that is not only TCP. Connection to the upstream server requires login and maybe TLS encryption. All that is hard to do.

The other option would be to have several opened upstream TCP connections, and choose one based on packet characteristics. You would need many-to-one relationship. One downstream connection and many upstream connections. You would have to go through postgres login process to each of those endpoints. That mechanism does not exist today and is also not trivial to add.

**Comment by shiponcs** [comment]
Thanks @lambdai, @wbpcode and @cpakulski

**Comment by shiponcs** [comment]
> The other option would be to have several opened upstream TCP connections, and choose one based on packet characteristics. You would need many-to-one relationship. One downstream connection and many upstream connections. You would have to go through postgres login process to each of those endpoints. That mechanism does not exist today and is also not trivial to add.

We've been doing R&D and successfully made one-downstream-two-upstream connection possible. Now, maybe, it is time to explore how to control those connections.
