### ISSUE TITLE
Support soft failure flag when CRL is enabled

### ISSUE THREAD

**Issue by ll78912** [envoyproxy/envoy#31320]
Support soft failure if CRL is enabled

*Description*:
Currently Envoy only supports hard failure modes when CRL is enabled, which can be quite restrictive in environments where temporary network issues or CRL accessibility problems occur. All services in our clusters running with short lived tls certificates and there is a process to refresh tls certificates at regular intervals. This proposed feature is crucial in our production environments, where thousands of services are running with plans to enable CRL check. We aim to initially enable a soft failure mode to monitor for any potential issues, before transitioning to a hard failure approach. This gradual implementation strategy will allow us to ensure stability and reliability across our services.

**Comment by wbpcode** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
Can you elaborate on the exact behavior you mean by "soft failure"?

**Comment by ll78912** [comment]
@wbpcode: Based on our research and experiments, we have identified that the Envoy CRL check can cause TLS verification to fail under the following circumstances:
1. TLS verification fails if any CRL (Certificate Revocation List) required for the TLS certificates is missing, even when the certificate has not been revoked.
2. TLS verification fails if the CRL has expired.
3. TLS verification also fails if the CRL indicates that the certificate has been revoked.

Note under 3, envoy's error message returned is inconsistent:
1. when client has revoked certificates in CRL, we get `SSLV3_ALERT_CERTIFICATE_REVOKED` error from server
2. when server has revoked certificates in CRL, we get `CERTIFICATE_VERIFY_FAILED` error from server
 
Our CRL validation context for both downstream and upstream connection:
```
validation_context:
   crl:
      filename: "/etc/test_crl.crl"
   only_verify_leaf_cert_crl: false
```
Soft failure behavior:
If soft failure mode is enabled, tls should not fail due to CRL check under any of the 3 situations above. Instead, proper alert messages can be logged by envoy such as `SSLV3_ALERT_CERTIFICATE_REVOKED`.

This feature is extremely helpful for use to test out our CRL refresh logic in production as we are using short-lived tls certificates.

**Comment by ggreenway** [comment]
Got it; so you want to test if there would have been any failures before enforcing. That makes sense.

Feel free to put together a PR for this.

**Comment by ggreenway** [comment]
@davidben I could use some advice on the best way to implement this against BoringSSL. Envoy currently does `X509_STORE_set_flags(store, X509_V_FLAG_CRL_CHECK)` to enable CRL checking.

We'd like to be able to get notified of a CRL failure, but not actually fail `X509_verify_cert()`, and not stop verifying other criteria if the CRL bit fails; we just want to log or increment a metric when the CRL check fails.

One way I can see to do this is something like 

```
      X509_STORE_set_verify_cb(store, [](int ok, X509_STORE_CTX* ctx) -> int {
        switch (X509_STORE_CTX_get_error(ctx)) {
        case X509_V_ERR_CERT_REVOKED:
        case X509_V_ERR_UNABLE_TO_GET_CRL:
          return 1;
        }
        return ok;
      });
```

But the docs for `X509_STORE_set_verify_cb` [clearly say not to use it](https://boringssl.googlesource.com/boringssl/+/356d37861f5772e2d87ef443f61f33c020e52b04/include/openssl/x509.h#5261).

Would it be better to duplicate some of the logic in [`check_cert`](https://boringssl.googlesource.com/boringssl/+/356d37861f5772e2d87ef443f61f33c020e52b04/crypto/x509/x509_vfy.c#761), and so CRL checking on our own? Then we'd have full control of what happens when a revoked cert is found.

What's the best way to handle this?

**Comment by guydc** [comment]
Hi @ggreenway, @davidben ! 

Did you reach any conclusion about the safety of using `X509_STORE_set_verify_cb` for this purpose? It seems that this pattern already exists when suppressing other, more straightforward, validation errors: https://github.com/envoyproxy/envoy/blob/d94ae7df0dea89dd216047f2f01fd7d675cfef2d/source/common/tls/cert_validator/utility.cc#L15-L18.
