### ISSUE TITLE
What does per_try_idle_timeout mean

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31332]
I'm trying to figure out how to configure `retry_policy`. I can't understand what `per_try_idle_timeout` means.

In the [official doc](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts), it says,

> The route [per_try_idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-retrypolicy-per-try-idle-timeout) can be configured to ensure continued response progress of individual retry attempts (including the first attempt). This is useful in cases where the total upstream request time is bounded by the number of attempts multiplied by the per try timeout, but while the user wants to ensure that individual attempts are making progress.

How could it ensure that individual attempts are making progress since the number of attempts multiplied by the per try timeout has run out.

Let's say that I configured `num_retries: 3` and `per_try_timeout: 3s`. So each retry will spend maximum 3 seconds. Meaning that after 9 seconds, Envoy will reply an error to the client. This is how I understand `retry_policy`. I can't see how to benifit from `per_try_idle_timeout`.

**Comment by wbpcode** [comment]
`per_try_idle_timeout` could be used to limit the max time of single try rather than max time of whole request. This is useful if some one want's quick retry.

If you cannot see the value of `per_try_idle_timeout`, it means it make no sense for you for now, then you can just ignore it. Envoy have lots lots of features and not every feature is valuable for everyone. :)
