### ISSUE TITLE
How to make LEAST_REQUEST work across multiple envoy replicas

### ISSUE THREAD

**Issue by chaitanyashete-n** [envoyproxy/envoy#31643]
How to make LEAST_REQUEST work across multiple envoy replicas

*Description*:
- We run envoy in a pod in a Kubernetes cluster and we have a Kubernetes service in front of envoy pod.
- We rely on LEAST_REQUEST lb_policy for load balancing. This is a requirement for our current design.
- When multiple pods of envoy are running, each pod seems to be running its own LEAST_REQUEST policy independently, since pods likely don't talk to each other.

With current extensibility that envoy provides, what is the best way to make LEAST_REQUEST policy work across multiple envoy pods (e.g. if request count state is maintained in some external store like redis).

**Comment by adisuissa** [comment]
cc @wbpcode @tonya11en @nezdolik as least-request codeowners

I guess one can implement such an extension, but my 2 cents are that it will become too slow to respond if there are many requests. This is because the network overhead each request has will probably outweigh the benefit of finding the host with the minimal number of requests.
A different approach is to have a system that assigns weights to the hosts, and periodically send these weight updates to the Envoys using EDS. This won't be exactly as least-request, but could probably approximate one.

**Comment by tonya11en** [comment]
It sounds like you want a consistent worldview across all pods, which is not really feasible for most workloads. No matter what you do, the active request count will almost always be stale.

It shouldn't be necessary to know the exact count of active requests for every endpoint, since an overloaded endpoint will have elevated service latency, and this manifests as more outstanding requests if there is no change to the RPS sent to the endpoint. 

If you _must_ have coordination across the whole distributed system, you could consider using the [Load Reporting Service (LRS)](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_reporting_service). I suspect this is going to be too much work for too little gain because:

1. You'd need to implement your own LRS. There's not an open sourced implementation like the rate limit service.
2. You'd need to use the information reported by LRS to adjust the endpoint weights via xDS, so you'd need to have a fairly advanced control plane in place.

**Comment by chaitanyashete-n** [comment]
Thank you for inputs on this.

We understand challenges involved with this. Just to give more context about our use case. Our requests are long running bidirectional streaming requests and each request does high performance computing workload. We rely on LEAST_REQUEST load balancing to ensure appropriate routing needed for compute intensive requests.

Thank you for pointer to LRS. We will look into this further.
