### ISSUE TITLE
Gauge stat only accepts integers

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [envoyproxy/envoy#31695]
*Title*: *Gauge stat only accepts integers*

*Description*:
Looking at the stats code, [I can see that gauge only accepts integers](https://github.com/envoyproxy/envoy/blob/79fed3b27b1dd0ad63f3b6e33160e72e7ff9313e/envoy/stats/stats.h#L157). This means that certain `double` metrics, like the [adaptive concurrency gradient](https://github.com/envoyproxy/envoy/blob/bb126b88bdae5fd422dd53d3e4f8639980de3827/source/extensions/filters/http/adaptive_concurrency/controller/gradient_controller.cc#L171) (which has values between 0.5 and 2) will only ever be reported as 0, 1 or 2, making the metric of little-to-no value.

Is this intentional? Do you see a problem in changing it to some other type? I can submit the PR if no objections

**Comment by phlax** [comment]
cc @jmarantz

**Comment by jmarantz** [comment]
I don't think we'd want to change the existing Gauge structure -- that could have massive unexpected consequences.

It is possible to add an *alternative* gauge structure, but for that use-case I don't think it's worth the trouble. Instead why don't you just use a scaled integer, say *1000, so that the values are between 500 and 2000.

**Comment by AbdulRahmanAlHamali** [comment]
That sounds reasonable. @tonya11en tagging you since you introduced adaptive concurrency. Any issue with changing the gradient dynamics a bit?
