### ISSUE TITLE
Switch mobile android ci tests `macos` -> `linux`

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#31726]
The macos runners are slower, less reliable, and much,  much, more expensive to run

Currently there are a number of macos/android jobs that seem to fail pretty frequently

Not sure if switching OS would resovle that out of the box, but seems a step in the right direction

**Comment by phlax** [comment]
cc @abeyad @fredyw @alyssawilk

**Comment by fredyw** [comment]
I deleted [Kotlin format (with ktlint) workflow](https://github.com/envoyproxy/envoy/pull/31730) that ran on macOS since we no longer have a need for that. The only remaining one is [kotlin-build](https://github.com/envoyproxy/envoy/blob/234dcc646cbfc1cd512742fc92ad704f514b5948/.github/workflows/mobile-compile_time_options.yml#L100) and I agree we should switch to running it on Linux.
