### ISSUE TITLE
How to make an endpoint fast failure

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31744]
I've read [the official doc ](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#arch-overview-health-checking-fast-failure) and its relative links, but I still can't understand how to remove an endpoint immediately.

It seems that setting the header `x-envoy-immediate-health-check-fail` in any response of an endpoint could remove the endpoint immediately (am I right?). Does it mean that the endpoint would be removed permanently? If so, how could I rejoin the endpoint into the cluster?

Furthermore, it doesn't seem that  `x-envoy-immediate-health-check-fail` could help me on my real case.
```
Envoy ---\
          -----> server
Envoy ---/
```
As you see, the two envoys can send requests to the server. I need a way to remove the server in each cluster of the two envoys. I think `x-envoy-immediate-health-check-fail` can remove the server from a cluster of one envoy but the server may still be there in a cluster of the other envoy. This is not what I want.

I don't know if `/healthcheck/fail` could help me. If clicking the `/healthcheck/fail` button on the admin page could remove one endpoint immediately, then I need to click the button on the two admin pages of the envoys, which is acceptable to me.

**Comment by phlax** [comment]
cc @zuercher @botengyao

**Comment by zuercher** [comment]
The /healthcheck/fail admin endpoint causes Envoy to start failing incoming health checks. I don’t think it’s relevant here. 

Options:
1. If you have active health checks enabled in the cluster, the server can start failing Envoy’s health check requests and start returning an `x-envoy-immediate-health-check-fail` response header for all requests. The server is not removed from the cluster’s load assignment. You can return it to service by removing the response header and responding successfully to subsequent health checks. As you point out requests may continue until every Envoy sees the header or sees a failing health check on the server. Given multiple worker threads, I’d guess you might even see multiple requests from a single Envoy. Note: by default, `healthy_panic_threshold` is set to 50%. When fewer than 50% of endpoints are healthy, Envoy starts ignoring health and uses all known endpoints. You may need to disable or adjust this setting. 
2. Provided you’re using EDS (either via a control plane server or with a file based ConfigSource), you can remove the host from the cluster’s load assignment. With health checks enabled, you’d also need to set `ignore_health_on_host_removal` on the cluster. Otherwise Envoy will continue to use the server until it fails a health check. Here you need to explicitly add the server back later. 
3. With a completely static config you could update the cluster load assignment on the Envoy hosts and hot restart to remove the host from the cluster.  Adding the server back is another config update and hot restart.
