### ISSUE TITLE
golang filter: add refresh method to the Headers so that people can get the latest headers in the OnLog

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#31905]
*Title*: *golang filter: add refresh method to the Headers so that people can get the latest headers in the OnLog*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Currently, there is no way to get the latest request/response headers in the OnLog method.
When we access the Headers object stored from the earlier phases, the headers inside them are not up-to-date, as other filter may change them.

Therefore, I intend to add a new `refresh` method to the HeaderMap interface. Users can call this method in the OnLog phase to get the latest headers.

Since the filters are run one by one during producing access log, it's safe to get all headers in the Go side.

Users can also call the `refresh` method in other situations. Whether it is safe or not is up to the situation. For example, when the `refresh` method is called to update the request headers during handling the response, it is almost safe because sanity filters won't write to the request headers after they are sent to the upstream.

CC @doujiang24

**Comment by doujiang24** [comment]
Another option, we could change the `OnLog()` method to `OnLog(HttpFormatterContext logContext, StreamInfo streamInfo)`

similar to the C++ method:
```
void Filter::log(const Formatter::HttpFormatterContext& log_context, const StreamInfo::StreamInfo& stream_info)
```
Or, we can move the `StreamInfo` into `HttpFormatterContext`, so that we can omit a new GC object for per OnLog call.

Reason:
It's not recommended to save the headermap for later using, after the fitler continue process back to Envoy.
I'll create a PR to doc the lifecycle, as requested here: https://github.com/envoyproxy/envoy/issues/31685#issuecomment-1896634267.

yep, the current implementation could be changed, we can discuss there~
