### ISSUE TITLE
Docker image with router_check_tool binary

### ISSUE THREAD

**Issue by shashank201192** [envoyproxy/envoy#32032]
*Title*: *Docker image with router_check_tool binary*

*Description*:
Is there a docker image available which contains the binary for envoy's router_check_tool. If not, how can I build same and publish to envoy's dockerhub?

**Comment by phlax** [comment]
i believe this tool is available in the `tools-*` images - see here https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=tools

can you confirm this works for you and we can close this ticket

**Comment by shashank201192** [comment]
I see only schema_validator_tool in this docker image. Below is the output from latest tools docker image envoyproxy/envoy:tools-dev

`
envoy@876db2fc900f:/usr/local/bin$ ls -ltr /usr/local/bin/
total 121344
-rwxr-xr-x 1 root root    19800 Jan  1  2000 su-exec
-rwxr-xr-x 1 root root 66941960 Jan  1  2000 envoy
-rwxr-xr-x 1 root root 57289528 Jan 25 01:43 schema_validator_tool
`

**Comment by phlax** [comment]
ok - if its not present in current tools image then i think that is the answer to your second question - ie where to put it

**Comment by phlax** [comment]
the relevant code is kinda legacy and a bit messy

the schema validator tool is built here

https://github.com/envoyproxy/envoy/blob/a34a18ad5f60cc65d2a651b504fefc3733c3d539/ci/do_ci.sh#L199-L201

i guess this is the best place to build the tool itself

the docker image is assembled here https://github.com/envoyproxy/envoy/blob/a34a18ad5f60cc65d2a651b504fefc3733c3d539/ci/Dockerfile-envoy#L51-L57  - so that would be where to include it in the docker image
