### ISSUE TITLE
How to send HTTP 103 response within filter

### ISSUE THREAD

**Issue by gruckus-gruckus** [envoyproxy/envoy#32186]
I'm wanting to create a HTTP filter that sends HTTP 103 Early Hints responses as soon as a request comes in (if it meets certain criteria like HTTP2), before the request gets proxied onwards. I can't see in the C++ or Go APIs how this can be done, seems like they only have decode headers/data without access to sending a response? Can i just call `encode1xxHeaders`, with the desired headers, from `decodeHeaders` phase to send an informational response?

**Comment by alyssawilk** [comment]
encode1xxHeaders should _theoretically_ work but I am not familiar with use cases which do this so it also may not work.  It's probably worth adding an envoy e2e test or doing a bunch of manual testing.
also due to https://github.com/envoyproxy/envoy/issues/19044 I'm really not sure it'd play well with 1xx headers from upstream.
cc @yanavlasov @KBaichoo for thoughts

**Comment by gruckus-gruckus** [comment]
Thanks alyssawilk! I'll give it a shot, and will post results if that's useful. I've been following the other 1xx threads, and it sounds like the first 103 would work, but others get discarded. I can work with that, if thats the case

**Comment by amarg-at** [comment]
I'm a bit confused on how to implement this. Do the WASM extension filters have access to the `encode1xxHeaders` method, or is that not in the api? Would it need to be added as a native filter?

**Comment by gruckus-gruckus** [comment]
I'm a bit confused on how to implement this. Do the WASM extension filters have access to the encode1xxHeaders method, or is that not in the api? Would it need to be added as a native filter?
