### ISSUE TITLE
Network filter to route MySQL connections based on SNI?

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/envoy#32303]
I'm doing research if it's possible to write an Envoy Filter (WASM, golang or native) which can route MySQL connections based on SNI? MySQL 8.1 clients added support for sending SNI recently so I want to use that.

The challenge here is that MySQL is server first protocol. I want to write a network filter which can
- Accept client TCP connection and doesn't establish an upstream connection yet
- Send **Initial Handshake** packet to the client
- Accept **Client SSL Request**, read SNI and based on that select upstream
- Receive the **Initial Handshake** packet from upstream and discard it
- Write the **Client SSL Request** packet to upstream
- Continue proxying everything else

From what I can understand currently it is not possible to write such a network filter because it looks like the filters need to select an upstream as soon as connection is established. Is that correct?

MySQL protocol for reference - https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html

**Comment by kyessenov** [comment]
There are really two "on-connected" events when using the downstream transport sockets. One if the "network connected" which starts the handshake. The other one is "handshake success", which triggers the subsequent network filters. So in theory, it sounds plausible to establish an upstream connection right after the handshake, when the SNI is available. There's some complication with TLSv1.3 early data, which we can ignore.

I haven't checked the code, so it might be doing something else right now - e.g. not waiting for the handshake to finish before starting the upstream connection, because it is easy to mix the two connected events. It might be helpful to test Envoy and see the full trace logs.

CC @rshriram
