### ISSUE TITLE
Enable base64/other UTF-8 encoding of non-UTF-8 proxy protocol TLVs

### ISSUE THREAD

**Issue by alhuan** [envoyproxy/envoy#32430]
*Title*: Enable base64/other UTF-8 encoding of non-UTF-8 proxy protocol TLVs

*Description*:
The proxy protocol filter can write metadata derived from proxy protocol TLVs that isn't UTF-8, as disclosed in this security advisory: https://github.com/envoyproxy/envoy/security/advisories/GHSA-gq3v-vvhj-96j6. The fix for this was to sanitize non-UTF-8 binary TLVs and replace non-UTF-8 characters with `!`. However, there's no requirement for proxy protocol TLVs to be UTF-8 in the first place—any binary vector is valid. 

For example, Azure TLVs are encoded as little-endian uint32s in the TLV, which can produce invalid UTF-8. In this case, sanitizing the UTF-8 solves the security issue but does so in a lossy way that prevents us from decoding useful information from the TLV for purposes such as allowing cloud traffic based on private link ID.

We'd like to add a flag in the Proxy Protocol filter that causes the filter to base64 encode the TLV before passing it on further into filter state/filter metadata. This would allow us to pass on all binary TLVs without lossy replacements.

I'm happy to contribute the change to Envoy; it would likely involve a small API change.

[optional *Relevant Links*:]
Azure TLVs: https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview#getting-connection-information-using-tcp-proxy-v2

**Comment by kyessenov** [comment]
The proposal sounds good to me! Contributions are welcome.

**Comment by alhuan** [comment]
@kyessenov I haven't had time to get around to this yet but could we tag this as "no stalebot" or "help wanted" please?

**Comment by Moglum** [comment]
I found this issue and eventually worked through the linked PRs and issues to a working solution on v1.38.0

The lossy sanitization can be avoided entirely without any new encoding flag. The fix requires two things used together:

**1. Use `DYNAMIC_METADATA` tlv_location (the default)**

Omit `tlv_location` from your proxy_protocol filter config (or set it explicitly to `DYNAMIC_METADATA`). Do **not** use `FILTER_STATE`.

With `DYNAMIC_METADATA`, the filter stores raw unsanitized TLV bytes in `typed_filter_metadata` 
https://github.com/envoyproxy/envoy/blob/eb069979b61614a7b3a53b13778e78ba2a7965df/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc#L652 It uses `tlv_value`, not `sanitised_tlv_value`. With `FILTER_STATE` it always sanitizes first — regardless of content.

**2. Read via `connectionStreamInfo():dynamicTypedMetadata()` in your Lua HTTP filter**

```lua
local ok, meta = pcall(function()
  return request_handle:connectionStreamInfo():dynamicTypedMetadata(
    "envoy.filters.listener.proxy_protocol")
end)
if ok and meta and meta.typed_metadata then
  local v = meta.typed_metadata["azure_link_id"]  -- raw bytes, no sanitization
  if v and #v == 5 then
    -- Azure TLV 0xEE: 1 sub-type byte + 4-byte LE uint32
    local b1, b2, b3, b4 = v:byte(2), v:byte(3), v:byte(4), v:byte(5)
    request_handle:headers():add(
      "x-azure-link-id",
      tostring(b1 + b2*256 + b3*65536 + b4*16777216))
  end
end
```

The critical distinction: `streamInfo():dynamicTypedMetadata()` reads HTTP request-level metadata and returns `nil` for proxy_protocol data. `connectionStreamInfo():dynamicTypedMetadata()` reads connection-level `typed_filter_metadata` https://github.com/envoyproxy/envoy/blob/0d379507474959fed589df5f6d1cb166338bd6ac/source/extensions/filters/http/lua/wrappers.cc#L222 which is where the proxy_protocol listener filter writes.

**proxy_protocol filter config:**

```yaml
name: envoy.filters.listener.proxy_protocol
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
  # tlv_location omitted → DYNAMIC_METADATA (proto enum 0, default) → raw bytes
  rules:
    - tlv_type: 0xEE
      on_tlv_present:
        metadata_namespace: "envoy.filters.listener.proxy_protocol"
        key: "azure_link_id"
```

Verified with Azure Private Link TLV `0xEE`: link ID `0x47002CB0` produces header `1191193776` (correct) instead of `1191193633` (the sanitized value from the `FILTER_STATE` path where `0xB0` → `0x21`).
