### ISSUE TITLE
coverage measurement broken on arm64 (if clang version match fails)

### ISSUE THREAD

**Issue by cinchurge** [envoyproxy/envoy#32493]
*Title*: coverage fails to run in the build container on arm64 machines

*Description*:
Invoking `coverage` breaks on arm64 machines, with the error message:
```
$ ./ci/run_envoy_docker.sh ./ci/do_ci.sh coverage
...
clang version 14.0.0 (http://git.linaro.org/toolchain/jenkins-scripts.git 3157e5d15f6bcd69b98455f9a5bc31e34fdc6123) does not match expected 14.0.0
```

*Repro steps*:
SHA:
```
$ git log -n 1 --oneline
7c410102b1 (HEAD -> main, origin/main, origin/HEAD) [http-cache-filter] limit cache read chunk size to buffer size (#32307)
```
Docker version:
```
$ docker --version
Docker version 24.0.7, build afdd53b
```
Repro (on an arm host):
```
$ ./ci/run_envoy_docker.sh ./ci/do_ci.sh coverage
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=aarch64
Setting test_tmpdir to /build/tmp.
Skip setting up Envoy Filter Example.
building using 12 CPUs
building for aarch64
clang toolchain with libc++ configured
coverage build with tests //test/...
clang version 14.0.0 (http://git.linaro.org/toolchain/jenkins-scripts.git 3157e5d15f6bcd69b98455f9a5bc31e34fdc6123) does not match expected 14.0.0
```

**Comment by phlax** [comment]
@cinchurge the issue is that its matching/checking the clang version ` ... does not match expected 14.0.0` - not sure the arch is significant, i think this more relates to your dev env

the version checks in the coverage ci are here https://github.com/envoyproxy/envoy/blob/1ad862ddf4856bc87df001ef5e889ba5fdbd3a45/test/run_envoy_bazel_coverage.sh#L9-L26

if you want to raise a PR that uses an environment variable to either disable the version checks or better make them warnings i would be happy to review

it would need to pass the env var through the run_envoy_docker.sh script

**Comment by phlax** [comment]
> how about making the regex matching  ...  wdyt?

great idea!

much better than my suggestion.

**Comment by phlax** [comment]
fixed, thanks @cinchurge
