### ISSUE TITLE
Enforce filter order dependencies

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#3286]
Today, filters can be loaded in any order and might depend on the request state and/or dynamic metadata produced by filters that are not included in a filter chain prior to the filter. We could improve this by having Envoy filter factories explicitly provide a vector of filter names that a filter depends on. This could be enforced/validated in two ways:
1. Envoy would refuse to load a filter chain that doesn't have all dependencies satisfied.
2. Envoy could restrict visibility of metadata/per-request state to just those explicitly declared filter dependencies.

**Comment by curiouserrandy** [comment]
I'd like to get a basic design for this feature roughed out before I dive into #3559, since I think the two issues are pretty closely related, and I don't want to do anything in #3559 that breaks what we eventually do here.  Spitballing ideas here to provoke argument, and (hopefully, eventually) consensus: 

* I'm adding dependency back-propagation as a requirement/nice-to-have from #3559 (i.e. filters should be able to tell when another filter depends on them, and what data the dependency is actually on).

* This is a run-time design; if a compile time design (as per the above comment) is desired, please push back.

* Filters which need access to other filter's data will have a configuration line added to them of the form "dependencies <filter>.<dataname>, ...." to list all data they are expecting to access.

* Configs which include dependencies on filters not earlier in the chain (i.e. not in a position to satisfy the dependency) will fail checking.  There will be a run time failure if information a filter is depended on is not created by the specified filter (?).

* dynamicMetadata() accessors will be moved from RequestInfo to FactoryContext.  The type will be changed from an API derived type over to a general map.  FactoryContext will implement that map s.t. only the data that a filter has declared interested in is visible to it.  (This implies that each filter will have its own FactoryContext.)

* FactoryContext will in addition export per-filter data about all the information that filter is expected to produce based on the configured filter chain.

Thoughts?  Rotten fruit?

**Comment by htuch** [comment]
I like the core idea of having filters make clear what their dependencies are. I think we can do this by having filters provide a list of filter names, that they will be expecting to rely upon for `dynamicMetadata()`. The dynamic metadata should already be organized as a map from "filter name -> metadata". This will be a first class method on the filter factory, much like `name()` is today. The one trick is that the organization of metadata today is by destination filter, rather than originating filter, we'd need to figure something out here.

I'm not sure if we need to modify where `dynamicMetadata()` lives if we do enforcement based on this.

**Comment by curiouserrandy** [comment]
So I think we need it to be filter names *and* value names, because in the case of user-defined header configuration (which I consider a sub-case of this), we want to tell the producing filter exactly what information is needed.  This may have complex type requirements (i.e. we can't just return a proto struct).  Let me know if you want me to let go of this requirement, but it seems an important one for performance, which seems a goal of the Envoy proxy.

I'm confused by your implementation comments.  dynamicMetadata() is currently hosted on the RequestInfo, which means access to it has no context as to which filter is doing the access.  Moving it to the filter factory would indeed give us that context, but that means we're modifying where it lives?

It's also of type envoy::api::v2::core::Metadata, which is a map<string, google.protobuf.Struct> and hence provides no enforcement mechanism.  I think we need to change this type unless we're willing to simply trust filter code, which strikes me as unwise.  We can totally export a type that provides a map interface (maybe two levels, maybe to a struct depending on the discussion in the first paragraph), but it can't be exposed as actually being a map.

My guess is that you're proposing exposing a map interface (not an envoy::api::v2::core::Metadata) from the filter factory, which I think is a fine idea--please confirm if that's true.  If so, the only top level issue to resolve is if dependencies are to filters, or to specific values exported by filters.

**Comment by mattklein123** [comment]
@curiouserrandy I commented in #3559, but since we are discussing design here, I'm still a little hazy on why all of this complexity is needed. I do really like the idea of a filter being able to describe its order dependencies as we have lots of confusion about that, but do we need complicated data dependencies also? What do we gain from that versus a more general mechanism such as request local storage (RLS) as tracked here: https://github.com/envoyproxy/envoy/issues/151

**Comment by htuch** [comment]
@curiouserrandy the idea with using `envoy::api::v2::core::Metadata` would be to apply some form of filtering before being presented to the user, presuming we can do this efficiently. I agree we want to structurally enforce visibility rules here. 

Regarding having the value labels being declared dependencies, I agree, we probably will want this for performance. I guess one of the tradeoffs here is whether it's actually possible to do it "statically", i.e. express this in the configuration, or whether the data dependencies might only be known at runtime. 

@mattklein123 this is the discussion we had at our sync up last week, I thought we had drifted towards a solution such as the one @curiouserrandy is proposing.

**Comment by curiouserrandy** [comment]
@htuch: Let's spend 5m chatting offline about the use of ...::Metadata; I don't have a sense as to the different possible implementations you're considering.  Naively, I think using that type requires a filtered copy for each filter.  

@mattklein123 : Ooops, I think #151 is what I was trying to get at in #3559 without realizing it exists.  Do you see a difference in intent between those two issues, or should I merge #3559 into #151, copying the meat of the discussion?

**Comment by curiouserrandy** [comment]
[Deleted last comment; please ignore in email stream.]

@htuch: Let's spend 5m chatting offline about the use of ...::Metadata; I don't have a sense as to the different possible implementations you're considering. Naively, I think using that type requires a filtered copy for each filter.

@mattklein123 : Oh, thanks for the pointer to #151; that's very relevant to this discussion.  Could you give me a sense as to how the intent of that issue is different than the dynamicMetadata() access being discussed in this issue?

**Comment by mattklein123** [comment]
> @mattklein123 this is the discussion we had at our sync up last week, I thought we had drifted towards a solution such as the one @curiouserrandy is proposing.

Sorry I'm probably just confused and don't fully understand what is being proposed. Per the other issue I'm just trying to make sure we don't wind up with complexity we don't need right away. @curiouserrandy maybe after you sync up with @htuch you can offer a more concrete proposal?

> @mattklein123 : Oh, thanks for the pointer to #151; that's very relevant to this discussion. Could you give me a sense as to how the intent of that issue is different than the dynamicMetadata() access being discussed in this issue?

I suspect it's very similar, but I'm not completely sure until the metadata proposal is more fleshed out because TBH I don't fully understand what is being proposed. I think we can resolve that issue with whatever we come up with. The idea is just to provide some request level storage that filters can use to pass data around that doesn't involve jamming it into headers which is what is done today.

**Comment by curiouserrandy** [comment]
Folks: I've written up a proposed design for this feature and https://github.com/envoyproxy/envoy/issues/3559 in https://docs.google.com/document/d/1GNawM59Pp09WZ34zqJYiO_qmERjuGbOUeAqF1GG6v9Q/edit#.  Comments welcome.

**Comment by mattklein123** [comment]
Closing in favor of https://github.com/envoyproxy/envoy/issues/14470
