### ISSUE TITLE
rethink panic threshold and priority LB interactions

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#3304]
See https://github.com/envoyproxy/envoy/pull/3282. There are some ideas in the comment threads about how we can improve how these two features interact to make it more intuitive.

cc @alyssawilk

**Comment by mpuncel** [comment]
my 2 cents: I agree with the overall idea mentioned in the other thread that panic threshold should let the spillover mechanism do its job when lower priorities have healthy hosts, but if the lowest priority is too unhealthy some kind of panic mechanism should kick in.

One way of doing it might be to have the spillover mechanism "wrap around" to the first priority, and just consider the first priority to be healthy in that circumstance (but still preferring the lowest priority if there are any healthy hosts there).

**Comment by cpakulski** [comment]
@mattklein123 @alyssawilk I can implement the logic described in #3282, unless someone is already working on this.

**Comment by alyssawilk** [comment]
That'd be great! I believe it's all yours :-)

**Comment by cpakulski** [comment]
Thanks!

**Comment by cpakulski** [comment]
@mattklein123 @alyssawilk Correct me if I am wrong. Currently there are 2 independent mechanisms which are executed when there is a change in Host Set: first redistributes load based on health: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/load_balancer_impl.cc#L56-L98 and second turns on Panic which puts all Hosts from priority level into a LB: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/thread_aware_lb_impl.cc#L19-L37. Those 2 mechanisms run kind of independent.
My understanding of the issue (#3282) is that if there are no priority levels (only one HostSet), load distribution is basically no-op but Panic logic should kick in to put 100% of hosts into LB. If there are priority levels, load distribution should run as is, but Panic logic should be suppressed and 100% of Hosts should be put into LB only when all Hosts from all priority levels are declared dead. Is this correct?

**Comment by mattklein123** [comment]
@alyssawilk correct me if I'm wrong, but I think the options here are either:
1) Default panic threshold to 0% if there is more than 1 priority.
2) Update the `choosePriority()` function:

https://github.com/envoyproxy/envoy/blob/6f92dc292de4c2db51f5dfbab5fc9b313ee9f315/source/common/upstream/load_balancer_impl.cc#L23

To check panic threshold as it iterates through each priority then potentially wrap around to the beginning as was recommended by @mpuncel?

**Comment by cpakulski** [comment]
How should option 1 be interpreted? - to completely disable panic thresholds or to enter panic when all hosts are gone? I may be mistaken, but in both cases it will conflict with load calculation. First case  basically disables creating LB with all upstream hosts regardless whether they are healthy or not (this happens only when panic threshold is reached). In the meantime load calculating may shift all traffic to priority 0, but LB attached to priority 0 will have empty list of upstream healthy hosts. Load calculation and checking panic thresholds are done in independent steps without sharing a context, but kind of depend on each other.

**Comment by alyssawilk** [comment]
I'd be inclined to update recalculatePerPriorityState()

I think we should always do priority spillover if the aggregate health is 100+, even if P=0 is in panic.  Basically at that point you can use configured hosts and they can handle the load, so you do spillover.  If the aggregate health is less than 100 and P=0 is in panic, your healthy hosts can't handle the load and you are in panic mode, so fail over to P=0 panic picking.  So the remaining question is what to do if the aggregate health is less than 100 and P=0 is not in panic?  I think in that case you still do spillover because you're not at a point you want to send traffic to unhealthy hosts.  

So I think we can just change recalculatePerPriorityState instead of hard-failing to P=0 if the health is 0, to hard failing if total health (without the min of 100) is less than 100 and P=0 is in panic.  WDYT?

**Comment by cpakulski** [comment]
> I think we should always do priority spillover if the aggregate health is 100+, even if P=0 is in panic.

Based on code analysis, LB for P=0 would send traffic to unhealthy hosts too if P=0 is in panic mode. It would be probably better to ignore panic for P=0 as long as aggregate health is 100+. 
The rest looks good to me.

**Comment by mattklein123** [comment]
> Based on code analysis, LB for P=0 would send traffic to unhealthy hosts too if P=0 is in panic mode. It would be probably better to ignore panic for P=0 as long as aggregate health is 100+.
The rest looks good to me.

Just went through the code. I think I understand this conversation but still a little hazy TBH. AFAICT @alyssawilk is proposing that we don't use panic at all if aggregate health is 100+, but then actually taking into account panic along with aggregate health < 100 for P0. So I think she is implying to not use panic in the case you are talking about?

Do you mind just listing out the exact changes you plan to make just to make sure we are all on the same page? Thank you!

**Comment by cpakulski** [comment]
I believe that now we all agree on logic to use. But I am struggling with "elegant" implementation. Currently, host changes to PrioritySet trigger update callbacks to be run: https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/upstream_impl.h#L295. One of the callbacks is [LoadBalancerBase::recalculatePerPriorityState ](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/load_balancer_impl.cc#L56). Note that this method calculates only load, not panic levels. Another callback which is called is [ThreadAwareLoadBalancerBase::refresh](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/thread_aware_lb_impl.cc#L19), which checks panic levels. With new approach, that calculation should be suppressed based on output from load calculation (if total health is 100+, panic levels should be ignored). The problem is that ThreadAwareLoadBalancerBase::refresh does not know whether aggregated health is less, equal or more than 100. Going forward, a new LB per each priority level is created and it also does its own [panic level check](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/maglev_lb.h#L67) (which should be suppressed if total health is 100+).
I will check it I can add total_health_ variable and carry it from load calculation to panic level checks and act accordingly. The other option would be to have ONLY ONE callback and do all calculations and create new load balancer in one step.
Sorry for long comment. It is also quite possible that I missed something here. This area of code is new to me.

**Comment by mpuncel** [comment]
disclaimer: I'm also a little hazy here, but I'm wondering if we can simplify things by ignoring the panic threshold setting altogether. There's already an "overprovision" factor here which is a measure of what percentage of locality/priority membership is needed to be at "full capacity". Panic threshold seems redundant to that to me.

One way to implement this I think would be to conceptually pretend there is a P=N+1 that is a copy of P=0 and hardcoded to be 100% healthy all the time. Then you can use only the overprovision factor/spillover mechanism and if aggregate health goes below 100 then you hit P=0 again as a backstop.

**Comment by mattklein123** [comment]
@cpakulski it's more confusing than that unfortunately. The "thread local" LB base is only used currently for the hashing load balancers. The rest of them don't use that and actually inherit from "zone aware LB base" which uses different logic in the panic path. I can't really so more without going and looking in detail, but we might need to unify that logic (maybe?). Or, as @mpuncel is mentioning and I initially thought, basically we could try to get rid of the `isGlobalPanic()` calls in this function:

https://github.com/envoyproxy/envoy/blob/9f89c12600da2800246201de76382f26ff201777/source/common/upstream/load_balancer_impl.cc#L355

And fold that logic into the pre-calculation phase? (And possibly slightly change the logic if there are multiple priorities.)

**Comment by cpakulski** [comment]
@mattklein123 The last comment confused me even more. Unless there is need to do it now, I would like to analyze the code further and maybe unify the logic, as you suggest or remove `isGlobalPanic()` calls as you and @mpuncel suggest, but it would be nice to know what I am doing.

**Comment by mattklein123** [comment]
@cpakulski no need to do it now, feel free to take a look at the code. I agree this is very confusing, and even if you just add more comments first that would be awesome.

**Comment by cpakulski** [comment]
I still plan to solve this issue, but cannot commit much time during the summer.

**Comment by cpakulski** [comment]
Created PR #4442 for this issue. It implements logic which are agreed upon (see conversation above).

However, I think that logic is broken when number of healthy hosts in a priority set drops down to zero. In such case, the priority set goes into panic mode, but is omitted from load calculation. See the following test case: https://github.com/cpakulski/envoy/blob/issue/3304/test/common/upstream/load_balancer_impl_test.cc#L264-L271. All Priority levels are in panic mode, but P=0 (host_set) and P=1 (failover_host_set) get no traffic because the number of healthy hosts in those sets are zero. I think that logic should be changed that if all priority levels are in panic mode, load distribution should be based on total number of hosts in priority set, not based on number of healthy hosts. In case of mentioned unit test distribution should be 33%, 33% and 33% as the number of hosts in each set is 5.

**Comment by cpakulski** [comment]
@mattklein123 @alyssawilk @dnoe I have PR for this issue in "stale" mode: #4442. Can one of you review it? As I mentioned above, I think that load calculation algorithm could be improved for situations when number of healthy hosts is really low and all priority levels are in panic.
