### ISSUE TITLE
Filter the metrics being emitted

### ISSUE THREAD

**Issue by abloom-stripe** [envoyproxy/envoy#3305]
*Title*: Filter the metrics being emitted

*Description*:
Envoy emits a large number of metrics. Many of them are useful, but there are a lot we don't use. The number of metrics being emitted in a large deployment of Envoy is expensive and we'd like to be able to control that. Unfortunately we use the `dog_statsd` sink which makes the [statsd/filter](https://github.com/statsd/filter) incompatible.

Envoy already has metric rewriting capabilities, I'm hoping this can be extended to also exclude metrics. If a `regex` is present with no captures (ie: no rewrite rules) and no `tag_name` that metric should be ignored.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#envoy-api-msg-config-metrics-v2-tagspecifier

**Comment by mattklein123** [comment]
This is somewhat similar to stuff that @mrice32 is working on. @mrice32 any thoughts on this?

**Comment by mrice32** [comment]
@abloom-stripe I'm working on making it easier for sinks that only care about subsets of Envoy stats.  My plan was to do this by making the existing flush of all metrics optional, and building a better interface for sinks that wish to query stats (see the discussion [here](https://github.com/envoyproxy/envoy/pull/3283).  One thing that I am not planning is to query them by tag values or tag extracted name, but I think these would be interesting additions to consider.  What you suggest is tackling the problem on the other end - stripping certain metrics from the flush.  It also seems that your use case is to exclude a select few rather than include a select few (which is our use case).

@mattklein123 I think both of these would be reasonable additions for these use cases.  The only way I could imagine to condense both of these into the same solution would be to build some sort of sink subscription, where each sink has the chance to subscribe to a particular stat when the stat is created, but I'm not sure how feasible this is as it would likely add a decent amount of overhead and complexity.

What do y'all think?

**Comment by mattklein123** [comment]
Yeah, I think it probably makes sense to split the problems apart. @mrice32 once you make the interface changes we discussed, I think it would be pretty easy to build what @abloom-stripe is asking for into something that is either specific to statsd, or potentially a general option that is used by some type of common filtering code uses during flush (this could potentially even be used for filtering the output of /stats).

**Comment by abloom-stripe** [comment]
Just to clarify we're using the dogstatsd metrics sink, not statsd. If we were using statsd we could shim [https://github.com/statsd/filter](statsd/filter) in between Envoy and our collector to do the filtering. If possible a generalized solution would be ideal.

**Comment by mattklein123** [comment]
This is done. Envoy stats can now be filtered.

**Comment by ryanjwh** [comment]
@mattklein123 can you elaborate on "Done" please? My company is suffering from Envoy metrics explosion because we use Datadog and it's picking up over 600 metrics from every container/sidecar running Envoy ($$$$$ in a commercial metrics platform that bills on metrics ingestion). So, we want to start allow/denylisting which metrics we want to collect from Envoy (regardless of Datadog, New Relic, Prometheus/Grafana, etc) by filtering metrics in the Envoy config.

I found this issue but cannot find anywhere in the Envoy documention that explains how to use what was completed here.

**Comment by mattklein123** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#envoy-v3-api-msg-config-metrics-v3-statsconfig and stats_matcher specifically.
