### ISSUE TITLE
re-enable async file tests

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#33114]
failing "due to CI infra change" but probably should handle that particular change.

**Comment by yanavlasov** [comment]
Permafail in async_file_handle_thread_pool_test and file_system_http_cache_test  Filesystem where bazel creates temporary directory does not support O_TMPFILE flag. This is likely due to some change in the RBE runner as not all filesystems support O_TMPFILE.

The code that creates anonymous files falls back to mkstemp/unlink, however this is not equivalent to O_TMPFILE if the such file later needs to be re-linked with the linkat call. Linux does not allow relinking of unlinked files that used to have a name - this is by design. This results in tests that rely on re-linking anonymous files created by mkstemp/unlink to fail.

This is a bug in Envoy code. The fallback to mkstemp/unlink is required since O_TMPFILE is not universally supported. However if mkstemp is used the file entry point can not be unlinked.

**Comment by ravenblackx** [comment]
Still planning to do it.

**Comment by ravenblackx** [comment]
Never stop nagging!
