### ISSUE TITLE
Can not write or read data to SASL Kafka 

### ISSUE THREAD

**Issue by rainbowwiki** [envoyproxy/envoy#33256]
Hello Team

**Description**:

we need to use envoy to do the proxy for kafka

1. envoy version: 1.18.2
2. kafka version: 2.8.1
3. configed follow this wiki: https://www.envoyproxy.io/docs/envoy/v1.18.2/configuration/listeners/network_filters/kafka_broker_filter#config-network-filters-kafka-broker
4. once kafka enable SASL Auth, 
- kafka-topics.sh can work well for example to list topics via envoy address.
- consumer client can not work (even consumer group can not found)
- write data also can not work
5. no auth version kafka work well 

**QA**:
1. is this filter support Auth-kafka ?
2. is this a bug?
3. I notice: the kafka proxy is experimental and is currently under active development. , do we have plan to release this version?
4. any version now for envoy include stable kafka-proxy ?

Hope for your feedback, thanks team!
-

**Comment by adamkotwasinski** [comment]
> 1. is this filter support Auth-kafka ?
2. is this a bug?
3. I notice: the kafka proxy is experimental and is currently under active development. , do we have plan to release this version?
4. any version now for envoy include stable kafka-proxy ?

1. The broker filter should be relatively transparent - all it does is decrypting payloads and updating metrics, in the most typical configuration it sends the data futher _as-is_, so even if the filter has bugs, you shouldn't be noticing it (unless the payloads cannot be parsed).
2. Need more info.
3. No concrete plans and right now there is not too much to talk about unless we identify proper issue and then we can decide whether it's 'working as intended' vs 'bug'.
4. Not feature-wise.

Are you using `SASL_PLAINTEXT` or `SASL_SSL` ? If `SASL_SSL` then it won't work -> Kafka broker does not decrypt data == is not capable of processing your requests.

If that's not the case, please try to eliminate `envoy.filters.network.kafka_broker` from your test scenario - does it work then? If it's really caused by broker filter then check the logs for [failed processing](https://github.com/envoyproxy/envoy/blob/main/contrib/kafka/filters/network/source/broker/filter.cc#L103) (run Envoy with debug logging)  and check the `request.unknown` / `request.failure` metrics.

**Comment by rainbowwiki** [comment]
hi [adamkotwasinski](https://github.com/adamkotwasinski)

removed kafkaBroker, work now,

so one more question about this:
1. what's the best practice for kafkaBroker?
2. the kafkaBroker feature only for record some metrics such as how many datas we received?

thanks!

**Comment by adamkotwasinski** [comment]
Hey @rainbowwiki I just realized you are running Kafka 2.8.1 & Envoy 1.18.2. 
Envoy 1.18.2 supports protocol up to Kafka 2.4 - so you need to upgrade your Envoy instance to something newer.
Compare: [1.29 can understand Kafka up to 3.5](https://www.envoyproxy.io/docs/envoy/v1.29.0/configuration/listeners/network_filters/kafka_broker_filter).
