### ISSUE TITLE
Changing locality priority level causes the locality to be duplicated

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#3327]
*Title*: *Changing the priority on a locality in a cluster with active health checks configured results in the locality being duplicated*

*Description*:
[mpuncel/envoy@b4e3af34dd06](https://github.com/mpuncel/envoy/commit/b4e3af34dd0600562ed6774b69f15822778d0b39) has a failing test case demonstrating this.

Example: if there are two localities L1 and L2 which are both included in an EDS update with priority 0 set for each, followed by an update with L1 in p0 and L2 in p0, Envoy ends up thinking that L2 is in both priority 0 and priority 1.

This seems to be due to an assumption within EdsClusterImpl that a locality will never move to a different priority. For that reason I'm guessing this would be a complex behavior change to implement.

Changing the behavior here to allow moving a locality to a different priority is useful for situations like disaster recovery exercises, for instance to test that an upstream service can take over for the geographically closest locality in the event of a datacenter or network outage.

Using the recently added `drain_connections_on_host_removal` cluster option might be a viable workaround, but with this behavior change this would be possible without giving up the eventual consistency design choice of Envoy (and i'm also not sure if the draining is destructive in this scenario).

**Comment by mattklein123** [comment]
@htuch @alyssawilk

**Comment by alyssawilk** [comment]
Yeah, I think it's worse than just moving priorities, I think in general there's an issue with removals, similar to #3312 where we're using locality as a unit of update.  So when we get a config update with 2 localities we update those two, but if the original priority level had 4 localities, the other two are assumed to be untouched, rather than being removed.

We can either say that any localities not present in an update are explicitly removed, which means in combination with #3312 any time you want to update one host in one locality in one priority you have to pass on the full tree, or we can instead say that unmentioned localities/priorities are assumed to be explicitly unchanged and the way to delete one is to remove all endpoints in it.

I think the former is much easier to understand and more likely for folks to get right, it just has the unfortunate side effect of all updates being more expensive as we have to pass all the data.  I'd be inclined to do that as the fix.  @htuch, thoughts?

@snowp as well since it relates to that fix.

**Comment by htuch** [comment]
Yes, I agree, we should nuke anything not mentioned in the update. We will deal with incremental updates differently, as per the incremental xDS proposal. @snowp @mpuncel is fixing this on your radar, or should @alyssawilk or I own this?

**Comment by snowp** [comment]
https://github.com/envoyproxy/envoy/pull/3318 aims to clear our priorities not mentioned in the update, I'll happily see that one through. I'm not familiar with the incremental xDS proposal but I imagine that's less important for us.

**Comment by htuch** [comment]
@snowp I'm not suggesting to add incremental xDS here. I'm suggesting that we should do what #3318 does but also for localities within a priority level. You might hit this bug as well.

**Comment by snowp** [comment]
Got it. Yeah that sounds like something we'd need to deal with, so I'll tackle that as well.

**Comment by htuch** [comment]
@snowp awesome, thanks for the contributions here.

**Comment by mpuncel** [comment]
If the approach to remove a locality if it isn't mentioned in the locality is implemented, we will cause unintended consequences with TCP draining if the locality is moved across priorities?

My concern is: imagine we have locality L1 in priority 0, and locality L2 in priority 1. If L1 is experiencing an outage, and requests are therefore spilling over to L2, an operator might promote L2 to priority 0. My understanding is that this would cause all of the existing connections to L2 to be drained, and new requests would open new connections to L2. That could be problematic in the case where L2 has a large number of clients, it will cause all client Envoys to initiate new connections to all of its endpoints it at the same time.

**Comment by snowp** [comment]
So looked into this and verified that localities will be removed from within a priority level when not referenced in the config update: https://github.com/snowp/envoy/commit/43647e8d07556b42f681870434bd03e728eb4479

The difference between my test and @mpuncel's test is that I didn't add any health checkers. When health checking is enabled we attempt to remove the endpoints within the locality but end up keeping them because they have not yet failed active HC. 

When the health status/cluster configuration does not stop us from removing the endpoint, removing an endpoint seems fine. This means that removing a locality from a priority can be accomplished by turning of health checking or using the `drain_connections_on_host_removal` flag on the cluster. 

To me the open question is whether we want to optimize this operation so a move between localities don't require deleting the locality from the old priority and adding a "new" locality to the new priority. From what I can tell @mpuncel is right in that currently we need to reestablish connections to the hosts (as they're treated as net new hosts) while closing down the old ones, which seems like a lot of unnecessary work.

 Seems like a lot of the code in upstream scopes host changes to a priority (e.g. through `PrioritySet::MemberUpdateCb`), which makes moving a host between priorities tricky. I could imagine a new callback along the lines of `HostPriorityChangedCb` that could be used to notify whatever system might care about a change in priority, but I don't know the overall code enough to know how feasible this is - or if there's an easier way to accomplish this.

**Comment by alyssawilk** [comment]
My inclination is to say that being unable to remove the locality is a bug, and avoiding draining and reestablishing connections is an optimization.  I think we can fix the underlying problem and if anyone encounters problems due to shifting localities around there can be a follow-up PR addressing that.

**Comment by htuch** [comment]
Yeah, I agree. Ideally we optimize for behavior within a static assignment of priorities/localities and correctness first, and then if it's a real issue (i.e. we have dynamic adjustment of priorities happening frequently enough in concrete use cases), then we can add this as a separate PR.

**Comment by snowp** [comment]
Maybe I'm misunderstanding - are you saying that if a locality is completely removed we should bypass the check to see if the endpoints are still reporting healthy?

**Comment by htuch** [comment]
I think if you have health checks enabled and expect hosts to stick around post-EDS removal while they are healthy, that should happen regardless of whether the locality or priority disappears. So, I think what you write is valid, thank you very much for digging into this!

@mpuncel does this make sense at your end, or do you have a different take?

**Comment by mpuncel** [comment]
yep, makes sense. I do think being able to change the priority on a locality (move operation) would be useful, I'll open a separate issue for that as a feature request
