### ISSUE TITLE
Support for timestamp based routing

### ISSUE THREAD

**Issue by abhinavk96** [envoyproxy/envoy#33310]
*Title*: 
Currently envoy supports routing requests based on header, and various other mechanisms. Support request's timestamp 
as a possible parameter for routing config.

*Description*:
Timestamp as a routing config will allow atomic cut over for traffic when the destination cluster for same routing config has changed/ or is expected to change at a specific time. 

For instance, if I want to configure my routing policies like this: 

if header1=value1, header2=value2 and current time < 8:00 AM, route to cluster1.
If header1=value1, header2=value2 and current time >= 8:00 AM, route to cluster2.

It's hard to achieve via LDS/RDS because config propagation itself will take some time (order of few seconds to mins depending on the control plane configuration). If config is pushed at 8:00 AM to say route to cluster2 now instead of 1, realistically traffic will begin getting routed around 8:01 - 8:05. 

I have been able to achieve effectively the above config using a lua script, where around time change boundaries, I pre-emptively push the script in the config to handle routing based on current timestamp, but I wonder if this is a common scenario for others, and having a standardized way to do this will benefit others.

**Comment by phlax** [comment]
interesting question

cc @adisuissa as you may have an idea if its possible/desirable to be added

**Comment by adisuissa** [comment]
Interesting, but I'm not sure if it is a common scenario for many distributed systems.
I typically try to stay away from using time as a property because in a distributed system latency can occur due to different reasons.
I wonder if it makes more sense to add that as another header (e.g., `header3=prefer_route_cluster1`) that the downstream will select depending on the time in the downstream client. I guess that similar to lua, one can have their own filter that depending on the time sets `header3` to be some value that the router will later use to route traffic.

Specifically for xDS propagation, I think one can use ECDS to configure a specific filter behavior (rather than the entire listener/route) and that should be faster. But again, if possible, I suggest avoiding estimating how long it would take for all the clients to receive the update (assuming the error-margin is in the order of seconds).
