### ISSUE TITLE
Why accept x-forwarded-* headers when Envoy as edge proxy ?

### ISSUE THREAD

**Issue by Kiblyn11** [envoyproxy/envoy#33700]
*Title*: Why accept x-forwarded-* headers when Envoy configured as edge proxy ?

*Description*:
Reading X-Forwarded-For doc [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for), I found that when Envoy is configured as edge proxy, it accepts and append to X-Forwarded-For header.
But why ? As it's on edge, it shouldn't have any reason to keep it coming from public client and internal components (example [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/ip/realclientip.go#L42) with OAuth2Proxy) relying on this header are mislead to trust the X-Forwarded-For entries before Envoy append it's own IP address.

It seems Envoy should ignore incoming `X-Forwarded-*` headers which are reserved for proxies when `use_remote_address = True` as it's supposed to be on edge with no proxies upfront.

**Comment by adisuissa** [comment]
cc @alyssawilk @yanavlasov

**Comment by alyssawilk** [comment]
because there may be proxies in front of Envoy and they communicate end user IP via x-forwarded-for.  Envoy treats x-forwarded for as an untrusted header: a correctly configured edge proxy won't for example treat a request which claims to be from a trusted IP in an untrusted x-forwarded-for header as a trusted request.  oauth code should do the same

**Comment by alyssawilk** [comment]
the internet is filled with HTTP proxies.  the x-forwarded header is a internet standard way of those proxies informing the next hop that they terminated TCP and what the original client IP is.
