### ISSUE TITLE
Cold-start Admission Control filter rejects before receiving the entire sliding window of samples.

### ISSUE THREAD

**Issue by idrajeev12** [envoyproxy/envoy#33739]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Cold-start Admission Control filter rejects before receiving the entire sliding window of samples.*

*Description*:
We have noticed that the Admission Control filter from the cold start does not wait to receive the whole sliding window of samples before starting to reject.
1. this leads to situations when a statistically insignificant number of requests can trigger rejections within a much smaller time interval than a configured sliding window.
2. for example: having a sliding window of 60 seconds we can see rejections starting after the first few seconds from the cold start by having only a few failed requests and successes.
3. we were curious if that is the desired approach and what would be the intention for that behavior.
We also noticed that seconds.count in averageRPS() implementation is derived from ageOfOldestSample() and we were curious would it be reasonable to use a sliding window interval instead of ageOfOldestSample()? We thought that it could improve the behavior when we see very early rejections from the cold start or when the traffic is sparse.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
Current repo
>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by idrajeev12** [comment]
@tonya11en Please review and share your thoughts?

**Comment by tonya11en** [comment]
Thanks for the detailed info! 

> for example: having a sliding window of 60 seconds we can see rejections starting after the first few seconds from the cold start by having only a few failed requests and successes.

This is not the behavior I would expect and is likely a result of the issue you found:

> We also noticed that seconds.count in averageRPS() implementation is derived from ageOfOldestSample() and we were curious would it be reasonable to use a sliding window interval instead of ageOfOldestSample()? We thought that it could improve the behavior when we see very early rejections from the cold start or when the traffic is sparse.

This is a bug. The docs are very clear on the expected behavior of the `rps_threshold` parameter:
```
If the average RPS of the sampling window is below this threshold, 
the request will not be rejected, even if the success rate is lower 
than sr_threshold. Defaults to 0.
```

Your sampling window is 60 seconds, so the `averageRPS()` should be calculated as the number of requests encountered over the last 60 seconds divided by 60. This current behavior will result in the broken behavior you've encountered at proxy start up and is made worse by the fact that the admission controller implementation tracks this thread-locally.

A naive fix would be simple, since all we'd need to do is [modify is this function](https://github.com/envoyproxy/envoy/blob/3aa26878b65b97ddead542696204da947d5cfcc6/source/extensions/filters/http/admission_control/thread_local_controller.cc#L20-L27), but looking at how this is implemented, I see no reason for the average RPS calculation to be thread-local. We'd likely be able to just change that to account for the _global_ average RPS and use that number in the rejection probabilities. Making the average RPS a common value across all threads would make the behavior more sane in my opinion.

Now, if we take a look at your config, my initial thoughts are that your `rps_threshold` of 1 is too low to be very effective even if the average RPS were being calculated properly. If you need to mitigate this issue before we're able to patch it, I'd start by increasing the RPS threshold to be something larger and see if you can get by until I or someone else (maybe you? :D) can send out a PR.

I would also keep in mind that increasing your lookback window to 60s will result in a slower recovery time. You may have already seen [the experiments in one of my earlier PR submissions](https://github.com/envoyproxy/envoy/pull/11910#issue-651901341), but I'm linking again for anyone else who may want to build an intuition for how the lookback window affects recovery times.

Let me know if you need me to clarify anything above. If you want to do the change, I'm happy to offer some guidance. Otherwise, I'll try to get around to submitting a PR in the next week or two.

**Comment by idrajeev12** [comment]
Appreciate your quick response and support on this @tonya11en, Let me review you this and get back to you with an update.

**Comment by ipoval** [comment]
@tonya11en , thank you!What do you think if we try to work on this issue with our resources and submit a fix?
If that's ok, then probably the first step for us would be to come up with the proposal for the alternative implementation/fix and align with you.

**Comment by tonya11en** [comment]
> @tonya11en , thank you!
> 
> 
> 
> What do you think if we try to work on this issue with our resources and submit a fix?
> 
> If that's ok, then probably the first step for us would be to come up with the proposal for the alternative implementation/fix and align with you.

Sounds good to me! Don't feel like you have to write a big formal document or anything. A few paragraphs on the high level approach should suffice and we can iterate on the specifics in the PR. 

Here's our guide on contributing to the project:
https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md

Let me know if there's anything else I can do to help you get going.

**Comment by ipoval** [comment]
@tonya11en  👋 , and sorry for the delay with the response

**Comment by Jayden-Lind** [comment]
Hey @tonya11en, 

A crude fix for this is possibly something like below. After testing this, this consistently waited til the window's last object was at the time of the sampling window. 

```
uint32_t ThreadLocalControllerImpl::averageRps() const {
  if (historical_data_.empty() || global_data_.requests == 0) {
    return 0;
  }
  using std::chrono::seconds;
  std::chrono::microseconds oldestSampleAge = ageOfOldestSample();
  seconds secs = std::max(seconds(1), std::chrono::duration_cast<seconds>(oldestSampleAge));
  if (secs == sampling_window_ || secs == sampling_window_ - seconds(1)) {
    return global_data_.requests / secs.count();
  }
  return 0;
}
```

**Comment by tonya11en** [comment]
> Your suggestion about averageRps() not requiring to be thread-local sounds reasonable, but aren't you afraid that it will require other parts also be transformed into non-thread-local equivalents, which could potentially impact performance?

@ipoval I'm not really worried about performance impact, since we'd only be introducing an atomic incr/decr. We can also benchmark it to ensure there's no impact. I'm not sure what you meant by "seems that it negatively affects some other logic", but I'd assume the unit tests would fail if it affected the behavior of the filter. 

@Jayden-Lind thanks for the suggestion. I'll start with a unit test and see if your suggested change addresses the problem. It's been a while since I've looked at this code, so I'll need to get familiar again.

I should be able to do it this week.

**Comment by tonya11en** [comment]
@ipoval I think https://github.com/envoyproxy/envoy/pull/34257 will fix this. Please verify if you have a chance.

**Comment by ipoval** [comment]
@tonya11en, thanks for the quick turnaround on the fix. We have done testing, and the results still show behaviour that does not wait for the full sampling window of events to start rejections.  The change `seconds secs =
      std::max(sampling_window_, std::chrono::duration_cast<seconds>(ageOfOldestSample()));` does improve the fact that we will react to larger spikes or failed requests, but it won't wait.

**Comment by tonya11en** [comment]
Maybe I'm misunderstanding something, but I don't see an issue here. Your first rejection came 16 seconds after the first request went through the filter and all of your requests will return a 504, which counts as an error by default. So you would have sent ~75 requests, which puts you over the RPS threshold, and your success rate would be 0%.

What is the behavior you expect?

**Comment by ipoval** [comment]
> What is the behaviour you expect?
As I understand the documentation and the algorithm there are 2 conditions that need to be satisfied:

1. request samples need to be accumulated for the whole sliding window internal
2. RPS for the whole sliding window of samples needs to be above the threshold

In the mentioned example the sliding window is set to 60s, and our expectation is that the algorithm would wait for at least 60s before the first rejection happens even if within the sliding window we could have bursts of samples that already satisfy the RPS threshold

**Comment by tonya11en** [comment]
_We should reopen this issue, since the discussion is still ongoing._

Regarding this:
> request samples need to be accumulated for the whole sliding window interval

I think this is our disconnect. I agree with the 2nd condition, but the first one I do not. I think that the RPS threshold parameter gives enough control. If we were to wait for the entire sliding window to pass before activating the admission controller, we open ourselves up to overloading the servers. 

My recommendation is that you increase the RPS threshold to be higher. A threshold of `1`, as you have above, is much too small in my opinion. What happens if you raise the threshold to be 50-75% of your steady-state RPS?

**Comment by ipoval** [comment]
thanks @tonya11en , I do understand your point

**Comment by tonya11en** [comment]
Let's just add a boolean parameter that will give the behavior you expect. We can't change the existing default brehavior, but I think it's fair to have some flag called something like `strict_window_enforcement`.

This should be pretty straightforward to implement if you want to submit the patch. I'm happy to answer questions and review.
