### ISSUE TITLE
`RateLimitQuotaIntegrationTest.TwoRequestWithTokenBucketThrottling` is flakey (TIMEOUT)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#34041]
This test was added in https://github.com/envoyproxy/envoy/pull/33921

as that PR was addressing a different flake im reluctant to revert, but the test takes a very long time and ci analytics gives it a 0% pass rate

![image](https://github.com/envoyproxy/envoy/assets/454682/1354eadb-a431-44e1-ade9-8dc834bcf944)

https://dev.azure.com/cncf/envoy/_build/results?buildId=170010&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=2181edf2-f610-59f2-c43a-04bb9d0bca00&l=457

**Comment by tyxia** [comment]
The newly added test is flaky actually due to the same reason: [pending stats implementation](https://github.com/envoyproxy/envoy/blob/6db20c3e6d224a55ec90494428d062bb43a03fdb/test/extensions/filters/http/rate_limit_quota/integration_test.cc#L642-L644.) 

I am thinking that remove the newly added test and lower the coverage threshold for RLQS

**Comment by phlax** [comment]
thanks @tyxia - probably we should do that as apart from failing its taking a long time

perhaps we should add a ticket re RLQS coverage?
