### ISSUE TITLE
gRPC compression/decompression guide

### ISSUE THREAD

**Issue by eottabom** [envoyproxy/envoy#34366]
*Title*: *I need a guide for gRPC compression/decompression.*

*Description*:
The filter for compression/decompression works only for http1.1.
I would like to know about the guide or method for gRPC compression/uncompression.

If envoy knows proto, it seems that compression and decompression are possible.

I think it will be possible with WASM filter another way.

**Comment by zuercher** [comment]
I don't believe Envoy supports grpc compression/decompression at the moment. For non-transcoding cases it shouldn't matter as the payload is passed through. For transcoding, only uncompressed payloads are supported. I agree that a custom http filter should be able to handle compressed payloads, WASM or otherwise.

**Comment by eottabom** [comment]
Is grpc compression/uncompression not allowed in the Envoy document?

If not, I would like to add it.

It would be nice if it stated that it should be treated with the same filter as WASM.
I hope that an example will be added as well.

**Comment by zuercher** [comment]
I recommend a short document describing your plan. I think it's probably the case that this would be another http filter.

**Comment by eottabom** [comment]
Is this what you want?

![example](https://github.com/envoyproxy/envoy/assets/37852701/4cf006d9-aa5d-4745-a516-73e12aa59306)
