### ISSUE TITLE
Qus: Does envoy support connecting to upstream Redis with TLS enabled?

### ISSUE THREAD

**Issue by AnirKulk** [envoyproxy/envoy#34819]
*Title*: *Qus: Does envoy support connecting to upstream Redis with TLS enabled?*

*Description*:
>I want to use envoy as a front proxy to my Elasticache Redis instance which has TLS enabled. I use the RedisProxy Listener filter and forward the traffic to a cluster identifying my Redis instance. However the connection fails, most likely because the Redis instance requires a TLS connection. If this is supported, I would appreciate if someone can share a simple envoy configuration yaml to achieve this.

Alternatively, can the RedisProxy be configured in such a way that it allows for TLS passthrough i.e. the TLS handshake is handled between the redis client and the redis server and envoy just acts as a passthrough proxy, but still taking care of things such as handle (Clustered) Redis redirects (MOVED)?

Regards
Ani

**Comment by tyxia** [comment]
cced Redis related owners

@msukalski @henryyyang @weisisea

**Comment by weisisea** [comment]
I haven't tried it myself. But it seems feasible to configure Envoy for upstream TLS connections:
https://github.com/salrashid123/envoy_redis/blob/main/README.md
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl

**Comment by solidDoWant** [comment]
~~From what I can tell, this isn't actually supported. If you look closely at [the linked example](https://github.com/salrashid123/envoy_redis/blob/main/client/main.go#L26-L30), the application client/downstream is providing client certificates and enabling TLS.~~

~~I tried something very similar to the linked example, but with redis health checks, and they're all failing. Downstream clients are able to get a `PONG` response to `PING` commands, but I strongly suspect that these are coming from the Envoy proxy filter rather than the upstream.~~

~~Can this be re-opened as a feature request?~~

I take it back - I was using the wrong config for upstream TLS. This is working properly. For anybody else stumbling across this issue, [here is the exact config I'm using](https://github.com/solidDoWant/infra-mk3/blob/831e0bb81a85f16563d736dde51ed198c48f61c4/cluster/gitops/development/harbor/app/envoy-config/redis-only.yaml).
