### ISSUE TITLE
OAuth2 filter: OpenID Connect Back-Channel Logout

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#35225]
*Title*: *OAuth2 filter: OpenID Connect Back-Channel Logout*

*Description*:

The Envoy [OAuth2 filter ](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) supports OIDC authentication by specifying the `openid` scope in the `auth_scopes`, but currently lacks Single LogOut(SLO) support.

The OAuth2 filter currently only supports local logout via the `signout_path` in its configuration. Upon invoking `signout_path`, the OAuth2 filter clears the local session cookies from the user agent, but does not terminate the user's login session with the OP and logout from other RPs.

This behavior poses the following issues:
* The local logout does not effectively work. Even after a local logout, when an end user attempts to access a protected URL again, they can do so after just a few redirects in their browsers, bypassing the need for re-authentication with the OP. This occurs because the OP user session is still valid and active, so the OP authentication process won't prompt for user credentials.
* User can't logout from all RPs.

Implementing support for [OpenID Connect Back-Channel Logout v1.0 Spec](http://openid.net/specs/openid-connect-backchannel-1_0.html) in the OAuth2 filter would offer significant benefits. This feature would enable logout across all relying parties (RPs), ensuring comprehensive session termination in OIDC environments..

[optional *Relevant Links*:]

- [OpenID Connect Back-Channel Logout v1.0 Spec](http://openid.net/specs/openid-connect-backchannel-1_0.html)
- [Envoy Gateway OIDC](https://gateway.envoyproxy.io/docs/tasks/security/oidc/)
- https://github.com/envoyproxy/envoy/issues/21982

Alternatives:

[OpenID Connect Session Management v1.0 Spec](http://openid.net/specs/openid-connect-session-1_0.html) and 
[OpenID Connect Front-Channel Logout v1.0 Spec](http://openid.net/specs/openid-connect-frontchannel-1_0.html) can also be used for SLO.

@arkodg @missBerg @loewenstein

**Comment by missBerg** [comment]
+1

RP logout through back channel logout is really important in multi application platforms (often seen in large SaaS solutions) because you want that when a user logs out of the platform, they have an experience of logging out of the entire platform.

**Comment by KBaichoo** [comment]
cc @mattklein123 @derekargueta

**Comment by derekargueta** [comment]
Sounds good to me

**Comment by zhaohuabing** [comment]
@KBaichoo Could you please label it as no stalebot? It's still valid. Thanks!

**Comment by bplotnick** [comment]
It might be worth separating out OIDC Back-Channel logout task from RP-Initiated Logout task. [RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) is the act of redirecting the user to the OP to indicate that the OP should end its session as well. This is relatively straightforward to implement.

OIDC Back-Channel Logout on the other hand is a way for the OP to broadcast to RPs to end their local sessions. This is actually going to be pretty tricky without some sort of centralized session management. For stateful sessions, this would be a database. But since we use stateless sessions, it would likely require a centralized JWT revocation system, which we do not currently have (not sure if there are plans here).

**Comment by zhaohuabing** [comment]
> The only way to solve this right now is to catch the logout route with a custom handler and send the RefreshToken in the cookies to the OIDC revocation endpoint manually before redirecting back to the app. This isn't trivial as in Envoy Gateway Refresh Token cookie names are not pre-emptible.

@coro If I understand correctly, by invaliding the RefreshToken, the OAuth2 filter won't be able to refresh the ID token, but it still need to wait until the ID token expires, right?

Another question, do you know is Back-Channel Logout supported among different OPs? ASAIK, many OPs like AWS cognito, Google OIDC connect, and Microsoft Entra ID don't support Back_Channel Logout.

**Comment by zhaohuabing** [comment]
> It might be worth separating out OIDC Back-Channel logout task from RP-Initiated Logout task. [RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) is the act of redirecting the user to the OP to indicate that the OP should end its session as well. This is relatively straightforward to implement.

@bplotnick  I like this idea. It would prevent the “slient“ re-login after user logs out, since the user session at the OP would be cleared.

**Comment by jack4it** [comment]
don't want to be a party pooper for sure, but semantically, would it be a bad idea to mix the oauth2 filter with OIDC spec?

**Comment by coro** [comment]
> If I understand correctly, by invalidating the RefreshToken, the OAuth2 filter won't be able to refresh the ID token, but it would still need to wait until the ID token expires, right?

@zhaohuabing Yes you're right, so after revocation we currently redirect to the local session logout endpoint which clears the session cookies then redirects again to the main login page.

> It might be worth separating out OIDC Back-Channel logout task from RP-Initiated Logout task.

@bplotnick You are right, I was conflating the two. What I'm looking for is actually the RP-Initiated Logout as per https://github.com/envoyproxy/envoy/issues/39373

**Comment by zhaohuabing** [comment]
> > If I understand correctly, by invalidating the RefreshToken, the OAuth2 filter won't be able to refresh the ID token, but it would still need to wait until the ID token expires, right?
> 
> [@zhaohuabing](https://github.com/zhaohuabing) Yes you're right, so after revocation we currently redirect to the local session logout endpoint which clears the session cookies then redirects again to the main login page.

@coro SO RP-Initiated Logout will solve your problem and avoid all these additional steps, right?

Do you have a situation where you do need Back-Channel Loggout?

**Comment by coro** [comment]
@zhaohuabing we don't currently have a use case for Back-Channel Logout, and RP-initiated will indeed solve our current problem.

**Comment by MelleKoning** [comment]
We have a deployment where we have put envoy as proxy in front of our UI as wel as Keycloak. Within KeyCloak we do the entire administration of groups, users etc.

Login flow works really nice as users get redirected to the keycloak login page for logging in. However when signout, users are not signed out really. 

We only have the envoy `/oauth2/signout` endpoint configured that the browser-code can hit upon. 

Users are not logged out from keycloak that way, as having a filter for `/oauth2/signout` (before routing took place) does not enable us to define the keycloak logout page with the user-id to logout.

Tried to work around this: When we define a separate `/logout` route that goes to the keycloak logout `realm/url`, that does not work either because the envoy session is not cleared and the URL is missing the user-token, that is: 

When we redirect /logout to the keycloak url of `https://hostname/realms/your-test-realm/protocol/openid-connect/logout?post_logout_redirect_uri=etc`
a html page with the error: Missing parameters: id_token_hint occurs - which we maybe could add via `claim_to_headers` but then still we would be missing the default `/oauth2/signout`. 

Should the UI really have to hit both of `oauth2/signout` and also do the call to KeyCloak-logout page as a two stage process?

Question: Not entirely sure what Back-Channel Logout or RP-initiated would provide, but would that also solve the scenario where an openid/oauth2 like keycloak was placet behind the envoy proxy like in our case?

**Comment by kkumlien** [comment]
Isn't this already possible using the `end_session_endpoint` property of the OAuth2 filter config? See https://www.envoyproxy.io/docs/envoy/v1.36.3/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#extensions-filters-http-oauth2-v3-oauth2config
I will test it soon with Keycloak 26, which supports _OpenID Connect RP-Initiated Logout_ according to keycloak/keycloak#12002

**Comment by Mr-EmPee** [comment]
> Isn't this already possible using the `end_session_endpoint` property of the OAuth2 filter config? See https://www.envoyproxy.io/docs/envoy/v1.36.3/api-v3/extensions/filters/http/oauth2/v3/oauth.proto#extensions-filters-http-oauth2-v3-oauth2config I will test it soon with Keycloak 26, which supports _OpenID Connect RP-Initiated Logout_ according to [keycloak/keycloak#12002](https://github.com/keycloak/keycloak/issues/12002)

It seems a recent change with keycloak:26.5 and envoy:v1.36.3 it works.
