### ISSUE TITLE
OAuth2 filter: stores sessions in Redis

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#35233]
*Title*: *OAuth2 filter: stores sessions in Redis*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

The OAuth2 filter currently stores the bearer token and ID token in user agents using secure cookies, with HMAC verification of the tokens.  Storing tokens in a server-side Redis cache can provide a better security gesture.

The possible implementation approach:
* Moving tokens to a Redis cache on the server side
* Implement a session ID cookie to map user sessions with their respective tokens

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Alternative: [Encrypting the cookies](https://github.com/envoyproxy/envoy/issues/23508) can also enhance the security of the tokens.

@arkodg @missBerg

**Comment by arkodg** [comment]
cc @cpakulski who looked into the feasibility of this

**Comment by derekargueta** [comment]
yeah I've thought of this, similar oauth-proxy. would be pretty neat, I also think it'd be the first use-case in Envoy of Redis for feature functionality and not just proxying.

**Comment by cpakulski** [comment]
I think that it is a common pattern right now to use ext-proc or ext-auth to grpc out of Envoy and have a simple application to decode grpc to Redis:

   _[Envoy] <--grpc--> [sidecar (translate grpc to redis)] <---redis----> [REDIS server]_

In many cases the sidecar simply maps between grpc to Redis. Having ability to directly go to redis from Envoy would definitely simplify the architecture and deployment:

 _[Envoy] <---redis----> [REDIS server]_

**Comment by denniskniep** [comment]
I agree with @cpakulski, an abstraction layer makes sense. Maybe one want to use a different cache solution.

Netflix uses this DataStructure as abstraction Layer at its core:
```
HashMap<String, SortedMap<Bytes, Bytes>>
```
Furthermore they describe their abstraction API for `Get`, `Put`, & `Delete` Requests in [this](https://netflixtechblog.com/introducing-netflixs-key-value-data-abstraction-layer-1ea8a0a11b30) blog post.

What about defining an explicit grpc-service for cache operations with a certain cache specific contract (i.e. see what netflix defined). Then OAuth2 filter calls this grpc-service when it needs to interact with the cache.

We could offer an reference implementation in go which implements that defined grpc-api and "translates" it to Redis api calls

Just to clarify, that my proposal is to implement an dedicated grpc-api for caching instead of using the already existing ext-proc or ext-auth
