### ISSUE TITLE
Why not add POST REST API method in admin module to support the dynamic configuration resources (such as listeners) update ?

### ISSUE THREAD

**Issue by wufanqqfsc** [envoyproxy/envoy#35260]
*Title*: *Proposal to add new admin REST API to support the dynamic resource update via POST methods*

*Description*:
>We know that the envoy admin rest api have some http get methods to get the configuration dumps of resources such as the listeners, So why not add some post method to support the dynamic resources update via admin REST API ?
So that it's very easy to update the LDS configurations via admin module.

**Comment by KBaichoo** [comment]
Hi @wufanqqfsc ,

I think this would create a large amount of complexity e.g. what happens in the cases where you're using a management server or file system xds which contradicts the POST provided? How would you monitor this fleetwide to know what configs your proxys are running? What happens if the proxy restarts (either from crash, hot restart -- how do we make that persist?

I'd suggest looking at file system xds if you aren['t using a management server for your envoys and seeing if you can use that for your usecase.

**Comment by wufanqqfsc** [comment]
@KBaichoo  thanks for your comments here . We are now using the file system xds, 
but as we know that we can't know the file based xds update results. This is not friendly for the file based xds.

And in our case we were not using a xds server because our envoy were running in some embedded system for some memory limitation. And also there is no mature XDS server which was implemented via c++. So using xds server means we should totally re-write a c++ version xDS server, so the cost is a little big...

So the best way may be we add some Post method for the Envoy admin and then hander the resource update via http message and then response the xds update result to the client. 

This is just our idea right now ,and so i ask this question for more suggestions from the envoy community.
