### ISSUE TITLE
prevent the use of custom resolvers for DNS discovery types

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#3553]
When cluster type is STRICT_DNS or LOGICAL_DNS, report an error when if a custom resolver is set on the endpoint Address to guide users to the correct configuration.

See discussion here: https://github.com/envoyproxy/envoy/pull/3261/files#r188243657

**Comment by Soumya117** [comment]
Is this issue still open and no one is working? If yes then i can start this one.

**Comment by mattklein123** [comment]
@Soumya117 feel free to work on it!

**Comment by Soumya117** [comment]
I went through the code and i might need some more clarity regarding what text should i put in the error! And i found one place where it could be changed (upstream_impl.cc) where we are actually going through dns resolvers and proceeding on the basis of envoy::api::v2::Cluster::STATIC / LOGICAL. Should i be looking somewhere else ?

**Comment by zuercher** [comment]
I'm going to correct the issue description in a moment, but it should say "STRICT_DNS" not "STATIC_DNS".

I think you want to add a check in the constructors of LogicalDnsCluster (logical_dns_cluster.cc) and StrictDnsClusterImpl (upstream_impl.cc). The Address objects that both use to obtain DNS names should not have a custom resolver set.

**Comment by Bplotka** [comment]
Hello!
Can we have rationales behind this? Why cannot one have custom resolver that is asynchronous, and use it with LOGICAL_DNS or STRICT_DNS? 

I tried to get these from the mentioned discussion:
> Should we just say that custom resolvers can't be used at all with DNS discovery types and block it? I don't think it really makes sense and is confusing. If we do that, I think we can have error checking / error messages to guide people in the right direction...
Why is it confusing and does not make sense? Because Resolver interface does not have hooks for async resolution?

> This would be reasonable. I think if we had the custom resolvers able to operate async, and some hooks to detect DNS changes, we could replace the hardcoded DNS cluster types with just resolver extensions. But, moving the resolver extension model to be expressive enough and then plumbing this would be a fair chunk of work.
I think it does not really make sense to have an interface for a custom resolver that is just synchronous for such fast proxy like envoy. 

I assume the only rationale behind preventing those is that.. it is hard to implement? or hard to define an interface for it?
