### ISSUE TITLE
opentelemetry tracing provider doesn't respect client_sampling when both traceparent and x-client-trace-id header is present

### ISSUE THREAD

**Issue by yuanguolang** [envoyproxy/envoy#35721]
*Title*: *opentelemetry tracing provider doesn't respect client_sampling when both traceparent and x-client-trace-id header is present*

*Description*:
Hi, we enabled opentelemtry tracing provider and we found out `client_sampling` in `tracing` is not applied if the incoming request has both `traceparent` and `x-client-trace-id` header. We also use `x-request-id` by default. Even if we set `client_sampling` to 0%, envoy still exports spans based on sample flag in parent context(`traceparent`) header. And envoy code seems align with the behavior. I wonder if this is the expected behavior, which means if envoy can extract the parent context from the incoming request, envoy will respect the sampling decision in the downstream, then no sampling decision will be applied.

in conn-manager, envoy startspan no matter what tracing decision made earlier:

https://github.com/envoyproxy/envoy/blob/6b9db09c69965d5bfb37bdd29693f8b7f9e9e9ec/source/common/http/conn_manager_impl.cc#L1397-L1398

in opentelemetry tracer, if envoy can extract parent context, which is a valid traceparent header, it will start a span from parent context, ignoring tracing decision made earlier.
https://github.com/envoyproxy/envoy/blob/6b9db09c69965d5bfb37bdd29693f8b7f9e9e9ec/source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc#L56-L68

thank you!

**Comment by dmehala** [comment]
The interesting part is here: https://github.com/envoyproxy/envoy/blob/6b9db09c69965d5bfb37bdd29693f8b7f9e9e9ec/source/extensions/tracers/opentelemetry/tracer.cc#L157-L165

The question boils down to: what takes precedence? Header or Envoy's tracing decision?

**Comment by joaopgrassi** [comment]
When `if (!extractor.propagationHeaderPresent()) { ` is true, meaning, there's no `traceparent`, Envoy invokes `startSpan` and sets the sampling decision that is already there, which should be the percentage one if you don't have anything else configured (a custom sampler in the OTel tracer). It will call this line https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/opentelemetry/tracer.cc#L261 which should set whatever tracing decision Envoy made.

Now, if the incoming request has a `traceparent` header, then the tracer respects that and uses whatever sampling decision was already recorded: https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/opentelemetry/tracer.cc#L284. This is the expected behavior, otherwise you may break the entire trace chain.
