### ISSUE TITLE
Memory allocator manager bytes release not working

### ISSUE THREAD

**Issue by singamL887** [envoyproxy/envoy#37092]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
I have been trying to use the memory allocator manager "bytes_to_release" on envoy 1.31. I have been using the following bootstrap configuration file 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    {
      "stats_config": {
        "stats_matcher": {
          "inclusion_list": {
            "patterns": [
              {
                "prefix": "overload"
              }
            ]
          }
        }
      },
      "memory_allocator_manager": {
        "bytes_to_release": 1024,
        "memory_release_interval": {
          "seconds": 1
        }
      },
      "overload_manager": {
        "refresh_interval": {
          "seconds": 1
        },
        "actions": [
          {
            "name": "envoy.overload_actions.shrink_heap",
            "triggers": [
              {
                "threshold": {
                  "value": 0.20
                },
                "name": "envoy.resource_monitors.fixed_heap"
              }
            ]
          },
          {
            "name": "envoy.overload_actions.stop_accepting_requests",
            "triggers": [
              {
                "threshold": {
                  "value": 0.90
                },
                "name": "envoy.resource_monitors.fixed_heap"
              }
            ]
          }
        ],
        "resource_monitors": [
          {
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig",
              "max_heap_size_bytes": 19874368
            },
            "name": "envoy.resource_monitors.fixed_heap"
          }
        ]
      }
    }
```

Here, had a fortio server and a client. I have sent traffic from the client to server and observed an increase in "heap_size". After the traffic is terminated, I was not able to see any decrease in "heap_size". 

Is there any issue in my test scenario or configuration?

My memory stats after the traffic is sent to the server, heap memory increased and the server readiness probe starts to fail 

```
{
"allocated": "12435616",
"heap_size": "23068672",
"pageheap_unmapped": "3727360",
"pageheap_free": "8192",
"total_thread_cache": "4714552",
"total_physical_bytes": "24134110"
}
```

My memory stats after 24 hours 

```
{
"allocated": "11122448",
"heap_size": "23068672",
"pageheap_unmapped": "3956736",
"pageheap_free": "0",
"total_thread_cache": "4835256",
"total_physical_bytes": "23904734"
}
```

So I don't see any decrease here. What is my mistake?

When a proxy stops accepting connections when heap size goes beyond the configured threshold, will this configuration help in decreasing the heap size and making it accept new connections?

Thank You

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by sakatkoori** [comment]
@nezdolik, could you please help check this, I see that, you were raised PR https://github.com/envoyproxy/envoy/pull/32589, is the testing we do is correct or any problem that you see ?

**Comment by sakatkoori** [comment]
@nezdolik did you get a chance to check? Could you please help check and suggest, this is bit important to us so.

**Comment by nezdolik** [comment]
@sakatkoori both mechanisms (shrink heap overload action and memory allocator manager) attempt to release free memory but there is no 100% guarantee it will actually happen due to multiple layers involved. They use same tcmalloc function `tcmalloc::MallocExtension::ReleaseMemoryToSystem`. Under the hood tcmalloc itself has bunch of optimizations on when the memory should be released, e.g. if memory is fragmented or too much was released during past round it will not attempt to release memory on current round. When tcmalloc actually decides to release the memory it does a syscall (via madvise(MADV_DONT_NEED)) letting the OS know that memory can be released. OS makes the final decision if memory should be released immediately or postponed for a process. Some more info [here](https://github.com/google/tcmalloc/blob/master/docs/stats.md?plain=1#L85).
On Envoy side you could check is any memory releasing is actually happening by checking if counter `allocator_manager_stats_.released_by_timer` is increasing over time.
You could experiment with the `bytes_to_release` and use larger values (like 16MB) and less frequent interval. I have observed that memory releasing works better with larger values, also some tcmalloc details are highlighted in this [comment](https://github.com/google/tcmalloc/issues/215#issuecomment-1848997994).
