### ISSUE TITLE
Will Envoy Proxy support Hyperlight?

### ISSUE THREAD

**Issue by shubham1172** [envoyproxy/envoy#37109]
*Title*: Envoy Proxy extension with Hyperlight micro-VMs

*Description*:
>Envoy Proxy allows certain extension points like Go filters, WASM, etc. With the recent release of https://github.com/hyperlight-dev/hyperlight, this is a question to the community if this is something Envoy should support? It could benefit as yet another fast extension point for Envoy which can be safer than WASM.

[optional *Relevant Links*:]
>Current state of WASM - https://github.com/envoyproxy/envoy/issues/35420

**Comment by yanavlasov** [comment]
There are currently no plans to add hyperlight. We will accept it as a contribution if you have resources to implement this.

**Comment by kyessenov** [comment]
CC @keithmattix 

I am not sure KVM privilege makes sense as a requirement for Envoy, especially when it runs sandboxed in containers.

**Comment by martijneken** [comment]
Not actively being worked on / supported today, but we do have it on the Proxy-Wasm roadmap because we are excited about the cheaper (thread-level) sandboxing: https://github.com/proxy-wasm/spec/pull/74

Progress on the Hyperlight side is periodically discussed in the Proxy-Wasm community meeting, and the notes are linked from here: https://github.com/proxy-wasm/community.
