### ISSUE TITLE
subset load balancer scalability concerns

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3929]
Envoy is becoming unstable (throughput drops) due to CPU spikes (>40% usage) when using the subset LB under the following conditions:

* an upstream cluster with > 1k endpoints
* where each endpoint has 3 metadata keys
* and there's at least 6 subsets active at any time
* and healthchecks change state at a rate of ~40/sec, which happens during deploys or when the cluster is rapidly scaling up or down

Although we've done some work to ensure rebuilding the subset LB is more efficient (https://github.com/envoyproxy/envoy/commit/17efc838016101f7607fbb9a27151da606e0bd13), the spikes — albeit reduced a bit — are still there. 

Relaxing the healtcheck thresholds would help. Though, it could also yield the undesired result of having valid healthchecks kick in when it's too late. 

A better solution might be to rate limit or coalesce healthcheck state changes when there's too many of them being triggered. That could maybe be done somewhere around:

https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L583.

There's also the possibility, previously mentioned by @mattklein123, of moving the subset LB rebuild work into the main thread and then posting the results. 

Ideally, the subset LB should be able to operate under the above conditions without any manual tuning.

Thoughts?

cc: @zuercher @trjordan @derekargueta @brian-pane

**Comment by mattklein123** [comment]
cc @htuch @jmarantz also.

Yeah I think there are a variety of things that we can do here and I've been thinking about this off and on for a while.

One of the most obvious (and easy ones IMO) is the one you point out which is to coalesce HC changes. I would suggest that we add a new config option for a cluster which specifies the max HC enforcement delay (name pending). Then, when there is an HC change, we optionally kick off a timer, the end of which we actually do all the updates. This mechanism would also be highly useful for the consistent load balancers which are also computationally expensive.

I also think that we should look into making the subset LB thread aware. I'm not sure how much work this would be, but it would also significantly reduce CPU usage on many core boxes, and also keep the workers from locking up. (This is the exact reason I implemented the thread aware stuff, because the ketama changes were locking uyp the workers).

**Comment by rgs1** [comment]
@mattklein123 for coalescing HC changes, I am thinking we could merge the updates and deliver them at once as opposed to doing it sequentially. Maybe it could be configurable. Thoughts?

**Comment by mattklein123** [comment]
Yes, sorry, I was assuming merge. In actuality, it would be harder and more costly to do sequentially :) (Since you would need to keep a list vs. just redo the healthy scan when the timer expires).

**Comment by rgs1** [comment]
@mattklein123 something like https://github.com/envoyproxy/envoy/pull/3941 perhaps?

**Comment by rgs1** [comment]
I think this can safely be closed at this point, given it's been running at scale pretty nicely for a couple of years.

cc: @fishcakez
