### ISSUE TITLE
Drop official support for CentOS build image

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#3937]
There is no official build for CentOS provided by LLVM folks, so we're stuck on old / community-maintained version of LLVM/clang (currently using 5.0, when 6.0 has been out for 4+ months and 7.0 is around the corner), which blocks update of the Ubuntu build image.

This is suboptimal considering the fact that Envoy is using bleeding-edge features of the C++ language.

Also, it seems that we don't use / verify the CentOS build image anywhere.

Thoughts?

cc @mattklein123 @lizan @htuch @ggreenway @jwfang

**Comment by ggreenway** [comment]
Can you elaborate on what is being blocked by using the old clang on centos? I've seen various comments/questions about centos in envoy forums and issues, so I presume some people are using this build, so I'm hesitant to pull the plug on it.

**Comment by PiotrSikora** [comment]
1. We're hardcoding version number in a few scripts (`ci/build_setup.sh`, `tools/check_format.py`),
2. `clang-format-5.0` produces different output than `clang-format-6.0`.

Since we don't use CentOS build image anywhere on the official CI, those might be fine, but it's hard to tell if/when we break something, since it's unmaintained build image.

**Comment by htuch** [comment]
I wonder if we can adopt a policy for build images that, like with extensions, they need an owner/sponsor to keep alive.

**Comment by lizan** [comment]
Is it possible to keep CentOS image but drop LLVM/Clang from it? It still can be used for building release/test binaries with GCC.

**Comment by ggreenway** [comment]
I would lean towards option (2). We already use different versions of gcc between different platforms, so it doesn't seem like different versions of clang should be more of a problem.

**Comment by lizan** [comment]
different versions of clang would cause:
- clang-format output is slightly different between versions, we can make clang-6 canonical and enforce them in CI.
- sanitizers behaves differently on (likely) false positives/negatives, they need to be handled correctly in tests (e.g. tag no_asan, no_tsan).

I'm leaning towards (3) and leave CentOS build/test with GCC as best-effort.

**Comment by ggreenway** [comment]
I agree we need to define a specific version of clang-format that we format with, and possibly check_format won't work on CentOS. 

For the actual build, I think I'm just arguing for not removing the existing tooling around CentOS. We don't run that build in CI anyways, so it's not officially supported in the same sense. I think various people/groups/companies already compile envoy for different linux flavors and versions, probably using whatever compiler is provided with their distro, so we already have issues with multiple compilers. Occasionally we get a PR that fixes the build for a different version of the compiler due to different warnings and whatnot, and I think that system (accepting PRs as they come, with the official project not devoting any effort to compiling with those compiler versions ourselves) is working fine.

So I'm advocating for leaving the CentOS stuff alone, and if a community member notices that something is broken, they can send a PR.
