### ISSUE TITLE
Support Unix Domain Socket Mode Configuration

### ISSUE THREAD

**Issue by llchan** [envoyproxy/envoy#4005]
It would be useful to be able to specify the mode of a listening unix domain socket.

I think this requires two changes:
1. Add a mode field to the `envoy.api.v2.core.Pipe` proto.
2. Create the socket with the specified mode in address_impl.cc. I think this can be done via fchmod before the bind, but this may not be totally portable.

**Comment by mattklein123** [comment]
@ggreenway thoughts here?

**Comment by ggreenway** [comment]
I agree that it would be useful. It also makes sense to be able to set the group of the socket-file.

This only applies to listeners, so I don't know that attaching it to core.Pipe is the right place, because that is used for both listen and connect. On the other hand, there isn't a good place to put that config, so maybe we could add it to core.Pipe and document that these fields are only used in some contexts.

**Comment by llchan** [comment]
Since the listener configs take in a oneof, we could potentially introduce a new `ListeningPipe` proto or something. That way we retain backwards compatibility with existing configs using `Pipe` (possibly deprecating it for a later removal), and the new type is listener-specific and can add stuff like mode/group/etc.

Not sure if it's worth the extra noise though.

**Comment by mattklein123** [comment]
@llchan I would be fine with either option. Agreed the oneof is probably cleaner. You could even include Pipe inside the ListeningPipe such that ListeningPipe only has the extra options.
