### ISSUE TITLE
Use clang to build release binary.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#4158]
From the [original PR](https://github.com/envoyproxy/envoy/pull/4138):
```
Loading 1000 static listeners in a binary built with gcc takes ~51s,
but only ~1.5s (34x faster) in a binary built with clang.
```
The problem was mitigated by #4117, which reduced number of preallocated elements in the `LcTrie`, though the difference in performance still exists (due to unpacked `LcNode`).

cc @mattklein123 @htuch @alyssawilk @lizan

**Comment by uromahn** [comment]
We are planning to introduce Envoy across our entire system and CentOS support is an absolute "must" for us. We are running our entire system on it and having everything re-certified with a different OS is just too expensive and time consuming.

I personally don't object the switch to clang as long as the current build for CentOS stays there.
I have experimented building a newer toolchain with clang6 for CentOS from source but the build is painfully slow and I wasn't getting much success so far (since I am not a C++ expert).
