### ISSUE TITLE
Verify certificates with common name

### ISSUE THREAD

**Issue by myidpt** [envoyproxy/envoy#4174]
*Title*: *Envoy needs to verify certificates using CN instead of SAN*

*Description*:
>Customers request Istio to support TLS authentication with legacy systems using certificates with identities encoded in CN instead of SAN. The CN could be IP address or FQDN.

**Comment by PiotrSikora** [comment]
@myidpt could you elaborate on why this is needed in Envoy? If Citadel and/or other CAs produce certificates with both CN and SAN, then Envoy can verify SAN and legacy systems can verify CN.

Reading the linked Istio issue, it seems that the problem is that Citadel doesn't produce certificates compatible with legacy systems, not that Envoy cannot verify certificates produces by legacy CAs.

Note: this is trivial to implement, but the world moved from CN to SAN, so I'd like to have a valid use case before adding this outdated verification method.

cc @ggreenway

**Comment by myidpt** [comment]
Yes I think the linked issue is not related to this feature. I think we can temporarily close this issue and reopen it when we need.
