### ISSUE TITLE
data-plane-api fails to build on master

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4218]
CI for data-plane-api has been failing since gogoproto was updated at https://github.com/envoyproxy/data-plane-api/commit/43bc9adb833ceda21fab346e443db0853517e699

Seems like the issue is related to building the go proto libraries, which is why it wasn't caught in envoyproxy/envoy CI. I tried to take a look but I'm not familiar enough with the go/bazel toolchain.

**Comment by danielhochman** [comment]
to fix this, `io_bazel_rules_go` needs to be updated to `>=0.9.0` in [data-plane-api/WORKSPACE](https://github.com/envoyproxy/data-plane-api/blob/8e09edd8fe81be46dc179c678f5f65c40ae7af63/WORKSPACE#L40-L44). however, i think the larger issue is that we're not sharing a WORKSPACE or dependencies from the main project over to the mirror. for example, the main project is on `0.11.1`: https://github.com/envoyproxy/envoy/blob/f218185ce1d6b8f31c89135d79932481fc348762/bazel/repository_locations.bzl#L127-L130

pinging @htuch for thoughts since he did a lot of the work on the original sync process.

**Comment by htuch** [comment]
I think we should reduce the amount of duplication here and switch to a single source of truth. Basically, just need to add to the copy script more places where we copy across and also verify this does the right thing. @snowp do you have cycles to work on this? If not, I might be able to get around to it later this week.

**Comment by snowp** [comment]
I'm afraid I won't be able to get to it this week, and I'll be OOO the following week

**Comment by snowp** [comment]
I have some more time on my hand and can pick this up. 

@htuch What were you thinking could be copied over in addition to what is already moved? From `ci/api_mirror.sh` it seems like the only things not copied over is `ci/`, `WORKSAPCE`, `LICENSE` and dotfiles. Is your idea to copy over `WORKSPACE` wholesale instead of using `api_dependencies` to share some of the external deps?

**Comment by htuch** [comment]
@snowp yeah, I think it might just be `WORKSPACE` based on what you say.
