### ISSUE TITLE
gRPC route matching

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4400]
Currently Envoy allows matching a gRPC request by matching on the content-type. It would be nice with first-class gRPC matching support to 1) make it less cumbersome to match gRPC traffic and 2) make it easier to handle gRPC content type variations such as `application/grpc+proto`. 

I'm imagining it would just be another option on `RouteMatch` which calls into `Envoy::Grpc::Common::hasGrpcContentType`

**Comment by htuch** [comment]
@snowp seems reasonable, Envoy should have first-class gRPC support here. FWIW, there is a little known and used experimental ALPN for gRPC `grpc-exp`. The Google C++ and Java (but not Go) clients support this.

**Comment by sgammon** [comment]
@htuch, @snowp, was support added for the `grpc-exp` ALPN token, or no? just wondering as it seems dispatching grpc over `h2` works but not `grpc-exp`.

**Comment by htuch** [comment]
ALPN is configurable on Envoy, so you can just list this in `alpn_protocols`. But, this isn't a reliable way to route or select for gRPC, since it's not a real standard.

**Comment by sgammon** [comment]
@htuch thank you for the swift reply :)

understood, and i am successfully advertising `grpc-exp` using the config you mention. Envoy even selects `grpc-exp` upstream with my Java-based gRPC server.

however, i'm hitting the routing issue - i can't properly route gRPC _through_ envoy, from a client, unless i force the client to select `h2`, either by prioritizing it on the client end or withholding advertisement of `grpc-exp` on Envoy's side.

we have gRPC-Java on both sides, and we control the ecosystem end-to-end in our use case. so we want to use `grpc-exp` if we can. is there a way to do this? and if not, would Envoy be open to a contribution to allow it?

after inspecting with wireshark, Envoy itself selects `grpc-exp` upstream, advertises it downstream, but just doesn't route with it once it is selected (the log line from envoy ends up as `HTTP/1.1` which is of course not the case).

**Comment by htuch** [comment]
@sgammon good point, we probably don't have the ability to switch to H2 codec. @mattklein123 would it be reasonable to also support `grpc-exp` here?

FWIW, some historical context. `grpc-exp` is something I completely made up when working on something internally which needed client side support for upgrading, and I was involved in making the gRPC client side changes to support this. That specific use case went away over time, but this support still exists in gRPC clients. I would love there to be a standard ALPN method that we know going forward will be supported. CC @markdroth do you have any thoughts?

**Comment by markdroth** [comment]
The best person on our team to comment about ALPN-related issues is @ejona86.

**Comment by sgammon** [comment]
@htuch thank you for the context on that. i have a question, then, because mostly my concern here is a failure to handshake between gRPC Java and our production systems (AFAIK, `grpc-exp` is supported in Java and C++ clients).

we host on google cloud in GKE, and we front our stuff with GSLB (using the new network endpoint groups feature). GSLB advertises `grpc-exp`, _in front of_ `h2` no less (see [here](https://www.ssllabs.com/ssltest/analyze.html?d=api.bloombox.cloud&s=2600%3a1901%3a0%3a945d%3a0%3a0%3a0%3a0&hideResults=on)), curiously only over NPN and not ALPN, though:
<img width="420" alt="screen shot 2019-02-06 at 11 51 08 am" src="https://user-images.githubusercontent.com/171897/52369409-8967e000-2a05-11e9-98da-b14e58cbcd76.png">

this is why we're hoping to support routing via `grpc-exp`, just in case clients decide to use it. the `grpc-java` SDK still includes it [here](https://github.com/grpc/grpc-java/blob/32d50eb3b3ed9d0701ad352dacc7d71e2d6425f1/netty/src/main/java/io/grpc/netty/GrpcSslContexts.java#L62) via both ALPN and NPN.

anyway, here is my question. when negotiating `grpc-exp`, is there any functional difference with `h2`? or is it just a hint that grpc is being used over the wire? i'm only curious if there is any expected performance loss, or something, if we force `h2`.

thank you again for the quick response

**Comment by sgammon** [comment]
depending on your answer @htuch,  i'm not sure if the right move is to propose removing `grpc-exp` from `grpc-java`, vs. patching envoy somehow to allow routing by various ALPN tags, vs. some other approach i am not thinking of

we are happy to contribute or test or otherwise help however needed :shipit:

**Comment by htuch** [comment]
You're talking about GCLB I think, right? We use both GSLB and GCLB to mean different but related things. I know why GCLB advertises `grpc-exp`, since this is code I wrote, but as mentioned above, it was there to address a use case that doesn't exist today, but it hasn't been turned down.

I'm pretty surprised this only happens only over NPN; gRPC is strictly HTTP/2, which is strictly ALPN, NPN is deprecated. 

It's purely a hint, telling the content is HTTP/2 and also gRPC. gRPC only expects `h2` as per its wire format.

I think it all comes down to what gRPC team (@ejona86) think we should do long term about ALPN. Is this going to be a thing, will `grpc-exp` get replaced or just turned down?

**Comment by sgammon** [comment]
@htuch i will defer to you regarding terminology, i am assuming GCLB == Google Cloud LB in which case yes. i am trying to illustrate that we use layer 7 LB not NLB but i presume that is obvious at this point.

thank you, i have what i need for us, but i'll keep monitoring here in case we can test or upgrade

**Comment by mattklein123** [comment]
Sorry I think I'm missing something here, but how is grpc-exp different from h2? Can't we still route in content-type?

**Comment by htuch** [comment]
`grpc-exp` would let you make the route decision earlier, e.g. at filter chain match.

**Comment by mattklein123** [comment]
But isn't that already supported? I thought we allow matching on along name? Or is the issue that we just have to alias grpc-exp to h2 during codec selection? If so that is a trivial change.

**Comment by htuch** [comment]
Yes, I think you would need to alias during codec selection, and it's probably trivial. The question is whether it's worth supporting at all given that `grpc-exp` is not standardized.

**Comment by ejona86** [comment]
To be clear to everyone, the "exp" in `grpc-exp` means "experimental". It was added to play with things like this, but to be productionized I was expecting to replace it with a new string.

`grpc-exp` is the same as `h2` from grpc's perspective. The assumed semantics would be that it only contains grpc, but otherwise speaks normal HTTP/2. There should probably never be protocol differences; any protocol differences should probably be negotiated with SETTINGS.

@sgammon, the difference in NPN and ALPN is likely because ssllabs can't detect unknown protocols with ALPN. With NPN the server returns the full list of protocols it supports. With ALPN the client sends the list and the server just selects one. To form its list, ssllabs is probably trying all the currently defined protocols and seeing which ones the server selects.

**Comment by sgammon** [comment]
@ejona86 thank you, that makes a ton of sense. i am really not worried about it now that i understand its intended purpose. for our own sake, forcing prioritized negotiation of `h2` in `grpc-java` fixes the issue.

perhaps it would be good to remove `grpc-exp` from the clients if there isn't going to be support for it moving forward. i am not 100% certain that it was causing our handshake errors (it seems like it would have to be on JDK SSL which we don't use), but they did clear up once i installed an ALPN configuration that omitted `grpc-exp` or placed it after `h2` in the proposed list of protocols from the client.

in any case, thank you all for your quick responses and insight, it's cool to know what it's for.

**Comment by ejona86** [comment]
> for our own sake, forcing prioritized negotiation of h2 in grpc-java fixes the issue.

> but they did clear up once i installed an ALPN configuration that omitted `grpc-exp` or placed it after `h2` in the proposed list of protocols from the client.

@sgammon, that really sounds like a bug in the server. The server should select h2 if it doesn't understand grpc-exp. I'd suggest running wireshark and looking at the server's reply (ServerHello ideally, but it may be an error instead). The ALPN protocol selected is in the ALPN extension.

![screenshot from 2019-02-12 09-41-49](https://user-images.githubusercontent.com/2811396/52656072-7001e080-2eaa-11e9-9909-e12f7c6cb33f.png)

(This is a recording of a grpc-java client talking to a grpc-java server.)

It would probably be fair to remove grpc-exp since nothing has really happened with it, and apparently we are selecting it today when we didn't intend to...

**Comment by sgammon** [comment]
@ejona86 if memory serves, it was originally a TLS alert, post-handshake. i've caught it over wireshark. ill try and dig up the screenshot.

in the meantime, it's easy when reading the source to interpret `grpc-exp` as needing to be prioritized, because that's what `grpc-java` itself does (see [here, where it is prioritized both for NPN and ALPN](https://github.com/grpc/grpc-java/blob/32d50eb3b3ed9d0701ad352dacc7d71e2d6425f1/netty/src/main/java/io/grpc/netty/GrpcSslContexts.java#L73), and [here where a test makes sure it's prioritized](https://github.com/grpc/grpc-java/blob/81da3eb95be37fa0647ce8da2e19de96ab84c600/netty/src/test/java/io/grpc/netty/GrpcSslContextsTest.java#L32), as long as i'm reading the code correctly).

meanwhile, because GCLB priotizes it over NPN, it seems from a developer's perspective that ALPN should match. but this explanation makes a ton of sense (i.e. Qualys doesn't know to offer it over ALPN in the `ClientHello`, so it consequently doesn't show up in the `ServerHello` coming back in diagnostics). maybe the solution is to document the difference somewhere, perhaps in `SECURITY.md`, which java devs have a practice of checking? i could file a PR. that is, if the ALPN tag for `grpc-exp` should stay in at all.

in any case, this was the behavior we were seeing (best guess until i dig up that screenshot. numbers were observed behavior):
- 1: `grpc-java` `<- TLS with ALPN "grpc-exp, h2" ->` GCLB
- 2: negotiates `grpc-exp`
- GCLB `<- TLS presumably with selected ALPN from client "grpc-exp" ->` [ESP](https://github.com/cloudendpoints/esp)
- GCLB `<-- TLS alert (presumably) -->` ESP
- 3: `grpc-java` `<-- TLS alert after handshake success -->` GCLB

we haven't been able to solve the above TLS alert for quite some time. we also noticed that this only occurred when traversing GCLB with external traffic - within our networks, i.e. direct gRPC over TLS, worked fine.

this is why @htuch's comment above caught my eye: because we only see this issue with our Java layer from the client side (rather than Swift, for instance, which doesn't support negotiating `grpc-exp`, because iirc it calls into Cgrpc, rather than C++ gRPC). we later switched to Envoy, and this surfaced again after noticing the following behavior locally, which also failed:
- 1: `grpc-java` `<- TLS with ALPN "grpc-exp,h2" ->` Envoy
- 2: Envoy is configured to select `grpc-exp`, so they agree on `grpc-exp`
- 3: Envoy doesn't match `grpc-exp` to our backend, or doesn't route it, or whatever, and fails the handshake (hence, the handshake errors i am talking about originally itt)

what prompted me to request that it be routable from the frontend, was that we observed the following behavior too (after removing `grpc-exp` from our own `ClientHello`):
- 1: `grpc-java` `<- TLS with ALPN "h2" ->` Envoy
- 2: only `h2` is listed on both sides, so that is what is selected
- 3: Envoy `<- TLS with ALPN "grpc-exp, h2" ->` `grpc-java server`
- 4: they select `grpc-exp` and everything is great and nobody got hurt

in particular point 4 in that final flow above is what inspired me to say, well, if GCLB supports it and priotizes it, and Envoy negotiates it upstream, all i need is Envoy to route it on the frontend and i can use my `grpc-exp` all the way up and down my stack.

but after the explanation above, which totally makes sense, i've forced `h2` to priotize from the client-side (that final flow above), and things work fine for now. we do this with the following patch to our gRPC clients in Java, when they are communicating externally (which, for us, traverses through GCLB):

```kotlin
/**
   * Prepare the SSL context for this service client.
   */
  protected open fun prepSSLContext(sslContext: SslContextBuilder): SslContextBuilder {
    // set ALPN config
    sslContext.applicationProtocolConfig(ApplicationProtocolConfig(
      ApplicationProtocolConfig.Protocol.ALPN,
      ApplicationProtocolConfig.SelectorFailureBehavior.CHOOSE_MY_LAST_PROTOCOL,
      ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
      "h2"  //, "grpc-exp" ISSUE: Envoy does not route based on this
    ))
   // ...
}
```

**Comment by sgammon** [comment]
@ejona86 sorry for the russian novel but TLS is thorny 😄 
hope that makes sense

**Comment by htuch** [comment]
@sgammon thanks for the analysis. @ejona86 WDYT about either standardizing `grpc-exp` or dropping it? It wold be great if we can avoid this pitfall when using a mix of Google gRPC libs and non-Google.
