### ISSUE TITLE
Redis PubSub primitives support

### ISSUE THREAD

**Issue by steeve** [envoyproxy/envoy#4424]
*Description*:
According to [1], Envoy doesn't support the Redis PubSub primitives such as
`BLPOP`, `SUBSCRIBE`, `UNSUBSCRIBE`, `PUBLISH`.

However, looking at [2], it looks like they should be pretty trivial to add.
Since things look pretty simple, I'm wondering if there's a reason they are
not at this time?

*Relevant Links*:
1. https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis#supported-commands
2. https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/network/redis_proxy/supported_commands.h

Thanks!

**Comment by danielhochman** [comment]
Currently, the proxy only supports request/response semantics. `SUBSCRIBE` and other PubSub violate this because you need to allocate a single long-lived connection decoding responses as they come.

`BLPOP` and other blocking commands could be supported, though still not trivial as much of the timeout logic would need modification along with connection allocation changes.

Most Redis proxies do not support these commands due to the complexity of managing them during cluster membership changes, managing stateful connections, etc. That's not to say that it can't be added, just that the Redis proxy was originally built to have feature parity with other popular proxies.

**Comment by steeve** [comment]
That's very clear, thank you! Closing the ticket.

Regarding stateful connection and membership changes, does Envoy have similar semantics for, say, gRPC streams? If so, would a hypothetical support from the Redis proxy "piggy-back" on it or are we talking about a full reimplementation?
