### ISSUE TITLE
Add ability to drain the listeners using the admin interface

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#4460]
*Title*: Add ability to drain the listeners using the admin interface

*Description*:
Drain the listeners on demand, with the assumption that we're going to shutdown shortly afterwards, so future updates to those listeners should be ignored.

cc @nmittler

**Comment by ramaraochavali** [comment]
It may be useful/partial solution to address this issue as https://github.com/istio/istio/issues/7665

**Comment by cmluciano** [comment]
@PiotrSikora I haven't explored this part deeply, but isn't this supposed to be the desired effect of "/quitquitquit" or is that behavior more synonymous with "/abortabortabort" ?

**Comment by mattklein123** [comment]
This should be pretty easily doable by allowing programmatic access to the existing drain functionality that is kicked off as part of hot restart.

**Comment by PiotrSikora** [comment]
@cmluciano it's the first half of `/quitquitquit`, really. The major use case for use would be to stop accepting incoming connections when acting as a sidecar, but still let the application to make outgoing connections (see #4461).

**Comment by bplotnick** [comment]
I think this is related to our need for per-listener shutdown - we run a single shared envoy per host instead of one-per-sidecar. If (our equivalent of) a pod is going down, we want to be able to just shut down that ingress listener. We do this today with our [healthcheck cache](https://github.com/Yelp/hacheck) , but we'll want to do this with Envoy in the future.

I think this might actually make the implementation easier, since if you had per-listener control, i presume that you could just drain the ingress listener but still keep the egress listener alive.

**Comment by ramaraochavali** [comment]
@mattklein123 We are interested in this feature. Just want to understand at a high level if the following is sufficient 
- add a admin endpoint `/drain_listeners`  that drains all listeners.
- add additional parameter like `/drain_listeners?inboundonly` - will drain only inbound listeners because that is what most people would want when a rolling upgrade happens because incoming connection should be stopped while inflight work should continue which may use outbound listeners. Since traffic direction is added to listener now - we can easily distinguish inbound/outbound listeners.

What do you think about that approach?

**Comment by mattklein123** [comment]
@ramaraochavali this sounds good to me. I think you could later also add a query param to even drain by name, etc.

**Comment by deiwin** [comment]
Wonder if the `?inboundonly` parameter could be added to `/healthcheck/fail` as well, to also initiate draining for inbound listeners only. What do you think?
