### ISSUE TITLE
Generic attribute bag shared by all filters

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#4528]
I was under the impression that the RequestInfo::FilterState (per request or per connection) is an object that can be modified by multiple (successive) filters. It turns out that its a write-once and read only object. @curiouserrandy any reason why you set the shared requestInfo::Filterstate to be a write-once thing instead of a model where multiple filters can write to same object?

I propose we move towards a generic attribute bag kind of system, such that the filters in a chain can append/update any attributes they want for that connection or request. This will allow all the reporting filters to consume info generated by all downstream filters, and emit access logs/reports with info gathered by everyone. Similarly, this will allow policy engines to act on data (about connection/request) gathered by multiple filters which have their own domain expertise.

 For example, consider a stack that has 
mongo+rbac+tcp_proxy+access_log
proprietary_decoder+rbac+tcp_proxy+access_log 
hcm+oauth_filter+rbac+router+access_log

In all these cases, the RBAC filter does not have to know the semantics of the previous filters. If it simply exposes the ability to act on attributes generated by previous filters, we could do a lot many cool things. Similar idea applies to access logs, allowing any newly introduced protocol codec (or existing mongo/redis/thrift etc.) to emit the attributes to be logged and we can have the access log filter spit them out. 

Along the same vein, it might help if we publish this so called object (one for HCM and one for Network stack) as protobuf representations for doc purposes.

**Comment by mattklein123** [comment]
Allowing multiple writers seems reasonable to me. It could also probably be expressed as part of the dependency/policy graph. @curiouserrandy thoughts?

**Comment by curiouserrandy** [comment]
[Just to clarify something that I think is understood: FilterState as a whole isn't write-once, but each object stored within FilterState is indeed write-once.]

Our experience at Google was that having a lot of filters all writing to the same objects made dependencies very hard to keep separate as the number of filters grew.  The goal of FilterState wasn't to create state that was shared between filters, it was to create a mechanism to allow information transfer between filters while keeping ownership and data flow of that data clear.  Data source is the (single) filter that sets the data originally, and the data sinks are the various filters that read that data.  

Note that the current implementation doesn't make it impossible for different filters to write to the same filter, it just discourages it.  Object methods can implement arbitrary functionality by casting away const; indeed, this was how I imagined lazy evaluation being done for cases in which that was useful.  But the current design is specifically for the purpose of getting people to think carefully about their dataflow between filters, lest they end up in the state that we've experienced here.  

In terms of a depencency graph, I suppose if we implemented the "Specifying Dependencies Between Filters" section of https://docs.google.com/document/d/1GNawM59Pp09WZ34zqJYiO_qmERjuGbOUeAqF1GG6v9Q/edit (and made it possible for multiple filters to call "providesData()" for a particular filter name, which the document doesn't forbid but hadn't been my vision) that could provide some level of constraint and documentation on the dependencies.  But I'd still worry that it was relaxing the structure too much for keeping inter-filter interfaces clean.  Maybe if you gave me some examples of the use cases you wanted to support?

@alyssawilk: You want to add to or modify anything in the above?

**Comment by ggreenway** [comment]
FWIW, in the [PR](https://github.com/envoyproxy/envoy/pull/4489) that @rshriram just put in, I suggested doing a similar, but oppositely directed version: a key that anyone can write to, and that tcp_proxy would consume (if set). But that still maintains the property that it is easy to reason about, because it is (as currently written) a directed message from one filter to another. I'd be curious to hear your (@curiouserrandy) opinion on that use.

**Comment by rshriram** [comment]
@curiouserrandy the use case I have is mentioned in the description above. I would like filters to add one or more attributes to a connection state (e.g., mongo adds some attributes, then tcp proxy adds some more, and finally access log uses it to create a log entry or the RBAC filter uses both to do some policy enforcement.). For example, lets say the RBAC filter looks for  "envoy.rbac.attributes" key in the shared connection state and does policies based on the attributes (a map of key value pairs). I would like all filters before RBAC to set the attributes that they glean from the connection into this shared object.

**Comment by htuch** [comment]
@ggreenway that was the original idea behind the post box style of the metadata namespace; the filter name was intended as the destination. It seems there are useful cases for both 1:N and N:1 communication.

**Comment by curiouserrandy** [comment]
@rshriram : Ah, sorry, somehow missed that section of your initial writeup.  I think I'm with @htuch / @ggreenway that 1:N and N:1 data flows would both have their use.  I'll note that one concern I have around N:1 is that I still don't think that it makes sense (at least based on what I understand of your use case) for multiple filters to overwrite the  *same* piece of data; what you want is for them to be able to add new pieces of data to a store/mailbox that the receiving filter will read.  

WRT to protobufs, part of the reason for this implementation (using templates to allow arbitrary object storage) was to allow the cost for creation of complex data to be done once, and to allow filters to export logic/intelligence to be used by other filters.  So I'd rather not pull back from the current C++ template implementation to protobufs (though if I've misunderstood your point please correct me).

@htuch : Since I didn't end up replacing RequestInfo::dynamicMetadata(), it would be perfectly reasonable to keep that post office box style (and document it more clearly).  I'm not sure having both mechanisms in parallel for almost the same data transfer (the only difference being 1:N vs. N:1) makes sense as the mechanisms are fairly different (I think of dynamicMetadata() as being for config->filter communication, and FilterState as being filter->filter communication) but it's an option we could consider.

**Comment by rshriram** [comment]
I am not looking for overwrite semantics. Append should do..

**Comment by curiouserrandy** [comment]
I would reasonably strongly prefer that we avoid that solution.  Let's craft a solution that's more targeted towards appending as opposed to allowing mutation.

One easy way to do that, either as another accessor or as a change to the existing situation, is to allow multiple setData<> of the same type on the same name, and have a getData<> that returns a vector of results.  Would that address this use case?

My personal preference would be another accessor so that it's clear when you're doing this different pattern of access.

**Comment by rshriram** [comment]
neither of these would satisfy this use case though.. What I want is a bag of attributes.. Like a map within a map..
 e.g.,
```
  mongoFilter:
     attributeBag = read_callbacks->connection().perConnectionState().getData("attribute_bag")
    attributeBag.addAttribute("foobar", someObject)
  rbacFilter:
    attributeBag = read_callbacks->connection().perConnectionState().getData("attribute_bag")
    iterate over the attributes in the attribute bag and do stuff..
```

**Comment by curiouserrandy** [comment]
Why wouldn't it satisfy the use case?  You just have objects with the same name (e.g. the destination filter that will consume the information) and those objects have an attributeName() accessor and the FilterState interface allows the ability to iterate through all of those objects.

**Comment by rshriram** [comment]
sorry, i messed up the example.. here is the right one
```
mongoFilter:
     attributeBag = read_callbacks->connection().perConnectionState().getData("attribute_bag")
    attributeBag.addAttribute("foobar", someObject)
filterX:
    attributeBag = read_callbacks->connection().perConnectionState().getData("attribute_bag")
    attributeBag.addAttribute("filterX", someObject)  
rbacFilter:
    attributeBag = read_callbacks->connection().perConnectionState().getData("attribute_bag")
    iterate over the attributes in the attribute bag and do stuff..
```

**Comment by rshriram** [comment]
Ah I see what you are saying.. return vector of objects instead of a single object..
that could work.

**Comment by rshriram** [comment]
should I change the getData to always return a vector instead of another variant?

**Comment by mandarjog** [comment]
We have been wanting a mixer-esque attribute bag for a while. I think it makes a lot of sense. 
This proposal will have to decide on issues of attribute vocabulary that mixer had to before. Is it purely defined by the producer of the attribute, are attributes  namespaced ?

**Comment by yangminzhu** [comment]
As this FitlerState is being implemented, what's the plan for the dynamic metadata? will the dynamic metadata be deprecated and removed sometime? If so when will this happen? Thanks.

**Comment by htuch** [comment]
@yangminzhu looks like it will be around for some time due to dependencies in JWT/RBAC filters IIRC.

**Comment by rshriram** [comment]
We are planning to remove dynamic metadata from RBAC
and use the filter state instead.

**Comment by yangminzhu** [comment]
Thanks for the comment, one more thing to confirm, currently the `FilterState` only has a generic [Object](https://github.com/envoyproxy/envoy/blob/ce634f4be8929f42366ea729fb098afdc139766a/include/envoy/stream_info/filter_state.h#L17) interface.
To make it useful for sharing data between filters, should we define some well-known classes sub-classing the Object? For example, StringObject, NumberObject or even StructObject (for the protobuf struct).

Or otherwise should just we let each filter to create their own classes sub-classing the Object? (This seems creating a hard dependency if filter Y wants to receive data generated by filter X)

/cc @qiwzhang

**Comment by rshriram** [comment]
Looking at RBAC filter, its simply a set of string matches isn't it? A string/NumberObject seems like a good start.

**Comment by htuch** [comment]
@rshriram I'm confused. How can the attributes be known well enough to be useful while the namespaces aren't known? At some point there is a contract over naming between producer and consumer, and that can include a namespace.

In your mixer example, why can't filter emit attributes under `istio.mixer` for example?

**Comment by mattklein123** [comment]
I think this is done. I will file a follow up issue to reconcile FilterState w/ dynamic metadata.
