### ISSUE TITLE
Reconcile the differences in behavior between STRICT_DNS and EDS

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy#4590]
*Description*:

This is a follow-up discussion of https://github.com/envoyproxy/envoy/issues/4548 and https://github.com/envoyproxy/envoy/pull/4575.

From @snowp in https://github.com/envoyproxy/envoy/issues/4548#issuecomment-426495302: I think we might want to follow up with figuring out how to reconcile the differences in behavior between STRICT_DNS and EDS, either by getting rid of the differences or acknowledging that they'll be different and making that clearer in code. For instance, EDS guarantees that a host only exists in one priority and will reuse the host instance (and consequently HC status etc.) when a host moves between priorities. Neither of these is true for STRICT_DNS AFAIK.

**Comment by snowp** [comment]
I see two options: We could update all priorities on every STRICT_DNS update and reuse hosts with the same address, similar to how we iterate over each priority during EDS updates. Doing this STRICT_DNS would behave the same way as EDS when it comes to managing existing hosts. A consequence of this would be that each host address can only occur once in each cluster. This gets a little tricky since multiple DNS updates won't be applied atomically (even the order would be non-deterministic), so it's not clear how one would actually orchestrate a host move from one priority to another.

The other option is to get rid of all this cleverness and never reuse host objects for STRICT_DNS, documenting that EDS should be used if this kind of behavior is desired.
