### ISSUE TITLE
SDS feature request:  only fetch trusted CA from SDS for CertificateValidationContext

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#4763]
*Title*: only fetch trusted CA from SDS for CertificateValidationContext

*Description*:
Istio likes to use SDS to send trusted CA for CertificateValidationContext.  But its SDS server doesn't have info for other fields, such as verify_subject_alt_name.  The discovery server has the info for "verify_subject_alt_name".

Like to change SDS that:
* Only trusted CA can be fetched from SDS,  the other fields of CertificateValidationContext can be specified in LDS/CDS from discovery server.
* Keep the current SDS of fetching whole CertificateValidationContext from SDS server.

Proposed Config change PR is:  https://github.com/envoyproxy/envoy/pull/4730

**Comment by lizan** [comment]
Looking at [CertificateValidationContext](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/auth/cert.proto#L113), is `trusted_ca` the only one you want to deliver from SDS? Perhaps `crl` should be delivered together? @PiotrSikora

**Comment by JimmyCYJ** [comment]
cc @wattli

**Comment by qiwzhang** [comment]
@PiotrSikora @lizan raised a good point that there are other fields in CertificateValidationContext needs to be fetched from SDS.   We don't want to add many oneof with sds_config for each field that potentially could be fetched from SDS.

Please look at my proposal (with is the current state of  #[4730](https://github.com/envoyproxy/envoy/pull/4730)

It allows users to send any number of fields as they want.

**Comment by wattli** [comment]
CRL is not something Istio security support as of now, but we want the design to be as generic as possible since Istio is not the only customer of Envoy and going forward we might support CRL as well.

@PiotrSikora , please let us know if you have better suggestions and your thought on Wayne's proposal.

**Comment by JimmyCYJ** [comment]
Hi @PiotrSikora , could you provide some feedbacks and let us know your concerns about #4730?

**Comment by PiotrSikora** [comment]
@wattli @JimmyCYJ @qiwzhang Per the discussion we had last week, trusted CA delivery for Istio can be implemented as either:
1) Trusted CA (and CRL) being delivered via SDS from NodeAgent and referred to in LDS/CDS from Pilot (i.e. this PR). This requires a new message containing trusted CA and CRL, and potentially some refactoring of the existing APIs, but is more of less what I suggested in https://github.com/envoyproxy/envoy/pull/4730#pullrequestreview-164865160. This solution has the benefit of trusted CA being transmitted and updated once, not O(services).
2) Trusted CA (and CRL) being delivered as part of LDS/CDS from Pilot. This doesn't require any changes to Envoy and works right now, but it requires changes in Citadel and Pilot in order to propagate and update trusted CA whenever it rotates. This solution was preferred by @lizan.

The second solution is cleaner from the API standpoint, but I could see the benefit of the verification material being distributed separately from the rules for it. Both solutions are fine, IMHO.

As for the solution suggested by in #4730, there is no precedence in Envoy APIs for the overrides, and I personally view it more as a hack than a properly designed solution for the issue at hand.

cc @ggreenway @mattklein123 @htuch FYI

**Comment by PiotrSikora** [comment]
I just remembered that CRLs can be provided (once #4825 is merged) as part of trusted CA (i.e. for a file-based data source, CA list and CRL list can be concatenated and loaded with trusted CA), so perhaps we can ignore the separate CRL field for the purpose of SDS? What do you think, @lizan?

**Comment by lizan** [comment]
> Trusted CA (and CRL) being delivered as part of LDS/CDS from Pilot. This doesn't require any changes to Envoy and works right now, but it requires changes in Citadel and Pilot in order to propagate and update trusted CA whenever it rotates. This solution was preferred by @lizan.

I prefer this or the whole CertificateValidationContext from NodeAgent via SDS. (i.e. not breaking CertificateValidationContext). On the second thought, via SDS actually make more sense. It is more efficient when there are changes to secure naming mapping, delivering via SDS wouldn't draining connection from cluster/listener.

IIRC, having pilot delivering secure naming mapping is an interim solution when we didn't have SDS, and citadel is only issuing certificates to ConfigMap. Do we have am issue tracking this at Istio side?
cc @myidpt @ZackButcher

**Comment by JimmyCYJ** [comment]
> IIRC, having pilot delivering secure naming mapping is an interim solution when we didn't have SDS, and citadel is only issuing certificates to ConfigMap. Do we have am issue tracking this at Istio side?

@myidpt @wattli may have more context about this.

**Comment by myidpt** [comment]
@lizan We don't have issue to track propagating secure naming info through SDS. While I think it's the right direction, I consider this not a short-term effort for Istio.

**Comment by htuch** [comment]
@PiotrSikora could we just use merge semantics and have both an SDS and LDS delivered CertificateValidationContext?

**Comment by qiwzhang** [comment]
@htuch I like this idea.
