### ISSUE TITLE
Intercepting of traffic based on the interface when Multus plugin is used

### ISSUE THREAD

**Issue by pmarhatha** [envoyproxy/envoy#4766]
Intercepting of traffic based on the interface when Multus plugin is used

Description:
For telecom apps which are utilizing the multus plugin in order to have multiple interfaces inside container / PODS , how Envoy/ Istio will intercept the traffic ? How it will identify the packets pertaining to an interface etc ?  Can envoy/istio offer features like rate limiting , timeout , error check , tracing etc based upon the interface which are offered by multus plugin ? .

Can envoy filter intercept the traffic based upon the interface ?

**Comment by zuercher** [comment]
I don't believe Envoy ever deals directly with specific network interfaces (e.g. eth0 vs eth1). It can bind Listeners to specific IP addresses, which might be good enough for your purposes. Each Listener has a separate filter chain, which makes a separate configuration for those feature possible.

**Comment by pmarhatha** [comment]
thanks zuercher  for your valuable inputs.How do i use the envoy filter to bind the listeners to specific IP address ? May be via  "ip tagging filter" ?  thanks in advance..

**Comment by readverish** [comment]
In the case where Envoy is deployed on a kubernetes cluster with the Multus plugin, it will be convenient to specify the listener interface rather than the IP address, because the IP address is not known until the Pod is created. 
We have developed a kubernetes controller which is also an xDS server that builds the Envoy configuration based on the cluster state. The controller cannot know which IP address was allocated to the Envoy Pod when providing the configuration snapshot.
