### ISSUE TITLE
Not to send x-forwarded-for header for AsyncClient

### ISSUE THREAD

**Issue by qiwzhang** [envoyproxy/envoy#4924]
*Title*: Not to send x-forwarded-for header for AsyncClient

*Description*:

The referred code is [here](https://github.com/envoyproxy/envoy/blob/master/source/common/http/async_client_impl.cc#L125)

X-FORWARDED-FOR is supposedly to be added for a forwarded request. But AsyncClient is for the requests originated by Envoy, not forwarded.   So it should not be added.

Background.  We are trying to fetch access token from GCP metadata server by using AsyncClient.
But if X-FORWARDED-FOR is added,  GCP metadata server  rejects it.

 [GCP metaddata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata)

**Comment by mattklein123** [comment]
This must be configurable. Envoy itself uses x-forwarded-for to determine internal/external status. The reason x-forwarded-for is added is so that the call is effectively forwarded on behalf of the local host.

This has come up before and IMO the GCP metadata server is broken, but I'm guessing you can't fix that. It's a shame we would have to make this configurable but I think that is what will be required if this must be changed.

**Comment by qiwzhang** [comment]
In that case, we will try to work around this problem without this change from Envoy.

**Comment by qiwzhang** [comment]
@htuch Thanks. I re-open it then.  But I may not have time to work on it since I have a work around.

**Comment by lizan** [comment]
> This has come up before and IMO the GCP metadata server is broken, but I'm guessing you can't fix that. It's a shame we would have to make this configurable but I think that is what will be required if this must be changed.

Why do you think metadata server is broken? Metadata server is rejecting the request with 403 Forbidden, it is reasonable for a service like metadata server to reject any forwarded request, as it is intended to be called from local application to get some sensitive information (e.g. auth tokens).

**Comment by mattklein123** [comment]
Because the forwarded IP address is the local IP address.

**Comment by CharlieC3** [comment]
@qiwzhang I'm running into this same problem. Calling `httpCall` synchronously still added the XFF header. According to this issue it sounds like I need to make the call asynchronous for the XFF header not to be included, but I'm not sure how to check if changing it to an async call is working or not.

For example, using this script:
```
function envoy_on_request(request_handle)
  local headers, body = request_handle:httpCall(
  "gcp_metadata",
  {
    [":method"] = "GET",
    [":path"] = "/computeMetadata/v1/instance/service-accounts/default/token",
    [":authority"] = "gcp_metadata",
    ["metadata-flavor"] = "Google"
  },
  "",
  5000,
  true)

  request_handle:logWarn(body)
end
```

How am I able to get the body of the `httpCall` response in this situation since the `httpCall` is async? Trying to log it results in the error:
```
bad argument #1 to 'logWarn' (string expected, got nil)"
```
