### ISSUE TITLE
BoringSSL - per error stats

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#5066]
It would be nice to have stats per BoringSSL error like certificate verification failure, SAN validation failure, TLS handshake error due to protocol error, etc. This alleviates the need to start trace logging and grep through the firehose of logs to identify issues related to TLS.

cc @htuch

**Comment by rshriram** [comment]
Better yet, it would be nice if failed connections appeared in the TCP access logs with appropriate response codes

**Comment by PiotrSikora** [comment]
@rshriram you mean those?

Name | Type | Description
-- | -- | --
ssl.connection_error | Counter | Total TLS connection errors not including failed certificate verifications
ssl.handshake | Counter | Total successful TLS connection handshakes
ssl.session_reused | Counter | Total successful TLS session resumptions
ssl.no_certificate | Counter | Total successul TLS connections with no client certificate
ssl.fail_verify_no_cert | Counter | Total TLS connections that failed because of missing client certificate
ssl.fail_verify_error | Counter | Total TLS connections that failed CA verification
ssl.fail_verify_san | Counter | Total TLS connections that failed SAN verification
ssl.fail_verify_cert_hash | Counter | Total TLS connections that failed certificate pinning verification
ssl.cipher.\<cipher\> | Counter | Total TLS connections that used \<cipher\>

**Comment by htuch** [comment]
@PiotrSikora would we want finer grained errors, e.g. at the per-elliptic curve error level? See for example https://code.woboq.org/crypto/openssl/crypto/ec/ec.h.html#1116. Same goes with other subsystems, they have more specific reason codes that can be useful in understanding why a cert is rejected.

**Comment by PiotrSikora** [comment]
@htuch definitely not, those are all errors for malformed certificates that would never hit the wire, and are never (in practice) the errors that you'd need to investigate.

I'm not saying that we don't need any more stats, but I'd rather add them on as-needed basis, since we're pretty well covered, IMHO, and all the cases that @rshriram requested in this issue are covered by existing stats.

**Comment by htuch** [comment]
@PiotrSikora fair enough. @rshriram does this seem satisfactory? If so, we can close this issue out.
