### ISSUE TITLE
Stop and send custom response in encoding filter

### ISSUE THREAD

**Issue by syml** [envoyproxy/envoy#5166]
*Title*: *Stop and send custom response in encoding filter*

*Description*:
We have an encoding filter and we would like to send a custom error response if some conditions are met. The conditions might only be available after some wait so we need a way to stop filter processing (StopIteration) then possibly send a custom response instead of calling continueEncoding.

The only alternative I have found is having two filters, one that waits on the condition and one that checks it. Even then it is not very convenient because there is no utility function like sendLocalReply which is available to decoding filters.

**Comment by htuch** [comment]
@syml as discussed internally, you should be able to `StopIteration` during `encodeHeaders()`, keep a reference to the headers,and after the wait, mutate them and `continueEncoding()`.

**Comment by syml** [comment]
@htuch Thanks Harvey, what about data? There doesn't seem to be a way to overwrite the data after encodeData() has been called once. I tried what you suggest and I was stuck trying to make data work. There are no encoding callbacks to overwrite the data afterwards.

**Comment by htuch** [comment]
@syml once you're at the data encoding stage, you can then directly invoke https://github.com/envoyproxy/envoy/blob/dd2b1d457e97cfd266673489fb8dd7c948bd0d7b/include/envoy/http/filter.h#L431.

**Comment by htuch** [comment]
FWIW, I think having some utility or convenience wrapper around this flow could be useful, but I'm not sure if we're missing any actual capability today that would require the multi-filter setup described above.

**Comment by syml** [comment]
@htuch the problem is that encodeData() is called before our callback runs. Depending on the result provided by the callback we want:
- just forward the app's data (success case)
- overwrite the app's data (addEncodedData doesn't seem enough, we need to clear the existing body) (error case).
The encoding callback class only allows to add data or get a read-only pointer to the data buffer.

**Comment by htuch** [comment]
@syml you should issue `StopIteration` in `enodeData` as well.

**Comment by htuch** [comment]
@syml explained this to me just now on a video call. The issue they face is that they issue an RPC for response YES/NO as they encode. They need to be able to buffer both headers/response and then do what is described at https://github.com/envoyproxy/envoy/issues/5166#issuecomment-443334937.

It's not possible to do `StopIterationBuffer/Watermark`, since these don't allow the data to be replaced. Doing `StopIterationNoBuffer` works, but then they need to manually do buffering in their filter, which is not subject to watermarking/flow control.

@mattklein123 @alyssawilk WDYT about a variant of `continueEncoding()` that allow you to resume in the filter's `encodeHeaders/encodeData`, rather than the next one in the pipe? There may be other ways to do this.

**Comment by mattklein123** [comment]
> @mattklein123 @alyssawilk WDYT about a variant of continueEncoding() that allow you to resume in the filter's encodeHeaders/encodeData, rather than the next one in the pipe? There may be other ways to do this.

That could work, though it might be a bit hard to grok.

The quick thing that comes to mind would be to have a non-const version of `const Buffer::Instance* encodingBuffer()` that allows direct manipulation of the buffered data. This would need some thinking as the reason it's constant currently is that it can see buffered data that was buffered by a previous filter. Perhaps there is a non-const version that only returns non-null if data is being buffered by the current filter and hasn't been continued yet?

**Comment by alyssawilk** [comment]
Alternately if the problem is that they want to never get that initial data, maybe some return code for encode/decode headers that defers the onData until the filter is ready?   I like the idea of being able to defer all data until the filter is ready to receive any, and I think it'd make the flow from the filter perspective fairly clear.

**Comment by htuch** [comment]
Yeah, I like @alyssawilk suggestion the best, since folks are often confused as to why data processing even occurs when headers are blocked.

**Comment by htuch** [comment]
@syml do you want to have a go at implementing this? This would also resolve some of the earlier surprises that @qiannawang encountered.
