### ISSUE TITLE
load balancer stat inconsistency

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#5168]
While investigating some 5xx issue in a cluster found the following stats for the cluster that has problems.
```
cluster.test_cluster.upstream_cx_none_healthy 10
cluster.test_cluster.lb_healthy_panic 10
cluster.test_cluster.membership_total : 3
cluster.test_cluster.membership_healthy: 3
```
While membership metrics show all the members as healthy, the `cx_none_healthy` and `lb_healthy_panic` incrementing seems to be inconsistent. Is this a bug or is there a scenario where this can happen?

**Comment by htuch** [comment]
@ramaraochavali were the members always healthy? Since membership is a gauge, it only gives you the current state, whereas the other stats are counters, reflecting history.

**Comment by ramaraochavali** [comment]
Another observation that lead to these inconsistent stats is 
- Envoys are running with some configuration
- We redeployed our control plane
- Control plane sent the new cluster definitions (old clusters but with changed circuit breaking stuff)
- Eds Clusters start warming up
- Eds subscription sent
- Because of some network problem, EDS updates were received after a huge delay
- Cluster Warm up complete at that time
- Requests start failing and `upstream_cx_none_healthy` and `lb_healthy_panic` keep incrementing
- There is no change to membership update, membership total stats.
Makes me wonder if cluster is some kind of limbo? Any ideas?

**Comment by ramaraochavali** [comment]
@dio I am debugging this issue and came across this line changed in #3783

https://github.com/envoyproxy/envoy/blob/9dacb47c8d3025191c2dea91f28bda0759bda23c/source/common/upstream/eds.cc#L84

Wondering, why are we setting the host to `FAILED_EDS_HEALTH` to start with instead of passing optional null value? It may not be causing this behaviour of inconsistent stats yet - still debugging that part but just wondering what could be the reason for setting it with failed state instead of optional null?

**Comment by htuch** [comment]
@ramaraochavali it's not actually marking them unhealthy, if you follow the code path. Instead, it's saying "this is the flag to use to mark unhealthy, _when_ you detect an unhealthy condition in the host EDS data while loading". It's a bit confusing, I agree..

**Comment by ramaraochavali** [comment]
@htuch Yeah. I saw that part later but forgot to update here - I think it would be less confusing to pass optional null value here and set the flag if you detect an unhealthy condition in the `PriorityStateManager`.

**Comment by ramaraochavali** [comment]
@mattklein123  We are not able to reproduce this even after repeated attempts. I think it is better to close this and will open again if I am able to reproduce this.

**Comment by mattklein123** [comment]
SGTM

**Comment by mattklein123** [comment]
I would have to look through the code. The only thing that comes to mind is a discrepancy during hot restart, given how these gauges work. Is hot restart involved here?

**Comment by ramaraochavali** [comment]
@mattklein123 I was able to consistently reproduce this with the following steps

1. Management server (Instance 1) is in connection with Envoy. It has fully exchanged the configuration
2. New Management Server comes up and it sends its initial cluster list with some tweaks to cluster config. Since the hash of config changed, it goes in to warming mode. It prints "add/update cluster starting warming"
3. Before it warms up - it gets disconnected and from the management server and connects to another management server
4.The new management server since it is still coming up it does not have full discovery data. At this point we send empty cluster load assignment (with out any resources) to let the initialization 
complete. Later we push the real discovery data.
5. At this stage, onConfigUpdate is called on EDS and it internally calls preInitComplete. We see the following log lines
```
[2019-01-21 17:27:51.435][8545699][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
[2019-01-21 17:28:19.177][8545699][info][upstream] [source/common/upstream/eds.cc:48] Missing ClusterLoadAssignment for test in onConfigUpdate()
[2019-01-21 17:28:19.177][8545699][info][upstream] [source/common/upstream/cluster_manager_impl.cc:483] warming cluster test complete
[2019-01-21 17:28:19.177][8546329][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8546333][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8546334][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8546336][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.178][8546338][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8546331][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8546332][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
[2019-01-21 17:28:19.177][8545699][info][upstream] [source/common/upstream/cluster_manager_impl.cc:501] updating TLS cluster test
```
6. After this, the clusters endpoints are cleared but stats still shows that it has end points.
7. I guess it is because of the initializatoin callback just creates TLS cluster with clusterinfo that has no hosts.

Should this be handled in Envoy (not sure how to handle)?

Another thing I was thinking (not tried though was) not send any empty ClusterLoadAssignment (just ignore call) and let the warm up complete when 
it has real hosts - I guess that is the purpose of warmup any way right? My only doubt is if there is not change in hosts metadata - why this is required?

What do you think?

**Comment by mattklein123** [comment]
Thanks for the detailed investigation. Yeah it seems like the stats just need to get updated in this case since there aren't any hosts? It seems like Envoy should correctly handle this case. @snowp any thoughts here? You have been going deep in this code lately and can likely offer the best advice.

**Comment by ramaraochavali** [comment]
Not just stats, I think if we just send empty CLA (with out any resources), envoy should probably handle this differently - because we are not sending any resource names and per doc
"When a requested resource is missing in a RDS or EDS update, Envoy will retain the last known value for this resource".
Any way, let us discuss on how to do when we actually fix this bug.

**Comment by snowp** [comment]
So is the issue here that the cluster is rebuilt with no endpoints (since the control plane responds with no EDS resources), but the endpoints still exist in the TLS cluster, so requests to it still attempt to route to the old endpoints? Is that the cause of the stat inconsistency?

Avoiding these kind of edge cases is part of why we never respond with an empty EDS response in our control plane (we hold the stream until the real response is ready), but given the language in the XDS protocol we might want to support this?

**Comment by ramaraochavali** [comment]
>>So is the issue here that the cluster is rebuilt with no endpoints (since the control plane responds with no EDS resources), but the endpoints still exist in the TLS cluster, so requests to it still attempt to route to the old endpoints? 
yes. The cluster is rebuild with no end points - it updates the TLS clusters as well with zero endpoints. But do not update the metrics.

>>but given the language in the XDS protocol we might want to support this?
Yes. That is what I am proposing. Since XDS protocol says, the control plane does not respond with resource, it should work with last known values.

**Comment by snowp** [comment]
Alright, yeah we should definitely fix the stat inconsistency. 

Regarding "last known values": since this only seems to happen when the cluster is rebuilt, any concerns about the old EDS values not being compatible with the new Cluster? 

For example, what if the Cluster was updated to remove the TLS settings, and endpoints were updated to point to a HTTP port instead of HTTPS. If you disconnected before you received EDS and reconnected, you'd now use the last known endpoint values but they'd useless because of the changes to the cluster.

**Comment by ramaraochavali** [comment]
While there may be some incompatible old EDS values if we retain the old host values, I think if the management server has not responded with any hosts for that resource(cluster), we should not treat that them being empty clear them - if the management server wants to clear the hosts also, it can send a ClusterLoadAssignment for that cluster with empty hosts. It would probably be better to be explicit about it.

**Comment by snowp** [comment]
I guess my thought was that you might want to delay cluster init until you get a EDS response for that cluster, not that you should bring it up with zero hosts. I'm a bit unclear on how cluster warming works in general, but I think the new old cluster is kept around until the new one is initialized?

**Comment by ramaraochavali** [comment]
I guess we are saying the same thing. Finish warming of the cluster only when there is a EDS response for that cluster - with both new cluster properties and supplied hosts. Till that time let the old cluster work as is ( That is what I meant by work with existing values). Stop
Initialising all clusters on empty CLA response.

**Comment by htuch** [comment]
I'm not sure if we want to force an EDS update on CDS update; in general it's hard to predict whether a CDS update needs a corresponding EDS update and the management server shouldn't have to bump EDS version on every CDS version bump; if there is no EDS version bump then there is nothing to serve.

I think for complex updates, it might be conceivable that you do make-before-break by using a new cluster name and doing the switch at the route level. Switching form HTTP to HTTPS, for example, seems like something that is not on the common path.

**Comment by ramaraochavali** [comment]
@htuch That is a good point. Should n't that mean for in an cluster update case, the warming of EDS cluster is a no-op and it should work with existing end points and EDS will respond when it has updated hosts as usual.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/cluster_manager.html?highlight=cluster%20warming#cluster-warming? 

I think it makes sense to treat it like that go in that direction. WDYT?

**Comment by htuch** [comment]
@ramaraochavali actually, looking at implementation, I think EDS updates always happen when a CDS update does today. I don't think it needs to, but that's the way it works. So, the description is accurate.

**Comment by ramaraochavali** [comment]
> and you are currently sending an empty ClusterLoadAssignment; in the above option you describe an EDS response with no ClusterLoadAssignment, these two are distinct.
We actually send the typeUrl as `type.googleapis.com/envoy.api.v2.ClusterLoadAssignment` with no resources added. We do not add the ClusterLoadAssignment for a cluster if we do not have end points.

**Comment by htuch** [comment]
@ramaraochavali if that's the case, I think the `Cluster` in question will never see an EDS update, since internally the `Cluster` subscribes to a specific resource name. Going back to your proposal:

> Subscribe to EDS when CDS update happens as we are doing today. But if the EDS response does not > have the ClusterLoadAssignments for Cluster - handle it in such a way that it does erase the host list (I > have not looked at in detail on how to do this - but if this is some thing we can pursue I will take a look).

I don't think this works nicely, because of the subscription model we have for EDS; absence of a resource doesn't indicate it is now empty. 

I'm inclined towards the idea of not having every CDS update issue an EDS request. There are some complications though; there is a question of how you transfer the EDS hosts from the old variant of the cluster to the new one; today we basically destroy the old EDS Cluster object and build a new one. In addition, you also need to have an EDS request made if `service_name` changes, since now the cluster points at a different EDS resource name. Or, we make the cluster mutable and deal with whatever the implications of that are (probably a few).

So, ^^ is a chunk of implementation complexity, even though conceptually it does deliver what you want, no warming. 

Taking another step back, we want to solve the stats problem. ^^ can be fixed by updating docs to match reality of implementation. For your stats problem, is it enough to clear stats on CDS updates? I think this thread started to drift after https://github.com/envoyproxy/envoy/issues/5168#issuecomment-456469054 because of the semantic gap in the xDS protocol spec.

**Comment by ramaraochavali** [comment]
>  if that's the case, I think the Cluster in question will never see an EDS update, since internally the Cluster subscribes to a specific resource name
AFAICT, that is not the case at least for ADS based on my debugging. Here onConfigUpdate is called with empty resources for all clusters.
https://github.com/envoyproxy/envoy/blob/79dca84543663c3058574f519667d71f4111840e/source/common/config/grpc_mux_impl.cc#L171

In any case, I think while I started the issue thinking that it is a stats issue, there is an underlying issue of xDS protocol as well. I think we should fix that also - stats is not the only problem for us. While we are applying a temporary fix for this specific case in our control plane implementation - I think it would be required to fix this issue at Envoy as well.

**Comment by htuch** [comment]
@ramaraochavali I think we first need to agree there is an implementation issue vs. a documentation one. This comes down to "is it a bad thing to refetch EDS on a CDS update and always warm?".

I'm in two camps about this; OTOH, it's simple to just refetch on every cluster update, OTOH it's conceptually cleaner to not do unnecessary fetches.

What's actually going on in reality is that Envoy has a long poll EDS discovery request pending at the management server, already setup for the resource in question. So, the management server needs to send an EDS response (despite no new request) after a CDS update. This actually does seem a bit crap, because it means the management server has to send a response when there is no actual update.

Here's a simpler solution; why not have the gRPC mux implementation hold onto live resources so that it can then supply them during the CDS update as needed? This avoids having to complicate `ClusterManager`.

**Comment by ramaraochavali** [comment]
@htuch 
> This actually does seem a bit crap, because it means the management server has to send a response when there is no actual update.

This is exactly the problem I am highlighting irrespective of the argument whether what we have today is correct or not. I agree with your reasoning on both the camps though. Also as a end user I am also confused about why envoy is touching a resource (cluster) when my response does not have a reference to it in EDS (I understand how it is working the way it is - just highlighting the end user perspective).

I think the point is what type of CDS updates require a EDS fetch vs not. 

Are you suggesting to hold `ClusterLoadAssignments` for each cluster in gRPC mux implementation and at the CDS update just merge it in to the Cluster built from the CDS update thus finish warming there it self? If yes, it seems like a reasonable solution to start with atleast for clusters to start with and the onus is on management server to update ClusterLoadAssignments as usual if it need to update. - is that what you are thinking?

**Comment by htuch** [comment]
In https://github.com/envoyproxy/envoy/issues/5168#issuecomment-459812020 I'm suggesting something slightly different. The idea is that gRPC mux implementation could cache previously received EDS responses.

Imagine you have cluster X and you have received an EDS assignment Y for X. This happens when X warm for the first time on creation. Now, you update X via CDS. The idea is that gRPC mux implementation might have held onto Y so that when the request comes to fetch X's EDS resources, Y is available locally, without having to go out on the wire.

It seems a bit heavy handed to do it in gRPC mux impl, but I think that's the closest we can do it, since the cluster itself is destroyed and replaced during the CDS update.

**Comment by ramaraochavali** [comment]
I see. The approach of responding to EDS request locally would also work and it has the added benefit of not changing the protocol semantics - except that the response would come from local cache.

**Comment by htuch** [comment]
@ramaraochavali it's either that or have some way during cluster rebuild on update to handover a snapshotted EDS state. The latter might help localize this to `ClusterManager`.

**Comment by ramaraochavali** [comment]
@htuch Sorry for delay here. I did some time on this today. Since this problem is during the warming(update phase), how about copying the active cluster priority set to warming cluster priority set here if the warming cluster priority set is empty? I tried that and it seems to resolve the issue but not sure of any side affects.
https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L473

**Comment by htuch** [comment]
I think this could work. @snowp do you think we can copy extant priority set for a cluster to an updated cluster object to transfer over endpoint state? My main concern would be around what happens if anything EDS related has changed, but providing the EDS details are the same it seems reasonable.

**Comment by snowp** [comment]
Yeah I think that would work, as long as care is taken to make sure all the update callbacks are handled properly. 

We'd want to make sure that anything that relies on capturing a reference to the priority set is updated correctly, and we'd probably want to make sure that we're not triggering any update callbacks when we're making the copy to ensure that we're not doing unnecessary rebuilds of the TLS cluster entries.

**Comment by ramaraochavali** [comment]
Cool. I would put up PR for this soon.
