### ISSUE TITLE
How can I register a resolver?

### ISSUE THREAD

**Issue by nakabonne** [envoyproxy/envoy#5186]
*Title*: *How can I register a resolver?*

*Description*:
I want to resolve names dynamically when getting EDS response.
That is, I am looking for a way to set a EDS config to use `LOGICAL_DNS/STRICT_DNS`.
There are multiple discussions on this subject.

- https://github.com/envoyproxy/envoy/issues/4290#issuecomment-416920502
- https://github.com/envoyproxy/go-control-plane/issues/87#issuecomment-400739949

In these discussions, it is recommended to do complete CDS response.
However, my log is output as follows.

```
Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```

So I look up the resolver_name in the [document](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto#core-socketaddress
) and it is written as below.
>The name of the resolver. This must have been registered with Envoy.

How can I register a resolver?

**Comment by junr03** [comment]
I think there are two parts to your question:

1. Your actual objective to resolve EDS endpoints via DNS: this is still a feature request, as also presented in #4290. That issue was auto closed, but can be reopened. The solution that @dio suggested there is still valid. Your control plane could do CDS for clusters with DNS-resolved addresses, instead of having EDS-based clusters.
2. Your question about the resolver: https://github.com/envoyproxy/envoy/issues/1477 has more contexts on resolvers.

**Comment by nakabonne** [comment]
Thank you for your politeness.
I thought resolver_name would solve the EDS endpoint via DNS, but it seems not to be the case.
My problem was solved. Thank you!
