### ISSUE TITLE
[Question] A feature to propagate context within trace

### ISSUE THREAD

**Issue by nakabonne** [envoyproxy/envoy#5266]
*Title*: *[Question] A feature to propagate context within trace*

*Description*:
Envoy has a feature to generate a span and automatically send it to a collector. This is a great feature.
However, we need to add application code so as to propagate the context between spans.
In order to achieve Envoy's goal "to abstract the network from application developers so that they can focus on business logic", I think Envoy should do the propagation.

I'd be grateful if you could tell the reason why does Envoy entrust propagation of context to application.
Thanks.

**Comment by objectiser** [comment]
It would certainly be great if this was possible - however the problem is that the Envoy proxy has no way of knowing which outbound requests were caused by which inbound requests.

The only way that an outbound request can be correlated to an inbound request, and therefore reported as being part of the same trace instance, is if some correlating information from the inbound request is passed to the outbound request - which can only be achieved in the application code.

**Comment by nakabonne** [comment]
Thank you for your prompt response.
I understand. Thank you for your perfect explanation.
