### ISSUE TITLE
mongo: fault injection

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#530]
Consider adding fault injection to the mongo proxy:

- Rate limit requests
- Delay requests and/or responses
- Fail requests

cc @scode @RomanDzhabarov

**Comment by scode** [comment]
A few things that could be useful, though we could discuss what's most important:

* Ability to inject latency with a target distribution (e.g. inject latency X at p99, Y at p999), but the minimum is probably to be able to inject a single fixed latency penalty on all requests. Probably easiest to just do a random dice throw and act according to a configuration provided map of `threshold->latency_to_inject`.

* Ability to inject latency on a per-source-service basis, so that we can ratchet up the impact incrementally from the PoV of which service is affected. I have no evidence this is required yet, should be discussed, but seems like it would help unblock further testing once certain callers have been determined to have a problem.

* Separating reads and writes (we may wish to inject different latencies for them).

* As an aside, we should likely consider per-request rate limiting alongside this work.

**Comment by rshriram** [comment]
Please keep me cc-ed on this as well. :). 

The current fault injection filter for HTTP supports injecting fixed delay for a subset of requests (adding exponential delay, etc. is on the list). It also supports restricting the faults to a specific destination cluster.

In terms of source-specific fault injection, you actually don't need this feature in Envoy. Whatever is setting up the filters on the caller end, can filter out the configuration that applies only to the calling (source) envoy or wildcards. Injecting faults at the destination side is of little use from our experience (wasted work, potential for misconfiguration that ends up impacting all consumers of the API, etc.).

In terms of delays, if injecting on the caller side, it is sufficient to delay just the requests alone (if the message exchange pattern is request/response).

**Comment by RomanDzhabarov** [comment]
https://github.com/lyft/envoy/pull/1519 PR introduced delays into mongo requests. Due to the limitation of mongo_proxy and tcp_proxy filters cannot do on a per operation basis faults.

The way it's going to work is:
Once an active delay is in progress, all incoming data up until the timer event fires will be apart of the delay. So, we'll not observe the same delay for all consequent operations, but rather some latency distribution.

In order to support proper per operation delays/faults, we'll need to rework mongo_proxy filter to be a full L7 proxy filter. Which is out of the current scope, but something to consider in the future.

**Comment by mattklein123** [comment]
Closing this as fixed for now.
