### ISSUE TITLE
Timeout failure in http2_upstream_integration_test's UpstreamConnectionCloseWithManyStreams

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#5316]
*Description*:

While building the Envoy trunk on a newly installed host, I got an intermittent test failure for `IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams`: both the IPv4 and the IPv6 versions of the test timed out.

Upon rerunning `bazel test`, with all the other test results cached so that `UpstreamConnectionCloseWithManyStreams` wasn't competing with anything else, this test case passed.

*Repro steps*:
Starting with a fresh checkout of the [current](https://github.com/envoyproxy/envoy/commit/6a49ebf9d0b6d0a2c826f12d531992c68efd868a) Envoy trunk on macOS, I ran:
```
bazel build //source/exe:envoy-static
time bazel test //test/...
```

*Test log output*:
```
[ RUN      ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv4
test/integration/http2_upstream_integration_test.cc:329: Failure
Value of: fake_upstream_connection_->waitForNewStream(*dispatcher_, upstream_requests.back())
  Actual: false (Timed out waiting for new stream.)
Expected: true
[  FAILED  ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv4, where GetParam() = 4-byte object <00-00 00-00> (10095 ms)
[ RUN      ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv6
test/integration/http2_upstream_integration_test.cc:329: Failure
Value of: fake_upstream_connection_->waitForNewStream(*dispatcher_, upstream_requests.back())
  Actual: false (Timed out waiting for new stream.)
Expected: true
[  FAILED  ] IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv6, where GetParam() = 4-byte object <01-00 00-00> (10092 ms)
```

**Comment by alyssawilk** [comment]
Hey Brian, I've definitely seen this a bunch on CI lately but only on the mac specific build which makes me think it's one of those mac-behaves-differently-than-linux bugs. Any chance you can try to repro with -l trace and ship logs via pastebin or some such?

Generally for flaking timing bugs if you run
bazel test //test/integration:http2_upstream_integration_test --test_arg=--gtest_filter="IpVersions/Http2UpstreamIntegrationTest.UpstreamConnectionCloseWithManyStreams/IPv6" --jobs 60 --local_resources 100000000000,100000000000,10000000 --runs_per_test=1000 --test_arg="-l trace"
you can reproduce but this looks flaky + mac only so it isn't working (or rather, isn't breaking) for me :-(

**Comment by brian-pane** [comment]
Thanks Alyssa! That suggestion enabled me to finally repro the error. Here's the test output with tracing: https://gist.github.com/brian-pane/1073fd865264e3309ecdeae184b11d82

**Comment by alyssawilk** [comment]
That is super helpful, thank you very much.

Now with logging, I can see 20 queries are queued, 18 new streams created on C2.
2 logs of "cancelling pending request" which matches up well with missing streams.
My guess is the recent refactor to the H2 connection pool created/exacerbated a race condition where the streams might get reset before Envoy detected the the connection pool established a connection, and so now the streams are reset before they're sent upstream, and we time out waiting for them.

This was supposed to have been fixed by the waitForHttpConnection, to ensure that sessions weren't queued, but I guess there's still a race between the connection being established, and Envoy realizing it's established and dequeueing.  I'll see what I can do about removing the race without losing reset-backup testing.
