### ISSUE TITLE
Make X-Envoy configurable

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#5363]
Right now, all Envoy "internal" headers are prefaced with X-Envoy.  This works well for folks who are using Envoy as their own proxy, but less well for cloud where one might be "transparently" proxying customer traffic where the customer might be using Envoy as well, and clients might want their X-Envoy headers to traverse a cloud proxy hop.

It'd be nice if the preface could be configurable, so that folks could differentiate internal X-Our-Build-Of-Envoy headers from X-Customer-Envoy headers.

More likely specific to Google, we'd like different teams to be able to have their own prefaces as well.

We could do this a number of ways (shamelessly stolen from an internal email from @curiouserrandy)

* Compile time: Have a macro that defines the prefix (X-Envoy vs. X-Google vs. X-My-Company whatever) and create header char* constants with macro stringification/concatenation based on this macro.  The problem with this is that that macro needs to be defined when the files that define the full header names are compiled, and those files are deep inside of envoy.  So if we want a single different prefix for different internal builds, that means we'd need separate build trees for envoy for those different parts (so that the actual envoy compilation would be done with different flags).  We could probably do that with blaze magic, but it would be somewhat ugly.

* Run time.  Refactor envoy to create flags with the X-Envoy prefix early in envoy startup based on the value of a variable exported from envoy, and allow setting of that variable earlier in envoy startup.  

* Link time.  Like run time, have the headers created from some other variable.  That variable name is exported, and specified in a separate .cc file for different targets.  Thus various builds could have their won  foo_team_envoy_header_prefix_spec.cc with 'char* envoy_header_prefix_spec = "X-Foo-Team";' in it,The problem with this is that it goes against my understanding of good practice for blaze, which is to have declarations and definitions in the same target, so if someone tried to link envoy and forgot to specify this they'd get a link error and have to do it by hand.  Or maybe we could have just that file be a different build target for every different consumer of envoy?  There may be a way to make this work semi-cleanly.

Per @htuch in the same thread, we're leaning towards run-time - it'd add a tiny bit to start-up cost but wouldn't make inline header parsing more expensive, and it would give us the flexibility we need internally

**Comment by cpakulski** [comment]
@alyssawilk I can do that - please assign it to me. Thx.

**Comment by alyssawilk** [comment]
Fantastic, thanks.  Feel encouraged to ping Harvey/Randy/I for review :-)

**Comment by cpakulski** [comment]
Just a quick question. How should it be controlled? New global config item, command line param, env variable?

**Comment by alyssawilk** [comment]
on the internal email thread @htuch suggested bootstrap config and as with all things config I'm going to assume his instincts are right :-)

**Comment by cpakulski** [comment]
Thanks!  Bootstrap config sounds good.

**Comment by mattklein123** [comment]
This sounds fine to me. FYI this is also loosely related to https://github.com/envoyproxy/envoy/issues/4815 though I don't think solving that issue is required to solve this issue.

**Comment by htuch** [comment]
Re: bootstrap, I think this is the easiest thing to do implementation wise, since we can build the shared singleton values at Envoy binary initialization. OTOH, this is a bit of a hack, since we are now moving HTTP configuration into the bootstrap, whereas it belongs conceptually in HCM or router configuration.

We'd probably have to rethink how O(1) headers are handled even if we had #4815 and wanted to support HCM/router configuration of the header values.

One other complication to throw in there; the `x-envoy-*` headers are used both for headers that Envoy receives, to parse out data and act on them, and also for headers that Envoy generates. It's conceivable that you might have an edge Envoy that wants to use `x-acme-*` for headers it generates, but use `x-envoy-*` inside the mesh. We could address this by actually distinguishing in the Envoy static headers by having two values for each `x-envoy-*` header.

**Comment by htuch** [comment]
@alyssawilk sure, start simple :)

**Comment by cpakulski** [comment]
Starting to work on it.
