### ISSUE TITLE
Request body unbuffered I/O

### ISSUE THREAD

**Issue by phylake** [envoyproxy/envoy#5368]
*Title*: *Request body unbuffered I/O*

*Description*:
I searched docs and previous issues for something related but couldn't find it.
Does Envoy supported unbuffered I/O? I'm looking for the equivalent of nginx's `proxy_request_buffering off` setting

[optional *Relevant Links*:]
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering

**Comment by PiotrSikora** [comment]
@phylake as @mattklein123 mentioned, Envoy is a streaming proxy, and it forwards request and response body bytes as soon as it receives them, similarly to what you get with `proxy_request_buffering off; proxy_buffering off;` in NGINX.

@mattklein123 for the background, in case you find this useful, NGINX's `proxy_request_buffering` controls whether the whole request body is buffered (either in memory or on disk for larger requests) before being forwarded upstream (to protect backends against trickle attacks, and to allow for retries even if backend fails mid-request), and `proxy_buffering` controls whether response body is buffered and sent in chunks to client (in order to minimize number of syscalls and TCP overhead) or streamed as soon as anything is available.

**Comment by phylake** [comment]
> There is buffering during proxy, but the entire request/response is streamed

@mattklein123 I've poured through the source and found [LibEventInstance](https://github.com/envoyproxy/envoy/blob/v1.9.0/source/common/buffer/buffer_impl.h#L49). Is there anything envoy-specific you can point me to or should I look to libevent for more detail about exactly what buffering is done during proxy?

The [flow control](https://github.com/envoyproxy/envoy/blob/v1.9.0/source/docs/flow_control.md) doc has been super helpful. Thanks!

**Comment by mattklein123** [comment]
Buffering vs. streaming is handled outside of libevent/the buffer implementation. 

I would take a look at https://github.com/envoyproxy/envoy/blob/master/include/envoy/http/filter.h#L43 and how that ends up getting plumbed into the HTTP connection manager (https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc).

**Comment by phylake** [comment]
(I looked for a related issue and didn't find one)
What about for retries? Those would have to be fully buffered in envoy for it to retry, correct? If so, where does that happen? I need to add a setting to cap the size of a request that can be retried.

**Comment by phylake** [comment]
bump

**Comment by phylake** [comment]
bump

**Comment by phylake** [comment]
I think I found the answer. Please confirm.

Envoy does buffer on retries but only up to the [`per_connection_buffer_limit_bytes `](https://www.envoyproxy.io/docs/envoy/v1.10.0/api-v2/api/v2/cds.proto#envoy-api-field-cluster-per-connection-buffer-limit-bytes), at which point it [abandons the retry logic](https://github.com/envoyproxy/envoy/blob/v1.10.0/source/common/router/router.cc#L419)

**Comment by phylake** [comment]
@mattklein123 is that ☝️ right?

**Comment by htuch** [comment]
@phylake yes, when retries are configured we will buffer up to the limit.
