### ISSUE TITLE
config: warning about using deprecated config

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#5559]
There is only [DEPRECATED.md](https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md) to track which field of config is deprecated. Though it is hard to check if the config provided to Envoy contains them and need migration in next version. A warning to users when such configs are provided either via file or xDS would be nice.

**Comment by mattklein123** [comment]
@lizan I was thinking about this, and couldn't we walk the config structures and look for any fields with a deprecated attribute set? We could do this maybe as part of the `Validate()` flow since we wrap most of that behavior for config load?

**Comment by lizan** [comment]
@mattklein123 yes that is what I was thinking of too. We need an interface for `Validate()` to raise deprecated warnings and logging them.

**Comment by alyssawilk** [comment]
Yep - I was planning on filing the same issue this week
I think it'd be great to have a three phase system:

1) warning for deprecated feature use, with links to the docs of how to migrate to the new
2) fail-by-default for deprecated features, overridable by default with a runtime-setting (#5693) no-really-I-want-to-use-deprecated-feature-X-even-though-it-will-vanish-soon to allow continued use
3) remove code which was off by default

We've had several features over the past few quarters where folks only migrated after the old code path had been removed, and we only discovered bugs or gaps with the new implementation after the old was removed.  I think if we fail-by-default it'll hopefully make folks serious about testing the new code path before the new code vanishes entirely.

What do you think?

Also @envoyproxy/maintainers

**Comment by mattklein123** [comment]
Huge +1 from me. I think this will be a huge benefit to everyone.

One thing that I do think we should do for (2) is have an option for how to handle deprecated features:
1) Fail by default, overridable via runtime (this is the default IMO)
2) Warn/stat by default, overridable via runtime

**Comment by junr03** [comment]
Big +1 from my perspective. We (Lyft) have definitely rushed on some feature deprecations if we have failed to pin point them with enough lead time.

Suggestion for 1) to additionally add a counter that gets incremented when as the deprecation warn logs get printed. I can see Lyft adding that stat to our dashboards in order to quickly see on deploy how many deprecated features we currently have, and act upon them based on a runbook.

**Comment by alyssawilk** [comment]
Cool, I'm on it.

Annoyingly while there is a C++ 'deprecated' field in proto reflection it apparently isn't set.  Have reached out to the protobuf team to try to figure out what the deal is.

**Comment by alyssawilk** [comment]
For stats, I'm not really keen on every caller of validate having to pass stats through in order to have this incremented.

That said, for run-time feature guarding (#5693 ) I was planning on making run-time a singleton, and doing fail-by-default warn-if-runtime-overridden for deprecated features.  I'd like to do the same thing for deprecated config fields - have a runtime option with the full name (thanks @lizan) where we will fail-by-default and warn-if-runtime-overridden to encourage folks to migrate off deprecated features ASAP

If we do *that* it'd make total sense to have a runtime varz of "number of times we warned instead of rejecting config due to a runtime override" and I don't have to do any stats plumbing.   

I think I'm going to land all the code to do this, envoy-announce that deprecated features are going to fail-by-default and that folks should set up run-time overrides if they see those warnings, and then do a separate PR (which may have to flap back and forth) for actually making things fatal-by-default.  

@envoyproxy/maintainers - I think we had general agreement (or at least no objections =P) about this on the runtime feature front but these are all pretty big changes so please share your thoughts early and often!

**Comment by alyssawilk** [comment]
Alternately if we want to get really fancy (which I'm inclined to do) with the new 2 release cycle we could could default runtime to warn-only for one release, have our deprecate script remove the runtime default to fail-by-default for a release, and then finally file the removal bugs.

**Comment by htuch** [comment]
+1 on default runtime to warn-only, then fail-by-default. We could help the deprecate script make flips automatically by either having commit meta-data or having each flag specified via a proto file in the repository.
