### ISSUE TITLE
Provide raw Envoy binaries outside of Docker

### ISSUE THREAD

**Issue by madhugilla** [envoyproxy/envoy#5668]
**Issue Template**

*Title*: *Where can we download the standalone Envoy Binaries*

*Description*:
>We want to use Envoy in a standalone environment(windows subsystem for linux) without docker, can you please let us know 
1) where can we download the Envoy binaries
2) How to get started using Envoy binaries in a docker less environment, i am assuming it will similar except for the docker part.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Bug Template**

*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).

**Comment by rnd4222** [comment]
@mattklein123 how do I extract them out of container? Also is there docker containers for specific (stable) version of envoy (not just latest)?

**Comment by dalu** [comment]
So much contempt for a worse alternative to nginx just because someone had to make yet another product.
docker is not everything is it in fact worse than the previous default - no default.
It's a typical case of corporate fuckup and overcomplication, a typical example of overengineering and also typical for the state of everything today.
It's like there are intentional bricks that were put there.
Not everyone's daddy is working at silicon valley and not everyone is 16 years old and has time to learn a new way every 2 years.
I find this ignorance so infuriating that I could smash it all to pieces.
No one wants your envoy proxy, the ONLY reason it because it's being pushed down everyone's throat by grpc-web, because of obvious design flaws. Apart from that NO SANE PERSON uses it. Look at the complicated configuration alone.
It's beyond frustrating.
The same as k8s, hype hype, but when it comes to actually using it you're left alone and forced to use big tech companies clouds for ridiculous prices.
"Extract the binary out the docker container"... absofuckinglutely ridiculous.

**Comment by mattklein123** [comment]
The previous comment/user was blocked due to violating our code of conduct.

With that said, I am going to reopen this issue and mark it help wanted. The maintainers cannot support every possible deployment scenario. We believe that offering Docker containers is a reasonable compromise. If someone in the community wants to work on the build/CI/etc. changes to provide raw binaries we are happy to support that work.

**Comment by skyrocknroll** [comment]
https://www.getenvoy.io/

**Comment by mattklein123** [comment]
@lizan @dio can we document getenvoy in our public docs here: https://www.envoyproxy.io/docs/envoy/latest/install/building#install-binaries and then we can call this resolved?

**Comment by jbonnett92** [comment]
> @lizan @dio can we document getenvoy in our public docs here: https://www.envoyproxy.io/docs/envoy/latest/install/building#install-binaries and then we can call this resolved?

I don't feel this helps, there are not prebuilt binaries or installers for Windows, the way you build the binaries is by using another dependency that some people wont have access to due to heavily locked down work environments.

**Comment by phlax** [comment]
@jbonnett92 see https://github.com/envoyproxy/envoy/milestone/36

this is something that is being actively worked on, even if progress is slow

**Comment by jbonnett92** [comment]
> @jbonnett92 see https://github.com/envoyproxy/envoy/milestone/36
> 
> this is something that is being actively worked on, even if progress is slow
Awesome, that you!

**Comment by dimo414** [comment]
It seems like this issue has regressed, as GetEnvoy.io now redirects to https://www.envoyproxy.io/docs/envoy/latest/start/install which doesn't appear to include any links to plain binaries.

**Comment by phlax** [comment]
> It seems like this issue has regressed

no regression - the binaries are now provided on the releases page

@jbonnett92 

> I don't feel this helps, there are no prebuilt binaries or installers for Windows

we are unlikely to provide windows binaries for the forseeable future - we are currently considering removal of windows support due to lack of maintenance (#28588 )

**Comment by aceqbaceq** [comment]
for whom to need extract envoy binary from docker containers:
# docker cp    76533e32adc1:/usr/local/bin/envoy /usr/local/bin/envoy
