### ISSUE TITLE
Adding rotation+compression options for logging

### ISSUE THREAD

**Issue by kiryazovi** [envoyproxy/envoy#5678]
*Description*:

**Ask**:
Would you be ok upstreaming a rotation solution+compression to the current logging implementation in Envoy?

**Motivation**:
We are currently in the process of adopting Envoy in our infrastructure. Typically up until now all of our logging had the distinct feature of rotating with compression. So in order to not break the customer's expectations in the future, we are working on making the envoy logs on our side fit into that.

**Initial steps**:
The spdlog rotating logger does not support compression or anything else for that matter except vanilla basic rotation. So we've started the process of upstreaming a callback solution which would make it so the users of spdlog (in this case also Envoy) would be able to make their own set of rules of how what and when to rotate.

**Suggestion**:
We can provide you with a commit with the following code:

1. Make config/command line options that would enable rotation (size of files, number of files, how to compress them). The point of this is that we _don't want_ to change current behavior. We want to add on top of it - it will be customer's choice to enable rotation - if they don't the Envoy logging will work as is currently.
2. Implement wrapper of rotating logger (from spdlog) with a callback for rotation.
3. Make a generic rotating callback that would compress after rotating. 
4. Implement also testing along with the whole thing.

If you are interested we'll try to provide an ETA on when we can give you a potential commit for you to review (It would need to pass internal reviews first)

*Relevant Links*
https://github.com/gabime/spdlog/issues/954

**Comment by mattklein123** [comment]
I'm not necessarily opposed to this, but is there a reason that you can't use `logrotate`? It does all of this automatically.

**Comment by georgi-d** [comment]
Hi, I work with @kiryazovi 

We cannot use `logrotate` for a few of reasons:
- `logrotate` is not available on the OS we are using and we prefer not to pull in additional dependencies
- `logrotate` need to be run periodically from cron like scheduler which is also not available/enabled on the OS we use 
- since it is run periodically `logrotate` cannot have exact control over the size of the files. We have setups where we enable  debug logging which generate very high volume of logs. During these runs a periodic log rotation would not meet the space requirements.

**Comment by mattklein123** [comment]
OK, this sounds like a reasonable addition as long as its entirely opt-in. Thank you!
