### ISSUE TITLE
thread: thread-factory singleton assertion

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#5734]
Running `bazel test //test/exe:main_common_test --runs_per_test=1000` fails 24/1000 times.

```
[2019-01-28 03:38:22.276][15][critical][assert] [source/common/thread/thread_factory_singleton.cc:16] assert failure: (thread_factory == nullptr) != (thread_factory_ == nullptr).
```

IMO it would be cleaner to just plumb Api::Api& where it needs to go so we don't need a prod singleton. We will likely need it almost everywhere anyway; it will be carrying TimeSystem/TimeSource as well once https://github.com/envoyproxy/envoy/pull/5660 is merged, and will be available anywhere Filesystem methods are used once https://github.com/envoyproxy/envoy/pull/5692 goes in.

**Comment by mattklein123** [comment]
+1

**Comment by AndresGuedez** [comment]
I agree this makes sense given the ubiquity of Api::Api going forward.

@jmarantz Is the 'main_common_test' flakiness showing up on CI runs, or did this just manifest in your own testing?

**Comment by jmarantz** [comment]
I don't remember if I noticed it first in CI or testing an unrelated PR. But I repro'd it in a clean client yesterday.

**Comment by jmarantz** [comment]
@AndresGuedez any chance you could take a look? This is easy to repro; just do 
```
bazel test -j 8 //test/exe:main_common_test --runs_per_test=1000
```

and you'll get errors like:

```
[ RUN      ] IpVersions/MainCommonTest.ConstructDestructLogger/IPv4
unknown file: Failure
C++ exception with description "argument index out of range" thrown in the test body.
[2019-04-19 02:58:43.155][14][critical][assert] [source/common/thread/thread_factory_singleton.cc:16] assert failure: (thread_factory == nullptr) != (thread_factory_ == nullptr).
```

When I tried this it failed 10+ times.

**Comment by AndresGuedez** [comment]
Ack; I'll spend some time on this tomorrow.

**Comment by AndresGuedez** [comment]
Spent some time looking into this. The `thread_factory_singleton.cc` assertion is actually a red herring. The assertion happens because tests in `main_common_test.cc` with the following statement:

`VERBOSE_EXPECT_NO_THROW(MainCommon main_common(argc(), argv())); `

are (very) occasionally throwing (hence the flakes), which prevents the `MainCommonBase` [destructor](https://github.com/envoyproxy/envoy/blob/master/source/exe/main_common.cc#L102) from being called and resetting the ThreadFactorySingleton pointer. When the ThreadFactorySingleton pointer is not reset by `~MainCommonBase()`, the test fixture's destructor ends up asserting when attempting to set the `ThreadFactorySingleton` pointeragain.

**Comment by jmarantz** [comment]
should we put in the try/catch (or whatever) logic so this doesn't crash?

I think you are right -- I think the root cause is address conflicts running network tests many times concurrently.

However this assertion masks that problem.

**Comment by AndresGuedez** [comment]
Spent some time looking into this. The `thread_factory_singleton.cc` assertion is actually a red herring. 

See below for a breakdown of the issue. The first part of the explanation details why the `ThreadFactorySingleton` assertion is triggering, but this is not actually the root cause of the flakes.

(1)
The `ThreadFactorySingleton` assertion happens because tests in `main_common_test.cc` with the following statement:

`VERBOSE_EXPECT_NO_THROW(MainCommon main_common(argc(), argv())); `

are (very) occasionally throwing (hence the flakes), which prevents the `MainCommonBase` [destructor](https://github.com/envoyproxy/envoy/blob/master/source/exe/main_common.cc#L102) from being called and resetting the ThreadFactorySingleton pointer. When the ThreadFactorySingleton pointer is not reset by `~MainCommonBase()`, the test fixture's destructor ends up asserting when attempting to set the `ThreadFactorySingleton` pointer again.

(2)
The actual issue is that tests are failing (occasionally) due to the following exception:

`[ RUN      ] IpVersions/MainCommonTest.ConstructDestructHotRestartEnabled/IPv6
terminate called after throwing an instance of 'fmt::v5::format_error'
  what():  argument index out of range`

I've been trying to get a stack trace but haven't been successful yet.

**Comment by AndresGuedez** [comment]
> I think you are right -- I think the root cause is address conflicts running network tests many times concurrently.

Yes, this seems likely to be the cause of the flakiness, although the manifestation of the failure needs to be addressed. I'm trying to track down where the exception is actually thrown to figure out the best way to deal with this.

**Comment by jmarantz** [comment]
My vote -- as you know -- is still to just plumb Api::Api& where needed. It will likely be needed for other things as well in many places where it's not plumbed already.

But you can also solve it with more exception handling.

**Comment by AndresGuedez** [comment]
> My vote -- as you know -- is still to just plumb Api::Api& where needed. It will likely be needed for other things as well in many places where it's not plumbed already.
> 
> But you can also solve it with more exception handling.

There are two issues here: 1) test flakiness due to the exception being thrown, and 2) the `ThreadFactorySingleton` assertion due to the lack of cleanup after the exception.

I am doing a bit more investigation into 1) before addressing 2), but I agree the `ThreadFactorySingleton` could be removed now that `Api::Api` is ubiquitous.

I won't actually be able to plumb the `Api&` into the [only existing user](https://github.com/envoyproxy/envoy/blob/8789695f4ca4ea5a73d2b85bb75b557ba925156b/source/extensions/quic_listeners/quiche/platform/quic_thread_impl.h#L36) of the singleton, but it's likely it could just take the `ThreadFactory` as an argument via the constructor instead.
