### ISSUE TITLE
Add file `mode` to `Pipe` listeners

### ISSUE THREAD

**Issue by franklin-stripe** [envoyproxy/envoy#5808]
*Title*: Add file `mode` to `Pipe` listeners

*Description*:
Envoy can be configured with Unix domain socket listeners via the `Pipe` `Address` type. By default, these sockets are created such that only the file owner can read and write to them, and the typical umask of `0022` prevent access from group or world. We have a use case where we'd like to grant fine-grain access to individual `Pipe` listeners (either via group- or world-permissive configurations)

It'd be nice if `Pipe`s could be configured individually for what `mode` permissions they should be created with. This would allow users to have fine-grain permissions per-listener, rather than working around it with a broad umask change.

**Comment by mattklein123** [comment]
Sounds reasonable to me.

**Comment by madeddie** [comment]
This sounds like a great idea and we need it (running envoy as user envoy on a non-dockerized load)

**Comment by mattrobenolt** [comment]
This would be _really_ useful to have. Or some implementation of being able to configure user/group and mode on the unix sockets. Similar to how haproxy would do it, etc.

There have also been multiple tickets for this so I didn't want to open another, but it's a shame that these are being auto closed for being stale. :( So I'm adding a louder +1 here mostly in hopes of this getting re-opened.

@alyssawilk maybe? Since you're in the OWNERS.md for listeners? :)

**Comment by mattklein123** [comment]
Reopening and marking help wanted.

**Comment by mattrobenolt** [comment]
Thanks @mattklein123. <3

**Comment by athampy** [comment]
I can pick this up
