### ISSUE TITLE
`upstream_cx_destroy_with_active_rq` - the meaning of this metric?

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#6455]
What actually happens when a connection is destroyed with active requests?

Should this never happen, or is it a normal part of operating envoy proxies? What does it indicate? Is it impacting to requests?

**Comment by mattklein123** [comment]
If there is an active request and a connection is terminated abnormally either by upstream or downstream, this stat is incremented.

**Comment by derekargueta** [comment]
[HTTP1 implementation](https://github.com/envoyproxy/envoy/blob/80ff3651fc7e21bf1153be6f499136412146a105/source/common/http/http1/conn_pool.cc#L124)

[HTTP2 implementation](https://github.com/envoyproxy/envoy/blob/b41ba5925a4e93d22a86c6501d63314ccf0d79f3/source/common/http/http2/conn_pool.cc#L146)

As far as the impact to requests, in HTTP/1 it can only have 1 request active, which is destroyed (along with the client). For HTTP/2, due to multiplexing, there can be multiple all of which are destroyed with [this method](https://github.com/envoyproxy/envoy/blob/b41ba5925a4e93d22a86c6501d63314ccf0d79f3/source/common/http/conn_pool_base.cc#L26). The result for these requests is [connection failure](https://github.com/envoyproxy/envoy/blob/b41ba5925a4e93d22a86c6501d63314ccf0d79f3/include/envoy/http/conn_pool.h#L28) which I _believe_ is a 503.
