### ISSUE TITLE
Feature request: strict header validation mode

### ISSUE THREAD

**Issue by julia-stripe** [envoyproxy/envoy#6482]
We've had several production issues caused by a client setting an invalid Envoy header, for example `"200.0"` as a timeout or an extra space in an `x-envoy-retry-on` header). Right now Envoy just silently ignores invalid header values. It would help avoid these situations if Envoy had a "strict header validation" option where it either fails every request which has an invalid Envoy header or logs an error.

thoughts on whether this would be straightforward / reasonable to implement? It seems like it would be tricky to implement strict validation for every single header but even having it for just a few headers would be helpful.

**Comment by mattklein123** [comment]
@julia-stripe agreed this sounds like a useful thing to add. I don't think it will be too terrible difficult to add, but it will require dealing with the case at all header sites. It might easiest to start with the headers parsed by the router and the headers parsed by the HTTP connection manager. I suppose we could also have config to enable this on a per-header basis.

**Comment by xyu-stripe** [comment]
@mattklein123 I'd like to work on this if it's not already being worked on.

Based on your comment, would the following sound like a reasonable approach?

1. Introduce a `strict_check_headers` config field to `envoy.router` configuration to enumerate headers that would be subject to strict validation. This is opt-in. Example config:
  ```
  http_filters:
  - name: envoy.router
    config:
      strict_check_headers:
      - x-envoy-upstream-rq-timeout-ms
      - x-envoy-upstream-rq-per-try-timeout-ms
      - x-envoy-retry-on
```
2. If a request contains a header listed in the config that has an invalid value, `Envoy::Router::Filter::decodeHeaders` rejects the request, returning HTTP status 400.
3. When envoy rejects requests this way, set a new response flag `IH` to indicate the reason was because of an invalid header.
4. The PR would be scoped to support the handful of headers we've observed in our own production issues (or those that are easily adjacent e.g. `x-envoy-max-retries`), and we'd validate the `strict_check_headers` field and emit a config validation error so folks won't erroneously expect some unsupported header to be strict-checked. The initial headers would be:
```
  x-envoy-upstream-rq-timeout-ms
  x-envoy-upstream-rq-per-try-timeout-ms
  x-envoy-max-retries
  x-envoy-retry-on
  x-envoy-retry-grpc-on
```

If all of this sounds sane, I can put together a PR for review. Otherwise, would appreciate your feedback about where there may be gaps in my own understanding.

**Comment by mattklein123** [comment]
@xyu-stripe yup sounds great to me.
