### ISSUE TITLE
config: support enforcing resource dependencies

### ISSUE THREAD

**Issue by fredlas** [envoyproxy/envoy#6569]
The purpose of aggregated xDS is to specify an ordering of updates, to reflect dependencies among different resource types. However, Envoy's current implementation does not pay attention to these dependencies when updates fail: if Y depends on X, and the X update fails, logically the Y update should not be applied. However, Envoy's xDS client will happily pass the Y update along to its consumer as if everything is fine.

This came up in the context of partial rejections (#5739, @alyssawilk @AndresGuedez @htuch ), but the two features can be implemented independently. Copying+updating my design thoughts on these "failure dependencies":

I am vaguely imagining a relatively clean bit of work (in particular with no xDS protocol changes (although maybe some changes to the resource protos themselves)) to accomplish that. In the "XdsGrpcContext" implementation I'm working on, you would also maintain some mapping that tells you "when you process a type_url1 update failure for resource X , reach into the type_url2 subscription to mark Y as unavailable, as well as type_url3 Z".

OR, rather than "reach in and mark Y unavailable", maybe it would be cleaner to just mark X's entry in the dependency map as being in a failure state. Then, when it comes time to update Y, notice from the map that its dependency X is in a failure state, and decide that the Y update attempt should fail (and also go into failure state). Yeah, I like this more.

The good news is that it should fit very cleanly on top of what I'm currently building, rather than needing to be built in from the start. So we can keep that design in mind, while holding off on actually doing it until the current work is done, without hassle.

**Comment by htuch** [comment]
@fredlas I think it's a bit more complicated. It helps to think concretely about resources, so here's a thought experiment with CDS and EDS. Let's consider two scenarios:

1. We're going to upgrade cluster X to use TLS. The management server sends CDS and then EDS updates for X (switching to port 443 from 80) down the pipe. The CDS update is rejected, in the above design, we reject the EDS update, WAI, we don't switch to the port 443 endpoints.

2. We're going to modify the timeout setting in X and then send some new assignments (unrelated to the timeout). The CDS update and now we reject the EDS update as well. This is bad, because the cluster already exists and should get some fresh endpoints when they arrive. We don't mark existing functioning clusters as bad just because of a bad update, Envoy is supposed to latch the last known good CDS and continue functioning.

See somewhat related discussion in https://github.com/envoyproxy/envoy/issues/5168

**Comment by fredlas** [comment]
Interesting. It sounds like, rather than tracking resource name dependencies, we should track resource version dependencies. The `Response` proto could carry a type_url+version pair, meaning "you should only accept this resource I'm sending if you've already accepted this prereq resource". (It's even cleaner, too, given that what I previously described glossed over how exactly Envoy would learn these dependencies).

Issues I can think of: 1) would a single resource ever reasonably need to have multiple dependencies (that aren't just a transitive chain), and if so, should it be any or all? 2) Unless we can just have the protocol declare that the server can't update a resource beyond version X until other updates depending on X have been accepted, we would have the issue of how to realize that 'opaqueversion2' ought to satisfy a dependency on 'opaqueversion1'.

**Comment by htuch** [comment]
Another way of tackling this is to push this on the management server. It could wait for round-trip confirmation when it wants consistency this strong.

The goal of xDS is always to provide the use case a choice in consistency models. With eventual consistency, the original xDS state, there was no special handling of failed resources, instead you build your system to work around this, e.g. by doing make-before-break.

So, I'd be hesitant about building something very complicated in Envoy and xDS if we can push this back on those management servers that want this.

**Comment by fredlas** [comment]
Oh, yes, that definitely makes sense!
