### ISSUE TITLE
mitigate delayed close timeout race with connection write buffer flush - reopen

### ISSUE THREAD

**Issue by MarcinFalkowski** [envoyproxy/envoy#6616]
This is a follow up to a previous issue: #6392
That issue was closed due to a fix: #6437

I reopen this, because I am worried that previous issue has not been fixed. 
I see approach to solving that issue changed over time and unfortunately I missed that change in PR. Sorry for not expressing my doubts earlier.

So these are my concerns / questions. Thank you in advance for answering these:

From the docs, regarding `delayed_close_timeout`:

> To be useful in avoiding the race condition described above, this timeout must be set to at least <max round trip time expected between clients and Envoy>+<100ms to account for a reasonable “worst” case processing time for a full iteration of Envoy’s event loop>.

And @alyssawilk comment from PR:

> I will say that with the new plan I'm not convinced that this solves #6392 insofar as 20ms pretty short. That said I think it solves an underlying problem worth solving and #6392 may simply need longer timeouts.

I understand that short timeout will not protect against race condition described in the docs (race between closing and client processing response data). But will a race condition with write buffer flush still be possible? I mean, is there a chance, that Envoy will truncate a response when `delayed_close_timeout` is set to low value (20-50ms)?

Another thing from that PR that I am worried about is the information, that disabling `delayed_closed_timeout` can cause connection leaking. So it turns out, that it is also bad idea. It's unfortunate, because this was our workaround for this whole issue.

I see we only have the following options:

1. disable `delayed_close_timeout`
  * PROS:
    * we are immune to race between connection closing and write buffer flush
    * we are compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)
  * CONS:
    * we are exposed to connection leaking
    * we are exposed to race between client response processing and connection closing
2. set `delayed_close_timeout` to low value (< 100ms + round trip)
  * PROS:
    * we are immune to connection leaking
    * we are compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)
  * CONS:
    * we are exposed to race between connection connection closing and write buffer flush (is this true?)
    * we are exposed to race between client response processing and connection closing
3. set `delayed_close_timeout` to high or default value
  * PROS:
    * we are immune to race between connection closing and write buffer flush
    * we are immune to race between client response processing and connection closing
  * CONS:
    * we are NOT compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)
4. Fix the client, so it will work well with delayed close

Based on this table, options 1-3 are not good enough. Is the option 4. our only option?

IMHO the missing option is: wait for write buffer flush for a reasonable long time (1s for example), and then close the connection immediately, or after a short amount of time. With this option, the only CONS I see is "we are exposed to race between client response processing and connection closing" which is good enough for us. I believe this option will require introducing separate timeouts for buffer flush and delayed closing.

**Comment by htuch** [comment]
@AndresGuedez since you worked on https://github.com/envoyproxy/envoy/pull/6437, do you have any thoughts on this?

**Comment by AndresGuedez** [comment]
> I understand that short timeout will not protect against race condition described in the docs (race between closing and client processing response data). But will a race condition with write buffer flush still be possible? I mean, is there a chance, that Envoy will truncate a response when `delayed_close_timeout` is set to low value (20-50ms)?

With PR #6437, Envoy will truncate the response only if there is backpressure to Envoy writing data to the client's socket and this causes write events to stall for an interval >= `delayed_close_timeout`. Prior to that PR, Envoy would close the connection early even if data was being regularly written to the client's socket.
 
> Another thing from that PR that I am worried about is the information, that disabling `delayed_closed_timeout` can cause connection leaking. So it turns out, that it is also bad idea. It's unfortunate, because this was our workaround for this whole issue.

Unfortunately, connection leaks were possible prior to PR #6437 when `delayed_close_timeout` is disabled. For simplicity of configuration and implementation, it's desirable to have fewer timeouts so this timeout also serves as an idle timeout. My expectation with this timeout is that there are very few use cases where an end user will choose to disable the timeout or set a low value against the recommendation, so the dual purpose seemed appropriate.

> 
> I see we only have the following options:
> 
> 1. disable `delayed_close_timeout`
> 
> * PROS:
>   
>   * we are immune to race between connection closing and write buffer flush
>   * we are compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)

Can you provide details on why delayed connection closing is an issue with Varnish healthchecks? Why is it an issue to wait 1s (by default) for those connections to terminate?

> * CONS:
>   
>   * we are exposed to connection leaking
>   * we are exposed to race between client response processing and connection closing
> 
> 1. set `delayed_close_timeout` to low value (< 100ms + round trip)
> 
> * PROS:
>   
>   * we are immune to connection leaking
>   * we are compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)
> * CONS:
>   
>   * we are exposed to race between connection connection closing and write buffer flush (is this true?)

It's possible if TCP ACKs from the client are not received within `delayed_close_timeout` window.  

>   * we are exposed to race between client response processing and connection closing
> 
> 1. set `delayed_close_timeout` to high or default value
> 
> * PROS:
>   
>   * we are immune to race between connection closing and write buffer flush
>   * we are immune to race between client response processing and connection closing
> * CONS:
>   
>   * we are NOT compatible with clients, that don't work well with delayed connection closing (e.g. Varnish healthchecks)

Please see my question re: the incompatibility of Varnish health checks and delayed connection close.

> 
> 1. Fix the client, so it will work well with delayed close
> 
> Based on this table, options 1-3 are not good enough. Is the option 4. our only option?
> 
> IMHO the missing option is: wait for write buffer flush for a reasonable long time (1s for example), and then close the connection immediately, or after a short amount of time. With this option, the only CONS I see is "we are exposed to race between client response processing and connection closing" which is good enough for us. I believe this option will require introducing separate timeouts for buffer flush and delayed closing.

Agreed this is another option. I was hoping to avoid this since adding more connection timeouts adds complexity for both Envoy developers and end users configuring the proxy, but it's possible your use case may be an exception to the dual purpose `delayed_close_timeout`.

My guess is that Varnish requires connections to be closed regardless of the HTTP response code prior to accepting a health check ack? If so, would it be possible to increase the Varnish health check timeout to be > delayed close timeout?

**Comment by MarcinFalkowski** [comment]
> Can you provide details on why delayed connection closing is an issue with Varnish healthchecks? Why is it an issue to wait 1s (by default) for those connections to terminate?

@AndresGuedez Sure. 

> My guess is that Varnish requires connections to be closed regardless of the HTTP response code prior to accepting a health check ack? 

Your guess is right. Varnish healtcheck (it is called a "probe") waits for connection closing by its backend (Envoy in this case) and adds that time to measured total time, which have to be less than the probe "timeout" parameter (otherwise heatcheck fails). Varnish doesn't close the connection by itself until the probe timeout triggers. In most recent version of Varnish this is even described in documentation https://varnish-cache.org/docs/6.2/reference/vcl.html#probes :

> Note that probes require the backend to complete sending the response and close the connection within the specified timeout

> If so, would it be possible to increase the Varnish health check timeout to be > delayed close timeout?

@AndresGuedez Yes, it would fix the problem. And It is possible, but very hard on our side. We have hundreds of varnish servers with thousands of healtchecks. And any of hundreds developers can create new ones. We would have to instruct them: "if your backend is Envoy, you should add +1s to varnish healtcheck timeout". Or we would have to create additional layer, which automatically modifies varnish configs. Either way it seems like over-complicated solution.

Varnish sends request request with `Connection: close`, but it doesn't close the connection after receiving a response. Thus I think Varnish violates rfc7230 section 6.6: 
> A client that sends a "close" connection option (...) MUST close the connection after reading the final response message corresponding to this request.

From this perspective it looks like this should be fixed in Varnish. But, on the other hand, we use Varnish with many http servers: various JVM servers, nodejs, nginx, apache, python/django and many others. And we never had this problem before with any of them. So it makes me think, that delayed connection closing is something very unique to Envoy. 

I think it is something worth a discussion: Should Envoy behave differently than most existing http servers/proxies? Or maybe this is not true and you know other servers which behave the same as Envoy?

If you think that current state is OK and there is no need to change, we would try to fix this in Varnish.

**Comment by AndresGuedez** [comment]
> > Note that probes require the backend to complete sending the response and close the connection within the specified timeout
> 
> > If so, would it be possible to increase the Varnish health check timeout to be > delayed close timeout?
> 
> @AndresGuedez Yes, it would fix the problem. And It is possible, but very hard on our side. We have hundreds of varnish servers with thousands of healtchecks. And any of hundreds developers can create new ones. We would have to instruct them: "if your backend is Envoy, you should add +1s to varnish healtcheck timeout". Or we would have to create additional layer, which automatically modifies varnish configs. Either way it seems like over-complicated solution.

Understood.

> Varnish sends request with `Connection: close`, but it doesn't close the connection after receiving a response. Thus I think Varnish violates rfc7230 section 6.6:
> 
> > A client that sends a "close" connection option (...) MUST close the connection after reading the final response message corresponding to this request.
> 
> From this perspective it looks like this should be fixed in Varnish. But, on the other hand, we use Varnish with many http servers: various JVM servers, nodejs, nginx, apache, python/django and many others. And we never had this problem before with any of them. So it makes me think, that delayed connection closing is something very unique to Envoy.

It seems most other proxies don't attempt to mitigate the connection close race condition that the delayed close timeout addresses. For your use case, it may be the case that clients and backends are well behaved in general, and your best option for now may be to simply disable this timeout. Doing so will leave open a small risk for connections to be leaked if they become inactive _after the close sequence has been initiated_, but this should be very rare. Prior to the delayed close timeout being introduced in 1.8, Envoy had no mechanism for addressing this type of connection leak, so if you were running Envoy prior to that version you were already exposed to this risk.

With that said, I agree this is not an ideal solution.

> 
> I think it is something worth a discussion: Should Envoy behave differently than most existing http servers/proxies? Or maybe this is not true and you know other servers which behave the same as Envoy?
> 
> If you think that current state is OK and there is no need to change, we would try to fix this in Varnish.

In my opinion, the best solution is that Varnish should become compliant with the HTTP spec and close connections after receiving the response from the backend. RFC 7230 6.6 provides a clear explanation as to why this is necessary:

> If a server performs an immediate close of a TCP connection, there is
   a significant risk that the client will not be able to read the last
   HTTP response.  If the server receives additional data from the
   client on a fully closed connection, such as another request that was
   sent by the client before receiving the server's response, the
   server's TCP stack will send a reset packet to the client;
   unfortunately, the reset packet might erase the client's
   unacknowledged input buffers before they can be read and interpreted
   by the client's HTTP parser.

As you already pointed out, the other option is for Envoy to implement a separate idle timeout at the connection layer to decouple the delayed close logic from the inactivity logic. I think this would be an unfortunate increase in complexity given that this is the only use case reported so far where the coupling of this logic has caused problems.

@mattklein123 @alyssawilk What are your thoughts on this? Which side of the line are you on regarding Envoy mitigating issues caused by clients not in compliance with (important sections of) the HTTP spec?

**Comment by alyssawilk** [comment]
I'd say that making Envoy more complicated to deal with non-compliant clients is not a high priority :-P

If folks are being impacted by this (yes) and have the cycles to dig into workarounds (maybe?  Marcin?) then we might allow the complexity, but I don't think it's a logical follow-on to Andres' work fixing the race for standards abiding clients.

**Comment by MarcinFalkowski** [comment]
> It seems most other proxies don't attempt to mitigate the connection close race condition that the delayed close timeout addresses.

@AndresGuedez So if I understand correctly, you say that other proxies are as vulnerable as Envoy with `delayed_close_timeout` set to 0. If this is true, we can accept that risk, because we are accepting it for years using other proxies and nothing ever happened.

@alyssawilk Yes, maybe it will be fixed on Varnish side (I created an issue: https://github.com/varnishcache/varnish-cache/issues/2994). If not, we can probably live with `delayed_closed_timeout` set to 0, because as @AndresGuedez said, the risk is very low.

Thanks for clear information.
