### ISSUE TITLE
router filter's global timeout timer starts later than the per try timeout one

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#6624]
*Title*: *router filter's global timeout starts later than per try timeout*

*Description*:
The router filter manages a per try timeout that puts an upper bound on the length of time an upstream request can take, and a global timeout that encompasses all upstream requests. However, there seems to be an oddity in that the global timeout timer is not started until after the full downstream request has been decoded (happens in `onRequestComplete()`) which can be later than when the per try timeout is armed (happens in `onPoolReady()`).

This is slightly problematic because of the fact that the per try timeout is disabled if it's larger than the global timeout (https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L150). However they're not measuring the same thing, so it's possible that the per try timeout could still fire first even if it is higher than the global timeout, in particular if the request takes a long time to decode. It also means that a global timeout alone will not protect you from a slow downstream client whereas a per try timeout does a better job just because it starts earlier (although this can be worked around by using `stream_idle_timeout` and `request_timeout` in the http connection manager).

A related problem is this assert: https://github.com/envoyproxy/envoy/blob/master/source/common/router/router.cc#L965. I believe it's possible to hit it if a retry due to per try timeout occurs before the full request has been decoded.

And here's an integration test case demonstrating the problem: https://github.com/envoyproxy/envoy/commit/d5b1de64ab22b8ccbea6cb7a290a8d95eb1afcdc. The test case is identical to the GlobalTimeout one at the top of the file except it doesn't finish writing the request (i.e. `end_stream` is true)

**Comment by mattklein123** [comment]
@mpuncel IMO it's a bug that the per-try timeout doesn't start when the global timeout starts. I don't recall the history of why it's implemented the way that it is. WDYT?

**Comment by snowp** [comment]
The per try timeout starts after `onPoolReady` is called, so i assume the idea is that the timeout should capture the upstream request time and not include stuff like receiving the downstream data.

Some options that come to mind:
 - start the *first* per try timeout at the same time as the global timeout, then proceed to restart the per try timeout on `onPoolReady` as it does right now. This is a bit weird because it means the first request has a tighter per try timeout than all the other requests since it includes more reading the downstream request.
- start the global timeout on when we see downstream headers. This means that we'll always start the global timeout before we arm the per try timeout. This will effectively shorten the timeout for existing use cases since we're starting the timeout earlier. Is this something we can safely do?
- start the global timeout the first time we see `onPoolReady`. This will also change the semantics of the global timeout, so it'll be decreased for use cases where the downstream request is slow/large and increase it for fast requests

**Comment by mattklein123** [comment]
> The per try timeout starts after onPoolReady is called, so i assume the idea is that the timeout should capture the upstream request time and not include stuff like receiving the downstream data.

As I said IMO this is a bug. 

> start the first per try timeout at the same time as the global timeout, then proceed to restart the per try timeout on onPoolReady as it does right now. This is a bit weird because it means the first request has a tighter per try timeout than all the other requests since it includes more reading the downstream request.

IMO this is what we should do. The idea here is that we control downstream timeouts with the HCM, and upstream timeouts with the router, but we shouldn't be accounting for downstream delay in the upstream timeouts.

**Comment by snowp** [comment]
@mattklein123 So are you saying we should start the global timeout where we today start the first per try timeout so that it's not dependent on when we finish reading the downstream request? Your comment and the quoted text seem to conflict

**Comment by snowp** [comment]
I guess I'm confused what "accounting for downstream delay" means in practice: should the router timeouts care when the downstream request completes? Or should they not start until the downstream request has finished so they're not accounting for downstream read time?

**Comment by mattklein123** [comment]
> I guess I'm confused what "accounting for downstream delay" means in practice: should the router timeouts care when the downstream request completes? Or should they not start until the downstream request has finished so they're not accounting for downstream read time?

Sorry for not being clear. IMO it's the latter. We should start the first per-try timeout when the global timeout stars (when downstream is complete), and then subsequent should start where it does now.

**Comment by snowp** [comment]
Ok thanks that cleared things up, seems like a reasonable solution. I'll try to get a fix up today
