### ISSUE TITLE
compile envoy on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by zplinuxlover** [envoyproxy/envoy#6911]
I compile envoy of master branch, but I got the error message,
I use the command 
     bazel build -c dbg  //source/exe:envoy-static

the error message is below

ERROR: /home/linuxlover/C++/envoy-master/source/exe/BUILD:27:1: Linking of rule '//source/exe:envoy-static' failed (Exit 1) envoy_cc_wrapper failed: error executing command /home/linuxlover/.cache/bazel/_bazel_linuxlover/00b64e74972e87e1f22d73a2a071beb5/external/local_config_cc/extra_tools/envoy_cc_wrapper -o bazel-out/k8-dbg/bin/source/exe/envoy-static -pthread ... (remaining 67 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: internal error in write_build_id, at ../../gold/layout.cc:5542
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 24.947s, Critical Path: 24.60s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by msamad** [comment]
I encountered the same error building it on Ubuntu 18.04 in WSL. The build process is a quite tricky in this one for someone new to these tools and bazel does not help much unless you really know what to look for. Anyways, after digging quite a bit and playing here and there, I managed to get a successful build.

Output for `lsb_release -a`
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
Output for `uname -a`
```
Linux DESKTOP-XXXXXX 4.4.0-18362-Microsoft #10000-Microsoft Fri Jun 21 11:23:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Outout for `uname -m`
```
x86_64
```

The solution in my case was to comment out `_envoy_stamped_linkopts()` for `linkopts` in `envoy_cc_binary` which is in `bazel/envoy_binary.bzl` file.

To simplify, in `bazel/envoy_binary.bzl`
change the following line
```
linkopts = linkopts + _envoy_stamped_linkopts()
```
to
```
linkopts = linkopts #+ _envoy_stamped_linkopts()
```

This give me a successful build. Now the reason for doing this is that if you run bazel with `-s`, it tells outputs the command it runs
If you run the following without commenting out ` _envoy_stamped_linkopts()`
```
bazel build -s //source/exe:envoy-static
```
It should give the big error but before error, it will print the full command it ran - the whole command will be wrapped in parenthesis. The important part of that full command is the following, I've split the command in multiple lines for easy understanding
```
envoy_cc_wrapper 
-o bazel-out/k8-fastbuild/bin/source/exe/envoy-static 
-pthread '-Wl,--hash-style=gnu' -static-libstdc++ -static-libgcc 
-Wl,@bazel-out/k8-fastbuild/bin/external/envoy/bazel/gnu_build_id.ldscript 
-Wl,-S '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -pass-exit-codes 
-Wl,@bazel-out/k8-fastbuild/bin/source/exe/envoy-static-2.params
```

Now running the same bazel command after commenting out ` _envoy_stamped_linkopts()`
```
bazel build -s //source/exe:envoy-static
```
would produce a successful build and produce the following command
```
envoy_cc_wrapper 
-o bazel-out/k8-fastbuild/bin/source/exe/envoy-static 
-pthread '-Wl,--hash-style=gnu' -static-libstdc++ -static-libgcc 
-Wl,-S '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -pass-exit-codes 
-Wl,@bazel-out/k8-fastbuild/bin/source/exe/envoy-static-2.params
```
If you compare this with the one for failed build above, you would notice that the line
```
-Wl,@bazel-out/k8-fastbuild/bin/external/envoy/bazel/gnu_build_id.ldscript 
```
is not there for the command that resulted in successful build.

Looking at the definition of `_envoy_stamped_linkopts` in `bazel/envoy_binary.bzl` indicates that similar issue happens on `macOS` and there is a fix already in place i.e. the select condition to do differently on `macOS`. `Ubuntu 18.04` in `WSL` is expected to work like any other Linux system but apparently it does not. 
```
def _envoy_stamped_linkopts():
    return select({
        # Coverage builds in CI are failing to link when setting a build ID.
        #
        # /usr/bin/ld.gold: internal error in write_build_id, at ../../gold/layout.cc:5419
        "@envoy//bazel:coverage_build": [],
        "@envoy//bazel:windows_x86_64": [],

        # macOS doesn't have an official equivalent to the `.note.gnu.build-id`
        # ELF section, so just stuff the raw ID into a new text section.
        "@envoy//bazel:apple": [
            "-sectcreate __TEXT __build_id",
            "$(location @envoy//bazel:raw_build_id.ldscript)",
        ],

        # Note: assumes GNU GCC (or compatible) handling of `--build-id` flag.
        "//conditions:default": [
            "-Wl,@$(location @envoy//bazel:gnu_build_id.ldscript)",
        ],
    })
```

Hope this helps!

P.S. I am still trying to wrap my head around all this build system for envoy so just a beginner. I haven't tested the binary that I get after the successful build so not sure if it breaks anything or not. There should be a proper solution to this instead of just commenting out like above, may be something like what has been done for `macOS`.

**Comment by lizan** [comment]
Sorry this somehow was buried in my inbox so I didn't take a look on it.

Can you paste what is in the file `bazel-out/k8-fastbuild/bin/external/envoy/bazel/gnu_build_id.ldscript`?

**Comment by msamad** [comment]
This is what I have in `bazel-out/k8-fastbuild/bin/external/envoy/bazel/gnu_build_id.ldscript`
```
--build-id=0x
```

**Comment by lizan** [comment]
@msamad which version of Bazel are you using?

**Comment by lizan** [comment]
that file should be like:
```
--build-id=0x3e63182c3e74e0d517d2f0d1fc2ee950bbfe21e1
```

which reflecting the git sha you're building.

**Comment by msamad** [comment]
> @msamad which version of Bazel are you using?

```
Build label: 0.26.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:35:14 2019 (1559032514)
Build timestamp: 1559032514
Build timestamp as int: 1559032514
```

**Comment by msamad** [comment]
> that file should be like:
> 
> ```
> --build-id=0x3e63182c3e74e0d517d2f0d1fc2ee950bbfe21e1
> ```
> 
> which reflecting the git sha you're building.

I see, let me do a clean build and see what I get

**Comment by lizan** [comment]
@msamad Try use the same version of envoy in `.bazelversion` file, or if that file doesn't exist, what you get from running `ci/run_envoy_docker.sh "bazel version"` (sorry this requires docker).

**Comment by msamad** [comment]
ok, I managed to get a successful build.

- Updated repo to the latest commit `8b549bd994a1256fb1913d5dce050a016ed63877`
- `.bazelversion` file has `0.28.1`
- `ci/run_envoy_docker.sh "bazel version"` returns
```
Bazelisk version: v0.0.8
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.28.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 19 15:19:51 2019 (1563549591)
Build timestamp: 1563549591
Build timestamp as int: 1563549591
```
- Updated my system bazel version to `0.28.1` based on above info

- Cleaned up the working directory with `bazel clean --expunge`
- Ran `bazel build //source/exe:envoy-static`
- The build was successful.

Only strange part is that when I checked `bazel-out/k8-fastbuild/bin/external/envoy/bazel/gnu_build_id.ldscript` file after the successful build, it was not there. Is that expected?

**Comment by Winbobob** [comment]
> that file should be like:
> 
> ```
> --build-id=0x3e63182c3e74e0d517d2f0d1fc2ee950bbfe21e1
> ```
> 
> which reflecting the git sha you're building.

Thank you!
I think the key part is this line: https://github.com/envoyproxy/envoy/blob/795ca0e1a30695d660f2648e6039957a4aa962f8/.bazelrc#L18
The script `get_workspace_status` let Bazel populate `bazel-out/volatile-status.txt` file with `BUILD_SCM_REVISION`.
And Envoy populates `gnu_build_id.ldscript` based on `bazel-out/volatile-status.txt` file, see https://github.com/envoyproxy/envoy/blob/49425f55aa9212a64b3390909160c41dc22ff349/bazel/BUILD#L40-L52

**Comment by Winbobob** [comment]
Note. If you build from a tarball instead of the git repo, you need to create the `SOURCE_VERSION` file via 
```
python3 tools/github/write_current_source_version.py
```
since tarball cannot get the git commit SHA.
