### ISSUE TITLE
Stats drop after hot restart

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#6924]
Since stats moved from shared memory to being copied over IPC (#5910), our metrics are seeing a transient drop during hot restarts. E.g.: for `cluster.${cluster}.health_check.failure`:

![image](https://user-images.githubusercontent.com/1349891/57642599-b76d3b00-7585-11e9-84aa-bf2f11f48378.png)

which isn't great because it triggers alerts, etc. I haven't looked into it too much yet, but one suspicion is that it's due to the overhead of copying things over....

Thoughts?

cc: @fredlas @mattklein123 @fishcakez

**Comment by mattklein123** [comment]
@rgs1 does the stat temporarily not exist? Is that the issue? Or is it going to 0 and then getting a burst? It's hard to tell. Also what stat sink are you using?

**Comment by fredlas** [comment]
I think what's happening is, the hot restart child is reading from those stats before they get copied over from the parent. With shared memory, it was not possible to read a value that wasn't the parent's current value, but with the new approach, there's a window.

Although, as far as the stat dumping goes, if the value hasn't been imported from hot restart, and hasn't been written to, it just shouldn't get exported, I think. So, maybe those drops are actually "no data" points being interpreted as 0?

I bet there's a fix to be had, regardless.

**Comment by rgs1** [comment]
cc: @sc0ttbeardsley

**Comment by rgs1** [comment]
@mattklein123 going to 0 and then getting a burst [confirming now tho]. We don't use a sink, we scrape /stats every 60 secs... [I know...]

**Comment by rgs1** [comment]
@mattklein123 this is what happens during a deploy if i scrape `/stats` every 50ms:

```
cluster.${cluster}.health_check.failure: 323321
cluster.${cluster}.health_check.failure: 323321
cluster.${cluster}.health_check.failure: 323321
cluster.${cluster}.health_check.failure: 323321
cluster.${cluster}.health_check.failure: 323321
cluster.${cluster}.health_check.failure: 0
cluster.${cluster}.health_check.failure: 0
cluster.${cluster}.health_check.failure: 0
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 2
cluster.${cluster}.health_check.failure: 3
```

**Comment by rgs1** [comment]
It takes > 90 seconds for stats to be copied over... That sounds like a lot of time?

**Comment by fredlas** [comment]
That does sound like a lot of time. It's also pretty surprising: the stat flushing in Server::InstanceImpl::flushStats() does the hot restart stat merge before calling flushMetricsToSinks(), and the hot restart child actually blocks on receiving the stats message from the parent. Short of knowing it outright doesn't have a hot restart parent, it looks like it's actually not possible for the child to skip past stat merging to stat flushing, without hitting a RELEASE_ASSERT.

I think the only way this could happen would be if the parent was choosing not to send all of its stats. Hmm, that makes me suspect this block of code:
```
// The hot restart parent is expected to have stopped its normal stat exporting (and so
// latching) by the time it begins exporting to the hot restart child.
uint64_t latched_value = counter->latch();
if (latched_value > 0) {
  [add latched_value to the hot restart message to be sent]
}
```

So, maybe before hot restart begins, the parent-to-be does a final latch of a certain counter. That counter doesn't get incremented again for ~90 seconds. As a result, no message includes it until then.

However, that wouldn't explain the jump back up. The 323320 part should be "in the past" and stay on the parent, which I believe was the intentional design.

**Comment by fredlas** [comment]
Maybe the "missing datapoints" idea is the missing piece. If what I just described happened, so that the child didn't receive any value for the counter for a while (and didn't have its own), it would just not export any value for the counter's delta that period. If the plotting thing it fed into interpreted "missing delta" as "missing stat" and brought it down to 0, that would be consistent with what is seen here.

**Comment by mattklein123** [comment]
> However, that wouldn't explain the jump back up. The 323320 part should be "in the past" and stay on the parent, which I believe was the intentional design.

Yeah, I don't think we are actually sending 323320 over, just the deltas. @rgs1 are the numbers you are showing grepped from `/stats` or are they coming out of your monitoring system?

**Comment by mattklein123** [comment]
Hmm. I know the problem. @fredlas, only statsd actually calls `latch()`. For everyone not using statsd they are going to see this problem. I think we need to lift the `latch()` mechanics out into being done by the server so that it's consistent?

**Comment by rgs1** [comment]
> > However, that wouldn't explain the jump back up. The 323320 part should be "in the past" and stay on the parent, which I believe was the intentional design.
> 
> Yeah, I don't think we are actually sending 323320 over, just the deltas. @rgs1 are the numbers you are showing grepped from `/stats` or are they coming out of your monitoring system?

grepping `/stats`

**Comment by fredlas** [comment]
Ok, I see. I think this might need a change to the Counter interface, although hopefully for the cleaner. Rather than having latch() be an atomic read-and-reset, let's have latch() just be a reset (and no longer return a value; maybe it should be renamed), and have a new delta() just be accessing the increment. Then, the use of latch() could be confined to just Server::Instance::flushStats (while not restarting) and the hot restart logic where it's currently being used. Sound reasonable?

**Comment by fredlas** [comment]
Oh, but then I guess if you're just accessing with delta(), you're going to miss increments if you aren't perfectly synced up.......

**Comment by mattklein123** [comment]
@fredlas my general thinking here is that we should keep the `latch()` functionality as is, but rework flushing for sinks so that we potentially drive it from server.cc (or some utility), which would iterate through state, latch, and then maybe call a more targeted function in the sinks with both the delta and the total. Or something like that. I would need to look at the code more to develop a more complete plan. Let me know if you want to poke around a bit or you want me to take a deeper look.

**Comment by fredlas** [comment]
I see, so rather than letting people call latch(), they instead need to provide a callback? Something like that? Maybe it would be best if you figure out what looks most likely to work before I start just trying to do something.

**Comment by mattklein123** [comment]
@fredlas sure I can do more investigation. I'm happy to work on this also if you are busy with other stuff. I might not get to it for a couple of weeks though.

**Comment by fredlas** [comment]
Sure, if you're interested, that might be best - I am not sure I have time unless this turns out to be pretty simple :-/

**Comment by mattklein123** [comment]
OK I'm working on a fix for this. @rgs1 when I have it would you be willing to test it in your env?
