### ISSUE TITLE
Define gauge HR merge type at definition point

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7080]
As a follow up to the hot restart stats evolution, we should move away from the hard coded stats merger map for gauges, and instead define this at the gauge definition point. This will likely mean creating new stats macros for gauges that encode the merge type.

**Comment by mattklein123** [comment]
@jmarantz one of us should do this since IMO it's a significant foot gun risk with the current code. Let's chat offline. cc @htuch

**Comment by jmarantz** [comment]
OK I'll grab it.

**Comment by jmarantz** [comment]
Rough plan:
  - add new pure API importMode() to class Gauge
  - add import mode enum selection to GAUGE macros
  - add required mode argument to gauge creation methods on stats allocator
  - get all that to compile.
  - run with checks against regexes to make sure all GAUGE macros are set with the same modes as
    we currently have from the regexes
  - get rid of the regexes

WDYT?

**Comment by jmarantz** [comment]
I'm making some progress, but I have some corner-cases to understand. One of them is what happens when a gauge is created in 'accumulate' mode. Then a new binary is released where we change the gauge to 'never-import' mode.  Currently, I think the import will not take place because we'll do a regex match on the stat name and find that we are disabling import.

Similarly, if a gauge was initially in never-import mode and then in the new binary the code is changed so the gauge is created in 'accumulate' mode, there will be no data about that stat sent from the parent process, so again we will not accumulate.

However, in the new system, we won't be using the regexes in production. Now consider 2 cases:
 1. The gauge was already created in the child process as 'never-import'. In this case, we can find the gauge and punt the transfer during the merge phase.
 2. The gauge was not yet created in the child process. In this case we'll create the gauge initially during the 'merge' process if because we'll assume it's an 'accumulate' based on its presence in the map. Only later, when the gauge is created by the child's code, will we come to learn it's a 'never-import'. I think the right thing to do is to zero the gauge and change its import-mode to 'never-import'. 

One thing that may be weird is that it could be exported from the child with its parents data before the child attempts to initialize the stat.

Does this sound like the right behavior?

@fredlas interested in your take here too.

**Comment by mattklein123** [comment]
@jmarantz the general plan looks good. Yeah, I was going to mention the corner cases that you mention (mainly around the stat getting created before the child initializes it with whatever import type it is). I have two potential thoughts here:

1) When we create a stat on behalf of the parent, perhaps just mark it as a special import type, "hot restart import," which would then signify that the child is allowed to create and change it to a different type in only that case?

2) We could potentially not do the immediate import via the temp scope, but actually hold the gauges until the child creates them with the right import type, and if the stat is never created the gauge would never show up? This actually matches the behavior we had with shared memory.

My inclination is that 2 is simpler. WDYT?

**Comment by fredlas** [comment]
I would expect that the import logic for a given stat should never change. If you can assume that, I think it should simplify things. If the stat is first created by the child defining it, then it gets the import type specified in the GAUGE macro. If the stat is first created by the child importing it, then it must be the "yes import" type. No need to do any sort of checks.

If a stat really does need to change, that could be a hot restart blocker. Although, I guess there's the issue of preventing the case where an author+reviewer both don't realize that it's not ok to change without changing HOT_RESTART_VERSION.

**Comment by jmarantz** [comment]
@fredlas RE "should never change" violates murphy's law, section 1, paragraph 1 :)

@mattklein123 I definitely like your first suggestion -- I'll just go back to using 2 flag bits to represent it. I think maybe I don't really need to do your second one though. I was worried about the admin /stats endpoint showing a value we'd discard, but we could just skip stats in this transient state, even if they are in the store. Could just modify shouldShowMetric() in source/server/http/admin.h to skip those -- or maybe just the call-site for gauges in handlerStats(). Might have to also look at stats sinks though -- I haven't poked around sinks too much.

How do counters and gauges get sent into sinks? I see in thread_local_store.cc how the histograms get in.

**Comment by fredlas** [comment]
That's what full restarts are for; please reread what I wrote.

**Comment by jmarantz** [comment]
Yup -- I read that. That latter issue of someone borking the ImportMode when creating a gauge, and in a later revision fixing it, not thinking this would be a hot-restart version-bump.

Also: I figured out the way gauges are captured, via MetricSnaphotImpl in server.cc. Will be very easy to filter out the not-yet initialized stats that were pulled in from the hot-restart protobuf.

**Comment by mattklein123** [comment]
@jmarantz @fredlas I definitely think we need to guard against someone changing the import type without understanding the implications.

@jmarantz I'm not sure whether it's easier to withhold the stats at push/pull time that came in from the parent or just not add them at all. It's probably a wash so I'm fine either way. 

Overall this plan SGTM.
