### ISSUE TITLE
How to restart envoy at docker container?

### ISSUE THREAD

**Issue by xxm404** [envoyproxy/envoy#7187]
**How to restart envoy at docker container?**

*Description*:
>when envoy running at docker container, __and pid is 1__,if execute `docker exec -d {container_id} envoy -c etc/envoy/envoy.yaml --restart-epoch 1 --log-level info --drain-time-s 60 --parent-shutdown-time-s 90` when parent shutdown, the current container also shutdow

**Comment by lizan** [comment]
@mattklein123 I think you previously mentioned container based hot restart is possible?

**Comment by mattklein123** [comment]
At a high level, in order to use hot restart the containers need to be able to talk to each other over unix domain sockets. This means they likely have to use host networking.

**Comment by derekargueta** [comment]
I implemented this a bit over a year ago - we do hot restarts across containers. The 2 container requirements I recall are 1) host networking (as Matt mentioned) and shared IPC for shared memory.

A few more things to consider
1) Both containers have to be running during the draining period, so the container names need to be different
2) If you have a container restart policy, it needs to not restart containers on clean exit, since a clean exit is expected on hot restart.

**Comment by easyfmxu** [comment]
> I implemented this a bit over a year ago - we do hot restarts across containers. The 2 container requirements I recall are 1) host networking (as Matt mentioned) and shared IPC for shared memory.
> 
> A few more things to consider
> 
> 1. Both containers have to be running during the draining period, so the container names need to be different
> 2. If you have a container restart policy, it needs to not restart containers on clean exit, since a clean exit is expected on hot restart.

@derekargueta We are interested in hot-restart with containers. do you have more details how do you do that? Also for things to consider. 2.  If you have a container restart policy, it needs to not restart containers on clean exit, since a clean exit is expected on hot restart. what does it exactly mean? Thanks

**Comment by ks864148379** [comment]
> I implemented this a bit over a year ago - we do hot restarts across containers. The 2 container requirements I recall are 1) host networking (as Matt mentioned) and shared IPC for shared memory.
> 
> A few more things to consider
> 
> 1. Both containers have to be running during the draining period, so the container names need to be different
> 2. If you have a container restart policy, it needs to not restart containers on clean exit, since a clean exit is expected on hot restart.

@derekargueta  Why should use host networking between containers? If I mount /dev and share IPC namespace and mount .sock between containers, envoy can hot restart too?
