### ISSUE TITLE
Add DataSource.http_uri for fetching blobs from remote HTTP endpoints.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#7311]
Currently, [`DataSource`](https://github.com/envoyproxy/envoy/blob/6a6e43a94201e9059de61fd6e94fda984615b54c/api/envoy/api/v2/core/base.proto#L175) blobs (e.g. TLS certificates) can be either inlined in the configuration or point to a file on the local filesystem.

Existing source types work fine for the small and/or easy to distribute blobs, but once we start including bigger blobs (e.g. WASM extensions), this is going to become an issue.

One solution for this is extending `DataSource` with [`HttpUri`](https://github.com/envoyproxy/envoy/blob/6a6e43a94201e9059de61fd6e94fda984615b54c/api/envoy/api/v2/core/http_uri.proto#L17) source type that would allow us to refer to blobs stored on remote HTTP endpoints and fetch them during configuration phase (this implies listener warming until the blob is fetched, etc.), ideally with some caching layer to avoid fetching the same blob multiple times.

We should also extend `HttpUri` (and/or `DataSource`) with `sha256` field to verify the checksum of the fetched blob.

This feature is rather important for the production deployments of [WebAssembly in Envoy](https://github.com/envoyproxy/envoy/issues/4272), but we somehow ended up with this effort completely unstaffed.

On a side-note, this might be a good good starter project for new Envoy contributors.

cc @duderino @mandarjog @silentdai @mattklein123 @htuch @lizan

**Comment by duderino** [comment]
Both @silentdai and @crazyxy said they could take this.   Post Thunderdome, one of them will claim it here.  But if someone else wants to grab it I doubt they'd object

**Comment by crazyxy** [comment]
I'll take this one.

**Comment by crazyxy** [comment]
I am working on this issue and stuck somewhere. After adding `HttpUri` as a data source, we need to support async data fetch. I tried to change current code from current data source to the new data source but came across several problems. 

I don't know how can we ensure that data is fetched before listener starts working. I know we can use `init manager`, `init target` and `init watcher` to coordinate the initialization. In order to ensure data is fetched before listener starts working, my idea is to bind `init target` to each remote DataSource and add it to `init manager`. When data is fetched, the target will send `onReady` notification. Since remote DataSouce could be used everywhere, does it mean that we need to add `init manager` everywhere?

@mattklein123 @htuch @lizan @PiotrSikora WDYT?

**Comment by lizan** [comment]
Adding HttpUri to existing `DataSource` structure might be too widespread than it has to be. e.g. there is no point to extend TLS key/cert data source to be an HttpUri given SDS exists, and the first cluster has no way to initialize such fetches.

Adding another type (`RemoteDataSource`? beat me on a better name) might make more sense, and then we will need a set of utility classes for that with coordinating init manager / target stuff with it. I think this will be easier because the places that it can be used are more limited. WDYT?

**Comment by silentdai** [comment]
Another way to think about it. We could add a AsyncDataSource which has one of  `RemoteDataSource` and existing `DataSource`.

**Comment by lizan** [comment]
Ah sorry for the confusion I meant "RemoteDataSource" being oneof (HttpUri, DataSource), so yes we need a better name.

**Comment by crazyxy** [comment]
Can we rename current `DataSource` to `LocalDataSource` and add a new `RemoteDataSource` which contains `HttpUri` and `sha256`. Have another `DataSource` which has `oneof` `RemoteDataSource` and `LocalDataSource`.

**Comment by crazyxy** [comment]
Can we rename current `DataSource` to `LocalDataSource` and add a new `RemoteDataSource` which contains `HttpUri` and `sha256`? Have another `DataSource` which has `oneof` `RemoteDataSource` and `LocalDataSource`. 

I am not sure about the risk of renaming.

**Comment by mattklein123** [comment]
I would not bother with renaming for this. IMO we can just use `RemoteDataSource` or `AsyncDataSource` or something like that.

**Comment by htuch** [comment]
+1 on having a distinct `RemoteDataSource` and skipping the rename. I think in the v3+ APIs we can clean this up a bit and add a `oneof`.

**Comment by silentdai** [comment]
@crazyxy and I had the discussion that to integrate the `asyncRead` api, a dispatcher is needed. Also a callback is need to continue the routines that need a content referenced by `RemoteDataSource`. `Init::Manager` should work. 

One of the WebAssembly use case is acting as network filter while the web assembly filter would use the result of that data source.

I am going to expose the InitManager to each network filter so that:
The filter could block the listener in warming state until the data source is fetched.

I am plan to provide `InitManager` as another context to the filter chain(so to each filter) that any single filter can register its own initialization procedure. Unlike SDS, I would assume the data referenced by `remotedatasource` is immutable during the lifetime of that listener.

P.S. For people who are aware of FilterChainDS. The `listener` above should be replaced by `filterchains`
