### ISSUE TITLE
Add static registration of AccessLog::Filter implementations

### ISSUE THREAD

**Issue by auni53** [envoyproxy/envoy#7326]
(This is a feature request.)

Currently there's no way to custom define your own custom AccessLog::Filters! Would be nice to have.

[This PR on static registration for AccessLog::instance](https://github.com/envoyproxy/envoy/pull/1609/files) should be a helpful reference.

cc: @ambuc @eziskind @AndresGuedez

**Comment by mattklein123** [comment]
+1

**Comment by efimki** [comment]
In first draft CL I've created a draft that adds a new Filter, 'ExtensionFilter' to AccessLogFilter.filter_specifier. 

I've defined a custom MockFilterFactory that registers 'mock_filter' and HeaderFilter underneath. This appears to work, but looks a little bit clunky.

I'm wondering if it is better to change FilterFactory::fromProto to use Config::Utility::getAndCheckFactory instead of hard-coded switch and register all currently-hardcoded filter types.

**Comment by efimki** [comment]
Hrm, I've found @htuch article [1] that seems to suggest that AccessLog.filter field should change from AccessLogFilter with 'oneof filter_specifier' to google.protobuf.Any that gets dynamically mapped into registered filter class. Does it make sense?

1. https://blog.envoyproxy.io/dynamic-extensibility-and-protocol-buffers-dcd0bf0b8801

**Comment by htuch** [comment]
As discussed offline, following the existing pattern of typed/untyped for this extension point in the v2 API makes sense.
