### ISSUE TITLE
Support protobuf logging

### ISSUE THREAD

**Issue by tschroed** [envoyproxy/envoy#743]
Initial change in. Items remaining:

- [ ] Docs
- [x] RequestInfo time cleanup and populate remaining fields
- [ ] Stats
- [ ] Plumb sample rate through from runtime filter to access log
- [x] Allow ability to set custom metadata from filters into access log and then send it as part of log (e.g., user ID, etc.).
- [ ] Populate TLS properties into access log
- [x] support HTTP custom request/response header logging

**Comment by mattklein123** [comment]
@tschroed big +1 from me. Can we potentially work on defining the initial proto here to get agreement? Then we can implement.

**Comment by dnoe** [comment]
I'll take this one next.  @mattklein123 Do you have any wishlist items for using this at Lyft I should take into account?  Otherwise I will use the existing access log as a starting point for defining the proto.

**Comment by dnoe** [comment]
I'm wrapping up the initial pass at this this and will push something for review to the API repo, it's taken a bit longer due to me learning about all the systems that will digest this on our side.  One mismatch that remains is that all of our internal logging keeps track of request+response bytes inclusive of headers but Envoy's format is exclusive of headers - just body bytes.  I can resolve this programmatically by tracking the header bytes separately and adding it back but before going too far down that path I'm also curious if there is any interest in moving to tracking the request and response size inclusive of headers.

**Comment by mattklein123** [comment]
@dnoe hmm. Good question. I think maybe we should support it both ways and allow different substitution variables to pick which one in RequestInfo? I can see people wanting both types. The current type roughly matches Apache logging style.

**Comment by mattklein123** [comment]
@dnoe @mrice32  let's chat offline, but we are going to need this at Lyft soon. Basically I want to create a gRPC logging API with a new logging provider that writes over the network to a streaming API. I talked to @htuch briefly and I'm not sure what overlap there is (if any) with what you are doing beyond just using the same log proto.

**Comment by htuch** [comment]
Is this done? Should we close out the issue?

**Comment by mattklein123** [comment]
I was using this to track the work items that I added to the description. There are still some things to finish up.

**Comment by mattklein123** [comment]
@lita @rodaine I updated the description with the remaining work that needs to be done on gRPC access logging to call it shipped. This can be done piecemeal while I'm out. We can dig into some details together next week.
