### ISSUE TITLE
Log error when per_connection_buffer_limit_bytes is exceed

### ISSUE THREAD

**Issue by gokhansengun** [envoyproxy/envoy#7430]
Envoy should log a warning or at least an info level log when the HTTP response body is over `per_connection_buffer_limit_bytes` and it produces an HTTP 500.

While debugging an issue (https://github.com/istio/istio/issues/13719) in Istio, we have had hard times in finding the root cause of an HTTP 500. It appeared to be due to `per_connection_buffer_limit_bytes`. Envoy logs did not mention the fact.

Would it be possible to add a warning or info level log to signify the fact?

**Comment by mattklein123** [comment]
Sure, PRs appreciated.

**Comment by gokhansengun** [comment]
Yeap, hopefully coming soon.

**Comment by alyssawilk** [comment]
So Envoy should be logging these and/or incrementing stats.  When the connection is closed due to
1) filters buffering rather than streaming and
2) responses being too large
It triggers one of a few code points.
If the request data is too large, it does
https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L2105
and you should see a   
ENVOY_STREAM_LOG(debug, "Sending local reply with details request_payload_too_large, details);
where request_payload_too_large has the details
//Envoy is doing non-streaming proxying, and the request payload exceeded configured limits.

If the response data is too large, 
https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L2223
will either sendLocalReply noting the response data is too large, or simply close the stream.
If the response is too large and headers have already been sent downstream, there isn't an explanation where we stream reset, so a log here
https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L2254
might be useful if the rs_too_large_ stat is insufficient for debug.
Make sense?

**Comment by PCaponetti** [comment]
@alyssawilk : chalk this up to a n00b mistake. on digging a bit deeper I see why this is not the right place to log anything, and after finding the where I think @gokhansengun would've wanted the log, I'm unsure a log would be necessary. @gokhansengun could you describe a little more about what you would like to see here? Did you get the 500 with `request_headers_too_large`?

**Comment by gokhansengun** [comment]
@PCaponetti while debugging the mentioned issue in Istio, I was getting HTTP 500 from Envoy. It was just looking like HTTP 500 was coming from the upstream though it was not.

What I am suggesting is to emit a log from Envoy so as to make the situation clearer for future occurrences.

**Comment by alyssawilk** [comment]
@gokhansengun as discussed above, now every time Envoy sends a local reply it logs at debug level that it sent the response and why.  Does that meet your need?

**Comment by gokhansengun** [comment]
yes @alyssawilk, that looks fine.

**Comment by PCaponetti** [comment]
@alyssawilk as noted above there's the situation where the stream is reset (after headers have been sent) that could use an extra log statement. I've got a small commit for that here: https://github.com/PCaponetti/envoy/commit/e3c60845504f0fc3005afaf6ee89b0aca63ee7d1

if you think it would be of any value LMK and I'll PR.

**Comment by alyssawilk** [comment]
Yeah, I think that'd help with debug if the response is too large after the headers are sent onwards.   feel free to send it my way

**Comment by PCaponetti** [comment]
done deal thx
