### ISSUE TITLE
Making outbound http requests from a filter

### ISSUE THREAD

**Issue by alexjames** [envoyproxy/envoy#7501]
Title: Making outbound http requests from a filter

Description:
I'm trying to write a Google OAuth 2 filter which requires me to make an outbound HTTP call to www.googleapis.com with the token so as to parse the token's information. I can't seem to find a generic http library in Envoy which allows me to do that. I looked at `Http:AsyncClient` and it seems that it requires specifying a cluster. I'm unsure if that's the expected way to making outbound HTTP calls. I'd expect something similar to what you'd find in other languages such as `send(URL, request)`. Is there a native/compliant library I can use for this? Google has it's own C++ library to make API calls but I'm unsure if it plays well with Envoy's async request-handling model.

Apologies beforehand if this has been answered elsewhere. I tried googling for a couple of hours and looking at other issues here, but I couldn't find anything. Thanks.

**Comment by alyssawilk** [comment]
Hm, I agree that async client is pretty tied to cluster.  

Without doing much digging I'd assume that Google has a gRPC API for what you're doing, and that'd probably be the easiest way to get this working.  You can see other examples of filters doing gRPC side calls, like the oath filter.

If that doesn't work I think this will require some code changes.  Last month I probably would have suggested refactoring it to be more neutral, but now it might make more sense to tweak @mattklein123 's forward proxy work since that handles the DNS lookup etc.

**Comment by mattklein123** [comment]
They way I would typically suggest doing this is to setup a logical_dns cluster for www.googleapis.com and then use that via async client. This is probably what you want given that all DNS resolution will then happen asynchronously. However, like @alyssawilk said, with the forward proxy work now well along, it probably would not be that difficult to get that working in the context of async client, though that is not something I'm planning on working on.

**Comment by alexjames** [comment]
Sorry about the delay in response, I was able to get this to work using a logical_dns cluster. Thanks Alyssa and Matt for your assistance.
