### ISSUE TITLE
build: define MEMORY_TEST_EXACT in specific target

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#7588]
*Description*:
MEMORY_TEST_EXACT is currently passed as cxxopt which means changing it invalidate all caches including dependency so it will be full rebuild, define it in bazel level and only define it via `select` in specific target will reduce the rebuild time.

**Comment by jmarantz** [comment]
I'm not following you. Wouldn't other flags have the same effect?

Also, MEMORY_TEST_EXACT is only set for release builds. Are release builds every used in CI otherwise? Or is the new build world you are working on making it possible for individuals building with "-c opt" in their dev environments share cache with CI release builds?

**Comment by lizan** [comment]
@jmarantz Sorry if the original description wasn't clear enough. If you do `--define` flag and `select` in specific target, Bazel is smart enough to keep the existing cache for the rest of targets because they are same after evaluating `select`. (e.g. changing boringssl=fips or normal won't trigger full rebuilt but only relevant targets).

In this case to repro: if you run `ci/do_ci.sh bazel.release.server_only` and subsequently `ci/do_ci.sh bazel.release` the second one would fully rebuild envoy binary while no source change involved.

**Comment by jmarantz** [comment]
Got it; thanks :) 

Actually I'm reconsidering use of -DMEMORY_TEST_EXACT at all; maybe it'd be better to just make a command-line flag and change do_ci.sh to set that. WDYT?

**Comment by lizan** [comment]
@jmarantz yeah that would be great too. up to you.
