### ISSUE TITLE
stats: Configurable Histogram Buckets

### ISSUE THREAD

**Issue by hrobertson** [envoyproxy/envoy#7599]
*Title*: Request: Make statistics histogram buckets configurable

*Description*:
Histogram buckets are currently hardcoded to cover a wide range of values (https://github.com/envoyproxy/envoy/blob/master/source/common/stats/histogram_impl.cc#L34)
Many users will benefit from customising the buckets to match their data/use case.

For example, the current buckets include a 10-30 second bucket. If the majority of an applications values fall in this bucket, the user would probably want increased resolution by having the boundaries be 10, 15, 20, 25, 30, for example.

In his implementation of histograms for Prometheus, @suhailpatel mentioned wanting to make this configurable: https://github.com/envoyproxy/envoy/pull/5601#discussion_r248099062

**Comment by jewertow** [comment]
I would like to implement this feature, but it will be my first contribution to envoy, so maybe do you have a suggestion how should I do it? How should it be configurable?

**Comment by mattklein123** [comment]
@ramaraochavali @postwait any thoughts on config for this?

**Comment by eightnoteight** [comment]
I felt like stats should be supporting summary type of metrics with configurable quantiles. because our problem with the hard coded buckets is that we couldn't properly track 95% percentile and 99% percentile.

making buckets configurable does solve our problem as then we can configure the buckets in such a way that 95% and 99% can be computable, currently even though 95% & 99% are different, because the buckets are spaced out very far, both the values look the same.

currently we are using statsd for this usecase to get proper 95 & 99 percentile

**Comment by eightnoteight** [comment]
@postwait 
can you please explain a bit more on the output transform and problems in choosing the bins for recording latencies

**Comment by postwait** [comment]
The "problem with choosing bins" is that Prometheus treats bins as separate series and apparently has limitations around cardinality there.  Envoy uses circllhist which tracks the data in a sparse set of ~43k bins.  The only reason transformation is "required" is to reduce that set of bins down to something Prometheus can cope with.  This transformation is trivial as you can just take the set of proposed Prometheus bin boundaries and ask the circllhist for a `count_below` on each.

The internal histogram implementation has very strong guarantees around the accuracy of quantile calculations.  However, Prometheus in its recommended configuration should never be used to calculate quantiles as they are wildly inaccurate due to poor bucketing choices.

There's no "good solution" here.  We could expose the quantiles to Prometheus, but then as you navigate around the time series, there would be no way to do the math on them (you can combine quantile calculations).  This is the same reason that exposing quantiles from statsd is a "very bad" practice.

Exposing the native histogram is the only way to allow for accurate quantile calculations, but Prometheus doesn't support this.

If you have a time series that is very important to calculate these things on and are stuck using Prometheus, you could expose a sufficient subset of the buckets to prom (likely < 1000 for a given series) and then Prometheus could more accurately calculate quantiles.

**Comment by postwait** [comment]
As a follow-up to this, please have a read of our paper:

https://github.com/circonus-labs/circllhist-paper/blob/master/circllhist.pdf

**Comment by Arnold1** [comment]
hi, 

@postwait any idea how to do that?

I also look for configurable histogram buckets:
to have histogram buckets from: 
```0.5, 1, 5, 10, 25...```
to
```0.5, 1, 5, 10, 15, 20, 25...```

**Comment by postwait** [comment]
Those boundaries all exist within the histogram, you just need to sum up the bins appropriately to get your desired boundaries. Upside is that with the bins you describe, you'll have 100% accuracy.

**Comment by Arnold1** [comment]
@postwait im not sure what you mean, could you show how?

**Comment by Arnold1** [comment]
@postwait any info?

**Comment by postwait** [comment]
You need to get the histogram out of envoy.  The move to openmetrics makes this harder.  I would expose the internal histogram over protobuf via the gRPC endpoint and then process it in the client.  I don't believe this has been implemented in Envoy yet.

You want 20ms, but tomorrow want 19ms... so if you get the full histogram out you can remove all that complication from Envoy just let the observer worry about it.

The internal histogram has about 43k possible bins, but they are almost always very sparse.  So ideally you just expose them all.  The problem is that the OpenMetrics approach to this is very inefficient.

**Comment by Arnold1** [comment]
@postwait ok thanks for the info. how can I get the internal histogram and how can I process it - do you mean in grafana?

**Comment by eightnoteight** [comment]
> hi,
> 
> @postwait any idea how to do the following with the current envoy?
> 
> I also look for configurable histogram buckets:
> to change the histogram buckets from:
> `0.5, 1, 5, 10, 25...`
> to
> `0.5, 1, 5, 10, 15, 20, 25...` ... I need buckets for 15 and 20ms...
> 
> @eightnoteight how did you end up getting P95 and P99?

ended up using the statsd exporter to customise the buckets, but later that has very little to none benefit with customising the buckets. still figuring out on proper use-case for customising the buckets, what was your exact use-case to have that extra 15 & 20 ms buckets ?

**Comment by ggreenway** [comment]
I'm hoping to fix this sometime in the next month or so.

My initial idea for how to configure it is to allow specifying a `repeated` message similar to the following in the bootstrap `stats_config`:

```
message HistogramBuckets {
    string regex;
    repeated double buckets;
}
```

**Comment by Arnold1** [comment]
@ggreenway why did you close it?
