### ISSUE TITLE
Support using streaming HTTP transport for sending traces to LightStep

### ISSUE THREAD

**Issue by xavierhardy** [envoyproxy/envoy#7618]
*Title*: *Support sending traces using streaming HTTP transport to LightStep satellite collectors*

*Description*:
>We have been recommended to use streaming HTTP transport for sending traces to satellite collectors. We haven't been able to migrate Envoy as there is no configuration option for that.

*Relevant Links*:
Configuration options for tracing using LightStep: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto#config-trace-v2-lightstepconfig

This requires upgrading the LightStep c++ library (https://github.com/envoyproxy/envoy/issues/7363)

cc: @tedsuo

**Comment by sbaum1994** [comment]
Hi Xavier - just wanted to respond on this issue. From speaking with @jmacd and @rnburn this would require significant effort to expose the streaming tracer from Envoy directly, since Envoy uses some customized options that aren’t available yet for the streaming transport on LightStep's latest C++ tracer.

It may be possible for you to use the streaming tracer via Envoy’s dynamic loading interface – similar to how it’s set up in this example for jaeger: [link](https://github.com/envoyproxy/envoy/blob/8bdebbfb936c533a822df9e96fd37be2cbdbab94//examples/jaeger-native-tracing/front-envoy-jaeger.yaml#L51-L68)
However, this would require you to include the LightStep C++ plugin in your server distributions that are hosting Envoy. 

The other alternative (since I know this is related to loadbalancing GRPC ingress on the Satellites) would be to run envoy as a front proxy to the Satellites so it could perform its own load balancing and we wouldn't need the HTTP streaming transport option. Based on how your current Satellite pool is hosted though I'm not sure if this is feasible. Best option may be to wait until you can run the Satellites on kubernetes, possibly with an Envoy proxy. (and then this problem will cease to exist)
