### ISSUE TITLE
route regex match fails for large URIs

### ISSUE THREAD

**Issue by skambashi** [envoyproxy/envoy#7728]
*Description*:
We've noticed that requests with a very long URI crashes our envoy service for routes defined using a regex matcher.

We're not sure if it's due to some overflow bug in Envoy's regex parser, but ideally Envoy should not crash because of a long URI.

*Repro steps*:
Define a route with a match regex like the following:
```
"match": {
    "regex": "/asdf/.*"
}
```
and then make a request with a large URI:
```
val longString = "a" * (50 * 1024)
client.send("GET", "/asdf/{longString}")
```

We've gotten around it by using a `prefix` matcher instead, but this appears to be a potential DoS vulnerability if not a security issue.

**Comment by dio** [comment]
cc. @jmarantz

**Comment by jmarantz** [comment]
Yeah regexes are like that. See the recent fun that happened at Cloudflare:

https://blog.cloudflare.com/cloudflare-outage/

and for more detail in:

https://blog.cloudflare.com/details-of-the-cloudflare-outage-on-july-2-2019/

I think you will be a lot happier with prefix-match :)

So I wouldn't be surprised that a regex can cause Envoy to get very low. I also might expect in some cases the regex library might throw during a match operation (not sure about this), and this path may not be well tested in Envoy. If that's an actual possibility I'd say the action-item for this bug is to repro and test a case where matching throws.

Another course of action is to add RE2 capability to Envoy. RE2 has a more restricted regex language which prevents catastrophic backtracking and also executes the regexes it does accept much more quickly than std::regex.

**Comment by PiotrSikora** [comment]
@jmarantz erm, Cloudflare's regex was much more complex (```(?:(?:\"|'|\]|\}|\\|\d|(?:nan|infinity|true|false|null|undefined|symbol|math)|\`|\-|\+)+[)]*;?((?:\s|-|~|!|{}|\|\||\+)*.*(?:.*=.*)))```) and failed because of backtracking.

Regex in this issue (`/asdf/.*`) is as trivial as it gets, and it's not acceptable for it to be a DoS vector. We should really move away from `std::regex` to RE2 or PCRE2 with limited backtracking.

**Comment by mattklein123** [comment]
For this reason I hate that we support regex matching at all. This type of situation is IMO almost unavoidable, though I agree with @PiotrSikora we should do better on this simple case.

**Comment by jmarantz** [comment]
Agreed. In any case I'll also note that we've observed that std::regex does memory allocations during matching, so it's possible that this crash could have been an OOM. I'm pretty sure RE2 does not do allocations during matching @yanavlasov might know for sure.

**Comment by yanavlasov** [comment]
The .* matcher in std::regex is recursive. It runs out of typical 1Mb stack with ~16k input. It will certainly OOM on 50k input.

**Comment by mattklein123** [comment]
std::regex has known issues and is not safe for general purpose use. I think the POR here is going to be to add a new "safe_regex" type using https://github.com/google/re2 and deprecate the existing regex matchers in various places. I can take this on.

**Comment by lizan** [comment]
FWIW this is the underlying bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164

**Comment by jplevyak** [comment]
I tested with libstdc++ and libc++.

libstdc++ crashes OOM at ~50K string length, and takes ~1000usec / regex_match.
libc++ doesn't OOM but at 50K takes ~9500usecs / regex_match.

So libc++ may not be a great solution for this issue since 1msec of CPU is quite a lot.

Re2 in comparision takes ~15useconds / FullMatch independent of string size.

**Comment by mattklein123** [comment]
@jplevyak nice, thanks for looking at that. FYI I'm working on re2.

**Comment by lizan** [comment]
@jplevyak thanks for the benchmark, we're in same page that adding re2 support (via different field `safe_regex` to keep the API backward compatibility) is the way to go.

I agree either of std::regex implementation in libstdc++ or libc++ is not great. The point of using libc++ is not because it doesn't OOM nor perform better, it is more because that's what we does in fuzzing test, so fuzzers weren't able to catch issue like this.

**Comment by mhite** [comment]
Is it safe to assume that the issue potentially exists in configurations that define `virtual_clusters` match patterns (and not just route matches)?

**Comment by mattklein123** [comment]
@mhite yes. See https://github.com/envoyproxy/envoy/pull/7878 for WIP fix.
