### ISSUE TITLE
x-envoy-original-path is not removed by VirtualHost.addRequestHeadersToRemove

### ISSUE THREAD

**Issue by mabukhovsky** [envoyproxy/envoy#7832]
My envoy config has prefix_rewrite set: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-prefix-rewrite
It is causing appearance of 'x-envoy-original-path' header that is sent to the upstream node.

I want to configure Envoy to not expose `x-envoy-original-path` in request header that is going out to an upstream node. For example, I've successfully used `VirtualHost.addRequestHeadersToRemove` to get rid of `x-envoy-expected-rq-timeout-ms`, but unfortunately it didn't work for for `x-envoy-original-path` header, and it's still present in request that is coming to the virtualHost's node.

Is it possible to get rid of `x-envoy-original-path` at all? If yes, I would appreciate your clue how to configure Envoy to work this way.

**Comment by zuercher** [comment]
You can suppress all x-envoy filters via the HTTP router filter's config: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/router/v2/router.proto#envoy-api-msg-config-filter-http-router-v2-router

Otherwise, that particular header is added after header manipulation configs are applied.

**Comment by suksw** [comment]
In case if anyone is looking for the new location: `suppress_envoy_headers` -> https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto
