### ISSUE TITLE
Skipping unsupported runtime layer: name: "base"

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#7919]
When starting up Envoy, it will log:

```
[2019-08-14 17:54:50.092][1][info][main] [source/server/server.cc:438] runtime: layers:
  - name: base
    static_layer:
      {}
  - name: admin
    admin_layer:
      {}
[2019-08-14 17:54:50.092][1][warning][runtime] [source/common/runtime/runtime_impl.cc:497] Skipping unsupported runtime layer: name: "base"
static_layer {
}
```

This is causing some confusion. What does this mean?

It seems like Envoy is trying to create some runtime layer "base" that it doesn't even support?

It seems to me, having no knowledge of runtime layers, that either
* Envoy shouldn't create this "base" layer
* Envoy should "support" this "base" layer
* Envoy should not warn about not supporting the base layer

Reproduce by running `docker run --rm -p 10000:10000 envoyproxy/envoy-dev:e1d713efc1342790208a86b7ba795d692b47f443`

**Comment by mattklein123** [comment]
cc @htuch and @asraa who has been looking at this recently. Can we make this more clear and/or fix if there is a default issue?

**Comment by asraa** [comment]
I believe this was just caused by #7251 and the case is missing because nothing needed to be done in LoaderImpl for that layer specifier case. Envoy shouldn't be logging a warning since this base layer is being used. Snapshots [pull this static layer directly from the config_](https://github.com/envoyproxy/envoy/blob/3dd84d3b41b6be378ccb71e81c0063a84bb956e3/source/common/runtime/runtime_impl.cc#L616). I'll defer to @htuch to confirm (and I can take care of it if that seems right).

**Comment by htuch** [comment]
@asraa correct, if you want to take care of the fix that SGTM. Thanks.

**Comment by howardjohn** [comment]
Confirmed fixed. Thanks @asraa!
