### ISSUE TITLE
v3 API: move CorsPolicy to per_filter_configs

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8097]
CorsPolicy exists before per_filter_configs, so it is in route directly now.

**Comment by lizan** [comment]
cc @envoyproxy/api-shepherds

**Comment by htuch** [comment]
I would like to approach this by adding to v2 the ability to first express `CorsPolicy` as a per_filter_config, deprecating the existing `CorsPolicy` field and then having `protoxform` auto-delete in v3.

I'm going to tag this as "help wanted", since we need to do the bulk of the work v2-side to make this happen first.

**Comment by ankatare** [comment]
@lizan  i would like to take this.
cc @htuch

**Comment by ankatare** [comment]
@lizan would you please provide some pointers for this issue to start. as i am beginner in project. so fwants to explore surroundings etc.

**Comment by ankatare** [comment]
cc @htuch

**Comment by ankatare** [comment]
unassigning myself as lack of info and low priority.
