### ISSUE TITLE
envoy.api.v2 regularization

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#8120]
One of the hangovers from the package structure introduced in early v2 was that` envoy.api.v2` had some special features that made it hard to treat systematically alongside other package namespaces, e.g. `envoy.config.bootstrap.v2`.

Specifically, it has subpackages that don't have versioning and some of the xDS services live in this package vs. `envoy.service`.

Within the scope of the v3 API migration is the removal of this inconsistency, this issue tracks.

**Comment by htuch** [comment]
FYI @kyessenov you may remember this.

**Comment by kyessenov** [comment]
Subpackages within v2 were introduced to group endpoint, route, cluster, listener protos. However, we could not move top-level protos for them from v2 package since protobuf Any uses fully qualified proto names in the services.

For new protos, we could create envoy.api.listener.v3, for example, to house all listener-related definitions.
