### ISSUE TITLE
Implement CDN loop detection

### ISSUE THREAD

**Issue by efimki** [envoyproxy/envoy#8183]
*Title*: *Implement CDN loop detection*

*Description*:

RFC 8586 [1] proposes CDN providers to develop CDN loop prevention mechanism by using a new CDN-Loop header. While more details are explained in RFC 8586 proposal, here we include a simple TODO list for this feature:

- Add a new CDN-Loop request header with configurable value when proxy is processing a request.
- Check whether a CDN request has CDN-Loop header with the same configurable value. If yes, deny that request with code 502.

*Relevant Links*:
1. https://datatracker.ietf.org/doc/rfc8586/

**Comment by zuercher** [comment]
If I understand correctly, you want to use Envoy to implement detection of the CDN-Loop header (responding with an error) and adding the header to the proxied request (for potential detection later if the request is circular).

I think you can already do this by adding routes [that match on the value of the header](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-msg-route-routematch) which perform a [direct response](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-msg-route-directresponseaction) with a 502. [Request headers can be added to proxied request](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-msg-route-routeaction) which covers the forwarding path.

**Comment by alyssawilk** [comment]
At first glance that sounds like a viable workaround but my intuition says this is something we may want as a core Envoy feature.
For Envoy cloud providers, customers are likely going to specify their own routes, and the likelihood of the majority of them doing this is roughly zero.    Basically I think loop detection ought to be a global configuration option rather than a per-route thing.

@htuch

**Comment by htuch** [comment]
In general, I'm an API minimalist and would recommend the solution @zuercher expressed. I agree with the point that @alyssawilk makes, but I lean on the API philosophy that we are creating a machine expressible language, and that UX improvements should be reflected in frontends to xDS. We're not exactly consistent with this, and @mattklein123 leans closer towards balancing UX with minimalism.

**Comment by zuercher** [comment]
It could also be implemented as an HTTP filter, I think.

**Comment by mattklein123** [comment]
FWIW this sounds like a good filter candidate to me.

**Comment by justin-mp** [comment]
I'm happy to work on this feature as an HTTP filter!

Parsing the CDN-Loop header in an RFC 8586-compliant way is somewhat annoying. You can't just split on `','` because the header allows parameter values that are quoted strings, which themselves can contain commas!  The best solution I've come up with is to go to the ABNF in the RFC and write a recursive descent parser.

Here's the approach I'd like to take to solving this problem, which I see forming 3 PRs:
1.  Write just enough of CDN-Loop header parser to pick out the RFC 8586 `cdn-id` values that appear in the header.
2.  Write a utility function to call the parser and count how many times a particular `cdn-id` value appears.
3.  Write the CDN-Loop HTTP filter.  The filter shall be configurable with (1) the `cdn-id` to look for and (2) the number of times it's allowed to be seen.  (It's possible that a CDN wants to let a request transit itself a small number of times before rejecting it.)  Call the utility function from the previous step to simplify the filter's implementation.

Does that make sense to people?

**Comment by alyssawilk** [comment]
Excellent, thanks!  Depending on how complicated 1) and 2) are it might be fine to fold them all together but otherwise this all sounds fine to me.
