### ISSUE TITLE
outlier detection: max_ejection_percent interfered by stats matcher unexpectedly

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#8259]
*Description*:
From https://github.com/istio/istio/issues/17004,

> Envoy use the stats key 
(https://github.com/envoyproxy/envoy/blob/38b926c63f347a70c933e0854ee9f31b1d2e85ce/source/common/upstream/outlier_detection_impl.cc#L420)
 `cluster.outbound|80||asm-test-http.default.svc.cluster.local.outlier_detection.ejections_active`  to record the count of the pods that be ejected in the cluster now

> the statsMatcher in the envoy bootstrap config is 
```
  "statsMatcher": {
                "inclusionList": {
                    "patterns": [
                        {
                            "prefix": "cluster_manager"
                        },
                        {
                            "prefix": "listener_manager"
                        },
                        {
                            "prefix": "http_mixer_filter"
                        },
                        {
                            "prefix": "tcp_mixer_filter"
                        },
                        {
                            "prefix": "server"
                        },
                        {
                            "prefix": "cluster.xds-grpc"
                        }
                    ]
                }
            }
        },
```

> `cluster.outbound` is not in the statsMatcher.inclusionList
so the counter ejections_active will be `NullCounterImpl` and always return zero

> it cause the field maxEjectionPercent failure to limit the number of ejected nodes

*Repro steps*:
See https://github.com/istio/istio/issues/17004

**Comment by nicktrav** [comment]
Recapping a conversation I had with @snowp on this - in the event that someone wants to pick this up that knows the Envoy codebase better than I.

If `ejections_active_` is filtered out (i.e. not enabled via inclusion of the metric) the following always comes out as zero:

https://github.com/envoyproxy/envoy/blob/7d3c6b2fc4a1b0a5c2e09f4167b13f36d6ac26a2/source/common/upstream/outlier_detection_impl.cc#L454

This results in the ejection branch of the if/else block always being run, which will eject all endpoints in the cluster if run enough.

Conceptually this should not be hard to fix that, we just need to track the value in the outlier detector instance, rather than relying on reading from the stats store.

 Correct me if any of this is inaccurate, @snowp, or if you have other thoughts on this.

**Comment by oblazek** [comment]
I can confirm the same behavior in different envoy version. When these stats are filtered out envoy will eject all hosts in a cluster (and doesn't honor MaxEjectionPercent).

**Comment by cpakulski** [comment]
I think that this issue has been fixed by https://github.com/envoyproxy/envoy/pull/11629. @lambdai please confirm, so it can be closed.

**Comment by lambdai** [comment]
@cpakulski Yes #11629 is the fix. Thank you for linking it

**Comment by ryant1986** [comment]
Hi, I'm seeing this behavior in istio 1.14, even after attempting to add the necessary stats to work around it
```
      proxyStatsMatcher:
        inclusionPrefixes:
          - "cluster_outlier"
          - "cluster_outbound"
          - "cluster.outbound"
        inclusionRegexps:
          - ".*cluster_outbound.*"
          - ".*cluster.outbound.*"
          - ".*outlier_detection.*"
          - ".*ejections_active.*"
```
I've confirmed that this isn't an issue in newer versions (1.20.2).  I'd like to get this working in an older version which we'll be running for some time in certain environments before we upgrade.  Can you confirm whether this stat configuration should fix my problem, and if not, what else I should try?
