### ISSUE TITLE
How do I make envoy log to the systemd journal other than using /dev/stdout?

### ISSUE THREAD

**Issue by Remz-Jay** [envoyproxy/envoy#8297]
*Description*:

I'm trying to make Envoy output access logs to my Systemd Journal rather than to a file.

Following #1291 i tried setting `envoy.http_connection_manager.access_log.config.path` to `/dev/stdout`.
This works when I manually run Envoy using `/usr/bin/envoy --config-path /etc/envoy/config.yaml`, but fails when started through `systemctl` with error:

```
unable to open file '/dev/stdout': No such device or address
```
Turns out that `stdout` is a symlink on my system:

```
envoy # ls -lsa /dev/stdout
0 lrwxrwxrwx 1 root root 15 16 sep 20:23 /dev/stdout -> /proc/self/fd/1
envoy # ls -lsa /proc/self/fd/1
0 lrwx------ 1 root root 64 19 sep 17:31 /proc/self/fd/1 -> /dev/pts/1
envoy # ls -lsa /dev/pts/1
0 crw--w---- 1 remco tty 136, 1 19 sep 17:31 /dev/pts/1
```
I tried setting `/dev/pts/1` as `path`, but that outputs the logs to my current console rather than to the systemd journal.

As such, how do I get Envoy to output logs to my journal rather than to a file, if `/dev/stdout` is not usable?

*Version info*:
```
envoy  version: 36cf26b9d6ac32f5671c24b92f9ea22ab70bc6c1/1.12.0-dev/Clean/RELEASE/BoringSSL
```
Manually compiled from source, running on Gentoo with Systemd, kernel 4.19.72  (so _not_ in Docker).

Systemd unit:
```
# /etc/systemd/system/envoy.service
[Unit]
Description=Envoy Proxy
Documentation=https://www.envoyproxy.io/
After=network-online.target
Requires=envoy-auth-server.service
Wants=nginx.service

[Service]
User=root
Restart=on-failure
ExecStart=/usr/bin/envoy --config-path /etc/envoy/config.yaml
[Install]
WantedBy=multi-user.target
```

**Comment by cetanu** [comment]
Did you manage to figure out how to do this? I'm also looking into it.

**Comment by cstrahan** [comment]
I forget the specifics of systemd's/journald's architecture, but I suspect that your process's `/dev/stdout` is a link to some socket under `/proc/self/fd`, and Linux doesn't support [`open(2)`](http://man7.org/linux/man-pages/man2/open.2.html)ing that link.

If you were to do this in your systemd unit:

```
readlink /dev/stdout
readlink -f /dev/stdout
```

I would bet you would see something like:

```
/proc/self/fd/1
/proc/29290/fd/socket:[994577]
```

To work around this limitation, you could change your unit like so:

```
ExecStart=bash -c '/usr/bin/envoy --config-path /etc/envoy/config.yaml | tee'
```

That would make envoy's `/dev/stdout` (i.e. file descriptor 1) be one end of a pipe, which envoy will have no problem opening. From there, `tee` will hand off envoy's output directly to _its_ file descriptor 1, which is the one set up by systemd in order to log to the journal. `tee` will have no difficulty doing so, because it directly uses file descriptor 1, instead of trying to open `/dev/stdout`.

**Comment by pelov** [comment]
My feeling is that this problem is still not properly resolved as it requires running envoy under bash.

Since the issue was opened there have been some changes in the access logging configuration of envoy by introducing explicit [envoy.access_loggers.stdout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/stream/v3/stream.proto#extension-envoy-access-loggers-stdout) and [envoy.access_loggers.stderr](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/stream/v3/stream.proto#extension-envoy-access-loggers-stderr) loggers. As far as I understand, they were trying to solve the problem of printing logs to stdout and stderr under windows (#13964). I was hoping that they will also solve the current problem but they haven't because the posix implementation still tries to open /dev/stdout and /dev/stderr which are missing under systemd and I am still getting the error:

`unable to open file '/dev/stdout': No such device or address`

My question is can't the posix implementation of stdout and stderr loggers also open directly fd 1 and 2 as the windows implementation and wouldn't that finally fix the problem?

I am also not sure if I should open a new issue (which essentially is the same problem as described here) or keep discussing it here.

**Comment by cetanu** [comment]
@dio (sorry, not sure who else to ping)
Could we get this re-opened, or should we submit a new issue to track the work to support stdout logging on linux?

**Comment by cetanu** [comment]
I was able to get envoy to log to stdout with the following systemd unit

```ini
[Unit]
Description=Envoy Proxy

[Service]
User=envoy
Type=simple
ExecStart=/usr/bin/envoy --config-path /etc/envoy.yaml
StandardOutput=journal # <------------------------------------------------ this
LimitNOFILE=1048576:1048576

[Install]
WantedBy=multi-user.target
```

**Comment by man-htsts** [comment]
> To work around this (Linux) limitation, you could change your unit like so:
> 
> ```
> ExecStart=bash -c '/usr/bin/envoy --config-path /etc/envoy/config.yaml | tee'
> ```

`pipefail` option and `sterr` redirection to `stdout` can be also usefull here:
```
ExecStart=bash -o pipefail -c '/usr/bin/envoy --config-path /etc/envoy/config.yaml 2>&1 | tee'
```

**Comment by eatnumber1** [comment]
@pelov you can get rid of bash in the resulting process tree. I'm not an envoy user, but it's the same for my use case (qbittorrent):

1. Exec the intended process
2. Make tee ignore the TERM signal, and
3. Fix the name in journalctl

Here's my setting for qbittorrent, but it should apply equally to Envoy.

```
ExecStart=/bin/bash -c 'exec /usr/bin/qbittorrent-nox --profile=/var/lib/qbittorrent > >(env --ignore-signal=TERM tee -p)'
SyslogIdentifier=qbittorrent
```

Something like this?

```
ExecStart=/bin/bash -c 'exec /usr/bin/envoy --config-path /etc/envoy/config.yaml > >(env --ignore-signal=TERM tee -p)'
SyslogIdentifier=envoy
```
