### ISSUE TITLE
SDS: request certificate for Envoy-generated private key

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#8372]
One approach to avoid sending private keys over SDS channel is to let Envoy generate private key on-demand, and ask SDS server to mint certificate for it, based on the credentials used to establish the connection between Envoy and SDS server (e.g. JWT token or TLS client certificate).

Generating private key takes from ~5ms (for P-256 ECDSA) to ~100ms (for 2048-bit RSA).

This proposal doesn't require any changes to the SDS protocol on the wire, but it would introduce new conventions regarding encoding magic values in the resource names.

1) `name: "generate:<type> name:<name>"` received in `tls_certificate_sds_secret_configs` in the xDS response would tell Envoy to generate a private key of a specific `<type>` (e.g. `rsa-2048` or `ecdsa-p256`), and request a certificate for it using SDS.  The `<name>` is used, so that control plane can refer to the same keypair in multiple places.

2) `name: "pubkey:<base64-encoded-public-key>"` received in the SDS request would tell SDS server to mint a certificate for the requested public key. The certificate will be generated for the identity based on the credentials used to establish the connection between Envoy and SDS server (e.g. JWT token or TLS client certificate).

Example exchange could look like this:

`ListenerDiscoveryResponse`:
```
[...]
  tls_context:
    common_tls_context:
      tls_certificate_sds_secret_configs:
        name: "generate:ecdsa-p256 name:identity"
        sds_config:
          [...]
[...]
```

`SecretDiscoveryRequest`:
```
type_url: type.googleapis.com/envoy.api.v2.auth.Secret
resource_names:
- "pubkey:<base64-encoded-public-key>"
```

`SecretDiscoveryResponse`:
```
type_url: type.googleapis.com/envoy.api.v2.auth.Secret
resources:
- name: "pubkey:<base64-encoded-public-key>"
  tls_certificate:
    certificate_chain: "<certificate-chain>"
    private_key: ""
```

This is a bit hacky, but it would work without any changes to the xDS APIs.

cc @louiscryan @htuch @mattklein123 @lizan

**Comment by mattklein123** [comment]
@PiotrSikora should we consider just implementing ACME support inside Envoy? This would be a lot more work but would be a hugely popular feature and then there would be no hacks here. WDYT?

**Comment by mattklein123** [comment]
ACME support issue: https://github.com/envoyproxy/envoy/issues/96

**Comment by lizan** [comment]
@mattklein123 my take on ACME is we can implement SDS add-on to existing ACME clients (e.g. certbot) so Envoy can talk to it. Full ACME client implementation inside Envoy sounds too much but I'm not against to that.

**Comment by PiotrSikora** [comment]
ACME is quite a different beast, and much bigger project. It's mostly concerned about proving that the requester can use requested identity, which we want to ignore in this proposal, and handle out-of-band (in relation to xDS protocol).

Also, there is a discussion to be had to decide which component (Envoy or xDS control plane) should be implementing ACME.

For edge servers, IMHO, it should definitely be the control plane, since you don't want hundreds of servers requesting the same WebPKI certificate from the CA.

For the service mesh, that argument is a bit weaker, but most of the time those instances won't be exposed directly to the Internet, so proving the identity using existing ACME mechanisms might be a bit tricky.

If that's the consensus, then we still need SDS to request TLS certificates from the control plane.

**Comment by lizan** [comment]
re: original request, I'm not fan of hacking on name based on that, is `name` the only field in the xDS request that can be customized?

**Comment by costinm** [comment]
Is it that hard to add another field ? 

Re. ACME - I think it would be simpler to have ACME behind SDS, i.e. Envoy uses SDS to talk with the control plane, and that handles ACME. The reason is that you need to create an account, store some keys for revocation, figure out a mapping for the HTTP challenge, possibly store the certificates - things that may require higher privs than envoy workloads.

**Comment by costinm** [comment]
Also there is the issue of permissions/authentication of  the workload - ACME with HTTP challenge might work if there is a single envoy with a public IP, but in a distributed system with envoy behind a load balancer it's a bit trickier even for HTTP challenge. 

And if DNS challenge is used - you need highly sensitive credentials for DNS, which are probably safer in the XDS or an isolated server, not on the VM running envoy.

**Comment by htuch** [comment]
* Prefer not to use resource name. I think for v2, this should not be a pub-sub but instead move to a custom bidi gRPC protocol like LRS/HDS. In UDPA we can revisit as we regularize this.

* If we are going to invent a new protocol (see ^^), then it would be good to rule out whether something like ACME can't address use cases. Prefer to use standards rather than invent new ones.

**Comment by mattklein123** [comment]
I mostly bring up ACME because it seems like we are developing something similar and per @htuch we should use a standard if there is one. I'm not an expert in this space so if we believe that ACME is not the right solution lets document that clearly when we implement whatever we implement. And if we believe that's the case I would like to close https://github.com/envoyproxy/envoy/issues/96 as something we won't implement.

Assuming we don't do ACME and have our own SDS-ish API, why do we have to have a hacky solution? Can't we just extend the SDS request/response to support our use case explicitly?

**Comment by costinm** [comment]
ACME is great - but I don't think implementing it directly in envoy is ideal. Quite a few servers do this - and it works for the simple case ( single server with public IP ). However advanced cases like getting a wildcard cert require DNS access. There are quite a few implementations of ACME client, and relatively easy to integrate in an XDS server.

SDS is good for pushing certs dynamically to envoy and other servers (in particular with quick rotation of certs), and running it on the same cluster with the XDS server allows reusing the H2 connection. I think as UDPA evolves it would be great if various certificate providers adopt SDS as a common protocol for cert rotation/provisioning.

Agreed, non-hacky is probably simpler and cleaner than hacky :-)

**Comment by htuch** [comment]
@PiotrSikora @costinm friendly ping; any progress on this? Would be nice to have a design doc as next step, but I think we're still debating ACME vs. custom SDS. Are there any additional folks in the community who are familiar with CSR/CA protocols and would like to weigh in?

**Comment by mattklein123** [comment]
cc @richarddli @SecurityInsanity IIRC Datawire is interested in doing built-in ACME support in Envoy so we should take that into account as we might have resources to do ACME if that is the right thing to do.

**Comment by SecurityInsanity** [comment]
Being able to have Envoy manage the ACME certs would definitely be a nice thing for us. That being said I agree there are a lot of challenges to bring ACME support into envoy (since there are a lot of cases that aren't covered just thinking about it: "how do we deal with a challenge coming to a wrong envoy node in http mode", "we probably don't wanna manage dns directly in envoy so that rules out dns challenge", etc. ; although I'd love to be proven wrong on this, cause it would be nice).

If this is something people want (which it sounds like it is) I think it'd be great to have support for it in SDS first, and then open up a bigger planning doc around ACME if we decide that's something we still want to pursue (which we at Datawire would like).
