### ISSUE TITLE
bazel/cc_configure.bzl breaks builds for C libraries

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#839]
It forces use of `g++` to even compile `.c` files, causes failure.

@htuch

**Comment by lizan** [comment]
cc https://github.com/istio/proxy/pull/260

**Comment by htuch** [comment]
Which C libraries are these?

**Comment by lizan** [comment]
gRPC

**Comment by htuch** [comment]
Basically, Bazel is completely broken today and tries to build C files with `gcc` instead of `g++` (see https://github.com/bazelbuild/bazel/issues/2840). We needed to override this for C++. I think it wouldn't be much work to convert `bazel/cc_configure.bzl` to sanely handle both C and C++ with `gcc` and `g++` respectively. I can do this, but not for a few days as I'm committed right now to the cmake-Bazel handoff, so if you need it before then, we welcome PRs.

**Comment by lizan** [comment]
Yes I understand. For now we can live without using cc_configure so it is not urgent, will do a PR if I have cycle.

**Comment by jmillikin-stripe** [comment]
This is fixed now, using the wrapper script in https://github.com/envoyproxy/envoy/pull/2631.
