### ISSUE TITLE
ci: pedantic spellcheck's demands are mysterious

### ISSUE THREAD

**Issue by fredlas** [envoyproxy/envoy#8481]
The pedantic spellcheck format presubmit does not point out the words it's unhappy with. I think it used to? Anyways, #8478 is currently in a situation where the format presubmit is failing, *and I don't know how to fix it.* I got a failure, looked at the log, added to the dictionary what I thought each line was complaining about. Got another failure, saw that two lines were still present, added something else. Got *yet another* failure, and now I can't think of what it might want.

Related / even better solution: I would like to propose turning this check off. I think #8478 makes for an excellent example. The PR was large enough that I did in fact let several typos slip in.... all of which were caught by the regular spell checker. Grammar is a much larger obstacle to readability than spelling, meaning that the relative benefit of a spell checker is very small. If a relatively very small benefit comes with any amount of toil, I think it very quickly becomes not worth it.

**Comment by mattklein123** [comment]
Overall I have found the spell checker to be useful.

Let's fix the usability issues vs. removing it. cc @zuercher who can likely help.

**Comment by zuercher** [comment]
I'll try to find some time to make it handle camel case words better. Currently before reporting a misspelled word, it'll try to break apart camel case and check the words individually. If one of the parts is misspelled, it presents the entire camel case word.

There are also a number of typos that have snuck in because we currently accept run-together words. I'll probably turn that off and do a pass of fixes.

**Comment by zuercher** [comment]
#8670 bounced, so reopening.
