### ISSUE TITLE
Need help understanding various timeout values when used with SSE and connection re-use

### ISSUE THREAD

**Issue by cyrus-mc** [envoyproxy/envoy#8517]
*Description*:

I apologize if this isn't the place to get questions answered. 

I am attempting to understand the various timeout values (cluster_idle_timeout, route idle_timeout, route timeout, etc) and how that impacts long lived connections (ie: SSE) and connection re-use.

Consulting the documentation:

[route.timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction)

> This spans between the point at which the entire downstream request (i.e. end-of-stream) has been processed and when the upstream response has been completely processed.

[route.idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction)

> Specifies the idle timeout for the route. If not specified, there is no per-route idle timeout, although the connection manager wide stream_idle_timeout will still apply.

All that seems to make sense and is validated through my tests. The one question I do have is for route.timeout where it talks about end-of-stream. For an SSE connection that is essentially a long lived connection. There is no end until either end of the connection terminates.  What I have found works is to set the route timeout to 0 (so never time out) and set a sane idle_timeout (we send keep alive messages every 15 seconds). 

[http_connection_manager.idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto)

> The idle timeout for connections managed by the connection manager. The idle timeout is defined as the period in which there are no active requests.

My initial thought was this was a global route.idle_timeout but after testing and further reading it appears the stream_idle_timeout is the global equivalent to route.idle_timeout. As the doc says this is the idle timeout for which there are no active requests. In the case of an SSE connection there is only really ever one request and then the server just pushes responses over time. I could not find where this timeout came into play. If my SSE connection finished the connection would not terminate until the stream idle timeout was hit (for my tests it was set to a higher value then the idle_timeout). 

Lastly is connection re-use. Is envoy able to mutii-plex multiple SSE streams over a single connection to an upstream server? I am finding that if I open up 6 SSE connections I get 6 connections. In our case we are going to have on the upper end of 1000s of active SSE connections and trying to think about resource usage on the envoy side as well as the service side.

**Comment by zuercher** [comment]
I'm answer from memory, so I may be off in some details.

I would expect the long-lived SSE request to be considered active and so the http connection manager idle_timeout won't come into play. That timeout triggers when the downstream connection remains open without any pending requests.

As far as connection re-use goes, there are a couple of things at play here.
* Envoy will re-use connections to upstream hosts, but for http/1.1 Envoy will not send another request on a connection while a previous request is pending. Instead it will open another connection or wait for an existing connection to become available (See the circuit breaker settings.)
* Related to that, separate connection pools are maintained per Envoy worker thread. So if a different thread serves a request it may open another connection to a host even if an idle connection is available in another worker's pool.
* Upstream connections will be closed on timeouts and other errors since the connection is left in an indeterminate state.
* Not sure if it's feasible for you, but using http/2 would automatically give you multiple simultaneous requests per upstream connection.

**Comment by cyrus-mc** [comment]
@zuercher 

Thanks for your response. I have validated what you stated. 

The http connection manager idle_timeout only comes into play where there are no pending requests and a SSE request counts as a pending request. In this situation the idle_timeout for the route is what is important. 

As for connection re-use, again what you stated is correct. Using http/2 for upstream allows multiple requests per upstream connection. When using http/1 it will open another connection as there is an active/pending request on the current connection.

Thanks
