### ISSUE TITLE
should http healthchecker consider consecutive connection failures as active healthcheck failure

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/envoy#8622]
Recently we had an issue where the http healthchecker timeout was set to `200000000s` and one of the hosts had raw connection disconnects. All the requests to the host were timing out and the outlier detection was active, but the active health check was not failing possibly because of https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_checker_impl.cc#L188-L194 .
Should consecutive raw connection disconnects considered as active healthcheck failure?

**Comment by mattklein123** [comment]
To me it seems better to set an appropriate timeout and not count raw disconnects, but I don't feel super strongly about this. @snowp any thoughts?

**Comment by snowp** [comment]
I think changing behavior could impact existing use cases in which upstream hosts might be temporarily unavailable during startup (eg maybe the proxy is coming up concurrently with required iptables rules or something) that today are working fine because we block warming on initial health checks. If we start treating connection failures as failures we'd continue with warming and initialize earlier than we do now in certain cases.

I can imagine making this configurable, but would also think that relying on timeouts would be sufficient in most cases. Perhaps there is some additional documentation that could make this clearer?
