### ISSUE TITLE
Prefix match for routes

### ISSUE THREAD

**Issue by Kishn0211** [envoyproxy/envoy#9022]
Hi,

I want to match the prefix :  /myapp/v5/resource or  /myapp/v6/resource
 
I tried below based on the documentation "https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routematch-regex" and it's not working.
"match": {
                "prefix": "/myapp/v\d/resource"
              }

Any suggestions??

Regards,

**Comment by Kishn0211** [comment]
Even tried with the regex as below
"match": {
"regex": "/myapp/v\d/resource"
}

**Comment by htuch** [comment]
@Kishn0211 you definitely want regex rather than prefix match here. Please follow the guidance at https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routematch-safe-regex for recommended regex use. I would also suggest turning up logging to trace level to understand what is going on.

**Comment by Kishn0211** [comment]
@htuch 
I tried something like below and was working
"match": {
"regex": "/myapp/v[6-7]/resource"
}

Thanks for the support

**Comment by Kishn0211** [comment]
Mypath has matrix param. So it was not detected.
Url: host/myapp/v[6-7]/resource;myname="ktr";lastname="min"
Is there a way to write regex for this

**Comment by cetanu** [comment]
Documentation says:

> The rule will not match if only a subsequence of the :path header matches the regex

Your regex must match the entire URL.

Suggestion:

```
"match": {
  "regex": "/myapp/v[6-7]/resource.*?"
}
```
