### ISSUE TITLE
Redirect IP CIDR to Single IP

### ISSUE THREAD

**Issue by ivelichkovich** [envoyproxy/envoy#9047]
*Title*: *Is there a way to redirect a CIDR block to a single IP but append headers for the original destination IP and port?*

*Description*:
I want to redirect requests destined for a CIDR block to an external proxy while appending the original destination IP and Port as headers for the proxy to use. Is this possible? If not could someone point me in the right direction to contribute back these features.

**Comment by mattklein123** [comment]
This is not exactly supported today. I think you might be able to cobble this together using the original destination load balancer (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/original_dst#original-destination-host-request-header) and a filter chain match that only matches on a particular CIDR block. There might be other ways but that is the first thing that comes to mind. cc @snowp @lambdai @PiotrSikora @lizan

**Comment by lambdai** [comment]
If the CIDR block and the destination is static: you can enumerate the blocks, you can easily generate the listener config, adding an matcher and attach a http_conn_manager, and assign a cluster for the routes.
LDS, RDS, CDS are involved though but it is naive since it's pure config.

To reduce anyone, you might need to create a dedicate filter to embed your transform rules from block to IP
e.g.  if you can figure out the dest IP and inject the original dest ip header into the downstream request, you can utilize the original_dst cluster, replacing the enumerated static ip cluster.
You can also add a http filter to calculate and override the single IP so that the listener filter chain match could be a single `match-all-blocks`.
