### ISSUE TITLE
Is there a request queue metric? 

### ISSUE THREAD

**Issue by aclowkey** [envoyproxy/envoy#9201]
*Title*:  Is there a request queue metric?

*Description*:
I noticed that if my upstream can handle X requests per second, and I load test with say, 2X, envoy still reports X~ for upstream_rq, which makes me think it has a request queue for the active connections or something

Is there any metric exposed that indicates how many requests are queued?

EDIT: The motivation is to scale my service according to ACTUAL rps envoy gets, rather than perceived upstream request, and load X, and 2X seem to have the same _rq value..

**Comment by zuercher** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats#statistics

There are a number of metrics prefixed with `downstream_rq` that should help. The `downstream_rq_active` gauge is incremented at the start of each downstream request and decremented when the response is completed.

**Comment by aclowkey** [comment]
Thanks for the tip!
The `rq_active` metric seems to be more relevant as it represents to load accurately.
Does `rq_total` only count completed requests? why is the rate of `rq_total` and raw `rq_active` are different?

**Comment by cazorla19** [comment]
> Thanks for the tip! The `rq_active` metric seems to be more relevant as it represents to load accurately. Does `rq_total` only count completed requests? Why is the rate of `rq_total` and raw `rq_active` are different?

@aclowkey I might be late with this answer, but I think the difference between two of those comes with the format.

`rq_total` is a `counter` metric, which (by Prometheus format) means that it can be only incremented. Thus, `rq_total` gets incremented each time when the new downstream request starts. This metric represents the **total amount of requests** since the Envoy process start.

`rq_active` is a `gauge` metric, which represents the **current amount of requests**, i.e. amount of active requests processed at the time of metrics scrape.

Keep in mind that it's still going hard to catch small 5/10-seconds spikes as the default interval of metrics scraping is 60 seconds.
