### ISSUE TITLE
Run clang-tidy as part of CI.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#921]
Now, that we have Clang in CI, it would be good idea to catch common mistakes with `clang-tidy`.

@htuch

**Comment by mattklein123** [comment]
I'm not sure what clang-tidy does but we should run as part of check/fix format flows.

**Comment by rlazarus** [comment]
Despite the name, [clang-tidy](http://clang.llvm.org/extra/clang-tidy/) isn't a formatter -- it's a static analyzer that catches common correctness and performance issues. For example, see #1023 where it flags all the times our loop variables could have been const references but were instead causing unnecessary copies.

I agree this should be part of CI but offhand I don't think it's simple to do with bazel -- clang-tidy relies on a "compilation database" to understand how each file is built, and at least on a cursory look I can't find a good way to get bazel to emit one. Some folks have written their own janky-looking scripts, and I'll see if we can adapt one or produce a janky script of our own.

(In the meantime, thanks to some Google-internal infrastructure, we get clang-tidy findings when we import the Envoy code into our source repo, so until CI does this properly we can at least push those fixes back upstream pretty easily.)

**Comment by jsedgwick** [comment]
FYI as part of getting warmed up on envoy I sort of accidentally started working on this while setting up YouCompleteMe support. Got Bazel emitting compile_commands.json (just some modifications to some aforementioned janky script) but I'm a little stuck getting include paths working right when running clang tooling from the root of the repo. Basically, it all works fine if you find and cd into the bazel exec root, but for incremental checks where you want to work live on the repo I have to figure out how to get compile_commands pointed at all the right spot. E.g. `-Iinclude/` helps a bunch so that exported envoy headers make it in, but I'm still working on external deps (e.g. headers from rapidjson) and especially generated protobuf headers since those obviously require an actual compile of either envoy or one of its deps (e.g. data-plane-api). Any pointers especially appreciated! clang tooling is so awesome so it'd be nice to have its support available to all :)

**Comment by jsedgwick** [comment]
p.s., literally the first file i ran clang-tidy on i (rather, it) found a nasty bug waiting to happen, so we should definitely get this available! for devs locally and eventually in CI

**Comment by lizan** [comment]
Did anyone try this recently? I was able to generate compilation database with https://github.com/grailbio/bazel-compilation-database and then run clang-tidy with it.

**Comment by PiotrSikora** [comment]
@lizan for compilation database, there is also [Kythe](https://kythe.io), which supports [extracting compilations using Bazel](https://kythe.io/examples/#extracting-compilations-using-bazel), and which  might be potentially slightly more useful for us in the future.

**Comment by htuch** [comment]
@lizan if you can make this work that would be awesome. Do you want to own this one?

**Comment by lizan** [comment]
Sure I will take this one if no one is working on that.

@PiotrSikora I tried Kythe for a bit but it requires too many Java dependencies to generate compilation db.
