### ISSUE TITLE
quiche: add a reloadable feature to enable/disable QUIC support

### ISSUE THREAD

**Issue by danzh2010** [envoyproxy/envoy#9230]
Current QUIC support can only be turned on/off via LDS. We can do better here by adding an Envoy reloadable feature for QUIC to turn the switch via runtime dynamic config push.

**Comment by nezdolik** [comment]
@mattklein123, could help with this task.

**Comment by mattklein123** [comment]
@nezdolik sgtm. TBH though I'm not completely sure how we can do this easily since there is no fallback. I think the only thing we could potentially do is just have a kill-switch for the UDP processing in general and then assume the client has a fallback. @alyssawilk is that what you were thinking?

**Comment by alyssawilk** [comment]
Yeah.  Internally I _think_ we have two modes of shut-off.  One for "we would like to turn QUIC off gracefully" which stops reading and sends public resets to active sessions (a few per event loop), and the "UDP is deemed dangerous" which just stops all UDP traffic.
Either way all clients should always fail over to TCP because you can never trust UDP on the internet, so even with silent shut-off it should time out, re-try handshake, and fail over.  It just takes a bit more time without the reset.

**Comment by mattklein123** [comment]
Fixed.
