### ISSUE TITLE
json_grpc_transcoder: missing dependency google.grpc.status when building with clang bazel rbe

### ISSUE THREAD

**Issue by TAOXUY** [envoyproxy/envoy#9335]
When we built envoy with clang-8 and rbe, we always got

 .../external/envoy/source/extensions/filters/http/grpc_json_transcoder/BUILD:15:1: undeclared inclusion(s) in rule '@envoy//source/extensions/filters/http/grpc_json_transcoder:json_transcoder_filter_lib':
this rule is missing dependency declarations for the following files included by 'external/envoy/source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc':
  'bazel-out/k8-dbg/bin/external/com_github_googleapis_googleapis/google/rpc/status.pb.h'

After adding rpc_status_proto in external_deps in json_transcoder_filter_lib, it works. I can issue a PR if it is a bug.

**Comment by TAOXUY** [comment]
@nareddyt

**Comment by nareddyt** [comment]
RBE is [Google Cloud Remote Build Execution](https://docs.bazel.build/versions/master/remote-execution.html). We do not use remote build, only remote caching.

This occurs for commit `648cfc3b6c1410d8b27aa33b6fc0392ab230d601`, which is 3 weeks old. We double-checked that there are no new changes to that file since then.

@TAOXUY will link a quick PR to fix this. It just adds a dependency to the bazel target.

**Comment by TAOXUY** [comment]
https://github.com/envoyproxy/envoy/pull/9336
