### ISSUE TITLE
Question: Envoy asynchronous access logging

### ISSUE THREAD

**Issue by ramachaitanyak** [envoyproxy/envoy#9389]
Hello, can anyone clarify if envoy supports asynchronous logging outside filters ? I want to log some information that envoy receives after the filter issuing the request is deleted. Is this even possible ?

**Comment by derekargueta** [comment]
Can you provide more information on what it is you're trying to log, and why it has to be after the filter is deleted?

**Comment by ramachaitanyak** [comment]
@derekargueta Thanks for your interest. We deploy envoy on the edges and POPs; now there are few components in our infrastructure that are running inside data centers.

We have a custom envoy filter analyzing requests and when there is a pattern of interest; it is forwarded to a pool inside the DC. The pools inside DC have a special criteria for tagging these requests with a key that match patterns; further classifying these requests.

Essentially we use these keys tagged by the back-end pools to cache information at the edge. Now the response to the client or downstream end-user from envoy may or may not wait until for these responses issued from the back-end pools. We maintain data-structures to persist these keys; however wanted to log these keys through envoy, so that it plugs into the rest of the monitoring infrastructure.

I did some research on envoy docs, I came across these resources:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging#access-logging-sinks
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/file.proto#envoy-api-msg-config-accesslog-v2-fileaccesslog

I am trying to work with these; however I do not understand enough to conclude; if these interfaces perform asynchronous io to files, so that there is no performance degradation; behaving like any other filter logging.

Any thoughts ?

Rama

**Comment by derekargueta** [comment]
@ramachaitanyak yes, access loggers are asynchronous. They fill up a buffer[1] and periodically flush it[2] in an asynchronous thread[2].

[1] https://github.com/envoyproxy/envoy/blob/43c91d8cc050cab248cdef26e0703de310cdd438/source/common/access_log/access_log_manager_impl.cc#L192
[2] https://github.com/envoyproxy/envoy/blob/43c91d8cc050cab248cdef26e0703de310cdd438/source/common/access_log/access_log_manager_impl.cc#L194
[3] https://github.com/envoyproxy/envoy/blob/43c91d8cc050cab248cdef26e0703de310cdd438/source/common/access_log/access_log_manager_impl.cc#L199

**Comment by ramachaitanyak** [comment]
Thanks @derekargueta I understand the access logging is performed through asynchronous io in a non-blocking manner. Seems like my references for using FileAccessLog interface is on the right track. Please correct me if it is not so.

Thanks!
Rama

**Comment by ramachaitanyak** [comment]
Actually I am trying to perform logging in envoy outside the context of a filter. The abstractions that I came across are FileAccessLog and AccessLogManagerImpl. I wanted to confirm with you if this is the right approach to do it. 

I was thinking of an API that uses both these interfaces mentioned FileAccessLog  and AccessLogManagerImpl  in doing this. Is this the best approach ?

What I am not sure is the use of AccessLogManagerImpl  interface. In here, do I need to use the whole interface or inherit another interface from AccessLogManager  to simply re-implement reopen  and createAccessLog  API.

@derekargueta please let me know your thoughts

**Comment by derekargueta** [comment]
Can you define "outside the context of a filter"?

You can write a custom access log extension that works much like the [default file access logger](https://github.com/envoyproxy/envoy/tree/master/source/extensions/access_loggers/file). That is,
1) Write a factory that inherits `Server::Configuration::AccessLogInstanceFactory`.
2) Write the access logger, which for convenience should inherit `Common::ImplBase` but doesn't have to.
3) configure it in your listener's access loggers.

If you use `Common::ImplBase`, you implement an `emitLog` function that gets called once per request/response, and allows you to log any data present in headers or metadata. The disk I/O is asynchronous to the request path. Is this what you're looking for?

**Comment by ramachaitanyak** [comment]
@derekargueta thanks for the advise.

Essentially I am trying to log the response on AsyncClientImpl  callback. Having a factory instance is what I have been recommended as well by @zuercher . I will try this approach and get back. 

After few discussions; I have learnt that every network operation occurs through some filter in envoy. I think it is about understanding the right filters and use FileAccessLog instance (Server::Configuration::AccessLogInstanceFactory ?) via factory method.

**Comment by derekargueta** [comment]
Ahhh, you want to write the data of an asynchronous http request/response to the access log. So if I understand correctly, you have a custom filter, in which you have an HTTP client that you're making an asynchronous side request, and you want to log data about *that*.

@zuercher can correct me if I'm wrong, but asynchronous requests is the one exception that doesn't go through the filter stack. The built-in access logging functionality only applies to the main request/response, not asynchronous requests. That's the reason [this ticket](https://github.com/envoyproxy/envoy/issues/8505) was opened - mirrored requests are just asynchronous requests with empty callbacks, but we don't have a way to tie that to the access logs.

You could probably still use the `Common::ImplBase` base class to create a file logger, however unlike my previous recommendations you probably don't want to register it as an "access logger" because when configured as one, it only logs data about the main request, and doesn't know of asynchronous look-aside calls you may do in a filter. The access logs are [called by the HttpConnectionManager](https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc#L559).

This is a bit tricky to implement, but I'm pretty sure it's possible. You'd want to:
1. Have your access logger registered as a singleton (see https://github.com/envoyproxy/envoy/blob/master/source/common/singleton/const_singleton.h#L5 and grep around for use of `ConstSingleton` to see how it's used, as well as `SINGLETON_MANAGER_REGISTRATION`).
2. In your `AsyncClientImpl` you can buffer/flush data to disk. The asynchronous thread launch is built into `AccessLogFileImpl` so you just need to call `write` and the rest is taken care of for you.
3. You can use your filter's configuration protobuf to pass configuration data about your logger.

AFAIK there is no existing implementation of this, so I'm just hypothesizing. In other words, this is uncharted territory you are exploring 🙂

**Comment by ramachaitanyak** [comment]
@derekargueta thanks for the comments. I actually made a bit more progress on this topic. I have indentified couple of ways to do it.

Firstly, there is a different requirement in our infrastructure; where these specific logs are parsed by a different engine compared to the regular envoy access logs. Though this is restricted; I have added an access log field to our custom filter's protobuf by doing this ` import "envoy/config/filter/accesslog/v2/accesslog.proto";`

I do something like this:

```
  auto log_config = config.access_log();
  access_logs_ = AccessLog::AccessLogFactory::fromProto(log_config, context);
```

Now after that I can pass the `AccessLog::InstanceSharedPtr` instance to the interface inheriting from `AsyncClientImpl` and invoke `log` API on this instance during `onSuccess`. Seems clean to me; but let me know your thoughts. This method allows us to configure the new access log (path/format) for our custom filter during deployments.

The other way to do this would be to hard code the the access log file and format during the filter create operation. After which you can acquire the AccessLog::InstanceSharedPtr using `FileAccessLogFactory::createAccessLogInstance()` API.

Once you have the instance you can invoke `log` which takes care of filesystem `write` and `flush` asynchronously while taking care of race conditions.

If you folks feel; there are better ways to handle this, please let me know.

Thanks for the time and interest.
Rama
