### ISSUE TITLE
Network utility function getLocalAddress() doesn't support multiple interfaces and link local IPv6 addresses

### ISSUE THREAD

**Issue by hennna** [envoyproxy/envoy#939]
The network utility function getLocalAddress() (https://github.com/lyft/envoy/blob/master/source/common/network/utility.cc#L136) currently returns the first non-loopback IPv4 interface address. This is done by looping through the linked list returned by getifaddrs (http://man7.org/linux/man-pages/man3/getifaddrs.3.html). This poses two problems when adding IPv6 support:
1. In the case of multiple interfaces, the first non-loopback address may not be the "local" address.
2. getifaddrs doesn't seem to return the link local ipv6 address of some interfaces (em1 on my workstation).

**Comment by hennna** [comment]
For (2), does it make sense to convert from MAC to IPv6 address?
 This conversion seems to work for my workstation but I'm not sure about the general case and if this will change in the future (http://stackoverflow.com/questions/27693120/convert-from-mac-to-ipv6)?

**Comment by mattklein123** [comment]
I discussed this with @htuch offline. The result of this function is used for various things including populating XFF if needed. My feeling is that ultimately we should probably allow the value that this function returns to be alternatively set on the CLI so that operators can do what they want if needed. In light of that, IMO, I would just make it do something somewhat sane in the interim and put in a TODO that something better needs to be done. (Your proposal seems fine to me).

**Comment by dnoe** [comment]
You can't guarantee that a MAC address is used for link-local IPv6
generation in the RFC 4862 way.  RFC 4941 specifies an alternate mechanism
that uses randomized address selection.  We should probably stay away from
assuming RFC 4862 link local addresses exist.

https://tools.ietf.org/html/rfc4941
