### ISSUE TITLE
proposal: api, extend BindConfig to multiple addresses

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#9811]
*Description*:
For certain clusters I want to [bind local ip address when I create an upstream connection](https://github.com/envoyproxy/envoy/blob/ac88316892cd47b6a9b58e3736e20e8863cd0d27/api/envoy/api/v2/cluster.proto#L700).
It worked well but not in ipv4v6 dual stack.

I wish I could have a single cluster config, when I recreate the upstream connection with ipv6 endpoint, cluster impl binds local ipv6 address, and bind ipv4 address for ipv4 endpoint.

I propose to extend BindConfig to contain multiple addresses
Use cases:
1. ipv4 and ipv6 address as above
2. there are other benefits: as tcp reverse proxy local ip:port is not infinite, consider the TIME_WAIT grace period. By providing more ipv4 addresses in config could mitigate.

**Comment by mattklein123** [comment]
At a high level this makes sense to me. @jrajahalme any thoughts on this?

**Comment by jrajahalme** [comment]
Seems reasonable, but the policy for source address selection should be well defined. Address family (v4/v6) is clear enough, but the second case implies multiple addresses of the same family. One solution is to try them in order until a bind succeeds? Since a single bind fail will not be a hard fail anymore, maybe it would be valuable to let the stack pick the address and port in case all the provided addresses fail to bind?

As for the case 2 above, using IP_BIND_ADDRESS_NO_PORT socket option may help:
```
IP_BIND_ADDRESS_NO_PORT (since Linux 4.2)
              Inform the kernel to not reserve an ephemeral port when using
              bind(2) with a port number of 0.  The port will later be auto‐
              matically chosen at connect(2) time, in a way that allows
              sharing a source port as long as the 4-tuple is unique.
```

Also, circumventing TIME_WAIT by resetting the connection in cases where the connection is deemed unhealthy would also help mitigate the case 2.

**Comment by lambdai** [comment]
@jrajahalme Thank you for the feedback!
How about this:
Step 1: update the api to allow specifying collection of addresses, 0 or more address. 
Step 2: Implementation: if the number of address is 0 or 1, fallback to the current behavior. If it contains both ipv4 and ipv6, bind the first ipv4 or ipv6 address depends on the stack.
Step 3: Introduce extra args to guide how multiple addresses could benefit in further use cases.
WDYT?
