### ISSUE TITLE
Websockets and retries

### ISSUE THREAD

**Issue by daniel-bolanos** [envoyproxy/envoy#9961]
Is it possible to configure Envoy to retry a Websocket connection on another backend server when either: 
- the Websocket upgrade fails (for example a 503 is returned instead of a 101)
- the server does not accept the connection

thank you!

**Comment by mattklein123** [comment]
I don't think we support Websocket retries currently, but @alyssawilk would know for sure. She is doing a bunch of work in this area and might be able to get this tracked as a feature addition as needed.

**Comment by alyssawilk** [comment]
I think websockets are treated just as other HTTP requests.  So there's no way to make only websockets retry, but if configured buffer enough of the upgrade request that if you 5xx you could send the upgrade header elsewhere.

**Comment by daniel-bolanos** [comment]
hi @alyssawilk thank you for your response. When you say 
> there's no way to make only websockets retry

Should I understand that it is because the websocket upgrade is just another `GET` request, so it will be treated just the same?

So, if I configure retries for GET, lets say for 503 error codes, will that make Envoy to retry the GET (upgrage request) on a different backend when the first one returns 503 (instead of a 101)?

**Comment by alyssawilk** [comment]
I believe that will work - if it doesn't I'm happy to dig a bit :-)

**Comment by fab-sgnct** [comment]
Sorry to resurrect this old topic. But landing here as I do not observe retries on 503 when having `Connection: Upgrade` and `Upgrade: Websocket` headers in my request.

# My setup
- create a fake app that counts queries and that sends 200 twice and then 503 for 3rd query and following ones (let's consider the endpoint is `/endpoint`)
- have 3 pods running of that service (let's name them A, B and C)
- as I'm on k8s with Istio (1.22.6), I get the default 2 retries on 503s (included in retriable status codes)
- I also have a DestinationRule like this to get some kind of "sticky session" based on query string param:
```
spec:
  host: poc-sample-app.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpQueryParameterName: qsp
```
The idea is that for a given value of qsp, the request is sent to same pod (best effort) as long as readiness does not change

# Test
And then I consider 2 test cases:
- one with regular GET requests
- one with indicated WS upgrade headers

## Case 1: regular GET requests
The test consist in sending curl requests 3 times:
```
curl -si https://mydomain.eu/endpoint?qsp=12345
```

With regular curl requests I get:
- 1st request sent to pod A answering 200 -> final istio gateway response = 200
- 2nd request sent to pod A answering 200 -> final istio gateway response = 200
- 3rd request sent to pod A, answering 503. Then sent to pod B, answering 200 -> final istio gateway response = 200

At this point we can see we get a retry on 503 as expected. Continuing with more requests we could end on 6th request with 503s from pod A, then B and 200 from pod C. Only from 7th request we would get 503 as final istio gateway response.
We always tried pod A first because of the DestinationRule but it didn't prevent retrying on pod B if pod A answers 503.

## Case 2: Fake WS upgrade requests.
Restart pods (to reset counters) and repeat the above but with the following curl request each time:
```
curl -si https://mydomain.eu/endpoint?qsp=12345 H "Connection: Upgrade" -H "Upgrade: Websocket"
```

This is then what I observe:
- 1st request sent to pod A answering 200 -> final istio gateway response = 200
- 2nd request sent to pod A answering 200 -> final istio gateway response = 200
- 3rd request sent to pod A, answering 503 -> final istio gateway response = 503

So we can see here we do not have the retry on 503 as expected anymore. This is the same app answering the API (without WS support, simply answering HTTP requests with 200 or 503) and same setup, the only change is on headers sent by curl request.

# Conclusion

Looking around for existing similar issue I landed on this github issue and think it is the same topic: there is no retry when the HTTP GET has the WS upgrade headers. @alyssawilk FYI if you are still working on this.

**Comment by garrettheel** [comment]
+1 on this feature being helpful for dealing with issues on initial websocket connect

I looked into this a little and the problem looks to be that the upgrade response is handled differently in the codec filter:

https://github.com/envoyproxy/envoy/blob/1a46b232d646f3b251782fb297fbed88eb9a18bb/source/common/router/upstream_codec_filter.cc#L169-L184

Any non 101 response leads to us erroring early, so we never reach the router filter where we'd retry.

**Comment by fab-sgnct** [comment]
Should we reopen this issue?

**Comment by fab-sgnct** [comment]
Note: in [Istio gateway helm chart](https://artifacthub.io/packages/helm/istio-official/gateway) values, you will need to add something like:

```
  podAnnotations:
    proxy.istio.io/config: |
      runtimeValues:
        envoy.reloadable_features.check_switch_protocol_websocket_handshake: "false"
```

to get this setting applied to all gateways (And persisted. Indeed the previous example using 'curl' only dynamically changes the live runtime value).

**Comment by gheel-figma** [comment]
> [Here is the commit](https://github.com/envoyproxy/envoy/commit/76b5c920cf30297e118dc0d25f647796623407d5) that introduced that change. It added [the following lines](https://github.com/envoyproxy/envoy/commit/76b5c920cf30297e118dc0d25f647796623407d5#diff-6f9c718224c533c13c2c0ba1d5abaab86be9d0cc73808749c77934e9f9b0d5d0R149-R153) to the changelog:
> 
> - area: websocket
>   change: |
>     Only 101 is considered a successful response for websocket handshake for HTTP/1.1, and Envoy as a proxy will proxy the response
>     header from upstream to downstream and then close the request if other status is received. This behavior can be
>     reverted by ``envoy_reloadable_features_check_switch_protocol_websocket_handshake``.
> And I indeed tried to set this on my k8s cluster ingress gateway like this:
> 
> kubectl -n istio-system exec -it istio-ingressgateway-5b786887b9-hmbwf -c istio-proxy -- curl -X POST http://localhost:15000/runtime_modify?envoy.reloadable_features.check_switch_protocol_websocket_handshake=false
> And then I could get proper retries on WS.
> 
> Now about the reason of this change is fixing [this vulnerability](https://github.com/envoyproxy/envoy/security/advisories/GHSA-vcf8-7238-v74c) that anyone willing to change this setting should consider first.

Note that https://github.com/envoyproxy/envoy/pull/39159 removes this feature flag, so will cease to work from v1.35.0 onwards

**Comment by botengyao** [comment]
I am fine to add a new runtime knob to unblock this use case.
